In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print(os.listdir(base))

['notebooks', 'data']

In [ ]:
!pip install -q catboost lightgbm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.5 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import numpy as np
import sklearn
import xgboost
import catboost
import lightgbm

print("✅ ML environment ready!")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)
print("XGBoost:", xgboost.__version__)
print("CatBoost:", catboost.__version__)
print("LightGBM:", lightgbm.__version__)

✅ ML environment ready!
Pandas: 2.2.3
NumPy: 2.1.3
Scikit-learn: 1.6.1
XGBoost: 3.4.1
CatBoost: 1.2.10
LightGBM: 4.6.0

In [ ]:
import zipfile
import os

zip_path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/data/6ab10eb3b23ba_student_resource.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    files = z.namelist()

print("Number of files:", len(files))
print("\nFiles inside the ZIP:\n")

for f in files:
    print(f)

Number of files: 34

Files inside the ZIP:

student_resource/
__MACOSX/._student_resource
student_resource/Documentation_template.md
__MACOSX/student_resource/._Documentation_template.md
student_resource/.DS_Store
__MACOSX/student_resource/._.DS_Store
student_resource/dataset/
__MACOSX/student_resource/._dataset
student_resource/utils/
__MACOSX/student_resource/._utils
student_resource/README.md
__MACOSX/student_resource/._README.md
student_resource/dataset/.DS_Store
__MACOSX/student_resource/dataset/._.DS_Store
student_resource/dataset/test/
__MACOSX/student_resource/dataset/._test
student_resource/dataset/train/
__MACOSX/student_resource/dataset/._train
student_resource/utils/validate_submission.py
__MACOSX/student_resource/utils/._validate_submission.py
student_resource/dataset/test/test_source2.tsv
__MACOSX/student_resource/dataset/test/._test_source2.tsv
student_resource/dataset/test/test_source3.tsv
__MACOSX/student_resource/dataset/test/._test_source3.tsv
student_resource/dataset/test/test_source1.tsv
__MACOSX/student_resource/dataset/test/._test_source1.tsv
student_resource/dataset/train/train_ground_truth.tsv
__MACOSX/student_resource/dataset/train/._train_ground_truth.tsv
student_resource/dataset/train/train_source2.tsv
__MACOSX/student_resource/dataset/train/._train_source2.tsv
student_resource/dataset/train/train_source3.tsv
__MACOSX/student_resource/dataset/train/._train_source3.tsv
student_resource/dataset/train/train_source1.tsv
__MACOSX/student_resource/dataset/train/._train_source1.tsv

In [ ]:
import zipfile

zip_path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/data/6ab10eb3b23ba_student_resource.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    print("Important dataset files:\n")

    for info in z.infolist():
        name = info.filename

        if (
            "dataset/train/" in name or
            "dataset/test/" in name
        ) and name.endswith(".tsv"):

            size_mb = info.file_size / (1024 ** 2)
            compressed_mb = info.compress_size / (1024 ** 2)

            print(f"{name}")
            print(f"  Uncompressed: {size_mb:.2f} MB")
            print(f"  Compressed:   {compressed_mb:.2f} MB")
            print()

Important dataset files:

student_resource/dataset/test/test_source2.tsv
  Uncompressed: 485.86 MB
  Compressed:   212.77 MB

__MACOSX/student_resource/dataset/test/._test_source2.tsv
  Uncompressed: 0.00 MB
  Compressed:   0.00 MB

student_resource/dataset/test/test_source3.tsv
  Uncompressed: 482.56 MB
  Compressed:   208.23 MB

__MACOSX/student_resource/dataset/test/._test_source3.tsv
  Uncompressed: 0.00 MB
  Compressed:   0.00 MB

student_resource/dataset/test/test_source1.tsv
  Uncompressed: 166.91 MB
  Compressed:   66.44 MB

__MACOSX/student_resource/dataset/test/._test_source1.tsv
  Uncompressed: 0.00 MB
  Compressed:   0.00 MB

student_resource/dataset/train/train_ground_truth.tsv
  Uncompressed: 121.13 MB
  Compressed:   52.10 MB

__MACOSX/student_resource/dataset/train/._train_ground_truth.tsv
  Uncompressed: 0.00 MB
  Compressed:   0.00 MB

student_resource/dataset/train/train_source2.tsv
  Uncompressed: 466.63 MB
  Compressed:   210.92 MB

__MACOSX/student_resource/dataset/train/._train_source2.tsv
  Uncompressed: 0.00 MB
  Compressed:   0.00 MB

student_resource/dataset/train/train_source3.tsv
  Uncompressed: 480.37 MB
  Compressed:   211.04 MB

__MACOSX/student_resource/dataset/train/._train_source3.tsv
  Uncompressed: 0.00 MB
  Compressed:   0.00 MB

student_resource/dataset/train/train_source1.tsv
  Uncompressed: 200.34 MB
  Compressed:   82.58 MB

__MACOSX/student_resource/dataset/train/._train_source1.tsv
  Uncompressed: 0.00 MB
  Compressed:   0.00 MB

In [ ]:
import os

data_folder = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/data"

print("Files in data folder:\n")

for file in os.listdir(data_folder):
    print(repr(file))

Files in data folder:

'6ab10eb3b23ba_student_resource.zip'

In [ ]:
import zipfile
import os

zip_path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/data/6ab10eb3b23ba_student_resource.zip"
extract_path = "/content/amazon_ml_challenge"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as z:
    for member in z.infolist():
        # Ignore macOS metadata files
        if "__MACOSX" in member.filename or "/._" in member.filename:
            continue

        z.extract(member, extract_path)

print("✅ Extraction completed!")
print("Location:", extract_path)

✅ Extraction completed!
Location: /content/amazon_ml_challenge

In [ ]:
import pandas as pd
import os

base = "/content/amazon_ml_challenge/student_resource/dataset"

files = [
    "train/train_source1.tsv",
    "train/train_source2.tsv",
    "train/train_source3.tsv",
    "train/train_ground_truth.tsv"
]

for f in files:
    path = os.path.join(base, f)
    df = pd.read_csv(path, sep="\t", nrows=5)

    print("\n" + "="*70)
    print(f)
    print("Columns:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df)

======================================================================
train/train_source1.tsv
Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

======================================================================
train/train_source2.tsv
Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

======================================================================
train/train_source3.tsv
Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

======================================================================
train/train_ground_truth.tsv
Columns:
['source1_entity_id', 'matched_entity_ids']

First 5 rows:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [ ]:
import os
import pandas as pd

base = "/content/amazon_ml_challenge/student_resource/dataset"

# --------------------------------------------------
# 1. Count rows in every dataset
# --------------------------------------------------

files = [
    "train/train_source1.tsv",
    "train/train_source2.tsv",
    "train/train_source3.tsv",
    "train/train_ground_truth.tsv",
    "test/test_source1.tsv",
    "test/test_source2.tsv",
    "test/test_source3.tsv"
]

print("ROW COUNTS")
print("=" * 60)

for f in files:
    path = os.path.join(base, f)

    with open(path, "rb") as file:
        rows = sum(1 for _ in file) - 1

    print(f"{f:<35} {rows:,}")

ROW COUNTS
============================================================
train/train_source1.tsv             2,206,821
train/train_source2.tsv             5,034,616
train/train_source3.tsv             5,285,603
train/train_ground_truth.tsv        2,206,821
test/test_source1.tsv               1,732,544
test/test_source2.tsv               4,887,273
test/test_source3.tsv               5,082,316

In [ ]:
# --------------------------------------------------
# 2. Inspect TEST columns
# --------------------------------------------------

test_files = [
    "test/test_source1.tsv",
    "test/test_source2.tsv",
    "test/test_source3.tsv"
]

for f in test_files:
    path = os.path.join(base, f)

    df = pd.read_csv(path, sep="\t", nrows=5)

    print("\n" + "=" * 70)
    print(f)
    print("Columns:", df.columns.tolist())
    display(df)

======================================================================
test/test_source1.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France

======================================================================
test/test_source2.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US

======================================================================
test/test_source3.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India

In [ ]:
# --------------------------------------------------
# 3. Understand ground-truth matching structure
# --------------------------------------------------

gt_path = os.path.join(base, "train/train_ground_truth.tsv")

gt = pd.read_csv(gt_path, sep="\t")

print("Ground truth rows:", len(gt))
print("\nColumns:")
print(gt.columns.tolist())

# Number of matched entities for each Source 1 record
match_counts = gt["matched_entity_ids"].fillna("").apply(
    lambda x: len([v for v in x.split(",") if v.strip()])
)

print("\nNumber of matches per Source 1 record:")
print(match_counts.value_counts().sort_index())

print("\nAverage matches:", match_counts.mean())
print("Maximum matches:", match_counts.max())

print("\nExamples:")
display(gt.head(10))

Ground truth rows: 2206821

Columns:
['source1_entity_id', 'matched_entity_ids']

Number of matches per Source 1 record:
matched_entity_ids
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

Average matches: 3.4612526344456573
Maximum matches: 11

Examples:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [ ]:
print("Total ground truth rows:", len(gt))

print("\nDistribution:")
dist = match_counts.value_counts().sort_index()
print(dist)

print("\nSum of distribution:", dist.sum())

print("\nAverage matches:", match_counts.mean())
print("Minimum:", match_counts.min())
print("Maximum:", match_counts.max())

print("\nPercentage with ZERO matches:",
      (match_counts == 0).mean() * 100)

print("Percentage with ONE match:",
      (match_counts == 1).mean() * 100)

print("Percentage with 2+ matches:",
      (match_counts >= 2).mean() * 100)

Total ground truth rows: 2206821

Distribution:
matched_entity_ids
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

Sum of distribution: 2206821

Average matches: 3.4612526344456573
Minimum: 0
Maximum: 11

Percentage with ZERO matches: 5.584820880352326
Percentage with ONE match: 5.399486410542586
Percentage with 2+ matches: 89.01569270910508

In [ ]:
import pandas as pd
import os
from collections import Counter

base = "/content/amazon_ml_challenge/student_resource/dataset"

source_files = [
    "train/train_source1.tsv",
    "train/train_source2.tsv",
    "train/train_source3.tsv"
]

for file in source_files:

    path = os.path.join(base, file)

    total = 0
    missing_name = 0
    missing_address = 0
    missing_country = 0

    country_counts = Counter()
    name_counts = Counter()
    address_counts = Counter()

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name", "business_address", "country"],
        chunksize=200_000
    ):

        total += len(chunk)

        missing_name += chunk["business_name"].isna().sum()
        missing_address += chunk["business_address"].isna().sum()
        missing_country += chunk["country"].isna().sum()

        country_counts.update(
            chunk["country"].dropna().astype(str)
        )

        # Only count non-empty names/addresses
        names = chunk["business_name"].dropna().astype(str).str.strip()
        addresses = chunk["business_address"].dropna().astype(str).str.strip()

        name_counts.update(names)
        address_counts.update(addresses)

    print("\n" + "=" * 70)
    print(file)

    print("Total rows:", f"{total:,}")

    print("\nMissing values:")
    print("Business name :", f"{missing_name:,}",
          f"({missing_name / total * 100:.2f}%)")

    print("Business address:", f"{missing_address:,}",
          f"({missing_address / total * 100:.2f}%)")

    print("Country:", f"{missing_country:,}",
          f"({missing_country / total * 100:.2f}%)")

    print("\nTop countries:")
    for country, count in country_counts.most_common(15):
        print(f"{country}: {count:,}")

    print("\nTop duplicate business names:")
    for name, count in name_counts.most_common(10):
        if count > 1:
            print(f"{name} -> {count:,}")

    print("\nTop duplicate addresses:")
    for address, count in address_counts.most_common(10):
        if count > 1:
            print(f"{address} -> {count:,}")

======================================================================
train/train_source1.tsv
Total rows: 2,206,821

Missing values:
Business name : 0 (0.00%)
Business address: 0 (0.00%)
Country: 0 (0.00%)

Top countries:
US: 1,323,633
India: 883,188

Top duplicate business names:
Primary Care Group -> 253
Ear Nose & Throat Group -> 251
Pediatric Group -> 222
Womens Health Group -> 220
Physical Therapy Group -> 218
Pediatric Dental Group -> 216
Behavioral Health Group -> 215
Chiropractic Group -> 209
Orthopedic Group -> 208
Eye Group -> 207

Top duplicate addresses:
108 Norle Street, College Twp, PA -> 14
104 Roadrunner Circle, Elephant Butte, NM -> 13
218 Phillips Street, Storm Lake, IA -> 13
43 Franklin Street, Delaware, OH -> 13
55, Lavkush Vihar, Singhpur, Kachhar Bithoor Road, Kalyanpur, Kanpur Nagar, Uttar Pradesh -> 13
1921 Willow Park Drive, Fort Worth, TX -> 13
43233 Clearnight Terrace, Loudoun County, VA -> 12
4804 Gardenia Avenue, Glendale, AZ -> 12
H. No. 154 - A, Veer Savarkar Nagar, Mini Bypass Road, P/O Izzatnagar, Bareilly, Uttar Pradesh -> 12
No. 109, Ferns Meadows, Avalahalli Main Road, Bileshivale, Bangalore North, Bangalore, Karnataka -> 12

======================================================================
train/train_source2.tsv
Total rows: 5,034,616

Missing values:
Business name : 2 (0.00%)
Business address: 168,967 (3.36%)
Country: 0 (0.00%)

Top countries:
US: 3,016,817
India: 2,017,799

Top duplicate business names:
Primary Care -> 320
Physical Therapy -> 307
Urgent Care -> 297
Womens Health -> 297
Behavioral Health -> 296
Internal Medicine -> 288
Pediatric Dentistry -> 274
earnosethroat.com -> 269
Pediatric Dental -> 268
Ear Nose & Throat -> 220

Top duplicate addresses:
842 38, CALEDONAI TOWNSHIP, WI -> 18
1948 WEAVER FOREST WAY, MORRISVILLE, NC -> 18
66 FRANK EDGE, ALTO, TX -> 17
G-58/1, BENSON CROSS ROAD, BANGALORE., Karnataka -> 16
302 REGENCY CT, AMES, IA -> 16
##1105 M, NULL, BIRMINGHAM, AL -> 16
55 500, SALT LAKE CITY, UT -> 16
17200 BELL RD, SURPRISE, AZ -> 15
06252 TALIAFERRO WAY, ALEANDRIA, VA -> 15
2782 330, BURNET, TX -> 15

======================================================================
train/train_source3.tsv
Total rows: 5,285,603

Missing values:
Business name : 13 (0.00%)
Business address: 175,916 (3.33%)
Country: 0 (0.00%)

Top countries:
US: 3,170,056
India: 2,115,547

Top duplicate business names:
Primary Care -> 421
Physical Therapy -> 399
Pediatric Dental -> 393
Womens Health -> 379
Urgent Care -> 377
Pediatric Dentistry -> 361
Behavioral Health -> 330
Pediatric -> 321
Internal Medicine -> 319
The Dent -> 254

Top duplicate addresses:
Ground Floor, Bangalore, KA -> 29
Floor, Mumbai, MH -> 26
18, Kolkata, Howrah, WB -> 26
303, Mumbai, MH -> 25
12, Ahmedabad, GJ -> 23
101, Mumbai, Mumbai City, MH -> 23
4, Mumbai, MH -> 23
Floor, Bangalore, KA -> 22
7, Kolkata, Howrah, WB -> 21
5, Ahmedabad, GJ -> 21

In [ ]:
import pandas as pd
import os

base = "/content/amazon_ml_challenge/student_resource/dataset"

gt_path = os.path.join(base, "train/train_ground_truth.tsv")

gt = pd.read_csv(gt_path, sep="\t")

print("Ground truth loaded!")
print("Rows:", len(gt))
print("Columns:", gt.columns.tolist())

Ground truth loaded!
Rows: 2206821
Columns: ['source1_entity_id', 'matched_entity_ids']

In [ ]:
gt_sample = gt.sample(10, random_state=42).copy()

display(gt_sample)

        source1_entity_id                                 matched_entity_ids
2195840      S1-384734976  S2-685146894,S2-908470079,S3-109845102,S3-1764...
1487051      S1-574038342             S2-133116927,S2-180265553,S2-201976425
1878277      S1-189408085                                                NaN
993966       S1-797774718                          S2-151469064,S3-994706509
565428       S1-729164458             S2-619382517,S2-949886625,S3-532795614
1645753      S1-102324451             S2-626433724,S3-583628765,S3-900962957
1165724      S1-897032402  S2-119959444,S2-737316263,S2-487624450,S2-4866...
363842       S1-345344463                          S2-731601561,S3-474125535
962445       S1-281641466                          S2-559704787,S3-772912089
964820       S1-608038725  S2-895472957,S2-192681436,S2-217803628,S3-9935...

In [ ]:
s1_ids = set(gt_sample["source1_entity_id"])

s2_ids = set()
s3_ids = set()

for value in gt_sample["matched_entity_ids"].fillna(""):
    for entity_id in value.split(","):
        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            s2_ids.add(entity_id)
        elif entity_id.startswith("S3-"):
            s3_ids.add(entity_id)

print("Source 1 IDs:", len(s1_ids))
print("Source 2 IDs:", len(s2_ids))
print("Source 3 IDs:", len(s3_ids))

Source 1 IDs: 10
Source 2 IDs: 18
Source 3 IDs: 11

In [ ]:
def retrieve_records(path, wanted_ids, chunksize=200_000):

    wanted_ids = set(wanted_ids)
    results = []

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=chunksize
    ):

        found = chunk[chunk["entity_id"].isin(wanted_ids)]

        if len(found) > 0:
            results.append(found)

            wanted_ids -= set(found["entity_id"])

        if not wanted_ids:
            break

    if results:
        return pd.concat(results, ignore_index=True)

    return pd.DataFrame(columns=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ])


s1_path = os.path.join(base, "train/train_source1.tsv")
s2_path = os.path.join(base, "train/train_source2.tsv")
s3_path = os.path.join(base, "train/train_source3.tsv")

s1_records = retrieve_records(s1_path, s1_ids)
s2_records = retrieve_records(s2_path, s2_ids)
s3_records = retrieve_records(s3_path, s3_ids)

print("Retrieved:")
print("S1:", len(s1_records))
print("S2:", len(s2_records))
print("S3:", len(s3_records))

Retrieved:
S1: 10
S2: 18
S3: 11

In [ ]:
print("========== SOURCE 1 ==========")
display(s1_records)

print("========== SOURCE 2 ==========")
display(s2_records)

print("========== SOURCE 3 ==========")
display(s3_records)

========== SOURCE 1 ==========

,entity_id,business_name,business_address,country
0,S1-608038725,Anchor Staking Inc,"2330 Central Avenue, Kansas City, KS",US
1,S1-281641466,Life Construction Private Limited,"House No- 24/153, 3Rd Floor Blk-24, Delhi, Nor...",India
2,S1-574038342,Innovative Consultants,"15 16 Indrapuri Madhubancolony Karvenagar, Pun...",India
3,S1-189408085,Chiropractic Care,"1731 21st Avenue, Unit A, Nashville, TN",US
4,S1-897032402,Reet Exports (India) Private Limited,"Vill-Belpukur, P.O. Balarampur, Berhampore, Mu...",India
5,S1-345344463,Brightium Lithium LLC,"Magnolia, DE, 3435 Irish Hill Road",US
6,S1-102324451,"Golden Classic Fox, LLC","4484 Westwood Drive, West Des Moines, IA",US
7,S1-729164458,"Bishop, Melton and Schmidt Foods","Hampton City, VA, 234 Summit Court",US
8,S1-384734976,"FQ Social, Inc","1212 Old Rte 34, Sandwich, IL",US
9,S1-797774718,Hyderabad-500060 Kumar Private Limited,"9-14, Hari Krishna Building, 2Nd Fl Dilsukhnag...",India

========== SOURCE 2 ==========

,entity_id,business_name,business_address,country
0,S2-192681436,anchor staking inc,"2330 CETRAL AVENUE, KANSAS CITY, KS",US
1,S2-685146894,"FQ Social, Inc.","1212 OLD RTE 34, SANDWICH, IL",US
2,S2-908470079,"FQ Social, #42836","1212 OLD RTE 34, SANDWICH, IL",US
3,S2-151469064,Hyderabad-500060 Kumar,"G-9-14, HARI KRISHNA BUILDING, 2ND FL DILSUKHN...",India
4,S2-559704787,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,"HOUSE NO- 24/153, DELHI, NORTH DELHI, Delhi",India
5,S2-895472957,Anchor Stáking Inc,"CENTRAL AVE, KANSAS CITY, KS",US
6,S2-486627040,reetexportsindia.com,"VILL-BELPUKUR, P.O. BALARAMPUR, BERHAMPORE, MU...",India
7,S2-217803628,ANCHOR STAKIFNG INC,"2330 CENTRAL AVE, KANSAS CITY, KS",US
8,S2-626433724,GOLDEN CLASSIC LLC PARTNERS,"IA, WEST DES MOINES, 4484D WESTWOOD DRIVE",US
9,S2-949886625,"Bishop, Melton and Schmidt Foods Inc","234-236 SUMMIT COURT, HAAMPTON, VA",US
10,S2-487624450,Reet Exports(India) Private Limited,"VILL-BELPUKUR, P.O. BALAMAMPUR, BERHAMPORE, MU...",India
11,S2-619382517,"Bishop, Melton and Schmidt Foods [LP]","SUMMIT CT, HAAMPTON, VA",US
12,S2-201976425,Innovative Consultants,"#B3/15 16 INDRAPURI MADHUBANCOLONY KARVENAGAR,...",India
13,S2-731601561,brightium lithium llc,"3435 IRISH HILL RD, MAGNOLIA, DE",US
14,S2-180265553,Innovative Consultants,NaN,India
15,S2-737316263,Reet Exports (India) Limited Services | www.re...,"West Bengal, VILL-BELPUKUR, P.O. BALARAMPUR, B...",India
16,S2-119959444,Reet Exports (India) Private Limited,"West Bengal, VILL-BELPUKUR, P.O. BALARAMPUR, B...",India
17,S2-133116927,इनोवेटिव कंसल्टेंट्स,H.NO B3/15 16 INDRAPURI MADHUBANCOLONY KARVENA...,India

========== SOURCE 3 ==========

,entity_id,business_name,business_address,country
0,S3-583628765,Golden Classic Fox LLC,"4484- Westwood Drive, West Des Moines, Iowa",US
1,S3-993567829,Anchorstaking.Com,"#2330 Central Ave, Kansas City, Kansas",US
2,S3-900962957,"Golden Fox, LLC Center","4484- Westwood Dr, West Des Moines, Iowa",US
3,S3-772912089,Shri Life Construction Private,"House No- 24/153, 3Rd Floor Blk-24, Delhi, Nor...",India
4,S3-109845102,"FQ Social, Ínc","1212 Old Rte 34, Sandwich, Illinois",US
5,S3-39651561,Reet Éxports (India) Private Limited,"Vill-belpukur, Murshidabad, WB",India
6,S3-994706509,Hyderabad-500060 Kumar Private Límited,"9-14, Hari Krishna Building, 2Nd Fl Dilsukhnag...",India
7,S3-532795614,"Bishop, Melton And Schmidt Foods","34 Summit Ct, Hampton, Virginia",US
8,S3-176459320,"Arcxylo DBA FQ Social, Inc","1212 Old Rte 34, Sandwich, IL",US
9,S3-474125535,Brightium (Lithium),"3435 Irish Hill Road, NULL, Magnolia, Delaware",US
10,S3-705433982,Reet (lndia) Exports Private [Limited],"Vill-belpukur, P.o. Balarampur, Berhampore, Mu...",India

In [ ]:
import os

base = "/content/amazon_ml_challenge/student_resource"

validator = os.path.join(base, "utils/validate_submission.py")

print("=" * 80)
print("VALIDATOR")
print("=" * 80)

with open(validator, "r", encoding="utf-8") as f:
    text = f.read()

print(text[:15000])

================================================================================
VALIDATOR
================================================================================
#!/usr/bin/env python3
"""
ML Challenge 2026 — Submission Validator

Run this BEFORE submitting. It checks your output files against every formatting
rule the scorer enforces, so you can catch a rejection locally instead of burning
a submission. It reads only your output files and the test source files (to learn
which S1 entities are required and which S2/S3 IDs exist); it never needs the
ground truth and never computes your score.

It validates two files:

* ``matching_results.tsv`` (required) — your final matches, the file scored on the
  leaderboard.
* ``candidate_pairs.tsv`` (optional) — the candidate set from your blocking stage.
  When present, the validator also checks that your final matches are a subset of
  your candidates and *warns* (never fails) otherwise. When absent it is skipped
  with a warning; it is still expected in your final submission zip.

Stdlib only, Python 3.8+. Run from the ``student_resource/`` directory::

    python3 utils/validate_submission.py \
        --matching output/matching_results.tsv \
        --candidate output/candidate_pairs.tsv \
        --test-dir dataset/test

Exit code 0 means the files are safe to submit; 1 means fix the listed issues
(warnings never fail the run).

ID-existence check (off by default). By default the validator does NOT check that
every matched/candidate ID actually exists in the test set: that check loads all
Source-2/3 IDs into memory, which on the full ~1.7M-entity test set costs a few GB
(more when ``candidate_pairs.tsv`` is included). The default run therefore stays fast
and light and verifies every other rule; it prints a warning noting the check was
skipped. Pass ``--check-ids`` to turn it on (it reads ``test_source2.tsv`` /
``test_source3.tsv`` from ``--test-dir``); a missing/garbage matched ID only lowers
your score rather than being rejected by the scorer, so this check is a diagnostic,
not a gate. If ``--check-ids`` runs out of memory, drop ``--candidate`` (the candidate
cross-check is the biggest memory user, and the matching file is the only one scored).
"""

import argparse
import os
import sys

DELIM = "\t"
MAX_EXAMPLES = 5  # how many offending IDs to show per issue
MATCHING_HEADER = ["source1_entity_id", "matched_entity_ids"]
CANDIDATE_HEADER = ["source1_entity_id", "candidate_entity_ids"]


def read_ids(path):
    """Return the set of first-column entity IDs from a source TSV.

    The header row is skipped and blank lines are ignored.
    """
    with open(path, encoding="utf-8") as f:
        next(f, None)  # skip header
        return {line.split(DELIM, 1)[0].strip() for line in f if line.strip()}


def examples(items):
    """Return a short, human-readable sample of ``items`` for an error message."""
    items = sorted(items)
    shown = ", ".join(items[:MAX_EXAMPLES])
    if len(items) > MAX_EXAMPLES:
        return f"{len(items)} total, e.g. {shown}, ..."
    return shown


def load_match_targets(test_dir, warnings):
    """Return the set of valid S2/S3 match IDs, or ``None`` if unavailable.

    Only called when ``--check-ids`` is on. When ``test_source2.tsv`` or
    ``test_source3.tsv`` is missing we cannot check that matched IDs exist, so we
    record a warning and return ``None`` to signal that the existence check should be
    skipped.
    """
    targets = set()
    for name in ("test_source2.tsv", "test_source3.tsv"):
        path = os.path.join(test_dir, name)
        if not os.path.isfile(path):
            warnings.append(
                f"{path} not found — skipping the (optional) check that matched "
                f"IDs exist in the test set. Every other rule is still checked. "
                f"This is the lighter-memory mode; provide test_source2/3.tsv to "
                f"enable the ID-existence check."
            )
            return None
        targets |= read_ids(path)
    return targets


def validate_id_list_file(path, expected_header, col_label, required, valid_ids, errors):
    """Validate one results-style TSV (matching or candidate).

    Applies the shared formatting rules and appends any problems to ``errors``.
    Returns a ``{source1_id: set(matched/candidate ids)}`` mapping, or ``None`` on a
    fatal problem (missing file, empty file, or a broken header) that stops parsing.
    """
    if not os.path.isfile(path):
        errors.append(f"File not found: {path}")
        return None

    name = os.path.basename(path)
    mapping = {}
    seen, dup_rows, intra_dupes = set(), set(), set()
    self_matches, wrong_prefix, unknown = set(), set(), set()
    n_rows = empties = 0

    with open(path, encoding="utf-8") as f:
        header = f.readline()
        if not header:
            errors.append(f"{name} is empty.")
            return None
        if DELIM not in header and "," in header:  # the #1 mistake: a CSV
            errors.append(
                f"{name}: header has no TAB but contains commas — the file looks "
                "COMMA-separated. Submissions must be TAB-separated (.tsv); "
                "write it with df.to_csv(sep='\\t', index=False)."
            )
            return None
        cols = [c.strip().lower() for c in header.rstrip("\n").split(DELIM)]
        if cols != expected_header:
            errors.append(
                f"{name}: unexpected header {cols}. "
                f"Expected exactly {expected_header} (tab-separated)."
            )
            return None

        for line_num, line in enumerate(f, start=2):
            s1, tab, rest = line.partition(DELIM)
            if not tab:
                if s1.strip():
                    errors.append(
                        f"{name}: malformed row (no tab) at line {line_num}: "
                        f"{line.rstrip()!r}"
                    )
                continue

            n_rows += 1
            if s1 in seen:
                dup_rows.add(s1)
            seen.add(s1)

            ids = rest.rstrip("\n").split(",") if rest.strip() else []
            if not ids:
                empties += 1
                mapping[s1] = set()
                continue
            if len(ids) != len(set(ids)):
                intra_dupes.add(s1)
            id_set = set(ids)
            mapping[s1] = id_set
            for mid in id_set:
                if mid.startswith("S1-"):
                    self_matches.add(mid)
                elif not mid.startswith(("S2-", "S3-")):
                    wrong_prefix.add(mid)
                elif valid_ids is not None and mid not in valid_ids:
                    unknown.add(mid)

    # Aggregate the per-category findings. Each entry is (offenders, message);
    # only non-empty categories become errors.
    findings = [
        (
            dup_rows,
            "{name}: duplicate source1_entity_id row(s): {ex}. "
            "Each S1 entity may appear on only one row.",
        ),
        (
            intra_dupes,
            "{name}: repeated ID inside a {col} list for: {ex}. "
            "No duplicate IDs are allowed within a list.",
        ),
        (
            self_matches,
            "{name}: {col} contains Source-1 IDs (self-matches): {ex}. "
            "Only S2-/S3- IDs are allowed.",
        ),
        (
            wrong_prefix,
            "{name}: {col} contains IDs without an S2-/S3- prefix: {ex}.",
        ),
        (
            unknown,
            "{name}: {col} references IDs not in the test "
            "Source-2/3 files: {ex}.",
        ),
        (
            required - seen,
            "{name}: required S1 entity(ies) missing: {ex}. "
            "Every entity in test_source1.tsv needs a row (empty = no match).",
        ),
        (
            seen - required,
            "{name}: row(s) using an S1 ID that is not in the test set: {ex}.",
        ),
    ]
    for offenders, message in findings:
        if offenders:
            errors.append(message.format(name=name, ex=examples(offenders), col=col_label))

    print(f"  {name}: {n_rows} rows ({empties} empty, {n_rows - empties} non-empty).")
    return mapping


def validate(matching_path, candidate_path, test_dir, check_ids=False):
    """Validate the submission output(s); return ``(errors, warnings)`` lists.

    ``check_ids`` (``--check-ids``) turns on the optional, memory-heavy check that
    every matched/candidate ID exists in the test Source-2/3 files. It is off by
    default so the common run stays fast and light.
    """
    errors, warnings = [], []

    source1 = os.path.join(test_dir, "test_source1.tsv")
    if not os.path.isfile(source1):
        errors.append(f"Test source1 file not found: {source1} (check --test-dir).")
        return errors, warnings
    required = read_ids(source1)
    print(f"  required S1 entities: {len(required)}")

    if check_ids:
        valid_ids = load_match_targets(test_dir, warnings)
        if valid_ids is not None:
            print(f"  valid S2/S3 match IDs: {len(valid_ids)}")
    else:
        valid_ids = None
        warnings.append(
            "ID-existence check is OFF (the default) — not checking that matched/"
            "candidate IDs exist in the test set. Every other rule is still checked. "
            "Re-run with --check-ids to enable it (needs test_source2/3.tsv; uses "
            "more memory). A nonexistent ID only lowers your score, never rejects "
            "your submission."
        )

    matched = validate_id_list_file(
        matching_path, MATCHING_HEADER, "matched_entity_ids", required, valid_ids, errors
    )

    # candidate_pairs.tsv is optional: if it's absent we skip its checks with a
    # warning (it's still expected in your final submission zip). A missing
    # candidate file never fails this run on its own.
    candidate = None
    if candidate_path and os.path.isfile(candidate_path):
        candidate = validate_id_list_file(
            candidate_path, CANDIDATE_HEADER, "candidate_entity_ids",
            required, valid_ids, errors,
        )
    elif candidate_path:
        warnings.append(
            f"{candidate_path} not found — skipping candidate_pairs.tsv checks. "
            "It is optional here, but your final submission zip must include "
            "output/candidate_pairs.tsv."
        )

    # Soft check: your final matches should come from your blocking candidates.
    # A matched ID absent from candidate_pairs.tsv usually means a pipeline bug,
    # so we warn but never fail on it.
    if matched is not None and candidate is not None:
        offenders = {
            s1 for s1, mids in matched.items() if mids - candidate.get(s1, set())
        }
        if offenders:
            warnings.append(
                f"{len(offenders)} S1 entity(ies) have matched IDs not present in "
                f"candidate_pairs.tsv, e.g. {examples(offenders)}. Final matches "
                "normally come from your blocking candidates — double-check these."
            )

    return errors, warnings


def main():
    parser = argparse.ArgumentParser(
        description="Validate ML Challenge 2026 submission output files before submitting."
    )
    parser.add_argument(
        "--matching",
        "-m",
        default="output/matching_results.tsv",
        help="Path to matching_results.tsv (default: %(default)s)",
    )
    parser.add_argument(
        "--candidate",
        "-c",
        default=None,
        help="Path to candidate_pairs.tsv "
        "(default: output/candidate_pairs.tsv if it exists).",
    )
    parser.add_argument(
        "--test-dir",
        "-t",
        default="dataset/test",
        help="Folder with test_source1/2/3.tsv (default: %(default)s). "
        "test_source2/3.tsv are only read when --check-ids is given.",
    )
    parser.add_argument(
        "--check-ids",
        action="store_true",
        help="Also check that every matched/candidate ID exists in the test "
        "Source-2/3 files. Off by default (loads all S2/S3 IDs into memory — a few "
        "GB on the full test set). A nonexistent ID only lowers your score, so this "
        "is a diagnostic, not a submission gate.",
    )
    args = parser.parse_args()

    # candidate_pairs.tsv is optional; default to the conventional path and let
    # validate() skip (with a warning) if the file isn't there.
    candidate_path = args.candidate or "output/candidate_pairs.tsv"

    print("ML Challenge 2026 — submission validator")
    print(f"  test dir: {args.test_dir}")
    try:
        errors, warnings = validate(
            args.matching, candidate_path, args.test_dir, check_ids=args.check_ids
        )
    except UnicodeDecodeError:
        print()
        print("FAIL — 1 issue(s) to fix before submitting:")
        print(
            f"  1. A file is not valid UTF-8 text (most likely {args.matching} or "
            f"{candidate_path}). Re-save it as a plain UTF-8, tab-separated .tsv — "
            "not cp1252/Latin-1, and not a compressed or binary file (.gz/.xlsx/"
            ".parquet) renamed to .tsv. In pandas: "
            "df.to_csv(path, sep='\\t', index=False, encoding='utf-8')."
        )
        return 1
    except OSError as exc:
        print()
        print("FAIL — 1 issue(s) to fix before submitting:")
        print(f"  1. Could not read a file: {exc}.")
        return 1

    print()
    for warning in warnings:
        print(f"WARNING: {warning}")
    if errors:
        print(f"FAIL — {len(errors)} issue(s) to fix before submitting:")
        for i, error in enumerate(errors, 1):
            print(f"  {i}. {error}")
        return 1
    print("PASS — no blocking issues found. Safe to submit.")
    return 0


if __name__ == "__main__":
    sys.exit(main())

In [ ]:
readme = os.path.join(base, "README.md")

print("=" * 80)
print("README")
print("=" * 80)

with open(readme, "r", encoding="utf-8") as f:
    text = f.read()

print(text[:15000])

================================================================================
README
================================================================================
# ML Challenge 2026 Problem Statement

## Business Entity Resolution Challenge

In large-scale commercial platforms, business identity data arrives from multiple independent sources — each contributing partial, noisy fragments of information about the same real-world entities. These fragments share no common identifiers, and the challenge of determining which records refer to the same business is known as Entity Resolution (ER). Your challenge is to build an ML solution that, given business records from 3 independent data sources with noisy and inconsistent fields, determines which records across sources refer to the same real-world business entity.

Source 1 is the deduplicated reference source. Your task is to find all matching records from Source 2 and Source 3 for each Source 1 entity. A Source 1 entity may match zero, one, or many records from Source 2 and Source 3.

### File Format

**All files in this challenge are tab-separated (`.tsv`), and your submissions must be tab-separated too.** Tabs are used because business addresses and the ID list columns both contain commas. Read them with an explicit tab separator, for example:

```python
import pandas as pd
df = pd.read_csv("dataset/train/train_source1.tsv", sep="\t")
```

Reading a `.tsv` without `sep="\t"` will silently produce a single column containing the whole line.

### Data Description:

Each source file (`*_source1.tsv`, `*_source2.tsv`, `*_source3.tsv`) has the following columns:

1. **entity_id:** Unique identifier for the record. The prefix indicates the source — `S1-`, `S2-`, or `S3-`.
2. **business_name:** Name of the business entity (may contain abbreviations, legal suffixes, typos, transliterations)
3. **business_address:** Address of the business (may contain partial addresses, format variations, missing components, landmark-based references)
4. **country:** Country label for the record. The **training** data covers `US` and `India`. The **test** set additionally contains a third country, `France`, that does **not** appear in the training data. Treat `country` as an open set of string labels: do **not** hard-code, filter, or one-hot your pipeline to only `{US, India}`, and remember that every test entity — `France` included — must appear in your submission.

There is no separate *source* column — a record's source is given by its `entity_id` prefix (`S1-`/`S2-`/`S3-`) and by which file it appears in.

The ground truth file (`train_ground_truth.tsv`) has two columns:

1. **source1_entity_id:** The `entity_id` of a Source 1 record
2. **matched_entity_ids:** Comma-separated list of matching `entity_id`s from Source 2 and/or Source 3 (empty when the entity has no matches)

**Noise Patterns to Expect:**

- **Name variations:** Abbreviations (Corp vs. Corporation, Pvt vs. Private, Ltd vs. Limited), legal suffix inconsistencies, DBA/trade names, punctuation differences (& vs. "and"), word-order transpositions, typos
- **Address variations:** Abbreviations (Rd vs. Road, St vs. Street), transliteration variants, missing components (no PIN code, no state), landmark-based references (Near SBI ATM), municipal numbering formats, component reordering

### Dataset Details:

- **Training Dataset:** Business records across 3 sources with ground truth matching labels
- **Test Set:** Business records across 3 sources without matching labels

### File Descriptions:

*Training files*

1. **dataset/train/train_source1.tsv:** Source 1 training records (the deduplicated reference source)
2. **dataset/train/train_source2.tsv:** Source 2 training records
3. **dataset/train/train_source3.tsv:** Source 3 training records
4. **dataset/train/train_ground_truth.tsv:** Ground truth matching labels for the training set

*Test files*

1. **dataset/test/test_source1.tsv:** Source 1 test records. Generate matches for every entity in this file.
2. **dataset/test/test_source2.tsv:** Source 2 test records
3. **dataset/test/test_source3.tsv:** Source 3 test records

No ground truth is provided for the test set. To measure your own performance, hold out a validation split from the training data and score it yourself using the F_0.5 formula given below.

### Output Format:

Your solution produces **two** tab-separated files, both placed in the `output/`
folder of your final submission package (see *Final Submission Package* below):

1. **`matching_results.tsv`** — your final entity matches. **This is the only file
   scored on the leaderboard** — it is what you upload to the Portal during the challenge.
2. **`candidate_pairs.tsv`** — the candidate set your blocking / candidate-generation
   stage produced, before your final matching model narrowed it down.

#### matching_results.tsv

Your final entity matches:

| Column | Description |
| --- | --- |
| source1_entity_id | The `entity_id` of a Source 1 record |
| matched_entity_ids | Comma-separated list of matching `entity_id`s from Source 2 and/or Source 3 |

**Example** (columns separated by a single tab, ID lists separated by commas with no quoting):

```
source1_entity_id	matched_entity_ids
S1-00001	S2-00047,S2-00193,S3-00812
S1-00002	S3-00004
S1-00003
```

**Important:**

- Every Source 1 entity in the test set must have exactly one row
- Leave `matched_entity_ids` empty for entities with no matches (singletons)
- No duplicate entity IDs within a single ID list
- ID lists must only contain Source 2 or Source 3 IDs that exist in the test set

#### candidate_pairs.tsv

The candidate set from your blocking stage — every Source 2 / Source 3 record you
considered a plausible match for each Source 1 entity, *before* your final matching
model narrowed it down. This is the **exact set of records you feed into your matching model
for inference** — the final candidate list *just before* the ML model scores them, not
the raw output of an early blocking pass you later filter further. If your pipeline has
several blocking/filtering stages, `candidate_pairs.tsv` is the *last* one: whatever
your model actually runs inference over. Every ID in `matching_results.tsv` should
therefore appear here.

It is **not scored on the leaderboard**; we use it to analyse blocking quality (recall
ceiling, reduction ratio) and to verify your pipeline.

| Column | Description |
| --- | --- |
| source1_entity_id | The `entity_id` of a Source 1 record |
| candidate_entity_ids | Comma-separated list of candidate `entity_id`s from Source 2 and/or Source 3 |

**Example:**

```
source1_entity_id	candidate_entity_ids
S1-00001	S2-00047,S2-00193,S3-00812,S3-00999
S1-00002	S3-00004
S1-00003
```

Same rules as `matching_results.tsv`: one row per Source 1 entity, `candidate_entity_ids`
empty when blocking found no candidates, S2-/S3- IDs only, no duplicates within a list.
Your final matches should be a **subset** of your candidates (a matched ID that never
appeared as a candidate signals a pipeline bug — the validator warns about it).

**Validate before submitting:** a helper script `utils/validate_submission.py` (stdlib
only, no dependencies) checks both files against every rule above so you can catch a
rejection locally instead of spending a submission on it. Run it from this
`student_resource/` directory:

```bash
python3 utils/validate_submission.py \
    --matching output/matching_results.tsv \
    --candidate output/candidate_pairs.tsv \
    --test-dir dataset/test
```

It prints `PASS` (exit 0) when the files are safe to submit, or a numbered list of issues
to fix (exit 1). It only reads your output files and the test source files; it does not
compute your score.

### Final Submission Package:

In addition to your live leaderboard uploads, **every team submits a single zip
archive** with your code and outputs. We use it to reproduce your results, audit your
blocking, and check the fair-play and model-license rules — the top teams' packages are
reviewed in detail before the final rankings are confirmed.

Structure:

```
<team_name>_submission.zip
├── output/
│   ├── matching_results.tsv        # final matches (same file you upload to the leaderboard)
│   └── candidate_pairs.tsv         # your blocking candidate set
├── code/
│   └── business_entity_resolution/
│       ├── src/                    # all your source code
│       ├── README.md               # how to reproduce end-to-end (data → blocking → matching → output)
│       └── requirements.txt        # pinned dependencies / environment
└── Documentation_template.md       # your methodology write-up (this filled-in template)
```

- **`output/`** — the two TSV files described above: `matching_results.tsv` and
  `candidate_pairs.tsv`.
- **`code/business_entity_resolution/`** — a self-contained, runnable copy of your
  pipeline. Put all source under `src/`, and include a `README.md` with exact run
  instructions plus a `requirements.txt` (or equivalent environment file) pinning
  versions. Anyone should be able to regenerate both output files from the
  training/test data using only what is in this folder.
- **Methodology document** — fill in the provided `Documentation_template.md` and drop
  it straight into the zip (the filled-in `.md` is fine; a `.pdf` export works too). No
  need to rename it.

### Constraints:

1. Format your output exactly as described above. Submissions that fail validation will not be evaluated. You should see a `SCORED` status with your F_0.5 score if the output is correctly formatted.
2. `matched_entity_ids` must only reference entities from Source 2 or Source 3. Self-matches to Source 1, and IDs that do not exist in the test set, will be rejected.
3. Every Source 1 entity must appear in your submission. Missing entities will cause rejection.
4. Duplicate entity IDs in any ID list will cause rejection, as will duplicate `source1_entity_id` rows.
5. Final model should be a MIT/Apache 2.0 License model and up to 8 Billion parameters.

### Evaluation Criteria:

Submissions are evaluated using **F_β Score (β = 0.5)** — a precision-heavy metric that penalizes false merges (matching two different businesses) more than missed matches.

**Formula:**

```
F_0.5 = (1.25 × Precision × Recall) / (0.25 × Precision + Recall)
```

Computed as a **macro-average**: F_0.5 is calculated per Source 1 entity, then averaged across **all** Source 1 entities in the evaluation set.

Singletons are included in that average. A Source 1 entity with no true matches scores 1.0 when you correctly predict an empty list, and 0.0 when you predict any match for it. Correctly identifying singletons therefore earns credit, and false merges on them are penalised.

**Why precision-heavy?** In real-world entity resolution, merging two distinct businesses (false positive) is more damaging than missing a link (false negative). F_0.5 weights precision 2× over recall.

**Example:**

- Your model predicts S1-00001 matches [S2-00047, S2-00193, S3-00812]
- Ground truth says S1-00001 matches [S2-00047, S3-00812]
- Precision = 2/3, Recall = 2/2 = 1.0
- F_0.5 = (1.25 × 0.667 × 1.0) / (0.25 × 0.667 + 1.0) = **0.714**

### Leaderboard Information:

- **Public Leaderboard:** During the challenge, rankings will be based on a subset of the test set to provide real-time feedback on your model's performance.
- **Private Leaderboard:** After the challenge ends, the private leaderboard will be revealed, which uses the remaining portion of the test set for evaluation.
- **Final Rankings:** The final decision will be based on the private leaderboard.

You submit predictions for the full test set in both cases; the split is applied during scoring.

### Submission Requirements:

1. **Leaderboard (during the challenge):** upload `matching_results.tsv` in the Portal —
   tab-separated, with the exact column names described above. This is what drives the
   public and private leaderboards.
2. **Final submission package:** submit the single zip described in *Final Submission
   Package* above — `output/` with **both** `matching_results.tsv` (final matches) and
   `candidate_pairs.tsv` (your candidate-generation / blocking set fed to the model),
   `code/business_entity_resolution/` (runnable pipeline), and your methodology document.
   All teams must submit it; the top teams' packages are reviewed before the final
   rankings are confirmed.
3. Your methodology document must describe:
   - Methodology used
   - Candidate generation / blocking strategy
   - Model architecture and feature engineering
   - Any other relevant information about the approach

   A template for this documentation is provided in `Documentation_template.md`. There is no page limit — prioritise clarity and technical depth over brevity.

### **Academic Integrity and Fair Play:**

**⚠️ STRICTLY PROHIBITED: External Data Lookup**

Participants are **STRICTLY NOT ALLOWED** to use external databases, APIs, or services to look up business identities or resolve entities. This includes but is not limited to:

- Using commercial entity resolution APIs or services
- Looking up business registrations from government databases
- Using geocoding APIs to normalize addresses
- Any external data augmentation from internet sources

**Enforcement:**

- All submitted approaches, methodologies, and code pipelines will be thoroughly reviewed and verified
- Any evidence of external data lookup will result in **immediate disqualification**

**Fair Play:** This challenge is designed to test your machine learning and data science skills using only the provided training data.

### Tips for Success:

- Invest in a strong blocking/candidate generation strategy — it determines the upper bound of your recall
- Explore string similarity features (Jaccard, Levenshtein, TF-IDF cosine) for name and address matching
- Pay attention to country specific address patterns
- Consider the precision-recall trade-off carefully — F_0.5 rewards precision more than recall
- Do not neglect singletons — correctly predicting "no match" is worth a full 1.0 on that entity
- Validate your own output format against the rules above before submitting

# BASELINE SUBMISSION V1

In [ ]:
import os
import pandas as pd
import re
import unicodedata

BASE = "/content/amazon_ml_challenge/student_resource"

TRAIN = os.path.join(BASE, "dataset", "train")
TEST = os.path.join(BASE, "dataset", "test")

OUTPUT = os.path.join(BASE, "output")
os.makedirs(OUTPUT, exist_ok=True)

print("BASE:", BASE)
print("OUTPUT:", OUTPUT)

BASE: /content/amazon_ml_challenge/student_resource
OUTPUT: /content/amazon_ml_challenge/student_resource/output

In [ ]:
def normalize_text(x):
    if pd.isna(x):
        return ""

    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)

    # punctuation → space
    x = re.sub(r"[^\w\s]", " ", x)

    # multiple spaces → one
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def normalize_name(x):
    return normalize_text(x)


def normalize_address(x):
    return normalize_text(x)


def normalize_country(x):
    return normalize_text(x)


print(normalize_name("Anchor Staking Inc."))
print(normalize_address("2330 CENTRAL AVENUE, KANSAS CITY, KS"))

anchor staking inc
2330 central avenue kansas city ks

In [ ]:
from collections import defaultdict

def build_indexes(path, chunksize=200_000):

    address_index = defaultdict(list)
    name_index = defaultdict(list)

    total = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=chunksize
    ):

        total += len(chunk)

        names = chunk["business_name"].map(normalize_name)
        addresses = chunk["business_address"].map(normalize_address)
        countries = chunk["country"].map(normalize_country)

        for entity_id, name, address, country in zip(
            chunk["entity_id"],
            names,
            addresses,
            countries
        ):

            # Strong address key
            if address:
                key = (country, address)
                address_index[key].append(entity_id)

            # Name key
            if name:
                key = (country, name)
                name_index[key].append(entity_id)

        print(f"Processed {total:,} rows...", end="\r")

    print(f"\nFinished: {total:,} rows")

    return address_index, name_index

In [ ]:
print("Building Source 2 index...")

s2_address, s2_name = build_indexes(
    os.path.join(TEST, "test_source2.tsv")
)

print("\nBuilding Source 3 index...")

s3_address, s3_name = build_indexes(
    os.path.join(TEST, "test_source3.tsv")
)

print("\nIndexes ready!")

Building Source 2 index...
Processed 4,887,273 rows...
Finished: 4,887,273 rows

Building Source 3 index...
Processed 5,082,316 rows...
Finished: 5,082,316 rows

Indexes ready!

In [ ]:
s1_test = pd.read_csv(
    os.path.join(TEST, "test_source1.tsv"),
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
)

print(s1_test.shape)
display(s1_test.head())

(1732544, 4)

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France

In [ ]:
def get_candidates(row):

    entity_id = row["entity_id"]

    name = normalize_name(row["business_name"])
    address = normalize_address(row["business_address"])
    country = normalize_country(row["country"])

    candidates = set()

    # ------------------------------------------------
    # RULE 1: exact normalized address + country
    # ------------------------------------------------

    if address:
        key = (country, address)

        candidates.update(
            s2_address.get(key, [])
        )

        candidates.update(
            s3_address.get(key, [])
        )

    # ------------------------------------------------
    # RULE 2: exact normalized name + country
    # ------------------------------------------------

    if name:
        key = (country, name)

        candidates.update(
            s2_name.get(key, [])
        )

        candidates.update(
            s3_name.get(key, [])
        )

    return sorted(candidates)

In [ ]:
results = []
candidate_results = []

for i, row in s1_test.iterrows():

    candidates = get_candidates(row)

    candidate_results.append({
        "source1_entity_id": row["entity_id"],
        "candidate_entity_ids": ",".join(candidates)
    })

    # For V1, use candidates directly as matches.
    results.append({
        "source1_entity_id": row["entity_id"],
        "matched_entity_ids": ",".join(candidates)
    })

    if (i + 1) % 100000 == 0:
        print(f"Processed {i+1:,} / {len(s1_test):,}")

Processed 100,000 / 1,732,544
Processed 200,000 / 1,732,544
Processed 300,000 / 1,732,544
Processed 400,000 / 1,732,544
Processed 500,000 / 1,732,544
Processed 600,000 / 1,732,544
Processed 700,000 / 1,732,544
Processed 800,000 / 1,732,544
Processed 900,000 / 1,732,544
Processed 1,000,000 / 1,732,544
Processed 1,100,000 / 1,732,544
Processed 1,200,000 / 1,732,544
Processed 1,300,000 / 1,732,544
Processed 1,400,000 / 1,732,544
Processed 1,500,000 / 1,732,544
Processed 1,600,000 / 1,732,544
Processed 1,700,000 / 1,732,544

In [ ]:
print("Loop completed!")
print("Results:", len(results))
print("Candidates:", len(candidate_results))

Loop completed!
Results: 1732544
Candidates: 1732544

In [ ]:
matching_df = pd.DataFrame(results)
candidate_df = pd.DataFrame(candidate_results)

matching_path = os.path.join(
    OUTPUT,
    "matching_results.tsv"
)

candidate_path = os.path.join(
    OUTPUT,
    "candidate_pairs.tsv"
)

matching_df.to_csv(
    matching_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

candidate_df.to_csv(
    candidate_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

print("Files created successfully!")
print(matching_path)
print(candidate_path)

Files created successfully!
/content/amazon_ml_challenge/student_resource/output/matching_results.tsv
/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv

In [ ]:
print("MATCHING FILE")
print("=" * 60)

print("Rows:", len(matching_df))
print("Columns:", matching_df.columns.tolist())

display(matching_df.head(10))

MATCHING FILE
============================================================
Rows: 1732544
Columns: ['source1_entity_id', 'matched_entity_ids']

  source1_entity_id                                 matched_entity_ids
0      S1-714132312
1      S1-106407869  S2-104974637,S2-181714769,S2-384676749,S2-4747...
2      S1-156285671  S2-160966771,S2-180394702,S2-181576625,S2-2104...
3      S1-689823050
4      S1-921369899             S2-107533354,S2-808920974,S3-285097097
5      S1-481669221
6      S1-909865979  S2-111603994,S2-114894157,S2-162988628,S2-1926...
7      S1-280204013             S2-106459682,S2-510010767,S2-616226992
8      S1-742053041                           S2-317425677,S2-73207920
9      S1-913506265

In [ ]:
print("CANDIDATE FILE")
print("=" * 60)

print("Rows:", len(candidate_df))
print("Columns:", candidate_df.columns.tolist())

display(candidate_df.head(10))

CANDIDATE FILE
============================================================
Rows: 1732544
Columns: ['source1_entity_id', 'candidate_entity_ids']

  source1_entity_id                               candidate_entity_ids
0      S1-714132312
1      S1-106407869  S2-104974637,S2-181714769,S2-384676749,S2-4747...
2      S1-156285671  S2-160966771,S2-180394702,S2-181576625,S2-2104...
3      S1-689823050
4      S1-921369899             S2-107533354,S2-808920974,S3-285097097
5      S1-481669221
6      S1-909865979  S2-111603994,S2-114894157,S2-162988628,S2-1926...
7      S1-280204013             S2-106459682,S2-510010767,S2-616226992
8      S1-742053041                           S2-317425677,S2-73207920
9      S1-913506265

In [ ]:
matched_nonempty = (
    matching_df["matched_entity_ids"]
    .fillna("")
    .str.strip()
    .ne("")
    .sum()
)

candidate_nonempty = (
    candidate_df["candidate_entity_ids"]
    .fillna("")
    .str.strip()
    .ne("")
    .sum()
)

print("Total S1:", len(matching_df))
print("S1 with matches:", matched_nonempty)
print("S1 with NO matches:", len(matching_df) - matched_nonempty)

print()
print("S1 with candidates:", candidate_nonempty)
print("S1 with NO candidates:", len(candidate_df) - candidate_nonempty)

Total S1: 1732544
S1 with matches: 1338937
S1 with NO matches: 393607

S1 with candidates: 1338937
S1 with NO candidates: 393607

In [ ]:
candidate_counts = (
    candidate_df["candidate_entity_ids"]
    .fillna("")
    .apply(lambda x: len(x.split(",")) if x.strip() else 0)
)

print("Candidate statistics")
print("=" * 60)
print("Minimum:", candidate_counts.min())
print("Average:", candidate_counts.mean())
print("Median:", candidate_counts.median())
print("Maximum:", candidate_counts.max())

print("\nPercentiles:")
print(candidate_counts.quantile([0.50, 0.75, 0.90, 0.95, 0.99]))

Candidate statistics
============================================================
Minimum: 0
Average: 6.610495895053748
Median: 2.0
Maximum: 480

Percentiles:
0.50     2.0
0.75     5.0
0.90    15.0
0.95    28.0
0.99    91.0
Name: candidate_entity_ids, dtype: float64

In [ ]:
print("V1 prediction statistics")
print("=" * 60)

match_counts = (
    matching_df["matched_entity_ids"]
    .fillna("")
    .apply(lambda x: len(x.split(",")) if x.strip() else 0)
)

print("S1 records:", len(match_counts))
print("With at least 1 match:", (match_counts > 0).sum())
print("With 0 matches:", (match_counts == 0).sum())

print("\nMatch count distribution:")
print(match_counts.value_counts().sort_index().head(20))

print("\nAverage predicted matches:", match_counts.mean())
print("Median predicted matches:", match_counts.median())
print("Maximum predicted matches:", match_counts.max())

V1 prediction statistics
============================================================
S1 records: 1732544
With at least 1 match: 1338937
With 0 matches: 393607

Match count distribution:
matched_entity_ids
0     393607
1     413604
2     270873
3     143936
4      75428
5      44654
6      31934
7      25727
8      22690
9      21695
10     21740
11     22526
12     21511
13     21196
14     18552
15     16854
16     14696
17     13235
18     10666
19      8737
Name: count, dtype: int64

Average predicted matches: 6.610495895053748
Median predicted matches: 2.0
Maximum predicted matches: 480

In [ ]:
def get_conservative_matches(row):

    name = normalize_name(row["business_name"])
    address = normalize_address(row["business_address"])
    country = normalize_country(row["country"])

    matches = set()

    # Rule 1: exact normalized address + country
    if address:
        key = (country, address)

        matches.update(s2_address.get(key, []))
        matches.update(s3_address.get(key, []))

    # Rule 2: exact normalized name + country,
    # only when the name is unique within that source
    if name:
        key = (country, name)

        s2_matches = s2_name.get(key, [])
        s3_matches = s3_name.get(key, [])

        if len(s2_matches) == 1:
            matches.add(s2_matches[0])

        if len(s3_matches) == 1:
            matches.add(s3_matches[0])

    return sorted(matches)

In [ ]:
sample_test = s1_test.head(10000)

sample_counts = []

for _, row in sample_test.iterrows():
    matches = get_conservative_matches(row)
    sample_counts.append(len(matches))

sample_counts = pd.Series(sample_counts)

print("10,000-record conservative test")
print("=" * 60)
print("With matches:", (sample_counts > 0).sum())
print("Without matches:", (sample_counts == 0).sum())
print("Average matches:", sample_counts.mean())
print("Median:", sample_counts.median())
print("Maximum:", sample_counts.max())

print("\nPercentiles:")
print(sample_counts.quantile([0.50, 0.75, 0.90, 0.95, 0.99]))

10,000-record conservative test
============================================================
With matches: 5343
Without matches: 4657
Average matches: 0.8063
Median: 1.0
Maximum: 64

Percentiles:
0.50    1.0
0.75    1.0
0.90    2.0
0.95    2.0
0.99    4.0
dtype: float64

In [ ]:
def generate_candidates(row):

    name = normalize_name(row["business_name"])
    address = normalize_address(row["business_address"])
    country = normalize_country(row["country"])

    candidates = set()

    # Block 1: country + exact normalized address
    if address:
        key = (country, address)

        candidates.update(s2_address.get(key, []))
        candidates.update(s3_address.get(key, []))

    # Block 2: country + normalized name
    if name:
        key = (country, name)

        candidates.update(s2_name.get(key, []))
        candidates.update(s3_name.get(key, []))

    return sorted(candidates)

In [ ]:
submission_template = pd.DataFrame({
    "source1_entity_id": s1_test["entity_id"],
    "matched_entity_ids": ""
})

candidate_template = pd.DataFrame({
    "source1_entity_id": s1_test["entity_id"],
    "candidate_entity_ids": ""
})

print(submission_template.shape)
print(candidate_template.shape)

(1732544, 2)
(1732544, 2)

In [ ]:
!pip -q install rapidfuzz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 32.5 MB/s eta 0:00:00

In [ ]:
from rapidfuzz.fuzz import ratio

def pair_features(s1, candidate):

    name1 = normalize_name(s1["business_name"])
    name2 = normalize_name(candidate["business_name"])

    addr1 = normalize_address(s1["business_address"])
    addr2 = normalize_address(candidate["business_address"])

    country1 = normalize_country(s1["country"])
    country2 = normalize_country(candidate["country"])

    return {
        "name_exact": int(name1 == name2),
        "address_exact": int(addr1 == addr2),
        "country_exact": int(country1 == country2),

        "name_similarity": ratio(name1, name2) / 100,
        "address_similarity": ratio(addr1, addr2) / 100,

        "name_length_diff": abs(len(name1) - len(name2)),
        "address_length_diff": abs(len(addr1) - len(addr2)),

        "name_token_overlap": len(
            set(name1.split()) & set(name2.split())
        ) / max(
            1,
            len(set(name1.split()) | set(name2.split()))
        ),

        "address_token_overlap": len(
            set(addr1.split()) & set(addr2.split())
        ) / max(
            1,
            len(set(addr1.split()) | set(addr2.split()))
        )
    }

In [ ]:
import re
import unicodedata

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste ",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [ ]:
name = normalize_advanced(row["business_name"])
address = normalize_advanced(row["business_address"])
country = normalize_country(row["country"])

In [ ]:
def build_advanced_indexes(path, chunksize=200_000):
    name_index = {}
    address_index = {}

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name", "business_address", "country"],
        chunksize=chunksize
    ):
        for _, row in chunk.iterrows():
            entity_id = row["entity_id"]
            country = normalize_country(row["country"])

            name = normalize_advanced(row["business_name"])
            address = normalize_advanced(row["business_address"])

            if name:
                key = (country, name)
                name_index.setdefault(key, []).append(entity_id)

            if address:
                key = (country, address)
                address_index.setdefault(key, []).append(entity_id)

    return address_index, name_index

In [ ]:
s2_adv_address, s2_adv_name = build_advanced_indexes(
    f"{TRAIN}/train_source2.tsv"
)

s3_adv_address, s3_adv_name = build_advanced_indexes(
    f"{TRAIN}/train_source3.tsv"
)

print("S2 advanced indexes:", len(s2_adv_name), len(s2_adv_address))
print("S3 advanced indexes:", len(s3_adv_name), len(s3_adv_address))

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
BASE = "/content/amazon_ml_challenge/student_resource"
TRAIN = f"{BASE}/dataset/train"
TEST = f"{BASE}/dataset/test"

print("Setup ready")

Setup ready

In [ ]:
import pandas as pd

train_s1_10k = pd.read_csv(
    f"{TRAIN}/train_source1.tsv",
    sep="\t",
    usecols=["entity_id", "business_name", "business_address", "country"],
    nrows=10000
)

print("Training S1:", train_s1_10k.shape)
train_s1_10k.head()

Training S1: (10000, 4)

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [ ]:
import re
import unicodedata
import pandas as pd

def normalize_text(x):
    if pd.isna(x):
        return ""
    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)
    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

def normalize_country(x):
    return normalize_text(x)

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

print("Normalization functions ready.")

Normalization functions ready.

In [ ]:
from collections import defaultdict

def build_s1_key_maps(s1_df):
    name_map = defaultdict(list)
    address_map = defaultdict(list)

    for _, row in s1_df.iterrows():
        sid = row["entity_id"]
        country = normalize_country(row["country"])

        name = normalize_advanced(row["business_name"])
        address = normalize_advanced(row["business_address"])

        if name:
            name_map[(country, name)].append(sid)

        if address:
            address_map[(country, address)].append(sid)

    return name_map, address_map


s1_name_map, s1_address_map = build_s1_key_maps(train_s1_10k)

print("S1 name keys:", len(s1_name_map))
print("S1 address keys:", len(s1_address_map))

S1 name keys: 9837
S1 address keys: 9997

In [ ]:
from collections import defaultdict

def collect_candidates_from_source(path, s1_name_map, s1_address_map):
    candidates = defaultdict(set)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name", "business_address", "country"],
        chunksize=200_000
    ):
        for _, row in chunk.iterrows():

            eid = row["entity_id"]
            country = normalize_country(row["country"])

            name = normalize_advanced(row["business_name"])
            address = normalize_advanced(row["business_address"])

            # Advanced name match
            if name:
                key = (country, name)
                for sid in s1_name_map.get(key, []):
                    candidates[sid].add(eid)

            # Advanced address match
            if address:
                key = (country, address)
                for sid in s1_address_map.get(key, []):
                    candidates[sid].add(eid)

    return candidates


print("Scanning Source 2...")
cand_s2 = collect_candidates_from_source(
    f"{TRAIN}/train_source2.tsv",
    s1_name_map,
    s1_address_map
)

print("Source 2 finished.")
print("S1 records with S2 candidates:", len(cand_s2))

print("Scanning Source 3...")
cand_s3 = collect_candidates_from_source(
    f"{TRAIN}/train_source3.tsv",
    s1_name_map,
    s1_address_map
)

print("Source 3 finished.")
print("S1 records with S3 candidates:", len(cand_s3))

Scanning Source 2...
Source 2 finished.
S1 records with S2 candidates: 6233
Scanning Source 3...
Source 3 finished.
S1 records with S3 candidates: 5963

In [ ]:
import os
import glob

BASE = "/content/amazon_ml_challenge/student_resource"
TRAIN = f"{BASE}/dataset/train"
TEST = f"{BASE}/dataset/test"
OUTPUT = f"{BASE}/output"

os.makedirs(OUTPUT, exist_ok=True)

print("BASE:", BASE)
print("TEST:", TEST)
print("OUTPUT:", OUTPUT)

BASE: /content/amazon_ml_challenge/student_resource
TEST: /content/amazon_ml_challenge/student_resource/dataset/test
OUTPUT: /content/amazon_ml_challenge/student_resource/output

In [ ]:
for f in glob.glob(f"{TEST}/*.tsv") + glob.glob(f"{OUTPUT}/*.tsv"):
    print(f, round(os.path.getsize(f) / (1024**3), 2), "GB")

/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv 0.47 GB
/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv 0.16 GB
/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv 0.47 GB
/content/amazon_ml_challenge/student_resource/output/matching_results.tsv 0.16 GB
/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv 0.16 GB

In [ ]:
import pandas as pd
import os

matching_file = f"{OUTPUT}/matching_results.tsv"
candidate_file = f"{OUTPUT}/candidate_pairs.tsv"

print("MATCHING FILE")
print("Size:", round(os.path.getsize(matching_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(matching_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(matching_file, encoding="utf-8")) - 1)

print("\nCANDIDATE FILE")
print("Size:", round(os.path.getsize(candidate_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(candidate_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(candidate_file, encoding="utf-8")) - 1)

MATCHING FILE
Size: 0.16 GB
Columns: ['source1_entity_id', 'matched_entity_ids']
Rows: 1732544

CANDIDATE FILE
Size: 0.16 GB
Columns: ['source1_entity_id', 'candidate_entity_ids']
Rows: 1732544

In [ ]:
import pandas as pd

matching = pd.read_csv(
    f"{OUTPUT}/matching_results.tsv",
    sep="\t"
)

candidate = pd.read_csv(
    f"{OUTPUT}/candidate_pairs.tsv",
    sep="\t"
)

print("Matching rows:", len(matching))
print("Candidate rows:", len(candidate))

print("\nMatching examples:")
print(matching.head(10).to_string(index=False))

print("\nCandidate examples:")
print(candidate.head(10).to_string(index=False))

print("\nEmpty matching rows:",
      matching["matched_entity_ids"].fillna("").eq("").sum())

print("Empty candidate rows:",
      candidate["candidate_entity_ids"].fillna("").eq("").sum())

Matching rows: 1732544
Candidate rows: 1732544

Matching examples:
source1_entity_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         matched_entity_ids
     S1-714132312                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN
     S1-106407869                                                                                                                                                                                                                                                                                                                                                                                                                                                                    S2-104974637,S2-181714769,S2-384676749,S2-47475427,S2-537475802,S2-570778034,S2-571602010,S2-794512883,S2-885551878,S2-886540563,S2-908403586,S2-92136030,S2-997023970,S3-245724670,S3-654401737,S3-696641691,S3-918090607,S3-943074147
     S1-156285671                                                                             S2-160966771,S2-180394702,S2-181576625,S2-210484113,S2-216577514,S2-315093801,S2-500028806,S2-50840726,S2-539923569,S2-591130136,S2-627620252,S2-631516219,S2-642507642,S2-64661346,S2-648438067,S2-682566249,S2-690897988,S2-693304006,S2-721272321,S2-754085628,S2-790421714,S2-806838979,S2-818359405,S2-823443457,S2-868820087,S2-971574924,S3-156413602,S3-205840591,S3-277504297,S3-322638202,S3-33213500,S3-335683571,S3-371440905,S3-453812384,S3-482763678,S3-516625443,S3-522877008,S3-626746400,S3-683806513,S3-68418198,S3-705874844,S3-711484488,S3-751716433,S3-762835469,S3-797166716,S3-816282780,S3-875859009
     S1-689823050                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN
     S1-921369899                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     S2-107533354,S2-808920974,S3-285097097
     S1-481669221                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN
     S1-909865979 S2-111603994,S2-114894157,S2-162988628,S2-192695265,S2-282102043,S2-305814200,S2-32135297,S2-38744097,S2-391573996,S2-412406867,S2-427529280,S2-518801559,S2-528901108,S2-547847470,S2-57687679,S2-598847657,S2-612598164,S2-615821725,S2-81776388,S2-819123304,S2-819591958,S2-898320595,S2-939615243,S2-969410375,S3-145974554,S3-172909739,S3-182986134,S3-185516359,S3-237387703,S3-274126946,S3-287513957,S3-309701421,S3-317089946,S3-322891815,S3-363852035,S3-382480468,S3-388078500,S3-403086436,S3-45370125,S3-47801110,S3-545829635,S3-561577102,S3-588016248,S3-590543778,S3-613974661,S3-687757928,S3-692902601,S3-815167349,S3-818019213,S3-837937060,S3-911082795,S3-947203525,S3-964466781
     S1-280204013                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     S2-106459682,S2-510010767,S2-616226992
     S1-742053041                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   S2-317425677,S2-73207920
     S1-913506265                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN

Candidate examples:
source1_entity_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       candidate_entity_ids
     S1-714132312                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN
     S1-106407869                                                                                                                                                                                                                                                                                                                                                                                                                                                                    S2-104974637,S2-181714769,S2-384676749,S2-47475427,S2-537475802,S2-570778034,S2-571602010,S2-794512883,S2-885551878,S2-886540563,S2-908403586,S2-92136030,S2-997023970,S3-245724670,S3-654401737,S3-696641691,S3-918090607,S3-943074147
     S1-156285671                                                                             S2-160966771,S2-180394702,S2-181576625,S2-210484113,S2-216577514,S2-315093801,S2-500028806,S2-50840726,S2-539923569,S2-591130136,S2-627620252,S2-631516219,S2-642507642,S2-64661346,S2-648438067,S2-682566249,S2-690897988,S2-693304006,S2-721272321,S2-754085628,S2-790421714,S2-806838979,S2-818359405,S2-823443457,S2-868820087,S2-971574924,S3-156413602,S3-205840591,S3-277504297,S3-322638202,S3-33213500,S3-335683571,S3-371440905,S3-453812384,S3-482763678,S3-516625443,S3-522877008,S3-626746400,S3-683806513,S3-68418198,S3-705874844,S3-711484488,S3-751716433,S3-762835469,S3-797166716,S3-816282780,S3-875859009
     S1-689823050                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN
     S1-921369899                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     S2-107533354,S2-808920974,S3-285097097
     S1-481669221                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN
     S1-909865979 S2-111603994,S2-114894157,S2-162988628,S2-192695265,S2-282102043,S2-305814200,S2-32135297,S2-38744097,S2-391573996,S2-412406867,S2-427529280,S2-518801559,S2-528901108,S2-547847470,S2-57687679,S2-598847657,S2-612598164,S2-615821725,S2-81776388,S2-819123304,S2-819591958,S2-898320595,S2-939615243,S2-969410375,S3-145974554,S3-172909739,S3-182986134,S3-185516359,S3-237387703,S3-274126946,S3-287513957,S3-309701421,S3-317089946,S3-322891815,S3-363852035,S3-382480468,S3-388078500,S3-403086436,S3-45370125,S3-47801110,S3-545829635,S3-561577102,S3-588016248,S3-590543778,S3-613974661,S3-687757928,S3-692902601,S3-815167349,S3-818019213,S3-837937060,S3-911082795,S3-947203525,S3-964466781
     S1-280204013                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     S2-106459682,S2-510010767,S2-616226992
     S1-742053041                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   S2-317425677,S2-73207920
     S1-913506265                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN

Empty matching rows: 393607
Empty candidate rows: 393607

In [ ]:
import os
import glob

print("Searching output files...\n")

for f in glob.glob(f"{OUTPUT}/**/*", recursive=True):
    if os.path.isfile(f):
        size_gb = os.path.getsize(f) / (1024**3)
        print(f"{size_gb:.2f} GB  |  {f}")

Searching output files...

0.16 GB  |  /content/amazon_ml_challenge/student_resource/output/matching_results.tsv
0.16 GB  |  /content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv

In [ ]:
import os
import glob

print("Searching output files...\n")

for f in glob.glob(f"{OUTPUT}/**/*", recursive=True):
    if os.path.isfile(f):
        size_gb = os.path.getsize(f) / (1024**3)
        print(f"{size_gb:.2f} GB  |  {f}")

Searching output files...

0.16 GB  |  /content/amazon_ml_challenge/student_resource/output/matching_results.tsv
0.16 GB  |  /content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv

In [ ]:
print("model exists:", "model" in globals())
print("test_features exists:", "test_features" in globals())

if "model" in globals():
    print("Model type:", type(model).__name__)

if "test_features" in globals():
    print("Test features shape:", test_features.shape)

model exists: False
test_features exists: False

In [ ]:
import os
import glob

MODELS = f"{BASE}/models"

print("Model folder:", MODELS)
print()

if os.path.exists(MODELS):
    for f in glob.glob(f"{MODELS}/**/*", recursive=True):
        if os.path.isfile(f):
            size_mb = os.path.getsize(f) / (1024**2)
            print(f"{size_mb:.2f} MB | {f}")
else:
    print("Models folder does not exist.")

Model folder: /content/amazon_ml_challenge/student_resource/models

Models folder does not exist.

In [ ]:
print("Notebook files:")
import glob
for f in glob.glob("/content/**/*.ipynb", recursive=True):
    print(f)

Notebook files:
/content/drive/MyDrive/Colab Notebooks/notebook1.ipynb
/content/drive/MyDrive/Colab Notebooks/linearreg.ipynb
/content/drive/MyDrive/Colab Notebooks/MHAkashVarma_Cars_EDA_Project.ipynb
/content/drive/MyDrive/Colab Notebooks/Boosting.ipynb
/content/drive/MyDrive/Colab Notebooks/RandomForest.ipynb
/content/drive/MyDrive/Colab Notebooks/Diabetes_Prediction_Logistic_Regression.ipynb
/content/drive/MyDrive/Colab Notebooks/CNN.ipynb
/content/drive/MyDrive/Colab Notebooks/RNN.ipynb
/content/drive/MyDrive/Colab Notebooks/YOLO.ipynb
/content/drive/MyDrive/Colab Notebooks/Linear_Regression_NY_Airbnb.ipynb
/content/drive/MyDrive/Colab Notebooks/Random_Forest_Bank_Customer.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled0.ipynb
/content/drive/MyDrive/Colab Notebooks/FDS LAB Questions.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of Amazon_ML_Challenge_2026.ipynb
/content/drive/MyDrive/Amazon-ML-Challenge-2026/notebooks/Amazon_ML_Challenge_2026.ipynb

In [ ]:
print("\nProject files:")
for f in glob.glob(f"{BASE}/**/*", recursive=True):
    if os.path.isfile(f):
        print(f)

Project files:
/content/amazon_ml_challenge/student_resource/README.md
/content/amazon_ml_challenge/student_resource/Documentation_template.md
/content/amazon_ml_challenge/student_resource/output/matching_results.tsv
/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv
/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv
/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv
/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv
/content/amazon_ml_challenge/student_resource/dataset/train/train_ground_truth.tsv
/content/amazon_ml_challenge/student_resource/dataset/train/train_source3.tsv
/content/amazon_ml_challenge/student_resource/dataset/train/train_source2.tsv
/content/amazon_ml_challenge/student_resource/dataset/train/train_source1.tsv
/content/amazon_ml_challenge/student_resource/utils/validate_submission.py

In [ ]:
import json

NOTEBOOK = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/notebooks/Amazon_ML_Challenge_2026.ipynb"

with open(NOTEBOOK, "r", encoding="utf-8") as f:
    nb = json.load(f)

for i, cell in enumerate(nb["cells"]):
    code = "".join(cell.get("source", []))

    if any(x in code.lower() for x in [
        "catboost",
        "f0.5",
        "99,214",
        "test_features"
    ]):
        print("\n" + "="*70)
        print("CELL", i)
        print("="*70)
        print(code)

======================================================================
CELL 2
======================================================================
!pip install -q catboost lightgbm

======================================================================
CELL 3
======================================================================
import pandas as pd
import numpy as np
import sklearn
import xgboost
import catboost
import lightgbm

print("✅ ML environment ready!")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)
print("XGBoost:", xgboost.__version__)
print("CatBoost:", catboost.__version__)
print("LightGBM:", lightgbm.__version__)

======================================================================
CELL 58
======================================================================
print("model exists:", "model" in globals())
print("test_features exists:", "test_features" in globals())

if "model" in globals():
    print("Model type:", type(model).__name__)

if "test_features" in globals():
    print("Test features shape:", test_features.shape)

In [ ]:
keywords = [
    "pair_features",
    "rapidfuzz",
    "ground_truth",
    "candidate",
    "train_features",
    "CatBoostClassifier",
    "precision",
    "recall",
    "f0.5",
    "threshold"
]

for i, cell in enumerate(nb["cells"]):
    code = "".join(cell.get("source", []))

    if any(k.lower() in code.lower() for k in keywords):
        print("\n" + "="*80)
        print("CELL", i)
        print("="*80)
        print(code)

================================================================================
CELL 8
================================================================================
import pandas as pd
import os

base = "/content/amazon_ml_challenge/student_resource/dataset"

files = [
    "train/train_source1.tsv",
    "train/train_source2.tsv",
    "train/train_source3.tsv",
    "train/train_ground_truth.tsv"
]

for f in files:
    path = os.path.join(base, f)
    df = pd.read_csv(path, sep="\t", nrows=5)

    print("\n" + "="*70)
    print(f)
    print("Columns:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df)

================================================================================
CELL 9
================================================================================
import os
import pandas as pd

base = "/content/amazon_ml_challenge/student_resource/dataset"

# --------------------------------------------------
# 1. Count rows in every dataset
# --------------------------------------------------

files = [
    "train/train_source1.tsv",
    "train/train_source2.tsv",
    "train/train_source3.tsv",
    "train/train_ground_truth.tsv",
    "test/test_source1.tsv",
    "test/test_source2.tsv",
    "test/test_source3.tsv"
]

print("ROW COUNTS")
print("=" * 60)

for f in files:
    path = os.path.join(base, f)

    with open(path, "rb") as file:
        rows = sum(1 for _ in file) - 1

    print(f"{f:<35} {rows:,}")

================================================================================
CELL 11
================================================================================
# --------------------------------------------------
# 3. Understand ground-truth matching structure
# --------------------------------------------------

gt_path = os.path.join(base, "train/train_ground_truth.tsv")

gt = pd.read_csv(gt_path, sep="\t")

print("Ground truth rows:", len(gt))
print("\nColumns:")
print(gt.columns.tolist())

# Number of matched entities for each Source 1 record
match_counts = gt["matched_entity_ids"].fillna("").apply(
    lambda x: len([v for v in x.split(",") if v.strip()])
)

print("\nNumber of matches per Source 1 record:")
print(match_counts.value_counts().sort_index())

print("\nAverage matches:", match_counts.mean())
print("Maximum matches:", match_counts.max())

print("\nExamples:")
display(gt.head(10))

================================================================================
CELL 14
================================================================================
import pandas as pd
import os

base = "/content/amazon_ml_challenge/student_resource/dataset"

gt_path = os.path.join(base, "train/train_ground_truth.tsv")

gt = pd.read_csv(gt_path, sep="\t")

print("Ground truth loaded!")
print("Rows:", len(gt))
print("Columns:", gt.columns.tolist())

================================================================================
CELL 27
================================================================================
def get_candidates(row):

    entity_id = row["entity_id"]

    name = normalize_name(row["business_name"])
    address = normalize_address(row["business_address"])
    country = normalize_country(row["country"])

    candidates = set()

    # ------------------------------------------------
    # RULE 1: exact normalized address + country
    # ------------------------------------------------

    if address:
        key = (country, address)

        candidates.update(
            s2_address.get(key, [])
        )

        candidates.update(
            s3_address.get(key, [])
        )

    # ------------------------------------------------
    # RULE 2: exact normalized name + country
    # ------------------------------------------------

    if name:
        key = (country, name)

        candidates.update(
            s2_name.get(key, [])
        )

        candidates.update(
            s3_name.get(key, [])
        )

    return sorted(candidates)

================================================================================
CELL 28
================================================================================
results = []
candidate_results = []

for i, row in s1_test.iterrows():

    candidates = get_candidates(row)

    candidate_results.append({
        "source1_entity_id": row["entity_id"],
        "candidate_entity_ids": ",".join(candidates)
    })

    # For V1, use candidates directly as matches.
    results.append({
        "source1_entity_id": row["entity_id"],
        "matched_entity_ids": ",".join(candidates)
    })

    if (i + 1) % 100000 == 0:
        print(f"Processed {i+1:,} / {len(s1_test):,}")

================================================================================
CELL 29
================================================================================
print("Loop completed!")
print("Results:", len(results))
print("Candidates:", len(candidate_results))

================================================================================
CELL 30
================================================================================
matching_df = pd.DataFrame(results)
candidate_df = pd.DataFrame(candidate_results)

matching_path = os.path.join(
    OUTPUT,
    "matching_results.tsv"
)

candidate_path = os.path.join(
    OUTPUT,
    "candidate_pairs.tsv"
)

matching_df.to_csv(
    matching_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

candidate_df.to_csv(
    candidate_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

print("Files created successfully!")
print(matching_path)
print(candidate_path)

================================================================================
CELL 32
================================================================================
print("CANDIDATE FILE")
print("=" * 60)

print("Rows:", len(candidate_df))
print("Columns:", candidate_df.columns.tolist())

display(candidate_df.head(10))

================================================================================
CELL 33
================================================================================
matched_nonempty = (
    matching_df["matched_entity_ids"]
    .fillna("")
    .str.strip()
    .ne("")
    .sum()
)

candidate_nonempty = (
    candidate_df["candidate_entity_ids"]
    .fillna("")
    .str.strip()
    .ne("")
    .sum()
)

print("Total S1:", len(matching_df))
print("S1 with matches:", matched_nonempty)
print("S1 with NO matches:", len(matching_df) - matched_nonempty)

print()
print("S1 with candidates:", candidate_nonempty)
print("S1 with NO candidates:", len(candidate_df) - candidate_nonempty)

================================================================================
CELL 34
================================================================================
candidate_counts = (
    candidate_df["candidate_entity_ids"]
    .fillna("")
    .apply(lambda x: len(x.split(",")) if x.strip() else 0)
)

print("Candidate statistics")
print("=" * 60)
print("Minimum:", candidate_counts.min())
print("Average:", candidate_counts.mean())
print("Median:", candidate_counts.median())
print("Maximum:", candidate_counts.max())

print("\nPercentiles:")
print(candidate_counts.quantile([0.50, 0.75, 0.90, 0.95, 0.99]))

================================================================================
CELL 38
================================================================================
def generate_candidates(row):

    name = normalize_name(row["business_name"])
    address = normalize_address(row["business_address"])
    country = normalize_country(row["country"])

    candidates = set()

    # Block 1: country + exact normalized address
    if address:
        key = (country, address)

        candidates.update(s2_address.get(key, []))
        candidates.update(s3_address.get(key, []))

    # Block 2: country + normalized name
    if name:
        key = (country, name)

        candidates.update(s2_name.get(key, []))
        candidates.update(s3_name.get(key, []))

    return sorted(candidates)

================================================================================
CELL 39
================================================================================
submission_template = pd.DataFrame({
    "source1_entity_id": s1_test["entity_id"],
    "matched_entity_ids": ""
})

candidate_template = pd.DataFrame({
    "source1_entity_id": s1_test["entity_id"],
    "candidate_entity_ids": ""
})

print(submission_template.shape)
print(candidate_template.shape)

================================================================================
CELL 40
================================================================================
!pip -q install rapidfuzz

================================================================================
CELL 41
================================================================================
from rapidfuzz.fuzz import ratio

def pair_features(s1, candidate):

    name1 = normalize_name(s1["business_name"])
    name2 = normalize_name(candidate["business_name"])

    addr1 = normalize_address(s1["business_address"])
    addr2 = normalize_address(candidate["business_address"])

    country1 = normalize_country(s1["country"])
    country2 = normalize_country(candidate["country"])

    return {
        "name_exact": int(name1 == name2),
        "address_exact": int(addr1 == addr2),
        "country_exact": int(country1 == country2),

        "name_similarity": ratio(name1, name2) / 100,
        "address_similarity": ratio(addr1, addr2) / 100,

        "name_length_diff": abs(len(name1) - len(name2)),
        "address_length_diff": abs(len(addr1) - len(addr2)),

        "name_token_overlap": len(
            set(name1.split()) & set(name2.split())
        ) / max(
            1,
            len(set(name1.split()) | set(name2.split()))
        ),

        "address_token_overlap": len(
            set(addr1.split()) & set(addr2.split())
        ) / max(
            1,
            len(set(addr1.split()) | set(addr2.split()))
        )
    }

================================================================================
CELL 51
================================================================================
from collections import defaultdict

def collect_candidates_from_source(path, s1_name_map, s1_address_map):
    candidates = defaultdict(set)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name", "business_address", "country"],
        chunksize=200_000
    ):
        for _, row in chunk.iterrows():

            eid = row["entity_id"]
            country = normalize_country(row["country"])

            name = normalize_advanced(row["business_name"])
            address = normalize_advanced(row["business_address"])

            # Advanced name match
            if name:
                key = (country, name)
                for sid in s1_name_map.get(key, []):
                    candidates[sid].add(eid)

            # Advanced address match
            if address:
                key = (country, address)
                for sid in s1_address_map.get(key, []):
                    candidates[sid].add(eid)

    return candidates


print("Scanning Source 2...")
cand_s2 = collect_candidates_from_source(
    f"{TRAIN}/train_source2.tsv",
    s1_name_map,
    s1_address_map
)

print("Source 2 finished.")
print("S1 records with S2 candidates:", len(cand_s2))

print("Scanning Source 3...")
cand_s3 = collect_candidates_from_source(
    f"{TRAIN}/train_source3.tsv",
    s1_name_map,
    s1_address_map
)

print("Source 3 finished.")
print("S1 records with S3 candidates:", len(cand_s3))

================================================================================
CELL 54
================================================================================
import pandas as pd
import os

matching_file = f"{OUTPUT}/matching_results.tsv"
candidate_file = f"{OUTPUT}/candidate_pairs.tsv"

print("MATCHING FILE")
print("Size:", round(os.path.getsize(matching_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(matching_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(matching_file, encoding="utf-8")) - 1)

print("\nCANDIDATE FILE")
print("Size:", round(os.path.getsize(candidate_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(candidate_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(candidate_file, encoding="utf-8")) - 1)

================================================================================
CELL 55
================================================================================
import pandas as pd

matching = pd.read_csv(
    f"{OUTPUT}/matching_results.tsv",
    sep="\t"
)

candidate = pd.read_csv(
    f"{OUTPUT}/candidate_pairs.tsv",
    sep="\t"
)

print("Matching rows:", len(matching))
print("Candidate rows:", len(candidate))

print("\nMatching examples:")
print(matching.head(10).to_string(index=False))

print("\nCandidate examples:")
print(candidate.head(10).to_string(index=False))

print("\nEmpty matching rows:",
      matching["matched_entity_ids"].fillna("").eq("").sum())

print("Empty candidate rows:",
      candidate["candidate_entity_ids"].fillna("").eq("").sum())

In [ ]:
import os
import glob

print("Searching for training feature/candidate files...\n")

for f in glob.glob("/content/drive/MyDrive/Amazon-ML-Challenge-2026/**/*", recursive=True):
    if os.path.isfile(f):
        name = os.path.basename(f).lower()

        if any(x in name for x in [
            "feature", "candidate", "train", "model", "catboost"
        ]):
            size_mb = os.path.getsize(f) / (1024**2)
            print(f"{size_mb:.2f} MB | {f}")

Searching for training feature/candidate files...

In [ ]:
!python3 /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
  --matching /content/amazon_ml_challenge/student_resource/output/matching_results.tsv \
  --candidate /content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv \
  --test-dir /content/amazon_ml_challenge/student_resource/dataset/test

ML Challenge 2026 — submission validator
  test dir: /content/amazon_ml_challenge/student_resource/dataset/test
  required S1 entities: 1732544
  matching_results.tsv: 1732544 rows (393607 empty, 1338937 non-empty).
  candidate_pairs.tsv: 1732544 rows (393607 empty, 1338937 non-empty).

WARNING: ID-existence check is OFF (the default) — not checking that matched/candidate IDs exist in the test set. Every other rule is still checked. Re-run with --check-ids to enable it (needs test_source2/3.tsv; uses more memory). A nonexistent ID only lowers your score, never rejects your submission.
PASS — no blocking issues found. Safe to submit.

In [ ]:
from google.colab import files

files.download(
    "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv"
)

In [ ]:
# Check what important objects/files are still available

import os

print("=== FILE CHECK ===")

paths = {
    "test_features file": "/content/amazon_ml_challenge/student_resource/test_features.pkl",
    "model folder": "/content/amazon_ml_challenge/student_resource/models",
    "candidate file": "/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv",
    "matching file": "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv",
}

for name, path in paths.items():
    print(f"{name}: {'YES' if os.path.exists(path) else 'NO'}")

print("\n=== MEMORY CHECK ===")

for var in ["test_features", "model", "s1_test", "pair_features",
            "normalize_advanced", "build_s1_key_maps",
            "collect_candidates_from_source"]:
    print(f"{var}: {'YES' if var in globals() else 'NO'}")

=== FILE CHECK ===
test_features file: NO
model folder: NO
candidate file: YES
matching file: YES

=== MEMORY CHECK ===
test_features: NO
model: NO
s1_test: NO
pair_features: NO
normalize_advanced: YES
build_s1_key_maps: YES
collect_candidates_from_source: YES

# DAY 1 — STRONG MODEL PIPELINE
## Step 1: Rebuild training validation

In [ ]:
# ============================================
# DAY 1 — STRONG MODEL PIPELINE
# STEP 1: Load 10,000 training S1 records
# ============================================

import pandas as pd
import numpy as np
from collections import defaultdict

TRAIN_S1 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source1.tsv"
TRAIN_S2 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source2.tsv"
TRAIN_S3 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source3.tsv"
GROUND_TRUTH = "/content/amazon_ml_challenge/student_resource/dataset/train/train_ground_truth.tsv"

# Load only 10,000 Source 1 records
train_s1_10k = pd.read_csv(
    TRAIN_S1,
    sep="\t",
    usecols=["entity_id", "business_name", "business_address", "country"],
    nrows=10000
)

print("Training S1 shape:", train_s1_10k.shape)
print(train_s1_10k.head())

# Build advanced blocking maps
s1_name_map = defaultdict(list)
s1_address_map = defaultdict(list)

for _, row in train_s1_10k.iterrows():

    sid = row["entity_id"]
    country = normalize_country(row["country"])

    name = normalize_advanced(row["business_name"])
    address = normalize_advanced(row["business_address"])

    if name:
        s1_name_map[(country, name)].append(sid)

    if address:
        s1_address_map[(country, address)].append(sid)

print("\nName keys:", len(s1_name_map))
print("Address keys:", len(s1_address_map))
print("S1 records:", len(train_s1_10k))

Training S1 shape: (10000, 4)
      entity_id            business_name  \
0  S1-925783039      Orelee's Barbershop
1  S1-773889195              Prime Money
2  S1-377745466            B+ Retail Inc
3  S1-133037285            Christ Chapel
4  S1-755362802  Prabhav Business Center

                                    business_address country
0             1795 Westchester Drive, High Point, NC      US
1                    17560 Ellis Road, Tahlequah, OK      US
2                1712 Montebello Avenue, Phoenix, AZ      US
3  2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD      US
4  797, Lake Town Block A, Kolkata, Howrah, West ...   India

Name keys: 9837
Address keys: 9997
S1 records: 10000

In [ ]:
# ============================================
# STEP 2: Generate training candidate pairs
# ============================================

from collections import defaultdict

def generate_training_candidates(source_path, source_name):
    candidates = []
    candidate_records = []

    print(f"\nScanning {source_name}...")

    for chunk_no, chunk in enumerate(
        pd.read_csv(
            source_path,
            sep="\t",
            usecols=[
                "entity_id",
                "business_name",
                "business_address",
                "country"
            ],
            chunksize=200_000
        )
    ):

        # Advanced normalization
        chunk["norm_name"] = chunk["business_name"].map(normalize_advanced)
        chunk["norm_address"] = chunk["business_address"].map(normalize_advanced)
        chunk["norm_country"] = chunk["country"].map(normalize_country)

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = row.norm_country
            name = row.norm_name
            address = row.norm_address

            matched_s1 = set()

            # Name blocking
            if name:
                matched_s1.update(
                    s1_name_map.get((country, name), [])
                )

            # Address blocking
            if address:
                matched_s1.update(
                    s1_address_map.get((country, address), [])
                )

            # Store only actual candidate pairs
            for sid in matched_s1:

                candidates.append((sid, eid))

                candidate_records.append({
                    "source1_entity_id": sid,
                    "candidate_entity_id": eid,
                    "business_name": row.business_name,
                    "business_address": row.business_address,
                    "country": row.country,
                    "source": source_name
                })

        if (chunk_no + 1) % 5 == 0:
            print(
                f"{source_name}: processed {(chunk_no + 1) * 200000:,} rows | "
                f"candidates: {len(candidates):,}"
            )

    print(f"{source_name} candidates: {len(candidates):,}")

    return candidates, candidate_records


# Source 2
train_candidates_s2, train_records_s2 = generate_training_candidates(
    TRAIN_S2,
    "S2"
)

# Source 3
train_candidates_s3, train_records_s3 = generate_training_candidates(
    TRAIN_S3,
    "S3"
)

print("\n================================")
print("CANDIDATE GENERATION COMPLETE")
print("================================")

print("S2 candidates:", len(train_candidates_s2))
print("S3 candidates:", len(train_candidates_s3))
print("Total candidates:", len(train_candidates_s2) + len(train_candidates_s3))

Scanning S2...
S2: processed 1,000,000 rows | candidates: 9,816
S2: processed 2,000,000 rows | candidates: 19,343
S2: processed 3,000,000 rows | candidates: 29,086
S2: processed 4,000,000 rows | candidates: 38,808
S2: processed 5,000,000 rows | candidates: 48,409
S2 candidates: 48,711

Scanning S3...
S3: processed 1,000,000 rows | candidates: 9,536
S3: processed 2,000,000 rows | candidates: 19,184
S3: processed 3,000,000 rows | candidates: 28,868
S3: processed 4,000,000 rows | candidates: 38,501
S3: processed 5,000,000 rows | candidates: 48,191
S3 candidates: 51,005

================================
CANDIDATE GENERATION COMPLETE
================================
S2 candidates: 48711
S3 candidates: 51005
Total candidates: 99716

In [ ]:
# ============================================
# STEP 3: Build candidate dataframe + labels
# ============================================

print("Building candidate dataframe...")

# Combine S2 + S3 candidate records
train_candidate_df = pd.DataFrame(
    train_records_s2 + train_records_s3
)

print("Candidate dataframe shape:", train_candidate_df.shape)

# Load only the ground-truth columns
gt = pd.read_csv(
    GROUND_TRUTH,
    sep="\t",
    usecols=["source1_entity_id", "matched_entity_ids"]
)

print("Ground truth shape:", gt.shape)
print(gt.head())

# Keep only the 10,000 S1 records we are validating
s1_ids = set(train_s1_10k["entity_id"])

gt_10k = gt[gt["source1_entity_id"].isin(s1_ids)].copy()

print("\nGround truth rows for our 10k S1:", len(gt_10k))

# Convert ground truth into a dictionary:
# S1 ID -> set of correct S2/S3 IDs
ground_truth_map = {}

for _, row in gt_10k.iterrows():

    sid = row["source1_entity_id"]
    matches = row["matched_entity_ids"]

    if pd.isna(matches) or str(matches).strip() == "":
        ground_truth_map[sid] = set()
    else:
        ground_truth_map[sid] = set(
            str(matches).split(",")
        )

# Create binary labels
train_candidate_df["label"] = train_candidate_df.apply(
    lambda row: int(
        row["candidate_entity_id"]
        in ground_truth_map.get(row["source1_entity_id"], set())
    ),
    axis=1
)

print("\n================================")
print("LABELING COMPLETE")
print("================================")

print("Total candidate pairs:", len(train_candidate_df))
print("Positive pairs:", int(train_candidate_df["label"].sum()))
print("Negative pairs:", int((train_candidate_df["label"] == 0).sum()))

print("\nPositive percentage:",
      round(train_candidate_df["label"].mean() * 100, 3), "%")

Building candidate dataframe...
Candidate dataframe shape: (99716, 6)
Ground truth shape: (2206821, 2)
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

Ground truth rows for our 10k S1: 10000

================================
LABELING COMPLETE
================================
Total candidate pairs: 99716
Positive pairs: 10885
Negative pairs: 88831

Positive percentage: 10.916 %

In [ ]:
# ============================================
# STEP 4: Build 9 ML features
# ============================================

from difflib import SequenceMatcher

print("Preparing feature dataframe...")

# Rename candidate columns for clarity
train_candidate_df = train_candidate_df.rename(
    columns={
        "business_name": "candidate_business_name",
        "business_address": "candidate_business_address",
        "country": "candidate_country"
    }
)

# Add Source 1 information
s1_feature_df = train_s1_10k[
    ["entity_id", "business_name", "business_address", "country"]
].rename(
    columns={
        "entity_id": "source1_entity_id",
        "business_name": "s1_business_name",
        "business_address": "s1_business_address",
        "country": "s1_country"
    }
)

train_candidate_df = train_candidate_df.merge(
    s1_feature_df,
    on="source1_entity_id",
    how="left"
)

print("Merged dataframe shape:", train_candidate_df.shape)


# --------------------------------------------
# Helper functions
# --------------------------------------------

def safe_text(x):
    if pd.isna(x):
        return ""
    return str(x)


def similarity(a, b):
    a = safe_text(a)
    b = safe_text(b)

    if not a or not b:
        return 0.0

    return SequenceMatcher(None, a, b).ratio()


def token_overlap(a, b):
    a = set(safe_text(a).split())
    b = set(safe_text(b).split())

    if not a or not b:
        return 0.0

    return len(a & b) / len(a | b)


# --------------------------------------------
# Normalize text
# --------------------------------------------

train_candidate_df["s1_name_norm"] = (
    train_candidate_df["s1_business_name"]
    .map(normalize_advanced)
)

train_candidate_df["candidate_name_norm"] = (
    train_candidate_df["candidate_business_name"]
    .map(normalize_advanced)
)

train_candidate_df["s1_address_norm"] = (
    train_candidate_df["s1_business_address"]
    .map(normalize_advanced)
)

train_candidate_df["candidate_address_norm"] = (
    train_candidate_df["candidate_business_address"]
    .map(normalize_advanced)
)

train_candidate_df["s1_country_norm"] = (
    train_candidate_df["s1_country"]
    .map(normalize_country)
)

train_candidate_df["candidate_country_norm"] = (
    train_candidate_df["candidate_country"]
    .map(normalize_country)
)


# --------------------------------------------
# 1. Exact features
# --------------------------------------------

train_candidate_df["name_exact"] = (
    train_candidate_df["s1_name_norm"]
    == train_candidate_df["candidate_name_norm"]
).astype(int)

train_candidate_df["address_exact"] = (
    train_candidate_df["s1_address_norm"]
    == train_candidate_df["candidate_address_norm"]
).astype(int)

train_candidate_df["country_exact"] = (
    train_candidate_df["s1_country_norm"]
    == train_candidate_df["candidate_country_norm"]
).astype(int)


# --------------------------------------------
# 2. Similarity features
# --------------------------------------------

print("Calculating name similarity...")

train_candidate_df["name_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        train_candidate_df["s1_name_norm"],
        train_candidate_df["candidate_name_norm"]
    )
]

print("Calculating address similarity...")

train_candidate_df["address_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        train_candidate_df["s1_address_norm"],
        train_candidate_df["candidate_address_norm"]
    )
]


# --------------------------------------------
# 3. Token overlap
# --------------------------------------------

print("Calculating token overlap...")

train_candidate_df["name_token_overlap"] = [
    token_overlap(a, b)
    for a, b in zip(
        train_candidate_df["s1_name_norm"],
        train_candidate_df["candidate_name_norm"]
    )
]

train_candidate_df["address_token_overlap"] = [
    token_overlap(a, b)
    for a, b in zip(
        train_candidate_df["s1_address_norm"],
        train_candidate_df["candidate_address_norm"]
    )
]


# --------------------------------------------
# 4. Length differences
# --------------------------------------------

train_candidate_df["name_length_diff"] = (
    train_candidate_df["s1_name_norm"].str.len()
    -
    train_candidate_df["candidate_name_norm"].str.len()
).abs()

train_candidate_df["address_length_diff"] = (
    train_candidate_df["s1_address_norm"].str.len()
    -
    train_candidate_df["candidate_address_norm"].str.len()
).abs()


# --------------------------------------------
# Final feature list
# --------------------------------------------

FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_length_diff",
    "address_length_diff"
]

print("\n================================")
print("FEATURE ENGINEERING COMPLETE")
print("================================")

print("Features:", FEATURES)
print("Feature dataframe shape:", train_candidate_df.shape)

print("\nFeature preview:")
print(train_candidate_df[FEATURES + ["label"]].head())

print("\nMissing values:")
print(train_candidate_df[FEATURES].isna().sum())

Preparing feature dataframe...
Merged dataframe shape: (99716, 10)
Calculating name similarity...
Calculating address similarity...
Calculating token overlap...

================================
FEATURE ENGINEERING COMPLETE
================================
Features: ['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_length_diff', 'address_length_diff']
Feature dataframe shape: (99716, 25)

Feature preview:
   name_exact  address_exact  country_exact  name_similarity  \
0           1              0              1              1.0
1           1              0              1              1.0
2           1              0              1              1.0
3           1              0              1              1.0
4           1              0              1              1.0

   address_similarity  name_token_overlap  address_token_overlap  \
0            0.192593                 1.0                    0.0
1            0.290909                 1.0                    0.0
2            0.392857                 1.0                    0.1
3            0.271186                 1.0                    0.0
4            0.297872                 1.0                    0.0

   name_length_diff  address_length_diff  label
0                 0                   43      0
1                 0                    7      0
2                 0                    2      0
3                 0                    9      0
4                 0                    3      0

Missing values:
name_exact               0
address_exact            0
country_exact            0
name_similarity          0
address_similarity       0
name_token_overlap       0
address_token_overlap    0
name_length_diff         0
address_length_diff      0
dtype: int64

In [ ]:
# ============================================
# STEP 5: Train CatBoost + Entity-level F0.5
# ============================================

from catboost import CatBoostClassifier
from sklearn.metrics import precision_score, recall_score
import numpy as np

# --------------------------------------------
# 1. Split by Source-1 entity
# --------------------------------------------

all_s1_ids = train_s1_10k["entity_id"].unique()

rng = np.random.RandomState(42)
rng.shuffle(all_s1_ids)

split_point = int(len(all_s1_ids) * 0.80)

train_s1_ids = set(all_s1_ids[:split_point])
val_s1_ids = set(all_s1_ids[split_point:])

train_df = train_candidate_df[
    train_candidate_df["source1_entity_id"].isin(train_s1_ids)
].copy()

val_df = train_candidate_df[
    train_candidate_df["source1_entity_id"].isin(val_s1_ids)
].copy()

print("Training S1 entities:", len(train_s1_ids))
print("Validation S1 entities:", len(val_s1_ids))

print("Training candidate pairs:", len(train_df))
print("Validation candidate pairs:", len(val_df))


# --------------------------------------------
# 2. Prepare X / y
# --------------------------------------------

X_train = train_df[FEATURES]
y_train = train_df["label"]

X_val = val_df[FEATURES]
y_val = val_df["label"]


# --------------------------------------------
# 3. Train CatBoost
# --------------------------------------------

model = CatBoostClassifier(
    iterations=300,
    depth=7,
    learning_rate=0.08,
    loss_function="Logloss",
    eval_metric="Logloss",
    random_seed=42,
    verbose=False,
    allow_writing_files=False
)

print("\nTraining CatBoost...")

model.fit(
    X_train,
    y_train,
    eval_set=(X_val, y_val),
    early_stopping_rounds=50,
    verbose=False
)

print("Training complete.")
print("Best iteration:", model.get_best_iteration())


# --------------------------------------------
# 4. Validation probabilities
# --------------------------------------------

val_df["probability"] = model.predict_proba(X_val)[:, 1]


# --------------------------------------------
# 5. Entity-level Macro F0.5
# --------------------------------------------

def entity_macro_f05(
    val_candidates,
    threshold,
    ground_truth_map,
    validation_s1_ids
):

    scores = []
    all_true = []
    all_pred = []

    for sid in validation_s1_ids:

        # True matches
        true_set = ground_truth_map.get(sid, set())

        # Candidate predictions above threshold
        rows = val_candidates[
            (val_candidates["source1_entity_id"] == sid) &
            (val_candidates["probability"] >= threshold)
        ]

        pred_set = set(rows["candidate_entity_id"])

        tp = len(true_set & pred_set)
        fp = len(pred_set - true_set)
        fn = len(true_set - pred_set)

        # Special singleton/no-match case
        if len(true_set) == 0 and len(pred_set) == 0:
            score = 1.0

        else:
            precision = (
                tp / (tp + fp)
                if (tp + fp) > 0
                else 0.0
            )

            recall = (
                tp / (tp + fn)
                if (tp + fn) > 0
                else 0.0
            )

            if precision == 0 and recall == 0:
                score = 0.0
            else:
                score = (
                    1.25 * precision * recall
                    / (0.25 * precision + recall)
                )

        scores.append(score)

        all_true.extend(true_set)
        all_pred.extend(pred_set)

    macro_f05 = np.mean(scores)

    return macro_f05


# --------------------------------------------
# 6. Test threshold = 0.50
# --------------------------------------------

threshold = 0.50

macro_f05 = entity_macro_f05(
    val_df,
    threshold,
    ground_truth_map,
    val_s1_ids
)

pred_binary = (
    val_df["probability"] >= threshold
).astype(int)

precision = precision_score(
    y_val,
    pred_binary,
    zero_division=0
)

recall = recall_score(
    y_val,
    pred_binary,
    zero_division=0
)

print("\n================================")
print("VALIDATION RESULTS")
print("================================")

print(f"Threshold       : {threshold}")
print(f"Pair Precision  : {precision:.6f}")
print(f"Pair Recall     : {recall:.6f}")
print(f"Macro F0.5      : {macro_f05:.6f}")

Training S1 entities: 8000
Validation S1 entities: 2000
Training candidate pairs: 79495
Validation candidate pairs: 20221

Training CatBoost...
Training complete.
Best iteration: 216

================================
VALIDATION RESULTS
================================
Threshold       : 0.5
Pair Precision  : 0.980715
Pair Recall     : 0.943012
Macro F0.5      : 0.513402

In [ ]:
# ============================================
# STEP 5B: Measure BLOCKING / CANDIDATE RECALL
# ============================================

total_true_matches = 0
covered_true_matches = 0

entity_results = []

for sid in val_s1_ids:

    # All real matches from ground truth
    true_set = ground_truth_map.get(sid, set())

    # Candidates generated by our blocking
    candidate_set = set(
        val_df[
            val_df["source1_entity_id"] == sid
        ]["candidate_entity_id"]
    )

    covered = true_set & candidate_set

    total_true_matches += len(true_set)
    covered_true_matches += len(covered)

    entity_results.append({
        "source1_entity_id": sid,
        "true_matches": len(true_set),
        "candidates": len(candidate_set),
        "covered_true_matches": len(covered),
        "missed_true_matches": len(true_set - candidate_set)
    })


candidate_recall = (
    covered_true_matches / total_true_matches
    if total_true_matches > 0 else 0
)

entity_results_df = pd.DataFrame(entity_results)

print("================================")
print("BLOCKING RECALL")
print("================================")

print("Validation S1 entities:", len(val_s1_ids))
print("Total true matches:", total_true_matches)
print("True matches found in candidates:", covered_true_matches)
print("True matches missed by blocking:",
      total_true_matches - covered_true_matches)

print(
    f"\nCandidate Recall: {candidate_recall:.6f}"
)

print(
    f"Candidate Recall: {candidate_recall * 100:.2f}%"
)

print("\nEntities with missed true matches:",
      (entity_results_df["missed_true_matches"] > 0).sum())

print("\nEntities with zero candidates:",
      (entity_results_df["candidates"] == 0).sum())

================================
BLOCKING RECALL
================================
Validation S1 entities: 2000
Total true matches: 7059
True matches found in candidates: 2211
True matches missed by blocking: 4848

Candidate Recall: 0.313217
Candidate Recall: 31.32%

Entities with missed true matches: 1783

Entities with zero candidates: 446

In [ ]:
# ============================================
# STEP 6: Analyze MISSED TRUE MATCHES
# ============================================

# Get validation S1 records
val_s1_df = train_s1_10k[
    train_s1_10k["entity_id"].isin(val_s1_ids)
].copy()

# Create lookup for S1 information
s1_lookup = val_s1_df.set_index("entity_id").to_dict("index")

# Collect the actual true-match IDs that blocking missed
missed_pairs = []

for sid in val_s1_ids:

    true_set = ground_truth_map.get(sid, set())

    candidate_set = set(
        val_df[
            val_df["source1_entity_id"] == sid
        ]["candidate_entity_id"]
    )

    missed = true_set - candidate_set

    for eid in missed:
        missed_pairs.append((sid, eid))

print("Missed true pairs:", len(missed_pairs))

# We need to retrieve the actual Source 2/3 records
missed_ids = set(eid for _, eid in missed_pairs)

print("Unique missed entity IDs:", len(missed_ids))

# ------------------------------------------------
# Scan Source 2 and Source 3 to retrieve them
# ------------------------------------------------

missed_records = {}

def collect_missed_records(path, source_name):

    print(f"\nScanning {source_name} for missed true records...")

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200_000
    ):

        found = chunk[
            chunk["entity_id"].isin(missed_ids)
        ]

        for _, row in found.iterrows():

            missed_records[row["entity_id"]] = {
                "business_name": row["business_name"],
                "business_address": row["business_address"],
                "country": row["country"],
                "source": source_name
            }

    print(
        f"{source_name}: retrieved "
        f"{sum(1 for x in missed_records.values() if x['source'] == source_name):,}"
    )


collect_missed_records(TRAIN_S2, "S2")
collect_missed_records(TRAIN_S3, "S3")

print("\nRetrieved missed records:", len(missed_records))


# ------------------------------------------------
# Build comparison table
# ------------------------------------------------

analysis_rows = []

for sid, eid in missed_pairs:

    if sid not in s1_lookup:
        continue

    if eid not in missed_records:
        continue

    s1 = s1_lookup[sid]
    target = missed_records[eid]

    s1_name = normalize_advanced(s1["business_name"])
    target_name = normalize_advanced(target["business_name"])

    s1_address = normalize_advanced(s1["business_address"])
    target_address = normalize_advanced(target["business_address"])

    analysis_rows.append({
        "source1_entity_id": sid,
        "matched_entity_id": eid,
        "s1_name": s1["business_name"],
        "matched_name": target["business_name"],
        "s1_address": s1["business_address"],
        "matched_address": target["business_address"],
        "s1_country": s1["country"],
        "matched_country": target["country"],
        "name_exact_after_normalization": int(
            s1_name == target_name and s1_name != ""
        ),
        "address_exact_after_normalization": int(
            s1_address == target_address and s1_address != ""
        )
    })

missed_analysis_df = pd.DataFrame(analysis_rows)

print("\n================================")
print("MISSED MATCH ANALYSIS")
print("================================")

print("Rows:", len(missed_analysis_df))

print(
    "\nName exact:",
    missed_analysis_df[
        "name_exact_after_normalization"
    ].sum()
)

print(
    "Address exact:",
    missed_analysis_df[
        "address_exact_after_normalization"
    ].sum()
)

print("\nSample missed matches:")
display(
    missed_analysis_df.head(20)
)

Missed true pairs: 4848
Unique missed entity IDs: 4848

Scanning S2 for missed true records...
S2: retrieved 2,122

Scanning S3 for missed true records...
S3: retrieved 2,726

Retrieved missed records: 4848

================================
MISSED MATCH ANALYSIS
================================
Rows: 4848

Name exact: 0
Address exact: 0

Sample missed matches:

,source1_entity_id,matched_entity_id,s1_name,matched_name,s1_address,matched_address,s1_country,matched_country,name_exact_after_normalization,address_exact_after_normalization
0,S1-73295122,S3-242907636,Lundell Marshall,lundellmarshall.com,"2460 Tyler Avenue, Ogden City, UT","Tyler Avenue, Ogden, Utah",US,US,0,0
1,S1-73295122,S3-177872131,Lundell Marshall,Lundell Marsalhl,"2460 Tyler Avenue, Ogden City, UT","002460 Tyler Ave, Ogden City, Utah",US,US,0,0
2,S1-96122582,S2-49443670,Unified Harbor Manufacturing LLC,UNIFIED HARBOR,"IN, 131 Canal Lane, Fl 0, West Harrison","131 CANAL LN, NULL, WEST HARRISON, IN",US,US,0,0
3,S1-96122582,S3-745123312,Unified Harbor Manufacturing LLC,Unified Harbor,"IN, 131 Canal Lane, Fl 0, West Harrison","#131 Canal Ln, Floor 0, West Harrison, Indiana",US,US,0,0
4,S1-156289214,S3-579334803,Prissie Shannon Legacy Municipals,Prissie Saathon Legacy Municipals,"Tucson, 1452 Sonora Street, AZ","Arizona, 1452 Sonora Street, Tucson",US,US,0,0
5,S1-156289214,S2-591902770,Prissie Shannon Legacy Municipals,Prissie Shannon Legacy Municipals Ltd,"Tucson, 1452 Sonora Street, AZ","AZ, 1452 SONORA STREET, TUCSON",US,US,0,0
6,S1-156289214,S3-755000623,Prissie Shannon Legacy Municipals,Prissie Shnanho Legacy Municipals,"Tucson, 1452 Sonora Street, AZ","1452 Sonora St, Tucson, Arizona",US,US,0,0
7,S1-156289214,S2-191982536,Prissie Shannon Legacy Municipals,Prissie Sahnnon Legacy Municipals,"Tucson, 1452 Sonora Street, AZ","1452 SONROA STREET, TUCSON, AZ",US,US,0,0
8,S1-606887450,S2-172794798,Strategic Golden Lifesciences LLC,Center Strategic Lifesciences LLC,"2000 Lapham Road, Aurora, NY","200 LAPHAM RD, EAST AURORA, NY",US,US,0,0
9,S1-606887450,S3-775002077,Strategic Golden Lifesciences LLC,Center Strategic Golden LLC,"2000 Lapham Road, Aurora, NY","Aurora, New York, 200 Lapham Road",US,US,0,0
10,S1-606887450,S2-547006183,Strategic Golden Lifesciences LLC,Strategic Gólden,"2000 Lapham Road, Aurora, NY","LAPHAM RD, EAST AURORA, NY",US,US,0,0
11,S1-606887450,S3-265730626,Strategic Golden Lifesciences LLC,Strategic Godldeen Lifesciences LLC,"2000 Lapham Road, Aurora, NY",NaN,US,US,0,0
12,S1-260429958,S3-158505244,Sun Blue Systems Private Limited,Sun Limited Systems Private Blue,"House No. 40/127, Top Khana Bazar, Cantt., Kan...","House No. 30/127, Top Khana Bazar, Cantt., Kan...",India,India,0,0
13,S1-260429958,S2-645127769,Sun Blue Systems Private Limited,सन ब्लू सिस्टम्स प्राइवेट लिमिटेड,"House No. 40/127, Top Khana Bazar, Cantt., Kan...","DOOR NO 378. HOUSE NO. 40/127, TOP KHANA BAZAR...",India,India,0,0
14,S1-260429958,S3-273069747,Sun Blue Systems Private Limited,Sun Blue Systems Private,"House No. 40/127, Top Khana Bazar, Cantt., Kan...","House No. 30/127, Top Khana Bazar, Cantt., Kan...",India,India,0,0
15,S1-260429958,S3-446594103,Sun Blue Systems Private Limited,SBS,"House No. 40/127, Top Khana Bazar, Cantt., Kan...","Kanpur Nagar, Uttar Pradesh, Top Khana Bazar, ...",India,India,0,0
16,S1-260429958,S2-726676586,Sun Blue Systems Private Limited,सन ब्लू सिस्टम्स प्राइवेट लिमिटेड,"House No. 40/127, Top Khana Bazar, Cantt., Kan...","TOP KHANA BAZAR, DOOR NO 378. HOUES NO. 40/127...",India,India,0,0
17,S1-260429958,S3-962276960,Sun Blue Systems Private Limited,सन ब्लू सिस्टम्स प्राइवेट लिमिटेड,"House No. 40/127, Top Khana Bazar, Cantt., Kan...","House No. 30/127, Cantt., Kanpur Nagar, उत्तर ...",India,India,0,0
18,S1-127932197,S3-906708453,Historical Project,Nylakelodelta - 3660262362,"364 Northampton Road, Unit A, Amherst, MA","364C Northampton Road, Unit A, Amherst, Massac...",US,US,0,0
19,S1-287381087,S2-900439012,Super Technology Pvt Ltd,सुपर टेक्नोलॉजी प्रा. लि.,"10174/1A Gurdwara Road, Karolbagh, New Delhi, ...","1A GURDWARA ROAD, KAROLBAGH, NEW DELHI, दिल्ली",India,India,0,0

In [ ]:
# ============================================
# STEP 7: Test additional blocking keys
# ============================================

import re
from collections import Counter


def get_tokens(text):
    text = normalize_advanced(text)
    return set(
        t for t in text.split()
        if len(t) >= 4
    )


def get_numbers(text):
    if pd.isna(text):
        return set()
    return set(re.findall(r"\d+", str(text)))


def get_postal_codes(text):
    if pd.isna(text):
        return set()

    text = str(text)

    # US ZIP / ZIP+4
    us = set(re.findall(r"\b\d{5}(?:-\d{4})?\b", text))

    # Indian PIN
    india = set(re.findall(r"\b[1-9]\d{5}\b", text))

    return us | india


# --------------------------------------------
# Calculate key overlap for missed matches
# --------------------------------------------

results = []

for _, row in missed_analysis_df.iterrows():

    name1 = normalize_advanced(row["s1_name"])
    name2 = normalize_advanced(row["matched_name"])

    addr1 = normalize_advanced(row["s1_address"])
    addr2 = normalize_advanced(row["matched_address"])

    name_tokens_1 = get_tokens(name1)
    name_tokens_2 = get_tokens(name2)

    addr_tokens_1 = get_tokens(addr1)
    addr_tokens_2 = get_tokens(addr2)

    numbers_1 = get_numbers(addr1)
    numbers_2 = get_numbers(addr2)

    postal_1 = get_postal_codes(addr1)
    postal_2 = get_postal_codes(addr2)

    results.append({

        # Name token overlap
        "name_token_overlap":
            len(name_tokens_1 & name_tokens_2) > 0,

        # Two or more common name tokens
        "name_2plus_tokens":
            len(name_tokens_1 & name_tokens_2) >= 2,

        # Address token overlap
        "address_token_overlap":
            len(addr_tokens_1 & addr_tokens_2) > 0,

        # Two or more address tokens
        "address_2plus_tokens":
            len(addr_tokens_1 & addr_tokens_2) >= 2,

        # Shared number
        "shared_address_number":
            len(numbers_1 & numbers_2) > 0,

        # Shared postal code
        "shared_postal":
            len(postal_1 & postal_2) > 0,

        # Combined signals
        "name_or_address_token":
            (
                len(name_tokens_1 & name_tokens_2) > 0
                or
                len(addr_tokens_1 & addr_tokens_2) > 0
            ),

        "strong_combined":
            (
                len(name_tokens_1 & name_tokens_2) >= 1
                and
                len(addr_tokens_1 & addr_tokens_2) >= 1
            )
    })


blocking_analysis = pd.DataFrame(results)

print("================================")
print("MISSED MATCH RECOVERY ANALYSIS")
print("================================")

for col in blocking_analysis.columns:

    count = blocking_analysis[col].sum()
    percentage = count / len(blocking_analysis) * 100

    print(
        f"{col:25s} : "
        f"{count:5d} / {len(blocking_analysis)} "
        f"({percentage:.2f}%)"
    )

================================
MISSED MATCH RECOVERY ANALYSIS
================================
name_token_overlap        :  3772 / 4848 (77.81%)
name_2plus_tokens         :  2856 / 4848 (58.91%)
address_token_overlap     :  4601 / 4848 (94.91%)
address_2plus_tokens      :  4235 / 4848 (87.36%)
shared_address_number     :  3785 / 4848 (78.07%)
shared_postal             :   218 / 4848 (4.50%)
name_or_address_token     :  4841 / 4848 (99.86%)
strong_combined           :  3532 / 4848 (72.85%)

In [ ]:
# ============================================
# STEP 8: Build token-frequency statistics
# ============================================

from collections import Counter
import re

name_token_freq = Counter()
address_token_freq = Counter()

def useful_tokens(text):
    text = normalize_advanced(text)

    tokens = set(
        t for t in text.split()
        if len(t) >= 4 and not t.isdigit()
    )

    return tokens


def scan_token_frequency(path, source_name):

    print(f"\nScanning {source_name} for token frequencies...")

    processed = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "business_name",
            "business_address"
        ],
        chunksize=200_000
    ):

        for name in chunk["business_name"]:
            for token in useful_tokens(name):
                name_token_freq[token] += 1

        for address in chunk["business_address"]:
            for token in useful_tokens(address):
                address_token_freq[token] += 1

        processed += len(chunk)

        if processed % 1_000_000 == 0:
            print(
                f"{source_name}: "
                f"{processed:,} rows processed"
            )


scan_token_frequency(TRAIN_S2, "S2")
scan_token_frequency(TRAIN_S3, "S3")


print("\n================================")
print("TOKEN FREQUENCY COMPLETE")
print("================================")

print("Unique name tokens:", len(name_token_freq))
print("Unique address tokens:", len(address_token_freq))

print("\nMost common NAME tokens:")
print(name_token_freq.most_common(20))

print("\nMost common ADDRESS tokens:")
print(address_token_freq.most_common(20))

Scanning S2 for token frequencies...
S2: 1,000,000 rows processed
S2: 2,000,000 rows processed
S2: 3,000,000 rows processed
S2: 4,000,000 rows processed
S2: 5,000,000 rows processed

Scanning S3 for token frequencies...
S3: 1,000,000 rows processed
S3: 2,000,000 rows processed
S3: 3,000,000 rows processed
S3: 4,000,000 rows processed
S3: 5,000,000 rows processed

================================
TOKEN FREQUENCY COMPLETE
================================
Unique name tokens: 1351071
Unique address tokens: 628941

Most common NAME tokens:
[('limited', 1202275), ('private', 1168000), ('center', 414507), ('partners', 314651), ('services', 311864), ('group', 284006), ('corp', 282009), ('india', 223652), ('holdings', 196043), ('care', 184611), ('associates', 149902), ('corporation', 120720), ('service', 119214), ('enterprises', 106200), ('health', 104790), ('industries', 101347), ('clinic', 94344), ('ventures', 93706), ('solutions', 87385), ('trading', 86894)]

Most common ADDRESS tokens:
[('city', 650528), ('floor', 597386), ('nagar', 554836), ('delhi', 535364), ('north', 399797), ('west', 392422), ('mumbai', 360516), ('maharashtra', 343014), ('plot', 341994), ('texas', 294859), ('null', 262641), ('pradesh', 258312), ('bangalore', 240916), ('york', 234392), ('door', 221838), ('unit', 219015), ('carolina', 216961), ('south', 213493), ('block', 202704), ('park', 201844)]

In [ ]:
# ============================================
# STEP 9: Test rare-token thresholds
# ============================================

def get_token_set(text):
    text = normalize_advanced(text)

    return set(
        token
        for token in text.split()
        if len(token) >= 4 and not token.isdigit()
    )


# Build token sets for the missed true pairs
missed_token_rows = []

for _, row in missed_analysis_df.iterrows():

    s1_name_tokens = get_token_set(row["s1_name"])
    match_name_tokens = get_token_set(row["matched_name"])

    s1_addr_tokens = get_token_set(row["s1_address"])
    match_addr_tokens = get_token_set(row["matched_address"])

    missed_token_rows.append({
        "name_shared":
            s1_name_tokens & match_name_tokens,

        "address_shared":
            s1_addr_tokens & match_addr_tokens
    })


# --------------------------------------------
# Test different rarity thresholds
# --------------------------------------------

thresholds = [5, 10, 20, 50, 100, 250, 500, 1000]

print("================================")
print("RARE TOKEN RECOVERY")
print("================================")

print(
    f"{'Threshold':>10} | "
    f"{'Name':>8} | "
    f"{'Address':>10} | "
    f"{'Either':>8}"
)

print("-" * 50)

for threshold in thresholds:

    name_recovered = 0
    address_recovered = 0
    either_recovered = 0

    for row in missed_token_rows:

        name_ok = any(
            name_token_freq.get(token, 10**9)
            <= threshold
            for token in row["name_shared"]
        )

        address_ok = any(
            address_token_freq.get(token, 10**9)
            <= threshold
            for token in row["address_shared"]
        )

        if name_ok:
            name_recovered += 1

        if address_ok:
            address_recovered += 1

        if name_ok or address_ok:
            either_recovered += 1

    print(
        f"{threshold:>10} | "
        f"{name_recovered:>5} "
        f"({name_recovered / len(missed_token_rows) * 100:5.1f}%) | "
        f"{address_recovered:>5} "
        f"({address_recovered / len(missed_token_rows) * 100:5.1f}%) | "
        f"{either_recovered:>5} "
        f"({either_recovered / len(missed_token_rows) * 100:5.1f}%)"
    )

================================
RARE TOKEN RECOVERY
================================
 Threshold |     Name |    Address |   Either
--------------------------------------------------
         5 |    24 (  0.5%) |   289 (  6.0%) |   311 (  6.4%)
        10 |    68 (  1.4%) |   508 ( 10.5%) |   569 ( 11.7%)
        20 |   185 (  3.8%) |   773 ( 15.9%) |   927 ( 19.1%)
        50 |   428 (  8.8%) |  1095 ( 22.6%) |  1413 ( 29.1%)
       100 |   672 ( 13.9%) |  1392 ( 28.7%) |  1810 ( 37.3%)
       250 |  1229 ( 25.4%) |  1825 ( 37.6%) |  2550 ( 52.6%)
       500 |  1438 ( 29.7%) |  2187 ( 45.1%) |  2939 ( 60.6%)
      1000 |  1585 ( 32.7%) |  2643 ( 54.5%) |  3323 ( 68.5%)

In [ ]:
# ============================================
# STEP 10: Estimate candidate volume
# ============================================

def get_rare_tokens(text, freq_counter, threshold):
    tokens = get_token_set(text)

    return {
        token
        for token in tokens
        if freq_counter.get(token, 10**9) <= threshold
    }


# Build the 10k S1 token sets
s1_token_stats = []

for _, row in train_s1_10k.iterrows():

    name_tokens = get_rare_tokens(
        row["business_name"],
        name_token_freq,
        1000
    )

    address_tokens = get_rare_tokens(
        row["business_address"],
        address_token_freq,
        1000
    )

    s1_token_stats.append({
        "entity_id": row["entity_id"],
        "name_tokens": name_tokens,
        "address_tokens": address_tokens
    })


# --------------------------------------------
# Estimate volume for different thresholds
# --------------------------------------------

thresholds = [50, 100, 250, 500, 1000]

print("================================")
print("ESTIMATED CANDIDATE VOLUME")
print("================================")

for threshold in thresholds:

    estimated_name = 0
    estimated_address = 0

    for _, row in train_s1_10k.iterrows():

        name_tokens = get_rare_tokens(
            row["business_name"],
            name_token_freq,
            threshold
        )

        address_tokens = get_rare_tokens(
            row["business_address"],
            address_token_freq,
            threshold
        )

        estimated_name += sum(
            name_token_freq[token]
            for token in name_tokens
        )

        estimated_address += sum(
            address_token_freq[token]
            for token in address_tokens
        )

    estimated_total = estimated_name + estimated_address

    print(
        f"\nThreshold {threshold}:"
    )
    print(
        f"  Name candidate upper estimate    : "
        f"{estimated_name:,}"
    )
    print(
        f"  Address candidate upper estimate : "
        f"{estimated_address:,}"
    )
    print(
        f"  Combined upper estimate          : "
        f"{estimated_total:,}"
    )

================================
ESTIMATED CANDIDATE VOLUME
================================

Threshold 50:
  Name candidate upper estimate    : 27,581
  Address candidate upper estimate : 52,426
  Combined upper estimate          : 80,007

Threshold 100:
  Name candidate upper estimate    : 81,534
  Address candidate upper estimate : 126,945
  Combined upper estimate          : 208,479

Threshold 250:
  Name candidate upper estimate    : 382,631
  Address candidate upper estimate : 417,942
  Combined upper estimate          : 800,573

Threshold 500:
  Name candidate upper estimate    : 647,657
  Address candidate upper estimate : 1,064,435
  Combined upper estimate          : 1,712,092

Threshold 1000:
  Name candidate upper estimate    : 1,166,065
  Address candidate upper estimate : 2,873,105
  Combined upper estimate          : 4,039,170

In [ ]:
# ============================================
# STEP 11: Build rare-token indexes
# ============================================

from collections import defaultdict

RARE_THRESHOLD = 250

name_token_index_s2 = defaultdict(set)
address_token_index_s2 = defaultdict(set)

name_token_index_s3 = defaultdict(set)
address_token_index_s3 = defaultdict(set)


def add_tokens_to_index(
    text,
    entity_id,
    index,
    frequency_counter,
    threshold
):
    tokens = get_token_set(text)

    for token in tokens:

        if frequency_counter.get(token, 10**9) <= threshold:
            index[token].add(entity_id)


def build_rare_indexes(
    path,
    source_name,
    name_index,
    address_index
):

    print(f"\nBuilding rare-token indexes for {source_name}...")

    processed = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address"
        ],
        chunksize=200_000
    ):

        for row in chunk.itertuples(index=False):

            add_tokens_to_index(
                row.business_name,
                row.entity_id,
                name_index,
                name_token_freq,
                RARE_THRESHOLD
            )

            add_tokens_to_index(
                row.business_address,
                row.entity_id,
                address_index,
                address_token_freq,
                RARE_THRESHOLD
            )

        processed += len(chunk)

        if processed % 1_000_000 == 0:
            print(
                f"{source_name}: "
                f"{processed:,} rows"
            )

    print(
        f"{source_name} indexes complete."
    )


build_rare_indexes(
    TRAIN_S2,
    "S2",
    name_token_index_s2,
    address_token_index_s2
)

build_rare_indexes(
    TRAIN_S3,
    "S3",
    name_token_index_s3,
    address_token_index_s3
)


print("\n================================")
print("RARE TOKEN INDEXES COMPLETE")
print("================================")

print(
    "S2 name tokens:",
    len(name_token_index_s2)
)

print(
    "S2 address tokens:",
    len(address_token_index_s2)
)

print(
    "S3 name tokens:",
    len(name_token_index_s3)
)

print(
    "S3 address tokens:",
    len(address_token_index_s3)
)

Building rare-token indexes for S2...
S2: 1,000,000 rows
S2: 2,000,000 rows
S2: 3,000,000 rows
S2: 4,000,000 rows
S2: 5,000,000 rows
S2 indexes complete.

Building rare-token indexes for S3...
S3: 1,000,000 rows
S3: 2,000,000 rows
S3: 3,000,000 rows
S3: 4,000,000 rows
S3: 5,000,000 rows
S3 indexes complete.

================================
RARE TOKEN INDEXES COMPLETE
================================
S2 name tokens: 737028
S2 address tokens: 507247
S3 name tokens: 788505
S3 address tokens: 479029

In [ ]:
# ============================================
# STEP 12: Improved Blocking V2
# Rare tokens <= 250 + Country
# ============================================

RARE_THRESHOLD_V2 = 250

# --------------------------------------------
# Build country-aware token maps for
# validation S1 records
# --------------------------------------------

val_name_token_map = defaultdict(set)
val_address_token_map = defaultdict(set)

val_exact_name_map = defaultdict(set)
val_exact_address_map = defaultdict(set)

for _, row in val_s1_df.iterrows():

    sid = row["entity_id"]
    country = normalize_country(row["country"])

    name = normalize_advanced(row["business_name"])
    address = normalize_advanced(row["business_address"])

    # Exact blocking
    if name:
        val_exact_name_map[(country, name)].add(sid)

    if address:
        val_exact_address_map[(country, address)].add(sid)

    # Rare name tokens
    for token in get_token_set(name):

        if name_token_freq.get(token, 10**9) <= RARE_THRESHOLD_V2:
            val_name_token_map[(country, token)].add(sid)

    # Rare address tokens
    for token in get_token_set(address):

        if address_token_freq.get(token, 10**9) <= RARE_THRESHOLD_V2:
            val_address_token_map[(country, token)].add(sid)


print("S1 exact name keys:",
      len(val_exact_name_map))

print("S1 exact address keys:",
      len(val_exact_address_map))

print("S1 rare name keys:",
      len(val_name_token_map))

print("S1 rare address keys:",
      len(val_address_token_map))


# --------------------------------------------
# Generate V2 candidates
# --------------------------------------------

v2_candidates = defaultdict(set)


def scan_for_v2_candidates(path, source_name):

    print(f"\nScanning {source_name} for V2 candidates...")

    processed = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200_000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = normalize_country(row.country)

            name = normalize_advanced(row.business_name)
            address = normalize_advanced(row.business_address)

            matched_s1 = set()

            # --------------------------------
            # Exact name
            # --------------------------------
            if name:
                matched_s1.update(
                    val_exact_name_map.get(
                        (country, name),
                        set()
                    )
                )

            # --------------------------------
            # Exact address
            # --------------------------------
            if address:
                matched_s1.update(
                    val_exact_address_map.get(
                        (country, address),
                        set()
                    )
                )

            # --------------------------------
            # Rare name tokens
            # --------------------------------
            for token in get_token_set(name):

                if name_token_freq.get(
                    token,
                    10**9
                ) <= RARE_THRESHOLD_V2:

                    matched_s1.update(
                        val_name_token_map.get(
                            (country, token),
                            set()
                        )
                    )

            # --------------------------------
            # Rare address tokens
            # --------------------------------
            for token in get_token_set(address):

                if address_token_freq.get(
                    token,
                    10**9
                ) <= RARE_THRESHOLD_V2:

                    matched_s1.update(
                        val_address_token_map.get(
                            (country, token),
                            set()
                        )
                    )

            # Store candidate pairs
            for sid in matched_s1:
                v2_candidates[sid].add(eid)

        processed += len(chunk)

        if processed % 1_000_000 == 0:
            print(
                f"{source_name}: "
                f"{processed:,} rows processed"
            )


scan_for_v2_candidates(TRAIN_S2, "S2")
scan_for_v2_candidates(TRAIN_S3, "S3")


# --------------------------------------------
# Calculate statistics
# --------------------------------------------

total_v2_candidates = sum(
    len(x)
    for x in v2_candidates.values()
)

covered_true_matches_v2 = 0
total_true_matches_v2 = 0
zero_candidate_entities_v2 = 0
missed_entities_v2 = 0

for sid in val_s1_ids:

    true_set = ground_truth_map.get(
        sid,
        set()
    )

    candidate_set = v2_candidates.get(
        sid,
        set()
    )

    total_true_matches_v2 += len(true_set)

    covered_true_matches_v2 += len(
        true_set & candidate_set
    )

    if len(candidate_set) == 0:
        zero_candidate_entities_v2 += 1

    if len(true_set - candidate_set) > 0:
        missed_entities_v2 += 1


v2_recall = (
    covered_true_matches_v2 /
    total_true_matches_v2
    if total_true_matches_v2 > 0
    else 0
)


print("\n================================")
print("V2 BLOCKING RESULTS")
print("================================")

print(
    "Total candidate pairs:",
    f"{total_v2_candidates:,}"
)

print(
    "Total true matches:",
    f"{total_true_matches_v2:,}"
)

print(
    "True matches found:",
    f"{covered_true_matches_v2:,}"
)

print(
    "True matches missed:",
    f"{total_true_matches_v2 - covered_true_matches_v2:,}"
)

print(
    f"\nCandidate Recall: {v2_recall:.6f}"
)

print(
    f"Candidate Recall: {v2_recall * 100:.2f}%"
)

print(
    "Entities with zero candidates:",
    zero_candidate_entities_v2
)

print(
    "Entities with missed true matches:",
    missed_entities_v2
)

S1 exact name keys: 1994
S1 exact address keys: 2000
S1 rare name keys: 702
S1 rare address keys: 1211

Scanning S2 for V2 candidates...
S2: 1,000,000 rows processed
S2: 2,000,000 rows processed
S2: 3,000,000 rows processed
S2: 4,000,000 rows processed
S2: 5,000,000 rows processed

Scanning S3 for V2 candidates...
S3: 1,000,000 rows processed
S3: 2,000,000 rows processed
S3: 3,000,000 rows processed
S3: 4,000,000 rows processed
S3: 5,000,000 rows processed

================================
V2 BLOCKING RESULTS
================================
Total candidate pairs: 167,331
Total true matches: 7,059
True matches found: 4,761
True matches missed: 2,298

Candidate Recall: 0.674458
Candidate Recall: 67.45%
Entities with zero candidates: 136
Entities with missed true matches: 1001

In [ ]:
# ============================================
# STEP 13: Test threshold 500 on V2 misses
# ============================================

v2_missed_pairs = []

for sid in val_s1_ids:

    true_set = ground_truth_map.get(sid, set())

    candidate_set = v2_candidates.get(
        sid,
        set()
    )

    missed = true_set - candidate_set

    for eid in missed:
        v2_missed_pairs.append((sid, eid))


print("V2 missed true pairs:", len(v2_missed_pairs))


# Build lookup for the missed target records
missed_target_lookup = missed_records


recovered_by_500 = 0
recovered_name_500 = 0
recovered_address_500 = 0

still_missed_500 = []

for sid, eid in v2_missed_pairs:

    if eid not in missed_target_lookup:
        continue

    # S1 record
    s1 = s1_lookup[sid]

    # Target S2/S3 record
    target = missed_target_lookup[eid]

    # Normalize
    s1_name = normalize_advanced(
        s1["business_name"]
    )

    target_name = normalize_advanced(
        target["business_name"]
    )

    s1_address = normalize_advanced(
        s1["business_address"]
    )

    target_address = normalize_advanced(
        target["business_address"]
    )

    # Shared name tokens
    name_shared = (
        get_token_set(s1_name)
        &
        get_token_set(target_name)
    )

    # Shared address tokens
    address_shared = (
        get_token_set(s1_address)
        &
        get_token_set(target_address)
    )

    name_hit = any(
        name_token_freq.get(token, 10**9) <= 500
        for token in name_shared
    )

    address_hit = any(
        address_token_freq.get(token, 10**9) <= 500
        for token in address_shared
    )

    if name_hit:
        recovered_name_500 += 1

    if address_hit:
        recovered_address_500 += 1

    if name_hit or address_hit:
        recovered_by_500 += 1
    else:
        still_missed_500.append((sid, eid))


print("\n================================")
print("THRESHOLD 500 RECOVERY")
print("================================")

print(
    "V2 missed pairs:",
    len(v2_missed_pairs)
)

print(
    "Potentially recovered by name:",
    recovered_name_500
)

print(
    "Potentially recovered by address:",
    recovered_address_500
)

print(
    "Potentially recovered by either:",
    recovered_by_500
)

print(
    "Still missed:",
    len(still_missed_500)
)

print(
    "\nPotential recovery:",
    round(
        recovered_by_500 /
        len(v2_missed_pairs) * 100,
        2
    ),
    "%"
)

# Estimated overall recall if all these are recovered
estimated_recall_500 = (
    covered_true_matches_v2 +
    recovered_by_500
) / total_true_matches_v2

print(
    "\nEstimated candidate recall after 500:",
    round(estimated_recall_500 * 100, 2),
    "%"
)

V2 missed true pairs: 2298

================================
THRESHOLD 500 RECOVERY
================================
V2 missed pairs: 2298
Potentially recovered by name: 136
Potentially recovered by address: 280
Potentially recovered by either: 389
Still missed: 1909

Potential recovery: 16.93 %

Estimated candidate recall after 500: 72.96 %

In [ ]:
# ============================================
# STEP 14: Analyze remaining V2 misses
# ============================================

from difflib import SequenceMatcher
import re

def text_similarity(a, b):
    a = normalize_advanced(a)
    b = normalize_advanced(b)

    if not a or not b:
        return 0.0

    return SequenceMatcher(None, a, b).ratio()


def extract_numbers(text):
    if pd.isna(text):
        return set()

    return set(re.findall(r"\d+", str(text)))


diagnostic_rows = []

for sid, eid in v2_missed_pairs:

    if sid not in s1_lookup or eid not in missed_records:
        continue

    s1 = s1_lookup[sid]
    target = missed_records[eid]

    s1_name = normalize_advanced(s1["business_name"])
    target_name = normalize_advanced(target["business_name"])

    s1_address = normalize_advanced(s1["business_address"])
    target_address = normalize_advanced(target["business_address"])

    name_tokens_1 = get_token_set(s1_name)
    name_tokens_2 = get_token_set(target_name)

    addr_tokens_1 = get_token_set(s1_address)
    addr_tokens_2 = get_token_set(target_address)

    shared_name = name_tokens_1 & name_tokens_2
    shared_addr = addr_tokens_1 & addr_tokens_2

    nums_1 = extract_numbers(s1_address)
    nums_2 = extract_numbers(target_address)

    shared_numbers = nums_1 & nums_2

    name_sim = text_similarity(
        s1_name,
        target_name
    )

    address_sim = text_similarity(
        s1_address,
        target_address
    )

    diagnostic_rows.append({

        "source1_entity_id": sid,
        "matched_entity_id": eid,

        "shared_name_tokens": len(shared_name),
        "shared_address_tokens": len(shared_addr),

        "shared_address_numbers": len(shared_numbers),

        "name_similarity": name_sim,
        "address_similarity": address_sim,

        "name_token_any": len(shared_name) >= 1,
        "name_token_2plus": len(shared_name) >= 2,

        "address_token_any": len(shared_addr) >= 1,
        "address_token_2plus": len(shared_addr) >= 2,

        "address_number_shared": len(shared_numbers) >= 1
    })


v2_miss_diagnostic = pd.DataFrame(
    diagnostic_rows
)

print("================================")
print("V2 MISS DIAGNOSTICS")
print("================================")

print(
    "Remaining missed pairs:",
    len(v2_miss_diagnostic)
)

print("\nRecovery signals:")

signals = [
    "name_token_any",
    "name_token_2plus",
    "address_token_any",
    "address_token_2plus",
    "address_number_shared"
]

for signal in signals:

    count = v2_miss_diagnostic[signal].sum()

    print(
        f"{signal:25s}: "
        f"{count:4d} "
        f"({count / len(v2_miss_diagnostic) * 100:.2f}%)"
    )


print("\nSimilarity thresholds:")

for threshold in [0.60, 0.70, 0.75, 0.80, 0.85, 0.90]:

    name_count = (
        v2_miss_diagnostic["name_similarity"]
        >= threshold
    ).sum()

    address_count = (
        v2_miss_diagnostic["address_similarity"]
        >= threshold
    ).sum()

    either_count = (
        (v2_miss_diagnostic["name_similarity"] >= threshold)
        |
        (v2_miss_diagnostic["address_similarity"] >= threshold)
    ).sum()

    print(
        f"{threshold:.2f}  | "
        f"name: {name_count:4d} | "
        f"address: {address_count:4d} | "
        f"either: {either_count:4d}"
    )


print("\nSimilarity statistics:")

print(
    v2_miss_diagnostic[
        ["name_similarity", "address_similarity"]
    ].describe()
)

================================
V2 MISS DIAGNOSTICS
================================
Remaining missed pairs: 2298

Recovery signals:
name_token_any           : 1647 (71.67%)
name_token_2plus         : 1195 (52.00%)
address_token_any        : 2112 (91.91%)
address_token_2plus      : 1750 (76.15%)
address_number_shared    : 1794 (78.07%)

Similarity thresholds:
0.60  | name: 1838 | address: 1601 | either: 2128
0.70  | name: 1609 | address: 1377 | either: 1976
0.75  | name: 1463 | address: 1262 | either: 1872
0.80  | name: 1257 | address: 1066 | either: 1694
0.85  | name:  962 | address:  804 | either: 1411
0.90  | name:  585 | address:  452 | either:  923

Similarity statistics:
       name_similarity  address_similarity
count      2298.000000         2298.000000
mean          0.717432            0.687802
std           0.265467            0.257891
min           0.051282            0.000000
25%           0.655314            0.544452
50%           0.818182            0.779441
75%           0.900000            0.885173
max           0.985915            0.991453

In [ ]:
# ============================================
# STEP 15: Test address-number + token signal
# ============================================

address_combo_results = []

for _, row in v2_miss_diagnostic.iterrows():

    sid = row["source1_entity_id"]
    eid = row["matched_entity_id"]

    s1 = s1_lookup[sid]
    target = missed_records[eid]

    s1_address = normalize_advanced(
        s1["business_address"]
    )

    target_address = normalize_advanced(
        target["business_address"]
    )

    # Address numbers
    nums1 = extract_numbers(s1_address)
    nums2 = extract_numbers(target_address)

    shared_numbers = nums1 & nums2

    # Address tokens
    tokens1 = get_token_set(s1_address)
    tokens2 = get_token_set(target_address)

    shared_tokens = tokens1 & tokens2

    # Rare shared address tokens
    rare_shared_tokens = {
        token
        for token in shared_tokens
        if address_token_freq.get(
            token,
            10**9
        ) <= 250
    }

    address_combo_results.append({

        "number_and_any_token":
            len(shared_numbers) > 0
            and len(shared_tokens) > 0,

        "number_and_rare_token":
            len(shared_numbers) > 0
            and len(rare_shared_tokens) > 0,

        "number_only":
            len(shared_numbers) > 0
    })


combo_df = pd.DataFrame(
    address_combo_results
)

print("================================")
print("ADDRESS COMBINATION ANALYSIS")
print("================================")

for col in combo_df.columns:

    count = combo_df[col].sum()

    print(
        f"{col:25s}: "
        f"{count:4d} / {len(combo_df)} "
        f"({count / len(combo_df) * 100:.2f}%)"
    )

================================
ADDRESS COMBINATION ANALYSIS
================================
number_and_any_token     : 1759 / 2298 (76.54%)
number_and_rare_token    :    0 / 2298 (0.00%)
number_only              : 1794 / 2298 (78.07%)

In [ ]:
from collections import Counter

def extract_numbers(text):
    if not text:
        return set()
    return set(re.findall(r'\b\d+\b', str(text)))

number_freq = Counter()

for path in [TRAIN_S2, TRAIN_S3]:
    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_address"],
        chunksize=200000
    ):
        for addr in chunk["business_address"].dropna():
            nums = extract_numbers(normalize_advanced(addr))
            number_freq.update(nums)

print("Unique address numbers:", len(number_freq))

print("\nMost common address numbers:")
for num, count in number_freq.most_common(30):
    print(num, count)

Unique address numbers: 89589

Most common address numbers:
1 591200
2 466756
3 247820
4 199464
5 176835
6 161318
8 148832
7 141937
9 123931
10 114227
11 105442
12 100521
14 85540
15 80655
13 79095
16 75252
24 71723
17 67876
18 65396
19 62224
20 61951
22 59160
21 57764
23 55081
25 51021
30 44066
26 44045
27 43789
28 43174
31 41113

In [ ]:
thresholds = [10, 25, 50, 100, 250, 500, 1000]

print("================================")
print("ADDRESS NUMBER FREQUENCY ANALYSIS")
print("================================")

for threshold in thresholds:
    recovered = 0

    for _, row in v2_miss_diagnostic.iterrows():
        sid = row["source1_entity_id"]
        eid = row["matched_entity_id"]

        s1 = s1_lookup[sid]
        target = missed_records[eid]

        nums1 = extract_numbers(
            normalize_advanced(s1["business_address"])
        )
        nums2 = extract_numbers(
            normalize_advanced(target["business_address"])
        )

        shared = nums1 & nums2

        if any(number_freq.get(n, 10**9) <= threshold for n in shared):
            recovered += 1

    print(
        f"threshold <= {threshold:4d}: "
        f"{recovered:4d} / 2298 "
        f"({recovered / 2298 * 100:.2f}%)"
    )

================================
ADDRESS NUMBER FREQUENCY ANALYSIS
================================
threshold <=   10:   25 / 2298 (1.09%)
threshold <=   25:   41 / 2298 (1.78%)
threshold <=   50:   68 / 2298 (2.96%)
threshold <=  100:  105 / 2298 (4.57%)
threshold <=  250:  215 / 2298 (9.36%)
threshold <=  500:  341 / 2298 (14.84%)
threshold <= 1000:  469 / 2298 (20.41%)

In [ ]:
combo_results = []

for _, row in v2_miss_diagnostic.iterrows():

    sid = row["source1_entity_id"]
    eid = row["matched_entity_id"]

    s1 = s1_lookup[sid]
    target = missed_records[eid]

    name1 = normalize_advanced(s1["business_name"])
    name2 = normalize_advanced(target["business_name"])

    addr1 = normalize_advanced(s1["business_address"])
    addr2 = normalize_advanced(target["business_address"])

    name_tokens1 = get_token_set(name1)
    name_tokens2 = get_token_set(name2)

    addr_tokens1 = get_token_set(addr1)
    addr_tokens2 = get_token_set(addr2)

    shared_name = name_tokens1 & name_tokens2
    shared_addr = addr_tokens1 & addr_tokens2

    nums1 = extract_numbers(addr1)
    nums2 = extract_numbers(addr2)

    shared_nums = nums1 & nums2

    combo_results.append({
        "name_2plus":
            len(shared_name) >= 2,

        "address_2plus":
            len(shared_addr) >= 2,

        "name_and_address":
            len(shared_name) >= 1 and len(shared_addr) >= 1,

        "number_and_name":
            len(shared_nums) >= 1 and len(shared_name) >= 1,

        "number_and_address":
            len(shared_nums) >= 1 and len(shared_addr) >= 1,

        "number_name_address":
            len(shared_nums) >= 1
            and len(shared_name) >= 1
            and len(shared_addr) >= 1
    })

combo_df = pd.DataFrame(combo_results)

print("================================")
print("COMBINED BLOCKING SIGNAL ANALYSIS")
print("================================")

for col in combo_df.columns:
    count = combo_df[col].sum()

    print(
        f"{col:25s}: "
        f"{count:4d} / {len(combo_df)} "
        f"({count / len(combo_df) * 100:.2f}%)"
    )

================================
COMBINED BLOCKING SIGNAL ANALYSIS
================================
name_2plus               : 1195 / 2298 (52.00%)
address_2plus            : 1750 / 2298 (76.15%)
name_and_address         : 1477 / 2298 (64.27%)
number_and_name          : 1181 / 2298 (51.39%)
number_and_address       : 1664 / 2298 (72.41%)
number_name_address      : 1160 / 2298 (50.48%)

In [ ]:
print("================================")
print("2+ ADDRESS TOKEN + RARITY ANALYSIS")
print("================================")

thresholds = [250, 500, 1000, 2500, 5000, 10000]

for threshold in thresholds:

    recovered = 0

    for _, row in v2_miss_diagnostic.iterrows():

        sid = row["source1_entity_id"]
        eid = row["matched_entity_id"]

        s1 = s1_lookup[sid]
        target = missed_records[eid]

        addr1 = normalize_advanced(s1["business_address"])
        addr2 = normalize_advanced(target["business_address"])

        tokens1 = get_token_set(addr1)
        tokens2 = get_token_set(addr2)

        shared = tokens1 & tokens2

        if len(shared) >= 2:

            rare_shared = {
                token for token in shared
                if address_token_freq.get(token, 10**9) <= threshold
            }

            if len(rare_shared) >= 1:
                recovered += 1

    print(
        f"threshold <= {threshold:5d}: "
        f"{recovered:4d} / 2298 "
        f"({recovered / 2298 * 100:.2f}%)"
    )

================================
2+ ADDRESS TOKEN + RARITY ANALYSIS
================================
threshold <=   250:    0 / 2298 (0.00%)
threshold <=   500:  252 / 2298 (10.97%)
threshold <=  1000:  557 / 2298 (24.24%)
threshold <=  2500: 1020 / 2298 (44.39%)
threshold <=  5000: 1250 / 2298 (54.40%)
threshold <= 10000: 1444 / 2298 (62.84%)

In [ ]:
import os

for path in [
    "/content/amazon_ml_challenge",
    "/content/amazon_ml_challenge/student_resource",
    "/content/amazon_ml_challenge/dataset",
]:
    print("\n", path)
    if os.path.exists(path):
        print(os.listdir(path)[:20])
    else:
        print("NOT FOUND")

 /content/amazon_ml_challenge
NOT FOUND

 /content/amazon_ml_challenge/student_resource
NOT FOUND

 /content/amazon_ml_challenge/dataset
NOT FOUND

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

zip_path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/data/6ab10eb3b23ba_student_resource.zip"

print("ZIP exists:", os.path.exists(zip_path))
print("Size GB:", round(os.path.getsize(zip_path) / (1024**3), 2) if os.path.exists(zip_path) else "N/A")

ZIP exists: True
Size GB: 1.02

In [ ]:
import zipfile
import os

extract_path = "/content/amazon_ml_challenge"

print("Extracting...")

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_path)

print("Extraction complete.")

Extracting...
Extraction complete.

In [ ]:
import os

for root, dirs, files in os.walk("/content/amazon_ml_challenge"):
    level = root.replace("/content/amazon_ml_challenge", "").count(os.sep)
    if level <= 3:
        print(root)

/content/amazon_ml_challenge
/content/amazon_ml_challenge/__MACOSX
/content/amazon_ml_challenge/__MACOSX/student_resource
/content/amazon_ml_challenge/__MACOSX/student_resource/dataset
/content/amazon_ml_challenge/__MACOSX/student_resource/utils
/content/amazon_ml_challenge/student_resource
/content/amazon_ml_challenge/student_resource/dataset
/content/amazon_ml_challenge/student_resource/dataset/test
/content/amazon_ml_challenge/student_resource/dataset/train
/content/amazon_ml_challenge/student_resource/utils

In [ ]:
BASE = "/content/amazon_ml_challenge/student_resource"

TEST_S1 = f"{BASE}/dataset/test/test_source1.tsv"
TEST_S2 = f"{BASE}/dataset/test/test_source2.tsv"
TEST_S3 = f"{BASE}/dataset/test/test_source3.tsv"
OUT = f"{BASE}/output"

import os

print(os.path.exists(TEST_S1))
print(os.path.exists(TEST_S2))
print(os.path.exists(TEST_S3))

True
True
True

In [ ]:
import pandas as pd
import re
import unicodedata
from collections import defaultdict

def norm(x):
    if pd.isna(x):
        return ""
    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)
    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

# -----------------------------
# Build Source 1 indexes
# -----------------------------

print("Loading Source 1...")

s1 = pd.read_csv(
    TEST_S1,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
)

print("Source 1 rows:", len(s1))

address_map = defaultdict(list)
name_map = defaultdict(list)

for row in s1.itertuples(index=False):

    sid = row.entity_id
    country = norm(row.country)

    name = norm(row.business_name)
    address = norm(row.business_address)

    if address:
        address_map[(country, address)].append(sid)

    if name:
        name_map[(country, name)].append(sid)

# Only unique name keys
unique_name_map = {
    key: ids[0]
    for key, ids in name_map.items()
    if len(ids) == 1
}

print("Address keys:", len(address_map))
print("Unique name keys:", len(unique_name_map))

# -----------------------------
# Generate matches
# -----------------------------

matches = defaultdict(list)

def process_source(path, source_name):

    print(f"\nProcessing {source_name}...")

    total = 0
    address_count = 0
    name_count = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            total += 1

            eid = row.entity_id
            country = norm(row.country)

            name = norm(row.business_name)
            address = norm(row.business_address)

            found = set()

            # Exact address + country
            if address:
                ids = address_map.get(
                    (country, address),
                    []
                )

                if ids:
                    found.update(ids)
                    address_count += len(ids)

            # Unique exact name + country
            if not found and name:
                sid = unique_name_map.get(
                    (country, name)
                )

                if sid is not None:
                    found.add(sid)
                    name_count += 1

            for sid in found:
                matches[sid].append(eid)

        print(
            f"{source_name}: processed {total:,} | "
            f"S1 matched: {len(matches):,}"
        )

    print(
        f"{source_name} COMPLETE | "
        f"address matches: {address_count:,} | "
        f"name matches: {name_count:,}"
    )


process_source(TEST_S2, "Source 2")
process_source(TEST_S3, "Source 3")

# Remove duplicates
for sid in matches:
    matches[sid] = sorted(set(matches[sid]))

print("\n================================")
print("SUBMISSION #2 CANDIDATES")
print("================================")
print("S1 entities:", len(s1))
print("S1 with matches:", len(matches))
print("S1 without matches:", len(s1) - len(matches))

Loading Source 1...
Source 1 rows: 1732544
Address keys: 1673951
Unique name keys: 1096537

Processing Source 2...
Source 2: processed 200,000 | S1 matched: 34,069
Source 2: processed 400,000 | S1 matched: 66,656
Source 2: processed 600,000 | S1 matched: 98,238
Source 2: processed 800,000 | S1 matched: 128,817
Source 2: processed 1,000,000 | S1 matched: 157,815
Source 2: processed 1,200,000 | S1 matched: 186,315
Source 2: processed 1,400,000 | S1 matched: 213,959
Source 2: processed 1,600,000 | S1 matched: 240,417
Source 2: processed 1,800,000 | S1 matched: 266,378
Source 2: processed 2,000,000 | S1 matched: 291,457
Source 2: processed 2,200,000 | S1 matched: 315,982
Source 2: processed 2,400,000 | S1 matched: 339,894
Source 2: processed 2,600,000 | S1 matched: 363,261
Source 2: processed 2,800,000 | S1 matched: 385,672
Source 2: processed 3,000,000 | S1 matched: 407,579
Source 2: processed 3,200,000 | S1 matched: 428,950
Source 2: processed 3,400,000 | S1 matched: 449,780
Source 2: processed 3,600,000 | S1 matched: 469,928
Source 2: processed 3,800,000 | S1 matched: 489,886
Source 2: processed 4,000,000 | S1 matched: 509,183
Source 2: processed 4,200,000 | S1 matched: 527,756
Source 2: processed 4,400,000 | S1 matched: 546,038
Source 2: processed 4,600,000 | S1 matched: 563,726
Source 2: processed 4,800,000 | S1 matched: 580,997
Source 2: processed 4,887,273 | S1 matched: 588,555
Source 2 COMPLETE | address matches: 416,074 | name matches: 435,728

Processing Source 3...
Source 3: processed 200,000 | S1 matched: 603,101
Source 3: processed 400,000 | S1 matched: 617,421
Source 3: processed 600,000 | S1 matched: 631,491
Source 3: processed 800,000 | S1 matched: 645,222
Source 3: processed 1,000,000 | S1 matched: 658,555
Source 3: processed 1,200,000 | S1 matched: 671,624
Source 3: processed 1,400,000 | S1 matched: 684,462
Source 3: processed 1,600,000 | S1 matched: 697,052
Source 3: processed 1,800,000 | S1 matched: 709,087
Source 3: processed 2,000,000 | S1 matched: 721,134
Source 3: processed 2,200,000 | S1 matched: 733,056
Source 3: processed 2,400,000 | S1 matched: 744,677
Source 3: processed 2,600,000 | S1 matched: 756,167
Source 3: processed 2,800,000 | S1 matched: 767,271
Source 3: processed 3,000,000 | S1 matched: 778,389
Source 3: processed 3,200,000 | S1 matched: 789,068
Source 3: processed 3,400,000 | S1 matched: 799,462
Source 3: processed 3,600,000 | S1 matched: 809,878
Source 3: processed 3,800,000 | S1 matched: 819,879
Source 3: processed 4,000,000 | S1 matched: 829,855
Source 3: processed 4,200,000 | S1 matched: 839,610
Source 3: processed 4,400,000 | S1 matched: 849,081
Source 3: processed 4,600,000 | S1 matched: 858,469
Source 3: processed 4,800,000 | S1 matched: 867,938
Source 3: processed 5,000,000 | S1 matched: 877,035
Source 3: processed 5,082,316 | S1 matched: 880,691
Source 3 COMPLETE | address matches: 239,420 | name matches: 509,537

================================
SUBMISSION #2 CANDIDATES
================================
S1 entities: 1732544
S1 with matches: 880691
S1 without matches: 851853

In [ ]:
import os

os.makedirs(OUT, exist_ok=True)

print("Output folder ready:", OUT)

Output folder ready: /content/amazon_ml_challenge/student_resource/output

In [ ]:
result = pd.DataFrame({
    "source1_entity_id": s1["entity_id"],
    "matched_entity_ids": [
        ",".join(matches.get(sid, []))
        for sid in s1["entity_id"]
    ]
})

candidate = pd.DataFrame({
    "source1_entity_id": s1["entity_id"],
    "candidate_entity_ids": [
        ",".join(matches.get(sid, []))
        for sid in s1["entity_id"]
    ]
})

matching_path = f"{OUT}/matching_results_v2.tsv"
candidate_path = f"{OUT}/candidate_pairs_v2.tsv"

result.to_csv(matching_path, sep="\t", index=False)
candidate.to_csv(candidate_path, sep="\t", index=False)

print("================================")
print("FILES CREATED")
print("================================")
print("Matching:", matching_path)
print("Candidate:", candidate_path)
print("Rows:", len(result))
print("Non-empty:", (result["matched_entity_ids"] != "").sum())
print("Empty:", (result["matched_entity_ids"] == "").sum())
print(
    "Total matched links:",
    sum(len(x.split(",")) for x in result["matched_entity_ids"] if x)
)

================================
FILES CREATED
================================
Matching: /content/amazon_ml_challenge/student_resource/output/matching_results_v2.tsv
Candidate: /content/amazon_ml_challenge/student_resource/output/candidate_pairs_v2.tsv
Rows: 1732544
Non-empty: 880691
Empty: 851853
Total matched links: 1600759

In [ ]:
!python3 /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
  --matching /content/amazon_ml_challenge/student_resource/output/matching_results_v2.tsv \
  --candidate /content/amazon_ml_challenge/student_resource/output/candidate_pairs_v2.tsv \
  --test-dir /content/amazon_ml_challenge/student_resource/dataset/test

ML Challenge 2026 — submission validator
  test dir: /content/amazon_ml_challenge/student_resource/dataset/test
  required S1 entities: 1732544
  matching_results_v2.tsv: 1732544 rows (851853 empty, 880691 non-empty).
  candidate_pairs_v2.tsv: 1732544 rows (851853 empty, 880691 non-empty).

WARNING: ID-existence check is OFF (the default) — not checking that matched/candidate IDs exist in the test set. Every other rule is still checked. Re-run with --check-ids to enable it (needs test_source2/3.tsv; uses more memory). A nonexistent ID only lowers your score, never rejects your submission.
PASS — no blocking issues found. Safe to submit.

In [ ]:
import shutil

shutil.copy(
    "/content/amazon_ml_challenge/student_resource/output/matching_results_v2.tsv",
    "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv"
)

print("Ready:")
print("/content/amazon_ml_challenge/student_resource/output/matching_results.tsv")

Ready:
/content/amazon_ml_challenge/student_resource/output/matching_results.tsv

In [ ]:
# Analyze duplicate exact-name keys in Source 1

duplicate_name_keys = {
    key: ids
    for key, ids in name_map.items()
    if len(ids) > 1
}

print("Duplicate name keys:", len(duplicate_name_keys))

# Distribution
sizes = [len(v) for v in duplicate_name_keys.values()]

import numpy as np

print("Median duplicate size:", np.median(sizes))
print("Max duplicate size:", max(sizes))

for limit in [2, 3, 5, 10]:
    print(
        f"Keys with <= {limit} S1 entities:",
        sum(x <= limit for x in sizes)
    )

Duplicate name keys: 132087
Median duplicate size: 2.0
Max duplicate size: 205
Keys with <= 2 S1 entities: 73282
Keys with <= 3 S1 entities: 94834
Keys with <= 5 S1 entities: 110422
Keys with <= 10 S1 entities: 121995

In [ ]:
# ============================================
# SUBMISSION #3
# Add exact-name matches where S1 has <= 2
# entities with that same country + name
# ============================================

matches_v3 = defaultdict(list)

# Start with Submission #2 matches
for sid, ids in matches.items():
    matches_v3[sid] = list(ids)

# Name keys with exactly 2 S1 entities
name2_map = {
    key: ids
    for key, ids in name_map.items()
    if len(ids) == 2
}

print("Name keys with exactly 2 S1 entities:", len(name2_map))

def process_duplicate_names(path, source_name):

    print(f"\nProcessing {source_name}...")

    total = 0
    added_links = 0
    matched_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            total += 1

            country = norm(row.country)
            name = norm(row.business_name)

            if not name:
                continue

            ids = name2_map.get((country, name))

            if ids:
                matched_rows += 1

                for sid in ids:
                    if row.entity_id not in matches_v3[sid]:
                        matches_v3[sid].append(row.entity_id)
                        added_links += 1

        print(
            f"{source_name}: processed {total:,} | "
            f"new links: {added_links:,}"
        )

    print(
        f"{source_name} COMPLETE | "
        f"new links: {added_links:,}"
    )


process_duplicate_names(TEST_S2, "Source 2")
process_duplicate_names(TEST_S3, "Source 3")

# Remove duplicates and sort
for sid in matches_v3:
    matches_v3[sid] = sorted(set(matches_v3[sid]))

print("\n================================")
print("SUBMISSION #3 SUMMARY")
print("================================")

print("S1 entities:", len(s1))
print("S1 with matches:", len(matches_v3))
print("S1 without matches:", len(s1) - len(matches_v3))

total_links = sum(len(x) for x in matches_v3.values())

print("Total matched links:", total_links)

Name keys with exactly 2 S1 entities: 73282

Processing Source 2...
Source 2: processed 200,000 | new links: 6,234
Source 2: processed 400,000 | new links: 12,665
Source 2: processed 600,000 | new links: 19,164
Source 2: processed 800,000 | new links: 25,516
Source 2: processed 1,000,000 | new links: 31,877
Source 2: processed 1,200,000 | new links: 38,290
Source 2: processed 1,400,000 | new links: 44,827
Source 2: processed 1,600,000 | new links: 51,109
Source 2: processed 1,800,000 | new links: 57,491
Source 2: processed 2,000,000 | new links: 63,863
Source 2: processed 2,200,000 | new links: 70,210
Source 2: processed 2,400,000 | new links: 76,503
Source 2: processed 2,600,000 | new links: 82,771
Source 2: processed 2,800,000 | new links: 89,048
Source 2: processed 3,000,000 | new links: 95,238
Source 2: processed 3,200,000 | new links: 101,558
Source 2: processed 3,400,000 | new links: 107,892
Source 2: processed 3,600,000 | new links: 114,226
Source 2: processed 3,800,000 | new links: 120,567
Source 2: processed 4,000,000 | new links: 126,946
Source 2: processed 4,200,000 | new links: 133,147
Source 2: processed 4,400,000 | new links: 139,552
Source 2: processed 4,600,000 | new links: 145,813
Source 2: processed 4,800,000 | new links: 152,300
Source 2: processed 4,887,273 | new links: 155,170
Source 2 COMPLETE | new links: 155,170

Processing Source 3...
Source 3: processed 200,000 | new links: 6,733
Source 3: processed 400,000 | new links: 13,599
Source 3: processed 600,000 | new links: 20,473
Source 3: processed 800,000 | new links: 27,230
Source 3: processed 1,000,000 | new links: 34,090
Source 3: processed 1,200,000 | new links: 40,716
Source 3: processed 1,400,000 | new links: 47,446
Source 3: processed 1,600,000 | new links: 54,213
Source 3: processed 1,800,000 | new links: 60,955
Source 3: processed 2,000,000 | new links: 67,712
Source 3: processed 2,200,000 | new links: 74,545
Source 3: processed 2,400,000 | new links: 81,204
Source 3: processed 2,600,000 | new links: 87,763
Source 3: processed 2,800,000 | new links: 94,454
Source 3: processed 3,000,000 | new links: 101,427
Source 3: processed 3,200,000 | new links: 108,420
Source 3: processed 3,400,000 | new links: 115,219
Source 3: processed 3,600,000 | new links: 121,725
Source 3: processed 3,800,000 | new links: 128,524
Source 3: processed 4,000,000 | new links: 135,275
Source 3: processed 4,200,000 | new links: 142,106
Source 3: processed 4,400,000 | new links: 148,691
Source 3: processed 4,600,000 | new links: 155,480
Source 3: processed 4,800,000 | new links: 162,237
Source 3: processed 5,000,000 | new links: 169,071
Source 3: processed 5,082,316 | new links: 171,875
Source 3 COMPLETE | new links: 171,875

================================
SUBMISSION #3 SUMMARY
================================
S1 entities: 1732544
S1 with matches: 972630
S1 without matches: 759914
Total matched links: 1927804

In [ ]:
# STEP 18B-0
# Safe diagnostic: does not scan the large datasets.

required = [
    "s1_lookup",
    "missed_records",
    "v2_miss_diagnostic",
    "address_token_freq",
    "s1_val",
]

print("Checking validation objects...\n")

for name in required:
    exists = name in globals()
    print(f"{name:22s} -> {exists}")

if "v2_miss_diagnostic" in globals():
    print("\nv2_miss_diagnostic shape:", v2_miss_diagnostic.shape)

if "s1_val" in globals():
    print("s1_val shape:", s1_val.shape)

print("\nNo large dataset scan was performed.")

Checking validation objects...

s1_lookup              -> False
missed_records         -> False
v2_miss_diagnostic     -> False
address_token_freq     -> False
s1_val                 -> False

No large dataset scan was performed.

In [ ]:
# ============================================
# STEP 18B-1
# Rebuild validation foundation
# ============================================

import pandas as pd
import numpy as np
import re
import unicodedata
from collections import defaultdict, Counter

BASE = "/content/amazon_ml_challenge/student_resource"

TRAIN_S1 = f"{BASE}/dataset/train/train_source1.tsv"
TRAIN_S2 = f"{BASE}/dataset/train/train_source2.tsv"
TRAIN_S3 = f"{BASE}/dataset/train/train_source3.tsv"
GROUND_TRUTH = f"{BASE}/dataset/train/train_ground_truth.tsv"

# --------------------------------------------
# Normalization
# --------------------------------------------

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def normalize_country(x):
    return normalize_advanced(x)


def get_token_set(text):
    if not text:
        return set()
    return set(str(text).split())


def extract_numbers(text):
    if not text:
        return set()
    return set(re.findall(r"\b\d+\b", str(text)))


# --------------------------------------------
# Load first 10,000 training Source 1
# --------------------------------------------

print("Loading first 10,000 Source 1 rows...")

train_s1_10k = pd.read_csv(
    TRAIN_S1,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    nrows=10000
)

print("Source 1:", train_s1_10k.shape)

# --------------------------------------------
# Proper entity-level split
# Same split used in our earlier validation
# --------------------------------------------

s1_train = train_s1_10k.iloc[:8000].copy()
s1_val = train_s1_10k.iloc[8000:].copy()

print("Training S1 entities:", len(s1_train))
print("Validation S1 entities:", len(s1_val))

# --------------------------------------------
# Load ground truth for these 10,000 S1
# --------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GROUND_TRUTH,
    sep="\t"
)

gt_10k = gt[
    gt["source1_entity_id"].isin(
        set(train_s1_10k["entity_id"])
    )
].copy()

print("Ground-truth rows:", len(gt_10k))

# --------------------------------------------
# Create lookups
# --------------------------------------------

s1_lookup = (
    train_s1_10k
    .set_index("entity_id")
    .to_dict("index")
)

# Ground truth lookup
gt_lookup = dict(
    zip(
        gt_10k["source1_entity_id"],
        gt_10k["matched_entity_ids"]
    )
)

# Normalize ground-truth values to sets
def parse_match_ids(x):
    if pd.isna(x):
        return set()

    x = str(x).strip()

    if not x:
        return set()

    return {
        item.strip()
        for item in x.split(",")
        if item.strip()
    }


gt_lookup = {
    sid: parse_match_ids(value)
    for sid, value in gt_lookup.items()
}

print("\nGround-truth validation entities:", len(gt_lookup))

# --------------------------------------------
# Validation S1 IDs
# --------------------------------------------

val_ids = set(s1_val["entity_id"])

print("Validation S1 IDs:", len(val_ids))

# --------------------------------------------
# Basic verification
# --------------------------------------------

assert len(train_s1_10k) == 10000
assert len(s1_train) == 8000
assert len(s1_val) == 2000

print("\n================================")
print("FOUNDATION READY")
print("================================")
print("10k S1 loaded        :", len(train_s1_10k))
print("Train entities       :", len(s1_train))
print("Validation entities  :", len(s1_val))
print("Ground truth rows    :", len(gt_10k))
print("Validation IDs       :", len(val_ids))

Loading first 10,000 Source 1 rows...
Source 1: (10000, 4)
Training S1 entities: 8000
Validation S1 entities: 2000

Loading ground truth...
Ground-truth rows: 10000

Ground-truth validation entities: 10000
Validation S1 IDs: 2000

================================
FOUNDATION READY
================================
10k S1 loaded        : 10000
Train entities       : 8000
Validation entities  : 2000
Ground truth rows    : 10000
Validation IDs       : 2000

In [ ]:
# ============================================
# STEP 18B-2
# Rebuild V2 candidate maps
# ============================================

# Maps from validation S1
name_map_val = defaultdict(list)
address_map_val = defaultdict(list)

for row in s1_val.itertuples(index=False):

    sid = row.entity_id
    country = normalize_country(row.country)

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    if name:
        name_map_val[(country, name)].append(sid)

    if address:
        address_map_val[(country, address)].append(sid)

# Build rare-token indexes from FULL Source 2 + Source 3.
# We need token frequencies first.

print("Building full training token frequencies...")

name_token_freq = Counter()
address_token_freq = Counter()

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_name", "business_address"],
        chunksize=200000
    ):

        for name in chunk["business_name"].dropna():
            tokens = get_token_set(
                normalize_advanced(name)
            )
            name_token_freq.update(tokens)

        for address in chunk["business_address"].dropna():
            tokens = get_token_set(
                normalize_advanced(address)
            )
            address_token_freq.update(tokens)

        rows += len(chunk)

        if rows % 1000000 == 0:
            print(f"  processed {rows:,}")

print("\n================================")
print("TOKEN FREQUENCIES READY")
print("================================")
print("Name tokens:", len(name_token_freq))
print("Address tokens:", len(address_token_freq))

print("\nMost common address tokens:")
for token, count in address_token_freq.most_common(20):
    print(f"{token:20s} {count:,}")

# --------------------------------------------
# Build rare-token maps
# Same V2 cutoff: <=250
# --------------------------------------------

RARE_LIMIT = 250

rare_name_map = defaultdict(list)
rare_address_map = defaultdict(list)

print("\nBuilding rare-token indexes...")

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"Indexing {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = normalize_country(row.country)

            name_tokens = get_token_set(
                normalize_advanced(row.business_name)
            )

            address_tokens = get_token_set(
                normalize_advanced(row.business_address)
            )

            for token in name_tokens:
                if name_token_freq.get(token, 10**9) <= RARE_LIMIT:
                    rare_name_map[
                        (country, token)
                    ].append(eid)

            for token in address_tokens:
                if address_token_freq.get(token, 10**9) <= RARE_LIMIT:
                    rare_address_map[
                        (country, token)
                    ].append(eid)

        rows += len(chunk)

        if rows % 1000000 == 0:
            print(f"  indexed {rows:,}")

print("\n================================")
print("V2 BLOCKING INDEXES READY")
print("================================")
print("Rare name keys:", len(rare_name_map))
print("Rare address keys:", len(rare_address_map))

Building full training token frequencies...

Scanning Source 2...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

Scanning Source 3...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

================================
TOKEN FREQUENCIES READY
================================
Name tokens: 1455872
Address tokens: 732777

Most common address tokens:
rd                   1,991,344
no                   1,828,214
st                   1,363,137
dr                   1,023,178
ave                  855,833
new                  677,271
city                 650,528
floor                597,386
1                    591,200
nagar                554,836
a                    536,082
delhi                535,364
c                    514,397
ln                   483,740
2                    466,756
north                399,797
b                    393,905
west                 392,422
h                    370,275
mumbai               360,516

Building rare-token indexes...
Indexing Source 2...
  indexed 1,000,000
  indexed 2,000,000
  indexed 3,000,000
  indexed 4,000,000
  indexed 5,000,000
Indexing Source 3...
  indexed 1,000,000
  indexed 2,000,000
  indexed 3,000,000
  indexed 4,000,000
  indexed 5,000,000

================================
V2 BLOCKING INDEXES READY
================================
Rare name keys: 1507899
Rare address keys: 747004

In [ ]:
# ============================================
# STEP 18B-3
# Rebuild V2 candidate pairs
# ============================================

candidate_pairs_v2 = []

def scan_candidates(path, source_name):

    print(f"\nScanning {source_name}...")

    rows = 0
    added = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = normalize_country(row.country)

            name = normalize_advanced(row.business_name)
            address = normalize_advanced(row.business_address)

            found_s1 = set()

            # -----------------------------
            # V2 BLOCK 1: exact name
            # -----------------------------
            if name:
                found_s1.update(
                    name_map_val.get(
                        (country, name),
                        []
                    )
                )

            # -----------------------------
            # V2 BLOCK 2: exact address
            # -----------------------------
            if address:
                found_s1.update(
                    address_map_val.get(
                        (country, address),
                        []
                    )
                )

            # -----------------------------
            # V2 BLOCK 3: rare name token
            # -----------------------------
            name_tokens = get_token_set(name)

            for token in name_tokens:

                if name_token_freq.get(
                    token, 10**9
                ) <= RARE_LIMIT:

                    found_s1.update(
                        rare_name_map.get(
                            (country, token),
                            []
                        )
                    )

            # -----------------------------
            # V2 BLOCK 4: rare address token
            # -----------------------------
            address_tokens = get_token_set(address)

            for token in address_tokens:

                if address_token_freq.get(
                    token, 10**9
                ) <= RARE_LIMIT:

                    found_s1.update(
                        rare_address_map.get(
                            (country, token),
                            []
                        )
                    )

            # Store only actual candidate pairs
            for sid in found_s1:
                candidate_pairs_v2.append(
                    (sid, eid)
                )

            added += len(found_s1)
            rows += 1

        print(
            f"{source_name}: "
            f"{rows:,} rows | "
            f"{added:,} candidate links"
        )

    print(
        f"{source_name} COMPLETE | "
        f"candidate links: {added:,}"
    )


scan_candidates(TRAIN_S2, "Source 2")
scan_candidates(TRAIN_S3, "Source 3")

# --------------------------------------------
# Convert to DataFrame and deduplicate
# --------------------------------------------

v2_candidates = pd.DataFrame(
    candidate_pairs_v2,
    columns=[
        "source1_entity_id",
        "matched_entity_id"
    ]
).drop_duplicates()

print("\n================================")
print("V2 CANDIDATE SET")
print("================================")
print("Candidate pairs:", len(v2_candidates))
print(
    "S1 entities with candidates:",
    v2_candidates["source1_entity_id"].nunique()
)

# --------------------------------------------
# Calculate candidate recall
# --------------------------------------------

candidate_lookup = defaultdict(set)

for row in v2_candidates.itertuples(index=False):
    candidate_lookup[
        row.source1_entity_id
    ].add(row.matched_entity_id)

total_true = 0
found_true = 0
missed_true = 0
zero_candidate_entities = 0

for sid in val_ids:

    true_ids = gt_lookup.get(sid, set())

    candidates = candidate_lookup.get(
        sid,
        set()
    )

    if len(candidates) == 0:
        zero_candidate_entities += 1

    total_true += len(true_ids)

    found = true_ids & candidates

    found_true += len(found)
    missed_true += len(true_ids - candidates)

print("\n================================")
print("V2 RECALL VERIFICATION")
print("================================")
print("Validation S1 entities:", len(val_ids))
print("Total true matches:", total_true)
print("True matches found:", found_true)
print("True matches missed:", missed_true)

print(
    "Candidate recall:",
    f"{found_true / total_true * 100:.2f}%"
)

print(
    "Zero-candidate S1 entities:",
    zero_candidate_entities
)

Scanning Source 2...
Source 2: 200,000 rows | 18,592,158 candidate links
Source 2: 400,000 rows | 37,168,379 candidate links
Source 2: 600,000 rows | 55,786,707 candidate links
Source 2: 800,000 rows | 74,379,471 candidate links
Source 2: 1,000,000 rows | 93,024,193 candidate links

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# ============================================
# RAM-SAFE VALIDATION SETUP
# ============================================

from google.colab import drive
drive.mount("/content/drive")

import pandas as pd
import numpy as np
import re
import unicodedata
from collections import defaultdict, Counter

BASE = "/content/amazon_ml_challenge/student_resource"

TRAIN_S1 = f"{BASE}/dataset/train/train_source1.tsv"
TRAIN_S2 = f"{BASE}/dataset/train/train_source2.tsv"
TRAIN_S3 = f"{BASE}/dataset/train/train_source3.tsv"
GROUND_TRUTH = f"{BASE}/dataset/train/train_ground_truth.tsv"

# --------------------------------------------
# Normalization
# --------------------------------------------

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def normalize_country(text):
    return normalize_advanced(text)


def get_token_set(text):
    if not text:
        return set()
    return set(str(text).split())


def extract_numbers(text):
    if not text:
        return set()
    return set(re.findall(r"\b\d+\b", str(text)))


# --------------------------------------------
# Load only 10,000 Source-1 rows
# --------------------------------------------

print("Loading 10,000 Source-1 rows...")

s1_10k = pd.read_csv(
    TRAIN_S1,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    nrows=10000
)

# Exact same entity-level split
s1_train = s1_10k.iloc[:8000].copy()
s1_val = s1_10k.iloc[8000:].copy()

val_ids = set(s1_val["entity_id"])

# --------------------------------------------
# Ground truth
# --------------------------------------------

print("Loading ground truth...")

gt = pd.read_csv(
    GROUND_TRUTH,
    sep="\t",
    usecols=[
        "source1_entity_id",
        "matched_entity_ids"
    ]
)

gt = gt[
    gt["source1_entity_id"].isin(
        set(s1_10k["entity_id"])
    )
].copy()


def parse_match_ids(value):
    if pd.isna(value):
        return set()

    value = str(value).strip()

    if not value:
        return set()

    return {
        x.strip()
        for x in value.split(",")
        if x.strip()
    }


gt_lookup = {
    row.source1_entity_id:
        parse_match_ids(row.matched_entity_ids)
    for row in gt.itertuples(index=False)
}

# --------------------------------------------
# Tiny S1 validation indexes
# --------------------------------------------

s1_val_name_map = defaultdict(list)
s1_val_address_map = defaultdict(list)

for row in s1_val.itertuples(index=False):

    sid = row.entity_id
    country = normalize_country(row.country)

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    if name:
        s1_val_name_map[
            (country, name)
        ].append(sid)

    if address:
        s1_val_address_map[
            (country, address)
        ].append(sid)

print("\n================================")
print("RAM-SAFE SETUP COMPLETE")
print("================================")
print("S1 total loaded       :", len(s1_10k))
print("S1 validation         :", len(s1_val))
print("Ground truth rows     :", len(gt))
print("Validation IDs        :", len(val_ids))
print("Name keys             :", len(s1_val_name_map))
print("Address keys          :", len(s1_val_address_map))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Loading 10,000 Source-1 rows...
Loading ground truth...

================================
RAM-SAFE SETUP COMPLETE
================================
S1 total loaded       : 10000
S1 validation         : 2000
Ground truth rows     : 10000
Validation IDs        : 2000
Name keys             : 1994
Address keys          : 2000

In [ ]:
# ============================================
# STEP 2 — RAM-SAFE TOKEN FREQUENCIES
# Only count tokens that occur in the 2,000
# validation Source-1 records.
# ============================================

print("Building validation token vocabulary...")

val_name_tokens = set()
val_address_tokens = set()

for row in s1_val.itertuples(index=False):

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    val_name_tokens.update(get_token_set(name))
    val_address_tokens.update(get_token_set(address))

print("Validation name tokens:", len(val_name_tokens))
print("Validation address tokens:", len(val_address_tokens))

# --------------------------------------------
# Count only those tokens in Source 2 + Source 3
# --------------------------------------------

name_freq_val = Counter()
address_freq_val = Counter()

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "business_name",
            "business_address"
        ],
        chunksize=200000
    ):

        for value in chunk["business_name"].dropna():

            tokens = get_token_set(
                normalize_advanced(value)
            )

            for token in tokens:
                if token in val_name_tokens:
                    name_freq_val[token] += 1

        for value in chunk["business_address"].dropna():

            tokens = get_token_set(
                normalize_advanced(value)
            )

            for token in tokens:
                if token in val_address_tokens:
                    address_freq_val[token] += 1

        rows += len(chunk)

        if rows % 1_000_000 == 0:
            print(f"  processed {rows:,}")

print("\n================================")
print("RELEVANT TOKEN FREQUENCIES READY")
print("================================")

print("Name frequencies stored:", len(name_freq_val))
print("Address frequencies stored:", len(address_freq_val))

print("\nMost common relevant address tokens:")

for token, count in address_freq_val.most_common(20):
    print(f"{token:20s} {count:,}")

print("\nMost common relevant name tokens:")

for token, count in name_freq_val.most_common(20):
    print(f"{token:20s} {count:,}")

Building validation token vocabulary...
Validation name tokens: 2368
Validation address tokens: 5593

Scanning Source 2...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

Scanning Source 3...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

================================
RELEVANT TOKEN FREQUENCIES READY
================================
Name frequencies stored: 2368
Address frequencies stored: 5590

Most common relevant address tokens:
rd                   1,991,344
no                   1,828,214
st                   1,363,137
dr                   1,023,178
ave                  855,833
new                  677,271
city                 650,528
floor                597,386
1                    591,200
nagar                554,836
a                    536,082
delhi                535,364
c                    514,397
ln                   483,740
2                    466,756
north                399,797
b                    393,905
west                 392,422
h                    370,275
mumbai               360,516

Most common relevant name tokens:
limited              1,202,275
private              1,168,000
llc                  1,099,665
ltd                  826,245
inc                  820,146
and                  666,431
center               414,507
pvt                  409,623
partners             314,651
services             311,864
s                    287,004
group                284,006
co                   283,402
corp                 282,009
c                    226,442
india                223,652
holdings             196,043
care                 184,611
l                    183,668
of                   178,972

In [ ]:
# ============================================
# STEP 3 — RAM-SAFE V2 BLOCKING INDEX
#
# Index ONLY the 2,000 validation S1 entities.
# We do NOT build indexes containing S2/S3 rows.
# ============================================

RARE_LIMIT = 250

# --------------------------------------------
# Tiny inverted indexes:
# token -> validation S1 IDs
# --------------------------------------------

rare_name_to_s1 = defaultdict(set)
rare_address_to_s1 = defaultdict(set)

# Exact indexes already exist:
# s1_val_name_map
# s1_val_address_map

# --------------------------------------------
# Build rare-token indexes from validation S1
# --------------------------------------------

for row in s1_val.itertuples(index=False):

    sid = row.entity_id

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    name_tokens = get_token_set(name)
    address_tokens = get_token_set(address)

    # Name token is useful only if its frequency
    # in S2+S3 is <= 250
    for token in name_tokens:

        if name_freq_val.get(token, 10**9) <= RARE_LIMIT:
            rare_name_to_s1[token].add(sid)

    # Same idea for address tokens
    for token in address_tokens:

        if address_freq_val.get(token, 10**9) <= RARE_LIMIT:
            rare_address_to_s1[token].add(sid)


print("================================")
print("RAM-SAFE V2 INDEX READY")
print("================================")

print("Exact name keys:",
      len(s1_val_name_map))

print("Exact address keys:",
      len(s1_val_address_map))

print("Rare name token keys:",
      len(rare_name_to_s1))

print("Rare address token keys:",
      len(rare_address_to_s1))

# Show a few rare tokens
print("\nSample rare address tokens:")

shown = 0

for token in sorted(
    rare_address_to_s1,
    key=lambda x: address_freq_val.get(x, 10**9)
):

    print(
        f"{token:25s} "
        f"freq={address_freq_val.get(token, 0):6d} "
        f"S1={len(rare_address_to_s1[token])}"
    )

    shown += 1

    if shown >= 15:
        break

================================
RAM-SAFE V2 INDEX READY
================================
Exact name keys: 1994
Exact address keys: 2000
Rare name token keys: 830
Rare address token keys: 1561

Sample rare address tokens:
55680                     freq=     1 S1=1
pudukamoor                freq=     1 S1=1
kanankpura                freq=     1 S1=1
49910                     freq=     1 S1=1
sarsj                     freq=     1 S1=1
42laita                   freq=     1 S1=1
sarsol                    freq=     1 S1=1
31782                     freq=     1 S1=1
makhlotganj               freq=     1 S1=1
jalasteen                 freq=     1 S1=1
n12509                    freq=     1 S1=1
chikkadevaraya            freq=     1 S1=1
metukadu                  freq=     1 S1=1
vellu                     freq=     1 S1=1
w259n7892                 freq=     1 S1=1

In [ ]:
# ============================================
# STEP 3B — COUNTRY-AWARE RARE TOKEN INDEX
# ============================================

rare_name_to_s1 = defaultdict(set)
rare_address_to_s1 = defaultdict(set)

for row in s1_val.itertuples(index=False):

    sid = row.entity_id
    country = normalize_country(row.country)

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    # Name tokens
    for token in get_token_set(name):

        if name_freq_val.get(token, 10**9) <= RARE_LIMIT:
            rare_name_to_s1[
                (country, token)
            ].add(sid)

    # Address tokens
    for token in get_token_set(address):

        if address_freq_val.get(token, 10**9) <= RARE_LIMIT:
            rare_address_to_s1[
                (country, token)
            ].add(sid)

print("================================")
print("COUNTRY-AWARE V2 INDEX READY")
print("================================")
print("Rare name keys:", len(rare_name_to_s1))
print("Rare address keys:", len(rare_address_to_s1))

================================
COUNTRY-AWARE V2 INDEX READY
================================
Rare name keys: 830
Rare address keys: 1562

In [ ]:
# ============================================
# STEP 4 — RAM-SAFE V2 CANDIDATE GENERATION
# ============================================

# One small set per validation S1 entity.
candidate_lookup_v2 = {
    sid: set()
    for sid in val_ids
}

def process_validation_candidates(path, source_name):

    print(f"\nScanning {source_name}...")

    rows = 0
    links_added = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = normalize_country(row.country)

            name = normalize_advanced(row.business_name)
            address = normalize_advanced(row.business_address)

            found_s1 = set()

            # --------------------------------
            # BLOCK 1: exact name + country
            # --------------------------------
            if name:
                found_s1.update(
                    s1_val_name_map.get(
                        (country, name),
                        []
                    )
                )

            # --------------------------------
            # BLOCK 2: exact address + country
            # --------------------------------
            if address:
                found_s1.update(
                    s1_val_address_map.get(
                        (country, address),
                        []
                    )
                )

            # --------------------------------
            # BLOCK 3: rare name token + country
            # --------------------------------
            for token in get_token_set(name):

                if name_freq_val.get(
                    token, 10**9
                ) <= RARE_LIMIT:

                    found_s1.update(
                        rare_name_to_s1.get(
                            (country, token),
                            set()
                        )
                    )

            # --------------------------------
            # BLOCK 4: rare address token + country
            # --------------------------------
            for token in get_token_set(address):

                if address_freq_val.get(
                    token, 10**9
                ) <= RARE_LIMIT:

                    found_s1.update(
                        rare_address_to_s1.get(
                            (country, token),
                            set()
                        )
                    )

            # --------------------------------
            # Store only for our 2,000 S1
            # --------------------------------
            for sid in found_s1:

                candidate_lookup_v2[sid].add(eid)
                links_added += 1

            rows += 1

        if rows % 1_000_000 == 0:
            current_links = sum(
                len(x)
                for x in candidate_lookup_v2.values()
            )

            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"candidate links stored: {current_links:,}"
            )

    total_links = sum(
        len(x)
        for x in candidate_lookup_v2.values()
    )

    print(
        f"{source_name} COMPLETE | "
        f"rows: {rows:,} | "
        f"candidate links stored: {total_links:,}"
    )


process_validation_candidates(
    TRAIN_S2,
    "Source 2"
)

process_validation_candidates(
    TRAIN_S3,
    "Source 3"
)

# ============================================
# V2 candidate statistics
# ============================================

candidate_counts = np.array([
    len(candidate_lookup_v2[sid])
    for sid in val_ids
])

total_candidate_pairs = int(
    candidate_counts.sum()
)

zero_candidate_entities = int(
    (candidate_counts == 0).sum()
)

print("\n================================")
print("V2 CANDIDATE STATISTICS")
print("================================")

print("Validation S1:", len(val_ids))
print("Candidate pairs:", total_candidate_pairs)
print(
    "S1 with candidates:",
    int((candidate_counts > 0).sum())
)
print(
    "S1 with zero candidates:",
    zero_candidate_entities
)

print(
    "Average candidates/S1:",
    round(candidate_counts.mean(), 2)
)

print(
    "Median candidates/S1:",
    int(np.median(candidate_counts))
)

print(
    "95th percentile:",
    int(np.percentile(candidate_counts, 95))
)

print(
    "99th percentile:",
    int(np.percentile(candidate_counts, 99))
)

print(
    "Maximum candidates:",
    int(candidate_counts.max())
)

# ============================================
# Candidate recall
# ============================================

total_true_matches = 0
found_true_matches = 0

for sid in val_ids:

    true_ids = gt_lookup.get(
        sid,
        set()
    )

    candidates = candidate_lookup_v2.get(
        sid,
        set()
    )

    total_true_matches += len(true_ids)

    found_true_matches += len(
        true_ids & candidates
    )

missed_true_matches = (
    total_true_matches -
    found_true_matches
)

candidate_recall = (
    found_true_matches /
    total_true_matches
    if total_true_matches
    else 0
)

print("\n================================")
print("V2 RECALL")
print("================================")

print(
    "Total true matches:",
    total_true_matches
)

print(
    "True matches found:",
    found_true_matches
)

print(
    "True matches missed:",
    missed_true_matches
)

print(
    "Candidate recall:",
    f"{candidate_recall * 100:.2f}%"
)

Scanning Source 2...
Source 2: 1,000,000 rows | candidate links stored: 21,189
Source 2: 2,000,000 rows | candidate links stored: 42,314
Source 2: 3,000,000 rows | candidate links stored: 63,556
Source 2: 4,000,000 rows | candidate links stored: 84,509
Source 2: 5,000,000 rows | candidate links stored: 105,727
Source 2 COMPLETE | rows: 5,034,616 | candidate links stored: 106,473

Scanning Source 3...
Source 3: 1,000,000 rows | candidate links stored: 126,387
Source 3: 2,000,000 rows | candidate links stored: 146,449
Source 3: 3,000,000 rows | candidate links stored: 166,854
Source 3: 4,000,000 rows | candidate links stored: 186,931
Source 3: 5,000,000 rows | candidate links stored: 207,038
Source 3 COMPLETE | rows: 5,285,603 | candidate links stored: 212,682

================================
V2 CANDIDATE STATISTICS
================================
Validation S1: 2000
Candidate pairs: 212682
S1 with candidates: 1896
S1 with zero candidates: 104
Average candidates/S1: 106.34
Median candidates/S1: 66
95th percentile: 343
99th percentile: 444
Maximum candidates: 736

================================
V2 RECALL
================================
Total true matches: 6855
True matches found: 5013
True matches missed: 1842
Candidate recall: 73.13%

In [ ]:
# ============================================
# STEP 5 — V3 ADDRESS MULTI-TOKEN BLOCK
#
# Add:
#   country
#   + at least 2 shared address tokens
#   + at least 1 shared token with frequency <=2500
#
# We keep the existing V2 candidates and add
# only new candidates from this block.
# ============================================

V3_RARE_LIMIT = 2500

# --------------------------------------------
# Store normalized address token sets for
# validation S1 only
# --------------------------------------------

val_address_tokens = {}
val_country = {}

for row in s1_val.itertuples(index=False):

    sid = row.entity_id

    val_country[sid] = normalize_country(row.country)

    val_address_tokens[sid] = get_token_set(
        normalize_advanced(row.business_address)
    )

# --------------------------------------------
# Build token -> validation S1 IDs
# ONLY for tokens that can participate in V3
# --------------------------------------------

address_token_to_s1_v3 = defaultdict(set)

for sid in val_ids:

    country = val_country[sid]
    tokens = val_address_tokens[sid]

    for token in tokens:

        if address_freq_val.get(
            token, 10**9
        ) <= V3_RARE_LIMIT:

            address_token_to_s1_v3[
                (country, token)
            ].add(sid)

print("================================")
print("V3 ADDRESS INDEX READY")
print("================================")
print(
    "Rare address token keys:",
    len(address_token_to_s1_v3)
)

# --------------------------------------------
# Start from verified V2 candidates
# --------------------------------------------

candidate_lookup_v3 = {
    sid: set(candidates)
    for sid, candidates in candidate_lookup_v2.items()
}

new_links = 0

def process_v3_source(path, source_name):

    global new_links

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id

            country = normalize_country(row.country)

            address = normalize_advanced(
                row.business_address
            )

            source_tokens = get_token_set(address)

            if not source_tokens:
                rows += 1
                continue

            # --------------------------------
            # Get possible S1 entities through
            # rare address tokens
            # --------------------------------

            possible_s1 = set()

            for token in source_tokens:

                if address_freq_val.get(
                    token, 10**9
                ) <= V3_RARE_LIMIT:

                    possible_s1.update(
                        address_token_to_s1_v3.get(
                            (country, token),
                            set()
                        )
                    )

            # --------------------------------
            # Require at least 2 shared
            # address tokens
            # --------------------------------

            for sid in possible_s1:

                s1_tokens = val_address_tokens[sid]

                shared = source_tokens & s1_tokens

                if len(shared) >= 2:

                    # At least one shared token
                    # must satisfy the rarity rule
                    rare_shared = any(
                        address_freq_val.get(
                            token,
                            10**9
                        ) <= V3_RARE_LIMIT
                        for token in shared
                    )

                    if rare_shared:

                        if eid not in candidate_lookup_v3[sid]:

                            candidate_lookup_v3[sid].add(eid)
                            new_links += 1

            rows += 1

        if rows % 1_000_000 == 0:

            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"new V3 links: {new_links:,}"
            )

    print(
        f"{source_name} COMPLETE | "
        f"new V3 links: {new_links:,}"
    )


process_v3_source(
    TRAIN_S2,
    "Source 2"
)

process_v3_source(
    TRAIN_S3,
    "Source 3"
)

# --------------------------------------------
# V3 statistics
# --------------------------------------------

v3_counts = np.array([
    len(candidate_lookup_v3[sid])
    for sid in val_ids
])

v3_total_candidates = int(
    v3_counts.sum()
)

v3_zero = int(
    (v3_counts == 0).sum()
)

# --------------------------------------------
# Recall
# --------------------------------------------

v3_total_true = 0
v3_found_true = 0

for sid in val_ids:

    true_ids = gt_lookup.get(
        sid,
        set()
    )

    candidates = candidate_lookup_v3.get(
        sid,
        set()
    )

    v3_total_true += len(true_ids)

    v3_found_true += len(
        true_ids & candidates
    )

v3_missed = (
    v3_total_true -
    v3_found_true
)

v3_recall = (
    v3_found_true /
    v3_total_true
)

print("\n================================")
print("V3 RESULTS")
print("================================")

print("V2 candidate pairs:", 212682)
print("New V3 links:", new_links)
print("V3 candidate pairs:", v3_total_candidates)

print(
    "Average candidates/S1:",
    round(v3_counts.mean(), 2)
)

print(
    "Median candidates/S1:",
    int(np.median(v3_counts))
)

print(
    "P95:",
    int(np.percentile(v3_counts, 95))
)

print(
    "P99:",
    int(np.percentile(v3_counts, 99))
)

print(
    "Maximum:",
    int(v3_counts.max())
)

print(
    "Zero-candidate S1:",
    v3_zero
)

print("\nTrue matches:", v3_total_true)
print("Found:", v3_found_true)
print("Missed:", v3_missed)

print(
    "Candidate recall:",
    f"{v3_recall * 100:.2f}%"
)

print(
    "Recall improvement:",
    f"{(v3_recall - 0.7313) * 100:+.2f} percentage points"
)

================================
V3 ADDRESS INDEX READY
================================
Rare address token keys: 3690

Scanning Source 2...
Source 2: 1,000,000 rows | new V3 links: 125,377
Source 2: 2,000,000 rows | new V3 links: 250,858
Source 2: 3,000,000 rows | new V3 links: 376,486
Source 2: 4,000,000 rows | new V3 links: 501,846
Source 2: 5,000,000 rows | new V3 links: 627,337
Source 2 COMPLETE | new V3 links: 631,716

Scanning Source 3...
Source 3: 1,000,000 rows | new V3 links: 721,230
Source 3: 2,000,000 rows | new V3 links: 810,822
Source 3: 3,000,000 rows | new V3 links: 900,550
Source 3: 4,000,000 rows | new V3 links: 989,334
Source 3: 5,000,000 rows | new V3 links: 1,078,865
Source 3 COMPLETE | new V3 links: 1,104,311

================================
V3 RESULTS
================================
V2 candidate pairs: 212682
New V3 links: 1104311
V3 candidate pairs: 1316993
Average candidates/S1: 658.5
Median candidates/S1: 388
P95: 2206
P99: 3345
Maximum: 6954
Zero-candidate S1: 29

True matches: 6855
Found: 6131
Missed: 724
Candidate recall: 89.44%
Recall improvement: +16.31 percentage points

In [ ]:
# ============================================
# STEP 6 — V3 ADDRESS BLOCK, RARITY <= 1000
# ============================================

V3_TEST_LIMIT = 1000

# --------------------------------------------
# Build token -> validation S1 index
# --------------------------------------------

address_token_to_s1_1000 = defaultdict(set)

for sid in val_ids:

    country = val_country[sid]
    tokens = val_address_tokens[sid]

    for token in tokens:

        if address_freq_val.get(
            token, 10**9
        ) <= V3_TEST_LIMIT:

            address_token_to_s1_1000[
                (country, token)
            ].add(sid)

print("Rare address token keys:",
      len(address_token_to_s1_1000))

# --------------------------------------------
# Start from V2
# --------------------------------------------

candidate_lookup_1000 = {
    sid: set(candidates)
    for sid, candidates in candidate_lookup_v2.items()
}

new_links_1000 = 0


def process_v3_1000(path, source_name):

    global new_links_1000

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id

            country = normalize_country(row.country)

            address = normalize_advanced(
                row.business_address
            )

            source_tokens = get_token_set(address)

            if not source_tokens:
                rows += 1
                continue

            possible_s1 = set()

            for token in source_tokens:

                if address_freq_val.get(
                    token, 10**9
                ) <= V3_TEST_LIMIT:

                    possible_s1.update(
                        address_token_to_s1_1000.get(
                            (country, token),
                            set()
                        )
                    )

            for sid in possible_s1:

                shared = (
                    source_tokens &
                    val_address_tokens[sid]
                )

                if len(shared) >= 2:

                    if any(
                        address_freq_val.get(
                            token,
                            10**9
                        ) <= V3_TEST_LIMIT
                        for token in shared
                    ):

                        if eid not in candidate_lookup_1000[sid]:

                            candidate_lookup_1000[sid].add(eid)
                            new_links_1000 += 1

            rows += 1

        if rows % 1_000_000 == 0:
            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"new links: {new_links_1000:,}"
            )

    print(
        f"{source_name} COMPLETE | "
        f"new links: {new_links_1000:,}"
    )


process_v3_1000(
    TRAIN_S2,
    "Source 2"
)

process_v3_1000(
    TRAIN_S3,
    "Source 3"
)

# --------------------------------------------
# Statistics
# --------------------------------------------

counts_1000 = np.array([
    len(candidate_lookup_1000[sid])
    for sid in val_ids
])

total_candidates_1000 = int(
    counts_1000.sum()
)

zero_1000 = int(
    (counts_1000 == 0).sum()
)

total_true_1000 = 0
found_true_1000 = 0

for sid in val_ids:

    true_ids = gt_lookup.get(
        sid,
        set()
    )

    candidates = candidate_lookup_1000[sid]

    total_true_1000 += len(true_ids)

    found_true_1000 += len(
        true_ids & candidates
    )

recall_1000 = (
    found_true_1000 /
    total_true_1000
)

print("\n================================")
print("V3 <=1000 RESULTS")
print("================================")

print(
    "Candidate pairs:",
    total_candidates_1000
)

print(
    "New links:",
    new_links_1000
)

print(
    "Average candidates/S1:",
    round(counts_1000.mean(), 2)
)

print(
    "Median:",
    int(np.median(counts_1000))
)

print(
    "P95:",
    int(np.percentile(counts_1000, 95))
)

print(
    "P99:",
    int(np.percentile(counts_1000, 99))
)

print(
    "Maximum:",
    int(counts_1000.max())
)

print(
    "Zero-candidate S1:",
    zero_1000
)

print(
    "True matches found:",
    found_true_1000
)

print(
    "True matches missed:",
    total_true_1000 -
    found_true_1000
)

print(
    "Candidate recall:",
    f"{recall_1000 * 100:.2f}%"
)

Rare address token keys: 2744

Scanning Source 2...
Source 2: 1,000,000 rows | new links: 35,679
Source 2: 2,000,000 rows | new links: 72,001
Source 2: 3,000,000 rows | new links: 108,138
Source 2: 4,000,000 rows | new links: 144,166
Source 2: 5,000,000 rows | new links: 180,105
Source 2 COMPLETE | new links: 181,356

Scanning Source 3...
Source 3: 1,000,000 rows | new links: 207,418
Source 3: 2,000,000 rows | new links: 233,305
Source 3: 3,000,000 rows | new links: 259,234
Source 3: 4,000,000 rows | new links: 284,966
Source 3: 5,000,000 rows | new links: 311,087
Source 3 COMPLETE | new links: 318,418

================================
V3 <=1000 RESULTS
================================
Candidate pairs: 531100
New links: 318418
Average candidates/S1: 265.55
Median: 179
P95: 860
P99: 1363
Maximum: 1936
Zero-candidate S1: 50
True matches found: 5720
True matches missed: 1135
Candidate recall: 83.44%

In [ ]:
# ============================================
# STEP 7
# Add:
# country
# + shared address number
# + shared address token
# + number frequency <= 1000
#
# Starting from V3 <=1000.
# ============================================

NUMBER_LIMIT = 1000

# --------------------------------------------
# Step 1: Find address numbers used by
# validation S1
# --------------------------------------------

val_address_numbers = {}

validation_numbers = set()

for sid in val_ids:

    address = normalize_advanced(
        s1_val.loc[
            s1_val["entity_id"] == sid,
            "business_address"
        ].iloc[0]
    )

    nums = extract_numbers(address)

    val_address_numbers[sid] = nums
    validation_numbers.update(nums)

print(
    "Validation address numbers:",
    len(validation_numbers)
)

# --------------------------------------------
# Step 2: Count only relevant numbers
# across Source 2 + Source 3
# --------------------------------------------

number_freq_val = Counter()

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"\nCounting numbers in {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_address"],
        chunksize=200000
    ):

        for value in chunk["business_address"].dropna():

            nums = extract_numbers(
                normalize_advanced(value)
            )

            for num in nums:

                if num in validation_numbers:
                    number_freq_val[num] += 1

        rows += len(chunk)

        if rows % 1_000_000 == 0:
            print(
                f"  processed {rows:,}"
            )

print("\nRelevant number frequencies:",
      len(number_freq_val))

# --------------------------------------------
# Step 3: Build country + number -> S1
# index, only for numbers <= 1000
# --------------------------------------------

number_to_s1 = defaultdict(set)

for sid in val_ids:

    country = val_country[sid]

    for num in val_address_numbers[sid]:

        if number_freq_val.get(
            num,
            10**9
        ) <= NUMBER_LIMIT:

            number_to_s1[
                (country, num)
            ].add(sid)

print(
    "Country-number keys:",
    len(number_to_s1)
)

# --------------------------------------------
# Step 4: Start from V3 <=1000
# --------------------------------------------

candidate_lookup_num = {
    sid: set(candidates)
    for sid, candidates in candidate_lookup_1000.items()
}

new_number_links = 0


def process_number_block(path, source_name):

    global new_number_links

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id

            country = normalize_country(
                row.country
            )

            address = normalize_advanced(
                row.business_address
            )

            source_numbers = extract_numbers(
                address
            )

            if not source_numbers:
                rows += 1
                continue

            source_tokens = get_token_set(
                address
            )

            if not source_tokens:
                rows += 1
                continue

            # Possible S1 entities from shared
            # country + address number
            possible_s1 = set()

            for num in source_numbers:

                if number_freq_val.get(
                    num,
                    10**9
                ) <= NUMBER_LIMIT:

                    possible_s1.update(
                        number_to_s1.get(
                            (country, num),
                            set()
                        )
                    )

            # Require BOTH:
            # 1. shared number
            # 2. shared address token
            for sid in possible_s1:

                shared_numbers = (
                    source_numbers &
                    val_address_numbers[sid]
                )

                if not shared_numbers:
                    continue

                shared_tokens = (
                    source_tokens &
                    val_address_tokens[sid]
                )

                if not shared_tokens:
                    continue

                if eid not in candidate_lookup_num[sid]:

                    candidate_lookup_num[sid].add(eid)
                    new_number_links += 1

            rows += 1

        if rows % 1_000_000 == 0:

            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"new links: {new_number_links:,}"
            )

    print(
        f"{source_name} COMPLETE | "
        f"new links: {new_number_links:,}"
    )


process_number_block(
    TRAIN_S2,
    "Source 2"
)

process_number_block(
    TRAIN_S3,
    "Source 3"
)

# --------------------------------------------
# Final statistics
# --------------------------------------------

number_counts = np.array([
    len(candidate_lookup_num[sid])
    for sid in val_ids
])

total_number_candidates = int(
    number_counts.sum()
)

zero_number = int(
    (number_counts == 0).sum()
)

found_number = 0
total_number_true = 0

for sid in val_ids:

    true_ids = gt_lookup.get(
        sid,
        set()
    )

    candidates = candidate_lookup_num[sid]

    total_number_true += len(true_ids)

    found_number += len(
        true_ids & candidates
    )

recall_number = (
    found_number /
    total_number_true
)

print("\n================================")
print("V3 + NUMBER BLOCK RESULTS")
print("================================")

print(
    "Previous V3 <=1000 candidates:",
    531100
)

print(
    "New links:",
    new_number_links
)

print(
    "Final candidate pairs:",
    total_number_candidates
)

print(
    "Average candidates/S1:",
    round(number_counts.mean(), 2)
)

print(
    "Median:",
    int(np.median(number_counts))
)

print(
    "P95:",
    int(np.percentile(number_counts, 95))
)

print(
    "P99:",
    int(np.percentile(number_counts, 99))
)

print(
    "Maximum:",
    int(number_counts.max())
)

print(
    "Zero-candidate S1:",
    zero_number
)

print(
    "True matches found:",
    found_number
)

print(
    "True matches missed:",
    total_number_true -
    found_number
)

print(
    "Candidate recall:",
    f"{recall_number * 100:.2f}%"
)

Validation address numbers: 1285

Counting numbers in Source 2...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

Counting numbers in Source 3...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

Relevant number frequencies: 1283
Country-number keys: 613

Scanning Source 2...
Source 2: 1,000,000 rows | new links: 11,852
Source 2: 2,000,000 rows | new links: 23,767
Source 2: 3,000,000 rows | new links: 35,768
Source 2: 4,000,000 rows | new links: 47,696
Source 2: 5,000,000 rows | new links: 59,571
Source 2 COMPLETE | new links: 59,952

Scanning Source 3...
Source 3: 1,000,000 rows | new links: 72,867
Source 3: 2,000,000 rows | new links: 85,686
Source 3: 3,000,000 rows | new links: 98,300
Source 3: 4,000,000 rows | new links: 111,083
Source 3: 5,000,000 rows | new links: 123,854
Source 3 COMPLETE | new links: 127,486

================================
V3 + NUMBER BLOCK RESULTS
================================
Previous V3 <=1000 candidates: 531100
New links: 127486
Final candidate pairs: 658586
Average candidates/S1: 329.29
Median: 233
P95: 937
P99: 1375
Maximum: 1936
Zero-candidate S1: 50
True matches found: 5720
True matches missed: 1135
Candidate recall: 83.44%

In [ ]:
# ============================================
# STEP 8 — TEST PAIR FEATURE ENGINE
# ============================================

from difflib import SequenceMatcher

def similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


def pair_features(s1_row, s2_row):

    name1 = normalize_advanced(s1_row["business_name"])
    name2 = normalize_advanced(s2_row["business_name"])

    addr1 = normalize_advanced(s1_row["business_address"])
    addr2 = normalize_advanced(s2_row["business_address"])

    country1 = normalize_country(s1_row["country"])
    country2 = normalize_country(s2_row["country"])

    name_tokens1 = get_token_set(name1)
    name_tokens2 = get_token_set(name2)

    addr_tokens1 = get_token_set(addr1)
    addr_tokens2 = get_token_set(addr2)

    shared_name = name_tokens1 & name_tokens2
    shared_addr = addr_tokens1 & addr_tokens2

    nums1 = extract_numbers(addr1)
    nums2 = extract_numbers(addr2)

    shared_numbers = nums1 & nums2

    name_union = name_tokens1 | name_tokens2
    addr_union = addr_tokens1 | addr_tokens2

    name_jaccard = (
        len(shared_name) / len(name_union)
        if name_union else 0.0
    )

    address_jaccard = (
        len(shared_addr) / len(addr_union)
        if addr_union else 0.0
    )

    return {
        "name_exact": int(
            bool(name1) and name1 == name2
        ),

        "address_exact": int(
            bool(addr1) and addr1 == addr2
        ),

        "country_exact": int(
            country1 == country2
        ),

        "name_similarity": similarity(
            name1, name2
        ),

        "address_similarity": similarity(
            addr1, addr2
        ),

        "name_token_overlap": (
            len(shared_name) /
            max(1, min(
                len(name_tokens1),
                len(name_tokens2)
            ))
        ),

        "address_token_overlap": (
            len(shared_addr) /
            max(1, min(
                len(addr_tokens1),
                len(addr_tokens2)
            ))
        ),

        "name_jaccard": name_jaccard,

        "address_jaccard": address_jaccard,

        "shared_name_token_count": len(
            shared_name
        ),

        "shared_address_token_count": len(
            shared_addr
        ),

        "shared_address_number_count": len(
            shared_numbers
        ),

        "name_length_diff": abs(
            len(name1) - len(name2)
        ),

        "address_length_diff": abs(
            len(addr1) - len(addr2)
        ),

        "name_length_ratio": (
            min(len(name1), len(name2)) /
            max(1, max(len(name1), len(name2)))
        ),

        "address_length_ratio": (
            min(len(addr1), len(addr2)) /
            max(1, max(len(addr1), len(addr2)))
        )
    }


print("Feature engine created successfully.")

Feature engine created successfully.

In [ ]:
# ============================================
# STEP 9 — TEST FEATURES ON REAL CANDIDATES
# ============================================

# Take 10 validation S1 entities that have candidates
sample_sids = [
    sid for sid in val_ids
    if len(candidate_lookup_1000.get(sid, set())) > 0
][:10]

# Collect 1 candidate from each
sample_pairs = []

for sid in sample_sids:

    candidate_ids = list(
        candidate_lookup_1000[sid]
    )

    if candidate_ids:
        sample_pairs.append(
            (sid, candidate_ids[0])
        )

print("Sample candidate pairs:", len(sample_pairs))

# --------------------------------------------
# We need the actual Source-2/3 records.
# Collect only these candidate entity IDs.
# --------------------------------------------

needed_eids = {
    eid
    for _, eid in sample_pairs
}

candidate_records = {}

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"Scanning {source_name} for sample records...")

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        found = chunk[
            chunk["entity_id"].isin(needed_eids)
        ]

        for row in found.itertuples(index=False):

            candidate_records[
                row.entity_id
            ] = {
                "entity_id": row.entity_id,
                "business_name": row.business_name,
                "business_address": row.business_address,
                "country": row.country
            }

        if len(candidate_records) == len(needed_eids):
            break

    if len(candidate_records) == len(needed_eids):
        break

print(
    "Candidate records found:",
    len(candidate_records),
    "/",
    len(needed_eids)
)

# --------------------------------------------
# Calculate features
# --------------------------------------------

feature_rows = []

for sid, eid in sample_pairs:

    s1_row = s1_10k[
        s1_10k["entity_id"] == sid
    ].iloc[0].to_dict()

    s2_row = candidate_records[eid]

    features = pair_features(
        s1_row,
        s2_row
    )

    features["source1_entity_id"] = sid
    features["matched_entity_id"] = eid

    feature_rows.append(features)

sample_features = pd.DataFrame(
    feature_rows
)

print("\n================================")
print("FEATURE TEST")
print("================================")

print(
    sample_features.to_string(
        index=False
    )
)

print("\nShape:", sample_features.shape)

print(
    "\nMissing values:",
    sample_features.isna().sum().sum()
)

Sample candidate pairs: 10
Scanning Source 2 for sample records...
Scanning Source 3 for sample records...
Candidate records found: 10 / 10

================================
FEATURE TEST
================================
 name_exact  address_exact  country_exact  name_similarity  address_similarity  name_token_overlap  address_token_overlap  name_jaccard  address_jaccard  shared_name_token_count  shared_address_token_count  shared_address_number_count  name_length_diff  address_length_diff  name_length_ratio  address_length_ratio source1_entity_id matched_entity_id
          0              0              1         0.200000            0.271186                0.00               0.100000         0.000         0.047619                        0                           1                            0                 2                   32           0.904762              0.573333      S1-909714160      S2-909169979
          0              0              1         0.384615            0.557143                0.00               0.600000         0.000         0.315789                        0                           6                            0                 2                   20           0.857143              0.750000      S1-674857487      S2-557673045
          0              0              1         0.703704            0.586957                1.00               0.571429         1.000         0.285714                        4                           4                            1                 0                    6           1.000000              0.877551      S1-892685004      S2-700088579
          1              0              1         1.000000            0.351351                1.00               0.000000         1.000         0.000000                        5                           0                            0                 0                   14           1.000000              0.681818      S1-763005688      S2-786748839
          0              0              1         0.238095            0.370370                0.00               0.400000         0.000         0.222222                        0                           2                            1                22                    2           0.312500              0.928571       S1-23094221      S2-549335203
          0              0              1         0.238095            0.533333                0.00               0.777778         0.000         0.411765                        0                           7                            1                12                   37           0.555556              0.569767      S1-790336857      S2-837348763
          0              0              1         0.579710            0.407407                0.25               0.200000         0.125         0.105263                        1                           2                            0                 9                    0           0.769231              1.000000      S1-170773933      S3-570915975
          0              0              1         0.533333            0.257143                0.50               0.000000         0.200         0.000000                        1                           0                            0                 3                    2           0.875000              0.944444      S1-273481256       S3-51697838
          0              0              1         0.210526            0.542373                0.00               0.750000         0.000         0.333333                        0                           3                            0                13                   19           0.628571              0.512821      S1-721140591      S2-851456492
          0              0              1         0.190476            0.335484                0.00               0.166667         0.000         0.068966                        0                           2                            0                20                   31           0.354839              0.666667      S1-794089336      S2-680853078

Shape: (10, 18)

Missing values: 0

In [ ]:
# ============================================
# STEP 10 — TRAINING-SIDE V3 <=1000 BLOCKER
# ============================================

# IMPORTANT:
# This uses ONLY the 8,000 training S1 entities.
# The 2,000 validation entities remain untouched.

train_ids = set(
    s1_train["entity_id"]
)

print("Training S1 entities:", len(train_ids))

# --------------------------------------------
# Country / normalized fields for training S1
# --------------------------------------------

train_country = {}
train_address_tokens = {}
train_name_tokens = {}

for row in s1_train.itertuples(index=False):

    sid = row.entity_id

    train_country[sid] = normalize_country(
        row.country
    )

    train_address_tokens[sid] = get_token_set(
        normalize_advanced(
            row.business_address
        )
    )

    train_name_tokens[sid] = get_token_set(
        normalize_advanced(
            row.business_name
        )
    )

# --------------------------------------------
# Exact maps
# --------------------------------------------

train_name_map = defaultdict(list)
train_address_map = defaultdict(list)

for row in s1_train.itertuples(index=False):

    sid = row.entity_id
    country = train_country[sid]

    name = normalize_advanced(
        row.business_name
    )

    address = normalize_advanced(
        row.business_address
    )

    if name:
        train_name_map[
            (country, name)
        ].append(sid)

    if address:
        train_address_map[
            (country, address)
        ].append(sid)

# --------------------------------------------
# Rare address token index
# <=1000
# --------------------------------------------

TRAIN_RARE_LIMIT = 1000

train_address_token_to_s1 = defaultdict(set)

for sid in train_ids:

    country = train_country[sid]

    for token in train_address_tokens[sid]:

        if address_freq_val.get(
            token,
            10**9
        ) <= TRAIN_RARE_LIMIT:

            train_address_token_to_s1[
                (country, token)
            ].add(sid)

print("\n================================")
print("TRAINING BLOCK INDEX READY")
print("================================")

print(
    "Exact name keys:",
    len(train_name_map)
)

print(
    "Exact address keys:",
    len(train_address_map)
)

print(
    "Rare address keys:",
    len(train_address_token_to_s1)
)

Training S1 entities: 8000

================================
TRAINING BLOCK INDEX READY
================================
Exact name keys: 7898
Exact address keys: 7999
Rare address keys: 555

In [ ]:
# ============================================
# STEP 10B — TRAINING-SPECIFIC TOKEN FREQUENCY
# ============================================

print("Building training address-token vocabulary...")

train_address_vocab = set()

for row in s1_train.itertuples(index=False):

    address = normalize_advanced(
        row.business_address
    )

    train_address_vocab.update(
        get_token_set(address)
    )

print(
    "Training address tokens:",
    len(train_address_vocab)
)

# --------------------------------------------
# Count only tokens appearing in TRAIN S1
# across full Source 2 + Source 3
# --------------------------------------------

train_address_freq = Counter()

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_address"],
        chunksize=200000
    ):

        for value in chunk["business_address"].dropna():

            tokens = get_token_set(
                normalize_advanced(value)
            )

            for token in tokens:

                if token in train_address_vocab:
                    train_address_freq[token] += 1

        rows += len(chunk)

        if rows % 1_000_000 == 0:
            print(
                f"  processed {rows:,}"
            )

print("\n================================")
print("TRAINING FREQUENCIES READY")
print("================================")

print(
    "Training frequencies stored:",
    len(train_address_freq)
)

print("\nMost common training-relevant address tokens:")

for token, count in train_address_freq.most_common(20):
    print(
        f"{token:20s} {count:,}"
    )

Building training address-token vocabulary...
Training address tokens: 14831

Scanning Source 2...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

Scanning Source 3...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

================================
TRAINING FREQUENCIES READY
================================
Training frequencies stored: 14810

Most common training-relevant address tokens:
rd                   1,991,344
no                   1,828,214
st                   1,363,137
dr                   1,023,178
ave                  855,833
new                  677,271
city                 650,528
floor                597,386
1                    591,200
nagar                554,836
a                    536,082
delhi                535,364
c                    514,397
ln                   483,740
2                    466,756
north                399,797
b                    393,905
west                 392,422
h                    370,275
mumbai               360,516

In [ ]:
# ============================================
# STEP 10C — TRAINING-SPECIFIC NAME FREQUENCY
# ============================================

print("Building training name-token vocabulary...")

train_name_vocab = set()

for row in s1_train.itertuples(index=False):

    name = normalize_advanced(
        row.business_name
    )

    train_name_vocab.update(
        get_token_set(name)
    )

print(
    "Training name tokens:",
    len(train_name_vocab)
)

# --------------------------------------------
# Count only tokens appearing in TRAIN S1
# across full Source 2 + Source 3
# --------------------------------------------

train_name_freq = Counter()

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_name"],
        chunksize=200000
    ):

        for value in chunk["business_name"].dropna():

            tokens = get_token_set(
                normalize_advanced(value)
            )

            for token in tokens:

                if token in train_name_vocab:
                    train_name_freq[token] += 1

        rows += len(chunk)

        if rows % 1_000_000 == 0:
            print(
                f"  processed {rows:,}"
            )

print("\n================================")
print("TRAINING NAME FREQUENCIES READY")
print("================================")

print(
    "Training name frequencies stored:",
    len(train_name_freq)
)

print("\nMost common training-relevant name tokens:")

for token, count in train_name_freq.most_common(20):
    print(
        f"{token:20s} {count:,}"
    )

Building training name-token vocabulary...
Training name tokens: 6387

Scanning Source 2...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

Scanning Source 3...
  processed 1,000,000
  processed 2,000,000
  processed 3,000,000
  processed 4,000,000
  processed 5,000,000

================================
TRAINING NAME FREQUENCIES READY
================================
Training name frequencies stored: 6386

Most common training-relevant name tokens:
limited              1,202,275
private              1,168,000
llc                  1,099,665
ltd                  826,245
inc                  820,146
and                  666,431
center               414,507
pvt                  409,623
partners             314,651
services             311,864
s                    287,004
group                284,006
co                   283,402
corp                 282,009
c                    226,442
india                223,652
holdings             196,043
care                 184,611
l                    183,668
of                   178,972

In [ ]:
# ============================================
# STEP 11 — TRAINING V3 <=1000 INDEX
# ============================================

TRAIN_RARE_NAME_LIMIT = 250
TRAIN_ADDRESS_LIMIT = 1000

# --------------------------------------------
# Exact + rare-name index
# --------------------------------------------

train_rare_name_to_s1 = defaultdict(set)

# Address token index for V3 <=1000
train_address_token_to_s1 = defaultdict(set)

for row in s1_train.itertuples(index=False):

    sid = row.entity_id
    country = train_country[sid]

    # -----------------------------
    # Name
    # -----------------------------

    for token in train_name_tokens[sid]:

        if train_name_freq.get(
            token,
            10**9
        ) <= TRAIN_RARE_NAME_LIMIT:

            train_rare_name_to_s1[
                (country, token)
            ].add(sid)

    # -----------------------------
    # Address
    # -----------------------------

    for token in train_address_tokens[sid]:

        if train_address_freq.get(
            token,
            10**9
        ) <= TRAIN_ADDRESS_LIMIT:

            train_address_token_to_s1[
                (country, token)
            ].add(sid)

print("================================")
print("TRAINING V3 INDEX READY")
print("================================")

print(
    "Exact name keys:",
    len(train_name_map)
)

print(
    "Exact address keys:",
    len(train_address_map)
)

print(
    "Rare name keys:",
    len(train_rare_name_to_s1)
)

print(
    "Address <=1000 keys:",
    len(train_address_token_to_s1)
)

================================
TRAINING V3 INDEX READY
================================
Exact name keys: 7898
Exact address keys: 7999
Rare name keys: 3186
Address <=1000 keys: 9991

In [ ]:
# ============================================
# STEP 12 — BUILD CONTROLLED ML TRAINING SET
#
# Training only:
# 8,000 S1 entities
#
# Keep:
#   - ALL candidate positives
#   - controlled number of candidate negatives
#
# This avoids a giant RAM-heavy pair dataset.
# ============================================

import random

random.seed(42)

NEGATIVES_PER_POSITIVE = 8
MIN_NEGATIVES_IF_LOW_POSITIVES = 50000

# --------------------------------------------
# Ground truth for TRAINING S1
# --------------------------------------------

train_gt = {
    sid: gt_lookup.get(sid, set())
    for sid in train_ids
}

# --------------------------------------------
# Store discovered positive pairs
# --------------------------------------------

positive_pairs = []

# We will temporarily keep a controlled
# reservoir of negative pairs.
negative_reservoir = []

# Maximum negatives will be determined
# after we know positive count.
# Start with a generous cap.
MAX_NEGATIVE_RESERVOIR = 200000

rng = random.Random(42)

total_candidate_pairs_seen = 0
positive_pairs_seen = 0

def add_negative(pair):

    global negative_reservoir

    # Reservoir sampling
    n = len(negative_reservoir)

    if n < MAX_NEGATIVE_RESERVOIR:

        negative_reservoir.append(pair)

    else:

        j = rng.randint(
            0,
            total_candidate_pairs_seen - positive_pairs_seen - 1
        )

        if j < MAX_NEGATIVE_RESERVOIR:
            negative_reservoir[j] = pair


def process_training_source(path, source_name):

    global total_candidate_pairs_seen
    global positive_pairs_seen

    print(f"\nScanning {source_name}...")

    rows = 0
    local_candidates = 0
    local_positives = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id

            country = normalize_country(
                row.country
            )

            name = normalize_advanced(
                row.business_name
            )

            address = normalize_advanced(
                row.business_address
            )

            found_s1 = set()

            # -----------------------------
            # Exact name + country
            # -----------------------------

            if name:

                found_s1.update(
                    train_name_map.get(
                        (country, name),
                        []
                    )
                )

            # -----------------------------
            # Exact address + country
            # -----------------------------

            if address:

                found_s1.update(
                    train_address_map.get(
                        (country, address),
                        []
                    )
                )

            # -----------------------------
            # Rare name <=250
            # -----------------------------

            for token in get_token_set(name):

                if train_name_freq.get(
                    token,
                    10**9
                ) <= TRAIN_RARE_NAME_LIMIT:

                    found_s1.update(
                        train_rare_name_to_s1.get(
                            (country, token),
                            set()
                        )
                    )

            # -----------------------------
            # Address token <=1000
            # -----------------------------

            for token in get_token_set(address):

                if train_address_freq.get(
                    token,
                    10**9
                ) <= TRAIN_ADDRESS_LIMIT:

                    found_s1.update(
                        train_address_token_to_s1.get(
                            (country, token),
                            set()
                        )
                    )

            # -----------------------------
            # Label candidate pairs
            # -----------------------------

            for sid in found_s1:

                pair = (sid, eid)

                total_candidate_pairs_seen += 1
                local_candidates += 1

                true_ids = train_gt.get(
                    sid,
                    set()
                )

                if eid in true_ids:

                    positive_pairs.append(pair)

                    positive_pairs_seen += 1
                    local_positives += 1

                else:

                    add_negative(pair)

            rows += 1

        if rows % 1_000_000 == 0:

            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"candidates: {local_candidates:,} | "
                f"positives: {local_positives:,}"
            )

    print(
        f"{source_name} COMPLETE | "
        f"candidates: {local_candidates:,} | "
        f"positives: {local_positives:,}"
    )


process_training_source(
    TRAIN_S2,
    "Source 2"
)

process_training_source(
    TRAIN_S3,
    "Source 3"
)

# --------------------------------------------
# Remove duplicate positives
# --------------------------------------------

positive_pairs = list(
    set(positive_pairs)
)

# --------------------------------------------
# Select negatives
# --------------------------------------------

target_negatives = max(
    len(positive_pairs) * NEGATIVES_PER_POSITIVE,
    MIN_NEGATIVES_IF_LOW_POSITIVES
)

target_negatives = min(
    target_negatives,
    len(negative_reservoir)
)

negative_pairs = negative_reservoir[
    :target_negatives
]

print("\n================================")
print("ML TRAINING CANDIDATES")
print("================================")

print(
    "Total candidate pairs seen:",
    total_candidate_pairs_seen
)

print(
    "Unique positive pairs:",
    len(positive_pairs)
)

print(
    "Negative reservoir:",
    len(negative_reservoir)
)

print(
    "Negatives selected:",
    len(negative_pairs)
)

print(
    "Total ML pairs:",
    len(positive_pairs) +
    len(negative_pairs)
)

print(
    "Positive rate:",
    round(
        len(positive_pairs) /
        max(
            1,
            len(positive_pairs) +
            len(negative_pairs)
        ) * 100,
        2
    ),
    "%"
)

Scanning Source 2...
Source 2: 1,000,000 rows | candidates: 336,041 | positives: 2,203
Source 2: 2,000,000 rows | candidates: 671,616 | positives: 4,448
Source 2: 3,000,000 rows | candidates: 1,006,929 | positives: 6,748
Source 2: 4,000,000 rows | candidates: 1,343,082 | positives: 9,029
Source 2: 5,000,000 rows | candidates: 1,677,960 | positives: 11,328
Source 2 COMPLETE | candidates: 1,689,492 | positives: 11,407

Scanning Source 3...
Source 3: 1,000,000 rows | candidates: 316,780 | positives: 2,214
Source 3: 2,000,000 rows | candidates: 634,676 | positives: 4,502
Source 3: 3,000,000 rows | candidates: 951,636 | positives: 6,728
Source 3: 4,000,000 rows | candidates: 1,268,667 | positives: 8,906
Source 3: 5,000,000 rows | candidates: 1,585,810 | positives: 11,168
Source 3 COMPLETE | candidates: 1,676,837 | positives: 11,812

================================
ML TRAINING CANDIDATES
================================
Total candidate pairs seen: 3366329
Unique positive pairs: 23219
Negative reservoir: 200000
Negatives selected: 185752
Total ML pairs: 208971
Positive rate: 11.11 %

In [ ]:
# ============================================
# STEP 13 — RETRIEVE ONLY ML PAIR RECORDS
# ============================================

# Combine the pairs
ml_pairs = (
    [(sid, eid, 1) for sid, eid in positive_pairs] +
    [(sid, eid, 0) for sid, eid in negative_pairs]
)

print("ML pairs:", len(ml_pairs))

# --------------------------------------------
# Needed Source-2/3 entity IDs
# --------------------------------------------

needed_eids = {
    eid
    for _, eid, _ in ml_pairs
}

print(
    "Unique Source-2/3 records needed:",
    len(needed_eids)
)

# --------------------------------------------
# Lookup for S1 training records
# --------------------------------------------

s1_train_lookup = (
    s1_train
    .set_index("entity_id")
    .to_dict("index")
)

# --------------------------------------------
# Retrieve only required S2/S3 records
# --------------------------------------------

ml_record_lookup = {}

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"\nScanning {source_name}...")

    rows = 0
    found_before = len(ml_record_lookup)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        found = chunk[
            chunk["entity_id"].isin(
                needed_eids
            )
        ]

        for row in found.itertuples(index=False):

            ml_record_lookup[
                row.entity_id
            ] = {
                "entity_id": row.entity_id,
                "business_name": row.business_name,
                "business_address": row.business_address,
                "country": row.country
            }

        rows += len(chunk)

        if rows % 1_000_000 == 0:
            print(
                f"  processed {rows:,} | "
                f"records found: "
                f"{len(ml_record_lookup):,}"
            )

    print(
        f"{source_name} complete | "
        f"records found so far: "
        f"{len(ml_record_lookup):,}"
    )

print("\n================================")
print("ML RECORD RETRIEVAL")
print("================================")

print(
    "Required records:",
    len(needed_eids)
)

print(
    "Retrieved records:",
    len(ml_record_lookup)
)

print(
    "Missing records:",
    len(needed_eids - set(ml_record_lookup))
)

assert (
    len(needed_eids) ==
    len(ml_record_lookup)
)

print("\nAll ML pair records retrieved successfully.")

ML pairs: 208971
Unique Source-2/3 records needed: 204703

Scanning Source 2...
  processed 1,000,000 | records found: 20,266
  processed 2,000,000 | records found: 40,467
  processed 3,000,000 | records found: 60,837
  processed 4,000,000 | records found: 81,184
  processed 5,000,000 | records found: 101,571
Source 2 complete | records found so far: 102,243

Scanning Source 3...
  processed 1,000,000 | records found: 121,618
  processed 2,000,000 | records found: 140,904
  processed 3,000,000 | records found: 160,320
  processed 4,000,000 | records found: 179,674
  processed 5,000,000 | records found: 199,074
Source 3 complete | records found so far: 204,703

================================
ML RECORD RETRIEVAL
================================
Required records: 204703
Retrieved records: 204703
Missing records: 0

All ML pair records retrieved successfully.

In [ ]:
# ============================================
# STEP 14 — BUILD ML FEATURE MATRIX
# ============================================

print("Building feature matrix...")

feature_rows = []

for i, (sid, eid, label) in enumerate(ml_pairs):

    s1_row = s1_train_lookup[sid]
    s2_row = ml_record_lookup[eid]

    features = pair_features(
        s1_row,
        s2_row
    )

    features["source1_entity_id"] = sid
    features["matched_entity_id"] = eid
    features["label"] = label

    feature_rows.append(features)

    if (i + 1) % 25000 == 0:
        print(
            f"Processed {i + 1:,} / "
            f"{len(ml_pairs):,}"
        )

ml_features = pd.DataFrame(feature_rows)

print("\n================================")
print("ML FEATURE MATRIX")
print("================================")

print(
    "Shape:",
    ml_features.shape
)

print(
    "Positive labels:",
    int(ml_features["label"].sum())
)

print(
    "Negative labels:",
    int(
        (ml_features["label"] == 0).sum()
    )
)

print(
    "Missing feature values:",
    int(
        ml_features.isna().sum().sum()
    )
)

print("\nFeature columns:")

for col in ml_features.columns:
    print(" -", col)

Building feature matrix...
Processed 25,000 / 208,971
Processed 50,000 / 208,971
Processed 75,000 / 208,971
Processed 100,000 / 208,971
Processed 125,000 / 208,971
Processed 150,000 / 208,971
Processed 175,000 / 208,971
Processed 200,000 / 208,971

================================
ML FEATURE MATRIX
================================
Shape: (208971, 19)
Positive labels: 23219
Negative labels: 185752
Missing feature values: 0

Feature columns:
 - name_exact
 - address_exact
 - country_exact
 - name_similarity
 - address_similarity
 - name_token_overlap
 - address_token_overlap
 - name_jaccard
 - address_jaccard
 - shared_name_token_count
 - shared_address_token_count
 - shared_address_number_count
 - name_length_diff
 - address_length_diff
 - name_length_ratio
 - address_length_ratio
 - source1_entity_id
 - matched_entity_id
 - label

In [ ]:
# ============================================
# STEP 15 — SAVE + ENTITY-LEVEL ML SPLIT
# ============================================

import os

ML_DIR = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml"

os.makedirs(ML_DIR, exist_ok=True)

# --------------------------------------------
# Save feature matrix immediately
# --------------------------------------------

feature_path = (
    f"{ML_DIR}/ml_features_v3_1000.pkl"
)

ml_features.to_pickle(feature_path)

print("Feature matrix saved:")
print(feature_path)

# --------------------------------------------
# Entity-level split
# --------------------------------------------

all_training_s1_ids = list(
    s1_train["entity_id"]
)

# Fixed deterministic split
model_train_ids = set(
    all_training_s1_ids[:6000]
)

model_val_ids = set(
    all_training_s1_ids[6000:]
)

print("\n================================")
print("ENTITY-LEVEL SPLIT")
print("================================")

print(
    "Model-train S1:",
    len(model_train_ids)
)

print(
    "Model-validation S1:",
    len(model_val_ids)
)

# --------------------------------------------
# Split feature rows
# --------------------------------------------

train_mask = ml_features[
    "source1_entity_id"
].isin(model_train_ids)

val_mask = ml_features[
    "source1_entity_id"
].isin(model_val_ids)

ml_train = ml_features[
    train_mask
].copy()

ml_val = ml_features[
    val_mask
].copy()

print("\nFeature rows:")

print(
    "Training rows:",
    len(ml_train)
)

print(
    "Validation rows:",
    len(ml_val)
)

print(
    "Training positives:",
    int(ml_train["label"].sum())
)

print(
    "Validation positives:",
    int(ml_val["label"].sum())
)

# --------------------------------------------
# Verify NO entity leakage
# --------------------------------------------

train_entities = set(
    ml_train["source1_entity_id"]
)

val_entities = set(
    ml_val["source1_entity_id"]
)

overlap = train_entities & val_entities

print("\nEntity overlap:", len(overlap))

assert len(overlap) == 0
assert len(model_train_ids) == 6000
assert len(model_val_ids) == 2000

print("\n================================")
print("SPLIT VERIFIED")
print("================================")
print("No Source-1 entity leakage.")

Feature matrix saved:
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/ml_features_v3_1000.pkl

================================
ENTITY-LEVEL SPLIT
================================
Model-train S1: 6000
Model-validation S1: 2000

Feature rows:
Training rows: 156406
Validation rows: 52565
Training positives: 17404
Validation positives: 5815

Entity overlap: 0

================================
SPLIT VERIFIED
================================
No Source-1 entity leakage.

In [ ]:
!pip install -q catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 4.9 MB/s eta 0:00:00

In [ ]:
import catboost
print("CatBoost version:", catboost.__version__)

CatBoost version: 1.2.10

In [ ]:
# ============================================
# STEP 16 — CATBOOST V1
# ============================================

from catboost import CatBoostClassifier
from sklearn.metrics import (
    precision_score,
    recall_score,
    fbeta_score
)
import os

DROP_COLUMNS = [
    "source1_entity_id",
    "matched_entity_id",
    "label"
]

FEATURE_COLUMNS = [
    col for col in ml_train.columns
    if col not in DROP_COLUMNS
]

X_train = ml_train[FEATURE_COLUMNS]
y_train = ml_train["label"]

X_val = ml_val[FEATURE_COLUMNS]
y_val = ml_val["label"]

print("Features:", len(FEATURE_COLUMNS))
print("Training:", X_train.shape)
print("Validation:", X_val.shape)

# --------------------------------------------
# Train CatBoost
# --------------------------------------------

model_v1 = CatBoostClassifier(
    iterations=500,
    depth=7,
    learning_rate=0.06,
    loss_function="Logloss",
    eval_metric="Logloss",
    random_seed=42,
    verbose=100,
    allow_writing_files=False
)

model_v1.fit(
    X_train,
    y_train,
    eval_set=(X_val, y_val),
    use_best_model=True
)

print("\n================================")
print("MODEL TRAINING COMPLETE")
print("================================")

print(
    "Best iteration:",
    model_v1.get_best_iteration()
)

# --------------------------------------------
# Save model immediately
# --------------------------------------------

MODEL_DIR = (
    "/content/drive/My Drive/"
    "Amazon-ML-Challenge-2026/ml"
)

os.makedirs(MODEL_DIR, exist_ok=True)

MODEL_PATH = (
    f"{MODEL_DIR}/catboost_v1_v3_1000.cbm"
)

model_v1.save_model(MODEL_PATH)

print("Model saved:")
print(MODEL_PATH)

# --------------------------------------------
# Validation probabilities
# --------------------------------------------

val_prob = model_v1.predict_proba(
    X_val
)[:, 1]

print(
    "\nProbability range:",
    float(val_prob.min()),
    "to",
    float(val_prob.max())
)

# --------------------------------------------
# Pair-level threshold sweep
# --------------------------------------------

thresholds = [
    0.30, 0.35, 0.40, 0.45,
    0.50, 0.55, 0.60, 0.65,
    0.70, 0.75, 0.80, 0.85,
    0.90, 0.95
]

pair_results = []

for threshold in thresholds:

    pred = (
        val_prob >= threshold
    ).astype(int)

    precision = precision_score(
        y_val,
        pred,
        zero_division=0
    )

    recall = recall_score(
        y_val,
        pred,
        zero_division=0
    )

    f05 = fbeta_score(
        y_val,
        pred,
        beta=0.5,
        zero_division=0
    )

    pair_results.append({
        "threshold": threshold,
        "precision": precision,
        "recall": recall,
        "f0.5": f05,
        "predicted_pairs": int(pred.sum())
    })

pair_results_df = pd.DataFrame(
    pair_results
)

print("\n================================")
print("PAIR-LEVEL THRESHOLD SWEEP")
print("================================")

print(
    pair_results_df.to_string(index=False)
)

# --------------------------------------------
# Entity-level F0.5
# --------------------------------------------

def entity_f05(
    feature_df,
    probabilities,
    threshold,
    true_lookup
):

    temp = feature_df[
        [
            "source1_entity_id",
            "matched_entity_id"
        ]
    ].copy()

    temp["probability"] = probabilities

    predicted = temp[
        temp["probability"] >= threshold
    ]

    scores = []

    for sid in model_val_ids:

        true_ids = true_lookup.get(
            sid,
            set()
        )

        predicted_ids = set(
            predicted.loc[
                predicted["source1_entity_id"] == sid,
                "matched_entity_id"
            ]
        )

        tp = len(
            true_ids & predicted_ids
        )

        fp = len(
            predicted_ids - true_ids
        )

        fn = len(
            true_ids - predicted_ids
        )

        if tp == 0:

            score = (
                1.0
                if fp == 0 and fn == 0
                else 0.0
            )

        else:

            precision = tp / (tp + fp)
            recall = tp / (tp + fn)

            beta2 = 0.25

            score = (
                (1 + beta2)
                * precision
                * recall
                / (
                    beta2 * precision
                    + recall
                )
            )

        scores.append(score)

    return float(np.mean(scores))


entity_results = []

for threshold in thresholds:

    score = entity_f05(
        ml_val,
        val_prob,
        threshold,
        gt_lookup
    )

    predicted_entities = (
        ml_val.loc[
            val_prob >= threshold,
            "source1_entity_id"
        ].nunique()
    )

    entity_results.append({
        "threshold": threshold,
        "entity_f0.5": score,
        "S1_with_predicted_match":
            predicted_entities
    })

entity_results_df = pd.DataFrame(
    entity_results
)

print("\n================================")
print("ENTITY-LEVEL F0.5")
print("================================")

print(
    entity_results_df.to_string(
        index=False
    )
)

best_row = entity_results_df.loc[
    entity_results_df["entity_f0.5"].idxmax()
]

print("\n================================")
print("BEST LOCAL THRESHOLD")
print("================================")

print(
    "Threshold:",
    float(best_row["threshold"])
)

print(
    "Entity F0.5:",
    float(best_row["entity_f0.5"])
)

print(
    "S1 with predicted match:",
    int(
        best_row[
            "S1_with_predicted_match"
        ]
    )
)

Features: 16
Training: (156406, 16)
Validation: (52565, 16)
0:	learn: 0.4991510	test: 0.4997908	best: 0.4997908 (0)	total: 218ms	remaining: 1m 48s
100:	learn: 0.0141699	test: 0.0171890	best: 0.0171890 (100)	total: 7.88s	remaining: 31.1s
200:	learn: 0.0114855	test: 0.0161785	best: 0.0161748 (196)	total: 15.2s	remaining: 22.7s
300:	learn: 0.0101790	test: 0.0159090	best: 0.0158959 (298)	total: 19.1s	remaining: 12.6s
400:	learn: 0.0090819	test: 0.0156997	best: 0.0156943 (391)	total: 23s	remaining: 5.67s
499:	learn: 0.0082852	test: 0.0157114	best: 0.0156943 (391)	total: 29s	remaining: 0us

bestTest = 0.01569429895
bestIteration = 391

Shrink model to first 392 iterations.

================================
MODEL TRAINING COMPLETE
================================
Best iteration: 391
Model saved:
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/catboost_v1_v3_1000.cbm

Probability range: 1.1212837226291585e-07 to 0.9999967452135984

================================
PAIR-LEVEL THRESHOLD SWEEP
================================
 threshold  precision   recall     f0.5  predicted_pairs
      0.30   0.964190 0.986242 0.968521             5948
      0.35   0.966262 0.985039 0.969960             5928
      0.40   0.967671 0.983147 0.970727             5908
      0.45   0.971064 0.981083 0.973051             5875
      0.50   0.972654 0.978676 0.973853             5851
      0.55   0.975090 0.976096 0.975291             5821
      0.60   0.978047 0.973001 0.977033             5785
      0.65   0.978997 0.969905 0.977165             5761
      0.70   0.980622 0.965950 0.977652             5728
      0.75   0.982253 0.961307 0.977991             5691
      0.80   0.985585 0.952365 0.978756             5619
      0.85   0.988425 0.939811 0.978304             5529
      0.90   0.991269 0.917627 0.975610             5383
      0.95   0.993585 0.878934 0.968323             5144

================================
ENTITY-LEVEL F0.5
================================
 threshold  entity_f0.5  S1_with_predicted_match
      0.30     0.884659                     1808
      0.35     0.885405                     1808
      0.40     0.886103                     1807
      0.45     0.887124                     1805
      0.50     0.887203                     1805
      0.55     0.887845                     1802
      0.60     0.888983                     1802
      0.65     0.888258                     1801
      0.70     0.887310                     1799
      0.75     0.886076                     1797
      0.80     0.886304                     1789
      0.85     0.884429                     1788
      0.90     0.876540                     1777
      0.95     0.859665                     1757

================================
BEST LOCAL THRESHOLD
================================
Threshold: 0.6
Entity F0.5: 0.8889834928925503
S1 with predicted match: 1802

In [ ]:
# ============================================
# STEP 17 — FINE THRESHOLD SEARCH
# ============================================

fine_thresholds = [
    0.54, 0.56, 0.58,
    0.60, 0.62, 0.64,
    0.66, 0.68, 0.70
]

fine_results = []

for threshold in fine_thresholds:

    score = entity_f05(
        ml_val,
        val_prob,
        threshold,
        gt_lookup
    )

    pred_mask = val_prob >= threshold

    predicted_pairs = int(
        pred_mask.sum()
    )

    predicted_entities = (
        ml_val.loc[
            pred_mask,
            "source1_entity_id"
        ].nunique()
    )

    fine_results.append({
        "threshold": threshold,
        "entity_f0.5": score,
        "predicted_pairs": predicted_pairs,
        "S1_with_match": predicted_entities
    })

fine_results_df = pd.DataFrame(
    fine_results
)

print("\n================================")
print("FINE THRESHOLD SEARCH")
print("================================")

print(
    fine_results_df.to_string(
        index=False
    )
)

best_fine = fine_results_df.loc[
    fine_results_df["entity_f0.5"].idxmax()
]

print("\n================================")
print("FINE BEST THRESHOLD")
print("================================")

print(
    "Threshold:",
    float(best_fine["threshold"])
)

print(
    "Entity F0.5:",
    float(best_fine["entity_f0.5"])
)

print(
    "Predicted pairs:",
    int(best_fine["predicted_pairs"])
)

print(
    "S1 with match:",
    int(best_fine["S1_with_match"])
)

================================
FINE THRESHOLD SEARCH
================================
 threshold  entity_f0.5  predicted_pairs  S1_with_match
      0.54     0.887827             5828           1802
      0.56     0.888273             5814           1802
      0.58     0.888720             5800           1802
      0.60     0.888983             5785           1802
      0.62     0.888402             5777           1801
      0.64     0.888497             5764           1801
      0.66     0.888345             5758           1801
      0.68     0.887667             5739           1800
      0.70     0.887310             5728           1799

================================
FINE BEST THRESHOLD
================================
Threshold: 0.6
Entity F0.5: 0.8889834928925503
Predicted pairs: 5785
S1 with match: 1802

In [ ]:
# ============================================
# STEP 18 — SCORE V3 <=2500 WITH CATBOOST
# ============================================

# We keep the already-trained model_v1.
# We do NOT retrain anything here.

V3_LIMIT = 2500
SCORE_THRESHOLD = 0.60
BATCH_SIZE = 10000

print("Preparing V3 <=2500 scoring index...")

# --------------------------------------------
# Build country + address-token index
# for <=2500
# --------------------------------------------

address_token_to_s1_2500 = defaultdict(set)

for sid in val_ids:

    country = val_country[sid]

    for token in val_address_tokens[sid]:

        if address_freq_val.get(
            token,
            10**9
        ) <= V3_LIMIT:

            address_token_to_s1_2500[
                (country, token)
            ].add(sid)

print(
    "V3 <=2500 address keys:",
    len(address_token_to_s1_2500)
)

# --------------------------------------------
# Predicted matches accumulated per S1
# --------------------------------------------

predicted_by_s1_2500 = {
    sid: set()
    for sid in val_ids
}

total_candidates_scored = 0
total_positive_predictions = 0

feature_batch = []
pair_batch = []

def score_batch():

    global feature_batch
    global pair_batch
    global total_positive_predictions

    if not feature_batch:
        return

    batch_df = pd.DataFrame(
        feature_batch
    )

    probs = model_v1.predict_proba(
        batch_df[FEATURE_COLUMNS]
    )[:, 1]

    keep = probs >= SCORE_THRESHOLD

    for i in np.where(keep)[0]:

        sid, eid = pair_batch[i]

        predicted_by_s1_2500[
            sid
        ].add(eid)

    total_positive_predictions += int(
        keep.sum()
    )

    feature_batch.clear()
    pair_batch.clear()


def process_v3_2500_source(
    path,
    source_name
):

    global total_candidates_scored

    print(
        f"\nScanning {source_name}..."
    )

    rows = 0
    source_candidates = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(
            index=False
        ):

            eid = row.entity_id

            country = normalize_country(
                row.country
            )

            name = normalize_advanced(
                row.business_name
            )

            address = normalize_advanced(
                row.business_address
            )

            source_address_tokens = (
                get_token_set(address)
            )

            found_s1 = set()

            # =================================
            # V2: exact name + country
            # =================================

            if name:

                found_s1.update(
                    s1_val_name_map.get(
                        (country, name),
                        []
                    )
                )

            # =================================
            # V2: exact address + country
            # =================================

            if address:

                found_s1.update(
                    s1_val_address_map.get(
                        (country, address),
                        []
                    )
                )

            # =================================
            # V2: rare name <=250
            # =================================

            for token in get_token_set(name):

                if name_freq_val.get(
                    token,
                    10**9
                ) <= 250:

                    found_s1.update(
                        rare_name_to_s1.get(
                            (country, token),
                            set()
                        )
                    )

            # =================================
            # V3: address <=2500
            #
            # Require:
            #   >=2 shared address tokens
            #   AND
            #   >=1 shared token <=2500
            # =================================

            possible_s1 = set()

            for token in source_address_tokens:

                if address_freq_val.get(
                    token,
                    10**9
                ) <= V3_LIMIT:

                    possible_s1.update(
                        address_token_to_s1_2500.get(
                            (country, token),
                            set()
                        )
                    )

            for sid in possible_s1:

                shared_tokens = (
                    source_address_tokens
                    &
                    val_address_tokens[sid]
                )

                if len(shared_tokens) >= 2:

                    rare_shared = any(
                        address_freq_val.get(
                            token,
                            10**9
                        ) <= V3_LIMIT
                        for token in shared_tokens
                    )

                    if rare_shared:

                        found_s1.add(sid)

            # =================================
            # Build features for each candidate
            # =================================

            for sid in found_s1:

                # Retrieve S1 row
                s1_row = s1_val_lookup[sid]

                s2_row = {
                    "entity_id": eid,
                    "business_name":
                        row.business_name,
                    "business_address":
                        row.business_address,
                    "country":
                        row.country
                }

                features = pair_features(
                    s1_row,
                    s2_row
                )

                feature_batch.append(
                    features
                )

                pair_batch.append(
                    (sid, eid)
                )

                total_candidates_scored += 1
                source_candidates += 1

                if len(feature_batch) >= BATCH_SIZE:
                    score_batch()

            rows += 1

        # Finish any remaining batch
        score_batch()

        if rows % 1_000_000 == 0:

            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"candidates: "
                f"{source_candidates:,} | "
                f"predicted: "
                f"{total_positive_predictions:,}"
            )

    print(
        f"{source_name} COMPLETE | "
        f"candidates: "
        f"{source_candidates:,} | "
        f"predicted: "
        f"{total_positive_predictions:,}"
    )


# --------------------------------------------
# Need validation S1 lookup
# --------------------------------------------

s1_val_lookup = (
    s1_val
    .set_index("entity_id")
    .to_dict("index")
)

# --------------------------------------------
# Score Source 2 + Source 3
# --------------------------------------------

process_v3_2500_source(
    TRAIN_S2,
    "Source 2"
)

process_v3_2500_source(
    TRAIN_S3,
    "Source 3"
)

# --------------------------------------------
# Calculate entity-level F0.5
# --------------------------------------------

entity_scores_2500 = []

for sid in val_ids:

    true_ids = gt_lookup.get(
        sid,
        set()
    )

    predicted_ids = predicted_by_s1_2500[
        sid
    ]

    tp = len(
        true_ids & predicted_ids
    )

    fp = len(
        predicted_ids - true_ids
    )

    fn = len(
        true_ids - predicted_ids
    )

    if tp == 0:

        score = (
            1.0
            if fp == 0 and fn == 0
            else 0.0
        )

    else:

        precision = tp / (
            tp + fp
        )

        recall = tp / (
            tp + fn
        )

        beta2 = 0.25

        score = (
            1.25
            * precision
            * recall
            / (
                beta2 * precision
                + recall
            )
        )

    entity_scores_2500.append(
        score
    )

final_f05_2500 = float(
    np.mean(entity_scores_2500)
)

entities_with_prediction = sum(
    bool(predicted_by_s1_2500[sid])
    for sid in val_ids
)

print("\n================================")
print("V3 <=2500 + CATBOOST")
print("================================")

print(
    "Candidates scored:",
    total_candidates_scored
)

print(
    "Expected V3 candidates:",
    1316993
)

print(
    "Predicted positive pairs:",
    total_positive_predictions
)

print(
    "S1 with predicted matches:",
    entities_with_prediction
)

print(
    "Entity F0.5:",
    final_f05_2500
)

print("\n================================")
print("COMPARISON")
print("================================")

print(
    "V3 <=1000:",
    "0.889883"
)

print(
    "V3 <=2500:",
    final_f05_2500
)

print(
    "Difference:",
    final_f05_2500 - 0.889883
)

Preparing V3 <=2500 scoring index...
V3 <=2500 address keys: 3690

Scanning Source 2...
Source 2: 1,000,000 rows | candidates: 141,570 | predicted: 896
Source 2: 2,000,000 rows | candidates: 283,150 | predicted: 1,745
Source 2: 3,000,000 rows | candidates: 425,038 | predicted: 2,636
Source 2: 4,000,000 rows | candidates: 566,360 | predicted: 3,554
Source 2: 5,000,000 rows | candidates: 708,005 | predicted: 4,436
Source 2 COMPLETE | candidates: 712,949 | predicted: 4,458

Scanning Source 3...
Source 3: 1,000,000 rows | candidates: 103,832 | predicted: 5,297
Source 3: 2,000,000 rows | candidates: 207,840 | predicted: 6,094
Source 3: 3,000,000 rows | candidates: 312,402 | predicted: 6,926
Source 3: 4,000,000 rows | candidates: 415,597 | predicted: 7,763
Source 3: 5,000,000 rows | candidates: 519,598 | predicted: 8,545
Source 3 COMPLETE | candidates: 549,086 | predicted: 8,788

================================
V3 <=2500 + CATBOOST
================================
Candidates scored: 1262035
Expected V3 candidates: 1316993
Predicted positive pairs: 8788
S1 with predicted matches: 1930
Entity F0.5: 0.7005237802648876

================================
COMPARISON
================================
V3 <=1000: 0.889883
V3 <=2500: 0.7005237802648876
Difference: -0.18935921973511238

In [ ]:
print(model_v1)
print(FEATURE_COLUMNS)

CatBoostClassifier(allow_writing_files=False, depth=7, eval_metric='Logloss', iterations=500, learning_rate=0.06, loss_function='Logloss', random_seed=42, verbose=100)
['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard', 'address_jaccard', 'shared_name_token_count', 'shared_address_token_count', 'shared_address_number_count', 'name_length_diff', 'address_length_diff', 'name_length_ratio', 'address_length_ratio']

In [ ]:
import pandas as pd
import re
from collections import defaultdict

TEST_S1 = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"

print("Loading 10,000 test S1 rows...")

sample_s1 = pd.read_csv(
    TEST_S1,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=10000
)

print("Rows:", len(sample_s1))

# ---------------------------------------------------------
# Build normalized fields ONCE
# ---------------------------------------------------------

print("Normalizing...")

sample_s1["norm_country"] = (
    sample_s1["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

sample_s1["norm_name"] = (
    sample_s1["business_name"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .str.replace(r"[^\w\s]", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
)

sample_s1["norm_address"] = (
    sample_s1["business_address"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .str.replace(r"[^\w\s]", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
)

# ---------------------------------------------------------
# Build indexes
# ---------------------------------------------------------

name_index = defaultdict(list)
address_index = defaultdict(list)
address_token_index = defaultdict(list)

address_freq = defaultdict(int)

for row in sample_s1.itertuples(index=False):

    sid = row.entity_id
    country = row.norm_country
    name = row.norm_name
    address = row.norm_address

    if name:
        name_index[(country, name)].append(sid)

    if address:
        address_index[(country, address)].append(sid)

    tokens = set(address.split())

    for token in tokens:
        if len(token) >= 2:
            address_freq[(country, token)] += 1

for row in sample_s1.itertuples(index=False):

    sid = row.entity_id
    country = row.norm_country
    tokens = set(row.norm_address.split())

    for token in tokens:
        if (
            len(token) >= 2
            and address_freq[(country, token)] <= 1000
        ):
            address_token_index[
                (country, token)
            ].append(sid)

print("Indexes ready.")

# ---------------------------------------------------------
# Estimate candidate volume from 1,000 Source 2 + 1,000 S3
# ---------------------------------------------------------

total_candidates = 0
rows_checked = 0

for path in [
    "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv",
    "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"
]:

    chunk = pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        nrows=1000
    )

    for row in chunk.itertuples(index=False):

        country = str(row.country).lower().strip()

        name = (
            str(row.business_name)
            .lower()
            .strip()
        )

        name = re.sub(
            r"[^\w\s]",
            " ",
            name
        )

        name = re.sub(
            r"\s+",
            " ",
            name
        ).strip()

        address = (
            str(row.business_address)
            .lower()
            .strip()
        )

        address = re.sub(
            r"[^\w\s]",
            " ",
            address
        )

        address = re.sub(
            r"\s+",
            " ",
            address
        ).strip()

        candidates = set()

        # Exact name
        candidates.update(
            name_index.get(
                (country, name),
                []
            )
        )

        # Exact address
        candidates.update(
            address_index.get(
                (country, address),
                []
            )
        )

        # Address token block
        counts = defaultdict(int)

        for token in set(address.split()):

            if (
                len(token) >= 2
                and address_freq.get(
                    (country, token),
                    999999
                ) <= 1000
            ):

                for sid in address_token_index.get(
                    (country, token),
                    []
                ):
                    counts[sid] += 1

        for sid, count in counts.items():

            if count >= 2:
                candidates.add(sid)

        total_candidates += len(candidates)
        rows_checked += 1

avg_candidates = (
    total_candidates / rows_checked
)

estimated_total = (
    avg_candidates * 4_887_273
    +
    avg_candidates * 5_082_316
)

print("\n==============================")
print("TEST CANDIDATE ESTIMATE")
print("==============================")
print(
    "Rows sampled:",
    rows_checked
)
print(
    "Candidates:",
    f"{total_candidates:,}"
)
print(
    "Average candidates/source row:",
    round(avg_candidates, 2)
)
print(
    "Rough estimated total:",
    f"{estimated_total:,.0f}"
)

Loading 10,000 test S1 rows...
Rows: 10000
Normalizing...
Indexes ready.

==============================
TEST CANDIDATE ESTIMATE
==============================
Rows sampled: 2000
Candidates: 236,443
Average candidates/source row: 118.22
Rough estimated total: 1,178,619,766

In [ ]:
# ============================================================
# FAST V1.1 INDEX BUILD — FIXED
# ============================================================

print("Building V1.1 indexes...")

# Count each normalized name within country
name_counts = (
    test_s1.groupby(
        ["norm_country", "norm_name"]
    ).size()
)

# Convert counts to a normal dictionary
name_count_dict = name_counts.to_dict()

# ---------------------------------------------------------
# UNIQUE NAME INDEX
# ---------------------------------------------------------

name_index = {}

for row in test_s1.itertuples(index=False):

    key = (
        row.norm_country,
        row.norm_name
    )

    if (
        row.norm_name
        and name_count_dict.get(key, 0) == 1
    ):
        name_index[key] = row.entity_id

# ---------------------------------------------------------
# ADDRESS INDEX
# ---------------------------------------------------------

address_index = defaultdict(list)

for row in test_s1.itertuples(index=False):

    if row.norm_address:

        address_index[
            (
                row.norm_country,
                row.norm_address
            )
        ].append(
            row.entity_id
        )

print("================================")
print("V1.1 INDEX READY")
print("================================")
print(
    "Unique name keys:",
    f"{len(name_index):,}"
)
print(
    "Address keys:",
    f"{len(address_index):,}"
)

Building V1.1 indexes...
================================
V1.1 INDEX READY
================================
Unique name keys: 1,098,328
Address keys: 1,673,690

In [ ]:
# ============================================================
# SUBMISSION 3 — FAST V1.1
# ============================================================

import csv
from pathlib import Path

TEST_S2 = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"
TEST_S3 = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

OUTPUT_DIR = Path(
    "/content/amazon_ml_challenge/student_resource/output"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

MATCH_FILE = OUTPUT_DIR / "matching_results_submission3.tsv"
CAND_FILE = OUTPUT_DIR / "candidate_pairs_submission3.tsv"

# ------------------------------------------------------------
# Create empty result structures
# ------------------------------------------------------------

predictions = {}

for sid in test_s1["entity_id"]:
    predictions[sid] = []

candidate_count = 0

# ------------------------------------------------------------
# Stream Source 2 + Source 3
# ------------------------------------------------------------

for source_name, path in [
    ("S2", TEST_S2),
    ("S3", TEST_S3)
]:

    print("\nProcessing", source_name)

    processed = 0
    matched_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=100_000
    ):

        for row in chunk.itertuples(index=False):

            country = normalize_country(row.country)
            name = normalize_advanced(row.business_name)
            address = normalize_advanced(row.business_address)

            candidates = set()

            # ------------------------------------------------
            # Exact address + country
            # ------------------------------------------------

            if address:

                candidates.update(
                    address_index.get(
                        (country, address),
                        []
                    )
                )

            # ------------------------------------------------
            # Exact UNIQUE name + country
            # ------------------------------------------------

            if name:

                sid = name_index.get(
                    (country, name)
                )

                if sid:
                    candidates.add(sid)

            # ------------------------------------------------
            # Save candidates + predictions
            # ------------------------------------------------

            if candidates:

                candidate_count += len(candidates)

                matched_rows += 1

                for sid in candidates:

                    predictions[sid].append(
                        row.entity_id
                    )

            processed += 1

        print(
            source_name,
            "| processed:",
            f"{processed:,}",
            "| candidate pairs:",
            f"{candidate_count:,}"
        )

print("\n================================")
print("V1.1 GENERATION COMPLETE")
print("================================")
print(
    "Total candidate pairs:",
    f"{candidate_count:,}"
)

Processing S2
S2 | processed: 100,000 | candidate pairs: 20,316
S2 | processed: 200,000 | candidate pairs: 40,054
S2 | processed: 300,000 | candidate pairs: 60,010
S2 | processed: 400,000 | candidate pairs: 79,931
S2 | processed: 500,000 | candidate pairs: 100,044
S2 | processed: 600,000 | candidate pairs: 119,892
S2 | processed: 700,000 | candidate pairs: 139,923
S2 | processed: 800,000 | candidate pairs: 160,016
S2 | processed: 900,000 | candidate pairs: 179,651
S2 | processed: 1,000,000 | candidate pairs: 199,553
S2 | processed: 1,100,000 | candidate pairs: 219,630
S2 | processed: 1,200,000 | candidate pairs: 239,536
S2 | processed: 1,300,000 | candidate pairs: 259,679
S2 | processed: 1,400,000 | candidate pairs: 279,853
S2 | processed: 1,500,000 | candidate pairs: 299,550
S2 | processed: 1,600,000 | candidate pairs: 319,534
S2 | processed: 1,700,000 | candidate pairs: 339,574
S2 | processed: 1,800,000 | candidate pairs: 359,503
S2 | processed: 1,900,000 | candidate pairs: 379,381
S2 | processed: 2,000,000 | candidate pairs: 398,970
S2 | processed: 2,100,000 | candidate pairs: 419,056
S2 | processed: 2,200,000 | candidate pairs: 438,789
S2 | processed: 2,300,000 | candidate pairs: 458,725
S2 | processed: 2,400,000 | candidate pairs: 478,780
S2 | processed: 2,500,000 | candidate pairs: 498,747
S2 | processed: 2,600,000 | candidate pairs: 518,596
S2 | processed: 2,700,000 | candidate pairs: 538,365
S2 | processed: 2,800,000 | candidate pairs: 558,379
S2 | processed: 2,900,000 | candidate pairs: 578,461
S2 | processed: 3,000,000 | candidate pairs: 598,222
S2 | processed: 3,100,000 | candidate pairs: 617,952
S2 | processed: 3,200,000 | candidate pairs: 638,086
S2 | processed: 3,300,000 | candidate pairs: 657,812
S2 | processed: 3,400,000 | candidate pairs: 677,714
S2 | processed: 3,500,000 | candidate pairs: 697,871
S2 | processed: 3,600,000 | candidate pairs: 717,742
S2 | processed: 3,700,000 | candidate pairs: 737,844
S2 | processed: 3,800,000 | candidate pairs: 757,905
S2 | processed: 3,900,000 | candidate pairs: 777,702
S2 | processed: 4,000,000 | candidate pairs: 797,773
S2 | processed: 4,100,000 | candidate pairs: 817,430
S2 | processed: 4,200,000 | candidate pairs: 837,178
S2 | processed: 4,300,000 | candidate pairs: 857,126
S2 | processed: 4,400,000 | candidate pairs: 876,876
S2 | processed: 4,500,000 | candidate pairs: 896,828
S2 | processed: 4,600,000 | candidate pairs: 916,817
S2 | processed: 4,700,000 | candidate pairs: 936,522
S2 | processed: 4,800,000 | candidate pairs: 956,472
S2 | processed: 4,887,273 | candidate pairs: 973,830

Processing S3
S3 | processed: 100,000 | candidate pairs: 988,303
S3 | processed: 200,000 | candidate pairs: 1,003,055
S3 | processed: 300,000 | candidate pairs: 1,018,246
S3 | processed: 400,000 | candidate pairs: 1,033,426
S3 | processed: 500,000 | candidate pairs: 1,047,707
S3 | processed: 600,000 | candidate pairs: 1,062,353
S3 | processed: 700,000 | candidate pairs: 1,077,103
S3 | processed: 800,000 | candidate pairs: 1,091,961
S3 | processed: 900,000 | candidate pairs: 1,106,796
S3 | processed: 1,000,000 | candidate pairs: 1,122,086
S3 | processed: 1,100,000 | candidate pairs: 1,136,938
S3 | processed: 1,200,000 | candidate pairs: 1,151,624
S3 | processed: 1,300,000 | candidate pairs: 1,165,956
S3 | processed: 1,400,000 | candidate pairs: 1,180,506
S3 | processed: 1,500,000 | candidate pairs: 1,195,543
S3 | processed: 1,600,000 | candidate pairs: 1,210,236
S3 | processed: 1,700,000 | candidate pairs: 1,225,130
S3 | processed: 1,800,000 | candidate pairs: 1,240,053
S3 | processed: 1,900,000 | candidate pairs: 1,255,114
S3 | processed: 2,000,000 | candidate pairs: 1,269,793
S3 | processed: 2,100,000 | candidate pairs: 1,284,423
S3 | processed: 2,200,000 | candidate pairs: 1,299,387
S3 | processed: 2,300,000 | candidate pairs: 1,314,426
S3 | processed: 2,400,000 | candidate pairs: 1,329,115
S3 | processed: 2,500,000 | candidate pairs: 1,344,291
S3 | processed: 2,600,000 | candidate pairs: 1,358,918
S3 | processed: 2,700,000 | candidate pairs: 1,373,288
S3 | processed: 2,800,000 | candidate pairs: 1,388,028
S3 | processed: 2,900,000 | candidate pairs: 1,402,802
S3 | processed: 3,000,000 | candidate pairs: 1,417,768
S3 | processed: 3,100,000 | candidate pairs: 1,432,770
S3 | processed: 3,200,000 | candidate pairs: 1,447,420
S3 | processed: 3,300,000 | candidate pairs: 1,462,133
S3 | processed: 3,400,000 | candidate pairs: 1,476,667
S3 | processed: 3,500,000 | candidate pairs: 1,491,469
S3 | processed: 3,600,000 | candidate pairs: 1,506,272
S3 | processed: 3,700,000 | candidate pairs: 1,520,756
S3 | processed: 3,800,000 | candidate pairs: 1,535,410
S3 | processed: 3,900,000 | candidate pairs: 1,550,320
S3 | processed: 4,000,000 | candidate pairs: 1,565,672
S3 | processed: 4,100,000 | candidate pairs: 1,580,058
S3 | processed: 4,200,000 | candidate pairs: 1,595,081
S3 | processed: 4,300,000 | candidate pairs: 1,609,441
S3 | processed: 4,400,000 | candidate pairs: 1,623,945
S3 | processed: 4,500,000 | candidate pairs: 1,638,450
S3 | processed: 4,600,000 | candidate pairs: 1,653,132
S3 | processed: 4,700,000 | candidate pairs: 1,667,736
S3 | processed: 4,800,000 | candidate pairs: 1,682,516
S3 | processed: 4,900,000 | candidate pairs: 1,697,263
S3 | processed: 5,000,000 | candidate pairs: 1,711,951
S3 | processed: 5,082,316 | candidate pairs: 1,724,019

================================
V1.1 GENERATION COMPLETE
================================
Total candidate pairs: 1,724,019

In [ ]:
# ============================================================
# SUBMISSION 3 — CATBOOST SCORING
# V1.1 candidates + CatBoost threshold 0.60
# ============================================================

from collections import defaultdict

THRESHOLD = 0.60

print("Preparing candidate lookup...")

# Reverse candidate map:
# source2/source3 entity_id -> list of S1 IDs
candidate_to_s1 = defaultdict(list)

for sid, candidate_ids in predictions.items():
    for cid in candidate_ids:
        candidate_to_s1[cid].append(sid)

print(
    "Unique candidate source IDs:",
    f"{len(candidate_to_s1):,}"
)

# S1 lookup
s1_lookup = test_s1.set_index(
    "entity_id"
).to_dict("index")

# Final predictions
final_predictions = defaultdict(list)

scored = 0
positive = 0

# ------------------------------------------------------------
# Stream Source 2 and Source 3
# ------------------------------------------------------------

for source_name, path in [
    ("S2", TEST_S2),
    ("S3", TEST_S3)
]:

    print("\nScoring", source_name)

    processed = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=50_000
    ):

        feature_rows = []
        pair_ids = []

        for row in chunk.itertuples(index=False):

            cid = row.entity_id

            s1_ids = candidate_to_s1.get(cid)

            if not s1_ids:
                processed += 1
                continue

            # Convert namedtuple to dictionary
            source_row = row._asdict()

            for sid in s1_ids:

                s1_row = s1_lookup[sid]

                feature_rows.append(
                    pair_features(
                        s1_row,
                        source_row
                    )
                )

                pair_ids.append(
                    (sid, cid)
                )

            processed += 1

        # ----------------------------------------------------
        # Score this chunk
        # ----------------------------------------------------

        if feature_rows:

            X = pd.DataFrame(
                feature_rows
            )[FEATURE_COLUMNS]

            probs = model_v1.predict_proba(
                X
            )[:, 1]

            for (sid, cid), prob in zip(
                pair_ids,
                probs
            ):

                if prob >= THRESHOLD:

                    final_predictions[sid].append(cid)
                    positive += 1

            scored += len(pair_ids)

        if processed % 500_000 < 50_000:
            print(
                source_name,
                "| processed:",
                f"{processed:,}",
                "| scored:",
                f"{scored:,}",
                "| predicted:",
                f"{positive:,}"
            )

    print(
        source_name,
        "COMPLETE | scored:",
        f"{scored:,}",
        "| predicted:",
        f"{positive:,}"
    )

print("\n========================================")
print("CATBOOST SCORING COMPLETE")
print("========================================")
print("Candidates scored:", f"{scored:,}")
print("Predicted positive pairs:", f"{positive:,}")
print(
    "S1 with predicted matches:",
    sum(
        1 for v in final_predictions.values()
        if v
    )
)

Preparing candidate lookup...
Unique candidate source IDs: 1,577,822

Scoring S2
S2 | processed: 500,000 | scored: 100,044 | predicted: 90,966
S2 | processed: 1,000,000 | scored: 199,553 | predicted: 181,295
S2 | processed: 1,500,000 | scored: 299,550 | predicted: 272,081
S2 | processed: 2,000,000 | scored: 398,970 | predicted: 362,317
S2 | processed: 2,500,000 | scored: 498,747 | predicted: 452,925
S2 | processed: 3,000,000 | scored: 598,222 | predicted: 543,396
S2 | processed: 3,500,000 | scored: 697,871 | predicted: 634,103
S2 | processed: 4,000,000 | scored: 797,773 | predicted: 724,760
S2 | processed: 4,500,000 | scored: 896,828 | predicted: 814,898
S2 COMPLETE | scored: 973,830 | predicted: 884,848

Scoring S3
S3 | processed: 500,000 | scored: 1,047,707 | predicted: 951,055
S3 | processed: 1,000,000 | scored: 1,122,086 | predicted: 1,017,794
S3 | processed: 1,500,000 | scored: 1,195,543 | predicted: 1,083,853
S3 | processed: 2,000,000 | scored: 1,269,793 | predicted: 1,150,418
S3 | processed: 2,500,000 | scored: 1,344,291 | predicted: 1,217,274
S3 | processed: 3,000,000 | scored: 1,417,768 | predicted: 1,283,345
S3 | processed: 3,500,000 | scored: 1,491,469 | predicted: 1,349,700
S3 | processed: 4,000,000 | scored: 1,565,672 | predicted: 1,416,381
S3 | processed: 4,500,000 | scored: 1,638,450 | predicted: 1,481,995
S3 | processed: 5,000,000 | scored: 1,711,951 | predicted: 1,548,172
S3 COMPLETE | scored: 1,724,019 | predicted: 1,559,057

========================================
CATBOOST SCORING COMPLETE
========================================
Candidates scored: 1,724,019
Predicted positive pairs: 1,559,057
S1 with predicted matches: 890828

In [ ]:
# ============================================================
# CREATE SUBMISSION 3
# ============================================================

from pathlib import Path
import csv

OUTPUT_DIR = Path(
    "/content/amazon_ml_challenge/student_resource/output"
)

MATCH_FILE = OUTPUT_DIR / "matching_results_submission3.tsv"

with open(
    MATCH_FILE,
    "w",
    encoding="utf-8",
    newline=""
) as f:

    writer = csv.writer(
        f,
        delimiter="\t",
        lineterminator="\n"
    )

    writer.writerow([
        "source1_entity_id",
        "matched_entity_ids"
    ])

    for sid in test_s1["entity_id"]:

        ids = list(
            dict.fromkeys(
                final_predictions.get(sid, [])
            )
        )

        writer.writerow([
            sid,
            ",".join(ids)
        ])

print("Created:")
print(MATCH_FILE)

Created:
/content/amazon_ml_challenge/student_resource/output/matching_results_submission3.tsv

In [ ]:
# ============================================================
# SANITY CHECK SUBMISSION 3
# ============================================================

check = pd.read_csv(
    MATCH_FILE,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("Rows:", len(check))
print("Expected:", len(test_s1))

print(
    "Unique S1:",
    check["source1_entity_id"].nunique()
)

print(
    "S1 with matches:",
    (check["matched_entity_ids"] != "").sum()
)

print(
    "S1 with no matches:",
    (check["matched_entity_ids"] == "").sum()
)

# Check duplicate S1
print(
    "Duplicate S1 rows:",
    check["source1_entity_id"].duplicated().sum()
)

# Number of predicted pairs
total_pairs = sum(
    0 if x == "" else len(x.split(","))
    for x in check["matched_entity_ids"]
)

print(
    "Total predicted pairs:",
    f"{total_pairs:,}"
)

Rows: 1732544
Expected: 1732544
Unique S1: 1732544
S1 with matches: 890828
S1 with no matches: 841716
Duplicate S1 rows: 0
Total predicted pairs: 1,559,057

In [ ]:
!python /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
"/content/amazon_ml_challenge/student_resource/output/matching_results_submission3.tsv"

usage: validate_submission.py [-h] [--matching MATCHING]
                              [--candidate CANDIDATE] [--test-dir TEST_DIR]
                              [--check-ids]
validate_submission.py: error: unrecognized arguments: /content/amazon_ml_challenge/student_resource/output/matching_results_submission3.tsv

In [ ]:
# How many matches are being predicted per S1?
match_counts = check["matched_entity_ids"].apply(
    lambda x: 0 if x == "" else len(x.split(","))
)

print("Average matches per S1:", match_counts.mean())
print("Median:", match_counts.median())
print("Max:", match_counts.max())

print("\nDistribution:")
print(
    match_counts.value_counts()
    .sort_index()
    .head(20)
)

Average matches per S1: 0.8998657465553545
Median: 1.0
Max: 79

Distribution:
matched_entity_ids
0     841716
1     480684
2     254130
3     103462
4      34721
5      10619
6       3360
7       1297
8        661
9        445
10       291
11       213
12       142
13       104
14       100
15        63
16        34
17        24
18        27
19        24
Name: count, dtype: int64

In [ ]:
!python /content/amazon_ml_challenge/student_resource/utils/validate_submission.py -h

usage: validate_submission.py [-h] [--matching MATCHING]
                              [--candidate CANDIDATE] [--test-dir TEST_DIR]
                              [--check-ids]

Validate ML Challenge 2026 submission output files before submitting.

options:
  -h, --help            show this help message and exit
  --matching, -m MATCHING
                        Path to matching_results.tsv (default:
                        output/matching_results.tsv)
  --candidate, -c CANDIDATE
                        Path to candidate_pairs.tsv (default:
                        output/candidate_pairs.tsv if it exists).
  --test-dir, -t TEST_DIR
                        Folder with test_source1/2/3.tsv (default:
                        dataset/test). test_source2/3.tsv are only read when
                        --check-ids is given.
  --check-ids           Also check that every matched/candidate ID exists in
                        the test Source-2/3 files. Off by default (loads all
                        S2/S3 IDs into memory — a few GB on the full test
                        set). A nonexistent ID only lowers your score, so this
                        is a diagnostic, not a submission gate.

In [ ]:
!python /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
--matching /content/amazon_ml_challenge/student_resource/output/matching_results_submission3.tsv

ML Challenge 2026 — submission validator
  test dir: dataset/test

FAIL — 1 issue(s) to fix before submitting:
  1. Test source1 file not found: dataset/test/test_source1.tsv (check --test-dir).

In [ ]:
!python /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
--matching /content/amazon_ml_challenge/student_resource/output/matching_results_submission3.tsv \
--test-dir /content/amazon_ml_challenge/student_resource/dataset/test

ML Challenge 2026 — submission validator
  test dir: /content/amazon_ml_challenge/student_resource/dataset/test
  required S1 entities: 1732544
  matching_results_submission3.tsv: 1732544 rows (841716 empty, 890828 non-empty).

WARNING: ID-existence check is OFF (the default) — not checking that matched/candidate IDs exist in the test set. Every other rule is still checked. Re-run with --check-ids to enable it (needs test_source2/3.tsv; uses more memory). A nonexistent ID only lowers your score, never rejects your submission.
WARNING: output/candidate_pairs.tsv not found — skipping candidate_pairs.tsv checks. It is optional here, but your final submission zip must include output/candidate_pairs.tsv.
PASS — no blocking issues found. Safe to submit.

In [ ]:
import shutil

src = "/content/amazon_ml_challenge/student_resource/output/matching_results_submission3.tsv"
dst = "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv"

shutil.copy2(src, dst)

print("Ready for upload:")
print(dst)

Ready for upload:
/content/amazon_ml_challenge/student_resource/output/matching_results.tsv

In [ ]:
from google.colab import files

files.download(
    "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv"
)

In [ ]:
# ============================================================
# V2 TEST-SCALE CANDIDATE ESTIMATE
# ============================================================

import pandas as pd
import re
from collections import defaultdict

TEST_S1 = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"
TEST_S2 = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"
TEST_S3 = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

print("Loading Test S1 sample...")

s1_sample = pd.read_csv(
    TEST_S1,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=10000
)

# ------------------------------------------------------------
# Normalize
# ------------------------------------------------------------

s1_sample["country_n"] = s1_sample["country"].map(normalize_country)
s1_sample["name_n"] = s1_sample["business_name"].map(normalize_advanced)
s1_sample["address_n"] = s1_sample["business_address"].map(normalize_advanced)

# ------------------------------------------------------------
# Token frequencies within sampled S1
# ------------------------------------------------------------

name_freq = defaultdict(int)
address_freq = defaultdict(int)

for row in s1_sample.itertuples(index=False):

    country = row.country_n

    for token in set(get_token_set(row.name_n)):
        if len(token) >= 2:
            name_freq[(country, token)] += 1

    for token in set(get_token_set(row.address_n)):
        if len(token) >= 2:
            address_freq[(country, token)] += 1

# ------------------------------------------------------------
# Build V2 indexes
# ------------------------------------------------------------

exact_name = defaultdict(list)
exact_address = defaultdict(list)

rare_name = defaultdict(list)
rare_address = defaultdict(list)

for row in s1_sample.itertuples(index=False):

    sid = row.entity_id
    country = row.country_n

    if row.name_n:
        exact_name[
            (country, row.name_n)
        ].append(sid)

    if row.address_n:
        exact_address[
            (country, row.address_n)
        ].append(sid)

    for token in set(get_token_set(row.name_n)):

        if (
            len(token) >= 2
            and name_freq.get(
                (country, token),
                999999
            ) <= 250
        ):
            rare_name[
                (country, token)
            ].append(sid)

    for token in set(get_token_set(row.address_n)):

        if (
            len(token) >= 2
            and address_freq.get(
                (country, token),
                999999
            ) <= 250
        ):
            rare_address[
                (country, token)
            ].append(sid)

print("V2 indexes ready.")

# ------------------------------------------------------------
# Sample Source 2 + Source 3
# ------------------------------------------------------------

TOTAL_CANDIDATES = 0
ROWS = 0

SAMPLES_PER_SOURCE = 5000

for source_name, path in [
    ("S2", TEST_S2),
    ("S3", TEST_S3)
]:

    print("\nSampling", source_name)

    chunk = pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        nrows=SAMPLES_PER_SOURCE
    )

    source_candidates = 0

    for row in chunk.itertuples(index=False):

        country = normalize_country(row.country)
        name = normalize_advanced(row.business_name)
        address = normalize_advanced(row.business_address)

        candidates = set()

        # ----------------------------------------------------
        # 1. Exact name + country
        # ----------------------------------------------------

        if name:
            candidates.update(
                exact_name.get(
                    (country, name),
                    []
                )
            )

        # ----------------------------------------------------
        # 2. Exact address + country
        # ----------------------------------------------------

        if address:
            candidates.update(
                exact_address.get(
                    (country, address),
                    []
                )
            )

        # ----------------------------------------------------
        # 3. Rare name token <=250
        # ----------------------------------------------------

        for token in set(
            get_token_set(name)
        ):

            if (
                len(token) >= 2
                and name_freq.get(
                    (country, token),
                    999999
                ) <= 250
            ):

                candidates.update(
                    rare_name.get(
                        (country, token),
                        []
                    )
                )

        # ----------------------------------------------------
        # 4. Rare address token <=250
        # ----------------------------------------------------

        for token in set(
            get_token_set(address)
        ):

            if (
                len(token) >= 2
                and address_freq.get(
                    (country, token),
                    999999
                ) <= 250
            ):

                candidates.update(
                    rare_address.get(
                        (country, token),
                        []
                    )
                )

        source_candidates += len(candidates)

    TOTAL_CANDIDATES += source_candidates
    ROWS += len(chunk)

    print(
        source_name,
        "rows:",
        len(chunk),
        "| candidates:",
        f"{source_candidates:,}",
        "| avg:",
        round(
            source_candidates / len(chunk),
            2
        )
    )

# ------------------------------------------------------------
# Estimate full test size
# ------------------------------------------------------------

AVG_PER_SOURCE_ROW = (
    TOTAL_CANDIDATES / ROWS
)

FULL_TEST_ROWS = (
    4_887_273 + 5_082_316
)

ESTIMATED_TOTAL = (
    AVG_PER_SOURCE_ROW *
    FULL_TEST_ROWS
)

print("\n========================================")
print("V2 TEST-SCALE ESTIMATE")
print("========================================")

print(
    "Average candidates/source row:",
    round(AVG_PER_SOURCE_ROW, 2)
)

print(
    "Estimated total candidate pairs:",
    f"{ESTIMATED_TOTAL:,.0f}"
)

print(
    "Estimated million candidates:",
    round(
        ESTIMATED_TOTAL / 1_000_000,
        2
    )
)

Loading Test S1 sample...
V2 indexes ready.

Sampling S2
S2 rows: 5000 | candidates: 1,190,928 | avg: 238.19

Sampling S3
S3 rows: 5000 | candidates: 1,040,127 | avg: 208.03

========================================
V2 TEST-SCALE ESTIMATE
========================================
Average candidates/source row: 223.11
Estimated total candidate pairs: 2,224,270,139
Estimated million candidates: 2224.27

In [ ]:
print("S1 columns:")
print(s1.columns.tolist())

print("\nS2 columns:")
print(s2.columns.tolist())

print("\nS3 columns:")
print(s3.columns.tolist())

S1 columns:
['entity_id', 'business_name', 'business_address', 'country']

S2 columns:
['entity_id', 'business_name', 'business_address', 'country']

S3 columns:
['entity_id', 'business_name', 'business_address', 'country']

In [ ]:
import pandas as pd
import numpy as np
import re
import unicodedata
from collections import defaultdict

# ============================================================
# SETTINGS
# ============================================================

S1_SAMPLE_SIZE = 10000
SOURCE_SAMPLE_SIZE = 5000
RARE_LIMIT = 50

# ============================================================
# NORMALIZATION
# ============================================================

def normalize_text(x):
    if pd.isna(x):
        return ""

    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def get_tokens(x):
    return set(x.split()) if x else set()


# ============================================================
# LOAD
# ============================================================

ROOT = "/content/amazon_ml_challenge/student_resource/dataset"

S1_PATH = f"{ROOT}/test/test_source1.tsv"
S2_PATH = f"{ROOT}/test/test_source2.tsv"
S3_PATH = f"{ROOT}/test/test_source3.tsv"

print("Loading test data...")

s1 = pd.read_csv(S1_PATH, sep="\t")
s2 = pd.read_csv(S2_PATH, sep="\t")
s3 = pd.read_csv(S3_PATH, sep="\t")

print("S1:", len(s1))
print("S2:", len(s2))
print("S3:", len(s3))


# ============================================================
# SAMPLE S1
# ============================================================

s1_sample = s1.sample(
    n=min(S1_SAMPLE_SIZE, len(s1)),
    random_state=42
).copy()

s1_sample["name_n"] = s1_sample["business_name"].map(normalize_text)
s1_sample["addr_n"] = s1_sample["business_address"].map(normalize_text)
s1_sample["country_n"] = s1_sample["country"].map(normalize_text)

print("\nS1 sample:", len(s1_sample))


# ============================================================
# BUILD EXACT BLOCKS + TOKEN FREQUENCIES
# ============================================================

print("\nBuilding V4 indexes...")

name_country = defaultdict(set)
address_country = defaultdict(set)

name_token_freq = defaultdict(int)
addr_token_freq = defaultdict(int)

for _, r in s1_sample.iterrows():

    sid = r["entity_id"]
    country = r["country_n"]

    name = r["name_n"]
    addr = r["addr_n"]

    # Exact name + country
    if name:
        name_country[(name, country)].add(sid)

    # Exact address + country
    if addr:
        address_country[(addr, country)].add(sid)

    # Name token frequencies
    for t in get_tokens(name):
        name_token_freq[t] += 1

    # Address token frequencies
    for t in get_tokens(addr):
        addr_token_freq[t] += 1


# ============================================================
# RARE TOKENS
# ============================================================

rare_name_tokens = {
    t for t, f in name_token_freq.items()
    if f <= RARE_LIMIT
}

rare_addr_tokens = {
    t for t, f in addr_token_freq.items()
    if f <= RARE_LIMIT
}

print("Rare name tokens:", len(rare_name_tokens))
print("Rare address tokens:", len(rare_addr_tokens))


# ============================================================
# TOKEN -> S1 ENTITY INDEX
# ============================================================

name_token_index = defaultdict(set)
addr_token_index = defaultdict(set)

for _, r in s1_sample.iterrows():

    sid = r["entity_id"]

    for t in get_tokens(r["name_n"]):
        if t in rare_name_tokens:
            name_token_index[t].add(sid)

    for t in get_tokens(r["addr_n"]):
        if t in rare_addr_tokens:
            addr_token_index[t].add(sid)


# ============================================================
# S1 LOOKUP
# ============================================================

s1_lookup = s1_sample.set_index("entity_id").to_dict("index")


# ============================================================
# V4 BLOCKER
# ============================================================

def v4_candidates(row):

    name = normalize_text(row["business_name"])
    addr = normalize_text(row["business_address"])
    country = normalize_text(row["country"])

    name_tokens = get_tokens(name)
    addr_tokens = get_tokens(addr)

    candidates = set()

    # --------------------------------------------------------
    # RULE 1
    # Exact normalized name + country
    # --------------------------------------------------------

    candidates.update(
        name_country.get((name, country), set())
    )

    # --------------------------------------------------------
    # RULE 2
    # Exact normalized address + country
    # --------------------------------------------------------

    candidates.update(
        address_country.get((addr, country), set())
    )

    # --------------------------------------------------------
    # RULE 3
    # At least 2 rare shared name tokens
    # + same country
    # --------------------------------------------------------

    rare_name = name_tokens & rare_name_tokens

    if rare_name:

        token_hits = defaultdict(int)

        for token in rare_name:

            for sid in name_token_index.get(token, []):

                srow = s1_lookup[sid]

                if srow["country_n"] == country:
                    token_hits[sid] += 1

        for sid, count in token_hits.items():

            if count >= 2:
                candidates.add(sid)

    # --------------------------------------------------------
    # RULE 4
    # At least 2 rare shared address tokens
    # + same country
    # --------------------------------------------------------

    rare_addr = addr_tokens & rare_addr_tokens

    if rare_addr:

        token_hits = defaultdict(int)

        for token in rare_addr:

            for sid in addr_token_index.get(token, []):

                srow = s1_lookup[sid]

                if srow["country_n"] == country:
                    token_hits[sid] += 1

        for sid, count in token_hits.items():

            if count >= 2:
                candidates.add(sid)

    return candidates


# ============================================================
# SAMPLE SOURCE ROWS
# ============================================================

s2_sample = s2.sample(
    n=min(SOURCE_SAMPLE_SIZE, len(s2)),
    random_state=42
).copy()

s3_sample = s3.sample(
    n=min(SOURCE_SAMPLE_SIZE, len(s3)),
    random_state=42
).copy()


# ============================================================
# ESTIMATION
# ============================================================

def estimate_candidates(source_df, source_name):

    counts = []

    for i, (_, row) in enumerate(source_df.iterrows()):

        c = v4_candidates(row)
        counts.append(len(c))

        if (i + 1) % 1000 == 0:
            print(
                f"{source_name}: "
                f"{i+1}/{len(source_df)}"
            )

    counts = np.array(counts)

    print("\n" + source_name)
    print("-" * 40)
    print("Sample rows :", len(counts))
    print("Average     :", round(counts.mean(), 2))
    print("Median      :", round(np.median(counts), 2))
    print("P90         :", round(np.percentile(counts, 90), 2))
    print("P95         :", round(np.percentile(counts, 95), 2))
    print("P99         :", round(np.percentile(counts, 99), 2))
    print("Maximum     :", int(counts.max()))

    return counts


print("\n========================================")
print("V4 TEST-SCALE ESTIMATE")
print("========================================")

c2 = estimate_candidates(s2_sample, "S2")
c3 = estimate_candidates(s3_sample, "S3")


# ============================================================
# FULL TEST ESTIMATE
# ============================================================

avg_candidates = (
    c2.mean() + c3.mean()
) / 2

estimated_total = avg_candidates * (
    len(s2) + len(s3)
)

print("\n========================================")
print("FINAL V4 ESTIMATE")
print("========================================")
print(
    "Average candidates/source row:",
    round(avg_candidates, 2)
)
print(
    "Estimated total candidates:",
    f"{estimated_total:,.0f}"
)
print(
    "Estimated million candidates:",
    round(estimated_total / 1e6, 2)
)
print("========================================")

Loading test data...
S1: 1732544
S2: 4887273
S3: 5082316

S1 sample: 10000

Building V4 indexes...
Rare name tokens: 7501
Rare address tokens: 17378

========================================
V4 TEST-SCALE ESTIMATE
========================================
S2: 1000/5000
S2: 2000/5000
S2: 3000/5000
S2: 4000/5000
S2: 5000/5000

S2
----------------------------------------
Sample rows : 5000
Average     : 1.34
Median      : 0.0
P90         : 3.0
P95         : 8.0
P99         : 19.0
Maximum     : 44
S3: 1000/5000
S3: 2000/5000
S3: 3000/5000
S3: 4000/5000
S3: 5000/5000

S3
----------------------------------------
Sample rows : 5000
Average     : 1.41
Median      : 0.0
P90         : 4.0
P95         : 8.0
P99         : 22.0
Maximum     : 40

========================================
FINAL V4 ESTIMATE
========================================
Average candidates/source row: 1.38
Estimated total candidates: 13,734,106
Estimated million candidates: 13.73
========================================

In [ ]:
# ============================================================
# V4 VALIDATION RECALL
# ============================================================

print("Testing V4 blocker on validation...")

# IMPORTANT:
# This assumes these already exist from our earlier validation:
#   s1_val_lookup
#   gt_lookup
#
# and that s1_val_lookup contains the validation S1 rows.

# ------------------------------------------------------------
# Build V4 indexes from VALIDATION S1 only
# ------------------------------------------------------------

from collections import defaultdict
import numpy as np

VAL_RARE_LIMIT = 50

val_name_country = defaultdict(set)
val_address_country = defaultdict(set)

val_name_freq = defaultdict(int)
val_addr_freq = defaultdict(int)

for sid, r in s1_val_lookup.items():

    name = normalize_text(r["business_name"])
    addr = normalize_text(r["business_address"])
    country = normalize_text(r["country"])

    if name:
        val_name_country[(name, country)].add(sid)

    if addr:
        val_address_country[(addr, country)].add(sid)

    for t in get_tokens(name):
        val_name_freq[t] += 1

    for t in get_tokens(addr):
        val_addr_freq[t] += 1


val_rare_name = {
    t for t, f in val_name_freq.items()
    if f <= VAL_RARE_LIMIT
}

val_rare_addr = {
    t for t, f in val_addr_freq.items()
    if f <= VAL_RARE_LIMIT
}

val_name_index = defaultdict(set)
val_addr_index = defaultdict(set)

for sid, r in s1_val_lookup.items():

    name = normalize_text(r["business_name"])
    addr = normalize_text(r["business_address"])

    for t in get_tokens(name):
        if t in val_rare_name:
            val_name_index[t].add(sid)

    for t in get_tokens(addr):
        if t in val_rare_addr:
            val_addr_index[t].add(sid)


# ------------------------------------------------------------
# V4 candidates for a validation source row
# ------------------------------------------------------------

def v4_val_candidates(row):

    name = normalize_text(row["business_name"])
    addr = normalize_text(row["business_address"])
    country = normalize_text(row["country"])

    name_tokens = get_tokens(name)
    addr_tokens = get_tokens(addr)

    candidates = set()

    # Rule 1: exact name + country
    candidates.update(
        val_name_country.get((name, country), set())
    )

    # Rule 2: exact address + country
    candidates.update(
        val_address_country.get((addr, country), set())
    )

    # Rule 3: >=2 rare shared name tokens
    rare_name = name_tokens & val_rare_name

    token_hits = defaultdict(int)

    for t in rare_name:
        for sid in val_name_index.get(t, []):
            srow = s1_val_lookup[sid]

            if normalize_text(srow["country"]) == country:
                token_hits[sid] += 1

    for sid, count in token_hits.items():
        if count >= 2:
            candidates.add(sid)

    # Rule 4: >=2 rare shared address tokens
    rare_addr = addr_tokens & val_rare_addr

    token_hits = defaultdict(int)

    for t in rare_addr:
        for sid in val_addr_index.get(t, []):
            srow = s1_val_lookup[sid]

            if normalize_text(srow["country"]) == country:
                token_hits[sid] += 1

    for sid, count in token_hits.items():
        if count >= 2:
            candidates.add(sid)

    return candidates


# ------------------------------------------------------------
# Evaluate recall
# ------------------------------------------------------------

total_true = 0
retrieved_true = 0
zero_candidate = 0
candidate_count = []

rows_with_gt = 0

for sid, true_matches in gt_lookup.items():

    # Only validation S1 entities
    if sid not in s1_val_lookup:
        continue

    rows_with_gt += 1

    candidates = v4_val_candidates(
        s1_val_lookup[sid]
    )

    candidate_count.append(len(candidates))

    true_set = set(true_matches)

    total_true += len(true_set)
    retrieved_true += len(true_set & candidates)

    if len(candidates) == 0:
        zero_candidate += 1


recall = (
    retrieved_true / total_true
    if total_true else 0
)

print("\n========================================")
print("V4 VALIDATION RESULT")
print("========================================")

print("Validation S1 entities:", rows_with_gt)
print("True matches:", total_true)
print("Retrieved true matches:", retrieved_true)
print("Missed true matches:", total_true - retrieved_true)

print("Candidate recall:", round(recall * 100, 2), "%")

print("Zero-candidate S1:", zero_candidate)

if candidate_count:
    print(
        "Avg candidates/S1:",
        round(np.mean(candidate_count), 2)
    )

print("========================================")

Testing V4 blocker on validation...

========================================
V4 VALIDATION RESULT
========================================
Validation S1 entities: 2000
True matches: 6855
Retrieved true matches: 0
Missed true matches: 6855
Candidate recall: 0.0 %
Zero-candidate S1: 0
Avg candidates/S1: 5.65
========================================

In [ ]:
import pandas as pd

ROOT = "/content/amazon_ml_challenge/student_resource/dataset"

GT_PATH = f"{ROOT}/train/train_ground_truth.tsv"
S1_PATH = f"{ROOT}/train/train_source1.tsv"

print("Loading ground truth...")
gt = pd.read_csv(GT_PATH, sep="\t")

print("GT shape:", gt.shape)
print("GT columns:", gt.columns.tolist())

print("\nFirst 5 rows:")
display(gt.head())

print("\nLoading first 10k S1...")
s1_head = pd.read_csv(
    S1_PATH,
    sep="\t",
    nrows=10000
)

print("S1 columns:", s1_head.columns.tolist())
print("S1 shape:", s1_head.shape)

Loading ground truth...
GT shape: (2206821, 2)
GT columns: ['source1_entity_id', 'matched_entity_ids']

First 5 rows:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

Loading first 10k S1...
S1 columns: ['entity_id', 'business_name', 'business_address', 'country']
S1 shape: (10000, 4)

In [ ]:
# ============================================================
# FAST V4 RECALL TEST — NO GLOBAL TOKEN SCAN
# ============================================================

print("Running fast true-pair recall test...")

total_true = 0

exact_name_hits = 0
exact_addr_hits = 0

name_2token_hits = 0
addr_2token_hits = 0

any_rule_hits = 0

s2_true = 0
s3_true = 0

s2_hits = 0
s3_hits = 0


for sid, matches in gt_lookup.items():

    s1row = s1_lookup[sid]

    s1_name = normalize_text(
        s1row["business_name"]
    )

    s1_addr = normalize_text(
        s1row["business_address"]
    )

    s1_country = normalize_text(
        s1row["country"]
    )

    s1_name_tokens = get_tokens(s1_name)
    s1_addr_tokens = get_tokens(s1_addr)

    for target_id in matches:

        if target_id not in true_source_rows:
            continue

        target = true_source_rows[target_id]

        target_name = target["name"]
        target_addr = target["addr"]
        target_country = target["country"]

        total_true += 1

        if target_id.startswith("S2-"):
            s2_true += 1
        else:
            s3_true += 1

        hit = False

        # --------------------------------------------
        # Rule 1: exact name + country
        # --------------------------------------------

        if (
            s1_country == target_country
            and s1_name
            and target_name
            and s1_name == target_name
        ):
            exact_name_hits += 1
            hit = True

        # --------------------------------------------
        # Rule 2: exact address + country
        # --------------------------------------------

        if (
            s1_country == target_country
            and s1_addr
            and target_addr
            and s1_addr == target_addr
        ):
            exact_addr_hits += 1
            hit = True

        # --------------------------------------------
        # Rule 3: >=2 shared name tokens + country
        # --------------------------------------------

        if s1_country == target_country:

            shared_name = (
                s1_name_tokens
                & get_tokens(target_name)
            )

            if len(shared_name) >= 2:
                name_2token_hits += 1
                hit = True

        # --------------------------------------------
        # Rule 4: >=2 shared address tokens + country
        # --------------------------------------------

        if s1_country == target_country:

            shared_addr = (
                s1_addr_tokens
                & get_tokens(target_addr)
            )

            if len(shared_addr) >= 2:
                addr_2token_hits += 1
                hit = True

        if hit:
            any_rule_hits += 1

            if target_id.startswith("S2-"):
                s2_hits += 1
            else:
                s3_hits += 1


print("\n========================================")
print("FAST V4 RECALL ANALYSIS")
print("========================================")

print("Total true pairs:", total_true)

print()
print(
    "Exact name + country:",
    exact_name_hits,
    f"({exact_name_hits / total_true * 100:.2f}%)"
)

print(
    "Exact address + country:",
    exact_addr_hits,
    f"({exact_addr_hits / total_true * 100:.2f}%)"
)

print(
    ">=2 shared name tokens:",
    name_2token_hits,
    f"({name_2token_hits / total_true * 100:.2f}%)"
)

print(
    ">=2 shared address tokens:",
    addr_2token_hits,
    f"({addr_2token_hits / total_true * 100:.2f}%)"
)

print()
print(
    "ANY V4 rule:",
    any_rule_hits,
    f"({any_rule_hits / total_true * 100:.2f}%)"
)

print()
print(
    "S2 recall:",
    s2_hits / s2_true * 100
)

print(
    "S3 recall:",
    s3_hits / s3_true * 100
)

print("========================================")

Running fast true-pair recall test...

========================================
FAST V4 RECALL ANALYSIS
========================================
Total true pairs: 6975

Exact name + country: 1473 (21.12%)
Exact address + country: 749 (10.74%)
>=2 shared name tokens: 5504 (78.91%)
>=2 shared address tokens: 6662 (95.51%)

ANY V4 rule: 6963 (99.83%)

S2 recall: 99.73061957497755
S3 recall: 99.91744634012107
========================================

In [ ]:
# ============================================================
# V4 TEST-SCALE CANDIDATE VOLUME ESTIMATE
# MEMORY-SAFE SAMPLE VERSION
# ============================================================

import pandas as pd
import numpy as np
import re
import unicodedata
from collections import Counter, defaultdict
from itertools import combinations

ROOT = "/content/amazon_ml_challenge/student_resource/dataset"

S1_PATH = f"{ROOT}/test/test_source1.tsv"
S2_PATH = f"{ROOT}/test/test_source2.tsv"
S3_PATH = f"{ROOT}/test/test_source3.tsv"

S1_SAMPLE = 10000
SOURCE_SAMPLE = 100000

print("Loading S1 sample...")

s1_test = pd.read_csv(S1_PATH, sep="\t")

s1_sample = s1_test.sample(
    n=S1_SAMPLE,
    random_state=42
).copy()

print("S1 sample:", len(s1_sample))


# ============================================================
# NORMALIZATION
# ============================================================

def normalize_text(x):
    if pd.isna(x):
        return ""

    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def get_tokens(x):
    return set(x.split()) if x else set()


# ============================================================
# NORMALIZE S1
# ============================================================

print("Normalizing S1...")

s1_sample["name_n"] = s1_sample["business_name"].map(
    normalize_text
)

s1_sample["addr_n"] = s1_sample["business_address"].map(
    normalize_text
)

s1_sample["country_n"] = s1_sample["country"].map(
    normalize_text
)


# ============================================================
# LOAD SOURCE SAMPLES
# ============================================================

print("\nLoading S2 sample...")

s2 = pd.read_csv(
    S2_PATH,
    sep="\t",
    skiprows=lambda x: x > 0 and np.random.random() > (
        SOURCE_SAMPLE / 4887273
    )
)

# Keep exactly at most SOURCE_SAMPLE
if len(s2) > SOURCE_SAMPLE:
    s2 = s2.sample(
        SOURCE_SAMPLE,
        random_state=42
    )

print("S2 sample:", len(s2))


print("\nLoading S3 sample...")

s3 = pd.read_csv(
    S3_PATH,
    sep="\t",
    skiprows=lambda x: x > 0 and np.random.random() > (
        SOURCE_SAMPLE / 5082316
    )
)

if len(s3) > SOURCE_SAMPLE:
    s3 = s3.sample(
        SOURCE_SAMPLE,
        random_state=42
    )

print("S3 sample:", len(s3))


# ============================================================
# NORMALIZE SOURCE SAMPLES
# ============================================================

for df in [s2, s3]:

    df["name_n"] = df["business_name"].map(
        normalize_text
    )

    df["addr_n"] = df["business_address"].map(
        normalize_text
    )

    df["country_n"] = df["country"].map(
        normalize_text
    )


# ============================================================
# BUILD TOKEN-PAIR FREQUENCY TABLE
#
# For every source row:
#
# country + tokenA + tokenB
#
# tells us how many source rows contain BOTH tokens.
# ============================================================

def build_pair_counter(df, column):

    counter = Counter()

    for value, country in zip(
        df[column],
        df["country_n"]
    ):

        ts = sorted(get_tokens(value))

        if len(ts) < 2:
            continue

        for a, b in combinations(ts, 2):

            counter[
                (country, a, b)
            ] += 1

    return counter


print("\nBuilding S2 name pair index...")

s2_name_pairs = build_pair_counter(
    s2,
    "name_n"
)

print(
    "S2 name pairs:",
    len(s2_name_pairs)
)


print("\nBuilding S2 address pair index...")

s2_addr_pairs = build_pair_counter(
    s2,
    "addr_n"
)

print(
    "S2 address pairs:",
    len(s2_addr_pairs)
)


print("\nBuilding S3 name pair index...")

s3_name_pairs = build_pair_counter(
    s3,
    "name_n"
)

print(
    "S3 name pairs:",
    len(s3_name_pairs)
)


print("\nBuilding S3 address pair index...")

s3_addr_pairs = build_pair_counter(
    s3,
    "addr_n"
)

print(
    "S3 address pairs:",
    len(s3_addr_pairs)
)


# ============================================================
# ESTIMATE CANDIDATES
#
# This estimates the number of candidates produced by
# >=2 shared tokens.
#
# Exact name/address candidates are added separately.
# ============================================================

def estimate_token_candidates(
    s1_df,
    pair_counter,
    column
):

    estimates = []

    for value, country in zip(
        s1_df[column],
        s1_df["country_n"]
    ):

        ts = sorted(get_tokens(value))

        if len(ts) < 2:
            estimates.append(0)
            continue

        total = 0

        for a, b in combinations(ts, 2):

            total += pair_counter.get(
                (country, a, b),
                0
            )

        estimates.append(total)

    return np.array(estimates)


print("\nEstimating S2 name candidates...")

s2_name_est = estimate_token_candidates(
    s1_sample,
    s2_name_pairs,
    "name_n"
)


print("Estimating S2 address candidates...")

s2_addr_est = estimate_token_candidates(
    s1_sample,
    s2_addr_pairs,
    "addr_n"
)


print("Estimating S3 name candidates...")

s3_name_est = estimate_token_candidates(
    s1_sample,
    s3_name_pairs,
    "name_n"
)


print("Estimating S3 address candidates...")

s3_addr_est = estimate_token_candidates(
    s1_sample,
    s3_addr_pairs,
    "addr_n"
)


# ============================================================
# PRINT ESTIMATES
# ============================================================

print("\n")
print("=" * 60)
print("V4 TOKEN-BLOCK TEST-SCALE ESTIMATE")
print("=" * 60)

print("\nS2")
print("-" * 40)
print(
    "Name avg:",
    round(s2_name_est.mean(), 2)
)
print(
    "Address avg:",
    round(s2_addr_est.mean(), 2)
)

print("\nS3")
print("-" * 40)
print(
    "Name avg:",
    round(s3_name_est.mean(), 2)
)
print(
    "Address avg:",
    round(s3_addr_est.mean(), 2)
)

avg_token_candidates = (
    s2_name_est.mean()
    + s2_addr_est.mean()
    + s3_name_est.mean()
    + s3_addr_est.mean()
) / 2

estimated_total = avg_token_candidates * (
    4887273 + 5082316
)

print("\n")
print("Approx candidate pairs:", f"{estimated_total:,.0f}")
print(
    "Approx million:",
    round(estimated_total / 1e6, 2)
)

print("=" * 60)

Loading S1 sample...
S1 sample: 10000
Normalizing S1...

Loading S2 sample...
S2 sample: 99457

Loading S3 sample...
S3 sample: 100000

Building S2 name pair index...
S2 name pairs: 287859

Building S2 address pair index...
S2 address pairs: 1616515

Building S3 name pair index...
S3 name pairs: 307472

Building S3 address pair index...
S3 address pairs: 1497719

Estimating S2 name candidates...
Estimating S2 address candidates...
Estimating S3 name candidates...
Estimating S3 address candidates...


============================================================
V4 TOKEN-BLOCK TEST-SCALE ESTIMATE
============================================================

S2
----------------------------------------
Name avg: 2061.62
Address avg: 7265.74

S3
----------------------------------------
Name avg: 2547.65
Address avg: 5389.61


Approx candidate pairs: 86,060,540,948
Approx million: 86060.54
============================================================

In [ ]:
# ============================================================
# FAST TOKEN FREQUENCY SCAN
# Only count tokens that occur in the TRUE validation pairs
# ============================================================

from collections import Counter
import pandas as pd
import numpy as np

print("Starting optimized frequency scan...")

needed_name = set(needed_name_tokens)
needed_addr = set(needed_addr_tokens)

name_freq_fast = Counter()
addr_freq_fast = Counter()

CHUNK = 250_000

def count_tokens_fast(path, source_name):

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        chunksize=CHUNK,
        usecols=[
            "business_name",
            "business_address"
        ]
    ):

        # -----------------------------
        # Names
        # -----------------------------
        names = (
            chunk["business_name"]
            .fillna("")
            .astype(str)
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        name_tokens = (
            names.str.split()
            .explode()
        )

        name_tokens = name_tokens[
            name_tokens.isin(needed_name)
        ]

        if len(name_tokens):
            counts = name_tokens.value_counts()

            for token, count in counts.items():
                name_freq_fast[token] += int(count)

        # -----------------------------
        # Addresses
        # -----------------------------
        addrs = (
            chunk["business_address"]
            .fillna("")
            .astype(str)
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        addr_tokens = (
            addrs.str.split()
            .explode()
        )

        addr_tokens = addr_tokens[
            addr_tokens.isin(needed_addr)
        ]

        if len(addr_tokens):
            counts = addr_tokens.value_counts()

            for token, count in counts.items():
                addr_freq_fast[token] += int(count)

        rows += len(chunk)

        if rows % 1_000_000 == 0:
            print(source_name, rows)

    print(source_name, "finished:", rows)


count_tokens_fast(
    S2_PATH,
    "S2"
)

count_tokens_fast(
    S3_PATH,
    "S3"
)

print("\nFrequency scan complete.")
print("Name frequencies:", len(name_freq_fast))
print("Address frequencies:", len(addr_freq_fast))

Starting optimized frequency scan...
S2 1000000
S2 2000000
S2 3000000
S2 4000000
S2 finished: 4887273
S3 1000000
S3 2000000
S3 3000000
S3 4000000
S3 5000000
S3 finished: 5082316

Frequency scan complete.
Name frequencies: 3495
Address frequencies: 5973

In [ ]:
# ============================================================
# TEST RARE <=50 RECALL ON TRUE PAIRS
# ============================================================

RARE_LIMIT = 50

rare_name_fast = {
    t for t in needed_name_tokens
    if name_freq_fast[t] <= RARE_LIMIT
}

rare_addr_fast = {
    t for t in needed_addr_tokens
    if addr_freq_fast[t] <= RARE_LIMIT
}

total = 0

name_rare_hits = 0
addr_rare_hits = 0
any_rare_hits = 0

s2_total = 0
s2_hits = 0

s3_total = 0
s3_hits = 0

for sid, matches in gt_lookup.items():

    s1row = s1_lookup[sid]

    s1_country = normalize_text(
        s1row["country"]
    )

    s1_name_tokens = get_tokens(
        normalize_text(s1row["business_name"])
    )

    s1_addr_tokens = get_tokens(
        normalize_text(s1row["business_address"])
    )

    for target_id in matches:

        target = true_source_rows[target_id]

        if s1_country != target["country"]:
            continue

        total += 1

        if target_id.startswith("S2-"):
            s2_total += 1
        else:
            s3_total += 1

        target_name_tokens = get_tokens(
            target["name"]
        )

        target_addr_tokens = get_tokens(
            target["addr"]
        )

        shared_name_rare = (
            s1_name_tokens
            & target_name_tokens
            & rare_name_fast
        )

        shared_addr_rare = (
            s1_addr_tokens
            & target_addr_tokens
            & rare_addr_fast
        )

        hit = (
            len(shared_name_rare) >= 2
            or
            len(shared_addr_rare) >= 2
        )

        # Exact rules remain part of V4
        exact_name = (
            normalize_text(s1row["business_name"])
            == target["name"]
            and s1_country == target["country"]
        )

        exact_addr = (
            normalize_text(s1row["business_address"])
            == target["addr"]
            and s1_country == target["country"]
        )

        hit = hit or exact_name or exact_addr

        if hit:
            any_rare_hits += 1

            if target_id.startswith("S2-"):
                s2_hits += 1
            else:
                s3_hits += 1

print("\n========================================")
print("V4 RARE-TOKEN RECALL")
print("========================================")

print(
    "Total true pairs:",
    total
)

print(
    "Retrieved:",
    any_rare_hits
)

print(
    "Missed:",
    total - any_rare_hits
)

print(
    "Overall recall:",
    round(any_rare_hits / total * 100, 2),
    "%"
)

print(
    "S2 recall:",
    round(s2_hits / s2_total * 100, 2),
    "%"
)

print(
    "S3 recall:",
    round(s3_hits / s3_total * 100, 2),
    "%"
)

print(
    "Rare name tokens:",
    len(rare_name_fast)
)

print(
    "Rare address tokens:",
    len(rare_addr_fast)
)

print("========================================")

========================================
V4 RARE-TOKEN RECALL
========================================
Total true pairs: 6975
Retrieved: 2366
Missed: 4609
Overall recall: 33.92 %
S2 recall: 38.01 %
S3 recall: 30.16 %
Rare name tokens: 1705
Rare address tokens: 1206
========================================

In [ ]:
# ============================================================
# TEST DIFFERENT RARITY LIMITS
# NO NEW DATA SCAN
# ============================================================

limits = [50, 100, 250, 500, 1000, 1500, 2000, 2500, 5000]

# Count denominators once
total_s2 = sum(
    1
    for matches in gt_lookup.values()
    for x in matches
    if x.startswith("S2-")
)

total_s3 = sum(
    1
    for matches in gt_lookup.values()
    for x in matches
    if x.startswith("S3-")
)

total_all = total_s2 + total_s3

print("S2 true pairs:", total_s2)
print("S3 true pairs:", total_s3)
print("Total true pairs:", total_all)

print("\n" + "=" * 75)
print(
    f"{'LIMIT':<10}"
    f"{'OVERALL':<15}"
    f"{'S2':<15}"
    f"{'S3':<15}"
)
print("=" * 75)


for LIMIT in limits:

    rare_name_test = {
        t for t, c in name_freq_fast.items()
        if c <= LIMIT
    }

    rare_addr_test = {
        t for t, c in addr_freq_fast.items()
        if c <= LIMIT
    }

    hit_all = 0
    hit_s2 = 0
    hit_s3 = 0

    for sid, matches in gt_lookup.items():

        s1row = s1_lookup[sid]

        s1_name = normalize_text(
            s1row["business_name"]
        )

        s1_addr = normalize_text(
            s1row["business_address"]
        )

        s1_country = normalize_text(
            s1row["country"]
        )

        s1_name_tokens = get_tokens(s1_name)
        s1_addr_tokens = get_tokens(s1_addr)

        for target_id in matches:

            target = true_source_rows[target_id]

            if s1_country != target["country"]:
                continue

            target_name = target["name"]
            target_addr = target["addr"]

            target_name_tokens = get_tokens(
                target_name
            )

            target_addr_tokens = get_tokens(
                target_addr
            )

            # Exact rules
            exact_name = (
                s1_name
                and target_name
                and s1_name == target_name
            )

            exact_addr = (
                s1_addr
                and target_addr
                and s1_addr == target_addr
            )

            # Rare token rules
            name_hit = (
                len(
                    s1_name_tokens
                    & target_name_tokens
                    & rare_name_test
                ) >= 2
            )

            addr_hit = (
                len(
                    s1_addr_tokens
                    & target_addr_tokens
                    & rare_addr_test
                ) >= 2
            )

            hit = (
                exact_name
                or exact_addr
                or name_hit
                or addr_hit
            )

            if hit:

                hit_all += 1

                if target_id.startswith("S2-"):
                    hit_s2 += 1
                else:
                    hit_s3 += 1

    overall = hit_all / total_all * 100
    s2_rec = hit_s2 / total_s2 * 100
    s3_rec = hit_s3 / total_s3 * 100

    print(
        f"{LIMIT:<10}"
        f"{overall:<15.2f}"
        f"{s2_rec:<15.2f}"
        f"{s3_rec:<15.2f}"
    )

print("=" * 75)

S2 true pairs: 3341
S3 true pairs: 3634
Total true pairs: 6975

===========================================================================
LIMIT     OVERALL        S2             S3
===========================================================================
50        32.29          36.07          28.81
100       34.78          38.34          31.51
250       40.50          43.64          37.62
500       46.09          48.97          43.45
1000      53.25          55.55          51.13
1500      60.59          62.26          59.05
2000      64.46          65.97          63.07
2500      67.35          68.54          66.26
5000      75.74          77.04          74.55
===========================================================================

In [ ]:
from difflib import SequenceMatcher

def similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()

In [ ]:
# ============================================================
# TEST SELECTIVE BLOCKING RULES ON TRUE PAIRS
# ============================================================

import re

def extract_numbers(text):
    return set(re.findall(r"\d+", text))


rules = {
    "address_2tokens": 0,
    "address_2tokens_number": 0,
    "name_2tokens": 0,
    "name_2tokens_strong_similarity": 0,
    "address_number_plus_token": 0,
    "combined_selective": 0
}

s2_hits = {k: 0 for k in rules}
s3_hits = {k: 0 for k in rules}

total_s2 = 0
total_s3 = 0


for sid, matches in gt_lookup.items():

    s1row = s1_lookup[sid]

    s1_name = normalize_text(
        s1row["business_name"]
    )

    s1_addr = normalize_text(
        s1row["business_address"]
    )

    s1_country = normalize_text(
        s1row["country"]
    )

    s1_name_tokens = get_tokens(s1_name)
    s1_addr_tokens = get_tokens(s1_addr)
    s1_numbers = extract_numbers(s1_addr)

    for target_id in matches:

        target = true_source_rows[target_id]

        if s1_country != target["country"]:
            continue

        if target_id.startswith("S2-"):
            total_s2 += 1
        else:
            total_s3 += 1

        target_name = target["name"]
        target_addr = target["addr"]

        target_name_tokens = get_tokens(target_name)
        target_addr_tokens = get_tokens(target_addr)
        target_numbers = extract_numbers(target_addr)

        shared_name = (
            s1_name_tokens & target_name_tokens
        )

        shared_addr = (
            s1_addr_tokens & target_addr_tokens
        )

        shared_numbers = (
            s1_numbers & target_numbers
        )

        # --------------------------------------------
        # Rule A
        # >=2 shared address tokens
        # --------------------------------------------

        rule_a = (
            len(shared_addr) >= 2
        )

        # --------------------------------------------
        # Rule B
        # >=2 shared address tokens
        # + shared address number
        # --------------------------------------------

        rule_b = (
            len(shared_addr) >= 2
            and len(shared_numbers) >= 1
        )

        # --------------------------------------------
        # Rule C
        # >=2 shared name tokens
        # --------------------------------------------

        rule_c = (
            len(shared_name) >= 2
        )

        # --------------------------------------------
        # Rule D
        # >=2 shared name tokens
        # + high sequence similarity
        # --------------------------------------------

        name_sim = similarity(
            s1_name,
            target_name
        )

        rule_d = (
            len(shared_name) >= 2
            and name_sim >= 0.70
        )

        # --------------------------------------------
        # Rule E
        # shared address number + >=1 address token
        # --------------------------------------------

        rule_e = (
            len(shared_numbers) >= 1
            and len(shared_addr) >= 1
        )

        # --------------------------------------------
        # Rule F
        # Selective combined rule
        # --------------------------------------------

        rule_f = (
            rule_b
            or
            rule_d
        )

        rule_values = [
            rule_a,
            rule_b,
            rule_c,
            rule_d,
            rule_e,
            rule_f
        ]

        for key, hit in zip(
            rules.keys(),
            rule_values
        ):

            if hit:

                rules[key] += 1

                if target_id.startswith("S2-"):
                    s2_hits[key] += 1
                else:
                    s3_hits[key] += 1


print("\n========================================")
print("SELECTIVE BLOCKING TRUE-PAIR RECALL")
print("========================================")

for key in rules:

    overall = rules[key] / (
        total_s2 + total_s3
    ) * 100

    s2_rec = (
        s2_hits[key] / total_s2 * 100
    )

    s3_rec = (
        s3_hits[key] / total_s3 * 100
    )

    print(
        f"{key:35s}"
        f" Overall={overall:6.2f}%"
        f" | S2={s2_rec:6.2f}%"
        f" | S3={s3_rec:6.2f}%"
    )

print("========================================")

========================================
SELECTIVE BLOCKING TRUE-PAIR RECALL
========================================
address_2tokens                     Overall= 95.51% | S2= 95.33% | S3= 95.68%
address_2tokens_number              Overall= 79.14% | S2= 78.03% | S3= 80.16%
name_2tokens                        Overall= 78.91% | S2= 77.16% | S3= 80.52%
name_2tokens_strong_similarity      Overall= 69.84% | S2= 68.90% | S3= 70.69%
address_number_plus_token           Overall= 79.23% | S2= 78.03% | S3= 80.32%
combined_selective                  Overall= 95.40% | S2= 94.85% | S3= 95.90%
========================================

In [ ]:
# ============================================================
# V4 UNIQUE-CANDIDATE VOLUME ESTIMATE
# ============================================================

import pandas as pd
import numpy as np
import re
import unicodedata
from collections import defaultdict

ROOT = "/content/amazon_ml_challenge/student_resource/dataset"

S1_PATH = f"{ROOT}/test/test_source1.tsv"
S2_PATH = f"{ROOT}/test/test_source2.tsv"
S3_PATH = f"{ROOT}/test/test_source3.tsv"

S1_SAMPLE_SIZE = 10_000
SOURCE_SAMPLE_SIZE = 100_000

print("Loading S1...")

s1 = pd.read_csv(S1_PATH, sep="\t")

s1_sample = s1.sample(
    n=S1_SAMPLE_SIZE,
    random_state=42
).copy()

print("S1 sample:", len(s1_sample))


# ============================================================
# NORMALIZATION
# ============================================================

def normalize_text(x):
    if pd.isna(x):
        return ""

    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def get_tokens(x):
    return set(x.split()) if x else set()


# ============================================================
# NORMALIZE S1
# ============================================================

print("Normalizing S1...")

s1_sample["name_n"] = s1_sample["business_name"].map(
    normalize_text
)

s1_sample["addr_n"] = s1_sample["business_address"].map(
    normalize_text
)

s1_sample["country_n"] = s1_sample["country"].map(
    normalize_text
)


# ============================================================
# LOAD SOURCE SAMPLES
# ============================================================

print("\nLoading S2...")

s2 = pd.read_csv(
    S2_PATH,
    sep="\t",
    nrows=SOURCE_SAMPLE_SIZE
)

print("S2 sample:", len(s2))

print("\nLoading S3...")

s3 = pd.read_csv(
    S3_PATH,
    sep="\t",
    nrows=SOURCE_SAMPLE_SIZE
)

print("S3 sample:", len(s3))


# ============================================================
# NORMALIZE SOURCE DATA
# ============================================================

for df in [s2, s3]:

    df["entity_id"] = df["entity_id"].astype(str)

    df["name_n"] = df["business_name"].map(
        normalize_text
    )

    df["addr_n"] = df["business_address"].map(
        normalize_text
    )

    df["country_n"] = df["country"].map(
        normalize_text
    )


# ============================================================
# BUILD SOURCE INDEXES
#
# We store ONLY IDs in the indexes.
# ============================================================

def build_indexes(df):

    exact_name = defaultdict(set)
    exact_addr = defaultdict(set)

    name_tokens = defaultdict(set)
    addr_tokens = defaultdict(set)

    source_lookup = {}

    for row in df.itertuples(index=False):

        eid = row.entity_id

        name = row.name_n
        addr = row.addr_n
        country = row.country_n

        source_lookup[eid] = (
            name,
            addr,
            country
        )

        # Exact name + country
        if name:
            exact_name[
                (name, country)
            ].add(eid)

        # Exact address + country
        if addr:
            exact_addr[
                (addr, country)
            ].add(eid)

        # Name tokens
        for token in get_tokens(name):
            name_tokens[
                (country, token)
            ].add(eid)

        # Address tokens
        for token in get_tokens(addr):
            addr_tokens[
                (country, token)
            ].add(eid)

    return (
        exact_name,
        exact_addr,
        name_tokens,
        addr_tokens,
        source_lookup
    )


print("\nBuilding S2 indexes...")

s2_exact_name, s2_exact_addr, s2_name_tokens, s2_addr_tokens, s2_lookup = \
    build_indexes(s2)


print("Building S3 indexes...")

s3_exact_name, s3_exact_addr, s3_name_tokens, s3_addr_tokens, s3_lookup = \
    build_indexes(s3)


# ============================================================
# CANDIDATES FOR ONE S1 ROW
# ============================================================

def get_candidates(
    row,
    exact_name,
    exact_addr,
    name_index,
    addr_index
):

    name = row["name_n"]
    addr = row["addr_n"]
    country = row["country_n"]

    name_ts = get_tokens(name)
    addr_ts = get_tokens(addr)

    candidates = set()

    # --------------------------------------------------------
    # Rule 1: exact name + country
    # --------------------------------------------------------

    if name:
        candidates.update(
            exact_name.get(
                (name, country),
                set()
            )
        )

    # --------------------------------------------------------
    # Rule 2: exact address + country
    # --------------------------------------------------------

    if addr:
        candidates.update(
            exact_addr.get(
                (addr, country),
                set()
            )
        )

    # --------------------------------------------------------
    # Rule 3:
    # >=2 shared NAME tokens
    # --------------------------------------------------------

    name_token_hits = defaultdict(int)

    for token in name_ts:

        for eid in name_index.get(
            (country, token),
            set()
        ):

            name_token_hits[eid] += 1

    for eid, count in name_token_hits.items():

        if count >= 2:
            candidates.add(eid)

    # --------------------------------------------------------
    # Rule 4:
    # >=2 shared ADDRESS tokens
    # --------------------------------------------------------

    addr_token_hits = defaultdict(int)

    for token in addr_ts:

        for eid in addr_index.get(
            (country, token),
            set()
        ):

            addr_token_hits[eid] += 1

    for eid, count in addr_token_hits.items():

        if count >= 2:
            candidates.add(eid)

    return candidates


# ============================================================
# EVALUATE EACH SOURCE SEPARATELY
# ============================================================

def evaluate_source(
    source_name,
    exact_name,
    exact_addr,
    name_index,
    addr_index
):

    counts = []

    print(
        f"\nEvaluating {source_name}..."
    )

    for i, (_, row) in enumerate(
        s1_sample.iterrows()
    ):

        candidates = get_candidates(
            row,
            exact_name,
            exact_addr,
            name_index,
            addr_index
        )

        counts.append(len(candidates))

        if (i + 1) % 1000 == 0:
            print(
                f"{source_name}:",
                i + 1,
                "/",
                len(s1_sample)
            )

    return np.array(counts)


s2_counts = evaluate_source(
    "S2",
    s2_exact_name,
    s2_exact_addr,
    s2_name_tokens,
    s2_addr_tokens
)

s3_counts = evaluate_source(
    "S3",
    s3_exact_name,
    s3_exact_addr,
    s3_name_tokens,
    s3_addr_tokens
)


# ============================================================
# RESULTS
# ============================================================

print("\n")
print("=" * 65)
print("V4 UNIQUE-CANDIDATE VOLUME")
print("=" * 65)

print("\nS2")
print("-" * 45)
print("Average :", round(s2_counts.mean(), 2))
print("Median  :", round(np.median(s2_counts), 2))
print("P90     :", round(np.percentile(s2_counts, 90), 2))
print("P95     :", round(np.percentile(s2_counts, 95), 2))
print("P99     :", round(np.percentile(s2_counts, 99), 2))
print("Maximum :", int(s2_counts.max()))

print("\nS3")
print("-" * 45)
print("Average :", round(s3_counts.mean(), 2))
print("Median  :", round(np.median(s3_counts), 2))
print("P90     :", round(np.percentile(s3_counts, 90), 2))
print("P95     :", round(np.percentile(s3_counts, 95), 2))
print("P99     :", round(np.percentile(s3_counts, 99), 2))
print("Maximum :", int(s3_counts.max()))


# Weighted average
avg_candidates = (
    s2_counts.mean() * len(s2)
    +
    s3_counts.mean() * len(s3)
) / (
    len(s2) + len(s3)
)

estimated_total = (
    avg_candidates *
    len(s1)
)

print("\n")
print("=" * 65)
print("TEST-SCALE ESTIMATE")
print("=" * 65)

print(
    "Weighted average candidates/S1:",
    round(avg_candidates, 2)
)

print(
    "Estimated total candidate pairs:",
    f"{estimated_total:,.0f}"
)

print(
    "Estimated million candidates:",
    round(estimated_total / 1e6, 2)
)

print("=" * 65)

Loading S1...
S1 sample: 10000
Normalizing S1...

Loading S2...
S2 sample: 100000

Loading S3...
S3 sample: 100000

Building S2 indexes...
Building S3 indexes...

Evaluating S2...
S2: 1000 / 10000
S2: 2000 / 10000
S2: 3000 / 10000
S2: 4000 / 10000
S2: 5000 / 10000
S2: 6000 / 10000
S2: 7000 / 10000
S2: 8000 / 10000
S2: 9000 / 10000
S2: 10000 / 10000

Evaluating S3...
S3: 1000 / 10000
S3: 2000 / 10000
S3: 3000 / 10000
S3: 4000 / 10000
S3: 5000 / 10000
S3: 6000 / 10000
S3: 7000 / 10000
S3: 8000 / 10000
S3: 9000 / 10000
S3: 10000 / 10000


=================================================================
V4 UNIQUE-CANDIDATE VOLUME
=================================================================

S2
---------------------------------------------
Average : 5348.97
Median  : 3758.5
P90     : 13541.3
P95     : 16480.25
P99     : 20172.71
Maximum : 25846

S3
---------------------------------------------
Average : 4976.62
Median  : 2968.5
P90     : 13174.2
P95     : 15405.05
P99     : 19104.15
Maximum : 23679


=================================================================
TEST-SCALE ESTIMATE
=================================================================
Weighted average candidates/S1: 5162.8
Estimated total candidate pairs: 8,944,769,674
Estimated million candidates: 8944.77
=================================================================

In [ ]:
import pandas as pd
import numpy as np
import re
import unicodedata
from collections import defaultdict

ROOT = "/content/amazon_ml_challenge/student_resource"

S1_PATH = f"{ROOT}/dataset/test/test_source1.tsv"
S2_PATH = f"{ROOT}/dataset/test/test_source2.tsv"
S3_PATH = f"{ROOT}/dataset/test/test_source3.tsv"

print("Loading S1...")
test_s1 = pd.read_csv(S1_PATH, sep="\t")
print("S1:", len(test_s1))

print("Loading S2 sample...")
test_s2 = pd.read_csv(S2_PATH, sep="\t", nrows=100000)
print("S2:", len(test_s2))

print("Loading S3 sample...")
test_s3 = pd.read_csv(S3_PATH, sep="\t", nrows=100000)
print("S3:", len(test_s3))

# 10k S1 sample
s1 = test_s1.sample(n=10000, random_state=42).copy()

print("\nS1 sample:", len(s1))
print("Ready.")

Loading S1...
S1: 1732544
Loading S2 sample...
S2: 100000
Loading S3 sample...
S3: 100000

S1 sample: 10000
Ready.

In [ ]:
# ============================================================
# RULE-BY-RULE CANDIDATE VOLUME
# ============================================================

import re
import unicodedata
import numpy as np
from collections import defaultdict

def norm(text):
    if pd.isna(text):
        return ""
    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def toks(text):
    return set(text.split()) if text else set()


# ------------------------------------------------------------
# Normalize
# ------------------------------------------------------------

print("Normalizing...")

for df in [s1, test_s2, test_s3]:
    df["name_n"] = df["business_name"].map(norm)
    df["addr_n"] = df["business_address"].map(norm)
    df["country_n"] = df["country"].map(norm)

print("Normalization complete.")


# ------------------------------------------------------------
# Build indexes
# ------------------------------------------------------------

def build_indexes(df):

    name_country = defaultdict(set)
    addr_country = defaultdict(set)
    name_token = defaultdict(set)
    addr_token = defaultdict(set)

    for idx, row in df.iterrows():

        name = row["name_n"]
        addr = row["addr_n"]
        country = row["country_n"]

        if name:
            name_country[(name, country)].add(idx)

        if addr:
            addr_country[(addr, country)].add(idx)

        for token in toks(name):
            name_token[token].add(idx)

        for token in toks(addr):
            addr_token[token].add(idx)

    return (
        name_country,
        addr_country,
        name_token,
        addr_token
    )


print("\nBuilding S2 indexes...")
s2_indexes = build_indexes(test_s2)

print("Building S3 indexes...")
s3_indexes = build_indexes(test_s3)

print("Indexes ready.")


# ------------------------------------------------------------
# Candidate count for ONE rule
# ------------------------------------------------------------

def count_rule(s1_df, indexes, rule):

    name_country, addr_country, name_token, addr_token = indexes

    counts = []

    for counter, (_, row) in enumerate(s1_df.iterrows()):

        if counter % 1000 == 0:
            print(f"{rule}: {counter}/{len(s1_df)}")

        name = row["name_n"]
        addr = row["addr_n"]
        country = row["country_n"]

        candidates = set()

        # Exact name + country
        if rule == "exact_name":
            candidates.update(
                name_country.get((name, country), set())
            )

        # Exact address + country
        elif rule == "exact_address":
            candidates.update(
                addr_country.get((addr, country), set())
            )

        # >= 2 shared name tokens
        elif rule == "name_2tokens":

            overlap = defaultdict(int)

            for token in toks(name):
                for sid in name_token.get(token, []):
                    overlap[sid] += 1

            for sid, count in overlap.items():
                if count >= 2:
                    candidates.add(sid)

        # >= 2 shared address tokens
        elif rule == "address_2tokens":

            overlap = defaultdict(int)

            for token in toks(addr):
                for sid in addr_token.get(token, []):
                    overlap[sid] += 1

            for sid, count in overlap.items():
                if count >= 2:
                    candidates.add(sid)

        counts.append(len(candidates))

    return np.array(counts)


# ------------------------------------------------------------
# Run one rule at a time
# ------------------------------------------------------------

rules = [
    "exact_name",
    "exact_address",
    "name_2tokens",
    "address_2tokens"
]

results = {}

for rule in rules:

    print("\n" + "=" * 65)
    print("RULE:", rule)
    print("=" * 65)

    s2_counts = count_rule(
        s1,
        s2_indexes,
        rule
    )

    s3_counts = count_rule(
        s1,
        s3_indexes,
        rule
    )

    results[rule] = {
        "s2": s2_counts,
        "s3": s3_counts
    }

    print("\nS2")
    print("Average :", round(s2_counts.mean(), 2))
    print("Median  :", round(np.median(s2_counts), 2))
    print("P90     :", round(np.percentile(s2_counts, 90), 2))
    print("P95     :", round(np.percentile(s2_counts, 95), 2))
    print("P99     :", round(np.percentile(s2_counts, 99), 2))
    print("Maximum :", int(s2_counts.max()))

    print("\nS3")
    print("Average :", round(s3_counts.mean(), 2))
    print("Median  :", round(np.median(s3_counts), 2))
    print("P90     :", round(np.percentile(s3_counts, 90), 2))
    print("P95     :", round(np.percentile(s3_counts, 95), 2))
    print("P99     :", round(np.percentile(s3_counts, 99), 2))
    print("Maximum :", int(s3_counts.max()))

Normalizing...
Normalization complete.

Building S2 indexes...
Building S3 indexes...
Indexes ready.

=================================================================
RULE: exact_name
=================================================================
exact_name: 0/10000
exact_name: 1000/10000
exact_name: 2000/10000
exact_name: 3000/10000
exact_name: 4000/10000
exact_name: 5000/10000
exact_name: 6000/10000
exact_name: 7000/10000
exact_name: 8000/10000
exact_name: 9000/10000
exact_name: 0/10000
exact_name: 1000/10000
exact_name: 2000/10000
exact_name: 3000/10000
exact_name: 4000/10000
exact_name: 5000/10000
exact_name: 6000/10000
exact_name: 7000/10000
exact_name: 8000/10000
exact_name: 9000/10000

S2
Average : 0.06
Median  : 0.0
P90     : 0.0
P95     : 0.0
P99     : 1.0
Maximum : 5

S3
Average : 0.06
Median  : 0.0
P90     : 0.0
P95     : 1.0
P99     : 1.0
Maximum : 5

=================================================================
RULE: exact_address
=================================================================
exact_address: 0/10000
exact_address: 1000/10000
exact_address: 2000/10000
exact_address: 3000/10000
exact_address: 4000/10000
exact_address: 5000/10000
exact_address: 6000/10000
exact_address: 7000/10000
exact_address: 8000/10000
exact_address: 9000/10000
exact_address: 0/10000
exact_address: 1000/10000
exact_address: 2000/10000
exact_address: 3000/10000
exact_address: 4000/10000
exact_address: 5000/10000
exact_address: 6000/10000
exact_address: 7000/10000
exact_address: 8000/10000
exact_address: 9000/10000

S2
Average : 0.01
Median  : 0.0
P90     : 0.0
P95     : 0.0
P99     : 0.0
Maximum : 1

S3
Average : 0.0
Median  : 0.0
P90     : 0.0
P95     : 0.0
P99     : 0.0
Maximum : 1

=================================================================
RULE: name_2tokens
=================================================================
name_2tokens: 0/10000
name_2tokens: 1000/10000
name_2tokens: 2000/10000
name_2tokens: 3000/10000
name_2tokens: 4000/10000
name_2tokens: 5000/10000
name_2tokens: 6000/10000
name_2tokens: 7000/10000
name_2tokens: 8000/10000
name_2tokens: 9000/10000
name_2tokens: 0/10000
name_2tokens: 1000/10000
name_2tokens: 2000/10000
name_2tokens: 3000/10000
name_2tokens: 4000/10000
name_2tokens: 5000/10000
name_2tokens: 6000/10000
name_2tokens: 7000/10000
name_2tokens: 8000/10000
name_2tokens: 9000/10000

S2
Average : 1953.76
Median  : 62.0
P90     : 7385.0
P95     : 7529.0
P99     : 8122.0
Maximum : 8544

S3
Average : 2470.02
Median  : 65.0
P90     : 9536.0
P95     : 9634.0
P99     : 10156.0
Maximum : 10591

=================================================================
RULE: address_2tokens
=================================================================
address_2tokens: 0/10000
address_2tokens: 1000/10000
address_2tokens: 2000/10000
address_2tokens: 3000/10000
address_2tokens: 4000/10000
address_2tokens: 5000/10000
address_2tokens: 6000/10000
address_2tokens: 7000/10000
address_2tokens: 8000/10000
address_2tokens: 9000/10000
address_2tokens: 0/10000
address_2tokens: 1000/10000
address_2tokens: 2000/10000
address_2tokens: 3000/10000
address_2tokens: 4000/10000
address_2tokens: 5000/10000
address_2tokens: 6000/10000
address_2tokens: 7000/10000
address_2tokens: 8000/10000
address_2tokens: 9000/10000

S2
Average : 3540.02
Median  : 2313.0
P90     : 9632.6
P95     : 12449.05
P99     : 16917.2
Maximum : 23030

S3
Average : 2690.6
Median  : 1230.0
P90     : 7229.8
P95     : 9790.05
P99     : 13659.05
Maximum : 19582

In [ ]:
# ============================================================
# SELECTIVE RARE-TOKEN CANDIDATE VOLUME
# ============================================================

from collections import defaultdict
import numpy as np

# ------------------------------------------------------------
# Build token frequencies in S2/S3
# ------------------------------------------------------------

def token_frequency(df, column):

    freq = defaultdict(int)

    for text in df[column]:
        for t in toks(text):
            freq[t] += 1

    return freq


print("Calculating S2 address token frequencies...")
s2_addr_freq = token_frequency(test_s2, "addr_n")

print("Calculating S3 address token frequencies...")
s3_addr_freq = token_frequency(test_s3, "addr_n")

print("Done.")

# ------------------------------------------------------------
# Candidate counter
# ------------------------------------------------------------

def selective_address_counts(
    s1_df,
    indexes,
    addr_freq,
    rarity_limit
):

    addr_token = indexes[3]

    counts = []

    for counter, (_, row) in enumerate(s1_df.iterrows()):

        if counter % 1000 == 0:
            print(
                f"limit={rarity_limit}: "
                f"{counter}/{len(s1_df)}"
            )

        address_tokens = toks(row["addr_n"])

        overlap = defaultdict(int)
        rare_shared = defaultdict(bool)

        for token in address_tokens:

            # Only use tokens that are not too common
            if addr_freq.get(token, 0) <= rarity_limit:

                for sid in addr_token.get(token, []):
                    overlap[sid] += 1
                    rare_shared[sid] = True

        count = 0

        for sid, shared_count in overlap.items():

            if shared_count >= 2 and rare_shared[sid]:
                count += 1

        counts.append(count)

    return np.array(counts)


limits = [
    500,
    1000,
    2000,
    5000,
    10000
]

volume_results = {}

for limit in limits:

    print("\n" + "=" * 70)
    print("RARITY LIMIT:", limit)
    print("=" * 70)

    s2_counts = selective_address_counts(
        s1,
        s2_indexes,
        s2_addr_freq,
        limit
    )

    s3_counts = selective_address_counts(
        s1,
        s3_indexes,
        s3_addr_freq,
        limit
    )

    volume_results[limit] = {
        "s2": s2_counts,
        "s3": s3_counts
    }

    print("\nS2")
    print("Average :", round(s2_counts.mean(), 2))
    print("Median  :", round(np.median(s2_counts), 2))
    print("P90     :", round(np.percentile(s2_counts, 90), 2))
    print("P95     :", round(np.percentile(s2_counts, 95), 2))
    print("P99     :", round(np.percentile(s2_counts, 99), 2))
    print("Maximum :", int(s2_counts.max()))

    print("\nS3")
    print("Average :", round(s3_counts.mean(), 2))
    print("Median  :", round(np.median(s3_counts), 2))
    print("P90     :", round(np.percentile(s3_counts, 90), 2))
    print("P95     :", round(np.percentile(s3_counts, 95), 2))
    print("P99     :", round(np.percentile(s3_counts, 99), 2))
    print("Maximum :", int(s3_counts.max()))

    weighted_avg = (
        s2_counts.mean() * 0.5 +
        s3_counts.mean() * 0.5
    )

    estimated_total = weighted_avg * 1_732_544

    print(
        "\nEstimated total full-test candidates:",
        f"{estimated_total:,.0f}"
    )

Calculating S2 address token frequencies...
Calculating S3 address token frequencies...
Done.

======================================================================
RARITY LIMIT: 500
======================================================================
limit=500: 0/10000
limit=500: 1000/10000
limit=500: 2000/10000
limit=500: 3000/10000
limit=500: 4000/10000
limit=500: 5000/10000
limit=500: 6000/10000
limit=500: 7000/10000
limit=500: 8000/10000
limit=500: 9000/10000
limit=500: 0/10000
limit=500: 1000/10000
limit=500: 2000/10000
limit=500: 3000/10000
limit=500: 4000/10000
limit=500: 5000/10000
limit=500: 6000/10000
limit=500: 7000/10000
limit=500: 8000/10000
limit=500: 9000/10000

S2
Average : 16.3
Median  : 1.0
P90     : 36.0
P95     : 74.0
P99     : 270.0
Maximum : 474

S3
Average : 23.7
Median  : 4.0
P90     : 63.0
P95     : 128.0
P99     : 308.02
Maximum : 443

Estimated total full-test candidates: 34,647,848

======================================================================
RARITY LIMIT: 1000
======================================================================
limit=1000: 0/10000
limit=1000: 1000/10000
limit=1000: 2000/10000
limit=1000: 3000/10000
limit=1000: 4000/10000
limit=1000: 5000/10000
limit=1000: 6000/10000
limit=1000: 7000/10000
limit=1000: 8000/10000
limit=1000: 9000/10000
limit=1000: 0/10000
limit=1000: 1000/10000
limit=1000: 2000/10000
limit=1000: 3000/10000
limit=1000: 4000/10000
limit=1000: 5000/10000
limit=1000: 6000/10000
limit=1000: 7000/10000
limit=1000: 8000/10000
limit=1000: 9000/10000

S2
Average : 47.62
Median  : 8.0
P90     : 130.0
P95     : 303.05
P99     : 547.02
Maximum : 755

S3
Average : 65.87
Median  : 11.0
P90     : 213.0
P95     : 302.1
P99     : 697.0
Maximum : 1226

Estimated total full-test candidates: 98,315,548

======================================================================
RARITY LIMIT: 2000
======================================================================
limit=2000: 0/10000
limit=2000: 1000/10000
limit=2000: 2000/10000
limit=2000: 3000/10000
limit=2000: 4000/10000
limit=2000: 5000/10000
limit=2000: 6000/10000
limit=2000: 7000/10000
limit=2000: 8000/10000
limit=2000: 9000/10000
limit=2000: 0/10000
limit=2000: 1000/10000
limit=2000: 2000/10000
limit=2000: 3000/10000
limit=2000: 4000/10000
limit=2000: 5000/10000
limit=2000: 6000/10000
limit=2000: 7000/10000
limit=2000: 8000/10000
limit=2000: 9000/10000

S2
Average : 348.49
Median  : 82.0
P90     : 1544.0
P95     : 1801.0
P99     : 1936.0
Maximum : 2107

S3
Average : 355.33
Median  : 68.0
P90     : 1642.0
P95     : 1972.0
P99     : 2071.0
Maximum : 2255

Estimated total full-test candidates: 609,698,173

======================================================================
RARITY LIMIT: 5000
======================================================================
limit=5000: 0/10000
limit=5000: 1000/10000
limit=5000: 2000/10000
limit=5000: 3000/10000
limit=5000: 4000/10000
limit=5000: 5000/10000
limit=5000: 6000/10000
limit=5000: 7000/10000
limit=5000: 8000/10000
limit=5000: 9000/10000
limit=5000: 0/10000
limit=5000: 1000/10000
limit=5000: 2000/10000
limit=5000: 3000/10000
limit=5000: 4000/10000
limit=5000: 5000/10000
limit=5000: 6000/10000
limit=5000: 7000/10000
limit=5000: 8000/10000
limit=5000: 9000/10000

S2
Average : 981.46
Median  : 558.0
P90     : 2437.0
P95     : 2718.05
P99     : 3620.0
Maximum : 7050

S3
Average : 687.64
Median  : 288.0
P90     : 1997.1
P95     : 2282.0
P99     : 2726.0
Maximum : 5040

Estimated total full-test candidates: 1,445,890,784

======================================================================
RARITY LIMIT: 10000
======================================================================
limit=10000: 0/10000
limit=10000: 1000/10000
limit=10000: 2000/10000
limit=10000: 3000/10000
limit=10000: 4000/10000
limit=10000: 5000/10000
limit=10000: 6000/10000
limit=10000: 7000/10000
limit=10000: 8000/10000
limit=10000: 9000/10000
limit=10000: 0/10000
limit=10000: 1000/10000
limit=10000: 2000/10000
limit=10000: 3000/10000
limit=10000: 4000/10000
limit=10000: 5000/10000
limit=10000: 6000/10000
limit=10000: 7000/10000
limit=10000: 8000/10000
limit=10000: 9000/10000

S2
Average : 2202.68
Median  : 1700.0
P90     : 5393.1
P95     : 6189.1
P99     : 8407.21
Maximum : 13939

S3
Average : 1589.8
Median  : 606.5
P90     : 4561.4
P95     : 5732.2
P99     : 7041.23
Maximum : 11336

Estimated total full-test candidates: 3,285,317,589

In [ ]:
import os

print("Checking saved ML files...")

ML_DIR = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml"

for f in os.listdir(ML_DIR):
    print(f)

Checking saved ML files...
ml_features_v3_1000.pkl
catboost_v1_v3_1000.cbm

In [ ]:
import pickle

FEATURE_PATH = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/ml_features_v3_1000.pkl"

with open(FEATURE_PATH, "rb") as f:
    data = pickle.load(f)

print(type(data))

if hasattr(data, "shape"):
    print("Shape:", data.shape)

if hasattr(data, "columns"):
    print("\nColumns:")
    print(list(data.columns))

if isinstance(data, dict):
    print("\nDictionary keys:")
    print(data.keys())

<class 'pandas.core.frame.DataFrame'>
Shape: (208971, 19)

Columns:
['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard', 'address_jaccard', 'shared_name_token_count', 'shared_address_token_count', 'shared_address_number_count', 'name_length_diff', 'address_length_diff', 'name_length_ratio', 'address_length_ratio', 'source1_entity_id', 'matched_entity_id', 'label']

In [ ]:
import pickle
import pandas as pd

FEATURE_PATH = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/ml_features_v3_1000.pkl"

with open(FEATURE_PATH, "rb") as f:
    df_v3 = pickle.load(f)

print("Shape:", df_v3.shape)

print("\nLabels:")
print(df_v3["label"].value_counts())

print("\nS1 entities:")
print(df_v3["source1_entity_id"].nunique())

print("\nMatched entities:")
print(df_v3["matched_entity_id"].nunique())

print("\nCandidate pairs per S1:")
counts = df_v3.groupby("source1_entity_id").size()

print("Average:", counts.mean())
print("Median :", counts.median())
print("P90    :", counts.quantile(0.90))
print("P95    :", counts.quantile(0.95))
print("P99    :", counts.quantile(0.99))
print("Max    :", counts.max())

print("\nPositive pairs per S1:")
positive_counts = (
    df_v3[df_v3["label"] == 1]
    .groupby("source1_entity_id")
    .size()
)

print("Average:", positive_counts.mean())
print("Median :", positive_counts.median())
print("Max    :", positive_counts.max())

Shape: (208971, 19)

Labels:
label
0    185752
1     23219
Name: count, dtype: int64

S1 entities:
7654

Matched entities:
204703

Candidate pairs per S1:
Average: 27.30219493075516
Median : 20.0
P90    : 61.0
P95    : 74.0
P99    : 101.0
Max    : 182

Positive pairs per S1:
Average: 3.2537836322869955
Median : 3.0
Max    : 11

In [ ]:
# ============================================================
# ANALYZE V3 POSITIVE vs NEGATIVE PAIRS
# ============================================================

import pandas as pd
import numpy as np

df = df_v3.copy()

features = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_ratio",
    "address_length_ratio"
]

print("=" * 70)
print("V3 FEATURE SEPARATION")
print("=" * 70)

for f in features:

    pos = df.loc[df["label"] == 1, f]
    neg = df.loc[df["label"] == 0, f]

    print(f"\n{f}")
    print("-" * 50)

    print(
        "Positive: "
        f"mean={pos.mean():.4f}, "
        f"median={pos.median():.4f}, "
        f"P10={pos.quantile(.10):.4f}, "
        f"P90={pos.quantile(.90):.4f}"
    )

    print(
        "Negative: "
        f"mean={neg.mean():.4f}, "
        f"median={neg.median():.4f}, "
        f"P10={neg.quantile(.10):.4f}, "
        f"P90={neg.quantile(.90):.4f}"
    )


# ------------------------------------------------------------
# Simple rule coverage
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("POSITIVE COVERAGE OF SIMPLE BLOCKING RULES")
print("=" * 70)

pos = df[df["label"] == 1]

rules = {
    "name_exact": pos["name_exact"] == 1,

    "address_exact": pos["address_exact"] == 1,

    "name_2tokens":
        pos["shared_name_token_count"] >= 2,

    "address_2tokens":
        pos["shared_address_token_count"] >= 2,

    "name_similarity_0.70":
        pos["name_similarity"] >= 0.70,

    "address_similarity_0.70":
        pos["address_similarity"] >= 0.70,

    "address_2tokens_AND_number":
        (
            (pos["shared_address_token_count"] >= 2) &
            (pos["shared_address_number_count"] >= 1)
        ),

    "name_2tokens_AND_sim_0.70":
        (
            (pos["shared_name_token_count"] >= 2) &
            (pos["name_similarity"] >= 0.70)
        ),

    "country_AND_address_2tokens":
        (
            (pos["country_exact"] == 1) &
            (pos["shared_address_token_count"] >= 2)
        ),

    "country_AND_name_2tokens":
        (
            (pos["country_exact"] == 1) &
            (pos["shared_name_token_count"] >= 2)
        )
}

for name, mask in rules.items():

    print(
        f"{name:40s} "
        f"{mask.sum():6d} / {len(pos):6d} "
        f"= {mask.mean()*100:6.2f}%"
    )

======================================================================
V3 FEATURE SEPARATION
======================================================================

name_exact
--------------------------------------------------
Positive: mean=0.2613, median=0.0000, P10=0.0000, P90=1.0000
Negative: mean=0.0208, median=0.0000, P10=0.0000, P90=0.0000

address_exact
--------------------------------------------------
Positive: mean=0.1398, median=0.0000, P10=0.0000, P90=1.0000
Negative: mean=0.0003, median=0.0000, P10=0.0000, P90=0.0000

country_exact
--------------------------------------------------
Positive: mean=1.0000, median=1.0000, P10=1.0000, P90=1.0000
Negative: mean=1.0000, median=1.0000, P10=1.0000, P90=1.0000

name_similarity
--------------------------------------------------
Positive: mean=0.8138, median=0.8889, P10=0.5556, P90=1.0000
Negative: mean=0.3166, median=0.2857, P10=0.1290, P90=0.5294

address_similarity
--------------------------------------------------
Positive: mean=0.7889, median=0.8552, P10=0.5000, P90=1.0000
Negative: mean=0.4017, median=0.3889, P10=0.2466, P90=0.5763

name_token_overlap
--------------------------------------------------
Positive: mean=0.7852, median=1.0000, P10=0.0000, P90=1.0000
Negative: mean=0.1103, median=0.0000, P10=0.0000, P90=0.4000

address_token_overlap
--------------------------------------------------
Positive: mean=0.8299, median=0.8571, P10=0.6000, P90=1.0000
Negative: mean=0.2425, median=0.2000, P10=0.0833, P90=0.4286

name_jaccard
--------------------------------------------------
Positive: mean=0.6496, median=0.6667, P10=0.0000, P90=1.0000
Negative: mean=0.0689, median=0.0000, P10=0.0000, P90=0.2000

address_jaccard
--------------------------------------------------
Positive: mean=0.6821, median=0.6923, P10=0.3750, P90=1.0000
Negative: mean=0.1267, median=0.1000, P10=0.0357, P90=0.2500

shared_name_token_count
--------------------------------------------------
Positive: mean=2.6508, median=3.0000, P10=0.0000, P90=4.0000
Negative: mean=0.3675, median=0.0000, P10=0.0000, P90=1.0000

shared_address_token_count
--------------------------------------------------
Positive: mean=6.4447, median=5.0000, P10=3.0000, P90=12.0000
Negative: mean=1.8252, median=1.0000, P10=1.0000, P90=4.0000

shared_address_number_count
--------------------------------------------------
Positive: mean=1.0384, median=1.0000, P10=0.0000, P90=2.0000
Negative: mean=0.2287, median=0.0000, P10=0.0000, P90=1.0000

name_length_ratio
--------------------------------------------------
Positive: mean=0.8739, median=0.9412, P10=0.6316, P90=1.0000
Negative: mean=0.7029, median=0.7241, P10=0.4231, P90=0.9524

address_length_ratio
--------------------------------------------------
Positive: mean=0.8444, median=0.8936, P10=0.6667, P90=1.0000
Negative: mean=0.7757, median=0.8000, P10=0.5641, P90=0.9630

======================================================================
POSITIVE COVERAGE OF SIMPLE BLOCKING RULES
======================================================================
name_exact                                 6067 /  23219 =  26.13%
address_exact                              3247 /  23219 =  13.98%
name_2tokens                              19215 /  23219 =  82.76%
address_2tokens                           22563 /  23219 =  97.17%
name_similarity_0.70                      18694 /  23219 =  80.51%
address_similarity_0.70                   17343 /  23219 =  74.69%
address_2tokens_AND_number                18082 /  23219 =  77.88%
name_2tokens_AND_sim_0.70                 17153 /  23219 =  73.87%
country_AND_address_2tokens               22563 /  23219 =  97.17%
country_AND_name_2tokens                  19215 /  23219 =  82.76%

In [ ]:
V5_MODEL = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/v5_model.cbm"

In [ ]:
import os

print("Searching for Submission 3 code...")

matches = []

for root, dirs, files in os.walk("/content"):
    # Skip huge/unimportant folders
    dirs[:] = [
        d for d in dirs
        if d not in ["drive", ".cache", "__pycache__"]
    ]

    for file in files:
        if file.endswith((".py", ".ipynb")):
            path = os.path.join(root, file)

            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    text = f.read()

                if (
                    "matching_results_submission3" in text
                    or "submission3" in text.lower()
                    or "CatBoost" in text
                ):
                    matches.append(path)

            except:
                pass

print("\nFOUND:")
for x in matches:
    print(x)

print("\nTotal:", len(matches))

Searching for Submission 3 code...

FOUND:

Total: 0

In [ ]:
print("Checking current Colab memory...\n")

for name, obj in list(globals().items()):

    if name.startswith("_"):
        continue

    name_low = name.lower()

    # Show likely ML / submission variables
    if any(x in name_low for x in [
        "candidate",
        "match",
        "model",
        "catboost",
        "feature",
        "submission",
        "test_s1",
        "test_s2",
        "test_s3"
    ]):
        try:
            print(
                name,
                "->",
                type(obj).__name__,
                getattr(obj, "shape", "")
            )
        except:
            print(name, "->", type(obj).__name__)

Checking current Colab memory...

matches -> list
estimate_token_candidates -> function
avg_token_candidates -> float64 ()
SequenceMatcher -> type
get_candidates -> function
avg_candidates -> float64 ()
test_s1 -> DataFrame (1732544, 4)
test_s2 -> DataFrame (100000, 7)
test_s3 -> DataFrame (100000, 7)
FEATURE_PATH -> str
features -> list
V5_MODEL -> str

In [ ]:
import inspect

print("get_candidates:")
print(inspect.signature(get_candidates))
print()
print(inspect.getsource(get_candidates))

get_candidates:
(row, exact_name, exact_addr, name_index, addr_index)

def get_candidates(
    row,
    exact_name,
    exact_addr,
    name_index,
    addr_index
):

    name = row["name_n"]
    addr = row["addr_n"]
    country = row["country_n"]

    name_ts = get_tokens(name)
    addr_ts = get_tokens(addr)

    candidates = set()

    # --------------------------------------------------------
    # Rule 1: exact name + country
    # --------------------------------------------------------

    if name:
        candidates.update(
            exact_name.get(
                (name, country),
                set()
            )
        )

    # --------------------------------------------------------
    # Rule 2: exact address + country
    # --------------------------------------------------------

    if addr:
        candidates.update(
            exact_addr.get(
                (addr, country),
                set()
            )
        )

    # --------------------------------------------------------
    # Rule 3:
    # >=2 shared NAME tokens
    # --------------------------------------------------------

    name_token_hits = defaultdict(int)

    for token in name_ts:

        for eid in name_index.get(
            (country, token),
            set()
        ):

            name_token_hits[eid] += 1

    for eid, count in name_token_hits.items():

        if count >= 2:
            candidates.add(eid)

    # --------------------------------------------------------
    # Rule 4:
    # >=2 shared ADDRESS tokens
    # --------------------------------------------------------

    addr_token_hits = defaultdict(int)

    for token in addr_ts:

        for eid in addr_index.get(
            (country, token),
            set()
        ):

            addr_token_hits[eid] += 1

    for eid, count in addr_token_hits.items():

        if count >= 2:
            candidates.add(eid)

    return candidates

In [ ]:
import pandas as pd

print("DataFrames currently in memory:\n")

for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):
        print(
            f"{name:35s} "
            f"shape={obj.shape} "
            f"columns={list(obj.columns)[:8]}"
        )

DataFrames currently in memory:

gt                                  shape=(2206821, 2) columns=['source1_entity_id', 'matched_entity_ids']
s1_head                             shape=(10000, 4) columns=['entity_id', 'business_name', 'business_address', 'country']
s1                                  shape=(10000, 7) columns=['entity_id', 'business_name', 'business_address', 'country', 'name_n', 'addr_n', 'country_n']
s1_10k                              shape=(10000, 4) columns=['entity_id', 'business_name', 'business_address', 'country']
s1_val                              shape=(2000, 4) columns=['entity_id', 'business_name', 'business_address', 'country']
s1_test                             shape=(1732544, 4) columns=['entity_id', 'business_name', 'business_address', 'country']
s1_sample                           shape=(10000, 7) columns=['entity_id', 'business_name', 'business_address', 'country', 'name_n', 'addr_n', 'country_n']
s2                                  shape=(100000, 7) columns=['entity_id', 'business_name', 'business_address', 'country', 'name_n', 'addr_n', 'country_n']
s3                                  shape=(100000, 7) columns=['entity_id', 'business_name', 'business_address', 'country', 'name_n', 'addr_n', 'country_n']
df                                  shape=(208971, 19) columns=['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard']
test_s1                             shape=(1732544, 4) columns=['entity_id', 'business_name', 'business_address', 'country']
test_s2                             shape=(100000, 7) columns=['entity_id', 'business_name', 'business_address', 'country', 'name_n', 'addr_n', 'country_n']
test_s3                             shape=(100000, 7) columns=['entity_id', 'business_name', 'business_address', 'country', 'name_n', 'addr_n', 'country_n']
data                                shape=(208971, 19) columns=['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard']
df_v3                               shape=(208971, 19) columns=['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard']
pos                                 shape=(23219, 19) columns=['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard']

In [ ]:
print("FEATURES:")
print(features)

print("\nV5 MODEL PATH:")
print(V5_MODEL)

print("\nOUTPUT FILES:")
import os

OUT = "/content/amazon_ml_challenge/student_resource/output"

for f in os.listdir(OUT):
    print(f)

FEATURES:
['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard', 'address_jaccard', 'shared_name_token_count', 'shared_address_token_count', 'shared_address_number_count', 'name_length_ratio', 'address_length_ratio']

V5 MODEL PATH:
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/v5_model.cbm

OUTPUT FILES:
matching_results_submission3.tsv
candidate_pairs_v2.tsv
matching_results.tsv
matching_results_v2.tsv

In [ ]:
import os

OUT = "/content/amazon_ml_challenge/student_resource/output"

for f in os.listdir(OUT):
    path = os.path.join(OUT, f)
    size_mb = os.path.getsize(path) / (1024 * 1024)
    print(f"{f:40s} {size_mb:,.2f} MB")

matching_results_submission3.tsv         41.26 MB
candidate_pairs_v2.tsv                   41.79 MB
matching_results.tsv                     41.26 MB
matching_results_v2.tsv                  41.79 MB

In [ ]:
import pandas as pd

path = "/content/amazon_ml_challenge/student_resource/output/candidate_pairs_v2.tsv"

cand = pd.read_csv(path, sep="\t", nrows=5)

print("Columns:")
print(list(cand.columns))

print("\nFirst 5 rows:")
display(cand)

Columns:
['source1_entity_id', 'candidate_entity_ids']

First 5 rows:

  source1_entity_id                    candidate_entity_ids
0      S1-714132312                                     NaN
1      S1-106407869                                     NaN
2      S1-156285671                                     NaN
3      S1-689823050                                     NaN
4      S1-921369899  S2-107533354,S2-808920974,S3-285097097

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

base = "/content/drive/My Drive"

for root, dirs, files in os.walk(base):
    for f in files:
        if f.startswith("V5_ML_Final") and f.endswith(".zip"):
            print(os.path.join(root, f))

/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final-20260925T182640Z-1-001.zip

In [ ]:
import zipfile
import os

zip_path = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final-20260925T182640Z-1-001.zip"

extract_path = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted successfully!")
print("\nFiles:")
for root, dirs, files in os.walk(extract_path):
    for f in files:
        print(os.path.join(root, f))

Extracted successfully!

Files:
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_threshold_predictions.csv
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_inference.py
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_feature_list.txt
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/V5_final_report.txt
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm
/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/ml_features_v3_1000.pkl

In [ ]:
V5_DIR = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final"

script_path = V5_DIR + "/v5_inference.py"

with open(script_path, "r", encoding="utf-8") as f:
    code = f.read()

print(code)

from catboost import CatBoostClassifier
import pandas as pd

MODEL_PATH = "/content/drive/MyDrive/V5_ML_Final/v5_model.cbm"

FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]

model = CatBoostClassifier()
model.load_model(MODEL_PATH)

def add_v5_features(df):
    X = df[FEATURES[:16]].copy()

    X["similarity_gap"] = (
        X["name_similarity"] - X["address_similarity"]
    ).abs()

    X["max_similarity"] = X[
        ["name_similarity", "address_similarity"]
    ].max(axis=1)

    X["similarity_product"] = (
        X["name_similarity"] * X["address_similarity"]
    )

    X["token_overlap_gap"] = (
        X["name_token_overlap"] - X["address_token_overlap"]
    ).abs()

    return X[FEATURES]

def predict_v5(candidate_features, threshold=0.60):
    X = add_v5_features(candidate_features)
    probability = model.predict_proba(X)[:, 1]
    prediction = (probability >= threshold).astype(int)
    return probability, prediction

In [ ]:
from catboost import CatBoostClassifier

V5_MODEL_PATH = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm"

FEATURES_16 = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio"
]

model_v5 = CatBoostClassifier()
model_v5.load_model(V5_MODEL_PATH)

X = df_v3[FEATURES_16].copy()

X["similarity_gap"] = (
    X["name_similarity"] - X["address_similarity"]
).abs()

X["max_similarity"] = X[
    ["name_similarity", "address_similarity"]
].max(axis=1)

X["similarity_product"] = (
    X["name_similarity"] * X["address_similarity"]
)

X["token_overlap_gap"] = (
    X["name_token_overlap"] - X["address_token_overlap"]
).abs()

FEATURES_20 = FEATURES_16 + [
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]

X = X[FEATURES_20]

probs = model_v5.predict_proba(X)[:, 1]

print("V5 loaded successfully")
print("Feature shape:", X.shape)
print("Predictions:", len(probs))
print("Probability range:", probs.min(), "to", probs.max())

V5 loaded successfully
Feature shape: (208971, 20)
Predictions: 208971
Probability range: 3.211570553559407e-08 to 0.9999931828208325

In [ ]:
# ============================================================
# SELECTIVE BLOCKER VOLUME TEST
# ============================================================

from collections import defaultdict
import numpy as np

# ------------------------------------------------------------
# Build token indexes
# ------------------------------------------------------------

def build_token_index(df, column):

    index = defaultdict(set)

    for idx, text in enumerate(df[column]):

        for token in toks(text):
            index[token].add(idx)

    return index


print("Building indexes...")

s2_name_index = build_token_index(test_s2, "name_n")
s2_addr_index = build_token_index(test_s2, "addr_n")

s3_name_index = build_token_index(test_s3, "name_n")
s3_addr_index = build_token_index(test_s3, "addr_n")

print("Indexes ready.")


# ------------------------------------------------------------
# Token frequencies
# ------------------------------------------------------------

def token_freq(df, column):

    freq = defaultdict(int)

    for text in df[column]:

        for token in toks(text):
            freq[token] += 1

    return freq


s2_name_freq = token_freq(test_s2, "name_n")
s2_addr_freq = token_freq(test_s2, "addr_n")

s3_name_freq = token_freq(test_s3, "name_n")
s3_addr_freq = token_freq(test_s3, "addr_n")


# ------------------------------------------------------------
# Candidate count
# ------------------------------------------------------------

def selective_candidates(
    row,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    name_limit,
    addr_limit,
    name_sim_threshold,
    addr_sim_threshold
):

    name1 = row["name_n"]
    addr1 = row["addr_n"]

    name_tokens = toks(name1)
    addr_tokens = toks(addr1)

    candidates = set()

    # --------------------------------------------------------
    # Name block
    # --------------------------------------------------------

    name_hits = defaultdict(int)

    for token in name_tokens:

        if name_freq.get(token, 999999999) <= name_limit:

            for eid in name_index.get(token, []):
                name_hits[eid] += 1

    for eid, count in name_hits.items():

        if count >= 2:

            # We only count here.
            # Similarity will be applied later during
            # actual feature generation.
            candidates.add(eid)

    # --------------------------------------------------------
    # Address block
    # --------------------------------------------------------

    addr_hits = defaultdict(int)

    for token in addr_tokens:

        if addr_freq.get(token, 999999999) <= addr_limit:

            for eid in addr_index.get(token, []):
                addr_hits[eid] += 1

    for eid, count in addr_hits.items():

        if count >= 2:
            candidates.add(eid)

    return candidates


# ------------------------------------------------------------
# Test configurations
# ------------------------------------------------------------

configs = [
    (500, 500),
    (500, 1000),
    (1000, 500),
    (1000, 1000),
]

for name_limit, addr_limit in configs:

    print("\n" + "=" * 70)
    print(
        f"NAME LIMIT={name_limit} | "
        f"ADDRESS LIMIT={addr_limit}"
    )
    print("=" * 70)

    s2_counts = []
    s3_counts = []

    for counter, (_, row) in enumerate(s1.iterrows()):

        if counter % 1000 == 0:
            print(f"{counter}/10000")

        s2_counts.append(
            len(
                selective_candidates(
                    row,
                    s2_name_index,
                    s2_addr_index,
                    s2_name_freq,
                    s2_addr_freq,
                    name_limit,
                    addr_limit,
                    0.70,
                    0.70
                )
            )
        )

        s3_counts.append(
            len(
                selective_candidates(
                    row,
                    s3_name_index,
                    s3_addr_index,
                    s3_name_freq,
                    s3_addr_freq,
                    name_limit,
                    addr_limit,
                    0.70,
                    0.70
                )
            )
        )

    s2_counts = np.array(s2_counts)
    s3_counts = np.array(s3_counts)

    avg = (s2_counts.mean() + s3_counts.mean()) / 2

    print("\nS2 average:", round(s2_counts.mean(), 2))
    print("S3 average:", round(s3_counts.mean(), 2))
    print("Combined average:", round(avg, 2))

    print(
        "Estimated full-test candidates:",
        f"{avg * 1_732_544:,.0f}"
    )

Building indexes...
Indexes ready.

======================================================================
NAME LIMIT=500 | ADDRESS LIMIT=500
======================================================================
0/10000
1000/10000
2000/10000
3000/10000
4000/10000
5000/10000
6000/10000
7000/10000
8000/10000
9000/10000

S2 average: 21.63
S3 average: 29.31
Combined average: 25.47
Estimated full-test candidates: 44,124,084

======================================================================
NAME LIMIT=500 | ADDRESS LIMIT=1000
======================================================================
0/10000
1000/10000
2000/10000
3000/10000
4000/10000
5000/10000
6000/10000
7000/10000
8000/10000
9000/10000

S2 average: 52.9
S3 average: 71.44
Combined average: 62.17
Estimated full-test candidates: 107,705,417

======================================================================
NAME LIMIT=1000 | ADDRESS LIMIT=500
======================================================================
0/10000
1000/10000
2000/10000
3000/10000
4000/10000
5000/10000
6000/10000
7000/10000
8000/10000
9000/10000

S2 average: 25.7
S3 average: 33.34
Combined average: 29.52
Estimated full-test candidates: 51,148,597

======================================================================
NAME LIMIT=1000 | ADDRESS LIMIT=1000
======================================================================
0/10000
1000/10000
2000/10000
3000/10000
4000/10000
5000/10000
6000/10000
7000/10000
8000/10000
9000/10000

S2 average: 56.95
S3 average: 75.45
Combined average: 66.2
Estimated full-test candidates: 114,696,319

In [ ]:
# ============================================================
# SELECTIVE BLOCKER WITH SIMILARITY
# ============================================================

def selective_candidates_v2(
    row,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    name_limit=500,
    addr_limit=500,
    name_sim=0.70,
    addr_sim=0.70
):

    name1 = row["name_n"]
    addr1 = row["addr_n"]

    name_tokens = toks(name1)
    addr_tokens = toks(addr1)

    candidates = set()

    # --------------------------------------------------------
    # Exact name / exact address
    # --------------------------------------------------------

    # These require country in the original indexes
    # and are handled separately below if available.

    # --------------------------------------------------------
    # Name: >=2 shared tokens + rare token
    # --------------------------------------------------------

    name_hits = defaultdict(int)

    for token in name_tokens:

        if name_freq.get(token, 999999999) <= name_limit:

            for eid in name_index.get(token, []):
                name_hits[eid] += 1

    for eid, count in name_hits.items():

        if count >= 2:
            candidates.add(eid)

    # --------------------------------------------------------
    # Address: >=2 shared tokens + rare token
    # --------------------------------------------------------

    addr_hits = defaultdict(int)

    for token in addr_tokens:

        if addr_freq.get(token, 999999999) <= addr_limit:

            for eid in addr_index.get(token, []):
                addr_hits[eid] += 1

    for eid, count in addr_hits.items():

        if count >= 2:
            candidates.add(eid)

    return candidates


# ------------------------------------------------------------
# First just calculate volume
# ------------------------------------------------------------

print("Testing 500/500 selective blocker...")

s2_counts = []
s3_counts = []

for counter, (_, row) in enumerate(s1.iterrows()):

    if counter % 1000 == 0:
        print(f"{counter}/10000")

    s2_counts.append(
        len(
            selective_candidates_v2(
                row,
                s2_name_index,
                s2_addr_index,
                s2_name_freq,
                s2_addr_freq,
                500,
                500
            )
        )
    )

    s3_counts.append(
        len(
            selective_candidates_v2(
                row,
                s3_name_index,
                s3_addr_index,
                s3_name_freq,
                s3_addr_freq,
                500,
                500
            )
        )
    )

s2_counts = np.array(s2_counts)
s3_counts = np.array(s3_counts)

print("\n" + "=" * 70)
print("500/500 SELECTIVE BLOCKER")
print("=" * 70)

print("\nS2")
print("Average:", s2_counts.mean())
print("Median :", np.median(s2_counts))
print("P90    :", np.percentile(s2_counts, 90))
print("P95    :", np.percentile(s2_counts, 95))
print("P99    :", np.percentile(s2_counts, 99))
print("Max    :", s2_counts.max())

print("\nS3")
print("Average:", s3_counts.mean())
print("Median :", np.median(s3_counts))
print("P90    :", np.percentile(s3_counts, 90))
print("P95    :", np.percentile(s3_counts, 95))
print("P99    :", np.percentile(s3_counts, 99))
print("Max    :", s3_counts.max())

Testing 500/500 selective blocker...
0/10000
1000/10000
2000/10000
3000/10000
4000/10000
5000/10000
6000/10000
7000/10000
8000/10000
9000/10000

======================================================================
500/500 SELECTIVE BLOCKER
======================================================================

S2
Average: 21.6279
Median : 3.0
P90    : 59.0
P95    : 106.0
P99    : 302.03000000000065
Max    : 539

S3
Average: 29.3077
Median : 7.0
P90    : 95.0
P95    : 136.0
P99    : 310.03000000000065
Max    : 513

In [ ]:
# ============================================================
# 500/500 + SIMILARITY FILTER
# ============================================================

from difflib import SequenceMatcher
import numpy as np

def sim(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


def selective_candidates_v3(
    row,
    source_df,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    name_limit=500,
    addr_limit=500,
    name_sim_threshold=0.70,
    addr_sim_threshold=0.70
):

    name1 = row["name_n"]
    addr1 = row["addr_n"]
    country1 = row["country_n"]

    name_tokens = toks(name1)
    addr_tokens = toks(addr1)

    candidates = set()

    # --------------------------------------------------------
    # NAME BLOCK
    # >=2 shared tokens
    # + at least one rare token
    # + name similarity >= 0.70
    # + same country
    # --------------------------------------------------------

    name_hits = defaultdict(int)

    for token in name_tokens:

        if name_freq.get(token, 999999999) <= name_limit:

            for eid in name_index.get(token, []):
                name_hits[eid] += 1

    for eid, count in name_hits.items():

        if count < 2:
            continue

        target = source_df.iloc[eid]

        if target["country_n"] != country1:
            continue

        if sim(name1, target["name_n"]) >= name_sim_threshold:
            candidates.add(eid)

    # --------------------------------------------------------
    # ADDRESS BLOCK
    # >=2 shared tokens
    # + at least one rare token
    # + address similarity >= 0.70
    # + same country
    # --------------------------------------------------------

    addr_hits = defaultdict(int)

    for token in addr_tokens:

        if addr_freq.get(token, 999999999) <= addr_limit:

            for eid in addr_index.get(token, []):
                addr_hits[eid] += 1

    for eid, count in addr_hits.items():

        if count < 2:
            continue

        target = source_df.iloc[eid]

        if target["country_n"] != country1:
            continue

        if sim(addr1, target["addr_n"]) >= addr_sim_threshold:
            candidates.add(eid)

    return candidates


# ------------------------------------------------------------
# Evaluate
# ------------------------------------------------------------

print("Testing 500/500 + similarity >= 0.70...")

s2_counts = []
s3_counts = []

for counter, (_, row) in enumerate(s1.iterrows()):

    if counter % 1000 == 0:
        print(f"{counter}/10000")

    s2_counts.append(
        len(
            selective_candidates_v3(
                row,
                test_s2,
                s2_name_index,
                s2_addr_index,
                s2_name_freq,
                s2_addr_freq
            )
        )
    )

    s3_counts.append(
        len(
            selective_candidates_v3(
                row,
                test_s3,
                s3_name_index,
                s3_addr_index,
                s3_name_freq,
                s3_addr_freq
            )
        )
    )


s2_counts = np.array(s2_counts)
s3_counts = np.array(s3_counts)

print("\n" + "=" * 70)
print("500/500 + SIMILARITY >= 0.70")
print("=" * 70)

print("\nS2")
print("Average:", round(s2_counts.mean(), 2))
print("Median :", round(np.median(s2_counts), 2))
print("P90    :", round(np.percentile(s2_counts, 90), 2))
print("P95    :", round(np.percentile(s2_counts, 95), 2))
print("P99    :", round(np.percentile(s2_counts, 99), 2))
print("Max    :", int(s2_counts.max()))

print("\nS3")
print("Average:", round(s3_counts.mean(), 2))
print("Median :", round(np.median(s3_counts), 2))
print("P90    :", round(np.percentile(s3_counts, 90), 2))
print("P95    :", round(np.percentile(s3_counts, 95), 2))
print("P99    :", round(np.percentile(s3_counts, 99), 2))
print("Max    :", int(s3_counts.max()))

combined_avg = (s2_counts.mean() + s3_counts.mean()) / 2

print("\nCombined average:", round(combined_avg, 2))

print(
    "Estimated full-test candidates:",
    f"{combined_avg * 1_732_544:,.0f}"
)

Testing 500/500 + similarity >= 0.70...
0/10000
1000/10000
2000/10000
3000/10000
4000/10000
5000/10000
6000/10000
7000/10000
8000/10000
9000/10000

======================================================================
500/500 + SIMILARITY >= 0.70
======================================================================

S2
Average: 3.31
Median : 0.0
P90    : 5.0
P95    : 16.0
P99    : 71.0
Max    : 142

S3
Average: 3.02
Median : 0.0
P90    : 4.0
P95    : 12.0
P99    : 67.0
Max    : 169

Combined average: 3.16
Estimated full-test candidates: 5,483,242

In [ ]:
# ============================================================
# OPTIMIZED THRESHOLD COMPARISON
# Candidate search happens ONCE per S1 row
# Similarities calculated ONCE per candidate
# ============================================================

from difflib import SequenceMatcher
import numpy as np

thresholds = [0.60, 0.65, 0.70, 0.75]

results = {
    0.60: [],
    0.65: [],
    0.70: [],
    0.75: []
}

def fast_sim(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


print("Starting optimized threshold comparison...")

for counter, (_, row) in enumerate(s1.iterrows()):

    if counter % 1000 == 0:
        print(f"{counter}/10000")

    name1 = row["name_n"]
    addr1 = row["addr_n"]
    country1 = row["country_n"]

    name_tokens = toks(name1)
    addr_tokens = toks(addr1)

    # ========================================================
    # S2 + S3 separately
    # ========================================================

    for source_df, name_index, addr_index, name_freq, addr_freq, source_key in [
        (
            test_s2,
            s2_name_index,
            s2_addr_index,
            s2_name_freq,
            s2_addr_freq,
            "s2"
        ),
        (
            test_s3,
            s3_name_index,
            s3_addr_index,
            s3_name_freq,
            s3_addr_freq,
            "s3"
        )
    ]:

        name_hits = defaultdict(int)
        addr_hits = defaultdict(int)

        # ----------------------------------------------------
        # Build NAME candidates
        # ----------------------------------------------------

        for token in name_tokens:

            if name_freq.get(token, 999999999) <= 500:

                for eid in name_index.get(token, []):
                    name_hits[eid] += 1

        # ----------------------------------------------------
        # Build ADDRESS candidates
        # ----------------------------------------------------

        for token in addr_tokens:

            if addr_freq.get(token, 999999999) <= 500:

                for eid in addr_index.get(token, []):
                    addr_hits[eid] += 1

        candidate_ids = set()

        # Only candidates with >=2 shared tokens
        candidate_ids.update(
            eid for eid, count in name_hits.items()
            if count >= 2
        )

        candidate_ids.update(
            eid for eid, count in addr_hits.items()
            if count >= 2
        )

        # ----------------------------------------------------
        # Calculate similarities ONCE
        # ----------------------------------------------------

        candidate_scores = []

        for eid in candidate_ids:

            target = source_df.iloc[eid]

            # Same country
            if target["country_n"] != country1:
                continue

            name_sim = 0.0
            addr_sim = 0.0

            if name_hits.get(eid, 0) >= 2:
                name_sim = fast_sim(
                    name1,
                    target["name_n"]
                )

            if addr_hits.get(eid, 0) >= 2:
                addr_sim = fast_sim(
                    addr1,
                    target["addr_n"]
                )

            candidate_scores.append(
                (name_sim, addr_sim)
            )

        # ----------------------------------------------------
        # Count all thresholds from same similarity values
        # ----------------------------------------------------

        for threshold in thresholds:

            count = sum(
                1
                for name_sim, addr_sim in candidate_scores
                if name_sim >= threshold
                or addr_sim >= threshold
            )

            results[threshold].append(
                (source_key, count)
            )


print("\n" + "=" * 75)
print("OPTIMIZED THRESHOLD COMPARISON")
print("=" * 75)

for threshold in thresholds:

    s2 = np.array([
        count
        for source, count in results[threshold]
        if source == "s2"
    ])

    s3 = np.array([
        count
        for source, count in results[threshold]
        if source == "s3"
    ])

    avg = (s2.mean() + s3.mean()) / 2

    estimated = avg * 1_732_544

    print(f"\nSimilarity >= {threshold:.2f}")
    print("-" * 45)
    print("S2 average:", round(s2.mean(), 2))
    print("S3 average:", round(s3.mean(), 2))
    print("Combined average:", round(avg, 2))
    print("Estimated full candidates:",
          f"{estimated:,.0f}")

Starting optimized threshold comparison...
0/10000
1000/10000
2000/10000
3000/10000
4000/10000
5000/10000
6000/10000
7000/10000
8000/10000
9000/10000

===========================================================================
OPTIMIZED THRESHOLD COMPARISON
===========================================================================

Similarity >= 0.60
---------------------------------------------
S2 average: 7.36
S3 average: 6.55
Combined average: 6.96
Estimated full candidates: 12,051,923

Similarity >= 0.65
---------------------------------------------
S2 average: 4.99
S3 average: 4.48
Combined average: 4.74
Estimated full candidates: 8,210,786

Similarity >= 0.70
---------------------------------------------
S2 average: 3.31
S3 average: 3.02
Combined average: 3.16
Estimated full candidates: 5,483,242

Similarity >= 0.75
---------------------------------------------
S2 average: 1.96
S3 average: 1.85
Combined average: 1.9
Estimated full candidates: 3,298,244

In [ ]:
# Safely inspect important variables currently in memory

names = list(globals().keys())

for name in names:
    if any(x in name.lower() for x in [
        "train", "s1", "s2", "s3", "index", "freq", "gt"
    ]):
        obj = globals()[name]

        try:
            if isinstance(obj, pd.DataFrame):
                print(f"{name:30} DataFrame {obj.shape}")
            elif isinstance(obj, dict):
                print(f"{name:30} dict ({len(obj):,} entries)")
        except:
            pass

gt                             DataFrame (2206821, 2)
s1_head                        DataFrame (10000, 4)
s1                             DataFrame (10000, 7)
s1_10k                         DataFrame (10000, 4)
s1_val                         DataFrame (2000, 4)
gt_lookup                      dict (2,000 entries)
s1_lookup                      dict (2,000 entries)
name_freq                      dict (50,667 entries)
addr_freq                      dict (76,714 entries)
s2_hits                        dict (6 entries)
s3_hits                        dict (6 entries)
s1row                          dict (3 entries)
s1_test                        DataFrame (1732544, 4)
s1_sample                      DataFrame (10000, 7)
s2_name_pairs                  dict (287,859 entries)
s2_addr_pairs                  dict (1,616,515 entries)
s3_name_pairs                  dict (307,472 entries)
s3_addr_pairs                  dict (1,497,719 entries)
name_freq_fast                 dict (3,495 entries)
addr_freq_fast                 dict (5,973 entries)
s2_exact_name                  dict (98,204 entries)
s2_exact_addr                  dict (96,859 entries)
s2_name_tokens                 dict (52,931 entries)
s2_addr_tokens                 dict (88,258 entries)
s2_lookup                      dict (100,000 entries)
s3_exact_name                  dict (98,396 entries)
s3_exact_addr                  dict (96,952 entries)
s3_name_tokens                 dict (55,200 entries)
s3_addr_tokens                 dict (83,129 entries)
s3_lookup                      dict (100,000 entries)
test_s1                        DataFrame (1732544, 4)
test_s2                        DataFrame (100000, 7)
test_s3                        DataFrame (100000, 7)
s2_addr_freq                   dict (81,828 entries)
s3_addr_freq                   dict (76,714 entries)
val_name_freq                  dict (0 entries)
val_addr_freq                  dict (0 entries)
s2_name_index                  dict (48,952 entries)
s2_addr_index                  dict (81,828 entries)
s3_name_index                  dict (50,667 entries)
s3_addr_index                  dict (76,714 entries)
s2_name_freq                   dict (48,952 entries)
s3_name_freq                   dict (50,667 entries)
name_index                     dict (50,667 entries)
addr_index                     dict (76,714 entries)

In [ ]:
print("s1_val sample:")
print(s1_val.head(2))

print("\nGT sample:")
for k, v in list(gt_lookup.items())[:3]:
    print("S1:", k)
    print("GT :", v)

print("\nDictionary samples:")

for name in [
    "s2_name_pairs",
    "s2_addr_pairs",
    "s3_name_pairs",
    "s3_addr_pairs"
]:
    d = globals()[name]

    print(f"\n{name}")
    print("length:", len(d))

    for k, v in list(d.items())[:2]:
        print("key  :", k)
        print("value:", v)

s1_val sample:
            entity_id                business_name  \
683306   S1-549264353       Mountain Health Center
1905595  S1-219672719  Beauchamp, Rice & Henderson

                              business_address country
683306   4 Whitmore Street, Lexington City, VA      US
1905595             472445 610 Road, Watts, OK      US

GT sample:
S1: S1-708400226
GT : ['S2-11447624', 'S2-737021373', 'S2-636078522', 'S3-952283138', 'S3-654593788', 'S3-614607391', 'S3-508757891', 'S3-729109395']
S1: S1-219765772
GT : ['S2-73475891', 'S2-359968183', 'S3-363685397', 'S3-985947781']
S1: S1-106966123
GT : ['S2-236522713', 'S2-224711873', 'S2-278888692', 'S2-619602212', 'S3-560100668']

Dictionary samples:

s2_name_pairs
length: 287859
key  : ('india', 'future', 'limited')
value: 43
key  : ('india', 'future', 'public')
value: 6

s2_addr_pairs
length: 1616515
key  : ('india', '1977', '1st')
value: 1
key  : ('india', '1977', '32')
value: 1

s3_name_pairs
length: 307472
key  : ('india', 'இன', 'ஜ')
value: 14
key  : ('india', 'இன', 'ட')
value: 73

s3_addr_pairs
length: 1497719
key  : ('india', '75', 'no')
value: 77
key  : ('india', '75', 'rd')
value: 29

In [ ]:
# ============================================================
# COUNT UNIQUE TRUE MATCHES IN THE 2,000-ROW VALIDATION SET
# ============================================================

all_gt_ids = []

for matches in gt_lookup.values():
    all_gt_ids.extend(matches)

s2_gt_ids = {
    x for x in all_gt_ids
    if x.startswith("S2-")
}

s3_gt_ids = {
    x for x in all_gt_ids
    if x.startswith("S3-")
}

print("Validation S1 rows :", len(gt_lookup))
print("Unique S2 true IDs :", len(s2_gt_ids))
print("Unique S3 true IDs :", len(s3_gt_ids))
print("Total unique true IDs:", len(s2_gt_ids) + len(s3_gt_ids))

Validation S1 rows : 2000
Unique S2 true IDs : 3341
Unique S3 true IDs : 3634
Total unique true IDs: 6975

In [ ]:
# ============================================================
# LOAD ONLY THE 6,975 TRUE S2/S3 ENTITIES
# FROM THE TRAINING DATA
# ============================================================

import pandas as pd

s2_needed = set(s2_gt_ids)
s3_needed = set(s3_gt_ids)

print("Looking for:")
print("S2:", len(s2_needed))
print("S3:", len(s3_needed))

train_s2_path = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source2.tsv"
train_s3_path = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source3.tsv"

# ------------------------------------------------------------
# Read S2 in chunks
# ------------------------------------------------------------

s2_true_parts = []

for chunk in pd.read_csv(
    train_s2_path,
    sep="\t",
    chunksize=200_000,
    dtype=str
):
    found = chunk[
        chunk["entity_id"].isin(s2_needed)
    ]

    if len(found):
        s2_true_parts.append(found)

    if sum(len(x) for x in s2_true_parts) >= len(s2_needed):
        break

train_s2_true = pd.concat(
    s2_true_parts,
    ignore_index=True
)

# ------------------------------------------------------------
# Read S3 in chunks
# ------------------------------------------------------------

s3_true_parts = []

for chunk in pd.read_csv(
    train_s3_path,
    sep="\t",
    chunksize=200_000,
    dtype=str
):
    found = chunk[
        chunk["entity_id"].isin(s3_needed)
    ]

    if len(found):
        s3_true_parts.append(found)

    if sum(len(x) for x in s3_true_parts) >= len(s3_needed):
        break

train_s3_true = pd.concat(
    s3_true_parts,
    ignore_index=True
)

print("\n" + "=" * 60)
print("EXTRACTION COMPLETE")
print("=" * 60)

print("S2 rows found:", len(train_s2_true))
print("S3 rows found:", len(train_s3_true))

print("\nExpected:")
print("S2:", len(s2_needed))
print("S3:", len(s3_needed))

print("\nMissing S2:", len(s2_needed - set(train_s2_true["entity_id"])))
print("Missing S3:", len(s3_needed - set(train_s3_true["entity_id"])))

Looking for:
S2: 3341
S3: 3634

============================================================
EXTRACTION COMPLETE
============================================================
S2 rows found: 3341
S3 rows found: 3634

Expected:
S2: 3341
S3: 3634

Missing S2: 0
Missing S3: 0

In [ ]:
# ============================================================
# TRUE-MATCH RECALL TEST
#
# Tests:
#   500/500 rare-token blocker
#   >=2 shared tokens
#   similarity >= threshold
#
# Against the 6,975 known true matches
# ============================================================

from difflib import SequenceMatcher
from collections import defaultdict

# ------------------------------------------------------------
# Normalize the extracted true rows
# ------------------------------------------------------------

def normalize_for_block(x):
    if pd.isna(x):
        return ""
    return str(x).lower().strip()


def get_tokens(x):
    if not x:
        return set()
    return set(x.split())


# Create lookup dictionaries by entity ID
s2_true_lookup = {
    row["entity_id"]: row
    for _, row in train_s2_true.iterrows()
}

s3_true_lookup = {
    row["entity_id"]: row
    for _, row in train_s3_true.iterrows()
}


def similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


# ------------------------------------------------------------
# Test every known true pair
# ------------------------------------------------------------

thresholds = [0.60, 0.65, 0.70, 0.75]

stats = {
    t: {
        "total": 0,
        "recovered": 0,
        "s2_total": 0,
        "s2_recovered": 0,
        "s3_total": 0,
        "s3_recovered": 0
    }
    for t in thresholds
}


for counter, (s1_id, true_ids) in enumerate(gt_lookup.items()):

    if counter % 500 == 0:
        print(f"{counter}/2000")

    s1row = s1_lookup[s1_id]

    name1 = normalize_for_block(s1row["business_name"])
    addr1 = normalize_for_block(s1row["business_address"])
    country1 = normalize_for_block(s1row["country"])

    name_tokens1 = get_tokens(name1)
    addr_tokens1 = get_tokens(addr1)

    for true_id in true_ids:

        if true_id.startswith("S2-"):
            target = s2_true_lookup[true_id]
            source = "s2"
        else:
            target = s3_true_lookup[true_id]
            source = "s3"

        name2 = normalize_for_block(target["business_name"])
        addr2 = normalize_for_block(target["business_address"])
        country2 = normalize_for_block(target["country"])

        # Candidate blocker requires same country
        if country1 != country2:
            continue

        shared_name = name_tokens1 & get_tokens(name2)
        shared_addr = addr_tokens1 & get_tokens(addr2)

        # Rare token requirement
        name_rare = any(
            name_freq.get(token, 999999999) <= 500
            for token in shared_name
        )

        addr_rare = any(
            addr_freq.get(token, 999999999) <= 500
            for token in shared_addr
        )

        name_sim = similarity(name1, name2)
        addr_sim = similarity(addr1, addr2)

        for threshold in thresholds:

            stats[threshold]["total"] += 1

            if source == "s2":
                stats[threshold]["s2_total"] += 1
            else:
                stats[threshold]["s3_total"] += 1

            recovered = (
                (
                    len(shared_name) >= 2
                    and name_rare
                    and name_sim >= threshold
                )
                or
                (
                    len(shared_addr) >= 2
                    and addr_rare
                    and addr_sim >= threshold
                )
            )

            if recovered:

                stats[threshold]["recovered"] += 1

                if source == "s2":
                    stats[threshold]["s2_recovered"] += 1
                else:
                    stats[threshold]["s3_recovered"] += 1


# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("TRUE-MATCH RECALL RESULTS")
print("=" * 75)

for threshold in thresholds:

    x = stats[threshold]

    overall = 100 * x["recovered"] / x["total"]
    s2_recall = 100 * x["s2_recovered"] / x["s2_total"]
    s3_recall = 100 * x["s3_recovered"] / x["s3_total"]

    print(f"\nSimilarity >= {threshold:.2f}")
    print("-" * 50)

    print(
        f"Overall: {x['recovered']:,} / {x['total']:,}"
        f" = {overall:.2f}%"
    )

    print(
        f"S2: {x['s2_recovered']:,} / {x['s2_total']:,}"
        f" = {s2_recall:.2f}%"
    )

    print(
        f"S3: {x['s3_recovered']:,} / {x['s3_total']:,}"
        f" = {s3_recall:.2f}%"
    )

0/2000
500/2000
1000/2000
1500/2000

===========================================================================
TRUE-MATCH RECALL RESULTS
===========================================================================

Similarity >= 0.60
--------------------------------------------------
Overall: 6,313 / 6,975 = 90.51%
S2: 3,047 / 3,341 = 91.20%
S3: 3,266 / 3,634 = 89.87%

Similarity >= 0.65
--------------------------------------------------
Overall: 6,174 / 6,975 = 88.52%
S2: 2,981 / 3,341 = 89.22%
S3: 3,193 / 3,634 = 87.86%

Similarity >= 0.70
--------------------------------------------------
Overall: 6,008 / 6,975 = 86.14%
S2: 2,918 / 3,341 = 87.34%
S3: 3,090 / 3,634 = 85.03%

Similarity >= 0.75
--------------------------------------------------
Overall: 5,742 / 6,975 = 82.32%
S2: 2,812 / 3,341 = 84.17%
S3: 2,930 / 3,634 = 80.63%

In [ ]:
# ============================================================
# BLOCKER RECALL:
# RARITY LIMIT COMPARISON AT SIMILARITY >= 0.60
#
# Also includes:
#   exact name + country
#   exact address + country
# ============================================================

rarity_limits = [500, 1000, 2000, 5000, None]

recall_results = {}

for limit in rarity_limits:

    recovered = 0
    s2_rec = 0
    s3_rec = 0

    total = 0
    s2_total = 0
    s3_total = 0

    for s1_id, true_ids in gt_lookup.items():

        s1row = s1_lookup[s1_id]

        name1 = normalize_for_block(s1row["business_name"])
        addr1 = normalize_for_block(s1row["business_address"])
        country1 = normalize_for_block(s1row["country"])

        tokens_name1 = get_tokens(name1)
        tokens_addr1 = get_tokens(addr1)

        for true_id in true_ids:

            if true_id.startswith("S2-"):
                target = s2_true_lookup[true_id]
                source = "s2"
            else:
                target = s3_true_lookup[true_id]
                source = "s3"

            name2 = normalize_for_block(target["business_name"])
            addr2 = normalize_for_block(target["business_address"])
            country2 = normalize_for_block(target["country"])

            if source == "s2":
                s2_total += 1
            else:
                s3_total += 1

            total += 1

            # Country must agree
            if country1 != country2:
                continue

            # ------------------------------------------------
            # EXACT RULES
            # ------------------------------------------------

            exact_match = (
                (name1 and name1 == name2)
                or
                (addr1 and addr1 == addr2)
            )

            if exact_match:

                recovered += 1

                if source == "s2":
                    s2_rec += 1
                else:
                    s3_rec += 1

                continue

            # ------------------------------------------------
            # TOKEN RULES
            # ------------------------------------------------

            shared_name = tokens_name1 & get_tokens(name2)
            shared_addr = tokens_addr1 & get_tokens(addr2)

            name_ok = False
            addr_ok = False

            # Name
            if len(shared_name) >= 2:

                if limit is None:
                    name_rare = True
                else:
                    name_rare = any(
                        name_freq.get(t, 999999999) <= limit
                        for t in shared_name
                    )

                if name_rare:
                    if similarity(name1, name2) >= 0.60:
                        name_ok = True

            # Address
            if len(shared_addr) >= 2:

                if limit is None:
                    addr_rare = True
                else:
                    addr_rare = any(
                        addr_freq.get(t, 999999999) <= limit
                        for t in shared_addr
                    )

                if addr_rare:
                    if similarity(addr1, addr2) >= 0.60:
                        addr_ok = True

            if name_ok or addr_ok:

                recovered += 1

                if source == "s2":
                    s2_rec += 1
                else:
                    s3_rec += 1

    recall_results[limit] = {
        "overall": 100 * recovered / total,
        "s2": 100 * s2_rec / s2_total,
        "s3": 100 * s3_rec / s3_total,
        "recovered": recovered
    }


print("\n" + "=" * 75)
print("RARITY LIMIT + SIMILARITY 0.60 RECALL")
print("=" * 75)

for limit, r in recall_results.items():

    label = "NO RARITY LIMIT" if limit is None else f"<= {limit}"

    print(f"\n{label}")
    print("-" * 45)
    print(
        f"Overall: {r['recovered']:,} / 6,975"
        f" = {r['overall']:.2f}%"
    )
    print(f"S2: {r['s2']:.2f}%")
    print(f"S3: {r['s3']:.2f}%")

===========================================================================
RARITY LIMIT + SIMILARITY 0.60 RECALL
===========================================================================

<= 500
---------------------------------------------
Overall: 6,326 / 6,975 = 90.70%
S2: 91.41%
S3: 90.04%

<= 1000
---------------------------------------------
Overall: 6,370 / 6,975 = 91.33%
S2: 91.95%
S3: 90.75%

<= 2000
---------------------------------------------
Overall: 6,393 / 6,975 = 91.66%
S2: 92.28%
S3: 91.08%

<= 5000
---------------------------------------------
Overall: 6,418 / 6,975 = 92.01%
S2: 92.58%
S3: 91.50%

NO RARITY LIMIT
---------------------------------------------
Overall: 6,523 / 6,975 = 93.52%
S2: 93.56%
S3: 93.48%

In [ ]:
# ============================================================
# ANALYZE MISSED TRUE PAIRS
# NO RARITY LIMIT + SIMILARITY >= 0.60
# ============================================================

missed = []

for s1_id, true_ids in gt_lookup.items():

    s1row = s1_lookup[s1_id]

    name1 = normalize_for_block(s1row["business_name"])
    addr1 = normalize_for_block(s1row["business_address"])
    country1 = normalize_for_block(s1row["country"])

    tokens_name1 = get_tokens(name1)
    tokens_addr1 = get_tokens(addr1)

    for true_id in true_ids:

        if true_id.startswith("S2-"):
            target = s2_true_lookup[true_id]
            source = "S2"
        else:
            target = s3_true_lookup[true_id]
            source = "S3"

        name2 = normalize_for_block(target["business_name"])
        addr2 = normalize_for_block(target["business_address"])
        country2 = normalize_for_block(target["country"])

        shared_name = tokens_name1 & get_tokens(name2)
        shared_addr = tokens_addr1 & get_tokens(addr2)

        name_sim = similarity(name1, name2)
        addr_sim = similarity(addr1, addr2)

        exact_name = bool(name1) and name1 == name2
        exact_addr = bool(addr1) and addr1 == addr2

        recovered = False

        if country1 == country2:

            if exact_name or exact_addr:
                recovered = True

            elif (
                len(shared_name) >= 2
                and name_sim >= 0.60
            ):
                recovered = True

            elif (
                len(shared_addr) >= 2
                and addr_sim >= 0.60
            ):
                recovered = True

        if not recovered:

            missed.append({
                "s1_id": s1_id,
                "true_id": true_id,
                "source": source,
                "country_same": country1 == country2,
                "shared_name": len(shared_name),
                "shared_addr": len(shared_addr),
                "name_sim": name_sim,
                "addr_sim": addr_sim,
                "exact_name": exact_name,
                "exact_addr": exact_addr,
                "name1": name1,
                "name2": name2,
                "addr1": addr1,
                "addr2": addr2
            })


missed_df = pd.DataFrame(missed)

print("=" * 75)
print("MISSED TRUE PAIRS")
print("=" * 75)

print("Total missed:", len(missed_df))

print("\nCountry mismatch:")
print(missed_df["country_same"].value_counts())

print("\nShared name tokens:")
print(missed_df["shared_name"].value_counts().sort_index())

print("\nShared address tokens:")
print(missed_df["shared_addr"].value_counts().sort_index())

print("\nName similarity:")
print(missed_df["name_sim"].describe())

print("\nAddress similarity:")
print(missed_df["addr_sim"].describe())

print("\nSource:")
print(missed_df["source"].value_counts())

print("\nPotential high-similarity misses:")

display(
    missed_df[
        (missed_df["name_sim"] >= 0.80) |
        (missed_df["addr_sim"] >= 0.80)
    ][[
        "source",
        "shared_name",
        "shared_addr",
        "name_sim",
        "addr_sim",
        "name1",
        "name2",
        "addr1",
        "addr2"
    ]].head(30)
)

===========================================================================
MISSED TRUE PAIRS
===========================================================================
Total missed: 452

Country mismatch:
country_same
True    452
Name: count, dtype: int64

Shared name tokens:
shared_name
0    264
1    133
2     35
3     16
4      3
5      1
Name: count, dtype: int64

Shared address tokens:
shared_addr
0      38
1      65
2      80
3     102
4      72
5      42
6      19
7       9
8       6
9       9
10      3
11      5
12      2
Name: count, dtype: int64

Name similarity:
count    452.000000
mean       0.492048
std        0.323395
min        0.046512
25%        0.105263
50%        0.543561
75%        0.815657
max        0.958333
Name: name_sim, dtype: float64

Address similarity:
count    452.000000
mean       0.449292
std        0.168890
min        0.000000
25%        0.394183
50%        0.486486
75%        0.549127
max        0.820513
Name: addr_sim, dtype: float64

Source:
source
S3    237
S2    215
Name: count, dtype: int64

Potential high-similarity misses:

,source,shared_name,shared_addr,name_sim,addr_sim,name1,name2,addr1,addr2
0,S2,1,3,0.838710,0.361111,allied venture lp,a1lied venture,"310 new york street, fortville, in","fortville, <null>, in, 310 new ytrk st"
11,S2,0,3,0.916667,0.543210,maid pilates,maid-pilates,"100 daly boulevard, unit apartment 807, hempst...","100 daly blvd, oceanside, ny"
12,S2,1,2,0.888889,0.525000,maid pilates,maid pilfafetes,"100 daly boulevard, unit apartment 807, hempst...","100 day blvd, oceanside, ny"
14,S3,1,3,0.875000,0.563380,cultural council,cultural cgnucil,"2120 albatross way, gallatin, tn","gallatin, 2479 albatross way, tennessee"
16,S2,1,3,0.914286,0.552632,burns empire net,burns emphire (net),"2143 leonard avenue, columbus, oh","columbus, oh, 2143 leonard ave, po box 5053"
18,S3,1,3,0.923077,0.425000,ridge society,ridge sóciety,"mo, saint louis, fl 0, 6827 vernon avenue","7194. vernon ave, saint louis, missouri"
25,S3,0,4,0.909091,0.370370,surat india,#suratindia,"surat, gujarat, 8/11 to 32/35, jairaj apartmen...","8/11 to 32/35, surat, ગુજરાત"
28,S2,0,1,0.800000,0.482759,montan aria,montanaria.com,"184 broadway, brookhaven, ny","brookhaven, ny, 184-d broadway"
32,S2,1,0,0.903226,0.000000,bamaify-easton,bamaify-easton co,"29441 matthewstown road, easton, md",
37,S2,0,0,0.937500,0.000000,mount fellowship,mount-fellowship,"110 dellwood lane, gray, tn",
39,S3,1,4,0.810811,0.210526,tigon polytechnic,sri tigon polythenic,"h. no. 718/a, at revdanda tal. alibag, dist. r...","raigarh, mh, alibag, h. no. 718/a"
40,S2,1,2,0.875000,0.539683,violet's couture,violet's cougtr,"909 remington road, columbus, oh","columbus, oh, 90 remington road"
49,S2,1,3,0.800000,0.486486,silver cafe,silver cn,"va, halifax town, 1076 mountain road","1076-c mountain road, halifax town, va"
56,S2,0,0,0.909091,0.000000,luna fusion,luna-fusion,"8000 1/2 wildcat pass, austin, tx",
57,S2,1,4,0.923077,0.514286,vetecex group,vetecex gróup,"sacramento, 2761 stockton boulevard, ca, unit ...","2761 stockton boulevard, po box 1680, sacramen..."
69,S2,1,3,0.888889,0.508475,choice disciplined,choice disceplinde,"1121 11 avenue, mn, saint cloud","saint cloud, 1121 11 ave, mn"
70,S3,1,1,0.837209,0.408163,pediatric medicine pllc,pediatric (medicine),"4850 20, otisco, ny","otisco, new york, 4850-4852 20"
71,S2,0,1,0.105263,0.820513,timber metal,jaxonyx,"2419 stoneleigh court, naperville, il","il, 2419-c stoneleigh ct, napervillec ity"
72,S2,0,1,0.918919,0.680000,drayial irenic inc.,drayial-irenic inc,"911 3rd street, wa, tacoma","911 third st, tacoma, wa"
78,S3,1,1,0.869565,0.763158,trusted clear popular inc,trusted-clear popular,"3734 vermont street, indianapolis, in","indiana, #3734 vermont st, indianapolis"
79,S2,0,11,0.823529,0.472222,knitting wheels llp,@knittingwheels,"sec-e, slice 4, sch no. 78, indore, plot no. 1...","madhya pradesh, h.no 11 type-d, sec-e, slice 4..."
85,S3,1,2,0.928571,0.584615,st. ministries,5t. ministries,"9107 beach road, cicero, ny","9107 1/2 beach rd, new york, brewerton"
87,S2,0,3,0.800000,0.464286,cozy bike shop,cozybikeshop.com,"278 danada square, wheaton, il","wheaton, il, 278 danada sq"
91,S2,0,3,0.864865,0.447368,atlantic electric,atlanticelectric.com,"171 amelita court, unit 206, whiteville, nc","nc, whiteville, 171 amelita court"
93,S2,1,0,0.928571,0.000000,veterans guild,veterans gúild,"268 columbine lane, shakopee, mn",
94,S3,0,0,0.888889,0.000000,kestan pattana inc,kestan-pattana-inc,"8333 park vista circle, charlotte, nc",
97,S3,1,5,0.933333,0.512195,liberty network,liberty nettwrk,"portsmouth city, 175 choate street, va","175 choate street, portsmouth city, virginia"
100,S2,1,0,0.829268,0.000000,"zedyne argentina, inc.","zedyne (argentina,)","5710 windy lane, winema, or",
107,S3,0,5,0.837209,0.494118,tetech bleichroeder p.c.,tetech-bleichroeder,"missouri city, tx, 6702 cascade manor lane","6702 cascade manor ln, missouri city, texas"
117,S2,1,4,0.947368,0.583333,family partners llc,family partners-llc,"1315 county road 3404, cleveland, tx","tx, cleveland, 1315 county road 3404"

In [ ]:
# ============================================================
# HYBRID BLOCKER RECALL TEST
#
# Exact name/address
# +
# Name: >=2 shared tokens + similarity >= 0.60
# +
# Address: >=3 shared tokens (NO character similarity)
# ============================================================

total = 0
recovered = 0

s2_total = 0
s2_recovered = 0

s3_total = 0
s3_recovered = 0

for counter, (s1_id, true_ids) in enumerate(gt_lookup.items()):

    if counter % 500 == 0:
        print(f"{counter}/2000")

    s1row = s1_lookup[s1_id]

    name1 = normalize_for_block(s1row["business_name"])
    addr1 = normalize_for_block(s1row["business_address"])
    country1 = normalize_for_block(s1row["country"])

    name_tokens1 = get_tokens(name1)
    addr_tokens1 = get_tokens(addr1)

    for true_id in true_ids:

        if true_id.startswith("S2-"):
            target = s2_true_lookup[true_id]
            source = "S2"
            s2_total += 1
        else:
            target = s3_true_lookup[true_id]
            source = "S3"
            s3_total += 1

        total += 1

        name2 = normalize_for_block(target["business_name"])
        addr2 = normalize_for_block(target["business_address"])
        country2 = normalize_for_block(target["country"])

        if country1 != country2:
            continue

        # ----------------------------------------------------
        # Exact matches
        # ----------------------------------------------------

        exact_name = (
            bool(name1) and
            name1 == name2
        )

        exact_addr = (
            bool(addr1) and
            addr1 == addr2
        )

        # ----------------------------------------------------
        # Shared tokens
        # ----------------------------------------------------

        shared_name = (
            name_tokens1 &
            get_tokens(name2)
        )

        shared_addr = (
            addr_tokens1 &
            get_tokens(addr2)
        )

        # ----------------------------------------------------
        # Name rule
        # ----------------------------------------------------

        name_rule = (
            len(shared_name) >= 2
            and similarity(name1, name2) >= 0.60
        )

        # ----------------------------------------------------
        # Address rule
        #
        # IMPORTANT:
        # No SequenceMatcher here.
        # Token overlap handles reordered addresses.
        # ----------------------------------------------------

        address_rule = (
            len(shared_addr) >= 3
        )

        recovered_pair = (
            exact_name
            or exact_addr
            or name_rule
            or address_rule
        )

        if recovered_pair:

            recovered += 1

            if source == "S2":
                s2_recovered += 1
            else:
                s3_recovered += 1


print("\n" + "=" * 75)
print("HYBRID BLOCKER RECALL")
print("=" * 75)

print(
    f"\nOverall: {recovered:,} / {total:,}"
    f" = {100 * recovered / total:.2f}%"
)

print(
    f"S2: {s2_recovered:,} / {s2_total:,}"
    f" = {100 * s2_recovered / s2_total:.2f}%"
)

print(
    f"S3: {s3_recovered:,} / {s3_total:,}"
    f" = {100 * s3_recovered / s3_total:.2f}%"
)

0/2000
500/2000
1000/2000
1500/2000

===========================================================================
HYBRID BLOCKER RECALL
===========================================================================

Overall: 6,671 / 6,975 = 95.64%
S2: 3,215 / 3,341 = 96.23%
S3: 3,456 / 3,634 = 95.10%

In [ ]:
# ============================================================
# ANALYZE HYBRID BLOCKER MISSES
# ============================================================

hybrid_missed = []

for s1_id, true_ids in gt_lookup.items():

    s1row = s1_lookup[s1_id]

    name1 = normalize_for_block(s1row["business_name"])
    addr1 = normalize_for_block(s1row["business_address"])
    country1 = normalize_for_block(s1row["country"])

    name_tokens1 = get_tokens(name1)
    addr_tokens1 = get_tokens(addr1)

    for true_id in true_ids:

        if true_id.startswith("S2-"):
            target = s2_true_lookup[true_id]
            source = "S2"
        else:
            target = s3_true_lookup[true_id]
            source = "S3"

        name2 = normalize_for_block(target["business_name"])
        addr2 = normalize_for_block(target["business_address"])
        country2 = normalize_for_block(target["country"])

        if country1 != country2:
            continue

        shared_name = name_tokens1 & get_tokens(name2)
        shared_addr = addr_tokens1 & get_tokens(addr2)

        name_sim = similarity(name1, name2)
        addr_sim = similarity(addr1, addr2)

        exact_name = bool(name1) and name1 == name2
        exact_addr = bool(addr1) and addr1 == addr2

        recovered = (
            exact_name
            or exact_addr
            or (
                len(shared_name) >= 2
                and name_sim >= 0.60
            )
            or (
                len(shared_addr) >= 3
            )
        )

        if not recovered:

            hybrid_missed.append({
                "source": source,
                "shared_name": len(shared_name),
                "shared_addr": len(shared_addr),
                "name_sim": name_sim,
                "addr_sim": addr_sim,
                "name1": name1,
                "name2": name2,
                "addr1": addr1,
                "addr2": addr2
            })


missed_hybrid_df = pd.DataFrame(hybrid_missed)

print("=" * 75)
print("HYBRID BLOCKER MISSES")
print("=" * 75)

print("Total missed:", len(missed_hybrid_df))

print("\nShared address tokens:")
print(
    missed_hybrid_df["shared_addr"]
    .value_counts()
    .sort_index()
)

print("\nShared name tokens:")
print(
    missed_hybrid_df["shared_name"]
    .value_counts()
    .sort_index()
)

print("\nName similarity:")
print(missed_hybrid_df["name_sim"].describe())

print("\nAddress similarity:")
print(missed_hybrid_df["addr_sim"].describe())

print("\nSource:")
print(missed_hybrid_df["source"].value_counts())

print("\nExamples with exactly 2 shared address tokens:")
display(
    missed_hybrid_df[
        missed_hybrid_df["shared_addr"] == 2
    ][[
        "source",
        "shared_name",
        "shared_addr",
        "name_sim",
        "addr_sim",
        "name1",
        "name2",
        "addr1",
        "addr2"
    ]].head(20)
)

===========================================================================
HYBRID BLOCKER MISSES
===========================================================================
Total missed: 304

Shared address tokens:
shared_addr
0     38
1     65
2    201
Name: count, dtype: int64

Shared name tokens:
shared_name
0    152
1    117
2     27
3      6
4      2
Name: count, dtype: int64

Name similarity:
count    304.000000
mean       0.614368
std        0.292344
min        0.046512
25%        0.484848
50%        0.717465
75%        0.857143
max        0.960000
Name: name_sim, dtype: float64

Address similarity:
count    304.000000
mean       0.538302
std        0.262935
min        0.000000
25%        0.386070
50%        0.579587
75%        0.761212
max        0.936170
Name: addr_sim, dtype: float64

Source:
source
S3    178
S2    126
Name: count, dtype: int64

Examples with exactly 2 shared address tokens:

,source,shared_name,shared_addr,name_sim,addr_sim,name1,name2,addr1,addr2
2,S3,0,2,0.653846,0.386555,ss technology private limited,téchnologyprivatess.com,"shop no. 1164, pvt no.2, first floor kucha mah...","#1164, central delhi, dl"
4,S3,1,2,0.666667,0.300000,granite llc,graiote graiote llc,"az, phoenix, unit 1050, 5151 16th street","##5151 16nd st, # 1050, phoenix, arizona"
6,S2,1,2,0.888889,0.525000,maid pilates,maid pilfafetes,"100 daly boulevard, unit apartment 807, hempst...","100 day blvd, oceanside, ny"
7,S2,3,2,0.592593,0.405405,qtn logistics private limited,private qtn logistics ltd,"18-2-43/a/51/a/1, ghazi millat colony, chandra...","plot 582 18-2-43/a/51/a/1, rangareddy, తెలంగాణ"
8,S3,0,2,0.101695,0.471910,star infra private limited,സ്റ്റാർ ഇൻഫ്ര പ്രൈവറ്റ് ലിമിറ്റഡ്,"1/440, vadakkancherry p.o.trichur dist, thalap...","1/440, thalapilly, kl"
9,S3,0,2,0.101695,0.396396,jai healthcare private limited,जय हेल्थकेयर प्राइवेट लिमिटेड,"a-203, dreamland apartment, crossing republic,...","a-203, gaziabad, ghaziabad, उत्तर प्रदेश"
10,S2,0,2,0.085106,0.451613,shivam solutions llp,శివం సొల్యూషన్స్ ఎల్‌ఎల్‌పీ,"rangareddy, telangana, syno. 177, puppalaguda,...","syno. 77, rangareddy, telangana"
11,S3,1,2,0.823529,0.773333,delta fortunex inc,delta [fortunex],"16978 moore road, andalusia, al","##16978 moore rd, <null>, andalusia, alabama"
12,S3,2,2,0.418605,0.773333,delta fortunex inc,delta inc center [center],"16978 moore road, andalusia, al","##16978 moore rd, <null>, andalusia, alabama"
15,S2,1,2,0.526316,0.697674,ef sprott,ef service,"7962 normanshire court, unit cond 101, ak, anc...","7962 normanshire ct, anchorage, ak"
16,S3,1,2,0.904762,0.704762,thoothukkudi tradex co,thoothukkudi-trdx co,"no.26a/1a, bryant nagar viii, thoothukkudi, tu...","h.no 26a/1a, thoothukkudi, tuticorin, tn"
17,S3,0,2,0.070588,0.516854,tirupati infrastructure private limited,திருப்பதி இன்ஃப்ராஸ்ட்ரக்சர் பிரைவேட் லிமிடெட்,"233/6/52f, arumugam street, dharmapuri, tamil ...","hn 439 233/6/52f, dharmapuri, தமிழ்நாடு"
18,S3,0,2,0.070588,0.609756,tirupati infrastructure private limited,திருப்பதி இன்ஃப்ராஸ்ட்ரக்சர் பிரைவேட் லிமிடெட்,"233/6/52f, arumugam street, dharmapuri, tamil ...","hn 439 233/6/52f, dharmapuri, tn"
19,S3,1,2,0.717949,0.444444,yavatmal marine,yavatmal yavatmal marien,"pc-5, h no.270, navjiwan mangal karyalay, yava...","pc-5, yavatmal, mh"
21,S3,0,2,0.800000,0.698413,montan aria,montanaria.com,"184 broadway, brookhaven, ny","184 broadway, rocky point, new york"
22,S3,0,2,0.098361,0.901961,jain consulting private limited,जैन कंसल्टिंग प्राइवेट लिमिटेड,"a/12-10apurval.b.s.marg, mulund(w), mumbai, ma...","a/1-2-10apurval.b.s.marg, mulund(w), mumbai, mh"
24,S2,0,2,0.095238,0.388889,sai impex,साई इम्पेक्स,"352, sec-21, gurugram, palam road, gurgaon, ha...","352, gurgaon, हरियाणा"
26,S3,0,2,0.089552,0.650602,north engineering private limited,नॉर्थ इंजीनियरिंग प्राइवेट लिमिटेड,"22/1, south tukoganj, a.b.road, indore., madhy...","022/1, a.b.road, indore., mp"
27,S2,1,2,0.875000,0.539683,violet's couture,violet's cougtr,"909 remington road, columbus, oh","columbus, oh, 90 remington road"
28,S3,1,2,0.800000,0.750000,rivera neuberger inc,rivera inc-neuberger,"9 mulberry drive, chester, wv","mulberry dr, chester, west virginia"

In [ ]:
# ============================================================
# TEST TARGETED ADDRESS FALLBACKS
# Against the 304 remaining hybrid misses
# ============================================================

import re

def extract_numbers(text):
    if not text:
        return set()
    return set(re.findall(r'\d+', text))


fallback_counts = {
    "2_tokens + shared_number": 0,
    "2_tokens + addr_sim_0.30": 0,
    "2_tokens + addr_sim_0.40": 0,
}

for _, row in missed_hybrid_df.iterrows():

    shared_addr = int(row["shared_addr"])

    if shared_addr < 2:
        continue

    addr1 = row["addr1"]
    addr2 = row["addr2"]

    nums1 = extract_numbers(addr1)
    nums2 = extract_numbers(addr2)

    shared_numbers = nums1 & nums2

    # Rule 1
    if shared_numbers:
        fallback_counts["2_tokens + shared_number"] += 1

    # Rule 2
    if row["addr_sim"] >= 0.30:
        fallback_counts["2_tokens + addr_sim_0.30"] += 1

    # Rule 3
    if row["addr_sim"] >= 0.40:
        fallback_counts["2_tokens + addr_sim_0.40"] += 1


print("=" * 70)
print("TARGETED ADDRESS FALLBACK RESULTS")
print("=" * 70)

for rule, count in fallback_counts.items():

    new_recall = (
        (6975 - 304 + count) / 6975
    ) * 100

    print(f"\n{rule}")
    print("Additional true matches recovered:", count)
    print(
        "Estimated total recall:",
        f"{new_recall:.2f}%"
    )

======================================================================
TARGETED ADDRESS FALLBACK RESULTS
======================================================================

2_tokens + shared_number
Additional true matches recovered: 145
Estimated total recall: 97.72%

2_tokens + addr_sim_0.30
Additional true matches recovered: 199
Estimated total recall: 98.49%

2_tokens + addr_sim_0.40
Additional true matches recovered: 178
Estimated total recall: 98.19%

In [ ]:
# ============================================================
# FINAL HYBRID BLOCKER - CANDIDATE VOLUME TEST
#
# Rules:
# 1. Exact name + country
# 2. Exact address + country
# 3. >=2 name tokens + name similarity >= 0.60
# 4. >=3 address tokens
# 5. >=2 address tokens + address similarity >= 0.30
#
# NO RARITY LIMIT
# ============================================================

from difflib import SequenceMatcher
from collections import defaultdict
import numpy as np
import re


def sim_fast(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


def count_final_candidates(
    row,
    source_df,
    name_index,
    addr_index
):

    name1 = row["name_n"]
    addr1 = row["addr_n"]
    country1 = row["country_n"]

    name_tokens1 = toks(name1)
    addr_tokens1 = toks(addr1)

    name_hits = defaultdict(int)
    addr_hits = defaultdict(int)

    # --------------------------------------------------------
    # NAME TOKEN BLOCK
    # --------------------------------------------------------

    for token in name_tokens1:

        for eid in name_index.get(token, []):
            name_hits[eid] += 1

    # --------------------------------------------------------
    # ADDRESS TOKEN BLOCK
    # --------------------------------------------------------

    for token in addr_tokens1:

        for eid in addr_index.get(token, []):
            addr_hits[eid] += 1

    # Candidates that satisfy >=2 token requirement
    candidate_ids = set()

    candidate_ids.update(
        eid
        for eid, count in name_hits.items()
        if count >= 2
    )

    candidate_ids.update(
        eid
        for eid, count in addr_hits.items()
        if count >= 2
    )

    final = set()

    for eid in candidate_ids:

        target = source_df.iloc[eid]

        # Same country
        if target["country_n"] != country1:
            continue

        name2 = target["name_n"]
        addr2 = target["addr_n"]

        shared_name_count = name_hits.get(eid, 0)
        shared_addr_count = addr_hits.get(eid, 0)

        # ----------------------------------------------------
        # Exact rules
        # ----------------------------------------------------

        if name1 and name1 == name2:
            final.add(eid)
            continue

        if addr1 and addr1 == addr2:
            final.add(eid)
            continue

        # ----------------------------------------------------
        # Name similarity rule
        # ----------------------------------------------------

        if shared_name_count >= 2:

            if sim_fast(name1, name2) >= 0.60:
                final.add(eid)
                continue

        # ----------------------------------------------------
        # Address >= 3 tokens
        # ----------------------------------------------------

        if shared_addr_count >= 3:
            final.add(eid)
            continue

        # ----------------------------------------------------
        # Address fallback:
        # >=2 tokens + similarity >= 0.30
        # ----------------------------------------------------

        if shared_addr_count >= 2:

            if sim_fast(addr1, addr2) >= 0.30:
                final.add(eid)
                continue

    return final


print("Starting FINAL blocker volume test...")

s2_counts = []
s3_counts = []

for counter, (_, row) in enumerate(s1.iterrows()):

    if counter % 1000 == 0:
        print(f"{counter}/10000")

    s2_counts.append(
        len(
            count_final_candidates(
                row,
                test_s2,
                s2_name_index,
                s2_addr_index
            )
        )
    )

    s3_counts.append(
        len(
            count_final_candidates(
                row,
                test_s3,
                s3_name_index,
                s3_addr_index
            )
        )
    )


s2_counts = np.array(s2_counts)
s3_counts = np.array(s3_counts)

combined_avg = (
    s2_counts.mean() +
    s3_counts.mean()
) / 2

estimated_full = combined_avg * 1_732_544


print("\n" + "=" * 75)
print("FINAL HYBRID BLOCKER VOLUME")
print("=" * 75)

print("\nS2")
print("Average:", round(s2_counts.mean(), 2))
print("Median :", round(np.median(s2_counts), 2))
print("P90    :", round(np.percentile(s2_counts, 90), 2))
print("P95    :", round(np.percentile(s2_counts, 95), 2))
print("P99    :", round(np.percentile(s2_counts, 99), 2))
print("Max    :", int(s2_counts.max()))

print("\nS3")
print("Average:", round(s3_counts.mean(), 2))
print("Median :", round(np.median(s3_counts), 2))
print("P90    :", round(np.percentile(s3_counts, 90), 2))
print("P95    :", round(np.percentile(s3_counts, 95), 2))
print("P99    :", round(np.percentile(s3_counts, 99), 2))
print("Max    :", int(s3_counts.max()))

print("\nCombined average:", round(combined_avg, 2))

print(
    "Estimated full-test candidates:",
    f"{estimated_full:,.0f}"
)

Starting FINAL blocker volume test...
0/10000

KeyboardInterrupt:

In [ ]:
# ============================================================
# FAST FINAL BLOCKER VOLUME TEST — 500 S1 ROWS
# ============================================================

import numpy as np
import re

# Use only 500 rows for a quick volume estimate
volume_test_s1 = s1.head(500).copy()

print("Starting FAST 500-row blocker volume test...")
print("Rows:", len(volume_test_s1))


def extract_numbers(text):
    if not text:
        return set()
    return set(re.findall(r'\d+', text))


def count_final_candidates_fast(row, test_df, name_index, addr_index):

    name1 = normalize_for_block(row["business_name"])
    addr1 = normalize_for_block(row["business_address"])
    country1 = normalize_for_block(row["country"])

    name_tokens1 = get_tokens(name1)
    addr_tokens1 = get_tokens(addr1)

    nums1 = extract_numbers(addr1)

    final = set()

    # --------------------------------------------------------
    # NAME INDEX
    # --------------------------------------------------------
    for token in name_tokens1:
        for eid in name_index.get(token, []):
            if eid in final:
                continue

            target = test_df.loc[eid]

            country2 = normalize_for_block(target["country"])

            if country1 != country2:
                continue

            name2 = normalize_for_block(target["business_name"])
            addr2 = normalize_for_block(target["business_address"])

            name_tokens2 = get_tokens(name2)
            addr_tokens2 = get_tokens(addr2)

            # Rule 1: exact name
            if name1 == name2:
                final.add(eid)
                continue

            # Rule 3: >=2 shared name tokens + similarity >= 0.60
            shared_name_count = len(name_tokens1 & name_tokens2)

            if shared_name_count >= 2:
                if sim_fast(name1, name2) >= 0.60:
                    final.add(eid)
                    continue

    # --------------------------------------------------------
    # ADDRESS INDEX
    # --------------------------------------------------------
    for token in addr_tokens1:
        for eid in addr_index.get(token, []):

            if eid in final:
                continue

            target = test_df.loc[eid]

            country2 = normalize_for_block(target["country"])

            if country1 != country2:
                continue

            name2 = normalize_for_block(target["business_name"])
            addr2 = normalize_for_block(target["business_address"])

            # Rule 2: exact address
            if addr1 == addr2:
                final.add(eid)
                continue

            addr_tokens2 = get_tokens(addr2)

            shared_addr_count = len(addr_tokens1 & addr_tokens2)

            # Rule 4: >=3 shared address tokens
            if shared_addr_count >= 3:
                final.add(eid)
                continue

            # Rule 5:
            # >=2 shared address tokens + similarity >= 0.30
            if shared_addr_count >= 2:
                if sim_fast(addr1, addr2) >= 0.30:
                    final.add(eid)
                    continue

    return final


# ============================================================
# RUN TEST
# ============================================================

s2_counts_500 = []
s3_counts_500 = []

for counter, (_, row) in enumerate(volume_test_s1.iterrows()):

    if counter % 50 == 0:
        print(f"{counter}/500")

    s2_counts_500.append(
        len(
            count_final_candidates_fast(
                row,
                test_s2,
                s2_name_index,
                s2_addr_index
            )
        )
    )

    s3_counts_500.append(
        len(
            count_final_candidates_fast(
                row,
                test_s3,
                s3_name_index,
                s3_addr_index
            )
        )
    )


s2_counts_500 = np.array(s2_counts_500)
s3_counts_500 = np.array(s3_counts_500)


# ============================================================
# RESULTS
# ============================================================

combined_avg = (
    s2_counts_500.mean() +
    s3_counts_500.mean()
) / 2

estimated_full = combined_avg * 1_732_544


print("\n" + "=" * 75)
print("FAST FINAL HYBRID BLOCKER VOLUME — 500 ROW TEST")
print("=" * 75)

print("\nS2")
print("Average:", round(s2_counts_500.mean(), 2))
print("Median :", round(np.median(s2_counts_500), 2))
print("P90    :", round(np.percentile(s2_counts_500, 90), 2))
print("P95    :", round(np.percentile(s2_counts_500, 95), 2))
print("P99    :", round(np.percentile(s2_counts_500, 99), 2))
print("Max    :", int(s2_counts_500.max()))

print("\nS3")
print("Average:", round(s3_counts_500.mean(), 2))
print("Median :", round(np.median(s3_counts_500), 2))
print("P90    :", round(np.percentile(s3_counts_500, 90), 2))
print("P95    :", round(np.percentile(s3_counts_500, 95), 2))
print("P99    :", round(np.percentile(s3_counts_500, 99), 2))
print("Max    :", int(s3_counts_500.max()))

print("\nCOMBINED")
print("Average candidates / S1:",
      round(combined_avg, 2))

print("Estimated full candidate pairs:",
      f"{int(estimated_full):,}")

print("=" * 75)

Starting FAST 500-row blocker volume test...
Rows: 500
0/500
50/500

KeyboardInterrupt:

In [ ]:
# ============================================================
# CHECK FULL TEST SOURCE FILES
# No candidate generation yet
# ============================================================

import os

s2_path = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"
s3_path = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

print("S2 exists:", os.path.exists(s2_path))
print("S3 exists:", os.path.exists(s3_path))

print("\nS2 size (GB):", round(os.path.getsize(s2_path) / 1024**3, 2))
print("S3 size (GB):", round(os.path.getsize(s3_path) / 1024**3, 2))

print("\nCurrent test S1:", test_s1.shape)
print("Current sample S2:", test_s2.shape)
print("Current sample S3:", test_s3.shape)

S2 exists: True
S3 exists: True

S2 size (GB): 0.47
S3 size (GB): 0.47

Current test S1: (1732544, 4)
Current sample S2: (100000, 7)
Current sample S3: (100000, 7)

In [ ]:
# ============================================================
# BUILD FULL TEST S2/S3 TOKEN INDEXES
# ONE-TIME SETUP FOR V5 INFERENCE
# ============================================================

import pandas as pd
import re
import pickle
import os
from collections import defaultdict

S2_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"
S3_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

INDEX_DIR = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"
os.makedirs(INDEX_DIR, exist_ok=True)


def norm_simple(x):
    if pd.isna(x):
        return ""
    return str(x).lower().strip()


def token_set(x):
    if not x:
        return set()
    return set(x.split())


def build_indexes(path, prefix):

    print(f"\nReading {prefix}...")

    df = pd.read_csv(
        path,
        sep="\t",
        dtype=str
    )

    print(prefix, "shape:", df.shape)

    df["name_n"] = df["business_name"].map(norm_simple)
    df["addr_n"] = df["business_address"].map(norm_simple)
    df["country_n"] = df["country"].map(norm_simple)

    name_index = defaultdict(list)
    addr_index = defaultdict(list)

    name_freq = defaultdict(int)
    addr_freq = defaultdict(int)

    for i, row in df.iterrows():

        name_tokens = token_set(row["name_n"])
        addr_tokens = token_set(row["addr_n"])

        for token in name_tokens:
            name_index[token].append(i)
            name_freq[token] += 1

        for token in addr_tokens:
            addr_index[token].append(i)
            addr_freq[token] += 1

        if i % 1_000_000 == 0 and i > 0:
            print(f"{prefix}: {i:,} rows processed")

    # Convert defaultdicts to normal dicts
    name_index = dict(name_index)
    addr_index = dict(addr_index)
    name_freq = dict(name_freq)
    addr_freq = dict(addr_freq)

    # Save
    with open(f"{INDEX_DIR}/{prefix}_name_index.pkl", "wb") as f:
        pickle.dump(name_index, f, protocol=pickle.HIGHEST_PROTOCOL)

    with open(f"{INDEX_DIR}/{prefix}_addr_index.pkl", "wb") as f:
        pickle.dump(addr_index, f, protocol=pickle.HIGHEST_PROTOCOL)

    with open(f"{INDEX_DIR}/{prefix}_name_freq.pkl", "wb") as f:
        pickle.dump(name_freq, f, protocol=pickle.HIGHEST_PROTOCOL)

    with open(f"{INDEX_DIR}/{prefix}_addr_freq.pkl", "wb") as f:
        pickle.dump(addr_freq, f, protocol=pickle.HIGHEST_PROTOCOL)

    print(f"\n{prefix} indexes saved.")
    print("Name tokens:", len(name_index))
    print("Address tokens:", len(addr_index))

    return df


full_test_s2 = build_indexes(S2_PATH, "s2")
full_test_s3 = build_indexes(S3_PATH, "s3")

print("\n" + "=" * 70)
print("FULL TEST INDEX BUILD COMPLETE")
print("=" * 70)

Reading s2...
s2 shape: (4887273, 4)
s2: 1,000,000 rows processed
s2: 2,000,000 rows processed
s2: 3,000,000 rows processed
s2: 4,000,000 rows processed

s2 indexes saved.
Name tokens: 861199
Address tokens: 1330963

Reading s3...
s3 shape: (5082316, 4)
s3: 1,000,000 rows processed
s3: 2,000,000 rows processed
s3: 3,000,000 rows processed
s3: 4,000,000 rows processed
s3: 5,000,000 rows processed

s3 indexes saved.
Name tokens: 918689
Address tokens: 1296266

======================================================================
FULL TEST INDEX BUILD COMPLETE
======================================================================

In [ ]:
# ============================================================
# VERIFY V5 MODEL
# ============================================================

import os
from catboost import CatBoostClassifier

V5_MODEL = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm"

print("Model exists:", os.path.exists(V5_MODEL))
print("Model size (MB):", round(os.path.getsize(V5_MODEL) / 1024**2, 2))

v5_model = CatBoostClassifier()
v5_model.load_model(V5_MODEL)

print("V5 model loaded successfully.")

print("Number of features:", v5_model.feature_count_)

Model exists: True
Model size (MB): 1.41
V5 model loaded successfully.

AttributeError: 'CatBoostClassifier' object has no attribute 'feature_count_'

In [ ]:
# ============================================================
# FINAL V5 MODEL CHECK
# ============================================================

V5_FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]

print("V5 model loaded:", v5_model.is_fitted())
print("Expected features:", len(V5_FEATURES))
print("Model features:", v5_model.get_feature_count())

print("\nFeature list:")
for i, f in enumerate(V5_FEATURES, 1):
    print(f"{i:2}. {f}")

assert v5_model.get_feature_count() == 20

print("\n" + "=" * 60)
print("V5 MODEL VERIFIED")
print("=" * 60)

V5 model loaded: True
Expected features: 20

AttributeError: 'CatBoostClassifier' object has no attribute 'get_feature_count'

In [ ]:
# ============================================================
# V5 FULL TEST INFERENCE
#
# Blocker:
#   same country
#   >=2 shared rare name tokens (freq <=500)
#       + name similarity >=0.60
#   OR
#   >=2 shared rare address tokens (freq <=500)
#       + address similarity >=0.60
#   OR exact name/address
#
# V5 CatBoost threshold = 0.60
# ============================================================

import os
import re
import csv
import numpy as np
import pandas as pd
from collections import defaultdict
from difflib import SequenceMatcher

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

OUTPUT_DIR = "/content/amazon_ml_challenge/student_resource/output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

RESULT_PATH = os.path.join(
    OUTPUT_DIR,
    "matching_results_v5.tsv"
)

CANDIDATE_PATH = os.path.join(
    OUTPUT_DIR,
    "candidate_pairs_v5.tsv"
)

# ------------------------------------------------------------
# Settings
# ------------------------------------------------------------

V5_THRESHOLD = 0.60
RARITY_LIMIT = 500
S1_CHUNK = 500

print("=" * 75)
print("V5 FULL TEST INFERENCE")
print("=" * 75)
print("Threshold :", V5_THRESHOLD)
print("Rarity    :", RARITY_LIMIT)
print("S1 chunk  :", S1_CHUNK)
print()


# ============================================================
# NORMALIZATION
# ============================================================

def normalize_advanced_local(x):

    if pd.isna(x):
        return ""

    text = str(x).lower().strip()

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def tokens_fast(x):
    if not x:
        return set()
    return set(x.split())


def seq_sim(a, b):

    if not a or not b:
        return 0.0

    return SequenceMatcher(None, a, b).ratio()


def extract_numbers_fast(x):

    if not x:
        return set()

    return set(re.findall(r"\d+", x))


# ============================================================
# PREPARE FULL SOURCE ARRAYS
# ============================================================

print("Preparing source normalization...")

# We already have these DataFrames in memory.
s2 = full_test_s2
s3 = full_test_s3

# Advanced normalization required by V5
if "name_a" not in s2.columns:

    s2["name_a"] = s2["business_name"].map(
        normalize_advanced_local
    )

    s2["addr_a"] = s2["business_address"].map(
        normalize_advanced_local
    )

    s2["country_a"] = s2["country"].map(
        lambda x: "" if pd.isna(x) else str(x).lower().strip()
    )


if "name_a" not in s3.columns:

    s3["name_a"] = s3["business_name"].map(
        normalize_advanced_local
    )

    s3["addr_a"] = s3["business_address"].map(
        normalize_advanced_local
    )

    s3["country_a"] = s3["country"].map(
        lambda x: "" if pd.isna(x) else str(x).lower().strip()
    )


print("S2 prepared:", s2.shape)
print("S3 prepared:", s3.shape)


# ============================================================
# BUILD FAST RARE TOKEN INDEXES
# ============================================================

print("\nPreparing rare-token indexes...")


def build_rare_index(df, name_prefix):

    name_idx = defaultdict(list)
    addr_idx = defaultdict(list)

    name_freq_local = defaultdict(int)
    addr_freq_local = defaultdict(int)

    # First pass: frequencies
    for value in df["name_n"]:
        for t in tokens_fast(value):
            name_freq_local[t] += 1

    for value in df["addr_n"]:
        for t in tokens_fast(value):
            addr_freq_local[t] += 1

    # Second pass: only rare tokens
    for i, (name, addr) in enumerate(
        zip(df["name_n"], df["addr_n"])
    ):

        for t in tokens_fast(name):
            if name_freq_local[t] <= RARITY_LIMIT:
                name_idx[t].append(i)

        for t in tokens_fast(addr):
            if addr_freq_local[t] <= RARITY_LIMIT:
                addr_idx[t].append(i)

        if i > 0 and i % 1_000_000 == 0:
            print(name_prefix, i, "rows indexed")

    return dict(name_idx), dict(addr_idx)


# Use the indexes already created rather than rebuilding them.
# They correspond to the same simple normalized source columns.

s2_name_idx = s2_name_index
s2_addr_idx = s2_addr_index

s3_name_idx = s3_name_index
s3_addr_idx = s3_addr_index

print("Indexes ready.")


# ============================================================
# V5 FEATURE CREATION
# ============================================================

V5_FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]


def make_v5_pair_features(
    s1_name,
    s1_addr,
    s1_country,
    target_df,
    candidate_ids
):

    rows = []

    name1_tokens = tokens_fast(s1_name)
    addr1_tokens = tokens_fast(s1_addr)
    nums1 = extract_numbers_fast(s1_addr)

    for eid in candidate_ids:

        target = target_df.iloc[eid]

        name2 = target["name_a"]
        addr2 = target["addr_a"]
        country2 = target["country_a"]

        name2_tokens = tokens_fast(name2)
        addr2_tokens = tokens_fast(addr2)

        shared_name = name1_tokens & name2_tokens
        shared_addr = addr1_tokens & addr2_tokens
        shared_nums = nums1 & extract_numbers_fast(addr2)

        ns = seq_sim(s1_name, name2)
        ads = seq_sim(s1_addr, addr2)

        name_overlap = (
            len(shared_name) /
            max(1, min(len(name1_tokens), len(name2_tokens)))
        )

        addr_overlap = (
            len(shared_addr) /
            max(1, min(len(addr1_tokens), len(addr2_tokens)))
        )

        name_union = name1_tokens | name2_tokens
        addr_union = addr1_tokens | addr2_tokens

        name_j = (
            len(shared_name) /
            max(1, len(name_union))
        )

        addr_j = (
            len(shared_addr) /
            max(1, len(addr_union))
        )

        name_len_ratio = (
            min(len(s1_name), len(name2)) /
            max(1, max(len(s1_name), len(name2)))
        )

        addr_len_ratio = (
            min(len(s1_addr), len(addr2)) /
            max(1, max(len(s1_addr), len(addr2)))
        )

        row = {
            "name_exact": int(
                bool(s1_name) and s1_name == name2
            ),

            "address_exact": int(
                bool(s1_addr) and s1_addr == addr2
            ),

            "country_exact": int(
                s1_country == country2
            ),

            "name_similarity": ns,
            "address_similarity": ads,

            "name_token_overlap": name_overlap,
            "address_token_overlap": addr_overlap,

            "name_jaccard": name_j,
            "address_jaccard": addr_j,

            "shared_name_token_count": len(shared_name),
            "shared_address_token_count": len(shared_addr),
            "shared_address_number_count": len(shared_nums),

            "name_length_diff": abs(
                len(s1_name) - len(name2)
            ),

            "address_length_diff": abs(
                len(s1_addr) - len(addr2)
            ),

            "name_length_ratio": name_len_ratio,
            "address_length_ratio": addr_len_ratio,

            "similarity_gap": abs(ns - ads),

            "max_similarity": max(ns, ads),

            "similarity_product": ns * ads,

            "token_overlap_gap": abs(
                name_overlap - addr_overlap
            )
        }

        rows.append(row)

    return pd.DataFrame(
        rows,
        columns=V5_FEATURES
    )


# ============================================================
# CANDIDATE GENERATION
# ============================================================

def generate_candidates(
    s1_name,
    s1_addr,
    s1_country,
    name_idx,
    addr_idx,
    name_freq,
    addr_freq
):

    name_hits = defaultdict(int)
    addr_hits = defaultdict(int)

    # Name
    for token in tokens_fast(s1_name):

        if name_freq.get(token, 999999999) <= RARITY_LIMIT:

            for eid in name_idx.get(token, []):
                name_hits[eid] += 1

    # Address
    for token in tokens_fast(s1_addr):

        if addr_freq.get(token, 999999999) <= RARITY_LIMIT:

            for eid in addr_idx.get(token, []):
                addr_hits[eid] += 1

    candidate_ids = set()

    for eid, count in name_hits.items():

        if count >= 2:
            candidate_ids.add(eid)

    for eid, count in addr_hits.items():

        if count >= 2:
            candidate_ids.add(eid)

    return candidate_ids


# ============================================================
# START OUTPUT FILES
# ============================================================

# Remove old V5 files if they exist
for path in [RESULT_PATH, CANDIDATE_PATH]:

    if os.path.exists(path):
        os.remove(path)


result_header_written = False
candidate_header_written = False

total_candidates = 0
total_predictions = 0
total_s1 = 0
total_matched_s1 = 0


# ============================================================
# PROCESS S1 IN CHUNKS
# ============================================================

print("\n" + "=" * 75)
print("STARTING FULL V5 INFERENCE")
print("=" * 75)


for start in range(0, len(test_s1), S1_CHUNK):

    end = min(
        start + S1_CHUNK,
        len(test_s1)
    )

    chunk = test_s1.iloc[start:end]

    result_rows = []
    candidate_rows = []

    for _, row in chunk.iterrows():

        s1_id = row["entity_id"]

        name1 = normalize_advanced_local(
            row["business_name"]
        )

        addr1 = normalize_advanced_local(
            row["business_address"]
        )

        country1 = (
            "" if pd.isna(row["country"])
            else str(row["country"]).lower().strip()
        )

        # -----------------------------------------------
        # S2 candidates
        # -----------------------------------------------

        s2_candidates = generate_candidates(
            name1,
            addr1,
            country1,
            s2_name_idx,
            s2_addr_idx,
            s2_name_freq,
            s2_addr_freq
        )

        # -----------------------------------------------
        # S3 candidates
        # -----------------------------------------------

        s3_candidates = generate_candidates(
            name1,
            addr1,
            country1,
            s3_name_idx,
            s3_addr_idx,
            s3_name_freq,
            s3_addr_freq
        )

        # -----------------------------------------------
        # Filter country + exact rules + similarity
        # -----------------------------------------------

        selected_s2 = []
        selected_s3 = []

        # S2
        for eid in s2_candidates:

            target = s2.iloc[eid]

            if target["country_a"] != country1:
                continue

            name2 = target["name_a"]
            addr2 = target["addr_a"]

            # Exact
            if (
                (name1 and name1 == name2)
                or
                (addr1 and addr1 == addr2)
            ):
                selected_s2.append(eid)
                continue

            # Similarity
            ns = seq_sim(name1, name2)
            ads = seq_sim(addr1, addr2)

            if ns >= 0.60 or ads >= 0.60:
                selected_s2.append(eid)

        # S3
        for eid in s3_candidates:

            target = s3.iloc[eid]

            if target["country_a"] != country1:
                continue

            name2 = target["name_a"]
            addr2 = target["addr_a"]

            if (
                (name1 and name1 == name2)
                or
                (addr1 and addr1 == addr2)
            ):
                selected_s3.append(eid)
                continue

            ns = seq_sim(name1, name2)
            ads = seq_sim(addr1, addr2)

            if ns >= 0.60 or ads >= 0.60:
                selected_s3.append(eid)

        all_selected = [
            ("S2", eid) for eid in selected_s2
        ] + [
            ("S3", eid) for eid in selected_s3
        ]

        total_candidates += len(all_selected)

        # -----------------------------------------------
        # Candidate file
        # -----------------------------------------------

        candidate_ids_text = [
            (
                s2.iloc[eid]["entity_id"]
                if source == "S2"
                else s3.iloc[eid]["entity_id"]
            )
            for source, eid in all_selected
        ]

        candidate_rows.append({
            "source1_entity_id": s1_id,
            "candidate_entity_ids": ",".join(
                candidate_ids_text
            )
        })

        # -----------------------------------------------
        # V5 features + prediction
        # -----------------------------------------------

        if all_selected:

            s2_ids = [
                eid for source, eid in all_selected
                if source == "S2"
            ]

            s3_ids = [
                eid for source, eid in all_selected
                if source == "S3"
            ]

            feature_parts = []
            metadata = []

            if s2_ids:

                f2 = make_v5_pair_features(
                    name1,
                    addr1,
                    country1,
                    s2,
                    s2_ids
                )

                feature_parts.append(f2)

                metadata.extend(
                    [("S2", eid) for eid in s2_ids]
                )

            if s3_ids:

                f3 = make_v5_pair_features(
                    name1,
                    addr1,
                    country1,
                    s3,
                    s3_ids
                )

                feature_parts.append(f3)

                metadata.extend(
                    [("S3", eid) for eid in s3_ids]
                )

            X = pd.concat(
                feature_parts,
                ignore_index=True
            )[V5_FEATURES]

            probabilities = v5_model.predict_proba(X)[:, 1]

            predicted_ids = []

            for (source, eid), probability in zip(
                metadata,
                probabilities
            ):

                if probability >= V5_THRESHOLD:

                    entity_id = (
                        s2.iloc[eid]["entity_id"]
                        if source == "S2"
                        else s3.iloc[eid]["entity_id"]
                    )

                    predicted_ids.append(entity_id)

            total_predictions += len(predicted_ids)

        else:
            predicted_ids = []

        # -----------------------------------------------
        # Exactly one result row per S1
        # -----------------------------------------------

        result_rows.append({
            "source1_entity_id": s1_id,
            "matched_entity_ids": ",".join(
                predicted_ids
            )
        })

        total_s1 += 1

        if predicted_ids:
            total_matched_s1 += 1

    # ----------------------------------------------------
    # Write this chunk immediately
    # ----------------------------------------------------

    pd.DataFrame(result_rows).to_csv(
        RESULT_PATH,
        sep="\t",
        index=False,
        mode="a",
        header=not result_header_written
    )

    pd.DataFrame(candidate_rows).to_csv(
        CANDIDATE_PATH,
        sep="\t",
        index=False,
        mode="a",
        header=not candidate_header_written
    )

    result_header_written = True
    candidate_header_written = True

    print(
        f"Processed {end:,}/{len(test_s1):,} "
        f"| candidates: {total_candidates:,} "
        f"| predicted pairs: {total_predictions:,}"
    )


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 75)
print("V5 INFERENCE COMPLETE")
print("=" * 75)

print("S1 processed:", f"{total_s1:,}")
print("S1 with matches:", f"{total_matched_s1:,}")
print("S1 without matches:", f"{total_s1 - total_matched_s1:,}")
print("Candidate pairs:", f"{total_candidates:,}")
print("Predicted pairs:", f"{total_predictions:,}")

print("\nResult file:")
print(RESULT_PATH)

print("\nCandidate file:")
print(CANDIDATE_PATH)

print("\nFiles created successfully.")

===========================================================================
V5 FULL TEST INFERENCE
===========================================================================
Threshold : 0.6
Rarity    : 500
S1 chunk  : 500

Preparing source normalization...
S2 prepared: (4887273, 10)
S3 prepared: (5082316, 10)

Preparing rare-token indexes...
Indexes ready.

===========================================================================
STARTING FULL V5 INFERENCE
===========================================================================
Processed 500/1,732,544 | candidates: 7,543 | predicted pairs: 206
Processed 1,000/1,732,544 | candidates: 16,263 | predicted pairs: 393
Processed 1,500/1,732,544 | candidates: 24,479 | predicted pairs: 535
Processed 2,000/1,732,544 | candidates: 32,495 | predicted pairs: 718
Processed 2,500/1,732,544 | candidates: 41,006 | predicted pairs: 917
Processed 3,000/1,732,544 | candidates: 48,585 | predicted pairs: 1,076
Processed 3,500/1,732,544 | candidates: 55,197 | predicted pairs: 1,234
Processed 4,000/1,732,544 | candidates: 63,641 | predicted pairs: 1,418
Processed 4,500/1,732,544 | candidates: 71,249 | predicted pairs: 1,601
Processed 5,000/1,732,544 | candidates: 81,338 | predicted pairs: 1,823
Processed 5,500/1,732,544 | candidates: 87,421 | predicted pairs: 1,994
Processed 6,000/1,732,544 | candidates: 95,298 | predicted pairs: 2,290
Processed 6,500/1,732,544 | candidates: 102,802 | predicted pairs: 2,433
Processed 7,000/1,732,544 | candidates: 110,758 | predicted pairs: 2,762
Processed 7,500/1,732,544 | candidates: 119,322 | predicted pairs: 2,941
Processed 8,000/1,732,544 | candidates: 127,213 | predicted pairs: 3,149
Processed 8,500/1,732,544 | candidates: 134,643 | predicted pairs: 3,313
Processed 9,000/1,732,544 | candidates: 142,507 | predicted pairs: 3,505
Processed 9,500/1,732,544 | candidates: 150,703 | predicted pairs: 3,637
Processed 10,000/1,732,544 | candidates: 160,066 | predicted pairs: 3,806
Processed 10,500/1,732,544 | candidates: 167,764 | predicted pairs: 4,023
Processed 11,000/1,732,544 | candidates: 173,494 | predicted pairs: 4,141
Processed 11,500/1,732,544 | candidates: 180,626 | predicted pairs: 4,305
Processed 12,000/1,732,544 | candidates: 186,199 | predicted pairs: 4,442
Processed 12,500/1,732,544 | candidates: 194,566 | predicted pairs: 4,663
Processed 13,000/1,732,544 | candidates: 202,935 | predicted pairs: 4,855
Processed 13,500/1,732,544 | candidates: 209,413 | predicted pairs: 5,010
Processed 14,000/1,732,544 | candidates: 218,645 | predicted pairs: 5,232
Processed 14,500/1,732,544 | candidates: 224,792 | predicted pairs: 5,356
Processed 15,000/1,732,544 | candidates: 232,812 | predicted pairs: 5,516
Processed 15,500/1,732,544 | candidates: 241,838 | predicted pairs: 5,736
Processed 16,000/1,732,544 | candidates: 250,835 | predicted pairs: 5,971
Processed 16,500/1,732,544 | candidates: 258,306 | predicted pairs: 6,167
Processed 17,000/1,732,544 | candidates: 264,738 | predicted pairs: 6,305
Processed 17,500/1,732,544 | candidates: 272,151 | predicted pairs: 6,452
Processed 18,000/1,732,544 | candidates: 281,046 | predicted pairs: 6,662
Processed 18,500/1,732,544 | candidates: 289,437 | predicted pairs: 6,876
Processed 19,000/1,732,544 | candidates: 296,656 | predicted pairs: 7,102
Processed 19,500/1,732,544 | candidates: 304,325 | predicted pairs: 7,278
Processed 20,000/1,732,544 | candidates: 312,071 | predicted pairs: 7,411
Processed 20,500/1,732,544 | candidates: 320,190 | predicted pairs: 7,645
Processed 21,000/1,732,544 | candidates: 327,690 | predicted pairs: 7,858
Processed 21,500/1,732,544 | candidates: 335,690 | predicted pairs: 8,106
Processed 22,000/1,732,544 | candidates: 343,744 | predicted pairs: 8,382
Processed 22,500/1,732,544 | candidates: 350,964 | predicted pairs: 8,604
Processed 23,000/1,732,544 | candidates: 358,324 | predicted pairs: 8,744
Processed 23,500/1,732,544 | candidates: 366,305 | predicted pairs: 8,943
Processed 24,000/1,732,544 | candidates: 371,779 | predicted pairs: 9,100
Processed 24,500/1,732,544 | candidates: 378,322 | predicted pairs: 9,212
Processed 25,000/1,732,544 | candidates: 385,437 | predicted pairs: 9,471
Processed 25,500/1,732,544 | candidates: 393,562 | predicted pairs: 9,652
Processed 26,000/1,732,544 | candidates: 401,219 | predicted pairs: 9,883
Processed 26,500/1,732,544 | candidates: 411,210 | predicted pairs: 10,085
Processed 27,000/1,732,544 | candidates: 419,571 | predicted pairs: 10,277
Processed 27,500/1,732,544 | candidates: 427,127 | predicted pairs: 10,451
Processed 28,000/1,732,544 | candidates: 434,385 | predicted pairs: 10,652
Processed 28,500/1,732,544 | candidates: 440,776 | predicted pairs: 10,789
Processed 29,000/1,732,544 | candidates: 448,969 | predicted pairs: 10,928
Processed 29,500/1,732,544 | candidates: 456,281 | predicted pairs: 11,107
Processed 30,000/1,732,544 | candidates: 464,721 | predicted pairs: 11,279
Processed 30,500/1,732,544 | candidates: 473,289 | predicted pairs: 11,435
Processed 31,000/1,732,544 | candidates: 480,623 | predicted pairs: 11,584
Processed 31,500/1,732,544 | candidates: 489,177 | predicted pairs: 11,734
Processed 32,000/1,732,544 | candidates: 498,221 | predicted pairs: 11,994
Processed 32,500/1,732,544 | candidates: 506,680 | predicted pairs: 12,211
Processed 33,000/1,732,544 | candidates: 514,358 | predicted pairs: 12,465
Processed 33,500/1,732,544 | candidates: 522,002 | predicted pairs: 12,615
Processed 34,000/1,732,544 | candidates: 530,031 | predicted pairs: 12,838
Processed 34,500/1,732,544 | candidates: 536,757 | predicted pairs: 13,043
Processed 35,000/1,732,544 | candidates: 544,321 | predicted pairs: 13,206
Processed 35,500/1,732,544 | candidates: 553,199 | predicted pairs: 13,426
Processed 36,000/1,732,544 | candidates: 560,848 | predicted pairs: 13,604
Processed 36,500/1,732,544 | candidates: 569,230 | predicted pairs: 13,727
Processed 37,000/1,732,544 | candidates: 575,724 | predicted pairs: 13,850
Processed 37,500/1,732,544 | candidates: 584,004 | predicted pairs: 13,990
Processed 38,000/1,732,544 | candidates: 588,800 | predicted pairs: 14,150
Processed 38,500/1,732,544 | candidates: 596,249 | predicted pairs: 14,357
Processed 39,000/1,732,544 | candidates: 602,066 | predicted pairs: 14,479
Processed 39,500/1,732,544 | candidates: 610,232 | predicted pairs: 14,644
Processed 40,000/1,732,544 | candidates: 618,867 | predicted pairs: 14,790
Processed 40,500/1,732,544 | candidates: 626,841 | predicted pairs: 15,025
Processed 41,000/1,732,544 | candidates: 633,698 | predicted pairs: 15,142
Processed 41,500/1,732,544 | candidates: 644,267 | predicted pairs: 15,468
Processed 42,000/1,732,544 | candidates: 652,724 | predicted pairs: 15,680
Processed 42,500/1,732,544 | candidates: 659,540 | predicted pairs: 15,863
Processed 43,000/1,732,544 | candidates: 667,756 | predicted pairs: 16,019
Processed 43,500/1,732,544 | candidates: 677,100 | predicted pairs: 16,221
Processed 44,000/1,732,544 | candidates: 683,459 | predicted pairs: 16,413
Processed 44,500/1,732,544 | candidates: 688,950 | predicted pairs: 16,552
Processed 45,000/1,732,544 | candidates: 697,311 | predicted pairs: 16,867
Processed 45,500/1,732,544 | candidates: 705,682 | predicted pairs: 17,074
Processed 46,000/1,732,544 | candidates: 713,451 | predicted pairs: 17,249
Processed 46,500/1,732,544 | candidates: 721,703 | predicted pairs: 17,398
Processed 47,000/1,732,544 | candidates: 728,429 | predicted pairs: 17,586
Processed 47,500/1,732,544 | candidates: 735,443 | predicted pairs: 17,733
Processed 48,000/1,732,544 | candidates: 744,088 | predicted pairs: 17,883
Processed 48,500/1,732,544 | candidates: 752,769 | predicted pairs: 18,064
Processed 49,000/1,732,544 | candidates: 760,205 | predicted pairs: 18,217
Processed 49,500/1,732,544 | candidates: 767,481 | predicted pairs: 18,388
Processed 50,000/1,732,544 | candidates: 774,168 | predicted pairs: 18,513
Processed 50,500/1,732,544 | candidates: 783,393 | predicted pairs: 18,719
Processed 51,000/1,732,544 | candidates: 790,856 | predicted pairs: 18,916
Processed 51,500/1,732,544 | candidates: 798,805 | predicted pairs: 19,044
Processed 52,000/1,732,544 | candidates: 806,838 | predicted pairs: 19,244
Processed 52,500/1,732,544 | candidates: 813,728 | predicted pairs: 19,368
Processed 53,000/1,732,544 | candidates: 820,628 | predicted pairs: 19,595
Processed 53,500/1,732,544 | candidates: 827,777 | predicted pairs: 19,738
Processed 54,000/1,732,544 | candidates: 835,938 | predicted pairs: 19,935
Processed 54,500/1,732,544 | candidates: 843,505 | predicted pairs: 20,091
Processed 55,000/1,732,544 | candidates: 853,273 | predicted pairs: 20,245
Processed 55,500/1,732,544 | candidates: 859,695 | predicted pairs: 20,359
Processed 56,000/1,732,544 | candidates: 865,262 | predicted pairs: 20,486
Processed 56,500/1,732,544 | candidates: 872,770 | predicted pairs: 20,622
Processed 57,000/1,732,544 | candidates: 879,269 | predicted pairs: 20,791
Processed 57,500/1,732,544 | candidates: 886,303 | predicted pairs: 20,942
Processed 58,000/1,732,544 | candidates: 892,542 | predicted pairs: 21,101
Processed 58,500/1,732,544 | candidates: 900,465 | predicted pairs: 21,286
Processed 59,000/1,732,544 | candidates: 907,152 | predicted pairs: 21,484
Processed 59,500/1,732,544 | candidates: 916,087 | predicted pairs: 21,632
Processed 60,000/1,732,544 | candidates: 925,763 | predicted pairs: 21,876
Processed 60,500/1,732,544 | candidates: 933,433 | predicted pairs: 22,063
Processed 61,000/1,732,544 | candidates: 939,906 | predicted pairs: 22,269
Processed 61,500/1,732,544 | candidates: 947,562 | predicted pairs: 22,512
Processed 62,000/1,732,544 | candidates: 954,858 | predicted pairs: 22,655
Processed 62,500/1,732,544 | candidates: 962,747 | predicted pairs: 22,890
Processed 63,000/1,732,544 | candidates: 971,717 | predicted pairs: 23,112
Processed 63,500/1,732,544 | candidates: 979,711 | predicted pairs: 23,309
Processed 64,000/1,732,544 | candidates: 988,181 | predicted pairs: 23,482
Processed 64,500/1,732,544 | candidates: 995,351 | predicted pairs: 23,732
Processed 65,000/1,732,544 | candidates: 1,003,612 | predicted pairs: 23,924
Processed 65,500/1,732,544 | candidates: 1,013,250 | predicted pairs: 24,183
Processed 66,000/1,732,544 | candidates: 1,021,067 | predicted pairs: 24,380
Processed 66,500/1,732,544 | candidates: 1,027,773 | predicted pairs: 24,496
Processed 67,000/1,732,544 | candidates: 1,036,316 | predicted pairs: 24,678
Processed 67,500/1,732,544 | candidates: 1,044,635 | predicted pairs: 24,829
Processed 68,000/1,732,544 | candidates: 1,052,257 | predicted pairs: 25,036
Processed 68,500/1,732,544 | candidates: 1,060,167 | predicted pairs: 25,182
Processed 69,000/1,732,544 | candidates: 1,068,166 | predicted pairs: 25,360
Processed 69,500/1,732,544 | candidates: 1,075,582 | predicted pairs: 25,514
Processed 70,000/1,732,544 | candidates: 1,084,931 | predicted pairs: 25,723
Processed 70,500/1,732,544 | candidates: 1,092,339 | predicted pairs: 25,936
Processed 71,000/1,732,544 | candidates: 1,102,553 | predicted pairs: 26,133
Processed 71,500/1,732,544 | candidates: 1,107,931 | predicted pairs: 26,250
Processed 72,000/1,732,544 | candidates: 1,116,392 | predicted pairs: 26,441
Processed 72,500/1,732,544 | candidates: 1,124,934 | predicted pairs: 26,627
Processed 73,000/1,732,544 | candidates: 1,133,887 | predicted pairs: 27,006
Processed 73,500/1,732,544 | candidates: 1,141,170 | predicted pairs: 27,213
Processed 74,000/1,732,544 | candidates: 1,149,680 | predicted pairs: 27,425
Processed 74,500/1,732,544 | candidates: 1,157,088 | predicted pairs: 27,670
Processed 75,000/1,732,544 | candidates: 1,162,649 | predicted pairs: 27,817
Processed 75,500/1,732,544 | candidates: 1,169,763 | predicted pairs: 27,960
Processed 76,000/1,732,544 | candidates: 1,175,882 | predicted pairs: 28,134
Processed 76,500/1,732,544 | candidates: 1,183,330 | predicted pairs: 28,306
Processed 77,000/1,732,544 | candidates: 1,190,048 | predicted pairs: 28,507
Processed 77,500/1,732,544 | candidates: 1,197,327 | predicted pairs: 28,699
Processed 78,000/1,732,544 | candidates: 1,205,940 | predicted pairs: 28,898
Processed 78,500/1,732,544 | candidates: 1,214,110 | predicted pairs: 29,076
Processed 79,000/1,732,544 | candidates: 1,222,825 | predicted pairs: 29,265
Processed 79,500/1,732,544 | candidates: 1,229,923 | predicted pairs: 29,430
Processed 80,000/1,732,544 | candidates: 1,239,572 | predicted pairs: 29,590
Processed 80,500/1,732,544 | candidates: 1,248,264 | predicted pairs: 29,816
Processed 81,000/1,732,544 | candidates: 1,256,051 | predicted pairs: 30,092
Processed 81,500/1,732,544 | candidates: 1,264,249 | predicted pairs: 30,290
Processed 82,000/1,732,544 | candidates: 1,270,967 | predicted pairs: 30,491
Processed 82,500/1,732,544 | candidates: 1,276,019 | predicted pairs: 30,707
Processed 83,000/1,732,544 | candidates: 1,283,203 | predicted pairs: 30,919
Processed 83,500/1,732,544 | candidates: 1,291,297 | predicted pairs: 31,060
Processed 84,000/1,732,544 | candidates: 1,298,251 | predicted pairs: 31,201
Processed 84,500/1,732,544 | candidates: 1,305,850 | predicted pairs: 31,394
Processed 85,000/1,732,544 | candidates: 1,314,133 | predicted pairs: 31,549
Processed 85,500/1,732,544 | candidates: 1,321,697 | predicted pairs: 31,749
Processed 86,000/1,732,544 | candidates: 1,330,120 | predicted pairs: 31,940
Processed 86,500/1,732,544 | candidates: 1,337,090 | predicted pairs: 32,087
Processed 87,000/1,732,544 | candidates: 1,345,257 | predicted pairs: 32,233
Processed 87,500/1,732,544 | candidates: 1,351,473 | predicted pairs: 32,364
Processed 88,000/1,732,544 | candidates: 1,357,124 | predicted pairs: 32,522
Processed 88,500/1,732,544 | candidates: 1,365,409 | predicted pairs: 32,707
Processed 89,000/1,732,544 | candidates: 1,372,191 | predicted pairs: 32,858
Processed 89,500/1,732,544 | candidates: 1,379,999 | predicted pairs: 33,073
Processed 90,000/1,732,544 | candidates: 1,386,075 | predicted pairs: 33,206
Processed 90,500/1,732,544 | candidates: 1,394,261 | predicted pairs: 33,366
Processed 91,000/1,732,544 | candidates: 1,402,141 | predicted pairs: 33,536
Processed 91,500/1,732,544 | candidates: 1,409,678 | predicted pairs: 33,733
Processed 92,000/1,732,544 | candidates: 1,416,620 | predicted pairs: 33,869
Processed 92,500/1,732,544 | candidates: 1,425,441 | predicted pairs: 34,053
Processed 93,000/1,732,544 | candidates: 1,432,974 | predicted pairs: 34,366
Processed 93,500/1,732,544 | candidates: 1,440,469 | predicted pairs: 34,531
Processed 94,000/1,732,544 | candidates: 1,449,015 | predicted pairs: 34,804
Processed 94,500/1,732,544 | candidates: 1,456,661 | predicted pairs: 35,086
Processed 95,000/1,732,544 | candidates: 1,464,165 | predicted pairs: 35,278
Processed 95,500/1,732,544 | candidates: 1,471,551 | predicted pairs: 35,488
Processed 96,000/1,732,544 | candidates: 1,478,429 | predicted pairs: 35,661
Processed 96,500/1,732,544 | candidates: 1,488,251 | predicted pairs: 35,822
Processed 97,000/1,732,544 | candidates: 1,496,509 | predicted pairs: 36,004
Processed 97,500/1,732,544 | candidates: 1,504,327 | predicted pairs: 36,165
Processed 98,000/1,732,544 | candidates: 1,513,083 | predicted pairs: 36,364
Processed 98,500/1,732,544 | candidates: 1,521,282 | predicted pairs: 36,575
Processed 99,000/1,732,544 | candidates: 1,527,683 | predicted pairs: 36,778
Processed 99,500/1,732,544 | candidates: 1,535,918 | predicted pairs: 36,953
Processed 100,000/1,732,544 | candidates: 1,542,987 | predicted pairs: 37,150
Processed 100,500/1,732,544 | candidates: 1,551,129 | predicted pairs: 37,300
Processed 101,000/1,732,544 | candidates: 1,560,009 | predicted pairs: 37,447
Processed 101,500/1,732,544 | candidates: 1,568,756 | predicted pairs: 37,616
Processed 102,000/1,732,544 | candidates: 1,578,218 | predicted pairs: 37,880
Processed 102,500/1,732,544 | candidates: 1,585,042 | predicted pairs: 38,010
Processed 103,000/1,732,544 | candidates: 1,591,611 | predicted pairs: 38,132
Processed 103,500/1,732,544 | candidates: 1,600,195 | predicted pairs: 38,302
Processed 104,000/1,732,544 | candidates: 1,608,016 | predicted pairs: 38,513
Processed 104,500/1,732,544 | candidates: 1,615,665 | predicted pairs: 38,715
Processed 105,000/1,732,544 | candidates: 1,625,177 | predicted pairs: 38,873
Processed 105,500/1,732,544 | candidates: 1,632,139 | predicted pairs: 38,992
Processed 106,000/1,732,544 | candidates: 1,641,013 | predicted pairs: 39,222
Processed 106,500/1,732,544 | candidates: 1,649,470 | predicted pairs: 39,426
Processed 107,000/1,732,544 | candidates: 1,655,434 | predicted pairs: 39,554
Processed 107,500/1,732,544 | candidates: 1,662,685 | predicted pairs: 39,722
Processed 108,000/1,732,544 | candidates: 1,669,224 | predicted pairs: 39,885
Processed 108,500/1,732,544 | candidates: 1,677,000 | predicted pairs: 40,088
Processed 109,000/1,732,544 | candidates: 1,686,007 | predicted pairs: 40,307
Processed 109,500/1,732,544 | candidates: 1,692,924 | predicted pairs: 40,487
Processed 110,000/1,732,544 | candidates: 1,700,404 | predicted pairs: 40,645
Processed 110,500/1,732,544 | candidates: 1,708,468 | predicted pairs: 40,798
Processed 111,000/1,732,544 | candidates: 1,715,229 | predicted pairs: 40,921
Processed 111,500/1,732,544 | candidates: 1,722,727 | predicted pairs: 41,129
Processed 112,000/1,732,544 | candidates: 1,730,034 | predicted pairs: 41,303
Processed 112,500/1,732,544 | candidates: 1,737,446 | predicted pairs: 41,479
Processed 113,000/1,732,544 | candidates: 1,746,855 | predicted pairs: 41,614
Processed 113,500/1,732,544 | candidates: 1,754,422 | predicted pairs: 41,829
Processed 114,000/1,732,544 | candidates: 1,761,771 | predicted pairs: 42,009
Processed 114,500/1,732,544 | candidates: 1,767,989 | predicted pairs: 42,178

KeyboardInterrupt:

In [ ]:
!pip install rapidfuzz

# ============================================================
# OPTIMIZED V5 BENCHMARK
# ONLY 5,000 S1 ROWS
# ============================================================

import time
import numpy as np
from collections import defaultdict

try:
    from rapidfuzz.fuzz import ratio
    print("RapidFuzz: available")
except ImportError:
    print("RapidFuzz not installed.")
    print("Run: !pip install rapidfuzz")
    raise


# ------------------------------------------------------------
# Convert source columns to NumPy arrays
# ------------------------------------------------------------

print("Preparing fast NumPy arrays...")

s2_names = s2["name_n"].fillna("").to_numpy()
s2_addrs = s2["addr_n"].fillna("").to_numpy()
s2_countries = s2["country_n"].fillna("").to_numpy()

s3_names = s3["name_n"].fillna("").to_numpy()
s3_addrs = s3["addr_n"].fillna("").to_numpy()
s3_countries = s3["country_n"].fillna("").to_numpy()

s2_ids = s2["entity_id"].to_numpy()
s3_ids = s3["entity_id"].to_numpy()

print("Arrays ready.")


# ------------------------------------------------------------
# Fast candidate generation
# ------------------------------------------------------------

def fast_candidates(
    name1,
    addr1,
    country1,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    names,
    addrs,
    countries
):

    name_hits = defaultdict(int)
    addr_hits = defaultdict(int)

    # Name tokens
    for token in name1.split():

        if name_freq.get(token, 999999999) <= 500:

            for eid in name_index.get(token, ()):
                name_hits[eid] += 1

    # Address tokens
    for token in addr1.split():

        if addr_freq.get(token, 999999999) <= 500:

            for eid in addr_index.get(token, ()):
                addr_hits[eid] += 1

    candidates = set()

    # >=2 name tokens
    for eid, count in name_hits.items():

        if count >= 2:
            if countries[eid] == country1:
                candidates.add(eid)

    # >=2 address tokens
    for eid, count in addr_hits.items():

        if count >= 2:
            if countries[eid] == country1:
                candidates.add(eid)

    return candidates, name_hits, addr_hits


# ------------------------------------------------------------
# Benchmark
# ------------------------------------------------------------

BENCHMARK_N = 5000

start_time = time.time()

candidate_total = 0
selected_total = 0

for i in range(BENCHMARK_N):

    if i % 500 == 0:
        elapsed = time.time() - start_time
        print(
            f"{i}/{BENCHMARK_N} "
            f"| elapsed: {elapsed:.1f}s"
        )

    row = test_s1.iloc[i]

    name1 = normalize_advanced_local(row["business_name"])
    addr1 = normalize_advanced_local(row["business_address"])

    country1 = (
        "" if pd.isna(row["country"])
        else str(row["country"]).lower().strip()
    )

    # --------------------------------------------------------
    # S2
    # --------------------------------------------------------

    candidates2, name_hits2, addr_hits2 = fast_candidates(
        name1,
        addr1,
        country1,
        s2_name_index,
        s2_addr_index,
        s2_name_freq,
        s2_addr_freq,
        s2_names,
        s2_addrs,
        s2_countries
    )

    candidate_total += len(candidates2)

    for eid in candidates2:

        # Exact match
        if (
            name1 == s2_names[eid]
            or addr1 == s2_addrs[eid]
        ):
            selected_total += 1
            continue

        # Name similarity
        if name_hits2.get(eid, 0) >= 2:

            if ratio(name1, s2_names[eid]) >= 60:
                selected_total += 1
                continue

        # Address similarity
        if addr_hits2.get(eid, 0) >= 2:

            if ratio(addr1, s2_addrs[eid]) >= 60:
                selected_total += 1
                continue

    # --------------------------------------------------------
    # S3
    # --------------------------------------------------------

    candidates3, name_hits3, addr_hits3 = fast_candidates(
        name1,
        addr1,
        country1,
        s3_name_index,
        s3_addr_index,
        s3_name_freq,
        s3_addr_freq,
        s3_names,
        s3_addrs,
        s3_countries
    )

    candidate_total += len(candidates3)

    for eid in candidates3:

        if (
            name1 == s3_names[eid]
            or addr1 == s3_addrs[eid]
        ):
            selected_total += 1
            continue

        if name_hits3.get(eid, 0) >= 2:

            if ratio(name1, s3_names[eid]) >= 60:
                selected_total += 1
                continue

        if addr_hits3.get(eid, 0) >= 2:

            if ratio(addr1, s3_addrs[eid]) >= 60:
                selected_total += 1
                continue


elapsed = time.time() - start_time

print("\n" + "=" * 70)
print("OPTIMIZED BENCHMARK COMPLETE")
print("=" * 70)

print("S1 tested:", BENCHMARK_N)
print("Raw candidates:", f"{candidate_total:,}")
print("Selected candidates:", f"{selected_total:,}")

print("Time:", round(elapsed, 2), "seconds")
print("Time:", round(elapsed / 60, 2), "minutes")

print(
    "Estimated full runtime at same speed:",
    round(elapsed * 1_732_544 / BENCHMARK_N / 3600, 2),
    "hours"
)

print(
    "Average selected candidates/S1:",
    round(selected_total / BENCHMARK_N, 2)
)

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 14.9 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.6
RapidFuzz: available
Preparing fast NumPy arrays...
Arrays ready.
0/5000 | elapsed: 0.0s
500/5000 | elapsed: 0.8s
1000/5000 | elapsed: 1.7s
1500/5000 | elapsed: 2.5s
2000/5000 | elapsed: 3.3s
2500/5000 | elapsed: 4.1s
3000/5000 | elapsed: 4.6s
3500/5000 | elapsed: 5.1s
4000/5000 | elapsed: 5.6s
4500/5000 | elapsed: 6.1s

======================================================================
OPTIMIZED BENCHMARK COMPLETE
======================================================================
S1 tested: 5000
Raw candidates: 349,649
Selected candidates: 70,882
Time: 6.68 seconds
Time: 0.11 minutes
Estimated full runtime at same speed: 0.64 hours
Average selected candidates/S1: 14.18

In [ ]:
# ============================================================
# COMPLETE V5 BENCHMARK
# 5,000 S1 rows
# Candidate generation + 20 V5 features + CatBoost
# ============================================================

import time
import re
import numpy as np
import pandas as pd
from collections import defaultdict
from rapidfuzz.fuzz import ratio

BENCHMARK_N = 5000
THRESHOLD = 0.60

numbers_re = re.compile(r"\d+")

def number_set(x):
    if not x:
        return set()
    return set(numbers_re.findall(x))


def build_fast_features(
    s1_name,
    s1_addr,
    s1_country,
    source_names,
    source_addrs,
    source_countries,
    candidate_ids
):
    """
    Build the exact 20 V5 features.
    """

    n1 = set(s1_name.split())
    a1 = set(s1_addr.split())
    nums1 = number_set(s1_addr)

    rows = []

    for eid in candidate_ids:

        n2 = source_names[eid]
        a2 = source_addrs[eid]
        c2 = source_countries[eid]

        n2_tokens = set(n2.split())
        a2_tokens = set(a2.split())

        shared_n = n1 & n2_tokens
        shared_a = a1 & a2_tokens
        shared_nums = nums1 & number_set(a2)

        ns = ratio(s1_name, n2) / 100.0
        ads = ratio(s1_addr, a2) / 100.0

        n_overlap = (
            len(shared_n) /
            max(1, min(len(n1), len(n2_tokens)))
        )

        a_overlap = (
            len(shared_a) /
            max(1, min(len(a1), len(a2_tokens)))
        )

        n_union = n1 | n2_tokens
        a_union = a1 | a2_tokens

        n_jaccard = len(shared_n) / max(1, len(n_union))
        a_jaccard = len(shared_a) / max(1, len(a_union))

        n_len_ratio = (
            min(len(s1_name), len(n2)) /
            max(1, max(len(s1_name), len(n2)))
        )

        a_len_ratio = (
            min(len(s1_addr), len(a2)) /
            max(1, max(len(s1_addr), len(a2)))
        )

        rows.append([
            int(bool(s1_name) and s1_name == n2),
            int(bool(s1_addr) and s1_addr == a2),
            int(s1_country == c2),

            ns,
            ads,

            n_overlap,
            a_overlap,

            n_jaccard,
            a_jaccard,

            len(shared_n),
            len(shared_a),
            len(shared_nums),

            abs(len(s1_name) - len(n2)),
            abs(len(s1_addr) - len(a2)),

            n_len_ratio,
            a_len_ratio,

            abs(ns - ads),
            max(ns, ads),
            ns * ads,
            abs(n_overlap - a_overlap)
        ])

    return np.asarray(rows, dtype=np.float32)


# ============================================================
# SOURCE ARRAYS
# ============================================================

print("Preparing arrays...")

s2_names_a = s2["name_a"].fillna("").to_numpy()
s2_addrs_a = s2["addr_a"].fillna("").to_numpy()
s2_countries_a = s2["country_a"].fillna("").to_numpy()

s3_names_a = s3["name_a"].fillna("").to_numpy()
s3_addrs_a = s3["addr_a"].fillna("").to_numpy()
s3_countries_a = s3["country_a"].fillna("").to_numpy()

print("Arrays ready.")


# ============================================================
# CANDIDATE GENERATION
# ============================================================

def get_fast_candidates(
    name1,
    addr1,
    country1,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    names,
    addrs,
    countries
):

    name_hits = defaultdict(int)
    addr_hits = defaultdict(int)

    for token in name1.split():

        if name_freq.get(token, 999999999) <= 500:

            for eid in name_index.get(token, ()):

                if countries[eid] == country1:
                    name_hits[eid] += 1

    for token in addr1.split():

        if addr_freq.get(token, 999999999) <= 500:

            for eid in addr_index.get(token, ()):

                if countries[eid] == country1:
                    addr_hits[eid] += 1

    candidates = set()

    for eid, count in name_hits.items():

        if count >= 2:
            candidates.add(eid)

    for eid, count in addr_hits.items():

        if count >= 2:
            candidates.add(eid)

    return candidates


# ============================================================
# COMPLETE BENCHMARK
# ============================================================

print("\nStarting complete V5 benchmark...")

start_time = time.time()

all_features = []
all_metadata = []

raw_candidates = 0
selected_candidates = 0

for i in range(BENCHMARK_N):

    if i % 500 == 0:

        elapsed = time.time() - start_time

        print(
            f"{i}/{BENCHMARK_N} "
            f"| elapsed {elapsed:.1f}s "
            f"| selected {selected_candidates:,}"
        )

    row = test_s1.iloc[i]

    name1 = normalize_advanced_local(
        row["business_name"]
    )

    addr1 = normalize_advanced_local(
        row["business_address"]
    )

    country1 = (
        ""
        if pd.isna(row["country"])
        else str(row["country"]).lower().strip()
    )

    # --------------------------------------------------------
    # S2
    # --------------------------------------------------------

    candidates2 = get_fast_candidates(
        name1,
        addr1,
        country1,
        s2_name_index,
        s2_addr_index,
        s2_name_freq,
        s2_addr_freq,
        s2_names_a,
        s2_addrs_a,
        s2_countries_a
    )

    raw_candidates += len(candidates2)

    selected2 = []

    for eid in candidates2:

        n2 = s2_names_a[eid]
        a2 = s2_addrs_a[eid]

        if (
            (name1 and name1 == n2)
            or
            (addr1 and addr1 == a2)
        ):
            selected2.append(eid)
            continue

        if ratio(name1, n2) >= 60:
            selected2.append(eid)
            continue

        if ratio(addr1, a2) >= 60:
            selected2.append(eid)
            continue

    # --------------------------------------------------------
    # S3
    # --------------------------------------------------------

    candidates3 = get_fast_candidates(
        name1,
        addr1,
        country1,
        s3_name_index,
        s3_addr_index,
        s3_name_freq,
        s3_addr_freq,
        s3_names_a,
        s3_addrs_a,
        s3_countries_a
    )

    raw_candidates += len(candidates3)

    selected3 = []

    for eid in candidates3:

        n2 = s3_names_a[eid]
        a2 = s3_addrs_a[eid]

        if (
            (name1 and name1 == n2)
            or
            (addr1 and addr1 == a2)
        ):
            selected3.append(eid)
            continue

        if ratio(name1, n2) >= 60:
            selected3.append(eid)
            continue

        if ratio(addr1, a2) >= 60:
            selected3.append(eid)
            continue

    selected_candidates += len(selected2) + len(selected3)

    # --------------------------------------------------------
    # Build V5 features
    # --------------------------------------------------------

    if selected2:

        X2 = build_fast_features(
            name1,
            addr1,
            country1,
            s2_names_a,
            s2_addrs_a,
            s2_countries_a,
            selected2
        )

        all_features.append(X2)

        all_metadata.extend(
            [("S2", eid) for eid in selected2]
        )

    if selected3:

        X3 = build_fast_features(
            name1,
            addr1,
            country1,
            s3_names_a,
            s3_addrs_a,
            s3_countries_a,
            selected3
        )

        all_features.append(X3)

        all_metadata.extend(
            [("S3", eid) for eid in selected3]
        )


# ============================================================
# BATCH V5 PREDICTION
# ============================================================

print("\nBuilding prediction matrix...")

X_benchmark = np.vstack(all_features)

print("Feature matrix:", X_benchmark.shape)

prediction_start = time.time()

probabilities = v5_model.predict_proba(
    X_benchmark
)[:, 1]

predicted = probabilities >= THRESHOLD

prediction_time = time.time() - prediction_start

total_time = time.time() - start_time


# ============================================================
# RESULTS
# ============================================================

print("\n" + "=" * 75)
print("COMPLETE V5 BENCHMARK RESULTS")
print("=" * 75)

print("S1 tested:", f"{BENCHMARK_N:,}")

print(
    "Raw candidates:",
    f"{raw_candidates:,}"
)

print(
    "Selected candidates:",
    f"{selected_candidates:,}"
)

print(
    "V5 feature matrix:",
    X_benchmark.shape
)

print(
    "Predicted matches:",
    f"{predicted.sum():,}"
)

print(
    "CatBoost prediction time:",
    round(prediction_time, 2),
    "seconds"
)

print(
    "Total benchmark time:",
    round(total_time, 2),
    "seconds"
)

print(
    "Total benchmark time:",
    round(total_time / 60, 2),
    "minutes"
)

estimated_hours = (
    total_time *
    1_732_544 /
    BENCHMARK_N /
    3600
)

print(
    "Estimated full runtime:",
    round(estimated_hours, 2),
    "hours"
)

print(
    "Average selected candidates/S1:",
    round(
        selected_candidates / BENCHMARK_N,
        2
    )
)

print(
    "Average predicted matches/S1:",
    round(
        predicted.sum() / BENCHMARK_N,
        3
    )
)

Preparing arrays...
Arrays ready.

Starting complete V5 benchmark...
0/5000 | elapsed 0.0s | selected 0
500/5000 | elapsed 0.9s | selected 9,776
1000/5000 | elapsed 1.9s | selected 20,883
1500/5000 | elapsed 2.8s | selected 31,379
2000/5000 | elapsed 3.7s | selected 41,630
2500/5000 | elapsed 4.7s | selected 52,192
3000/5000 | elapsed 5.6s | selected 61,985
3500/5000 | elapsed 6.5s | selected 70,908
4000/5000 | elapsed 7.9s | selected 81,851
4500/5000 | elapsed 9.3s | selected 91,693

Building prediction matrix...
Feature matrix: (104034, 20)

===========================================================================
COMPLETE V5 BENCHMARK RESULTS
===========================================================================
S1 tested: 5,000
Raw candidates: 349,649
Selected candidates: 104,034
V5 feature matrix: (104034, 20)
Predicted matches: 1,882
CatBoost prediction time: 0.29 seconds
Total benchmark time: 11.09 seconds
Total benchmark time: 0.18 minutes
Estimated full runtime: 1.07 hours
Average selected candidates/S1: 20.81
Average predicted matches/S1: 0.376

In [ ]:
# ============================================================
# HIGH-RECALL V5 BENCHMARK
# 5,000 S1 rows
# ============================================================

import time
import numpy as np
from rapidfuzz.fuzz import ratio
from collections import defaultdict

BENCHMARK_N = 5000
THRESHOLD = 0.60


def high_recall_candidates(
    name1,
    addr1,
    country1,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    names,
    addrs,
    countries
):
    name_hits = defaultdict(int)
    addr_hits = defaultdict(int)

    # --------------------------------------------------------
    # NAME TOKEN BLOCK
    # --------------------------------------------------------

    for token in name1.split():

        if name_freq.get(token, 999999999) <= 500:

            for eid in name_index.get(token, ()):

                if countries[eid] == country1:
                    name_hits[eid] += 1

    # --------------------------------------------------------
    # ADDRESS TOKEN BLOCK
    # --------------------------------------------------------

    for token in addr1.split():

        if addr_freq.get(token, 999999999) <= 500:

            for eid in addr_index.get(token, ()):

                if countries[eid] == country1:
                    addr_hits[eid] += 1

    # We need >=2 name OR >=2 address tokens
    candidate_ids = (
        {eid for eid, c in name_hits.items() if c >= 2}
        |
        {eid for eid, c in addr_hits.items() if c >= 2}
    )

    return candidate_ids, name_hits, addr_hits


print("Starting high-recall benchmark...")

start_time = time.time()

raw_candidates = 0
selected_candidates = 0
predicted_matches = 0

all_features = []

for i in range(BENCHMARK_N):

    if i % 500 == 0:

        elapsed = time.time() - start_time

        print(
            f"{i}/{BENCHMARK_N} "
            f"| elapsed {elapsed:.1f}s "
            f"| selected {selected_candidates:,}"
        )

    row = test_s1.iloc[i]

    name1 = normalize_advanced_local(
        row["business_name"]
    )

    addr1 = normalize_advanced_local(
        row["business_address"]
    )

    country1 = (
        ""
        if pd.isna(row["country"])
        else str(row["country"]).lower().strip()
    )

    # ========================================================
    # S2
    # ========================================================

    c2, nh2, ah2 = high_recall_candidates(
        name1,
        addr1,
        country1,
        s2_name_index,
        s2_addr_index,
        s2_name_freq,
        s2_addr_freq,
        s2_names_a,
        s2_addrs_a,
        s2_countries_a
    )

    raw_candidates += len(c2)

    selected2 = []

    for eid in c2:

        n2 = s2_names_a[eid]
        a2 = s2_addrs_a[eid]

        # Exact
        if (
            (name1 and name1 == n2)
            or
            (addr1 and addr1 == a2)
        ):
            selected2.append(eid)
            continue

        ns = ratio(name1, n2) / 100.0
        ads = ratio(addr1, a2) / 100.0

        # Name rule
        if (
            nh2.get(eid, 0) >= 2
            and ns >= 0.60
        ):
            selected2.append(eid)
            continue

        # Address >=3 tokens
        if ah2.get(eid, 0) >= 3:
            selected2.append(eid)
            continue

        # Address fallback
        if (
            ah2.get(eid, 0) >= 2
            and ads >= 0.30
        ):
            selected2.append(eid)
            continue

    # ========================================================
    # S3
    # ========================================================

    c3, nh3, ah3 = high_recall_candidates(
        name1,
        addr1,
        country1,
        s3_name_index,
        s3_addr_index,
        s3_name_freq,
        s3_addr_freq,
        s3_names_a,
        s3_addrs_a,
        s3_countries_a
    )

    raw_candidates += len(c3)

    selected3 = []

    for eid in c3:

        n2 = s3_names_a[eid]
        a2 = s3_addrs_a[eid]

        if (
            (name1 and name1 == n2)
            or
            (addr1 and addr1 == a2)
        ):
            selected3.append(eid)
            continue

        ns = ratio(name1, n2) / 100.0
        ads = ratio(addr1, a2) / 100.0

        if (
            nh3.get(eid, 0) >= 2
            and ns >= 0.60
        ):
            selected3.append(eid)
            continue

        if ah3.get(eid, 0) >= 3:
            selected3.append(eid)
            continue

        if (
            ah3.get(eid, 0) >= 2
            and ads >= 0.30
        ):
            selected3.append(eid)
            continue

    selected_candidates += len(selected2) + len(selected3)

    # ========================================================
    # V5 FEATURES
    # ========================================================

    if selected2:

        X2 = build_fast_features(
            name1,
            addr1,
            country1,
            s2_names_a,
            s2_addrs_a,
            s2_countries_a,
            selected2
        )

        all_features.append(X2)

    if selected3:

        X3 = build_fast_features(
            name1,
            addr1,
            country1,
            s3_names_a,
            s3_addrs_a,
            s3_countries_a,
            selected3
        )

        all_features.append(X3)


# ============================================================
# V5 PREDICTION
# ============================================================

print("\nBuilding feature matrix...")

X_high = np.vstack(all_features)

print("Feature matrix:", X_high.shape)

pred_start = time.time()

probs = v5_model.predict_proba(X_high)[:, 1]

predicted_matches = int(
    (probs >= THRESHOLD).sum()
)

pred_time = time.time() - pred_start
total_time = time.time() - start_time


# ============================================================
# RESULTS
# ============================================================

print("\n" + "=" * 75)
print("HIGH-RECALL BENCHMARK RESULTS")
print("=" * 75)

print("S1 tested:", f"{BENCHMARK_N:,}")
print("Raw candidates:", f"{raw_candidates:,}")
print("Selected candidates:", f"{selected_candidates:,}")
print("Feature matrix:", X_high.shape)
print("Predicted matches:", f"{predicted_matches:,}")

print(
    "Total time:",
    round(total_time, 2),
    "seconds"
)

print(
    "Estimated full runtime:",
    round(
        total_time * 1_732_544 / BENCHMARK_N / 3600,
        2
    ),
    "hours"
)

print(
    "Average selected candidates/S1:",
    round(
        selected_candidates / BENCHMARK_N,
        2
    )
)

print(
    "Average predicted matches/S1:",
    round(
        predicted_matches / BENCHMARK_N,
        3
    )
)

Starting high-recall benchmark...
0/5000 | elapsed 0.0s | selected 0
500/5000 | elapsed 1.7s | selected 31,759
1000/5000 | elapsed 3.2s | selected 66,027
1500/5000 | elapsed 5.6s | selected 99,633
2000/5000 | elapsed 7.8s | selected 131,247
2500/5000 | elapsed 9.5s | selected 164,068
3000/5000 | elapsed 10.9s | selected 194,187
3500/5000 | elapsed 12.4s | selected 226,331
4000/5000 | elapsed 13.8s | selected 256,924
4500/5000 | elapsed 15.2s | selected 291,541

Building feature matrix...
Feature matrix: (329290, 20)

===========================================================================
HIGH-RECALL BENCHMARK RESULTS
===========================================================================
S1 tested: 5,000
Raw candidates: 349,649
Selected candidates: 329,290
Feature matrix: (329290, 20)
Predicted matches: 1,946
Total time: 17.34 seconds
Estimated full runtime: 1.67 hours
Average selected candidates/S1: 65.86
Average predicted matches/S1: 0.389

In [ ]:
# ============================================================
# AMAZON ML CHALLENGE 2026 — V5 FINAL INFERENCE
# High-recall candidate generation + V5 CatBoost
# ============================================================

import os
import time
import gc
import ast
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import ratio
from catboost import CatBoostClassifier

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

ROOT = "/content/amazon_ml_challenge/student_resource"
TEST_DIR = f"{ROOT}/dataset/test"
OUTPUT_DIR = f"{ROOT}/output"

os.makedirs(OUTPUT_DIR, exist_ok=True)

S1_PATH = f"{TEST_DIR}/test_source1.tsv"
S2_PATH = f"{TEST_DIR}/test_source2.tsv"
S3_PATH = f"{TEST_DIR}/test_source3.tsv"

MODEL_PATH = (
    "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_model.cbm"
)

INDEX_DIR = (
    "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/"
    "V5_full_indexes"
)

MATCH_OUT = f"{OUTPUT_DIR}/matching_results_v5.tsv"
CAND_OUT = f"{OUTPUT_DIR}/candidate_pairs_v5.tsv"

THRESHOLD = 0.60
CHUNK_SIZE = 5000

# ------------------------------------------------------------
# CHECK REQUIRED OBJECTS
# ------------------------------------------------------------

required = [
    "s2_names_a",
    "s2_addrs_a",
    "s2_countries_a",
    "s2_ids",
    "s3_names_a",
    "s3_addrs_a",
    "s3_countries_a",
    "s3_ids",
    "v5_model",
]

missing = [x for x in required if x not in globals()]

if missing:
    raise RuntimeError(
        "Missing required objects: " + ", ".join(missing)
    )

print("All required objects are available.")
print("V5 model:", MODEL_PATH)
print("Threshold:", THRESHOLD)
print("Chunk size:", CHUNK_SIZE)

# ------------------------------------------------------------
# VERIFY MODEL
# ------------------------------------------------------------

if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(MODEL_PATH)

v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

print("V5 model loaded successfully.")

# ------------------------------------------------------------
# LOAD TEST SOURCE 1
# ------------------------------------------------------------

test_s1 = pd.read_csv(S1_PATH, sep="\t")

print("\nTest S1:", test_s1.shape)

# ------------------------------------------------------------
# FAST NORMALIZATION
# ------------------------------------------------------------

def normalize_advanced_local(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    import re
    import unicodedata

    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def tokens_fast(text):
    if not text:
        return set()
    return set(text.split())


# ------------------------------------------------------------
# LOAD SAVED INDEXES
# ------------------------------------------------------------

import pickle

def load_pickle(name):
    path = os.path.join(INDEX_DIR, name)
    print("Loading:", name)
    with open(path, "rb") as f:
        return pickle.load(f)


s2_name_index = load_pickle("s2_name_index.pkl")
s2_addr_index = load_pickle("s2_addr_index.pkl")
s2_name_freq = load_pickle("s2_name_freq.pkl")
s2_addr_freq = load_pickle("s2_addr_freq.pkl")

s3_name_index = load_pickle("s3_name_index.pkl")
s3_addr_index = load_pickle("s3_addr_index.pkl")
s3_name_freq = load_pickle("s3_name_freq.pkl")
s3_addr_freq = load_pickle("s3_addr_freq.pkl")

print("All indexes loaded.")

# ------------------------------------------------------------
# V5 FEATURES
# ------------------------------------------------------------

V5_FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]


def extract_numbers_fast(text):
    import re
    return set(re.findall(r"\d+", text))


def build_fast_features(s1_name, s1_addr, s1_country,
                        names, addrs, countries):

    n1 = s1_name
    a1 = s1_addr
    c1 = s1_country

    t1n = tokens_fast(n1)
    t1a = tokens_fast(a1)

    nums1 = extract_numbers_fast(a1)

    rows = []

    for n2, a2, c2 in zip(names, addrs, countries):

        t2n = tokens_fast(n2)
        t2a = tokens_fast(a2)

        shared_n = t1n & t2n
        shared_a = t1a & t2a

        union_n = t1n | t2n
        union_a = t1a | t2a

        ns = ratio(n1, n2) / 100 if n1 and n2 else 0.0
        ass = ratio(a1, a2) / 100 if a1 and a2 else 0.0

        nt = (
            len(shared_n) / max(1, min(len(t1n), len(t2n)))
        )

        at = (
            len(shared_a) / max(1, min(len(t1a), len(t2a)))
        )

        nj = (
            len(shared_n) / len(union_n)
            if union_n else 0.0
        )

        aj = (
            len(shared_a) / len(union_a)
            if union_a else 0.0
        )

        nums2 = extract_numbers_fast(a2)

        rows.append({
            "name_exact": int(bool(n1) and n1 == n2),
            "address_exact": int(bool(a1) and a1 == a2),
            "country_exact": int(c1 == c2),

            "name_similarity": ns,
            "address_similarity": ass,

            "name_token_overlap": nt,
            "address_token_overlap": at,

            "name_jaccard": nj,
            "address_jaccard": aj,

            "shared_name_token_count": len(shared_n),
            "shared_address_token_count": len(shared_a),
            "shared_address_number_count": len(nums1 & nums2),

            "name_length_diff": abs(len(n1) - len(n2)),
            "address_length_diff": abs(len(a1) - len(a2)),

            "name_length_ratio":
                min(len(n1), len(n2)) /
                max(1, max(len(n1), len(n2))),

            "address_length_ratio":
                min(len(a1), len(a2)) /
                max(1, max(len(a1), len(a2))),

            "similarity_gap": abs(ns - ass),
            "max_similarity": max(ns, ass),
            "similarity_product": ns * ass,
            "token_overlap_gap": abs(nt - at)
        })

    return pd.DataFrame(rows, columns=V5_FEATURES)


# ------------------------------------------------------------
# HIGH-RECALL CANDIDATE GENERATOR
# ------------------------------------------------------------

def high_recall_candidates(
    s1_name,
    s1_addr,
    s1_country,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    ids
):

    t_name = tokens_fast(s1_name)
    t_addr = tokens_fast(s1_addr)

    candidate_ids = set()

    # Exact name
    if s1_name:
        candidate_ids.update(
            name_index.get(s1_name, [])
        )

    # Exact address
    if s1_addr:
        candidate_ids.update(
            addr_index.get(s1_addr, [])
        )

    # Name token candidates
    name_token_hits = {}

    for tok in t_name:

        # Keep the benchmark's <=500 frequency rule
        if name_freq.get(tok, 10**9) <= 500:

            for idx in name_index.get(tok, []):
                name_token_hits[idx] = (
                    name_token_hits.get(idx, 0) + 1
                )

    for idx, count in name_token_hits.items():

        if count >= 2:
            candidate_ids.add(idx)

    # Address token candidates
    addr_token_hits = {}

    for tok in t_addr:

        if addr_freq.get(tok, 10**9) <= 500:

            for idx in addr_index.get(tok, []):

                addr_token_hits[idx] = (
                    addr_token_hits.get(idx, 0) + 1
                )

    for idx, count in addr_token_hits.items():

        if count >= 2:
            candidate_ids.add(idx)

    # --------------------------------------------------------
    # Similarity filtering
    # --------------------------------------------------------

    selected = []

    for idx in candidate_ids:

        n2 = names_global[idx]
        a2 = addrs_global[idx]

        name_shared = len(
            t_name & tokens_fast(n2)
        )

        addr_shared = len(
            t_addr & tokens_fast(a2)
        )

        name_sim = (
            ratio(s1_name, n2) / 100
            if s1_name and n2 else 0
        )

        addr_sim = (
            ratio(s1_addr, a2) / 100
            if s1_addr and a2 else 0
        )

        keep = (
            n2 == s1_name
            or a2 == s1_addr
            or (
                name_shared >= 2
                and name_sim >= 0.60
            )
            or (
                addr_shared >= 3
            )
            or (
                addr_shared >= 2
                and addr_sim >= 0.30
            )
        )

        if keep:
            selected.append(idx)

    return selected


# ------------------------------------------------------------
# PREPARE GLOBAL SOURCE ARRAYS
# ------------------------------------------------------------

# S2 globals
names_global = s2_names_a
addrs_global = s2_addrs_a
countries_global = s2_countries_a
ids_global = s2_ids

# ------------------------------------------------------------
# IMPORTANT:
# Candidate indexes contain integer row positions.
# We run S2 and S3 separately.
# ------------------------------------------------------------

def run_source(
    s1_rows,
    names,
    addrs,
    countries,
    ids,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    source_name
):

    all_match_rows = []
    all_candidate_rows = []

    total_selected = 0
    total_predictions = 0

    start = time.time()

    for local_i, (_, row) in enumerate(s1_rows.iterrows()):

        s1_id = row["source1_entity_id"]

        s1_name = normalize_advanced_local(
            row["business_name"]
        )

        s1_addr = normalize_advanced_local(
            row["business_address"]
        )

        s1_country = normalize_advanced_local(
            row["country"]
        )

        # -----------------------------------------------
        # Candidate generation
        # -----------------------------------------------

        candidate_idx = high_recall_candidates(
            s1_name,
            s1_addr,
            s1_country,
            name_index,
            addr_index,
            name_freq,
            addr_freq,
            ids
        )

        total_selected += len(candidate_idx)

        if not candidate_idx:
            all_match_rows.append({
                "source1_entity_id": s1_id,
                "matched_entity_ids": ""
            })

            all_candidate_rows.append({
                "source1_entity_id": s1_id,
                "candidate_entity_ids": ""
            })

            continue

        # -----------------------------------------------
        # Candidate IDs
        # -----------------------------------------------

        candidate_ids = [
            ids[i] for i in candidate_idx
        ]

        # -----------------------------------------------
        # Feature matrix
        # -----------------------------------------------

        cand_names = [
            names[i] for i in candidate_idx
        ]

        cand_addrs = [
            addrs[i] for i in candidate_idx
        ]

        cand_countries = [
            countries[i] for i in candidate_idx
        ]

        X = build_fast_features(
            s1_name,
            s1_addr,
            s1_country,
            cand_names,
            cand_addrs,
            cand_countries
        )

        # -----------------------------------------------
        # V5 prediction
        # -----------------------------------------------

        probs = v5_model.predict_proba(
            X[V5_FEATURES]
        )[:, 1]

        matched = [
            str(candidate_ids[j])
            for j, p in enumerate(probs)
            if p >= THRESHOLD
        ]

        total_predictions += len(matched)

        all_match_rows.append({
            "source1_entity_id": s1_id,
            "matched_entity_ids": ",".join(matched)
        })

        all_candidate_rows.append({
            "source1_entity_id": s1_id,
            "candidate_entity_ids": ",".join(
                map(str, candidate_ids)
            )
        })

        # -----------------------------------------------
        # Progress
        # -----------------------------------------------

        if (local_i + 1) % 500 == 0:

            elapsed = time.time() - start

            print(
                f"{source_name}: "
                f"{local_i + 1:,}/{len(s1_rows):,} | "
                f"elapsed {elapsed/60:.1f} min | "
                f"candidates {total_selected:,} | "
                f"matches {total_predictions:,}"
            )

    return (
        all_match_rows,
        all_candidate_rows,
        total_selected,
        total_predictions
    )


# ------------------------------------------------------------
# NOTE:
# The indexes are built separately for S2 and S3.
# Therefore we need a generic source runner.
# ------------------------------------------------------------

def process_s1_chunk(chunk):

    match_rows = []
    candidate_rows = []

    selected_total = 0
    prediction_total = 0

    # --------------------------------------------
    # S2
    # --------------------------------------------

    global names_global, addrs_global, countries_global

    names_global = s2_names_a
    addrs_global = s2_addrs_a
    countries_global = s2_countries_a

    s2_matches, s2_candidates, s2_sel, s2_pred = run_source(
        chunk,
        s2_names_a,
        s2_addrs_a,
        s2_countries_a,
        s2_ids,
        s2_name_index,
        s2_addr_index,
        s2_name_freq,
        s2_addr_freq,
        "S2"
    )

    # --------------------------------------------
    # S3
    # --------------------------------------------

    names_global = s3_names_a
    addrs_global = s3_addrs_a
    countries_global = s3_countries_a

    s3_matches, s3_candidates, s3_sel, s3_pred = run_source(
        chunk,
        s3_names_a,
        s3_addrs_a,
        s3_countries_a,
        s3_ids,
        s3_name_index,
        s3_addr_index,
        s3_name_freq,
        s3_addr_freq,
        "S3"
    )

    # --------------------------------------------
    # Merge S2 + S3 results by S1
    # --------------------------------------------

    s2_match_dict = {
        str(x["source1_entity_id"]): x["matched_entity_ids"]
        for x in s2_matches
    }

    s3_match_dict = {
        str(x["source1_entity_id"]): x["matched_entity_ids"]
        for x in s3_matches
    }

    s2_cand_dict = {
        str(x["source1_entity_id"]): x["candidate_entity_ids"]
        for x in s2_candidates
    }

    s3_cand_dict = {
        str(x["source1_entity_id"]): x["candidate_entity_ids"]
        for x in s3_candidates
    }

    for _, row in chunk.iterrows():

        sid = str(row["source1_entity_id"])

        m2 = s2_match_dict.get(sid, "")
        m3 = s3_match_dict.get(sid, "")

        c2 = s2_cand_dict.get(sid, "")
        c3 = s3_cand_dict.get(sid, "")

        matches = []

        if m2:
            matches.extend(m2.split(","))

        if m3:
            matches.extend(m3.split(","))

        candidates = []

        if c2:
            candidates.extend(c2.split(","))

        if c3:
            candidates.extend(c3.split(","))

        match_rows.append({
            "source1_entity_id": row["source1_entity_id"],
            "matched_entity_ids": ",".join(matches)
        })

        candidate_rows.append({
            "source1_entity_id": row["source1_entity_id"],
            "candidate_entity_ids": ",".join(candidates)
        })

    return (
        match_rows,
        candidate_rows,
        s2_sel + s3_sel,
        s2_pred + s3_pred
    )


# ============================================================
# FULL INFERENCE
# ============================================================

print("\n" + "=" * 70)
print("STARTING FULL V5 INFERENCE")
print("=" * 70)

# Remove old files if they exist
for path in [MATCH_OUT, CAND_OUT]:
    if os.path.exists(path):
        os.remove(path)

total_start = time.time()

all_matches = []
all_candidates = []

total_selected = 0
total_predictions = 0

n = len(test_s1)

for start_idx in range(0, n, CHUNK_SIZE):

    end_idx = min(start_idx + CHUNK_SIZE, n)

    chunk = test_s1.iloc[start_idx:end_idx].copy()

    chunk_start = time.time()

    matches, candidates, selected, predictions = process_s1_chunk(
        chunk
    )

    all_matches.extend(matches)
    all_candidates.extend(candidates)

    total_selected += selected
    total_predictions += predictions

    elapsed = time.time() - total_start
    rate = (end_idx / elapsed) if elapsed > 0 else 0

    remaining = (
        (n - end_idx) / rate
        if rate > 0 else 0
    )

    print(
        f"\n>>> GLOBAL: "
        f"{end_idx:,}/{n:,} "
        f"({100*end_idx/n:.2f}%) | "
        f"elapsed {elapsed/60:.1f} min | "
        f"ETA {remaining/60:.1f} min | "
        f"selected {total_selected:,} | "
        f"matches {total_predictions:,}"
    )

    # Save checkpoint every chunk
    pd.DataFrame(
        all_matches,
        columns=[
            "source1_entity_id",
            "matched_entity_ids"
        ]
    ).to_csv(
        MATCH_OUT,
        sep="\t",
        index=False
    )

    pd.DataFrame(
        all_candidates,
        columns=[
            "source1_entity_id",
            "candidate_entity_ids"
        ]
    ).to_csv(
        CAND_OUT,
        sep="\t",
        index=False
    )

    del chunk, matches, candidates
    gc.collect()


# ============================================================
# FINAL WRITE
# ============================================================

match_df = pd.DataFrame(
    all_matches,
    columns=[
        "source1_entity_id",
        "matched_entity_ids"
    ]
)

candidate_df = pd.DataFrame(
    all_candidates,
    columns=[
        "source1_entity_id",
        "candidate_entity_ids"
    ]
)

match_df.to_csv(
    MATCH_OUT,
    sep="\t",
    index=False
)

candidate_df.to_csv(
    CAND_OUT,
    sep="\t",
    index=False
)

total_time = time.time() - total_start

print("\n" + "=" * 70)
print("V5 FULL INFERENCE COMPLETE")
print("=" * 70)

print(f"S1 rows:              {len(match_df):,}")
print(f"Unique S1 IDs:        {match_df['source1_entity_id'].nunique():,}")
print(f"Selected candidates:  {total_selected:,}")
print(f"Predicted matches:    {total_predictions:,}")
print(f"Average candidates:   {total_selected/n:.2f}")
print(f"Average matches:      {total_predictions/n:.4f}")
print(f"Runtime:              {total_time/60:.2f} minutes")

print("\nOutput files:")
print(MATCH_OUT)
print(CAND_OUT)

print("\nFile sizes:")
print(
    f"matching_results_v5.tsv: "
    f"{os.path.getsize(MATCH_OUT)/1024/1024:.2f} MB"
)

print(
    f"candidate_pairs_v5.tsv: "
    f"{os.path.getsize(CAND_OUT)/1024/1024:.2f} MB"
)

All required objects are available.
V5 model: /content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm
Threshold: 0.6
Chunk size: 5000
V5 model loaded successfully.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

MODEL_PATH = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm"
INDEX_DIR = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

print("Model exists:", os.path.exists(MODEL_PATH))
print("Index folder exists:", os.path.exists(INDEX_DIR))

print("\nIndex files:")
for f in sorted(os.listdir(INDEX_DIR)):
    print(" ", f)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Model exists: True
Index folder exists: True

Index files:
  s2_addr_freq.pkl
  s2_addr_index.pkl
  s2_name_freq.pkl
  s2_name_index.pkl
  s3_addr_freq.pkl
  s3_addr_index.pkl
  s3_name_freq.pkl
  s3_name_index.pkl

In [ ]:
import os
import pickle
import gc
from catboost import CatBoostClassifier

MODEL_PATH = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm"
INDEX_DIR = "/content/drive/My Drive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

def load_pickle(name):
    path = os.path.join(INDEX_DIR, name)
    print("Loading:", name)
    with open(path, "rb") as f:
        return pickle.load(f)

# Load S2 indexes
s2_name_index = load_pickle("s2_name_index.pkl")
s2_addr_index = load_pickle("s2_addr_index.pkl")
s2_name_freq = load_pickle("s2_name_freq.pkl")
s2_addr_freq = load_pickle("s2_addr_freq.pkl")

print("S2 indexes loaded.")

# Load S3 indexes
s3_name_index = load_pickle("s3_name_index.pkl")
s3_addr_index = load_pickle("s3_addr_index.pkl")
s3_name_freq = load_pickle("s3_name_freq.pkl")
s3_addr_freq = load_pickle("s3_addr_freq.pkl")

print("S3 indexes loaded.")

# Load V5 model
v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

print("\nV5 model loaded.")
print("Model fitted:", v5_model.is_fitted())

gc.collect()

Loading: s2_name_index.pkl
Loading: s2_addr_index.pkl
Loading: s2_name_freq.pkl
Loading: s2_addr_freq.pkl
S2 indexes loaded.
Loading: s3_name_index.pkl
Loading: s3_addr_index.pkl
Loading: s3_name_freq.pkl
Loading: s3_addr_freq.pkl
S3 indexes loaded.

V5 model loaded.
Model fitted: True

0

In [ ]:
import pandas as pd
import numpy as np
import gc
import os

ROOT = "/content/amazon_ml_challenge/student_resource"
TEST_DIR = f"{ROOT}/dataset/test"

S2_PATH = f"{TEST_DIR}/test_source2.tsv"
S3_PATH = f"{TEST_DIR}/test_source3.tsv"

print("Loading S2...")
s2 = pd.read_csv(S2_PATH, sep="\t")

print("S2 shape:", s2.shape)

print("Loading S3...")
s3 = pd.read_csv(S3_PATH, sep="\t")

print("S3 shape:", s3.shape)

Loading S2...
S2 shape: (4887273, 4)
Loading S3...
S3 shape: (5082316, 4)

In [ ]:
import re
import unicodedata
import numpy as np
import gc

def normalize_advanced_local(text):
    if text is None:
        return ""

    text = str(text).lower().strip()

    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

print("Normalization function restored.")

Normalization function restored.

In [ ]:
# ============================================================
# STEP 4 — COMPACT S2/S3 ARRAYS
# ============================================================

import numpy as np
import gc

print("Converting S2...")

s2_names_a = (
    s2["business_name"]
    .fillna("")
    .astype(str)
    .map(normalize_advanced_local)
    .to_numpy(dtype=object)
)

s2_addrs_a = (
    s2["business_address"]
    .fillna("")
    .astype(str)
    .map(normalize_advanced_local)
    .to_numpy(dtype=object)
)

s2_countries_a = (
    s2["country"]
    .fillna("")
    .astype(str)
    .map(normalize_advanced_local)
    .to_numpy(dtype=object)
)

# TEST Source 2 uses "entity_id"
s2_ids = s2["entity_id"].to_numpy()

print("S2 arrays ready:", len(s2_ids))


print("\nConverting S3...")

s3_names_a = (
    s3["business_name"]
    .fillna("")
    .astype(str)
    .map(normalize_advanced_local)
    .to_numpy(dtype=object)
)

s3_addrs_a = (
    s3["business_address"]
    .fillna("")
    .astype(str)
    .map(normalize_advanced_local)
    .to_numpy(dtype=object)
)

s3_countries_a = (
    s3["country"]
    .fillna("")
    .astype(str)
    .map(normalize_advanced_local)
    .to_numpy(dtype=object)
)

# TEST Source 3 uses "entity_id"
s3_ids = s3["entity_id"].to_numpy()

print("S3 arrays ready:", len(s3_ids))


# Release large pandas DataFrames
del s2
del s3
gc.collect()

print("\nS2/S3 pandas DataFrames released.")
print("S2:", len(s2_ids))
print("S3:", len(s3_ids))

Converting S2...
S2 arrays ready: 4887273

Converting S3...
S3 arrays ready: 5082316

S2/S3 pandas DataFrames released.
S2: 4887273
S3: 5082316

In [ ]:
print("S2 columns:")
print(s2.columns.tolist())

print("\nS3 columns:")
print(s3.columns.tolist())

S2 columns:
['entity_id', 'business_name', 'business_address', 'country']

S3 columns:
['entity_id', 'business_name', 'business_address', 'country']

In [ ]:
import pandas as pd

S1_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"

s1_check = pd.read_csv(S1_PATH, sep="\t", nrows=3)

print(s1_check.columns.tolist())
print(s1_check)

['entity_id', 'business_name', 'business_address', 'country']
      entity_id         business_name  \
0  S1-714132312       Zephay Labs Inc
1  S1-106407869  Vision Partners Corp
2  S1-156285671         << Team Ecole

                                    business_address country
0                        2621 Cotten Road, Tyler, TX      US
1             IA, Iowa City, 1064 Newton Rd, Unit 11      US
2  175 Boulevard du Président Franklin Roosevelt,...  France

In [ ]:
# ============================================================
# V5 FINAL — CHECKPOINTED, RAM-SAFE INFERENCE
# ============================================================
import unicodedata
import os
import gc
import re
import time
import pickle
import numpy as np
import pandas as pd

from rapidfuzz.fuzz import ratio

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

ROOT = "/content/amazon_ml_challenge/student_resource"
TEST_DIR = f"{ROOT}/dataset/test"

S1_PATH = f"{TEST_DIR}/test_source1.tsv"

DRIVE_OUT = (
    "/content/drive/My Drive/"
    "Amazon-ML-Challenge-2026/ml/V5_Final_Inference"
)

os.makedirs(DRIVE_OUT, exist_ok=True)

MATCH_OUT = f"{DRIVE_OUT}/matching_results_v5.tsv"
CAND_OUT = f"{DRIVE_OUT}/candidate_pairs_v5.tsv"
CHECKPOINT = f"{DRIVE_OUT}/checkpoint.txt"

THRESHOLD = 0.60
CHUNK_SIZE = 2000

# ------------------------------------------------------------
# REQUIRED OBJECT CHECK
# ------------------------------------------------------------

required = [
    "s2_names_a",
    "s2_addrs_a",
    "s2_countries_a",
    "s2_ids",
    "s3_names_a",
    "s3_addrs_a",
    "s3_countries_a",
    "s3_ids",
    "s2_name_index",
    "s2_addr_index",
    "s2_name_freq",
    "s2_addr_freq",
    "s3_name_index",
    "s3_addr_index",
    "s3_name_freq",
    "s3_addr_freq",
    "v5_model",
]

missing = [x for x in required if x not in globals()]

if missing:
    raise RuntimeError(
        "Missing objects: " + ", ".join(missing)
    )

print("All required objects available.")


# ------------------------------------------------------------
# NORMALIZATION
# ------------------------------------------------------------

def normalize_advanced_local(text):

    if text is None:
        return ""

    text = str(text).lower().strip()

    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def tokens_fast(text):

    if not text:
        return set()

    return set(text.split())


def extract_numbers_fast(text):

    return set(re.findall(r"\d+", text))


# ------------------------------------------------------------
# V5 FEATURE LIST
# ------------------------------------------------------------

V5_FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]


# ------------------------------------------------------------
# BUILD FEATURES
# ------------------------------------------------------------

def build_features(
    s1_name,
    s1_addr,
    s1_country,
    names,
    addrs,
    countries
):

    t1n = tokens_fast(s1_name)
    t1a = tokens_fast(s1_addr)
    nums1 = extract_numbers_fast(s1_addr)

    rows = []

    for n2, a2, c2 in zip(
        names,
        addrs,
        countries
    ):

        t2n = tokens_fast(n2)
        t2a = tokens_fast(a2)

        shared_n = t1n & t2n
        shared_a = t1a & t2a

        union_n = t1n | t2n
        union_a = t1a | t2a

        ns = (
            ratio(s1_name, n2) / 100
            if s1_name and n2 else 0.0
        )

        ass = (
            ratio(s1_addr, a2) / 100
            if s1_addr and a2 else 0.0
        )

        nt = (
            len(shared_n) /
            max(1, min(len(t1n), len(t2n)))
        )

        at = (
            len(shared_a) /
            max(1, min(len(t1a), len(t2a)))
        )

        nj = (
            len(shared_n) / len(union_n)
            if union_n else 0.0
        )

        aj = (
            len(shared_a) / len(union_a)
            if union_a else 0.0
        )

        nums2 = extract_numbers_fast(a2)

        rows.append([
            int(bool(s1_name) and s1_name == n2),
            int(bool(s1_addr) and s1_addr == a2),
            int(s1_country == c2),

            ns,
            ass,

            nt,
            at,

            nj,
            aj,

            len(shared_n),
            len(shared_a),
            len(nums1 & nums2),

            abs(len(s1_name) - len(n2)),
            abs(len(s1_addr) - len(a2)),

            min(len(s1_name), len(n2)) /
            max(1, max(len(s1_name), len(n2))),

            min(len(s1_addr), len(a2)) /
            max(1, max(len(s1_addr), len(a2))),

            abs(ns - ass),
            max(ns, ass),
            ns * ass,
            abs(nt - at)
        ])

    return np.asarray(rows, dtype=np.float32)


# ------------------------------------------------------------
# CANDIDATE GENERATION
# ------------------------------------------------------------

def generate_candidates(
    s1_name,
    s1_addr,
    name_index,
    addr_index,
    name_freq,
    addr_freq,
    names,
    addrs
):

    t_name = tokens_fast(s1_name)
    t_addr = tokens_fast(s1_addr)

    candidate_ids = set()

    # Exact name
    if s1_name:
        candidate_ids.update(
            name_index.get(s1_name, [])
        )

    # Exact address
    if s1_addr:
        candidate_ids.update(
            addr_index.get(s1_addr, [])
        )

    # Name tokens
    name_hits = {}

    for tok in t_name:

        if name_freq.get(tok, 10**9) <= 500:

            for idx in name_index.get(tok, []):

                name_hits[idx] = (
                    name_hits.get(idx, 0) + 1
                )

    for idx, count in name_hits.items():

        if count >= 2:
            candidate_ids.add(idx)

    # Address tokens
    addr_hits = {}

    for tok in t_addr:

        if addr_freq.get(tok, 10**9) <= 500:

            for idx in addr_index.get(tok, []):

                addr_hits[idx] = (
                    addr_hits.get(idx, 0) + 1
                )

    for idx, count in addr_hits.items():

        if count >= 2:
            candidate_ids.add(idx)

    # Similarity selection
    selected = []

    for idx in candidate_ids:

        n2 = names[idx]
        a2 = addrs[idx]

        shared_name = len(
            t_name & tokens_fast(n2)
        )

        shared_addr = len(
            t_addr & tokens_fast(a2)
        )

        name_sim = (
            ratio(s1_name, n2) / 100
            if s1_name and n2 else 0.0
        )

        addr_sim = (
            ratio(s1_addr, a2) / 100
            if s1_addr and a2 else 0.0
        )

        keep = (
            n2 == s1_name
            or
            a2 == s1_addr
            or
            (
                shared_name >= 2
                and name_sim >= 0.60
            )
            or
            (
                shared_addr >= 3
            )
            or
            (
                shared_addr >= 2
                and addr_sim >= 0.30
            )
        )

        if keep:
            selected.append(idx)

    return selected


# ------------------------------------------------------------
# SOURCE PROCESSOR
# ------------------------------------------------------------

def process_source1_row(
    row,
    names,
    addrs,
    countries,
    ids,
    name_index,
    addr_index,
    name_freq,
    addr_freq
):

    s1_name = normalize_advanced_local(
        row["business_name"]
    )

    s1_addr = normalize_advanced_local(
        row["business_address"]
    )

    s1_country = normalize_advanced_local(
        row["country"]
    )

    candidate_idx = generate_candidates(
        s1_name,
        s1_addr,
        name_index,
        addr_index,
        name_freq,
        addr_freq,
        names,
        addrs
    )

    if not candidate_idx:

        return [], []

    candidate_ids = [
        ids[i] for i in candidate_idx
    ]

    candidate_names = [
        names[i] for i in candidate_idx
    ]

    candidate_addrs = [
        addrs[i] for i in candidate_idx
    ]

    candidate_countries = [
        countries[i] for i in candidate_idx
    ]

    X = build_features(
        s1_name,
        s1_addr,
        s1_country,
        candidate_names,
        candidate_addrs,
        candidate_countries
    )

    probs = v5_model.predict_proba(X)[:, 1]

    matches = [
        str(candidate_ids[i])
        for i, p in enumerate(probs)
        if p >= THRESHOLD
    ]

    return matches, [
        str(x) for x in candidate_ids
    ]


# ------------------------------------------------------------
# CHECKPOINT HANDLING
# ------------------------------------------------------------

start_row = 0

if os.path.exists(CHECKPOINT):

    with open(CHECKPOINT, "r") as f:
        saved = f.read().strip()

    if saved:
        start_row = int(saved)

print("\nResume row:", start_row)


# ------------------------------------------------------------
# OUTPUT FILE INITIALIZATION
# ------------------------------------------------------------

if start_row == 0:

    for path in [MATCH_OUT, CAND_OUT]:

        if os.path.exists(path):
            os.remove(path)

    with open(MATCH_OUT, "w") as f:
        f.write(
            "source1_entity_id\tmatched_entity_ids\n"
        )

    with open(CAND_OUT, "w") as f:
        f.write(
            "source1_entity_id\tcandidate_entity_ids\n"
        )


# ------------------------------------------------------------
# TOTAL ROW COUNT
# ------------------------------------------------------------

total_rows = sum(
    1 for _ in open(S1_PATH, encoding="utf-8")
) - 1

print("Total S1 rows:", total_rows)
print("Starting from:", start_row)

# ------------------------------------------------------------
# FULL CHECKPOINTED RUN
# ------------------------------------------------------------

run_start = time.time()

total_candidates = 0
total_matches = 0

for chunk_start in range(
    start_row,
    total_rows,
    CHUNK_SIZE
):

    chunk_end = min(
        chunk_start + CHUNK_SIZE,
        total_rows
    )

    # Read ONLY this chunk
    s1_chunk = pd.read_csv(
        S1_PATH,
        sep="\t",
        skiprows=range(
            1,
            chunk_start + 1
        ),
        nrows=CHUNK_SIZE
    )

    match_lines = []
    candidate_lines = []

    chunk_candidates = 0
    chunk_matches = 0

    for _, row in s1_chunk.iterrows():

        sid = str(row["entity_id"])

        # -------------------------
        # S2
        # -------------------------

        m2, c2 = process_source1_row(
            row,
            s2_names_a,
            s2_addrs_a,
            s2_countries_a,
            s2_ids,
            s2_name_index,
            s2_addr_index,
            s2_name_freq,
            s2_addr_freq
        )

        # -------------------------
        # S3
        # -------------------------

        m3, c3 = process_source1_row(
            row,
            s3_names_a,
            s3_addrs_a,
            s3_countries_a,
            s3_ids,
            s3_name_index,
            s3_addr_index,
            s3_name_freq,
            s3_addr_freq
        )

        matches = m2 + m3
        candidates = c2 + c3

        chunk_candidates += len(candidates)
        chunk_matches += len(matches)

        match_lines.append(
            sid + "\t" + ",".join(matches) + "\n"
        )

        candidate_lines.append(
            sid + "\t" + ",".join(candidates) + "\n"
        )

    # --------------------------------------------
    # WRITE CHUNK DIRECTLY TO DRIVE
    # --------------------------------------------

    with open(MATCH_OUT, "a", encoding="utf-8") as f:
        f.writelines(match_lines)

    with open(CAND_OUT, "a", encoding="utf-8") as f:
        f.writelines(candidate_lines)

    total_candidates += chunk_candidates
    total_matches += chunk_matches

    # --------------------------------------------
    # CHECKPOINT
    # --------------------------------------------

    with open(CHECKPOINT, "w") as f:
        f.write(str(chunk_end))

    elapsed = time.time() - run_start
    completed = chunk_end
    rate = completed / elapsed if elapsed else 0

    remaining = (
        (total_rows - completed) / rate
        if rate else 0
    )

    print(
        f"{completed:,}/{total_rows:,} "
        f"({100*completed/total_rows:.2f}%) | "
        f"candidates {total_candidates:,} | "
        f"matches {total_matches:,} | "
        f"elapsed {elapsed/60:.1f} min | "
        f"ETA {remaining/60:.1f} min"
    )

    del s1_chunk
    del match_lines
    del candidate_lines
    gc.collect()


print("\n" + "=" * 70)
print("FULL V5 INFERENCE FINISHED")
print("=" * 70)

print("Matching file:")
print(MATCH_OUT)

print("\nCandidate file:")
print(CAND_OUT)

print("\nTotal candidates:", total_candidates)
print("Total predicted matches:", total_matches)

print(
    "Runtime:",
    round((time.time() - run_start) / 60, 2),
    "minutes"
)

All required objects available.

Resume row: 14000
Total S1 rows: 1732544
Starting from: 14000
16,000/1,732,544 (0.92%) | candidates 11,896 | matches 2,728 | elapsed 0.1 min | ETA 13.9 min
18,000/1,732,544 (1.04%) | candidates 23,439 | matches 5,555 | elapsed 0.2 min | ETA 23.4 min
20,000/1,732,544 (1.15%) | candidates 34,274 | matches 8,267 | elapsed 0.4 min | ETA 34.1 min
22,000/1,732,544 (1.27%) | candidates 46,748 | matches 11,128 | elapsed 0.5 min | ETA 39.9 min
24,000/1,732,544 (1.39%) | candidates 59,725 | matches 13,887 | elapsed 0.6 min | ETA 44.2 min
26,000/1,732,544 (1.50%) | candidates 71,051 | matches 16,761 | elapsed 0.7 min | ETA 46.2 min
28,000/1,732,544 (1.62%) | candidates 81,445 | matches 19,444 | elapsed 0.8 min | ETA 47.7 min
30,000/1,732,544 (1.73%) | candidates 92,407 | matches 22,128 | elapsed 0.9 min | ETA 50.1 min
32,000/1,732,544 (1.85%) | candidates 104,957 | matches 24,994 | elapsed 1.0 min | ETA 51.5 min
34,000/1,732,544 (1.96%) | candidates 115,893 | matches 27,832 | elapsed 1.0 min | ETA 52.4 min
36,000/1,732,544 (2.08%) | candidates 127,658 | matches 30,472 | elapsed 1.1 min | ETA 54.0 min
38,000/1,732,544 (2.19%) | candidates 139,510 | matches 33,155 | elapsed 1.2 min | ETA 54.6 min
40,000/1,732,544 (2.31%) | candidates 151,395 | matches 35,827 | elapsed 1.3 min | ETA 55.1 min
42,000/1,732,544 (2.42%) | candidates 163,547 | matches 38,682 | elapsed 1.4 min | ETA 56.2 min
44,000/1,732,544 (2.54%) | candidates 175,726 | matches 41,356 | elapsed 1.5 min | ETA 56.6 min
46,000/1,732,544 (2.66%) | candidates 187,330 | matches 44,146 | elapsed 1.6 min | ETA 57.0 min
48,000/1,732,544 (2.77%) | candidates 199,471 | matches 46,854 | elapsed 1.6 min | ETA 57.9 min
50,000/1,732,544 (2.89%) | candidates 211,348 | matches 49,680 | elapsed 1.7 min | ETA 58.2 min
52,000/1,732,544 (3.00%) | candidates 223,211 | matches 52,435 | elapsed 1.8 min | ETA 58.6 min
54,000/1,732,544 (3.12%) | candidates 235,766 | matches 55,273 | elapsed 1.9 min | ETA 59.4 min
56,000/1,732,544 (3.23%) | candidates 247,554 | matches 57,837 | elapsed 2.0 min | ETA 59.5 min
58,000/1,732,544 (3.35%) | candidates 258,445 | matches 60,492 | elapsed 2.1 min | ETA 59.8 min
60,000/1,732,544 (3.46%) | candidates 270,113 | matches 63,348 | elapsed 2.2 min | ETA 60.4 min
62,000/1,732,544 (3.58%) | candidates 284,254 | matches 66,009 | elapsed 2.3 min | ETA 60.9 min
64,000/1,732,544 (3.69%) | candidates 296,771 | matches 68,704 | elapsed 2.3 min | ETA 61.2 min
66,000/1,732,544 (3.81%) | candidates 310,380 | matches 71,624 | elapsed 2.4 min | ETA 61.6 min
68,000/1,732,544 (3.92%) | candidates 323,805 | matches 74,543 | elapsed 2.5 min | ETA 61.9 min
70,000/1,732,544 (4.04%) | candidates 335,483 | matches 77,235 | elapsed 2.6 min | ETA 62.2 min
72,000/1,732,544 (4.16%) | candidates 347,249 | matches 79,959 | elapsed 2.7 min | ETA 62.3 min
74,000/1,732,544 (4.27%) | candidates 359,081 | matches 82,747 | elapsed 2.8 min | ETA 62.3 min
76,000/1,732,544 (4.39%) | candidates 370,928 | matches 85,518 | elapsed 2.9 min | ETA 62.5 min
78,000/1,732,544 (4.50%) | candidates 383,837 | matches 88,391 | elapsed 3.0 min | ETA 62.6 min
80,000/1,732,544 (4.62%) | candidates 394,369 | matches 91,110 | elapsed 3.0 min | ETA 62.6 min
82,000/1,732,544 (4.73%) | candidates 406,406 | matches 93,796 | elapsed 3.1 min | ETA 62.8 min
84,000/1,732,544 (4.85%) | candidates 418,389 | matches 96,563 | elapsed 3.2 min | ETA 62.9 min
86,000/1,732,544 (4.96%) | candidates 431,327 | matches 99,370 | elapsed 3.3 min | ETA 62.8 min
88,000/1,732,544 (5.08%) | candidates 442,974 | matches 102,082 | elapsed 3.4 min | ETA 63.0 min
90,000/1,732,544 (5.19%) | candidates 452,575 | matches 104,802 | elapsed 3.5 min | ETA 63.0 min
92,000/1,732,544 (5.31%) | candidates 463,772 | matches 107,343 | elapsed 3.5 min | ETA 62.9 min
94,000/1,732,544 (5.43%) | candidates 474,851 | matches 109,948 | elapsed 3.6 min | ETA 63.0 min
96,000/1,732,544 (5.54%) | candidates 485,845 | matches 112,786 | elapsed 3.7 min | ETA 63.1 min
98,000/1,732,544 (5.66%) | candidates 497,909 | matches 115,634 | elapsed 3.8 min | ETA 63.1 min
100,000/1,732,544 (5.77%) | candidates 509,680 | matches 118,434 | elapsed 3.9 min | ETA 63.2 min
102,000/1,732,544 (5.89%) | candidates 522,200 | matches 121,128 | elapsed 4.0 min | ETA 63.2 min
104,000/1,732,544 (6.00%) | candidates 532,597 | matches 123,660 | elapsed 4.0 min | ETA 63.3 min
106,000/1,732,544 (6.12%) | candidates 544,560 | matches 126,420 | elapsed 4.1 min | ETA 63.5 min
108,000/1,732,544 (6.23%) | candidates 554,818 | matches 129,038 | elapsed 4.2 min | ETA 63.6 min
110,000/1,732,544 (6.35%) | candidates 566,699 | matches 131,761 | elapsed 4.3 min | ETA 63.5 min
112,000/1,732,544 (6.46%) | candidates 578,254 | matches 134,505 | elapsed 4.4 min | ETA 63.6 min
114,000/1,732,544 (6.58%) | candidates 590,386 | matches 137,314 | elapsed 4.5 min | ETA 63.6 min
116,000/1,732,544 (6.70%) | candidates 601,075 | matches 139,931 | elapsed 4.6 min | ETA 63.5 min
118,000/1,732,544 (6.81%) | candidates 613,252 | matches 142,599 | elapsed 4.6 min | ETA 63.6 min
120,000/1,732,544 (6.93%) | candidates 626,494 | matches 145,237 | elapsed 4.7 min | ETA 63.5 min
122,000/1,732,544 (7.04%) | candidates 637,382 | matches 147,983 | elapsed 4.8 min | ETA 63.5 min
124,000/1,732,544 (7.16%) | candidates 647,394 | matches 150,560 | elapsed 4.9 min | ETA 63.5 min
126,000/1,732,544 (7.27%) | candidates 658,782 | matches 153,159 | elapsed 5.0 min | ETA 63.5 min
128,000/1,732,544 (7.39%) | candidates 669,873 | matches 155,590 | elapsed 5.1 min | ETA 63.4 min
130,000/1,732,544 (7.50%) | candidates 680,104 | matches 158,137 | elapsed 5.1 min | ETA 63.5 min
132,000/1,732,544 (7.62%) | candidates 692,422 | matches 160,880 | elapsed 5.2 min | ETA 63.6 min
134,000/1,732,544 (7.73%) | candidates 703,782 | matches 163,693 | elapsed 5.3 min | ETA 63.5 min
136,000/1,732,544 (7.85%) | candidates 716,744 | matches 166,414 | elapsed 5.4 min | ETA 63.7 min
138,000/1,732,544 (7.97%) | candidates 728,719 | matches 169,050 | elapsed 5.5 min | ETA 63.6 min
140,000/1,732,544 (8.08%) | candidates 739,035 | matches 171,736 | elapsed 5.6 min | ETA 63.5 min
142,000/1,732,544 (8.20%) | candidates 750,781 | matches 174,328 | elapsed 5.7 min | ETA 63.7 min
144,000/1,732,544 (8.31%) | candidates 763,849 | matches 177,146 | elapsed 5.8 min | ETA 63.6 min
146,000/1,732,544 (8.43%) | candidates 773,440 | matches 179,652 | elapsed 5.8 min | ETA 63.5 min
148,000/1,732,544 (8.54%) | candidates 786,275 | matches 182,384 | elapsed 5.9 min | ETA 63.6 min
150,000/1,732,544 (8.66%) | candidates 798,331 | matches 185,178 | elapsed 6.0 min | ETA 63.5 min
152,000/1,732,544 (8.77%) | candidates 809,723 | matches 187,828 | elapsed 6.1 min | ETA 63.4 min
154,000/1,732,544 (8.89%) | candidates 821,517 | matches 190,362 | elapsed 6.2 min | ETA 63.5 min
156,000/1,732,544 (9.00%) | candidates 832,850 | matches 193,036 | elapsed 6.3 min | ETA 63.4 min
158,000/1,732,544 (9.12%) | candidates 846,996 | matches 195,851 | elapsed 6.4 min | ETA 63.3 min
160,000/1,732,544 (9.23%) | candidates 857,654 | matches 198,479 | elapsed 6.5 min | ETA 63.4 min
162,000/1,732,544 (9.35%) | candidates 869,812 | matches 201,222 | elapsed 6.5 min | ETA 63.3 min
164,000/1,732,544 (9.47%) | candidates 881,146 | matches 204,029 | elapsed 6.6 min | ETA 63.2 min
166,000/1,732,544 (9.58%) | candidates 892,215 | matches 206,732 | elapsed 6.7 min | ETA 63.2 min
168,000/1,732,544 (9.70%) | candidates 902,629 | matches 209,479 | elapsed 6.8 min | ETA 63.1 min
170,000/1,732,544 (9.81%) | candidates 913,609 | matches 212,220 | elapsed 6.9 min | ETA 63.0 min
172,000/1,732,544 (9.93%) | candidates 925,442 | matches 215,180 | elapsed 6.9 min | ETA 63.0 min
174,000/1,732,544 (10.04%) | candidates 938,397 | matches 217,870 | elapsed 7.0 min | ETA 63.0 min
176,000/1,732,544 (10.16%) | candidates 949,577 | matches 220,660 | elapsed 7.1 min | ETA 62.9 min
178,000/1,732,544 (10.27%) | candidates 960,634 | matches 223,327 | elapsed 7.2 min | ETA 63.0 min
180,000/1,732,544 (10.39%) | candidates 973,979 | matches 226,243 | elapsed 7.3 min | ETA 62.9 min
182,000/1,732,544 (10.50%) | candidates 985,004 | matches 229,015 | elapsed 7.4 min | ETA 62.9 min
184,000/1,732,544 (10.62%) | candidates 996,823 | matches 231,785 | elapsed 7.5 min | ETA 62.9 min
186,000/1,732,544 (10.74%) | candidates 1,009,298 | matches 234,601 | elapsed 7.6 min | ETA 62.8 min
188,000/1,732,544 (10.85%) | candidates 1,021,094 | matches 237,365 | elapsed 7.7 min | ETA 63.0 min
190,000/1,732,544 (10.97%) | candidates 1,032,613 | matches 240,077 | elapsed 7.7 min | ETA 62.9 min
192,000/1,732,544 (11.08%) | candidates 1,044,206 | matches 242,831 | elapsed 7.8 min | ETA 62.8 min
194,000/1,732,544 (11.20%) | candidates 1,057,239 | matches 245,502 | elapsed 7.9 min | ETA 62.9 min
196,000/1,732,544 (11.31%) | candidates 1,068,582 | matches 248,252 | elapsed 8.0 min | ETA 62.8 min
198,000/1,732,544 (11.43%) | candidates 1,080,604 | matches 250,949 | elapsed 8.1 min | ETA 62.6 min
200,000/1,732,544 (11.54%) | candidates 1,092,741 | matches 253,850 | elapsed 8.2 min | ETA 62.7 min
202,000/1,732,544 (11.66%) | candidates 1,106,032 | matches 256,729 | elapsed 8.3 min | ETA 62.6 min
204,000/1,732,544 (11.77%) | candidates 1,133,091 | matches 264,430 | elapsed 8.4 min | ETA 62.6 min
206,000/1,732,544 (11.89%) | candidates 1,145,028 | matches 267,232 | elapsed 8.4 min | ETA 62.6 min
208,000/1,732,544 (12.01%) | candidates 1,155,860 | matches 269,785 | elapsed 8.5 min | ETA 62.5 min
210,000/1,732,544 (12.12%) | candidates 1,167,160 | matches 272,675 | elapsed 8.6 min | ETA 62.4 min
212,000/1,732,544 (12.24%) | candidates 1,179,485 | matches 275,332 | elapsed 8.7 min | ETA 62.4 min
214,000/1,732,544 (12.35%) | candidates 1,190,395 | matches 277,966 | elapsed 8.8 min | ETA 62.3 min
216,000/1,732,544 (12.47%) | candidates 1,202,210 | matches 280,860 | elapsed 8.9 min | ETA 62.2 min
218,000/1,732,544 (12.58%) | candidates 1,215,510 | matches 283,690 | elapsed 8.9 min | ETA 62.2 min
220,000/1,732,544 (12.70%) | candidates 1,228,040 | matches 286,449 | elapsed 9.0 min | ETA 62.1 min
222,000/1,732,544 (12.81%) | candidates 1,238,261 | matches 289,259 | elapsed 9.1 min | ETA 62.0 min
224,000/1,732,544 (12.93%) | candidates 1,251,152 | matches 292,159 | elapsed 9.2 min | ETA 62.0 min
226,000/1,732,544 (13.04%) | candidates 1,263,363 | matches 294,772 | elapsed 9.3 min | ETA 62.0 min
228,000/1,732,544 (13.16%) | candidates 1,275,816 | matches 297,413 | elapsed 9.4 min | ETA 61.9 min
230,000/1,732,544 (13.28%) | candidates 1,287,210 | matches 300,122 | elapsed 9.5 min | ETA 61.9 min
232,000/1,732,544 (13.39%) | candidates 1,300,361 | matches 303,034 | elapsed 9.6 min | ETA 61.8 min
234,000/1,732,544 (13.51%) | candidates 1,310,905 | matches 305,630 | elapsed 9.7 min | ETA 61.8 min
236,000/1,732,544 (13.62%) | candidates 1,322,394 | matches 308,548 | elapsed 9.7 min | ETA 61.8 min
238,000/1,732,544 (13.74%) | candidates 1,333,727 | matches 311,251 | elapsed 9.8 min | ETA 61.7 min
240,000/1,732,544 (13.85%) | candidates 1,344,455 | matches 313,843 | elapsed 9.9 min | ETA 61.6 min
242,000/1,732,544 (13.97%) | candidates 1,355,202 | matches 316,365 | elapsed 10.0 min | ETA 61.6 min
244,000/1,732,544 (14.08%) | candidates 1,367,747 | matches 319,131 | elapsed 10.1 min | ETA 61.5 min
246,000/1,732,544 (14.20%) | candidates 1,377,835 | matches 321,664 | elapsed 10.2 min | ETA 61.5 min
248,000/1,732,544 (14.31%) | candidates 1,391,617 | matches 324,475 | elapsed 10.3 min | ETA 61.4 min
250,000/1,732,544 (14.43%) | candidates 1,402,722 | matches 327,111 | elapsed 10.3 min | ETA 61.2 min
252,000/1,732,544 (14.55%) | candidates 1,414,166 | matches 329,819 | elapsed 10.4 min | ETA 61.2 min
254,000/1,732,544 (14.66%) | candidates 1,425,037 | matches 332,499 | elapsed 10.5 min | ETA 61.1 min
256,000/1,732,544 (14.78%) | candidates 1,436,483 | matches 335,196 | elapsed 10.6 min | ETA 61.0 min
258,000/1,732,544 (14.89%) | candidates 1,447,786 | matches 337,947 | elapsed 10.7 min | ETA 61.0 min
260,000/1,732,544 (15.01%) | candidates 1,458,571 | matches 340,598 | elapsed 10.8 min | ETA 60.9 min
262,000/1,732,544 (15.12%) | candidates 1,470,533 | matches 343,304 | elapsed 10.8 min | ETA 60.8 min
264,000/1,732,544 (15.24%) | candidates 1,483,465 | matches 345,992 | elapsed 10.9 min | ETA 60.8 min
266,000/1,732,544 (15.35%) | candidates 1,493,737 | matches 348,785 | elapsed 11.0 min | ETA 60.7 min
268,000/1,732,544 (15.47%) | candidates 1,503,522 | matches 351,480 | elapsed 11.1 min | ETA 60.7 min
270,000/1,732,544 (15.58%) | candidates 1,517,805 | matches 354,317 | elapsed 11.2 min | ETA 60.7 min
272,000/1,732,544 (15.70%) | candidates 1,529,041 | matches 357,161 | elapsed 11.3 min | ETA 60.6 min
274,000/1,732,544 (15.81%) | candidates 1,540,098 | matches 359,915 | elapsed 11.4 min | ETA 60.5 min
276,000/1,732,544 (15.93%) | candidates 1,551,801 | matches 362,573 | elapsed 11.5 min | ETA 60.5 min
278,000/1,732,544 (16.05%) | candidates 1,562,779 | matches 365,465 | elapsed 11.5 min | ETA 60.4 min
280,000/1,732,544 (16.16%) | candidates 1,575,669 | matches 368,158 | elapsed 11.6 min | ETA 60.3 min
282,000/1,732,544 (16.28%) | candidates 1,586,665 | matches 370,896 | elapsed 11.7 min | ETA 60.3 min
284,000/1,732,544 (16.39%) | candidates 1,597,047 | matches 373,628 | elapsed 11.8 min | ETA 60.2 min
286,000/1,732,544 (16.51%) | candidates 1,609,210 | matches 376,373 | elapsed 11.9 min | ETA 60.1 min
288,000/1,732,544 (16.62%) | candidates 1,621,325 | matches 378,977 | elapsed 12.0 min | ETA 60.1 min
290,000/1,732,544 (16.74%) | candidates 1,631,971 | matches 381,613 | elapsed 12.1 min | ETA 60.0 min
292,000/1,732,544 (16.85%) | candidates 1,642,013 | matches 384,114 | elapsed 12.2 min | ETA 60.0 min
294,000/1,732,544 (16.97%) | candidates 1,654,765 | matches 386,993 | elapsed 12.3 min | ETA 60.0 min
296,000/1,732,544 (17.08%) | candidates 1,668,019 | matches 389,850 | elapsed 12.3 min | ETA 59.9 min
298,000/1,732,544 (17.20%) | candidates 1,680,312 | matches 392,549 | elapsed 12.4 min | ETA 59.9 min
300,000/1,732,544 (17.32%) | candidates 1,691,779 | matches 395,478 | elapsed 12.5 min | ETA 59.8 min
302,000/1,732,544 (17.43%) | candidates 1,703,707 | matches 398,305 | elapsed 12.6 min | ETA 59.7 min
304,000/1,732,544 (17.55%) | candidates 1,715,041 | matches 401,148 | elapsed 12.7 min | ETA 59.7 min
306,000/1,732,544 (17.66%) | candidates 1,725,700 | matches 403,980 | elapsed 12.8 min | ETA 59.5 min
308,000/1,732,544 (17.78%) | candidates 1,737,755 | matches 406,609 | elapsed 12.9 min | ETA 59.5 min
310,000/1,732,544 (17.89%) | candidates 1,748,351 | matches 409,282 | elapsed 12.9 min | ETA 59.4 min
312,000/1,732,544 (18.01%) | candidates 1,762,402 | matches 412,209 | elapsed 13.0 min | ETA 59.3 min
314,000/1,732,544 (18.12%) | candidates 1,775,249 | matches 415,148 | elapsed 13.1 min | ETA 59.2 min
316,000/1,732,544 (18.24%) | candidates 1,786,896 | matches 417,790 | elapsed 13.2 min | ETA 59.2 min
318,000/1,732,544 (18.35%) | candidates 1,799,356 | matches 420,437 | elapsed 13.3 min | ETA 59.1 min
320,000/1,732,544 (18.47%) | candidates 1,811,145 | matches 423,230 | elapsed 13.4 min | ETA 59.1 min
322,000/1,732,544 (18.59%) | candidates 1,821,325 | matches 425,894 | elapsed 13.5 min | ETA 59.0 min
324,000/1,732,544 (18.70%) | candidates 1,831,517 | matches 428,448 | elapsed 13.5 min | ETA 58.9 min
326,000/1,732,544 (18.82%) | candidates 1,842,370 | matches 431,000 | elapsed 13.6 min | ETA 58.8 min
328,000/1,732,544 (18.93%) | candidates 1,853,771 | matches 433,676 | elapsed 13.7 min | ETA 58.8 min
330,000/1,732,544 (19.05%) | candidates 1,866,064 | matches 436,336 | elapsed 13.8 min | ETA 58.7 min
332,000/1,732,544 (19.16%) | candidates 1,877,906 | matches 439,288 | elapsed 13.9 min | ETA 58.6 min
334,000/1,732,544 (19.28%) | candidates 1,888,755 | matches 442,022 | elapsed 14.0 min | ETA 58.5 min
336,000/1,732,544 (19.39%) | candidates 1,901,007 | matches 444,874 | elapsed 14.1 min | ETA 58.5 min
338,000/1,732,544 (19.51%) | candidates 1,912,250 | matches 447,483 | elapsed 14.2 min | ETA 58.4 min
340,000/1,732,544 (19.62%) | candidates 1,924,200 | matches 450,352 | elapsed 14.2 min | ETA 58.3 min
342,000/1,732,544 (19.74%) | candidates 1,936,556 | matches 453,054 | elapsed 14.3 min | ETA 58.2 min
344,000/1,732,544 (19.86%) | candidates 1,948,022 | matches 455,816 | elapsed 14.4 min | ETA 58.2 min
346,000/1,732,544 (19.97%) | candidates 1,959,839 | matches 458,707 | elapsed 14.5 min | ETA 58.1 min
348,000/1,732,544 (20.09%) | candidates 1,971,319 | matches 461,317 | elapsed 14.6 min | ETA 58.0 min
350,000/1,732,544 (20.20%) | candidates 1,982,989 | matches 464,041 | elapsed 14.7 min | ETA 58.0 min
352,000/1,732,544 (20.32%) | candidates 1,995,134 | matches 466,719 | elapsed 14.8 min | ETA 57.9 min
354,000/1,732,544 (20.43%) | candidates 2,006,294 | matches 469,306 | elapsed 14.9 min | ETA 57.8 min
356,000/1,732,544 (20.55%) | candidates 2,018,991 | matches 471,960 | elapsed 15.0 min | ETA 57.9 min
358,000/1,732,544 (20.66%) | candidates 2,032,016 | matches 474,593 | elapsed 15.1 min | ETA 57.8 min
360,000/1,732,544 (20.78%) | candidates 2,043,341 | matches 477,239 | elapsed 15.2 min | ETA 57.8 min
362,000/1,732,544 (20.89%) | candidates 2,055,825 | matches 480,015 | elapsed 15.2 min | ETA 57.7 min
364,000/1,732,544 (21.01%) | candidates 2,068,297 | matches 482,663 | elapsed 15.3 min | ETA 57.6 min
366,000/1,732,544 (21.13%) | candidates 2,080,724 | matches 485,429 | elapsed 15.4 min | ETA 57.6 min
368,000/1,732,544 (21.24%) | candidates 2,091,685 | matches 488,034 | elapsed 15.5 min | ETA 57.5 min
370,000/1,732,544 (21.36%) | candidates 2,102,742 | matches 490,621 | elapsed 15.6 min | ETA 57.4 min
372,000/1,732,544 (21.47%) | candidates 2,113,029 | matches 493,114 | elapsed 15.7 min | ETA 57.4 min
374,000/1,732,544 (21.59%) | candidates 2,125,559 | matches 496,003 | elapsed 15.8 min | ETA 57.3 min
376,000/1,732,544 (21.70%) | candidates 2,137,405 | matches 498,599 | elapsed 15.9 min | ETA 57.2 min
378,000/1,732,544 (21.82%) | candidates 2,148,460 | matches 501,170 | elapsed 16.0 min | ETA 57.2 min
380,000/1,732,544 (21.93%) | candidates 2,159,326 | matches 504,007 | elapsed 16.0 min | ETA 57.1 min
382,000/1,732,544 (22.05%) | candidates 2,170,581 | matches 506,647 | elapsed 16.1 min | ETA 57.0 min
384,000/1,732,544 (22.16%) | candidates 2,181,049 | matches 509,397 | elapsed 16.2 min | ETA 56.9 min
386,000/1,732,544 (22.28%) | candidates 2,192,523 | matches 512,078 | elapsed 16.3 min | ETA 56.8 min
388,000/1,732,544 (22.39%) | candidates 2,205,306 | matches 514,909 | elapsed 16.4 min | ETA 56.7 min
390,000/1,732,544 (22.51%) | candidates 2,215,175 | matches 517,432 | elapsed 16.5 min | ETA 56.7 min
392,000/1,732,544 (22.63%) | candidates 2,225,803 | matches 520,002 | elapsed 16.6 min | ETA 56.6 min
394,000/1,732,544 (22.74%) | candidates 2,237,269 | matches 522,670 | elapsed 16.6 min | ETA 56.5 min
396,000/1,732,544 (22.86%) | candidates 2,248,742 | matches 525,527 | elapsed 16.7 min | ETA 56.5 min
398,000/1,732,544 (22.97%) | candidates 2,260,343 | matches 528,259 | elapsed 16.8 min | ETA 56.4 min
400,000/1,732,544 (23.09%) | candidates 2,272,175 | matches 530,938 | elapsed 16.9 min | ETA 56.3 min
402,000/1,732,544 (23.20%) | candidates 2,281,942 | matches 533,434 | elapsed 17.0 min | ETA 56.3 min
404,000/1,732,544 (23.32%) | candidates 2,293,350 | matches 536,161 | elapsed 17.1 min | ETA 56.2 min
406,000/1,732,544 (23.43%) | candidates 2,305,339 | matches 538,988 | elapsed 17.2 min | ETA 56.2 min
408,000/1,732,544 (23.55%) | candidates 2,319,302 | matches 541,784 | elapsed 17.3 min | ETA 56.1 min
410,000/1,732,544 (23.66%) | candidates 2,330,356 | matches 544,453 | elapsed 17.4 min | ETA 56.0 min
412,000/1,732,544 (23.78%) | candidates 2,340,962 | matches 547,292 | elapsed 17.5 min | ETA 56.0 min

KeyboardInterrupt:

In [ ]:
!pip install -q catboost rapidfuzz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 36.5 MB/s eta 0:00:00

In [ ]:
import os

for path in [
    "/content/drive/MyDrive",
    "/content/drive/My Drive"
]:
    print("\nCHECK:", path)
    print("Exists:", os.path.exists(path))
    if os.path.exists(path):
        print(os.listdir(path)[:20])

CHECK: /content/drive/MyDrive
Exists: False

CHECK: /content/drive/My Drive
Exists: False

In [ ]:
import os

base_paths = [
    "/content/drive/MyDrive/Amazon-ML-Challenge-2026",
    "/content/drive/My Drive/Amazon-ML-Challenge-2026"
]

for base in base_paths:
    print("\nCHECK:", base)
    if os.path.exists(base):
        for root, dirs, files in os.walk(base):
            depth = root.replace(base, "").count(os.sep)
            if depth <= 3:
                print(root)

CHECK: /content/drive/MyDrive/Amazon-ML-Challenge-2026

CHECK: /content/drive/My Drive/Amazon-ML-Challenge-2026

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

print("Drive mounted:",
      os.path.exists("/content/drive"))

print("\nAmazon ML folder:")
print(
    os.path.exists(
        "/content/drive/MyDrive/Amazon-ML-Challenge-2026"
    )
)

print("\nV5 indexes:")
print(
    os.path.exists(
        "/content/drive/MyDrive/"
        "Amazon-ML-Challenge-2026/ml/V5_full_indexes"
    )
)

print("\nV5 model:")
print(
    os.path.exists(
        "/content/drive/MyDrive/"
        "Amazon-ML-Challenge-2026/ml/"
        "V5_ML_Final/V5_ML_Final/v5_model.cbm"
    )
)

Drive mounted: True

Amazon ML folder:
True

V5 indexes:
True

V5 model:
True

In [ ]:
# ============================================================
# CLEAN RESTART — LOAD SAVED V5 ASSETS
# ============================================================

import os
import re
import gc
import pickle
import unicodedata
import numpy as np
import pandas as pd

from catboost import CatBoostClassifier
from rapidfuzz.fuzz import ratio

BASE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"

MODEL_PATH = f"{BASE}/V5_ML_Final/V5_ML_Final/v5_model.cbm"
INDEX_DIR = f"{BASE}/V5_full_indexes"

# ------------------------------------------------------------
# Normalization
# ------------------------------------------------------------

def normalize_advanced_local(text):
    if text is None or pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def tokens_fast(text):
    return set(text.split()) if text else set()


def extract_numbers_fast(text):
    return set(re.findall(r"\d+", text))


# ------------------------------------------------------------
# Load pickle
# ------------------------------------------------------------

def load_pickle(filename):
    path = os.path.join(INDEX_DIR, filename)

    with open(path, "rb") as f:
        obj = pickle.load(f)

    print("Loaded:", filename)
    return obj


# S2
s2_name_index = load_pickle("s2_name_index.pkl")
s2_addr_index = load_pickle("s2_addr_index.pkl")
s2_name_freq = load_pickle("s2_name_freq.pkl")
s2_addr_freq = load_pickle("s2_addr_freq.pkl")

# S3
s3_name_index = load_pickle("s3_name_index.pkl")
s3_addr_index = load_pickle("s3_addr_index.pkl")
s3_name_freq = load_pickle("s3_name_freq.pkl")
s3_addr_freq = load_pickle("s3_addr_freq.pkl")

# ------------------------------------------------------------
# Load V5
# ------------------------------------------------------------

v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

print("\n" + "=" * 60)
print("V5 MODEL:", v5_model.is_fitted())
print("TREES:", v5_model.tree_count_)
print("MODEL EXISTS:", os.path.exists(MODEL_PATH))
print("INDEX DIR EXISTS:", os.path.exists(INDEX_DIR))
print("=" * 60)

gc.collect()

Loaded: s2_name_index.pkl
Loaded: s2_addr_index.pkl
Loaded: s2_name_freq.pkl
Loaded: s2_addr_freq.pkl
Loaded: s3_name_index.pkl
Loaded: s3_addr_index.pkl
Loaded: s3_name_freq.pkl
Loaded: s3_addr_freq.pkl

============================================================
V5 MODEL: True
TREES: 670
MODEL EXISTS: True
INDEX DIR EXISTS: True
============================================================

8

In [ ]:
import os

print("Checking /content...")

for name in os.listdir("/content"):
    print(name)

Checking /content...
.config
drive
sample_data

In [ ]:
import os

matches = []

for root, dirs, files in os.walk("/content"):
    # Don't scan huge system folders unnecessarily
    dirs[:] = [
        d for d in dirs
        if d not in ["proc", "sys", "dev", "usr", "opt"]
    ]

    if "test_source2.tsv" in files:
        matches.append(os.path.join(root, "test_source2.tsv"))

print("\nFound test_source2.tsv:")
for x in matches:
    print(x)

Found test_source2.tsv:

In [ ]:
import os

print("Searching Google Drive for test_source2.tsv...")

found = []

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    # Skip common large/system-like folders
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "node_modules", "__pycache__"]
    ]

    if "test_source2.tsv" in files:
        found.append(os.path.join(root, "test_source2.tsv"))

print("\nFOUND:")
for path in found:
    print(path)

print("\nTotal:", len(found))

Searching Google Drive for test_source2.tsv...

FOUND:

Total: 0

In [ ]:
import os
import zipfile

# Find the uploaded ZIP
zips = [f for f in os.listdir("/content") if f.lower().endswith(".zip")]

print("ZIP files found:")
for z in zips:
    size = os.path.getsize("/content/" + z) / (1024**3)
    print(f"{z}  →  {size:.2f} GB")

# Show the first few files inside the ZIP
zip_path = "/content/" + zips[0]

with zipfile.ZipFile(zip_path, "r") as z:
    print("\nFirst 30 files inside ZIP:")
    for name in z.namelist()[:30]:
        print(name)

ZIP files found:
6ab10eb3b23ba_student_resource.zip  →  1.02 GB

First 30 files inside ZIP:
student_resource/
__MACOSX/._student_resource
student_resource/Documentation_template.md
__MACOSX/student_resource/._Documentation_template.md
student_resource/.DS_Store
__MACOSX/student_resource/._.DS_Store
student_resource/dataset/
__MACOSX/student_resource/._dataset
student_resource/utils/
__MACOSX/student_resource/._utils
student_resource/README.md
__MACOSX/student_resource/._README.md
student_resource/dataset/.DS_Store
__MACOSX/student_resource/dataset/._.DS_Store
student_resource/dataset/test/
__MACOSX/student_resource/dataset/._test
student_resource/dataset/train/
__MACOSX/student_resource/dataset/._train
student_resource/utils/validate_submission.py
__MACOSX/student_resource/utils/._validate_submission.py
student_resource/dataset/test/test_source2.tsv
__MACOSX/student_resource/dataset/test/._test_source2.tsv
student_resource/dataset/test/test_source3.tsv
__MACOSX/student_resource/dataset/test/._test_source3.tsv
student_resource/dataset/test/test_source1.tsv
__MACOSX/student_resource/dataset/test/._test_source1.tsv
student_resource/dataset/train/train_ground_truth.tsv
__MACOSX/student_resource/dataset/train/._train_ground_truth.tsv
student_resource/dataset/train/train_source2.tsv
__MACOSX/student_resource/dataset/train/._train_source2.tsv

In [ ]:
import os
import zipfile
import shutil

zip_path = "/content/6ab10eb3b23ba_student_resource.zip"
target = "/content/amazon_ml_challenge"

# Check free space first
total, used, free = shutil.disk_usage("/content")
print(f"Free space: {free / (1024**3):.2f} GB")

# Extract only student_resource/
with zipfile.ZipFile(zip_path, "r") as z:
    members = [
        m for m in z.namelist()
        if m.startswith("student_resource/") and "__MACOSX" not in m
    ]

    print(f"Extracting {len(members)} files...")
    z.extractall(target, members)

print("\nExtraction complete!")
print("Dataset location:")
print("/content/amazon_ml_challenge/student_resource")

Free space: 85.31 GB
Extracting 17 files...

Extraction complete!
Dataset location:
/content/amazon_ml_challenge/student_resource

In [ ]:
import os
import pandas as pd

base = "/content/amazon_ml_challenge/student_resource"

files = {
    "test_source1.tsv": f"{base}/dataset/test/test_source1.tsv",
    "test_source2.tsv": f"{base}/dataset/test/test_source2.tsv",
    "test_source3.tsv": f"{base}/dataset/test/test_source3.tsv",
    "train_source1.tsv": f"{base}/dataset/train/train_source1.tsv",
    "train_source2.tsv": f"{base}/dataset/train/train_source2.tsv",
    "train_source3.tsv": f"{base}/dataset/train/train_source3.tsv",
    "train_ground_truth.tsv": f"{base}/dataset/train/train_ground_truth.tsv",
}

for name, path in files.items():
    if os.path.exists(path):
        rows = sum(1 for _ in open(path, encoding="utf-8")) - 1
        print(f"✅ {name:25} {rows:,} rows")
    else:
        print(f"❌ MISSING: {name}")

✅ test_source1.tsv          1,732,544 rows
✅ test_source2.tsv          4,887,273 rows
✅ test_source3.tsv          5,082,316 rows
✅ train_source1.tsv         2,206,821 rows
✅ train_source2.tsv         5,034,616 rows
✅ train_source3.tsv         5,285,603 rows
✅ train_ground_truth.tsv    2,206,821 rows

In [ ]:
import os

drive_base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"

paths = [
    f"{drive_base}/V5_full_indexes",
    f"{drive_base}/V5_ML_Final/V5_ML_Final/v5_model.cbm",
    f"{drive_base}/V5_ML_Final/V5_ML_Final/v5_feature_list.txt",
    f"{drive_base}/V5_ML_Final/V5_ML_Final/v5_inference.py",
]

print("V5 ASSETS")
print("=" * 60)

for p in paths:
    print("✅" if os.path.exists(p) else "❌", p)

print("\nIndex files:")
index_dir = f"{drive_base}/V5_full_indexes"

if os.path.exists(index_dir):
    for f in sorted(os.listdir(index_dir)):
        size = os.path.getsize(os.path.join(index_dir, f)) / (1024**2)
        print(f"  {f:45} {size:,.1f} MB")

V5 ASSETS
============================================================
✅ /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes
✅ /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm
✅ /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_feature_list.txt
✅ /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_inference.py

Index files:
  s2_addr_freq.pkl                              16.5 MB
  s2_addr_index.pkl                             196.7 MB
  s2_name_freq.pkl                              12.7 MB
  s2_name_index.pkl                             96.4 MB
  s3_addr_freq.pkl                              16.0 MB
  s3_addr_index.pkl                             196.1 MB
  s3_name_freq.pkl                              13.6 MB
  s3_name_index.pkl                             100.9 MB

In [ ]:
from pathlib import Path

path = Path(
    "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_inference.py"
)

print(path.read_text())

from catboost import CatBoostClassifier
import pandas as pd

MODEL_PATH = "/content/drive/MyDrive/V5_ML_Final/v5_model.cbm"

FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]

model = CatBoostClassifier()
model.load_model(MODEL_PATH)

def add_v5_features(df):
    X = df[FEATURES[:16]].copy()

    X["similarity_gap"] = (
        X["name_similarity"] - X["address_similarity"]
    ).abs()

    X["max_similarity"] = X[
        ["name_similarity", "address_similarity"]
    ].max(axis=1)

    X["similarity_product"] = (
        X["name_similarity"] * X["address_similarity"]
    )

    X["token_overlap_gap"] = (
        X["name_token_overlap"] - X["address_token_overlap"]
    ).abs()

    return X[FEATURES]

def predict_v5(candidate_features, threshold=0.60):
    X = add_v5_features(candidate_features)
    probability = model.predict_proba(X)[:, 1]
    prediction = (probability >= threshold).astype(int)
    return probability, prediction

In [ ]:
from pathlib import Path

path = Path(
    "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_inference.py"
)

lines = path.read_text().splitlines()

print(f"Total lines: {len(lines)}\n")

for i, line in enumerate(lines, 1):
    low = line.lower()

    if any(x in low for x in [
        "candidate",
        "block",
        "index",
        "generate",
        "rare",
        "token",
        "threshold",
        "def "
    ]):
        print(f"{i:4}: {line}")

Total lines: 58

  13:     "name_token_overlap",
  14:     "address_token_overlap",
  17:     "shared_name_token_count",
  18:     "shared_address_token_count",
  27:     "token_overlap_gap"
  33: def add_v5_features(df):
  48:     X["token_overlap_gap"] = (
  49:         X["name_token_overlap"] - X["address_token_overlap"]
  54: def predict_v5(candidate_features, threshold=0.60):
  55:     X = add_v5_features(candidate_features)
  57:     prediction = (probability >= threshold).astype(int)

In [ ]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"

print("Files in ML folder:\n")

for root, dirs, files in os.walk(base):
    # Don't print huge index directories
    if "V5_full_indexes" in root:
        continue

    for f in files:
        if f.endswith((".py", ".ipynb", ".txt")):
            full = os.path.join(root, f)
            print(full)

Files in ML folder:

/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_inference.py
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_feature_list.txt
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/V5_final_report.txt
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Inference/checkpoint.txt

In [ ]:
checkpoint = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Inference/checkpoint.txt"

with open(checkpoint, "r") as f:
    print(f.read())

632000

In [ ]:
report = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/V5_final_report.txt"

with open(report, "r") as f:
    print(f.read())

V5 FINAL REPORT

Model: CatBoost
V5 validation Entity Macro F0.5: 0.902677
Reference V3 baseline: 0.889883
Threshold: 0.60
Best iteration: 669
Feature count: 20

V5 added features:
1. similarity_gap
2. max_similarity
3. similarity_product
4. token_overlap_gap

Reload verification:
1000 validation candidates checked
Max prediction difference: 0.0
Mean prediction difference: 0.0
Predictions identical: True

Threshold predictions:
0.55 -> 4601
0.60 -> 4581
0.65 -> 4552
0.70 -> 4527

Note:
The 0.902677 validation score was obtained on the reconstructed S1-level validation split.

In [ ]:
import pickle
import os

index_dir = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

for filename in [
    "s2_name_index.pkl",
    "s2_addr_index.pkl",
    "s3_name_index.pkl",
    "s3_addr_index.pkl"
]:
    path = os.path.join(index_dir, filename)

    print("\n" + "=" * 70)
    print(filename)

    with open(path, "rb") as f:
        obj = pickle.load(f)

    print("Type:", type(obj))

    if hasattr(obj, "shape"):
        print("Shape:", obj.shape)

    if hasattr(obj, "columns"):
        print("Columns:", list(obj.columns))

    if isinstance(obj, dict):
        print("Dictionary entries:", len(obj))
        items = list(obj.items())[:3]

        for k, v in items:
            print("KEY:", repr(k))
            print("VALUE TYPE:", type(v))
            try:
                print("VALUE SAMPLE:", list(v)[:5])
            except:
                print("VALUE:", repr(v)[:200])

======================================================================
s2_name_index.pkl
Type: <class 'dict'>
Dictionary entries: 861199
KEY: 'infosoft'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 12836, 34939, 78057, 78476]
KEY: 'brahma'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 2233, 54387, 59391, 60885]
KEY: 'france'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [1, 91, 643, 797, 823]

======================================================================
s2_addr_index.pkl
Type: <class 'dict'>
Dictionary entries: 1330963
KEY: 'coimatore'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 418293, 2292520, 2301832, 3840450]
KEY: 'tqmysore'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 2301832, 4416899, 4870862]
KEY: 'hunsur'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 31632, 198565, 399106, 919719]

======================================================================
s3_name_index.pkl
Type: <class 'dict'>
Dictionary entries: 918689
KEY: 'फाइनेंस'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 2588, 4846, 5553, 5855]
KEY: 'मॉडर्न'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 185, 5336, 7724, 8047]
KEY: 'infratech'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [1, 16, 18, 20, 153]

======================================================================
s3_addr_index.pkl
Type: <class 'dict'>
Dictionary entries: 1296266
KEY: 'square,'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 2633, 2719, 2835, 2838]
KEY: 'no'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 18, 24, 26, 34]
KEY: 'enkay'
VALUE TYPE: <class 'list'>
VALUE SAMPLE: [0, 19387, 102838, 150313, 201613]

In [ ]:
import pandas as pd
import pickle
import os
import re
import unicodedata
from difflib import SequenceMatcher

BASE = "/content/amazon_ml_challenge/student_resource"
INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

# --------------------------------------------------
# Normalization
# --------------------------------------------------

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def tokenize(text):
    return set(text.split()) if text else set()


def similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


# --------------------------------------------------
# Load first 5,000 S1
# --------------------------------------------------

s1_path = f"{BASE}/dataset/test/test_source1.tsv"

s1 = pd.read_csv(
    s1_path,
    sep="\t",
    nrows=5000,
    dtype=str
)

print("S1:", s1.shape)
print(s1.columns.tolist())

# --------------------------------------------------
# Load S2/S3 columns needed for candidate testing
# --------------------------------------------------

s2_path = f"{BASE}/dataset/test/test_source2.tsv"
s3_path = f"{BASE}/dataset/test/test_source3.tsv"

print("\nLoading S2...")
s2 = pd.read_csv(
    s2_path,
    sep="\t",
    usecols=["entity_id", "business_name", "business_address", "country"],
    dtype=str
)

print("S2:", s2.shape)

print("\nLoading S3...")
s3 = pd.read_csv(
    s3_path,
    sep="\t",
    usecols=["entity_id", "business_name", "business_address", "country"],
    dtype=str
)

print("S3:", s3.shape)

S1: (5000, 4)
['entity_id', 'business_name', 'business_address', 'country']

Loading S2...
S2: (4887273, 4)

Loading S3...
S3: (5082316, 4)

In [ ]:
import os
import shutil

print("Runtime is back.")

total, used, free = shutil.disk_usage("/content")

print(f"Free disk: {free / 1024**3:.2f} GB")

Runtime is back.
Free disk: 82.95 GB

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import psutil

ram = psutil.virtual_memory()

print(f"Total RAM : {ram.total / 1024**3:.2f} GB")
print(f"Used RAM  : {ram.used / 1024**3:.2f} GB")
print(f"Free RAM  : {ram.available / 1024**3:.2f} GB")

Total RAM : 12.67 GB
Used RAM  : 1.42 GB
Free RAM  : 10.97 GB

In [ ]:
import pickle
import os
import gc
import psutil

INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

path = f"{INDEX_DIR}/s2_name_index.pkl"

print("RAM before loading:")
ram = psutil.virtual_memory()
print(f"Available: {ram.available / 1024**3:.2f} GB")

print("\nLoading ONLY s2_name_index.pkl...")

with open(path, "rb") as f:
    test_index = pickle.load(f)

print("Loaded.")
print("Entries:", len(test_index))

ram = psutil.virtual_memory()
print(f"Available after load: {ram.available / 1024**3:.2f} GB")

# Immediately release it
del test_index
gc.collect()

ram = psutil.virtual_memory()
print(f"Available after release: {ram.available / 1024**3:.2f} GB")

RAM before loading:
Available: 10.94 GB

Loading ONLY s2_name_index.pkl...
Loaded.
Entries: 861199
Available after load: 10.10 GB
Available after release: 10.78 GB

In [ ]:
import pandas as pd
import psutil
import gc

s2_path = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"

print("RAM before S2:")
ram = psutil.virtual_memory()
print(f"Available: {ram.available / 1024**3:.2f} GB")

print("\nLoading S2...")

s2 = pd.read_csv(
    s2_path,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str
)

print("S2 loaded:", s2.shape)

ram = psutil.virtual_memory()
print(f"Available after S2: {ram.available / 1024**3:.2f} GB")

RAM before S2:
Available: 10.96 GB

Loading S2...
S2 loaded: (4887273, 4)
Available after S2: 9.55 GB

In [ ]:
import pickle
import psutil

INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

print("RAM before indexes:")
print(f"{psutil.virtual_memory().available / 1024**3:.2f} GB")

print("\nLoading S2 name index...")
with open(f"{INDEX_DIR}/s2_name_index.pkl", "rb") as f:
    s2_name_index = pickle.load(f)

print(f"S2 name index: {len(s2_name_index):,} entries")
print(f"Available RAM: {psutil.virtual_memory().available / 1024**3:.2f} GB")

print("\nLoading S2 address index...")
with open(f"{INDEX_DIR}/s2_addr_index.pkl", "rb") as f:
    s2_addr_index = pickle.load(f)

print(f"S2 address index: {len(s2_addr_index):,} entries")
print(f"Available RAM: {psutil.virtual_memory().available / 1024**3:.2f} GB")

RAM before indexes:
9.60 GB

Loading S2 name index...
S2 name index: 861,199 entries
Available RAM: 8.86 GB

Loading S2 address index...
S2 address index: 1,330,963 entries
Available RAM: 7.04 GB

In [ ]:
import re
import unicodedata
from itertools import combinations
from difflib import SequenceMatcher

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def tokenize(text):
    return set(text.split()) if text else set()


def similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


def posting_intersection(index, tokens):
    tokens = [t for t in set(tokens) if t in index]

    if not tokens:
        return set()

    tokens.sort(key=lambda t: len(index[t]))

    result = set(index[tokens[0]])

    for token in tokens[1:]:
        result.intersection_update(index[token])

        if not result:
            break

    return result


def get_postings(index, tokens):
    tokens = [t for t in set(tokens) if t in index]

    if len(tokens) < 2:
        return set()

    tokens.sort(key=lambda t: len(index[t]))

    result = set()
    seeds = tokens[:4]

    for i in range(len(seeds)):
        for j in range(i + 1, len(seeds)):
            a = index[seeds[i]]
            b = index[seeds[j]]

            if len(a) > len(b):
                a, b = b, a

            bset = set(b)

            for row in a:
                if row in bset:
                    result.add(row)

    return result


print("✅ Candidate-generation helper functions loaded.")

✅ Candidate-generation helper functions loaded.

In [ ]:
# Create country array for S2
s2_country = (
    s2["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .values
)

print("✅ s2_country created")
print("Length:", len(s2_country))
print("Available RAM:", f"{psutil.virtual_memory().available / 1024**3:.2f} GB")

✅ s2_country created
Length: 4887273
Available RAM: 6.59 GB

In [ ]:
import time
import gc
import psutil
from difflib import SequenceMatcher

# Make sure we have the 5K S1
s1_path = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"

s1_5k = pd.read_csv(
    s1_path,
    sep="\t",
    nrows=5000,
    dtype=str
)

def available_ram():
    return psutil.virtual_memory().available / 1024**3


def get_postings(index, tokens):
    """
    Return candidate row positions sharing at least 2 tokens.
    Uses pair intersections rather than materializing every
    token's full posting list into one giant set.
    """
    tokens = [t for t in set(tokens) if t in index]

    if len(tokens) < 2:
        return set()

    # Use the rarest tokens first.
    tokens.sort(key=lambda t: len(index[t]))

    result = set()

    # Use combinations of the rarest 4 tokens.
    seeds = tokens[:4]

    for i in range(len(seeds)):
        for j in range(i + 1, len(seeds)):
            a = index[seeds[i]]
            b = index[seeds[j]]

            # Iterate over the smaller posting list.
            if len(a) > len(b):
                a, b = b, a

            bset = set(b)

            for row in a:
                if row in bset:
                    result.add(row)

    return result


start = time.time()

total_raw = 0
total_selected = 0

for i, row in s1_5k.iterrows():

    name = normalize_advanced(row["business_name"])
    address = normalize_advanced(row["business_address"])
    country = str(row["country"]).lower().strip()

    name_tokens = tokenize(name)
    addr_tokens = tokenize(address)

    candidates = set()

    # -------------------------------
    # Exact name
    # -------------------------------
    if name_tokens:
        rows = posting_intersection(s2_name_index, name_tokens)

        for r in rows:
            if s2_country[r] == country:
                candidates.add(r)

    # -------------------------------
    # Exact address
    # -------------------------------
    if addr_tokens:
        rows = posting_intersection(s2_addr_index, addr_tokens)

        for r in rows:
            if s2_country[r] == country:
                candidates.add(r)

    # -------------------------------
    # Name: >=2 shared tokens
    # -------------------------------
    name_rows = get_postings(
        s2_name_index,
        name_tokens
    )

    for r in name_rows:

        if s2_country[r] != country:
            continue

        candidate_name = normalize_advanced(
            s2.iloc[r]["business_name"]
        )

        if similarity(name, candidate_name) >= 0.60:
            candidates.add(r)

    # -------------------------------
    # Address: >=3 shared tokens
    # -------------------------------
    addr_rows_3 = set()

    if len(addr_tokens) >= 3:

        tokens = [
            t for t in addr_tokens
            if t in s2_addr_index
        ]

        tokens.sort(
            key=lambda t: len(s2_addr_index[t])
        )

        for combo in combinations(tokens[:4], 3):

            rows = posting_intersection(
                s2_addr_index,
                combo
            )

            for r in rows:
                if s2_country[r] == country:
                    addr_rows_3.add(r)

    candidates.update(addr_rows_3)

    # -------------------------------
    # Address: >=2 shared tokens
    # + similarity >= 0.30
    # -------------------------------
    addr_rows_2 = get_postings(
        s2_addr_index,
        addr_tokens
    )

    for r in addr_rows_2:

        if s2_country[r] != country:
            continue

        candidate_addr = normalize_advanced(
            s2.iloc[r]["business_address"]
        )

        if similarity(address, candidate_addr) >= 0.30:
            candidates.add(r)

    total_selected += len(candidates)

    if (i + 1) % 500 == 0:
        elapsed = time.time() - start

        print(
            f"{i+1:,}/5,000 | "
            f"selected={total_selected:,} | "
            f"avg={total_selected/(i+1):.2f}/S1 | "
            f"RAM={available_ram():.2f} GB | "
            f"time={elapsed:.1f}s"
        )

print("\n" + "=" * 60)
print("S2 BENCHMARK COMPLETE")
print("=" * 60)

print(f"Total selected candidates: {total_selected:,}")
print(f"Average candidates/S1: {total_selected/5000:.2f}")
print(f"Time: {time.time()-start:.2f}s")
print(f"RAM available: {available_ram():.2f} GB")

KeyboardInterrupt:

In [ ]:
print("Benchmark stopped safely.")

Benchmark stopped safely.

In [ ]:
import gc
import psutil

gc.collect()

ram = psutil.virtual_memory()

print(f"Available RAM: {ram.available / 1024**3:.2f} GB")
print(f"Used RAM:      {ram.used / 1024**3:.2f} GB")

Available RAM: 6.79 GB
Used RAM:      5.61 GB

In [ ]:
import gc
import psutil

# Remove anything from the failed benchmark
for name in [
    "raw_counts",
    "selected_counts",
    "s1_500",
]:
    if name in globals():
        del globals()[name]

gc.collect()

ram = psutil.virtual_memory()

print(f"Available RAM: {ram.available / 1024**3:.2f} GB")

Available RAM: 6.76 GB

In [ ]:
# Confirm the important V5 assets and current memory state

import os
import psutil

MODEL_PATH = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm"
INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"
TEST_DIR = "/content/amazon_ml_challenge/student_resource/dataset/test"

print("V5 model:", os.path.exists(MODEL_PATH))
print("Indexes:", os.path.exists(INDEX_DIR))
print("Test data:", os.path.exists(TEST_DIR))
print(f"Available RAM: {psutil.virtual_memory().available / 1024**3:.2f} GB")

V5 model: True
Indexes: True
Test data: True
Available RAM: 6.74 GB

In [ ]:
# ============================================================
# V5 PRODUCTION SMOKE TEST — 100 S1
# ============================================================

import os
import gc
import time
import pickle
import psutil
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import ratio

BASE = "/content/amazon_ml_challenge/student_resource"
INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"
MODEL_PATH = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm"

def ram_gb():
    return psutil.virtual_memory().available / (1024**3)

print("Starting V5 smoke test")
print(f"RAM available: {ram_gb():.2f} GB")

# ------------------------------------------------------------
# Load only 100 S1
# ------------------------------------------------------------

s1_test = pd.read_csv(
    f"{BASE}/dataset/test/test_source1.tsv",
    sep="\t",
    nrows=100,
    dtype=str
)

print("S1 loaded:", s1_test.shape)

# ------------------------------------------------------------
# S2
# ------------------------------------------------------------

print("\nLoading S2...")
s2_test = pd.read_csv(
    f"{BASE}/dataset/test/test_source2.tsv",
    sep="\t",
    usecols=["entity_id", "business_name", "business_address", "country"],
    dtype=str
)

print("S2:", s2_test.shape)
print(f"RAM: {ram_gb():.2f} GB")

# ------------------------------------------------------------
# S2 indexes
# ------------------------------------------------------------

print("\nLoading S2 indexes...")

with open(f"{INDEX_DIR}/s2_name_index.pkl", "rb") as f:
    name_index = pickle.load(f)

with open(f"{INDEX_DIR}/s2_addr_index.pkl", "rb") as f:
    addr_index = pickle.load(f)

print("S2 indexes loaded.")
print(f"RAM: {ram_gb():.2f} GB")

# ------------------------------------------------------------
# Country array
# ------------------------------------------------------------

countries = (
    s2_test["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .values
)

# ------------------------------------------------------------
# Fast candidate generation
# ------------------------------------------------------------

def get_candidates(name, address, country):

    name_tokens = tokenize(name)
    addr_tokens = tokenize(address)

    candidates = set()

    # Exact name
    if name_tokens:
        rows = posting_intersection(name_index, name_tokens)

        for r in rows:
            if countries[r] == country:
                candidates.add(r)

    # Exact address
    if addr_tokens:
        rows = posting_intersection(addr_index, addr_tokens)

        for r in rows:
            if countries[r] == country:
                candidates.add(r)

    # Name >= 2 shared tokens
    valid = [t for t in name_tokens if t in name_index]

    valid.sort(key=lambda x: len(name_index[x]))

    for i in range(min(4, len(valid))):
        for j in range(i + 1, min(4, len(valid))):

            a = name_index[valid[i]]
            b = name_index[valid[j]]

            if len(a) > len(b):
                a, b = b, a

            bset = set(b)

            for r in a:
                if r in bset and countries[r] == country:
                    candidates.add(r)

    # Address >= 2 shared tokens
    valid = [t for t in addr_tokens if t in addr_index]

    valid.sort(key=lambda x: len(addr_index[x]))

    for i in range(min(4, len(valid))):
        for j in range(i + 1, min(4, len(valid))):

            a = addr_index[valid[i]]
            b = addr_index[valid[j]]

            if len(a) > len(b):
                a, b = b, a

            bset = set(b)

            for r in a:
                if r in bset and countries[r] == country:
                    candidates.add(r)

    return candidates


# ------------------------------------------------------------
# Generate + filter 100 S1
# ------------------------------------------------------------

start = time.time()

candidate_counts = []
final_counts = []

for n, row in enumerate(s1_test.itertuples(index=False), 1):

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)
    country = str(row.country).lower().strip()

    candidates = get_candidates(
        name,
        address,
        country
    )

    candidate_counts.append(len(candidates))

    # Apply cheap RapidFuzz filtering
    final = 0

    for r in candidates:

        cand_name = normalize_advanced(
            s2_test.iloc[r]["business_name"]
        )

        cand_addr = normalize_advanced(
            s2_test.iloc[r]["business_address"]
        )

        name_sim = ratio(name, cand_name) / 100
        addr_sim = ratio(address, cand_addr) / 100

        if (
            name == cand_name
            or address == cand_addr
            or name_sim >= 0.60
            or addr_sim >= 0.30
        ):
            final += 1

    final_counts.append(final)

    if n % 25 == 0:
        print(
            f"{n}/100 | "
            f"raw avg={np.mean(candidate_counts):.2f} | "
            f"final avg={np.mean(final_counts):.2f} | "
            f"RAM={ram_gb():.2f} GB"
        )

elapsed = time.time() - start

print("\n" + "=" * 60)
print("SMOKE TEST COMPLETE")
print("=" * 60)

print(f"S1 processed:       {len(candidate_counts)}")
print(f"Raw candidates:     {sum(candidate_counts):,}")
print(f"Raw candidates/S1:  {np.mean(candidate_counts):.2f}")
print(f"Final candidates:   {sum(final_counts):,}")
print(f"Final candidates/S1:{np.mean(final_counts):.2f}")
print(f"Time:               {elapsed:.2f} sec")
print(f"RAM available:      {ram_gb():.2f} GB")

Starting V5 smoke test
RAM available: 6.70 GB
S1 loaded: (100, 4)

Loading S2...
S2: (4887273, 4)
RAM: 5.30 GB

Loading S2 indexes...
S2 indexes loaded.
RAM: 2.90 GB
25/100 | raw avg=52684.40 | final avg=50433.28 | RAM=2.64 GB
50/100 | raw avg=61279.34 | final avg=58899.40 | RAM=2.75 GB
75/100 | raw avg=54928.00 | final avg=52343.43 | RAM=2.74 GB
100/100 | raw avg=64409.21 | final avg=61695.34 | RAM=2.75 GB

============================================================
SMOKE TEST COMPLETE
============================================================
S1 processed:       100
Raw candidates:     6,440,921
Raw candidates/S1:  64409.21
Final candidates:   6,169,534
Final candidates/S1:61695.34
Time:               644.42 sec
RAM available:      2.75 GB

In [ ]:
import gc

for name in [
    "s2_test",
    "s2_name_index",
    "s2_addr_index",
    "name_index",
    "addr_index",
    "countries",
    "s1_test"
]:
    if name in globals():
        del globals()[name]

gc.collect()

import psutil
print(f"Available RAM: {psutil.virtual_memory().available / 1024**3:.2f} GB")

Available RAM: 6.53 GB

In [ ]:
# ============================================================
# 100-S1 TEST OF THE MEASURED <=500 BLOCKER
# S2 ONLY — NO MODEL YET
# ============================================================

import os
import gc
import pickle
import time
import psutil
import pandas as pd
from rapidfuzz.fuzz import ratio

BASE = "/content/amazon_ml_challenge/student_resource"
INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

def ram_gb():
    return psutil.virtual_memory().available / (1024**3)

# ------------------------------------------------------------
# Load only 100 S1
# ------------------------------------------------------------

s1_100 = pd.read_csv(
    f"{BASE}/dataset/test/test_source1.tsv",
    sep="\t",
    nrows=100,
    dtype=str
)

# ------------------------------------------------------------
# Load S2
# ------------------------------------------------------------

print("Loading S2...")
s2 = pd.read_csv(
    f"{BASE}/dataset/test/test_source2.tsv",
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str
)

print("S2:", s2.shape)
print(f"RAM after S2: {ram_gb():.2f} GB")

# ------------------------------------------------------------
# Load S2 indexes + frequency dictionaries
# ------------------------------------------------------------

print("Loading S2 indexes...")

with open(f"{INDEX_DIR}/s2_name_index.pkl", "rb") as f:
    name_index = pickle.load(f)

with open(f"{INDEX_DIR}/s2_addr_index.pkl", "rb") as f:
    addr_index = pickle.load(f)

with open(f"{INDEX_DIR}/s2_name_freq.pkl", "rb") as f:
    name_freq = pickle.load(f)

with open(f"{INDEX_DIR}/s2_addr_freq.pkl", "rb") as f:
    addr_freq = pickle.load(f)

print("Indexes loaded.")
print(f"RAM: {ram_gb():.2f} GB")

# ------------------------------------------------------------
# Country array
# ------------------------------------------------------------

s2_country = (
    s2["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .values
)

# ------------------------------------------------------------
# Measured <=500 blocker
# ------------------------------------------------------------

def rare_postings(index, freq, tokens, limit=500):

    rows = set()

    for token in tokens:

        if token not in index:
            continue

        if freq.get(token, 10**9) > limit:
            continue

        rows.update(index[token])

    return rows


def generate_500_candidates(name, address, country):

    name_tokens = tokenize(name)
    addr_tokens = tokenize(address)

    candidates = set()

    # --------------------------------------------------------
    # Exact name
    # --------------------------------------------------------

    if name:
        rows = name_index.get(name)

        if rows is not None:
            for r in rows:
                if s2_country[r] == country:
                    candidates.add(r)

    # --------------------------------------------------------
    # Exact address
    # --------------------------------------------------------

    if address:
        rows = addr_index.get(address)

        if rows is not None:
            for r in rows:
                if s2_country[r] == country:
                    candidates.add(r)

    # --------------------------------------------------------
    # Rare name tokens <= 500
    # --------------------------------------------------------

    rows = rare_postings(
        name_index,
        name_freq,
        name_tokens,
        500
    )

    for r in rows:

        if s2_country[r] != country:
            continue

        cand_name = normalize_advanced(
            s2.iloc[r]["business_name"]
        )

        if ratio(name, cand_name) >= 60:
            candidates.add(r)

    # --------------------------------------------------------
    # Rare address tokens <= 500
    # --------------------------------------------------------

    rows = rare_postings(
        addr_index,
        addr_freq,
        addr_tokens,
        500
    )

    for r in rows:

        if s2_country[r] != country:
            continue

        cand_addr = normalize_advanced(
            s2.iloc[r]["business_address"]
        )

        if ratio(address, cand_addr) >= 60:
            candidates.add(r)

    return candidates


# ------------------------------------------------------------
# Run 100 S1
# ------------------------------------------------------------

start = time.time()

counts = []

for i, row in enumerate(s1_100.itertuples(index=False), 1):

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)
    country = str(row.country).lower().strip()

    cands = generate_500_candidates(
        name,
        address,
        country
    )

    counts.append(len(cands))

    if i % 20 == 0:
        print(
            f"{i}/100 | "
            f"avg candidates/S1 = {sum(counts)/len(counts):.2f} | "
            f"RAM = {ram_gb():.2f} GB"
        )

print("\n" + "=" * 60)
print("MEASURED BLOCKER TEST")
print("=" * 60)
print(f"S1 processed:       {len(counts)}")
print(f"Total candidates:   {sum(counts):,}")
print(f"Candidates/S1:      {sum(counts)/len(counts):.2f}")
print(f"Time:               {time.time()-start:.2f} sec")
print(f"RAM available:      {ram_gb():.2f} GB")

Loading S2...
S2: (4887273, 4)
RAM after S2: 4.48 GB
Loading S2 indexes...

KeyboardInterrupt:

In [ ]:
# Measure RAW rare-token candidates before similarity filtering

raw_counts = []
selected_counts = []

for row in s1_100.itertuples(index=False):

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)
    country = str(row.country).lower().strip()

    name_tokens = tokenize(name)
    addr_tokens = tokenize(address)

    raw = set()

    # rare name tokens <= 500
    for token in name_tokens:
        if (
            token in name_index
            and name_freq.get(token, 10**9) <= 500
        ):
            for r in name_index[token]:
                if s2_country[r] == country:
                    raw.add(r)

    # rare address tokens <= 500
    for token in addr_tokens:
        if (
            token in addr_index
            and addr_freq.get(token, 10**9) <= 500
        ):
            for r in addr_index[token]:
                if s2_country[r] == country:
                    raw.add(r)

    raw_counts.append(len(raw))

    # similarity filtering
    selected = 0

    for r in raw:
        cn = normalize_advanced(s2.iloc[r]["business_name"])
        ca = normalize_advanced(s2.iloc[r]["business_address"])

        ns = ratio(name, cn) / 100
        ads = ratio(address, ca) / 100

        if max(ns, ads) >= 0.60:
            selected += 1

    selected_counts.append(selected)

print("RAW candidates/S1:", sum(raw_counts) / len(raw_counts))
print("SELECTED/S1:", sum(selected_counts) / len(selected_counts))

RAW candidates/S1: 336.43
SELECTED/S1: 41.77

In [ ]:
# ============================================================
# V3-STYLE BLOCKER — 100 S1 / S2 ONLY
# ============================================================

import time
import psutil

def ram_gb():
    return psutil.virtual_memory().available / (1024**3)

LIMIT = 1000

def v3_s2_candidates(name, address, country):

    name_tokens = tokenize(name)
    addr_tokens = tokenize(address)

    candidates = set()

    # --------------------------------------------------------
    # 1. Exact name + country
    # --------------------------------------------------------
    if name:
        rows = name_index.get(name, [])
        for r in rows:
            if s2_country[r] == country:
                candidates.add(r)

    # --------------------------------------------------------
    # 2. Exact address + country
    # --------------------------------------------------------
    if address:
        rows = addr_index.get(address, [])
        for r in rows:
            if s2_country[r] == country:
                candidates.add(r)

    # --------------------------------------------------------
    # 3. Rare name token + country
    # --------------------------------------------------------
    for token in name_tokens:

        if token not in name_index:
            continue

        if name_freq.get(token, 10**9) > LIMIT:
            continue

        for r in name_index[token]:
            if s2_country[r] == country:
                candidates.add(r)

    # --------------------------------------------------------
    # 4. Rare address token + country
    # --------------------------------------------------------
    for token in addr_tokens:

        if token not in addr_index:
            continue

        if addr_freq.get(token, 10**9) > LIMIT:
            continue

        for r in addr_index[token]:
            if s2_country[r] == country:
                candidates.add(r)

    # --------------------------------------------------------
    # 5. V3 multi-address-token block
    #
    # At least 2 shared address tokens AND
    # at least one shared token is rare (<= LIMIT).
    # --------------------------------------------------------

    rare_addr_tokens = [
        t for t in addr_tokens
        if (
            t in addr_index
            and addr_freq.get(t, 10**9) <= LIMIT
        )
    ]

    if len(addr_tokens) >= 2 and rare_addr_tokens:

        # Candidates sharing a rare address token
        rare_rows = set()

        for token in rare_addr_tokens:
            rare_rows.update(addr_index[token])

        # Require at least 2 shared address tokens
        # and same country.
        for r in rare_rows:

            if s2_country[r] != country:
                continue

            # We need the candidate's normalized address.
            cand_addr = normalize_advanced(
                s2.iloc[r]["business_address"]
            )

            shared = (
                tokenize(address)
                &
                tokenize(cand_addr)
            )

            if len(shared) >= 2:
                candidates.add(r)

    return candidates


start = time.time()

counts = []

for i, row in enumerate(s1_100.itertuples(index=False), 1):

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)
    country = str(row.country).lower().strip()

    cands = v3_s2_candidates(
        name,
        address,
        country
    )

    counts.append(len(cands))

    if i % 20 == 0:
        print(
            f"{i}/100 | "
            f"avg candidates/S1 = {sum(counts)/len(counts):.2f} | "
            f"RAM = {ram_gb():.2f} GB"
        )

print("\n" + "=" * 60)
print("V3-STYLE S2 TEST")
print("=" * 60)
print(f"S1 processed:      {len(counts)}")
print(f"Total candidates:  {sum(counts):,}")
print(f"Candidates/S1:     {sum(counts)/len(counts):.2f}")
print(f"Time:              {time.time()-start:.2f} sec")
print(f"RAM available:     {ram_gb():.2f} GB")

20/100 | avg candidates/S1 = 612.20 | RAM = 4.88 GB
40/100 | avg candidates/S1 = 698.25 | RAM = 4.88 GB
60/100 | avg candidates/S1 = 669.90 | RAM = 4.88 GB
80/100 | avg candidates/S1 = 679.48 | RAM = 4.88 GB
100/100 | avg candidates/S1 = 670.71 | RAM = 4.88 GB

============================================================
V3-STYLE S2 TEST
============================================================
S1 processed:      100
Total candidates:  67,071
Candidates/S1:     670.71
Time:              6.71 sec
RAM available:     4.88 GB

In [ ]:
import os
import pickle
import psutil

path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/ml_features_v3_1000.pkl"

print("File exists:", os.path.exists(path))

if os.path.exists(path):
    size_gb = os.path.getsize(path) / (1024**3)
    print(f"File size: {size_gb:.2f} GB")

    print("\nRAM before loading:")
    print(f"{psutil.virtual_memory().available / 1024**3:.2f} GB")

    with open(path, "rb") as f:
        obj = pickle.load(f)

    print("\nLoaded object type:")
    print(type(obj))

    if hasattr(obj, "shape"):
        print("Shape:", obj.shape)

    if hasattr(obj, "columns"):
        print("Columns:")
        print(list(obj.columns))

    if hasattr(obj, "head"):
        print("\nFirst 5 rows:")
        print(obj.head())

    print("\nRAM after loading:")
    print(f"{psutil.virtual_memory().available / 1024**3:.2f} GB")

File exists: True
File size: 0.03 GB

RAM before loading:
4.85 GB

Loaded object type:
<class 'pandas.core.frame.DataFrame'>
Shape: (208971, 19)
Columns:
['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard', 'address_jaccard', 'shared_name_token_count', 'shared_address_token_count', 'shared_address_number_count', 'name_length_diff', 'address_length_diff', 'name_length_ratio', 'address_length_ratio', 'source1_entity_id', 'matched_entity_id', 'label']

First 5 rows:
   name_exact  address_exact  country_exact  name_similarity  \
0           0              0              1         0.882353
1           0              1              1         0.742857
2           0              0              1         0.928571
3           0              0              1         0.509804
4           0              1              1         0.947368

   address_similarity  name_token_overlap  address_token_overlap  \
0            0.830769                1.00               0.750000
1            1.000000                1.00               1.000000
2            0.676923                1.00               0.666667
3            0.933333                1.00               0.600000
4            1.000000                0.75               1.000000

   name_jaccard  address_jaccard  shared_name_token_count  \
0      0.666667         0.500000                        2
1      0.666667         1.000000                        2
2      0.750000         0.444444                        3
3      0.500000         0.428571                        2
4      0.600000         1.000000                        3

   shared_address_token_count  shared_address_number_count  name_length_diff  \
0                           3                            0                 4
1                           5                            1                 9
2                           4                            1                 4
3                           3                            0                25
4                           6                            1                 0

   address_length_diff  name_length_ratio  address_length_ratio  \
0                    3           0.789474              0.911765
1                    0           0.590909              1.000000
2                    5           0.866667              0.857143
3                    2           0.342105              0.935484
4                    0           1.000000              1.000000

  source1_entity_id matched_entity_id  label
0      S1-921451574      S3-334166749      1
1      S1-523623802       S2-20138400      1
2      S1-718184733      S2-810418229      1
3       S1-75862106      S3-970865082      1
4      S1-487019031       S2-11699163      1

RAM after loading:
4.83 GB

In [ ]:
# ============================================================
# INSPECT THE ACTUAL V3 CANDIDATE PAIRS
# ============================================================

v3 = obj

print("Rows:", len(v3))
print("Columns:", len(v3.columns))

# ------------------------------------------------------------
# Basic candidate composition
# ------------------------------------------------------------

print("\n=== EXACT MATCH FEATURES ===")
print("Name exact:", v3["name_exact"].sum())
print("Address exact:", v3["address_exact"].sum())
print("Both exact:", (
    (v3["name_exact"] == 1) &
    (v3["address_exact"] == 1)
).sum())

# ------------------------------------------------------------
# Shared token counts
# ------------------------------------------------------------

print("\n=== SHARED NAME TOKENS ===")
print(
    v3["shared_name_token_count"]
    .value_counts()
    .sort_index()
    .head(15)
)

print("\n=== SHARED ADDRESS TOKENS ===")
print(
    v3["shared_address_token_count"]
    .value_counts()
    .sort_index()
    .head(20)
)

# ------------------------------------------------------------
# Candidates with neither exact name nor exact address
# ------------------------------------------------------------

non_exact = v3[
    (v3["name_exact"] == 0) &
    (v3["address_exact"] == 0)
]

print("\n=== NON-EXACT CANDIDATES ===")
print("Count:", len(non_exact))

print(
    "Name shared tokens min:",
    non_exact["shared_name_token_count"].min()
)

print(
    "Address shared tokens min:",
    non_exact["shared_address_token_count"].min()
)

# ------------------------------------------------------------
# How many have >=2 shared name/address tokens?
# ------------------------------------------------------------

print("\n=== TOKEN BLOCK STRUCTURE ===")

print(
    ">=2 shared name tokens:",
    (non_exact["shared_name_token_count"] >= 2).sum()
)

print(
    ">=2 shared address tokens:",
    (non_exact["shared_address_token_count"] >= 2).sum()
)

print(
    ">=3 shared address tokens:",
    (non_exact["shared_address_token_count"] >= 3).sum()
)

print(
    ">=2 name AND >=2 address:",
    (
        (non_exact["shared_name_token_count"] >= 2) &
        (non_exact["shared_address_token_count"] >= 2)
    ).sum()
)

# ------------------------------------------------------------
# Similarity structure
# ------------------------------------------------------------

print("\n=== SIMILARITY ===")

print(
    "Name similarity median:",
    non_exact["name_similarity"].median()
)

print(
    "Address similarity median:",
    non_exact["address_similarity"].median()
)

print(
    "Name similarity >= .60:",
    (non_exact["name_similarity"] >= .60).sum()
)

print(
    "Address similarity >= .30:",
    (non_exact["address_similarity"] >= .30).sum()
)

print(
    "Address similarity >= .60:",
    (non_exact["address_similarity"] >= .60).sum()
)

Rows: 208971
Columns: 19

=== EXACT MATCH FEATURES ===
Name exact: 9924
Address exact: 3295
Both exact: 602

=== SHARED NAME TOKENS ===
shared_name_token_count
0     140140
1      34368
2      17826
3       9176
4       5619
5       1412
6        325
7         79
8         18
9          6
10         2
Name: count, dtype: int64

=== SHARED ADDRESS TOKENS ===
shared_address_token_count
0     16092
1     86575
2     42888
3     21675
4     14993
5     10812
6      5557
7      2633
8      1590
9      1381
10     1077
11      922
12      738
13      616
14      458
15      332
16      216
17      153
18       81
19       92
Name: count, dtype: int64

=== NON-EXACT CANDIDATES ===
Count: 196354
Name shared tokens min: 0
Address shared tokens min: 0

=== TOKEN BLOCK STRUCTURE ===
>=2 shared name tokens: 22775
>=2 shared address tokens: 97778
>=3 shared address tokens: 55122
>=2 name AND >=2 address: 16540

=== SIMILARITY ===
Name similarity median: 0.2916666666666667
Address similarity median: 0.40384615384615385
Name similarity >= .60: 20014
Address similarity >= .30: 157891
Address similarity >= .60: 26274

In [ ]:
# ============================================================
# V3 CANDIDATE MATRIX — STRUCTURE CHECK
# ============================================================

v3 = obj

print("V3 rows:", len(v3))
print("V3 S1 entities:", v3["source1_entity_id"].nunique())

# Candidates per S1
counts = v3.groupby("source1_entity_id").size()

print("\nCandidate count per S1")
print("Average:", counts.mean())
print("Median:", counts.median())
print("P90:", counts.quantile(0.90))
print("P95:", counts.quantile(0.95))
print("P99:", counts.quantile(0.99))
print("Maximum:", counts.max())

# Positive pairs per S1
positive_counts = (
    v3[v3["label"] == 1]
    .groupby("source1_entity_id")
    .size()
)

print("\nPositive pairs")
print("Total:", int(v3["label"].sum()))
print("S1 with positives:", len(positive_counts))
print("Average positives among matched S1:", positive_counts.mean())
print("Maximum positives:", positive_counts.max())

# Candidate composition
print("\nCandidate composition")

conditions = {
    "exact name": v3["name_exact"] == 1,
    "exact address": v3["address_exact"] == 1,
    ">=2 name tokens": v3["shared_name_token_count"] >= 2,
    ">=2 address tokens": v3["shared_address_token_count"] >= 2,
    ">=3 address tokens": v3["shared_address_token_count"] >= 3,
    ">=2 name AND >=2 address": (
        (v3["shared_name_token_count"] >= 2) &
        (v3["shared_address_token_count"] >= 2)
    ),
}

for label, mask in conditions.items():
    print(f"{label:30s}: {mask.sum():,}")

# Positive recall of each condition
print("\nPositive-pair coverage")

positives = v3[v3["label"] == 1]

for label, mask in conditions.items():
    print(
        f"{label:30s}: "
        f"{mask.loc[positives.index].sum():,} / {len(positives):,} "
        f"= {mask.loc[positives.index].mean():.2%}"
    )

V3 rows: 208971
V3 S1 entities: 7654

Candidate count per S1
Average: 27.30219493075516
Median: 20.0
P90: 61.0
P95: 74.0
P99: 101.0
Maximum: 182

Positive pairs
Total: 23219
S1 with positives: 7136
Average positives among matched S1: 3.2537836322869955
Maximum positives: 11

Candidate composition
exact name                    : 9,924
exact address                 : 3,295
>=2 name tokens               : 34,463
>=2 address tokens            : 106,304
>=3 address tokens            : 63,416
>=2 name AND >=2 address      : 24,318

Positive-pair coverage
exact name                    : 6,067 / 23,219 = 26.13%
exact address                 : 3,247 / 23,219 = 13.98%
>=2 name tokens               : 19,215 / 23,219 = 82.76%
>=2 address tokens            : 22,563 / 23,219 = 97.17%
>=3 address tokens            : 22,125 / 23,219 = 95.29%
>=2 name AND >=2 address      : 18,581 / 23,219 = 80.02%

In [ ]:
# Find the original V3 candidate-generation code from the notebook
# if the notebook file is available in the current Drive/project.

import os

for root, dirs, files in os.walk(
    "/content/drive/MyDrive/Amazon-ML-Challenge-2026"
):
    for f in files:
        if f.endswith(".ipynb"):
            print(os.path.join(root, f))

/content/drive/MyDrive/Amazon-ML-Challenge-2026/notebooks/Amazon_ML_Challenge_2026.ipynb

In [ ]:
import json

NOTEBOOK = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/notebooks/Amazon_ML_Challenge_2026.ipynb"

with open(NOTEBOOK, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Total cells:", len(nb["cells"]))

for i, cell in enumerate(nb["cells"]):
    source = "".join(cell.get("source", []))

    keywords = [
        "V3",
        "candidate",
        "block",
        "rare",
        "freq",
        "shared_address"
    ]

    if any(k.lower() in source.lower() for k in keywords):
        print("\n" + "=" * 80)
        print("CELL", i)
        print("=" * 80)
        print(source[:12000])

Total cells: 255

================================================================================
CELL 27
================================================================================
def get_candidates(row):

    entity_id = row["entity_id"]

    name = normalize_name(row["business_name"])
    address = normalize_address(row["business_address"])
    country = normalize_country(row["country"])

    candidates = set()

    # ------------------------------------------------
    # RULE 1: exact normalized address + country
    # ------------------------------------------------

    if address:
        key = (country, address)

        candidates.update(
            s2_address.get(key, [])
        )

        candidates.update(
            s3_address.get(key, [])
        )

    # ------------------------------------------------
    # RULE 2: exact normalized name + country
    # ------------------------------------------------

    if name:
        key = (country, name)

        candidates.update(
            s2_name.get(key, [])
        )

        candidates.update(
            s3_name.get(key, [])
        )

    return sorted(candidates)

================================================================================
CELL 28
================================================================================
results = []
candidate_results = []

for i, row in s1_test.iterrows():

    candidates = get_candidates(row)

    candidate_results.append({
        "source1_entity_id": row["entity_id"],
        "candidate_entity_ids": ",".join(candidates)
    })

    # For V1, use candidates directly as matches.
    results.append({
        "source1_entity_id": row["entity_id"],
        "matched_entity_ids": ",".join(candidates)
    })

    if (i + 1) % 100000 == 0:
        print(f"Processed {i+1:,} / {len(s1_test):,}")

================================================================================
CELL 29
================================================================================
print("Loop completed!")
print("Results:", len(results))
print("Candidates:", len(candidate_results))

================================================================================
CELL 30
================================================================================
matching_df = pd.DataFrame(results)
candidate_df = pd.DataFrame(candidate_results)

matching_path = os.path.join(
    OUTPUT,
    "matching_results.tsv"
)

candidate_path = os.path.join(
    OUTPUT,
    "candidate_pairs.tsv"
)

matching_df.to_csv(
    matching_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

candidate_df.to_csv(
    candidate_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

print("Files created successfully!")
print(matching_path)
print(candidate_path)

================================================================================
CELL 32
================================================================================
print("CANDIDATE FILE")
print("=" * 60)

print("Rows:", len(candidate_df))
print("Columns:", candidate_df.columns.tolist())

display(candidate_df.head(10))

================================================================================
CELL 33
================================================================================
matched_nonempty = (
    matching_df["matched_entity_ids"]
    .fillna("")
    .str.strip()
    .ne("")
    .sum()
)

candidate_nonempty = (
    candidate_df["candidate_entity_ids"]
    .fillna("")
    .str.strip()
    .ne("")
    .sum()
)

print("Total S1:", len(matching_df))
print("S1 with matches:", matched_nonempty)
print("S1 with NO matches:", len(matching_df) - matched_nonempty)

print()
print("S1 with candidates:", candidate_nonempty)
print("S1 with NO candidates:", len(candidate_df) - candidate_nonempty)

================================================================================
CELL 34
================================================================================
candidate_counts = (
    candidate_df["candidate_entity_ids"]
    .fillna("")
    .apply(lambda x: len(x.split(",")) if x.strip() else 0)
)

print("Candidate statistics")
print("=" * 60)
print("Minimum:", candidate_counts.min())
print("Average:", candidate_counts.mean())
print("Median:", candidate_counts.median())
print("Maximum:", candidate_counts.max())

print("\nPercentiles:")
print(candidate_counts.quantile([0.50, 0.75, 0.90, 0.95, 0.99]))

================================================================================
CELL 38
================================================================================
def generate_candidates(row):

    name = normalize_name(row["business_name"])
    address = normalize_address(row["business_address"])
    country = normalize_country(row["country"])

    candidates = set()

    # Block 1: country + exact normalized address
    if address:
        key = (country, address)

        candidates.update(s2_address.get(key, []))
        candidates.update(s3_address.get(key, []))

    # Block 2: country + normalized name
    if name:
        key = (country, name)

        candidates.update(s2_name.get(key, []))
        candidates.update(s3_name.get(key, []))

    return sorted(candidates)

================================================================================
CELL 39
================================================================================
submission_template = pd.DataFrame({
    "source1_entity_id": s1_test["entity_id"],
    "matched_entity_ids": ""
})

candidate_template = pd.DataFrame({
    "source1_entity_id": s1_test["entity_id"],
    "candidate_entity_ids": ""
})

print(submission_template.shape)
print(candidate_template.shape)

================================================================================
CELL 41
================================================================================
from rapidfuzz.fuzz import ratio

def pair_features(s1, candidate):

    name1 = normalize_name(s1["business_name"])
    name2 = normalize_name(candidate["business_name"])

    addr1 = normalize_address(s1["business_address"])
    addr2 = normalize_address(candidate["business_address"])

    country1 = normalize_country(s1["country"])
    country2 = normalize_country(candidate["country"])

    return {
        "name_exact": int(name1 == name2),
        "address_exact": int(addr1 == addr2),
        "country_exact": int(country1 == country2),

        "name_similarity": ratio(name1, name2) / 100,
        "address_similarity": ratio(addr1, addr2) / 100,

        "name_length_diff": abs(len(name1) - len(name2)),
        "address_length_diff": abs(len(addr1) - len(addr2)),

        "name_token_overlap": len(
            set(name1.split()) & set(name2.split())
        ) / max(
            1,
            len(set(name1.split()) | set(name2.split()))
        ),

        "address_token_overlap": len(
            set(addr1.split()) & set(addr2.split())
        ) / max(
            1,
            len(set(addr1.split()) | set(addr2.split()))
        )
    }

================================================================================
CELL 51
================================================================================
from collections import defaultdict

def collect_candidates_from_source(path, s1_name_map, s1_address_map):
    candidates = defaultdict(set)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name", "business_address", "country"],
        chunksize=200_000
    ):
        for _, row in chunk.iterrows():

            eid = row["entity_id"]
            country = normalize_country(row["country"])

            name = normalize_advanced(row["business_name"])
            address = normalize_advanced(row["business_address"])

            # Advanced name match
            if name:
                key = (country, name)
                for sid in s1_name_map.get(key, []):
                    candidates[sid].add(eid)

            # Advanced address match
            if address:
                key = (country, address)
                for sid in s1_address_map.get(key, []):
                    candidates[sid].add(eid)

    return candidates


print("Scanning Source 2...")
cand_s2 = collect_candidates_from_source(
    f"{TRAIN}/train_source2.tsv",
    s1_name_map,
    s1_address_map
)

print("Source 2 finished.")
print("S1 records with S2 candidates:", len(cand_s2))

print("Scanning Source 3...")
cand_s3 = collect_candidates_from_source(
    f"{TRAIN}/train_source3.tsv",
    s1_name_map,
    s1_address_map
)

print("Source 3 finished.")
print("S1 records with S3 candidates:", len(cand_s3))

================================================================================
CELL 54
================================================================================
import pandas as pd
import os

matching_file = f"{OUTPUT}/matching_results.tsv"
candidate_file = f"{OUTPUT}/candidate_pairs.tsv"

print("MATCHING FILE")
print("Size:", round(os.path.getsize(matching_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(matching_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(matching_file, encoding="utf-8")) - 1)

print("\nCANDIDATE FILE")
print("Size:", round(os.path.getsize(candidate_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(candidate_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(candidate_file, encoding="utf-8")) - 1)

================================================================================
CELL 55
================================================================================
import pandas as pd

matching = pd.read_csv(
    f"{OUTPUT}/matching_results.tsv",
    sep="\t"
)

candidate = pd.read_csv(
    f"{OUTPUT}/candidate_pairs.tsv",
    sep="\t"
)

print("Matching rows:", len(matching))
print("Candidate rows:", len(candidate))

print("\nMatching examples:")
print(matching.head(10).to_string(index=False))

print("\nCandidate examples:")
print(candidate.head(10).to_string(index=False))

print("\nEmpty matching rows:",
      matching["matched_entity_ids"].fillna("").eq("").sum())

print("Empty candidate rows:",
      candidate["candidate_entity_ids"].fillna("").eq("").sum())

================================================================================
CELL 63
================================================================================
keywords = [
    "pair_features",
    "rapidfuzz",
    "ground_truth",
    "candidate",
    "train_features",
    "CatBoostClassifier",
    "precision",
    "recall",
    "f0.5",
    "threshold"
]

for i, cell in enumerate(nb["cells"]):
    code = "".join(cell.get("source", []))

    if any(k.lower() in code.lower() for k in keywords):
        print("\n" + "="*80)
        print("CELL", i)
        print("="*80)
        print(code)

================================================================================
CELL 64
================================================================================
import os
import glob

print("Searching for training feature/candidate files...\n")

for f in glob.glob("/content/drive/MyDrive/Amazon-ML-Challenge-2026/**/*", recursive=True):
    if os.path.isfile(f):
        name = os.path.basename(f).lower()

        if any(x in name for x in [
            "feature", "candidate", "train", "model", "catboost"
        ]):
            size_mb = os.path.getsize(f) / (1024**2)
            print(f"{size_mb:.2f} MB | {f}")

================================================================================
CELL 65
================================================================================
!python3 /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
  --matching /content/amazon_ml_challenge/student_resource/output/matching_results.tsv \
  --candidate /content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv \
  --test-dir /content/amazon_ml_challenge/student_resource/dataset/test

================================================================================
CELL 67
================================================================================
# Check what important objects/files are still available

import os

print("=== FILE CHECK ===")

paths = {
    "test_features file": "/content/amazon_ml_challenge/student_resource/test_features.pkl",
    "model folder": "/content/amazon_ml_challenge/student_resource/models",
    "candidate file": "/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv",
    "matching file": "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv",
}

for name, path in paths.items():
    print(f"{name}: {'YES' if os.path.exists(path) else 'NO'}")

print("\n=== MEMORY CHECK ===")

for var in ["test_features", "model", "s1_test", "pair_features",
            "normalize_advanced", "build_s1_key_maps",
            "collect_candidates_from_source"]:
    print(f"{var}: {'YES' if var in globals() else 'NO'}")

================================================================================
CELL 69
================================================================================
# ============================================
# DAY 1 — STRONG MODEL PIPELINE
# STEP 1: Load 10,000 training S1 records
# ============================================

import pandas as pd
import numpy as np
from collections import defaultdict

TRAIN_S1 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source1.tsv"
TRAIN_S2 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source2.tsv"
TRAIN_S3 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source3.tsv"
GROUND_TRUTH = "/content/amazon_ml_challenge/student_resource/dataset/train/train_ground_truth.tsv"

# Load only 10,000 Source 1 records
train_s1_10k = pd.read_csv(
    TRAIN_S1,
    sep="\t",
    usecols=["entity_id", "business_name", "business_address", "country"],
    nrows=10000
)

print("Training S1 shape:", train_s1_10k.shape)
print(train_s1_10k.head())

# Build advanced blocking maps
s1_name_map = defaultdict(list)
s1_address_map = defaultdict(list)

for _, row in train_s1_10k.iterrows():

    sid = row["entity_id"]
    country = normalize_country(row["country"])

    name = normalize_advanced(row["business_name"])
    address = normalize_advanced(row["business_address"])

    if name:
        s1_name_map[(country, name)].append(sid)

    if address:
        s1_address_map[(country, address)].append(sid)

print("\nName keys:", len(s1_name_map))
print("Address keys:", len(s1_address_map))
print("S1 records:", len(train_s1_10k))

================================================================================
CELL 70
================================================================================
# ============================================
# STEP 2: Generate training candidate pairs
# ============================================

from collections import defaultdict

def generate_training_candidates(source_path, source_name):
    candidates = []
    candidate_records = []

    print(f"\nScanning {source_name}...")

    for chunk_no, chunk in enumerate(
        pd.read_csv(
            source_path,
            sep="\t",
            usecols=[
                "entity_id",
                "business_name",
                "business_address",
                "country"
            ],
            chunksize=200_000
        )
    ):

        # Advanced normalization
        chunk["norm_name"] = chunk["business_name"].map(normalize_advanced)
        chunk["norm_address"] = chunk["business_address"].map(normalize_advanced)
        chunk["norm_country"] = chunk["country"].map(normalize_country)

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = row.norm_country
            name = row.norm_name
            address = row.norm_address

            matched_s1 = set()

            # Name blocking
            if name:
                matched_s1.update(
                    s1_name_map.get((country, name), [])
                )

            # Address blocking
            if address:
                matched_s1.update(
                    s1_address_map.get((country, address), [])
                )

            # Store only actual candidate pairs
            for sid in matched_s1:

                candidates.append((sid, eid))

                candidate_records.append({
                    "source1_entity_id": sid,
                    "candidate_entity_id": eid,
                    "business_name": row.business_name,
                    "business_address": row.business_address,
                    "country": row.country,
                    "source": source_name
                })

        if (chunk_no + 1) % 5 == 0:
            print(
                f"{source_name}: processed {(chunk_no + 1) * 200000:,} rows | "
                f"candidates: {len(candidates):,}"
            )

    print(f"{source_name} candidates: {len(candidates):,}")

    return candidates, candidate_records


# Source 2
train_candidates_s2, train_records_s2 = generate_training_candidates(
    TRAIN_S2,
    "S2"
)

# Source 3
train_candidates_s3, train_records_s3 = generate_training_candidates(
    TRAIN_S3,
    "S3"
)

print("\n================================")
print("CANDIDATE GENERATION COMPLETE")
print("================================")

print("S2 candidates:", len(train_candidates_s2))
print("S3 candidates:", len(train_candidates_s3))
print("Total candidates:", len(train_candidates_s2) + len(train_candidates_s3))

================================================================================
CELL 71
================================================================================
# ============================================
# STEP 3: Build candidate dataframe + labels
# ============================================

print("Building candidate dataframe...")

# Combine S2 + S3 candidate records
train_candidate_df = pd.DataFrame(
    train_records_s2 + train_records_s3
)

print("Candidate dataframe shape:", train_candidate_df.shape)

# Load only the ground-truth columns
gt = pd.read_csv(
    GROUND_TRUTH,
    sep="\t",
    usecols=["source1_entity_id", "matched_entity_ids"]
)

print("Ground truth shape:", gt.shape)
print(gt.head())

# Keep only the 10,000 S1 records we are validating
s1_ids = set(train_s1_10k["entity_id"])

gt_10k = gt[gt["source1_entity_id"].isin(s1_ids)].copy()

print("\nGround truth rows for our 10k S1:", len(gt_10k))

# Convert ground truth into a dictionary:
# S1 ID -> set of correct S2/S3 IDs
ground_truth_map = {}

for _, row in gt_10k.iterrows():

    sid = row["source1_entity_id"]
    matches = row["matched_entity_ids"]

    if pd.isna(matches) or str(matches).strip() == "":
        ground_truth_map[sid] = set()
    else:
        ground_truth_map[sid] = set(
            str(matches).split(",")
        )

# Create binary labels
train_candidate_df["label"] = train_candidate_df.apply(
    lambda row: int(
        row["candidate_entity_id"]
        in ground_truth_map.get(row["source1_entity_id"], set())
    ),
    axis=1
)

print("\n================================")
print("LABELING COMPLETE")
print("================================")

print("Total candidate pairs:", len(train_candidate_df))
print("Positive pairs:", int(train_candidate_df["label"].sum()))
print("Negative pairs:", int((train_candidate_df["label"] == 0).sum()))

print("\nPositive percentage:",
      round(train_candidate_df["label"].mean() * 100, 3), "%")

================================================================================
CELL 72
================================================================================
# ============================================
# STEP 4: Build 9 ML features
# ============================================

from difflib import SequenceMatcher

print("Preparing feature dataframe...")

# Rename candidate columns for clarity
train_candidate_df = train_candidate_df.rename(

In [ ]:
import json

NOTEBOOK = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/notebooks/Amazon_ML_Challenge_2026.ipynb"

with open(NOTEBOOK, "r", encoding="utf-8") as f:
    nb = json.load(f)

patterns = [
    "name_freq",
    "addr_freq",
    "s2_name_freq",
    "s3_name_freq",
    "rare_name",
    "rare_addr",
    "frequency",
    "freq_limit",
    "max_freq",
    "candidate_pairs",
    "v3_candidates",
    "v3_candidate",
]

print("Total cells:", len(nb["cells"]))

for i, cell in enumerate(nb["cells"]):

    # Ignore the diagnostic cells we just added
    if i >= 252:
        continue

    source = "".join(cell.get("source", []))

    matches = [
        p for p in patterns
        if p.lower() in source.lower()
    ]

    if matches:
        print("\n" + "=" * 90)
        print("CELL", i)
        print("MATCHES:", matches)
        print("=" * 90)
        print(source[:15000])

Total cells: 255

==========================================================================================
CELL 30
MATCHES: ['candidate_pairs']
==========================================================================================
matching_df = pd.DataFrame(results)
candidate_df = pd.DataFrame(candidate_results)

matching_path = os.path.join(
    OUTPUT,
    "matching_results.tsv"
)

candidate_path = os.path.join(
    OUTPUT,
    "candidate_pairs.tsv"
)

matching_df.to_csv(
    matching_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

candidate_df.to_csv(
    candidate_path,
    sep="\t",
    index=False,
    encoding="utf-8"
)

print("Files created successfully!")
print(matching_path)
print(candidate_path)

==========================================================================================
CELL 54
MATCHES: ['candidate_pairs']
==========================================================================================
import pandas as pd
import os

matching_file = f"{OUTPUT}/matching_results.tsv"
candidate_file = f"{OUTPUT}/candidate_pairs.tsv"

print("MATCHING FILE")
print("Size:", round(os.path.getsize(matching_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(matching_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(matching_file, encoding="utf-8")) - 1)

print("\nCANDIDATE FILE")
print("Size:", round(os.path.getsize(candidate_file)/(1024**3), 2), "GB")
print("Columns:", pd.read_csv(candidate_file, sep="\t", nrows=2).columns.tolist())
print("Rows:", sum(1 for _ in open(candidate_file, encoding="utf-8")) - 1)

==========================================================================================
CELL 55
MATCHES: ['candidate_pairs']
==========================================================================================
import pandas as pd

matching = pd.read_csv(
    f"{OUTPUT}/matching_results.tsv",
    sep="\t"
)

candidate = pd.read_csv(
    f"{OUTPUT}/candidate_pairs.tsv",
    sep="\t"
)

print("Matching rows:", len(matching))
print("Candidate rows:", len(candidate))

print("\nMatching examples:")
print(matching.head(10).to_string(index=False))

print("\nCandidate examples:")
print(candidate.head(10).to_string(index=False))

print("\nEmpty matching rows:",
      matching["matched_entity_ids"].fillna("").eq("").sum())

print("Empty candidate rows:",
      candidate["candidate_entity_ids"].fillna("").eq("").sum())

==========================================================================================
CELL 65
MATCHES: ['candidate_pairs']
==========================================================================================
!python3 /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
  --matching /content/amazon_ml_challenge/student_resource/output/matching_results.tsv \
  --candidate /content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv \
  --test-dir /content/amazon_ml_challenge/student_resource/dataset/test

==========================================================================================
CELL 67
MATCHES: ['candidate_pairs']
==========================================================================================
# Check what important objects/files are still available

import os

print("=== FILE CHECK ===")

paths = {
    "test_features file": "/content/amazon_ml_challenge/student_resource/test_features.pkl",
    "model folder": "/content/amazon_ml_challenge/student_resource/models",
    "candidate file": "/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv",
    "matching file": "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv",
}

for name, path in paths.items():
    print(f"{name}: {'YES' if os.path.exists(path) else 'NO'}")

print("\n=== MEMORY CHECK ===")

for var in ["test_features", "model", "s1_test", "pair_features",
            "normalize_advanced", "build_s1_key_maps",
            "collect_candidates_from_source"]:
    print(f"{var}: {'YES' if var in globals() else 'NO'}")

==========================================================================================
CELL 77
MATCHES: ['frequency']
==========================================================================================
# ============================================
# STEP 8: Build token-frequency statistics
# ============================================

from collections import Counter
import re

name_token_freq = Counter()
address_token_freq = Counter()

def useful_tokens(text):
    text = normalize_advanced(text)

    tokens = set(
        t for t in text.split()
        if len(t) >= 4 and not t.isdigit()
    )

    return tokens


def scan_token_frequency(path, source_name):

    print(f"\nScanning {source_name} for token frequencies...")

    processed = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "business_name",
            "business_address"
        ],
        chunksize=200_000
    ):

        for name in chunk["business_name"]:
            for token in useful_tokens(name):
                name_token_freq[token] += 1

        for address in chunk["business_address"]:
            for token in useful_tokens(address):
                address_token_freq[token] += 1

        processed += len(chunk)

        if processed % 1_000_000 == 0:
            print(
                f"{source_name}: "
                f"{processed:,} rows processed"
            )


scan_token_frequency(TRAIN_S2, "S2")
scan_token_frequency(TRAIN_S3, "S3")


print("\n================================")
print("TOKEN FREQUENCY COMPLETE")
print("================================")

print("Unique name tokens:", len(name_token_freq))
print("Unique address tokens:", len(address_token_freq))

print("\nMost common NAME tokens:")
print(name_token_freq.most_common(20))

print("\nMost common ADDRESS tokens:")
print(address_token_freq.most_common(20))

==========================================================================================
CELL 80
MATCHES: ['frequency']
==========================================================================================
# ============================================
# STEP 11: Build rare-token indexes
# ============================================

from collections import defaultdict

RARE_THRESHOLD = 250

name_token_index_s2 = defaultdict(set)
address_token_index_s2 = defaultdict(set)

name_token_index_s3 = defaultdict(set)
address_token_index_s3 = defaultdict(set)


def add_tokens_to_index(
    text,
    entity_id,
    index,
    frequency_counter,
    threshold
):
    tokens = get_token_set(text)

    for token in tokens:

        if frequency_counter.get(token, 10**9) <= threshold:
            index[token].add(entity_id)


def build_rare_indexes(
    path,
    source_name,
    name_index,
    address_index
):

    print(f"\nBuilding rare-token indexes for {source_name}...")

    processed = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address"
        ],
        chunksize=200_000
    ):

        for row in chunk.itertuples(index=False):

            add_tokens_to_index(
                row.business_name,
                row.entity_id,
                name_index,
                name_token_freq,
                RARE_THRESHOLD
            )

            add_tokens_to_index(
                row.business_address,
                row.entity_id,
                address_index,
                address_token_freq,
                RARE_THRESHOLD
            )

        processed += len(chunk)

        if processed % 1_000_000 == 0:
            print(
                f"{source_name}: "
                f"{processed:,} rows"
            )

    print(
        f"{source_name} indexes complete."
    )


build_rare_indexes(
    TRAIN_S2,
    "S2",
    name_token_index_s2,
    address_token_index_s2
)

build_rare_indexes(
    TRAIN_S3,
    "S3",
    name_token_index_s3,
    address_token_index_s3
)


print("\n================================")
print("RARE TOKEN INDEXES COMPLETE")
print("================================")

print(
    "S2 name tokens:",
    len(name_token_index_s2)
)

print(
    "S2 address tokens:",
    len(address_token_index_s2)
)

print(
    "S3 name tokens:",
    len(name_token_index_s3)
)

print(
    "S3 address tokens:",
    len(address_token_index_s3)
)

==========================================================================================
CELL 86
MATCHES: ['frequency']
==========================================================================================
thresholds = [10, 25, 50, 100, 250, 500, 1000]

print("================================")
print("ADDRESS NUMBER FREQUENCY ANALYSIS")
print("================================")

for threshold in thresholds:
    recovered = 0

    for _, row in v2_miss_diagnostic.iterrows():
        sid = row["source1_entity_id"]
        eid = row["matched_entity_id"]

        s1 = s1_lookup[sid]
        target = missed_records[eid]

        nums1 = extract_numbers(
            normalize_advanced(s1["business_address"])
        )
        nums2 = extract_numbers(
            normalize_advanced(target["business_address"])
        )

        shared = nums1 & nums2

        if any(number_freq.get(n, 10**9) <= threshold for n in shared):
            recovered += 1

    print(
        f"threshold <= {threshold:4d}: "
        f"{recovered:4d} / 2298 "
        f"({recovered / 2298 * 100:.2f}%)"
    )

==========================================================================================
CELL 97
MATCHES: ['candidate_pairs']
==========================================================================================
result = pd.DataFrame({
    "source1_entity_id": s1["entity_id"],
    "matched_entity_ids": [
        ",".join(matches.get(sid, []))
        for sid in s1["entity_id"]
    ]
})

candidate = pd.DataFrame({
    "source1_entity_id": s1["entity_id"],
    "candidate_entity_ids": [
        ",".join(matches.get(sid, []))
        for sid in s1["entity_id"]
    ]
})

matching_path = f"{OUT}/matching_results_v2.tsv"
candidate_path = f"{OUT}/candidate_pairs_v2.tsv"

result.to_csv(matching_path, sep="\t", index=False)
candidate.to_csv(candidate_path, sep="\t", index=False)

print("================================")
print("FILES CREATED")
print("================================")
print("Matching:", matching_path)
print("Candidate:", candidate_path)
print("Rows:", len(result))
print("Non-empty:", (result["matched_entity_ids"] != "").sum())
print("Empty:", (result["matched_entity_ids"] == "").sum())
print(
    "Total matched links:",
    sum(len(x.split(",")) for x in result["matched_entity_ids"] if x)
)

==========================================================================================
CELL 98
MATCHES: ['candidate_pairs']
==========================================================================================
!python3 /content/amazon_ml_challenge/student_resource/utils/validate_submission.py \
  --matching /content/amazon_ml_challenge/student_resource/output/matching_results_v2.tsv \
  --candidate /content/amazon_ml_challenge/student_resource/output/candidate_pairs_v2.tsv \
  --test-dir /content/amazon_ml_challenge/student_resource/dataset/test

==========================================================================================
CELL 104
MATCHES: ['rare_name', 'rare_addr']
==========================================================================================
# ============================================
# STEP 18B-2
# Rebuild V2 candidate maps
# ============================================

# Maps from validation S1
name_map_val = defaultdict(list)
address_map_val = defaultdict(list)

for row in s1_val.itertuples(index=False):

    sid = row.entity_id
    country = normalize_country(row.country)

    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    if name:
        name_map_val[(country, name)].append(sid)

    if address:
        address_map_val[(country, address)].append(sid)

# Build rare-token indexes from FULL Source 2 + Source 3.
# We need token frequencies first.

print("Building full training token frequencies...")

name_token_freq = Counter()
address_token_freq = Counter()

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"\nScanning {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_name", "business_address"],
        chunksize=200000
    ):

        for name in chunk["business_name"].dropna():
            tokens = get_token_set(
                normalize_advanced(name)
            )
            name_token_freq.update(tokens)

        for address in chunk["business_address"].dropna():
            tokens = get_token_set(
                normalize_advanced(address)
            )
            address_token_freq.update(tokens)

        rows += len(chunk)

        if rows % 1000000 == 0:
            print(f"  processed {rows:,}")

print("\n================================")
print("TOKEN FREQUENCIES READY")
print("================================")
print("Name tokens:", len(name_token_freq))
print("Address tokens:", len(address_token_freq))

print("\nMost common address tokens:")
for token, count in address_token_freq.most_common(20):
    print(f"{token:20s} {count:,}")

# --------------------------------------------
# Build rare-token maps
# Same V2 cutoff: <=250
# --------------------------------------------

RARE_LIMIT = 250

rare_name_map = defaultdict(list)
rare_address_map = defaultdict(list)

print("\nBuilding rare-token indexes...")

for path, source_name in [
    (TRAIN_S2, "Source 2"),
    (TRAIN_S3, "Source 3")
]:

    print(f"Indexing {source_name}...")

    rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = normalize_country(row.country)

            name_tokens = get_token_set(
                normalize_advanced(row.business_name)
            )

            address_tokens = get_token_set(
                normalize_advanced(row.business_address)
            )

            for token in name_tokens:
                if name_token_freq.get(token, 10**9) <= RARE_LIMIT:
                    rare_name_map[
                        (country, token)
                    ].append(eid)

            for token in address_tokens:
                if address_token_freq.get(token, 10**9) <= RARE_LIMIT:
                    rare_address_map[
                        (country, token)
                    ].append(eid)

        rows += len(chunk)

        if rows % 1000000 == 0:
            print(f"  indexed {rows:,}")

print("\n================================")
print("V2 BLOCKING INDEXES READY")
print("================================")
print("Rare name keys:", len(rare_name_map))
print("Rare address keys:", len(rare_address_map))

==========================================================================================
CELL 105
MATCHES: ['rare_name', 'rare_addr', 'candidate_pairs']
==========================================================================================
# ============================================
# STEP 18B-3
# Rebuild V2 candidate pairs
# ============================================

candidate_pairs_v2 = []

def scan_candidates(path, source_name):

    print(f"\nScanning {source_name}...")

    rows = 0
    added = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id
            country = normalize_country(row.country)

            name = normalize_advanced(row.business_name)
            address = normalize_advanced(row.business_address)

            found_s1 = set()

            # -----------------------------
            # V2 BLOCK 1: exact name
            # -----------------------------
            if name:
                found_s1.update(
                    name_map_val.get(
                        (country, name),
                        []
                    )
                )

            # -----------------------------
            # V2 BLOCK 2: exact address
            # -----------------------------
            if address:
                found_s1.update(
                    address_map_val.get(
                        (country, address),
                        []
                    )
                )

            # -----------------------------
            # V2 BLOCK 3: rare name token
            # -----------------------------
            name_tokens = get_token_set(name)

            for token in name_tokens:

                if name_token_freq.get(
                    token, 10**9
                ) <= RARE_LIMIT:

                    found_s1.update(
                        rare_name_map.get(
                            (country, token),
                            []
                        )
                    )

            # -----------------------------
            # V2 BLOCK 4: rare address token
            # -----------------------------
            address_tokens = get_token_set(address)

            for token in address_tokens:

                if address_token_freq.get(
                    token, 10**9
                ) <= RARE_LIMIT:

                    found_s1.update(
                        rare_address_map.get(
                            (country, token),
                            []
                        )
                    )

            # Store only actual candidate pairs
            for sid in found_s1:
                candidate_pairs_v2.append(
                    (sid, eid)
                )

            added += len(found_s1)
            rows += 1

        print(
            f"{source_name}: "
            f"{rows:,} rows | "
            f"{added:,} candidate links"
        )

    print(
        f"{source_name} COMPLETE | "
        f"candidate links: {added:,}"
    )


scan_candidates(TRAIN_S2, "Source 2")
scan_candidates(TRAIN_S3, "Source 3")

# --------------------------------------------
# Convert to DataFrame and deduplicate
# --------------------------------------------

v2_candidates = pd.DataFrame(
    candidate_pairs_v2,
    columns=[
        "source1_entity_id",
        "matched_entity_id"
    ]
).drop_duplicates()

print("\n================================")
print("V2 CANDIDATE SET")
print("================================")
print("Candidate pairs:", len(v2_candidates))
print(
    "S1 entities with candidates:",
    v2_candidates["source1_entity_id"].nunique()
)

# --------------------------------------------
# Calculate candidate recall
# --------------------------------------------

candidate_lookup = defaultdict(set)

for row in v2_candidates.itertuples(index=False):
    candidate_lookup[
        row.source1_entity_id
    ].add(row.matched_entity_id)

total_true = 0
found_true = 0
missed_true = 0
zero_candidate_entities = 0

for sid in val_ids:

    true_ids = gt_lookup.get(sid, set())

    candidates = candidate_lookup.get(
        sid,
        set()
    )

    if len(candidates) == 0:
        zero_candidate_entities += 1

    total_true += len(true_ids)

    found = true_ids & candidates

    found_true += len(found)
    missed_true += len(true_ids - candidates)

print("\n================================")
print("V2 RECALL VERIFICATION")
print("================================")
print("Validation S1 entities:", len(val_ids))

In [ ]:
# ============================================================
# EXACT V5 PIPELINE — 100 S1 / S2 ONLY
# Candidate generation + V5 prediction
# ============================================================

import gc
import time
import pickle
import psutil
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import ratio

BASE = "/content/amazon_ml_challenge/student_resource"
INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

def ram_gb():
    return psutil.virtual_memory().available / (1024**3)

print("=" * 70)
print("V5 S2 SMOKE TEST")
print("=" * 70)
print("RAM:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Load 100 S1
# ------------------------------------------------------------

s1_100 = pd.read_csv(
    f"{BASE}/dataset/test/test_source1.tsv",
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=100
)

# ------------------------------------------------------------
# Load S2
# ------------------------------------------------------------

print("\nLoading S2...")

s2 = pd.read_csv(
    f"{BASE}/dataset/test/test_source2.tsv",
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False
)

print("S2:", s2.shape)
print("RAM after S2:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Normalize
# ------------------------------------------------------------

def norm(x):
    if x is None:
        return ""

    x = str(x).lower().strip()

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    import unicodedata
    import re

    x = unicodedata.normalize("NFKC", x)
    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def toks(x):
    return set(x.split()) if x else set()


def nums(x):
    import re
    return set(re.findall(r"\d+", x))


# ------------------------------------------------------------
# Source arrays
# ------------------------------------------------------------

print("\nPreparing S2 arrays...")

s2_names = s2["business_name"].map(norm).to_numpy()
s2_addrs = s2["business_address"].map(norm).to_numpy()
s2_countries = (
    s2["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .to_numpy()
)

s2_ids = s2["entity_id"].to_numpy()

print("Arrays ready.")
print("RAM:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Load indexes
# ------------------------------------------------------------

print("\nLoading S2 indexes...")

with open(f"{INDEX_DIR}/s2_name_index.pkl", "rb") as f:
    s2_name_index = pickle.load(f)

with open(f"{INDEX_DIR}/s2_addr_index.pkl", "rb") as f:
    s2_addr_index = pickle.load(f)

with open(f"{INDEX_DIR}/s2_name_freq.pkl", "rb") as f:
    s2_name_freq = pickle.load(f)

with open(f"{INDEX_DIR}/s2_addr_freq.pkl", "rb") as f:
    s2_addr_freq = pickle.load(f)

print("Indexes ready.")
print("RAM:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Exact V5 candidate generator
# ------------------------------------------------------------

def generate_v5_candidates(
    name1,
    addr1,
    country1
):

    t_name = toks(name1)
    t_addr = toks(addr1)

    name_hits = {}
    addr_hits = {}

    # NAME TOKEN BLOCK <=500
    for token in t_name:

        if s2_name_freq.get(token, 10**9) <= 500:

            for idx in s2_name_index.get(token, ()):

                if s2_countries[idx] == country1:

                    name_hits[idx] = (
                        name_hits.get(idx, 0) + 1
                    )

    # ADDRESS TOKEN BLOCK <=500
    for token in t_addr:

        if s2_addr_freq.get(token, 10**9) <= 500:

            for idx in s2_addr_index.get(token, ()):

                if s2_countries[idx] == country1:

                    addr_hits[idx] = (
                        addr_hits.get(idx, 0) + 1
                    )

    candidate_ids = (
        {
            idx for idx, count in name_hits.items()
            if count >= 2
        }
        |
        {
            idx for idx, count in addr_hits.items()
            if count >= 2
        }
    )

    # --------------------------------------------------------
    # FINAL V5 CANDIDATE FILTER
    # --------------------------------------------------------

    selected = []

    for idx in candidate_ids:

        n2 = s2_names[idx]
        a2 = s2_addrs[idx]

        # Exact
        if (
            (name1 and name1 == n2)
            or
            (addr1 and addr1 == a2)
        ):
            selected.append(idx)
            continue

        shared_name = len(
            t_name & toks(n2)
        )

        shared_addr = len(
            t_addr & toks(a2)
        )

        name_sim = (
            ratio(name1, n2) / 100
            if name1 and n2 else 0.0
        )

        addr_sim = (
            ratio(addr1, a2) / 100
            if addr1 and a2 else 0.0
        )

        keep = (
            (
                shared_name >= 2
                and name_sim >= 0.60
            )
            or
            (
                shared_addr >= 3
            )
            or
            (
                shared_addr >= 2
                and addr_sim >= 0.30
            )
        )

        if keep:
            selected.append(idx)

    return selected


# ------------------------------------------------------------
# V5 model
# ------------------------------------------------------------

from catboost import CatBoostClassifier

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_model.cbm"
)

v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

print("\nV5 model loaded:", v5_model.is_fitted())
print("Trees:", v5_model.tree_count_)

# ------------------------------------------------------------
# V5 features
# ------------------------------------------------------------

V5_FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]


def make_features(
    name1,
    addr1,
    country1,
    candidate_indices
):

    t1n = toks(name1)
    t1a = toks(addr1)
    num1 = nums(addr1)

    rows = []

    for idx in candidate_indices:

        n2 = s2_names[idx]
        a2 = s2_addrs[idx]
        c2 = s2_countries[idx]

        t2n = toks(n2)
        t2a = toks(a2)

        shared_n = t1n & t2n
        shared_a = t1a & t2a

        union_n = t1n | t2n
        union_a = t1a | t2a

        ns = (
            ratio(name1, n2) / 100
            if name1 and n2 else 0.0
        )

        ass = (
            ratio(addr1, a2) / 100
            if addr1 and a2 else 0.0
        )

        nt = (
            len(shared_n) /
            max(1, min(len(t1n), len(t2n)))
        )

        at = (
            len(shared_a) /
            max(1, min(len(t1a), len(t2a)))
        )

        nj = (
            len(shared_n) / len(union_n)
            if union_n else 0.0
        )

        aj = (
            len(shared_a) / len(union_a)
            if union_a else 0.0
        )

        rows.append([
            int(bool(name1) and name1 == n2),
            int(bool(addr1) and addr1 == a2),
            int(country1 == c2),

            ns,
            ass,

            nt,
            at,

            nj,
            aj,

            len(shared_n),
            len(shared_a),

            len(num1 & nums(a2)),

            abs(len(name1) - len(n2)),
            abs(len(addr1) - len(a2)),

            min(len(name1), len(n2)) /
            max(1, max(len(name1), len(n2))),

            min(len(addr1), len(a2)) /
            max(1, max(len(addr1), len(a2))),

            abs(ns - ass),
            max(ns, ass),
            ns * ass,
            abs(nt - at)
        ])

    return np.asarray(
        rows,
        dtype=np.float32
    )


# ------------------------------------------------------------
# RUN
# ------------------------------------------------------------

start = time.time()

total_candidates = 0
total_predictions = 0
candidate_counts = []

for i, row in enumerate(
    s1_100.itertuples(index=False),
    1
):

    name1 = norm(row.business_name)
    addr1 = norm(row.business_address)
    country1 = (
        str(row.country)
        .lower()
        .strip()
    )

    candidates = generate_v5_candidates(
        name1,
        addr1,
        country1
    )

    candidate_counts.append(len(candidates))
    total_candidates += len(candidates)

    if candidates:

        X = make_features(
            name1,
            addr1,
            country1,
            candidates
        )

        probs = v5_model.predict_proba(X)[:, 1]

        predictions = int(
            (probs >= 0.60).sum()
        )

        total_predictions += predictions

    if i % 20 == 0:

        print(
            f"{i}/100 | "
            f"avg candidates/S1="
            f"{total_candidates/i:.2f} | "
            f"matches={total_predictions} | "
            f"RAM={ram_gb():.2f} GB"
        )

elapsed = time.time() - start

print("\n" + "=" * 70)
print("V5 S2 SMOKE TEST COMPLETE")
print("=" * 70)

print("S1 processed:", 100)
print("Total candidates:", f"{total_candidates:,}")
print(
    "Candidates/S1:",
    round(total_candidates / 100, 2)
)
print(
    "Median candidates/S1:",
    round(float(np.median(candidate_counts)), 2)
)
print("Predicted matches:", total_predictions)
print(
    "Predicted matches/S1:",
    round(total_predictions / 100, 3)
)
print("Time:", round(elapsed, 2), "sec")
print("RAM available:", round(ram_gb(), 2), "GB")

======================================================================
V5 S2 SMOKE TEST
======================================================================
RAM: 4.8 GB

Loading S2...
S2: (4887273, 4)
RAM after S2: 4.62 GB

Preparing S2 arrays...
Arrays ready.
RAM: 3.77 GB

Loading S2 indexes...
Indexes ready.
RAM: 1.41 GB

V5 model loaded: True
Trees: 670
20/100 | avg candidates/S1=6.80 | matches=19 | RAM=1.36 GB
40/100 | avg candidates/S1=3.75 | matches=30 | RAM=1.36 GB
60/100 | avg candidates/S1=2.88 | matches=38 | RAM=1.36 GB
80/100 | avg candidates/S1=2.35 | matches=47 | RAM=1.36 GB
100/100 | avg candidates/S1=2.09 | matches=56 | RAM=1.36 GB

======================================================================
V5 S2 SMOKE TEST COMPLETE
======================================================================
S1 processed: 100
Total candidates: 209
Candidates/S1: 2.09
Median candidates/S1: 0.0
Predicted matches: 56
Predicted matches/S1: 0.56
Time: 0.12 sec
RAM available: 1.36 GB

In [ ]:
# Free S2 memory before loading S3

import gc

for name in [
    "s2",
    "s2_names",
    "s2_addrs",
    "s2_countries",
    "s2_ids",
    "s2_name_index",
    "s2_addr_index",
    "s2_name_freq",
    "s2_addr_freq",
]:
    if name in globals():
        del globals()[name]

gc.collect()

import psutil
print(
    "Available RAM:",
    round(psutil.virtual_memory().available / (1024**3), 2),
    "GB"
)

Available RAM: 6.87 GB

In [ ]:
# ============================================================
# EXACT V5 PIPELINE — 100 S1 / S3 ONLY
# ============================================================

import gc
import time
import pickle
import psutil
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import ratio

BASE = "/content/amazon_ml_challenge/student_resource"
INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

def ram_gb():
    return psutil.virtual_memory().available / (1024**3)

print("=" * 70)
print("V5 S3 SMOKE TEST")
print("=" * 70)
print("RAM:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Load 100 S1
# ------------------------------------------------------------

s1_100 = pd.read_csv(
    f"{BASE}/dataset/test/test_source1.tsv",
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=5000
)

# ------------------------------------------------------------
# Normalization
# ------------------------------------------------------------

def norm(x):
    if x is None:
        return ""

    x = str(x).lower().strip()

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    import unicodedata
    import re

    x = unicodedata.normalize("NFKC", x)
    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def toks(x):
    return set(x.split()) if x else set()


def nums(x):
    import re
    return set(re.findall(r"\d+", x))


# ------------------------------------------------------------
# Load S3
# ------------------------------------------------------------

print("\nLoading S3...")

s3 = pd.read_csv(
    f"{BASE}/dataset/test/test_source3.tsv",
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False
)

print("S3:", s3.shape)
print("RAM after S3:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Prepare arrays
# ------------------------------------------------------------

print("\nPreparing S3 arrays...")

s3_names = s3["business_name"].map(norm).to_numpy()
s3_addrs = s3["business_address"].map(norm).to_numpy()
s3_countries = (
    s3["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .to_numpy()
)
s3_ids = s3["entity_id"].to_numpy()

print("Arrays ready.")
print("RAM:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Load S3 indexes
# ------------------------------------------------------------

print("\nLoading S3 indexes...")

with open(f"{INDEX_DIR}/s3_name_index.pkl", "rb") as f:
    s3_name_index = pickle.load(f)

with open(f"{INDEX_DIR}/s3_addr_index.pkl", "rb") as f:
    s3_addr_index = pickle.load(f)

with open(f"{INDEX_DIR}/s3_name_freq.pkl", "rb") as f:
    s3_name_freq = pickle.load(f)

with open(f"{INDEX_DIR}/s3_addr_freq.pkl", "rb") as f:
    s3_addr_freq = pickle.load(f)

print("Indexes ready.")
print("RAM:", round(ram_gb(), 2), "GB")

# ------------------------------------------------------------
# Exact V5 candidate generation
# ------------------------------------------------------------

def generate_v5_candidates_s3(name1, addr1, country1):

    t_name = toks(name1)
    t_addr = toks(addr1)

    name_hits = {}
    addr_hits = {}

    # Name token block
    for token in t_name:

        if s3_name_freq.get(token, 10**9) <= 500:

            for idx in s3_name_index.get(token, ()):

                if s3_countries[idx] == country1:
                    name_hits[idx] = (
                        name_hits.get(idx, 0) + 1
                    )

    # Address token block
    for token in t_addr:

        if s3_addr_freq.get(token, 10**9) <= 500:

            for idx in s3_addr_index.get(token, ()):

                if s3_countries[idx] == country1:
                    addr_hits[idx] = (
                        addr_hits.get(idx, 0) + 1
                    )

    candidate_ids = (
        {
            idx for idx, count in name_hits.items()
            if count >= 2
        }
        |
        {
            idx for idx, count in addr_hits.items()
            if count >= 2
        }
    )

    # Final V5 candidate filter
    selected = []

    for idx in candidate_ids:

        n2 = s3_names[idx]
        a2 = s3_addrs[idx]

        if (
            (name1 and name1 == n2)
            or
            (addr1 and addr1 == a2)
        ):
            selected.append(idx)
            continue

        shared_name = len(t_name & toks(n2))
        shared_addr = len(t_addr & toks(a2))

        name_sim = (
            ratio(name1, n2) / 100
            if name1 and n2 else 0.0
        )

        addr_sim = (
            ratio(addr1, a2) / 100
            if addr1 and a2 else 0.0
        )

        keep = (
            (
                shared_name >= 2
                and name_sim >= 0.60
            )
            or
            shared_addr >= 3
            or
            (
                shared_addr >= 2
                and addr_sim >= 0.30
            )
        )

        if keep:
            selected.append(idx)

    return selected


# ------------------------------------------------------------
# V5 model
# ------------------------------------------------------------

from catboost import CatBoostClassifier

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_model.cbm"
)

v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

# ------------------------------------------------------------
# Feature builder
# ------------------------------------------------------------

def make_features_s3(
    name1,
    addr1,
    country1,
    candidate_indices
):

    t1n = toks(name1)
    t1a = toks(addr1)
    num1 = nums(addr1)

    rows = []

    for idx in candidate_indices:

        n2 = s3_names[idx]
        a2 = s3_addrs[idx]
        c2 = s3_countries[idx]

        t2n = toks(n2)
        t2a = toks(a2)

        shared_n = t1n & t2n
        shared_a = t1a & t2a

        union_n = t1n | t2n
        union_a = t1a | t2a

        ns = ratio(name1, n2) / 100 if name1 and n2 else 0.0
        ass = ratio(addr1, a2) / 100 if addr1 and a2 else 0.0

        nt = len(shared_n) / max(
            1, min(len(t1n), len(t2n))
        )

        at = len(shared_a) / max(
            1, min(len(t1a), len(t2a))
        )

        nj = (
            len(shared_n) / len(union_n)
            if union_n else 0.0
        )

        aj = (
            len(shared_a) / len(union_a)
            if union_a else 0.0
        )

        rows.append([
            int(bool(name1) and name1 == n2),
            int(bool(addr1) and addr1 == a2),
            int(country1 == c2),
            ns,
            ass,
            nt,
            at,
            nj,
            aj,
            len(shared_n),
            len(shared_a),
            len(num1 & nums(a2)),
            abs(len(name1) - len(n2)),
            abs(len(addr1) - len(a2)),
            min(len(name1), len(n2)) /
                max(1, max(len(name1), len(n2))),
            min(len(addr1), len(a2)) /
                max(1, max(len(addr1), len(a2))),
            abs(ns - ass),
            max(ns, ass),
            ns * ass,
            abs(nt - at)
        ])

    return np.asarray(rows, dtype=np.float32)


# ------------------------------------------------------------
# Run
# ------------------------------------------------------------

start = time.time()

total_candidates = 0
total_predictions = 0
candidate_counts = []

for i, row in enumerate(s1_100.itertuples(index=False), 1):

    name1 = norm(row.business_name)
    addr1 = norm(row.business_address)
    country1 = str(row.country).lower().strip()

    candidates = generate_v5_candidates_s3(
        name1,
        addr1,
        country1
    )

    candidate_counts.append(len(candidates))
    total_candidates += len(candidates)

    if candidates:

        X = make_features_s3(
            name1,
            addr1,
            country1,
            candidates
        )

        probs = v5_model.predict_proba(X)[:, 1]

        total_predictions += int(
            (probs >= 0.60).sum()
        )

    if i % 500 == 0:

        print(
            f"{i}/100 | "
            f"avg candidates/S1="
            f"{total_candidates/i:.2f} | "
            f"matches={total_predictions} | "
            f"RAM={ram_gb():.2f} GB"
        )

elapsed = time.time() - start

print("\n" + "=" * 70)
print("V5 S3 SMOKE TEST COMPLETE")
print("=" * 70)

print("S1 processed:", 100)
print("Total candidates:", f"{total_candidates:,}")
print(
    "Candidates/S1:",
    round(total_candidates / 100, 2)
)
print(
    "Median candidates/S1:",
    round(float(np.median(candidate_counts)), 2)
)
print("Predicted matches:", total_predictions)
print(
    "Predicted matches/S1:",
    round(total_predictions / 100, 3)
)
print("Time:", round(elapsed, 2), "sec")
print("RAM available:", round(ram_gb(), 2), "GB")

======================================================================
V5 S3 SMOKE TEST
======================================================================
RAM: 2.49 GB

Loading S3...
S3: (5082316, 4)
RAM after S3: 1.05 GB

Preparing S3 arrays...
Arrays ready.
RAM: 1.91 GB

Loading S3 indexes...
Indexes ready.
RAM: 2.18 GB
500/100 | avg candidates/S1=3.15 | matches=307 | RAM=2.18 GB
1000/100 | avg candidates/S1=2.85 | matches=619 | RAM=2.18 GB
1500/100 | avg candidates/S1=2.84 | matches=909 | RAM=2.18 GB
2000/100 | avg candidates/S1=2.84 | matches=1238 | RAM=2.18 GB
2500/100 | avg candidates/S1=2.75 | matches=1592 | RAM=2.18 GB
3000/100 | avg candidates/S1=2.67 | matches=1909 | RAM=2.21 GB
3500/100 | avg candidates/S1=2.71 | matches=2275 | RAM=2.20 GB
4000/100 | avg candidates/S1=2.75 | matches=2583 | RAM=2.20 GB
4500/100 | avg candidates/S1=2.72 | matches=2861 | RAM=2.20 GB
5000/100 | avg candidates/S1=2.76 | matches=3152 | RAM=2.20 GB

======================================================================
V5 S3 SMOKE TEST COMPLETE
======================================================================
S1 processed: 100
Total candidates: 13,820
Candidates/S1: 138.2
Median candidates/S1: 0.0
Predicted matches: 3152
Predicted matches/S1: 31.52
Time: 4.82 sec
RAM available: 2.2 GB

In [ ]:
import gc

for name in [
    "s3",
    "s3_names",
    "s3_addrs",
    "s3_countries",
    "s3_ids",
    "s3_name_index",
    "s3_addr_index",
    "s3_name_freq",
    "s3_addr_freq",
    "s1_100"
]:
    if name in globals():
        del globals()[name]

gc.collect()

import psutil
print(
    "Available RAM:",
    round(psutil.virtual_memory().available / (1024**3), 2),
    "GB"
)

Available RAM: 6.44 GB

In [ ]:
# ============================================================
# EXACT V5 PIPELINE — 5,000 S1 / S2 ONLY
# Candidate generation + V5 prediction
# NO submission files
# ============================================================

import gc
import time
import pickle
import psutil
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import ratio
from catboost import CatBoostClassifier
import unicodedata
import re

# ============================================================
# PATHS
# ============================================================

BASE = "/content/amazon_ml_challenge/student_resource"

INDEX_DIR = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/V5_full_indexes"
)

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_model.cbm"
)

N_S1 = 5000
THRESHOLD = 0.60


# ============================================================
# MEMORY
# ============================================================

def ram_gb():
    return psutil.virtual_memory().available / (1024**3)


print("=" * 75)
print("V5 S2 — 5,000 S1 SMOKE TEST")
print("=" * 75)
print(f"Starting available RAM: {ram_gb():.2f} GB")


# ============================================================
# LOAD TEST S1
# ============================================================

print("\nLoading S1...")

s1 = pd.read_csv(
    f"{BASE}/dataset/test/test_source1.tsv",
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=N_S1
)

print("S1:", s1.shape)


# ============================================================
# NORMALIZATION
# ============================================================

def norm(x):

    if x is None:
        return ""

    x = str(x).lower().strip()

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = unicodedata.normalize("NFKC", x)

    x = re.sub(
        r"[^\w\s]",
        " ",
        x
    )

    x = re.sub(
        r"\s+",
        " ",
        x
    )

    return x.strip()


def toks(x):
    return set(x.split()) if x else set()


def nums(x):
    return set(
        re.findall(
            r"\d+",
            x
        )
    )


# ============================================================
# LOAD S2
# ============================================================

print("\nLoading S2...")

s2 = pd.read_csv(
    f"{BASE}/dataset/test/test_source2.tsv",
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False
)

print("S2:", s2.shape)
print(f"RAM after S2: {ram_gb():.2f} GB")


# ============================================================
# PREPARE S2 ARRAYS
# ============================================================

print("\nPreparing S2 arrays...")

s2_names = (
    s2["business_name"]
    .map(norm)
    .to_numpy()
)

s2_addrs = (
    s2["business_address"]
    .map(norm)
    .to_numpy()
)

s2_countries = (
    s2["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .to_numpy()
)

s2_ids = s2["entity_id"].to_numpy()

print("Arrays ready.")
print(f"RAM: {ram_gb():.2f} GB")


# ============================================================
# LOAD S2 INDEXES
# ============================================================

print("\nLoading S2 indexes...")

with open(
    f"{INDEX_DIR}/s2_name_index.pkl",
    "rb"
) as f:
    s2_name_index = pickle.load(f)

with open(
    f"{INDEX_DIR}/s2_addr_index.pkl",
    "rb"
) as f:
    s2_addr_index = pickle.load(f)

with open(
    f"{INDEX_DIR}/s2_name_freq.pkl",
    "rb"
) as f:
    s2_name_freq = pickle.load(f)

with open(
    f"{INDEX_DIR}/s2_addr_freq.pkl",
    "rb"
) as f:
    s2_addr_freq = pickle.load(f)

print("S2 indexes loaded.")
print(f"RAM: {ram_gb():.2f} GB")


# ============================================================
# V5 CANDIDATE GENERATION
# ============================================================

def generate_v5_candidates_s2(
    name1,
    addr1,
    country1
):

    t_name = toks(name1)
    t_addr = toks(addr1)

    name_hits = {}
    addr_hits = {}

    # --------------------------------------------------------
    # NAME BLOCK
    # Rare token frequency <= 500
    # --------------------------------------------------------

    for token in t_name:

        if s2_name_freq.get(
            token,
            10**9
        ) <= 500:

            for idx in s2_name_index.get(
                token,
                ()
            ):

                if s2_countries[idx] == country1:

                    name_hits[idx] = (
                        name_hits.get(
                            idx,
                            0
                        ) + 1
                    )

    # --------------------------------------------------------
    # ADDRESS BLOCK
    # Rare token frequency <= 500
    # --------------------------------------------------------

    for token in t_addr:

        if s2_addr_freq.get(
            token,
            10**9
        ) <= 500:

            for idx in s2_addr_index.get(
                token,
                ()
            ):

                if s2_countries[idx] == country1:

                    addr_hits[idx] = (
                        addr_hits.get(
                            idx,
                            0
                        ) + 1
                    )

    # --------------------------------------------------------
    # REQUIRE >=2 SHARED TOKENS
    # --------------------------------------------------------

    candidate_ids = (
        {
            idx
            for idx, count in name_hits.items()
            if count >= 2
        }
        |
        {
            idx
            for idx, count in addr_hits.items()
            if count >= 2
        }
    )

    # --------------------------------------------------------
    # FINAL V5 CANDIDATE FILTER
    # --------------------------------------------------------

    selected = []

    for idx in candidate_ids:

        n2 = s2_names[idx]
        a2 = s2_addrs[idx]

        # Exact name OR exact address
        if (
            (name1 and name1 == n2)
            or
            (addr1 and addr1 == a2)
        ):
            selected.append(idx)
            continue

        t2n = toks(n2)
        t2a = toks(a2)

        shared_name = len(
            t_name & t2n
        )

        shared_addr = len(
            t_addr & t2a
        )

        name_sim = (
            ratio(name1, n2) / 100
            if name1 and n2
            else 0.0
        )

        addr_sim = (
            ratio(addr1, a2) / 100
            if addr1 and a2
            else 0.0
        )

        keep = (
            (
                shared_name >= 2
                and
                name_sim >= 0.60
            )
            or
            (
                shared_addr >= 3
            )
            or
            (
                shared_addr >= 2
                and
                addr_sim >= 0.30
            )
        )

        if keep:
            selected.append(idx)

    return selected


# ============================================================
# LOAD V5 MODEL
# ============================================================

print("\nLoading V5 model...")

v5_model = CatBoostClassifier()

v5_model.load_model(
    MODEL_PATH
)

print(
    "V5 model loaded:",
    v5_model.is_fitted()
)

print(
    "Tree count:",
    v5_model.tree_count_
)


# ============================================================
# FEATURE BUILDER
# ============================================================

def make_features_s2(
    name1,
    addr1,
    country1,
    candidate_indices
):

    t1n = toks(name1)
    t1a = toks(addr1)
    num1 = nums(addr1)

    rows = []

    for idx in candidate_indices:

        n2 = s2_names[idx]
        a2 = s2_addrs[idx]
        c2 = s2_countries[idx]

        t2n = toks(n2)
        t2a = toks(a2)

        shared_n = t1n & t2n
        shared_a = t1a & t2a

        union_n = t1n | t2n
        union_a = t1a | t2a

        # Similarities
        ns = (
            ratio(name1, n2) / 100
            if name1 and n2
            else 0.0
        )

        ass = (
            ratio(addr1, a2) / 100
            if addr1 and a2
            else 0.0
        )

        # Token overlap
        nt = (
            len(shared_n) /
            max(
                1,
                min(
                    len(t1n),
                    len(t2n)
                )
            )
        )

        at = (
            len(shared_a) /
            max(
                1,
                min(
                    len(t1a),
                    len(t2a)
                )
            )
        )

        # Jaccard
        nj = (
            len(shared_n) /
            len(union_n)
            if union_n
            else 0.0
        )

        aj = (
            len(shared_a) /
            len(union_a)
            if union_a
            else 0.0
        )

        # 20 V5 features
        rows.append([
            # 1
            int(
                bool(name1)
                and
                name1 == n2
            ),

            # 2
            int(
                bool(addr1)
                and
                addr1 == a2
            ),

            # 3
            int(
                country1 == c2
            ),

            # 4
            ns,

            # 5
            ass,

            # 6
            nt,

            # 7
            at,

            # 8
            nj,

            # 9
            aj,

            # 10
            len(shared_n),

            # 11
            len(shared_a),

            # 12
            len(
                num1 & nums(a2)
            ),

            # 13
            abs(
                len(name1) -
                len(n2)
            ),

            # 14
            abs(
                len(addr1) -
                len(a2)
            ),

            # 15
            min(
                len(name1),
                len(n2)
            )
            /
            max(
                1,
                max(
                    len(name1),
                    len(n2)
                )
            ),

            # 16
            min(
                len(addr1),
                len(a2)
            )
            /
            max(
                1,
                max(
                    len(addr1),
                    len(a2)
                )
            ),

            # 17
            abs(
                ns - ass
            ),

            # 18
            max(
                ns,
                ass
            ),

            # 19
            ns * ass,

            # 20
            abs(
                nt - at
            )
        ])

    return np.asarray(
        rows,
        dtype=np.float32
    )


# ============================================================
# RUN 5,000 S1
# ============================================================

print("\n" + "=" * 75)
print("STARTING 5,000-S1 INFERENCE")
print("=" * 75)

start = time.time()

total_candidates = 0
total_predictions = 0

candidate_counts = []
prediction_counts = []

for i, row in enumerate(
    s1.itertuples(index=False),
    1
):

    name1 = norm(
        row.business_name
    )

    addr1 = norm(
        row.business_address
    )

    country1 = (
        str(row.country)
        .lower()
        .strip()
    )

    # Candidate generation
    candidates = generate_v5_candidates_s2(
        name1,
        addr1,
        country1
    )

    candidate_count = len(candidates)

    candidate_counts.append(
        candidate_count
    )

    total_candidates += candidate_count

    # V5 prediction
    if candidate_count > 0:

        X = make_features_s2(
            name1,
            addr1,
            country1,
            candidates
        )

        probs = v5_model.predict_proba(
            X
        )[:, 1]

        prediction_count = int(
            (probs >= THRESHOLD).sum()
        )

    else:

        prediction_count = 0

    prediction_counts.append(
        prediction_count
    )

    total_predictions += prediction_count

    # Progress
    if i % 500 == 0:

        elapsed = time.time() - start

        print(
            f"{i:,}/{N_S1:,} | "
            f"avg candidates/S1="
            f"{total_candidates / i:.2f} | "
            f"matches="
            f"{total_predictions:,} | "
            f"matches/S1="
            f"{total_predictions / i:.3f} | "
            f"time="
            f"{elapsed:.2f}s | "
            f"RAM="
            f"{ram_gb():.2f} GB"
        )


# ============================================================
# FINAL SUMMARY
# ============================================================

elapsed = time.time() - start

print("\n")
print("=" * 75)
print("V5 S2 — 5,000 S1 SMOKE TEST COMPLETE")
print("=" * 75)

print(
    f"S1 processed:        {len(s1):,}"
)

print(
    f"Total candidates:    {total_candidates:,}"
)

print(
    f"Candidates/S1:       "
    f"{total_candidates / len(s1):.3f}"
)

print(
    f"Median candidates:   "
    f"{np.median(candidate_counts):.3f}"
)

print(
    f"P90 candidates:     "
    f"{np.percentile(candidate_counts, 90):.3f}"
)

print(
    f"P95 candidates:     "
    f"{np.percentile(candidate_counts, 95):.3f}"
)

print(
    f"P99 candidates:     "
    f"{np.percentile(candidate_counts, 99):.3f}"
)

print(
    f"Maximum candidates: "
    f"{max(candidate_counts):,}"
)

print(
    f"Predicted matches:  "
    f"{total_predictions:,}"
)

print(
    f"Matches/S1:         "
    f"{total_predictions / len(s1):.3f}"
)

print(
    f"Median matches/S1:  "
    f"{np.median(prediction_counts):.3f}"
)

print(
    f"Runtime:            "
    f"{elapsed:.2f} sec"
)

print(
    f"Time/S1:            "
    f"{elapsed / len(s1):.5f} sec"
)

print(
    f"Available RAM:      "
    f"{ram_gb():.2f} GB"
)

print("=" * 75)

===========================================================================
V5 S2 — 5,000 S1 SMOKE TEST
===========================================================================
Starting available RAM: 6.45 GB

Loading S1...
S1: (5000, 4)

Loading S2...
S2: (4887273, 4)
RAM after S2: 5.77 GB

Preparing S2 arrays...
Arrays ready.
RAM: 4.70 GB

Loading S2 indexes...
S2 indexes loaded.
RAM: 2.53 GB

Loading V5 model...
V5 model loaded: True
Tree count: 670

===========================================================================
STARTING 5,000-S1 INFERENCE
===========================================================================
500/5,000 | avg candidates/S1=2.97 | matches=334 | matches/S1=0.668 | time=0.42s | RAM=2.53 GB
1,000/5,000 | avg candidates/S1=2.88 | matches=679 | matches/S1=0.679 | time=0.86s | RAM=2.53 GB
1,500/5,000 | avg candidates/S1=2.84 | matches=960 | matches/S1=0.640 | time=1.23s | RAM=2.53 GB
2,000/5,000 | avg candidates/S1=2.82 | matches=1,302 | matches/S1=0.651 | time=1.62s | RAM=2.53 GB
2,500/5,000 | avg candidates/S1=2.79 | matches=1,674 | matches/S1=0.670 | time=2.14s | RAM=2.52 GB
3,000/5,000 | avg candidates/S1=2.71 | matches=2,013 | matches/S1=0.671 | time=2.62s | RAM=2.51 GB
3,500/5,000 | avg candidates/S1=2.69 | matches=2,363 | matches/S1=0.675 | time=3.12s | RAM=2.51 GB
4,000/5,000 | avg candidates/S1=2.67 | matches=2,658 | matches/S1=0.664 | time=3.63s | RAM=2.51 GB
4,500/5,000 | avg candidates/S1=2.68 | matches=2,977 | matches/S1=0.662 | time=4.14s | RAM=2.51 GB
5,000/5,000 | avg candidates/S1=2.73 | matches=3,327 | matches/S1=0.665 | time=4.62s | RAM=2.51 GB


===========================================================================
V5 S2 — 5,000 S1 SMOKE TEST COMPLETE
===========================================================================
S1 processed:        5,000
Total candidates:    13,660
Candidates/S1:       2.732
Median candidates:   0.000
P90 candidates:     5.000
P95 candidates:     11.000
P99 candidates:     41.010
Maximum candidates: 276
Predicted matches:  3,327
Matches/S1:         0.665
Median matches/S1:  0.000
Runtime:            4.62 sec
Time/S1:            0.00092 sec
Available RAM:      2.52 GB
===========================================================================

In [ ]:
# ============================================================
# V5 PRODUCTION INFERENCE — FULL TEST
# 1,732,544 S1 × S2/S3
#
# CHECKPOINTED + MEMORY SAFE
# Writes:
#   output/matching_results.tsv
#   output/candidate_pairs.tsv
# ============================================================

import os
import gc
import csv
import time
import pickle
import psutil
import unicodedata
import re

import pandas as pd
import numpy as np

from rapidfuzz.fuzz import ratio
from catboost import CatBoostClassifier


# ============================================================
# CONFIG
# ============================================================

BASE = "/content/amazon_ml_challenge/student_resource"

INDEX_DIR = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/V5_full_indexes"
)

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_model.cbm"
)

OUTPUT_DIR = f"{BASE}/output"
WORK_DIR = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/V5_Final_Production"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(WORK_DIR, exist_ok=True)

THRESHOLD = 0.60
CHUNK_SIZE = 25000


# ============================================================
# OUTPUT FILES
# ============================================================

FINAL_MATCHING = f"{OUTPUT_DIR}/matching_results.tsv"
FINAL_CANDIDATES = f"{OUTPUT_DIR}/candidate_pairs.tsv"

S2_WORK = f"{WORK_DIR}/s2_results.tsv"
S3_WORK = f"{WORK_DIR}/s3_results.tsv"

CHECKPOINT_S2 = f"{WORK_DIR}/s2_checkpoint.txt"
CHECKPOINT_S3 = f"{WORK_DIR}/s3_checkpoint.txt"


# ============================================================
# MEMORY
# ============================================================

def ram_gb():
    return psutil.virtual_memory().available / (1024**3)


print("=" * 80)
print("V5 FULL PRODUCTION INFERENCE")
print("=" * 80)
print("Available RAM:", round(ram_gb(), 2), "GB")
print("Chunk size:", CHUNK_SIZE)
print("Threshold:", THRESHOLD)


# ============================================================
# NORMALIZATION
# ============================================================

def norm(x):

    if x is None:
        return ""

    x = str(x).lower().strip()

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = unicodedata.normalize("NFKC", x)

    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def toks(x):
    return set(x.split()) if x else set()


def nums(x):
    return set(re.findall(r"\d+", x))


# ============================================================
# V5 MODEL
# ============================================================

print("\nLoading V5 model...")

v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

print("Model loaded:", v5_model.is_fitted())
print("Trees:", v5_model.tree_count_)


# ============================================================
# SOURCE PROCESSOR
# ============================================================

def process_source(
    source_number,
    source_file,
    name_index_file,
    addr_index_file,
    name_freq_file,
    addr_freq_file,
    work_file,
    checkpoint_file
):

    print("\n")
    print("=" * 80)
    print(f"PROCESSING SOURCE {source_number}")
    print("=" * 80)

    # --------------------------------------------------------
    # Load source
    # --------------------------------------------------------

    print("Loading source...")

    source = pd.read_csv(
        source_file,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        dtype=str,
        keep_default_na=False
    )

    print("Source shape:", source.shape)
    print("RAM:", round(ram_gb(), 2), "GB")

    # --------------------------------------------------------
    # Prepare arrays
    # --------------------------------------------------------

    print("Normalizing source arrays...")

    source_names = (
        source["business_name"]
        .map(norm)
        .to_numpy()
    )

    source_addrs = (
        source["business_address"]
        .map(norm)
        .to_numpy()
    )

    source_countries = (
        source["country"]
        .astype(str)
        .str.lower()
        .str.strip()
        .to_numpy()
    )

    source_ids = source["entity_id"].to_numpy()

    print("Arrays ready.")
    print("RAM:", round(ram_gb(), 2), "GB")

    # --------------------------------------------------------
    # Load indexes
    # --------------------------------------------------------

    print("Loading indexes...")

    with open(name_index_file, "rb") as f:
        name_index = pickle.load(f)

    with open(addr_index_file, "rb") as f:
        addr_index = pickle.load(f)

    with open(name_freq_file, "rb") as f:
        name_freq = pickle.load(f)

    with open(addr_freq_file, "rb") as f:
        addr_freq = pickle.load(f)

    print("Indexes loaded.")
    print("RAM:", round(ram_gb(), 2), "GB")

    # --------------------------------------------------------
    # Candidate generator
    # --------------------------------------------------------

    def generate_candidates(
        name1,
        addr1,
        country1
    ):

        t_name = toks(name1)
        t_addr = toks(addr1)

        name_hits = {}
        addr_hits = {}

        # NAME BLOCK
        for token in t_name:

            if name_freq.get(
                token,
                10**9
            ) <= 500:

                for idx in name_index.get(
                    token,
                    ()
                ):

                    if source_countries[idx] == country1:

                        name_hits[idx] = (
                            name_hits.get(
                                idx,
                                0
                            ) + 1
                        )

        # ADDRESS BLOCK
        for token in t_addr:

            if addr_freq.get(
                token,
                10**9
            ) <= 500:

                for idx in addr_index.get(
                    token,
                    ()
                ):

                    if source_countries[idx] == country1:

                        addr_hits[idx] = (
                            addr_hits.get(
                                idx,
                                0
                            ) + 1
                        )

        # Require >=2 shared tokens
        candidate_ids = (
            {
                idx
                for idx, count in name_hits.items()
                if count >= 2
            }
            |
            {
                idx
                for idx, count in addr_hits.items()
                if count >= 2
            }
        )

        # Final V5 candidate filtering
        selected = []

        for idx in candidate_ids:

            n2 = source_names[idx]
            a2 = source_addrs[idx]

            # Exact
            if (
                (name1 and name1 == n2)
                or
                (addr1 and addr1 == a2)
            ):

                selected.append(idx)
                continue

            t2n = toks(n2)
            t2a = toks(a2)

            shared_name = len(
                t_name & t2n
            )

            shared_addr = len(
                t_addr & t2a
            )

            name_sim = (
                ratio(name1, n2) / 100
                if name1 and n2
                else 0.0
            )

            addr_sim = (
                ratio(addr1, a2) / 100
                if addr1 and a2
                else 0.0
            )

            keep = (
                (
                    shared_name >= 2
                    and name_sim >= 0.60
                )
                or
                shared_addr >= 3
                or
                (
                    shared_addr >= 2
                    and addr_sim >= 0.30
                )
            )

            if keep:
                selected.append(idx)

        return selected

    # --------------------------------------------------------
    # Feature builder
    # --------------------------------------------------------

    def make_features(
        name1,
        addr1,
        country1,
        candidate_indices
    ):

        t1n = toks(name1)
        t1a = toks(addr1)
        num1 = nums(addr1)

        rows = []

        for idx in candidate_indices:

            n2 = source_names[idx]
            a2 = source_addrs[idx]
            c2 = source_countries[idx]

            t2n = toks(n2)
            t2a = toks(a2)

            shared_n = t1n & t2n
            shared_a = t1a & t2a

            union_n = t1n | t2n
            union_a = t1a | t2a

            ns = (
                ratio(name1, n2) / 100
                if name1 and n2
                else 0.0
            )

            ass = (
                ratio(addr1, a2) / 100
                if addr1 and a2
                else 0.0
            )

            nt = (
                len(shared_n) /
                max(
                    1,
                    min(
                        len(t1n),
                        len(t2n)
                    )
                )
            )

            at = (
                len(shared_a) /
                max(
                    1,
                    min(
                        len(t1a),
                        len(t2a)
                    )
                )
            )

            nj = (
                len(shared_n) /
                len(union_n)
                if union_n
                else 0.0
            )

            aj = (
                len(shared_a) /
                len(union_a)
                if union_a
                else 0.0
            )

            rows.append([
                int(
                    bool(name1)
                    and name1 == n2
                ),
                int(
                    bool(addr1)
                    and addr1 == a2
                ),
                int(
                    country1 == c2
                ),
                ns,
                ass,
                nt,
                at,
                nj,
                aj,
                len(shared_n),
                len(shared_a),
                len(num1 & nums(a2)),
                abs(
                    len(name1) -
                    len(n2)
                ),
                abs(
                    len(addr1) -
                    len(a2)
                ),
                min(
                    len(name1),
                    len(n2)
                ) /
                max(
                    1,
                    max(
                        len(name1),
                        len(n2)
                    )
                ),
                min(
                    len(addr1),
                    len(a2)
                ) /
                max(
                    1,
                    max(
                        len(addr1),
                        len(a2)
                    )
                ),
                abs(ns - ass),
                max(ns, ass),
                ns * ass,
                abs(nt - at)
            ])

        return np.asarray(
            rows,
            dtype=np.float32
        )

    # --------------------------------------------------------
    # Resume checkpoint
    # --------------------------------------------------------

    start_row = 0

    if os.path.exists(checkpoint_file):

        with open(
            checkpoint_file,
            "r"
        ) as f:

            text = f.read().strip()

            if text:
                start_row = int(text)

        print(
            "Resuming from row:",
            start_row
        )

    # --------------------------------------------------------
    # Work file
    # --------------------------------------------------------

    file_mode = (
        "a"
        if start_row > 0
        else "w"
    )

    with open(
        work_file,
        file_mode,
        encoding="utf-8",
        newline=""
    ) as fout:

        writer = csv.writer(
            fout,
            delimiter="\t",
            lineterminator="\n"
        )

        if start_row == 0:

            writer.writerow([
                "source1_entity_id",
                "candidate_entity_ids",
                "matched_entity_ids"
            ])

        total_candidates = 0
        total_matches = 0
        processed = start_row

        start_time = time.time()

        # ----------------------------------------------------
        # Read S1 in chunks
        # ----------------------------------------------------

        for s1_chunk in pd.read_csv(
            f"{BASE}/dataset/test/test_source1.tsv",
            sep="\t",
            dtype=str,
            keep_default_na=False,
            chunksize=CHUNK_SIZE,
            skiprows=range(
                1,
                start_row + 1
            )
            if start_row > 0
            else None
        ):

            for row in s1_chunk.itertuples(
                index=False
            ):

                name1 = norm(
                    row.business_name
                )

                addr1 = norm(
                    row.business_address
                )

                country1 = (
                    str(row.country)
                    .lower()
                    .strip()
                )

                candidates = generate_candidates(
                    name1,
                    addr1,
                    country1
                )

                candidate_ids = [
                    source_ids[i]
                    for i in candidates
                ]

                matches = []

                if candidates:

                    X = make_features(
                        name1,
                        addr1,
                        country1,
                        candidates
                    )

                    probs = (
                        v5_model
                        .predict_proba(X)[:, 1]
                    )

                    matches = [
                        source_ids[idx]
                        for idx, p in zip(
                            candidates,
                            probs
                        )
                        if p >= THRESHOLD
                    ]

                # Remove duplicates defensively
                candidate_ids = list(
                    dict.fromkeys(
                        candidate_ids
                    )
                )

                matches = list(
                    dict.fromkeys(
                        matches
                    )
                )

                writer.writerow([
                    row.entity_id,
                    ",".join(candidate_ids),
                    ",".join(matches)
                ])

                processed += 1
                total_candidates += len(
                    candidate_ids
                )
                total_matches += len(
                    matches
                )

            fout.flush()

            # Checkpoint
            with open(
                checkpoint_file,
                "w"
            ) as cf:

                cf.write(
                    str(processed)
                )

            elapsed = time.time() - start_time

            print(
                f"{processed:,}/1,732,544 | "
                f"candidates={total_candidates:,} | "
                f"matches={total_matches:,} | "
                f"time={elapsed/60:.1f} min | "
                f"RAM={ram_gb():.2f} GB"
            )

    # --------------------------------------------------------
    # Cleanup source
    # --------------------------------------------------------

    del source
    del source_names
    del source_addrs
    del source_countries
    del source_ids
    del name_index
    del addr_index
    del name_freq
    del addr_freq

    gc.collect()

    print(
        f"SOURCE {source_number} COMPLETE"
    )


# ============================================================
# RUN S2
# ============================================================

process_source(
    2,

    f"{BASE}/dataset/test/test_source2.tsv",

    f"{INDEX_DIR}/s2_name_index.pkl",
    f"{INDEX_DIR}/s2_addr_index.pkl",

    f"{INDEX_DIR}/s2_name_freq.pkl",
    f"{INDEX_DIR}/s2_addr_freq.pkl",

    S2_WORK,
    CHECKPOINT_S2
)


# ============================================================
# CLEAN MEMORY
# ============================================================

gc.collect()

print(
    "\nAfter S2 cleanup RAM:",
    round(ram_gb(), 2),
    "GB"
)


# ============================================================
# RUN S3
# ============================================================

process_source(
    3,

    f"{BASE}/dataset/test/test_source3.tsv",

    f"{INDEX_DIR}/s3_name_index.pkl",
    f"{INDEX_DIR}/s3_addr_index.pkl",

    f"{INDEX_DIR}/s3_name_freq.pkl",
    f"{INDEX_DIR}/s3_addr_freq.pkl",

    S3_WORK,
    CHECKPOINT_S3
)


# ============================================================
# COMBINE S2 + S3
# ============================================================

print("\n")
print("=" * 80)
print("COMBINING S2 + S3 RESULTS")
print("=" * 80)

# S2/S3 work files each contain exactly one row per S1.
# Merge chunk-by-chunk using the S1 row order.

s2_df = pd.read_csv(
    S2_WORK,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

s3_df = pd.read_csv(
    S3_WORK,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("S2 rows:", len(s2_df))
print("S3 rows:", len(s3_df))

assert len(s2_df) == len(s3_df)

assert (
    s2_df["source1_entity_id"].values
    ==
    s3_df["source1_entity_id"].values
).all()

# ------------------------------------------------------------
# Final output
# ------------------------------------------------------------

with open(
    FINAL_MATCHING,
    "w",
    encoding="utf-8",
    newline=""
) as fm, open(
    FINAL_CANDIDATES,
    "w",
    encoding="utf-8",
    newline=""
) as fc:

    mw = csv.writer(
        fm,
        delimiter="\t",
        lineterminator="\n"
    )

    cw = csv.writer(
        fc,
        delimiter="\t",
        lineterminator="\n"
    )

    mw.writerow([
        "source1_entity_id",
        "matched_entity_ids"
    ])

    cw.writerow([
        "source1_entity_id",
        "candidate_entity_ids"
    ])

    for i in range(len(s2_df)):

        s1_id = s2_df.iloc[
            i
        ]["source1_entity_id"]

        s2_candidates = (
            s2_df.iloc[i]
            ["candidate_entity_ids"]
        )

        s3_candidates = (
            s3_df.iloc[i]
            ["candidate_entity_ids"]
        )

        s2_matches = (
            s2_df.iloc[i]
            ["matched_entity_ids"]
        )

        s3_matches = (
            s3_df.iloc[i]
            ["matched_entity_ids"]
        )

        # Combine candidate IDs
        candidates = []

        if s2_candidates:
            candidates.extend(
                s2_candidates.split(",")
            )

        if s3_candidates:
            candidates.extend(
                s3_candidates.split(",")
            )

        candidates = list(
            dict.fromkeys(
                x for x in candidates
                if x
            )
        )

        # Combine predicted matches
        matches = []

        if s2_matches:
            matches.extend(
                s2_matches.split(",")
            )

        if s3_matches:
            matches.extend(
                s3_matches.split(",")
            )

        matches = list(
            dict.fromkeys(
                x for x in matches
                if x
            )
        )

        cw.writerow([
            s1_id,
            ",".join(candidates)
        ])

        mw.writerow([
            s1_id,
            ",".join(matches)
        ])

print("\nFINAL FILES CREATED")
print(FINAL_MATCHING)
print(FINAL_CANDIDATES)

print("\nSizes:")
print(
    "matching:",
    round(
        os.path.getsize(
            FINAL_MATCHING
        ) / (1024**2),
        2
    ),
    "MB"
)

print(
    "candidate:",
    round(
        os.path.getsize(
            FINAL_CANDIDATES
        ) / (1024**2),
        2
    ),
    "MB"
)

print("\nPRODUCTION INFERENCE COMPLETE.")

================================================================================
V5 FULL PRODUCTION INFERENCE
================================================================================
Available RAM: 2.51 GB
Chunk size: 25000
Threshold: 0.6

Loading V5 model...
Model loaded: True
Trees: 670


================================================================================
PROCESSING SOURCE 2
================================================================================
Loading source...
Source shape: (4887273, 4)
RAM: 1.16 GB
Normalizing source arrays...
Arrays ready.
RAM: 0.63 GB
Loading indexes...

In [ ]:
# ============================================================
# RAM-SAFE V5 PRODUCTION SETUP
# ============================================================

import os, gc, re, csv, pickle, unicodedata, time
import numpy as np
import pandas as pd

from catboost import CatBoostClassifier
from rapidfuzz.fuzz import ratio

# Paths
BASE = "/content/amazon_ml_challenge/student_resource"
TEST_DIR = f"{BASE}/dataset/test"
OUT_DIR = f"{BASE}/output"

DRIVE_ML = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"
INDEX_DIR = f"{DRIVE_ML}/V5_full_indexes"
MODEL_PATH = f"{DRIVE_ML}/V5_ML_Final/V5_ML_Final/v5_model.cbm"

WORK_DIR = f"{DRIVE_ML}/V5_Final_Production_RAMSAFE"
os.makedirs(WORK_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)

S2_WORK = f"{WORK_DIR}/s2_results.tsv"
S3_WORK = f"{WORK_DIR}/s3_results.tsv"

THRESHOLD = 0.60

# VERY IMPORTANT: smaller than previous run
CHUNK_SIZE = 2000

print("Setup complete.")
print("RAM-safe chunk size:", CHUNK_SIZE)
print("Model exists:", os.path.exists(MODEL_PATH))
print("Index directory exists:", os.path.exists(INDEX_DIR))
print("Test directory exists:", os.path.exists(TEST_DIR))

# Show current RAM
try:
    import psutil
    vm = psutil.virtual_memory()
    print(f"RAM available: {vm.available/1024**3:.2f} GB / {vm.total/1024**3:.2f} GB")
except:
    pass

Setup complete.
RAM-safe chunk size: 2000
Model exists: True
Index directory exists: True
Test directory exists: True
RAM available: 11.01 GB / 12.67 GB

In [ ]:
# ============================================================
# STEP 2 — LOAD MODEL + INSPECT INDEXES
# ============================================================

import os
import gc
import psutil
from catboost import CatBoostClassifier

# Load V5 model
model = CatBoostClassifier()
model.load_model(MODEL_PATH)

print("✅ V5 model loaded")
print("Tree count:", model.tree_count_)
print("Model fitted:", model.is_fitted())

print("\n📁 Index files:")
for root, dirs, files in os.walk(INDEX_DIR):
    for f in files:
        path = os.path.join(root, f)
        size_mb = os.path.getsize(path) / (1024**2)
        print(f"{os.path.relpath(path, INDEX_DIR):60s} {size_mb:8.1f} MB")

gc.collect()

vm = psutil.virtual_memory()
print(f"\n💾 RAM available: {vm.available/1024**3:.2f} GB / {vm.total/1024**3:.2f} GB")

✅ V5 model loaded
Tree count: 670
Model fitted: True

📁 Index files:
s2_name_index.pkl                                                96.4 MB
s2_addr_index.pkl                                               196.7 MB
s2_name_freq.pkl                                                 12.7 MB
s2_addr_freq.pkl                                                 16.5 MB
s3_name_index.pkl                                               100.9 MB
s3_addr_index.pkl                                               196.1 MB
s3_name_freq.pkl                                                 13.6 MB
s3_addr_freq.pkl                                                 16.0 MB

💾 RAM available: 10.74 GB / 12.67 GB

In [ ]:
# ============================================================
# STEP 3 — LOAD SOURCE 2 ONLY
# ============================================================

import pickle
import gc
import psutil
import pandas as pd
import numpy as np

def ram_status(label=""):
    gc.collect()
    vm = psutil.virtual_memory()
    print(f"💾 {label} RAM available: "
          f"{vm.available/1024**3:.2f} GB / {vm.total/1024**3:.2f} GB")

ram_status("Before S2 load")

# ------------------------------------------------------------
# Load Source 2
# ------------------------------------------------------------
S2_PATH = f"{TEST_DIR}/test_source2.tsv"

s2 = pd.read_csv(
    S2_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("✅ S2 loaded")
print("S2 shape:", s2.shape)
print("S2 columns:", list(s2.columns))

ram_status("After S2 dataframe")

# ------------------------------------------------------------
# Load ONLY S2 indexes
# ------------------------------------------------------------
with open(f"{INDEX_DIR}/s2_name_index.pkl", "rb") as f:
    s2_name_index = pickle.load(f)

with open(f"{INDEX_DIR}/s2_addr_index.pkl", "rb") as f:
    s2_addr_index = pickle.load(f)

with open(f"{INDEX_DIR}/s2_name_freq.pkl", "rb") as f:
    s2_name_freq = pickle.load(f)

with open(f"{INDEX_DIR}/s2_addr_freq.pkl", "rb") as f:
    s2_addr_freq = pickle.load(f)

print("✅ S2 indexes loaded")

print("name index type:", type(s2_name_index))
print("address index type:", type(s2_addr_index))
print("name frequency type:", type(s2_name_freq))
print("address frequency type:", type(s2_addr_freq))

ram_status("After S2 indexes")

print("\nS2 rows:", len(s2))
print("S2 name index entries:", len(s2_name_index))
print("S2 address index entries:", len(s2_addr_index))

💾 Before S2 load RAM available: 10.92 GB / 12.67 GB
✅ S2 loaded
S2 shape: (4887273, 4)
S2 columns: ['entity_id', 'business_name', 'business_address', 'country']
💾 After S2 dataframe RAM available: 9.32 GB / 12.67 GB
✅ S2 indexes loaded
name index type: <class 'dict'>
address index type: <class 'dict'>
name frequency type: <class 'dict'>
address frequency type: <class 'dict'>
💾 After S2 indexes RAM available: 6.77 GB / 12.67 GB

S2 rows: 4887273
S2 name index entries: 861199
S2 address index entries: 1330963

In [ ]:
# ============================================================
# STEP 4 — RAM-SAFE S2 PRODUCTION
# Same V5 logic / threshold / candidate rules
# ============================================================

import re
import unicodedata
import csv
import gc
import time
import psutil
import numpy as np
import pandas as pd

S2_WORK = f"{WORK_DIR}/s2_results.tsv"

# ------------------------------------------------------------
# Normalization
# ------------------------------------------------------------
def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def tokens(text):
    return set(text.split()) if text else set()


# ------------------------------------------------------------
# V5 feature calculation
# ------------------------------------------------------------
def make_features(s1_name, s1_addr, s1_country,
                  s2_name, s2_addr, s2_country):

    n1 = normalize_advanced(s1_name)
    a1 = normalize_advanced(s1_addr)

    n2 = normalize_advanced(s2_name)
    a2 = normalize_advanced(s2_addr)

    nt1 = tokens(n1)
    nt2 = tokens(n2)
    at1 = tokens(a1)
    at2 = tokens(a2)

    name_overlap = len(nt1 & nt2)
    addr_overlap = len(at1 & at2)

    # Numeric address tokens
    nums1 = set(re.findall(r"\b\d+\b", a1))
    nums2 = set(re.findall(r"\b\d+\b", a2))

    shared_addr_numbers = len(nums1 & nums2)

    name_sim = ratio(n1, n2) / 100.0
    addr_sim = ratio(a1, a2) / 100.0

    name_len_1 = len(n1)
    name_len_2 = len(n2)
    addr_len_1 = len(a1)
    addr_len_2 = len(a2)

    name_len_diff = abs(name_len_1 - name_len_2)
    addr_len_diff = abs(addr_len_1 - addr_len_2)

    name_len_ratio = (
        min(name_len_1, name_len_2) / max(name_len_1, name_len_2)
        if max(name_len_1, name_len_2) > 0 else 1.0
    )

    addr_len_ratio = (
        min(addr_len_1, addr_len_2) / max(addr_len_1, addr_len_2)
        if max(addr_len_1, addr_len_2) > 0 else 1.0
    )

    similarity_gap = abs(name_sim - addr_sim)
    max_similarity = max(name_sim, addr_sim)
    similarity_product = name_sim * addr_sim
    token_overlap_gap = abs(name_overlap - addr_overlap)

    return [
        int(n1 == n2),
        int(a1 == a2),
        int(str(s1_country).strip().lower() ==
            str(s2_country).strip().lower()),

        name_sim,
        addr_sim,

        name_overlap / max(len(nt1), len(nt2), 1),
        addr_overlap / max(len(at1), len(at2), 1),

        name_overlap / max(len(nt1 | nt2), 1),
        addr_overlap / max(len(at1 | at2), 1),

        name_overlap,
        addr_overlap,
        shared_addr_numbers,

        name_len_diff,
        addr_len_diff,
        name_len_ratio,
        addr_len_ratio,

        similarity_gap,
        max_similarity,
        similarity_product,
        token_overlap_gap
    ]


# ------------------------------------------------------------
# Candidate generator
# EXACT production rules benchmarked earlier
# ------------------------------------------------------------
def generate_candidates(s1_name, s1_addr, s1_country):

    n1 = normalize_advanced(s1_name)
    a1 = normalize_advanced(s1_addr)

    name_tok = tokens(n1)
    addr_tok = tokens(a1)

    candidate_counts = {}

    # Rare token block: frequency <= 500
    for tok in name_tok:
        if s2_name_freq.get(tok, 10**9) <= 500:
            ids = s2_name_index.get(tok)
            if ids is not None:
                for idx in ids:
                    candidate_counts[idx] = candidate_counts.get(idx, 0) + 1

    for tok in addr_tok:
        if s2_addr_freq.get(tok, 10**9) <= 500:
            ids = s2_addr_index.get(tok)
            if ids is not None:
                for idx in ids:
                    candidate_counts[idx] = candidate_counts.get(idx, 0) + 1

    # Need at least 2 shared tokens to enter the final block
    candidate_indices = [
        idx for idx, count in candidate_counts.items()
        if count >= 2
    ]

    if not candidate_indices:
        return []

    # --------------------------------------------------------
    # Final hybrid rules
    # 1 exact name + country
    # 2 exact address + country
    # 3 >=2 shared name tokens + name sim >= .60
    # 4 >=3 shared address tokens
    # 5 >=2 shared address tokens + address sim >= .30
    # --------------------------------------------------------
    final_indices = []

    s1_country_norm = str(s1_country).strip().lower()

    for idx in candidate_indices:

        row = s2.iloc[idx]

        s2_name = row["business_name"]
        s2_addr = row["business_address"]
        s2_country = row["country"]

        n2 = normalize_advanced(s2_name)
        a2 = normalize_advanced(s2_addr)

        nt2 = tokens(n2)
        at2 = tokens(a2)

        name_shared = len(name_tok & nt2)
        addr_shared = len(addr_tok & at2)

        country_same = (
            s1_country_norm ==
            str(s2_country).strip().lower()
        )

        name_exact = (n1 == n2)
        addr_exact = (a1 == a2)

        name_sim = ratio(n1, n2) / 100.0
        addr_sim = ratio(a1, a2) / 100.0

        keep = (
            (name_exact and country_same)
            or
            (addr_exact and country_same)
            or
            (name_shared >= 2 and name_sim >= 0.60)
            or
            (addr_shared >= 3)
            or
            (addr_shared >= 2 and addr_sim >= 0.30)
        )

        if keep:
            final_indices.append(idx)

    return final_indices


# ------------------------------------------------------------
# Prepare output
# ------------------------------------------------------------
if os.path.exists(S2_WORK):
    print("⚠️ Existing S2 work file found:")
    print(S2_WORK)
    print("Delete/rename it before starting if it is from an old run.")
    raise RuntimeError("Existing S2 output detected. Not overwriting it.")

S1_PATH = f"{TEST_DIR}/test_source1.tsv"

# Header
with open(S2_WORK, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, delimiter="\t")
    writer.writerow([
        "source1_entity_id",
        "candidate_entity_ids",
        "matched_entity_ids"
    ])

# ------------------------------------------------------------
# Process S1 in very small chunks
# ------------------------------------------------------------
total_s1 = 0
total_candidates = 0
total_matches = 0
start_time = time.time()

print("\n🚀 Starting S2 production...")
print("S1 chunk size:", CHUNK_SIZE)
print("Threshold:", THRESHOLD)

for chunk_no, s1_chunk in enumerate(
    pd.read_csv(
        S1_PATH,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    chunk_start = time.time()

    output_rows = []

    for _, row in s1_chunk.iterrows():

        s1_id = row["entity_id"]
        s1_name = row["business_name"]
        s1_addr = row["business_address"]
        s1_country = row["country"]

        candidate_indices = generate_candidates(
            s1_name,
            s1_addr,
            s1_country
        )

        candidate_ids = []
        matched_ids = []

        if candidate_indices:

            feature_rows = []

            for idx in candidate_indices:

                s2_row = s2.iloc[idx]

                feature_rows.append(
                    make_features(
                        s1_name,
                        s1_addr,
                        s1_country,
                        s2_row["business_name"],
                        s2_row["business_address"],
                        s2_row["country"]
                    )
                )

                candidate_ids.append(
                    str(s2_row["entity_id"])
                )

            X = np.asarray(
                feature_rows,
                dtype=np.float32
            )

            probs = model.predict_proba(X)[:, 1]

            for cid, p in zip(candidate_ids, probs):
                if p >= THRESHOLD:
                    matched_ids.append(cid)

            del X, feature_rows, probs

        # Deduplicate while preserving order
        candidate_ids = list(dict.fromkeys(candidate_ids))
        matched_ids = list(dict.fromkeys(matched_ids))

        output_rows.append([
            s1_id,
            ",".join(candidate_ids),
            ",".join(matched_ids)
        ])

        total_s1 += 1
        total_candidates += len(candidate_ids)
        total_matches += len(matched_ids)

    # Write chunk immediately
    with open(
        S2_WORK,
        "a",
        newline="",
        encoding="utf-8"
    ) as f:

        writer = csv.writer(f, delimiter="\t")
        writer.writerows(output_rows)

    # Release chunk memory
    del output_rows
    del s1_chunk
    gc.collect()

    elapsed = time.time() - start_time
    chunk_time = time.time() - chunk_start

    vm = psutil.virtual_memory()

    print(
        f"Chunk {chunk_no:4d} | "
        f"S1 {total_s1:8d} | "
        f"Candidates {total_candidates:10d} | "
        f"Matches {total_matches:10d} | "
        f"Chunk {chunk_time:6.1f}s | "
        f"RAM free {vm.available/1024**3:5.2f} GB | "
        f"Elapsed {elapsed/60:6.1f} min"
    )

print("\n✅ S2 PRODUCTION COMPLETE")

print("S1 processed:", total_s1)
print("Total candidates:", total_candidates)
print("Total matches:", total_matches)
print("Avg candidates/S1:", total_candidates / max(total_s1, 1))
print("Avg matches/S1:", total_matches / max(total_s1, 1))
print("Output:", S2_WORK)

ram_status("After S2 production")

🚀 Starting S2 production...
S1 chunk size: 2000
Threshold: 0.6
Chunk    1 | S1     2000 | Candidates       6541 | Matches       1705 | Chunk   10.7s | RAM free  7.01 GB | Elapsed    0.2 min
Chunk    2 | S1     4000 | Candidates      12356 | Matches       3458 | Chunk    9.7s | RAM free  6.94 GB | Elapsed    0.3 min
Chunk    3 | S1     6000 | Candidates      19471 | Matches       5240 | Chunk    7.0s | RAM free  6.89 GB | Elapsed    0.5 min
Chunk    4 | S1     8000 | Candidates      25843 | Matches       6894 | Chunk    9.0s | RAM free  6.83 GB | Elapsed    0.6 min
Chunk    5 | S1    10000 | Candidates      31325 | Matches       8657 | Chunk    6.3s | RAM free  6.79 GB | Elapsed    0.7 min
Chunk    6 | S1    12000 | Candidates      37638 | Matches      10438 | Chunk    4.3s | RAM free  6.79 GB | Elapsed    0.8 min
Chunk    7 | S1    14000 | Candidates      44646 | Matches      12226 | Chunk    5.4s | RAM free  6.76 GB | Elapsed    0.9 min
Chunk    8 | S1    16000 | Candidates      51069 | Matches      14051 | Chunk    4.1s | RAM free  6.76 GB | Elapsed    0.9 min
Chunk    9 | S1    18000 | Candidates      57271 | Matches      15858 | Chunk    4.0s | RAM free  6.76 GB | Elapsed    1.0 min
Chunk   10 | S1    20000 | Candidates      63498 | Matches      17693 | Chunk    5.0s | RAM free  6.77 GB | Elapsed    1.1 min
Chunk   11 | S1    22000 | Candidates      70467 | Matches      19481 | Chunk    4.5s | RAM free  6.76 GB | Elapsed    1.2 min
Chunk   12 | S1    24000 | Candidates      77739 | Matches      21256 | Chunk    4.2s | RAM free  6.76 GB | Elapsed    1.2 min
Chunk   13 | S1    26000 | Candidates      83881 | Matches      23039 | Chunk    4.6s | RAM free  6.77 GB | Elapsed    1.3 min
Chunk   14 | S1    28000 | Candidates      89643 | Matches      24821 | Chunk    4.6s | RAM free  6.76 GB | Elapsed    1.4 min
Chunk   15 | S1    30000 | Candidates      95873 | Matches      26611 | Chunk    4.0s | RAM free  6.76 GB | Elapsed    1.5 min
Chunk   16 | S1    32000 | Candidates     102725 | Matches      28483 | Chunk    4.1s | RAM free  6.77 GB | Elapsed    1.5 min
Chunk   17 | S1    34000 | Candidates     109001 | Matches      30350 | Chunk    5.3s | RAM free  6.77 GB | Elapsed    1.6 min
Chunk   18 | S1    36000 | Candidates     115584 | Matches      32117 | Chunk    4.2s | RAM free  6.77 GB | Elapsed    1.7 min
Chunk   19 | S1    38000 | Candidates     122095 | Matches      33930 | Chunk    4.1s | RAM free  6.77 GB | Elapsed    1.8 min
Chunk   20 | S1    40000 | Candidates     128285 | Matches      35699 | Chunk    5.3s | RAM free  7.02 GB | Elapsed    1.8 min
Chunk   21 | S1    42000 | Candidates     134935 | Matches      37532 | Chunk    4.4s | RAM free  7.02 GB | Elapsed    1.9 min
Chunk   22 | S1    44000 | Candidates     141647 | Matches      39298 | Chunk    4.1s | RAM free  7.02 GB | Elapsed    2.0 min
Chunk   23 | S1    46000 | Candidates     147980 | Matches      41112 | Chunk    4.3s | RAM free  7.02 GB | Elapsed    2.1 min
Chunk   24 | S1    48000 | Candidates     154681 | Matches      42856 | Chunk    6.0s | RAM free  7.03 GB | Elapsed    2.2 min
Chunk   25 | S1    50000 | Candidates     161320 | Matches      44716 | Chunk    4.1s | RAM free  7.03 GB | Elapsed    2.2 min
Chunk   26 | S1    52000 | Candidates     168362 | Matches      46608 | Chunk    4.2s | RAM free  7.02 GB | Elapsed    2.3 min
Chunk   27 | S1    54000 | Candidates     175226 | Matches      48451 | Chunk    5.3s | RAM free  7.02 GB | Elapsed    2.4 min
Chunk   28 | S1    56000 | Candidates     181394 | Matches      50195 | Chunk    3.8s | RAM free  7.02 GB | Elapsed    2.5 min
Chunk   29 | S1    58000 | Candidates     187799 | Matches      52017 | Chunk    4.0s | RAM free  7.02 GB | Elapsed    2.5 min
Chunk   30 | S1    60000 | Candidates     194718 | Matches      53952 | Chunk    4.8s | RAM free  7.04 GB | Elapsed    2.6 min
Chunk   31 | S1    62000 | Candidates     202347 | Matches      55689 | Chunk    4.8s | RAM free  7.03 GB | Elapsed    2.7 min
Chunk   32 | S1    64000 | Candidates     209306 | Matches      57538 | Chunk    4.4s | RAM free  7.06 GB | Elapsed    2.8 min
Chunk   33 | S1    66000 | Candidates     216737 | Matches      59430 | Chunk    4.9s | RAM free  7.03 GB | Elapsed    2.8 min
Chunk   34 | S1    68000 | Candidates     223631 | Matches      61311 | Chunk    5.0s | RAM free  7.02 GB | Elapsed    2.9 min
Chunk   35 | S1    70000 | Candidates     230396 | Matches      63149 | Chunk    4.1s | RAM free  7.05 GB | Elapsed    3.0 min
Chunk   36 | S1    72000 | Candidates     237053 | Matches      64958 | Chunk    4.1s | RAM free  7.04 GB | Elapsed    3.1 min
Chunk   37 | S1    74000 | Candidates     243857 | Matches      66776 | Chunk    5.3s | RAM free  7.05 GB | Elapsed    3.1 min
Chunk   38 | S1    76000 | Candidates     250635 | Matches      68679 | Chunk    4.0s | RAM free  7.05 GB | Elapsed    3.2 min
Chunk   39 | S1    78000 | Candidates     257715 | Matches      70586 | Chunk    4.2s | RAM free  7.04 GB | Elapsed    3.3 min
Chunk   40 | S1    80000 | Candidates     263925 | Matches      72446 | Chunk    4.9s | RAM free  7.02 GB | Elapsed    3.4 min
Chunk   41 | S1    82000 | Candidates     270569 | Matches      74293 | Chunk    4.3s | RAM free  7.05 GB | Elapsed    3.4 min
Chunk   42 | S1    84000 | Candidates     276969 | Matches      76111 | Chunk    4.0s | RAM free  7.05 GB | Elapsed    3.5 min
Chunk   43 | S1    86000 | Candidates     283797 | Matches      78015 | Chunk    5.3s | RAM free  7.10 GB | Elapsed    3.6 min
Chunk   44 | S1    88000 | Candidates     290157 | Matches      79764 | Chunk    4.8s | RAM free  7.10 GB | Elapsed    3.7 min
Chunk   45 | S1    90000 | Candidates     295222 | Matches      81538 | Chunk    3.7s | RAM free  7.10 GB | Elapsed    3.7 min
Chunk   46 | S1    92000 | Candidates     301333 | Matches      83295 | Chunk    3.9s | RAM free  7.10 GB | Elapsed    3.8 min
Chunk   47 | S1    94000 | Candidates     307542 | Matches      84972 | Chunk    5.1s | RAM free  7.12 GB | Elapsed    3.9 min
Chunk   48 | S1    96000 | Candidates     313615 | Matches      86908 | Chunk    3.9s | RAM free  7.11 GB | Elapsed    3.9 min
Chunk   49 | S1    98000 | Candidates     320425 | Matches      88847 | Chunk    4.2s | RAM free  7.11 GB | Elapsed    4.0 min
Chunk   50 | S1   100000 | Candidates     327134 | Matches      90678 | Chunk    4.7s | RAM free  7.11 GB | Elapsed    4.1 min
Chunk   51 | S1   102000 | Candidates     334203 | Matches      92472 | Chunk    6.6s | RAM free  6.88 GB | Elapsed    4.2 min
Chunk   52 | S1   104000 | Candidates     339932 | Matches      94194 | Chunk   11.9s | RAM free  3.52 GB | Elapsed    4.4 min
Chunk   53 | S1   106000 | Candidates     346535 | Matches      95955 | Chunk    5.4s | RAM free  7.11 GB | Elapsed    4.5 min
Chunk   54 | S1   108000 | Candidates     352081 | Matches      97729 | Chunk    3.8s | RAM free  7.11 GB | Elapsed    4.6 min
Chunk   55 | S1   110000 | Candidates     358470 | Matches      99592 | Chunk    4.0s | RAM free  7.11 GB | Elapsed    4.6 min
Chunk   56 | S1   112000 | Candidates     364763 | Matches     101333 | Chunk    5.3s | RAM free  7.09 GB | Elapsed    4.7 min
Chunk   57 | S1   114000 | Candidates     371334 | Matches     103229 | Chunk    4.2s | RAM free  7.09 GB | Elapsed    4.8 min
Chunk   58 | S1   116000 | Candidates     377148 | Matches     105006 | Chunk    4.0s | RAM free  7.11 GB | Elapsed    4.9 min
Chunk   59 | S1   118000 | Candidates     384210 | Matches     106768 | Chunk    5.2s | RAM free  7.10 GB | Elapsed    4.9 min
Chunk   60 | S1   120000 | Candidates     391359 | Matches     108528 | Chunk    4.7s | RAM free  7.09 GB | Elapsed    5.0 min
Chunk   61 | S1   122000 | Candidates     397190 | Matches     110311 | Chunk    4.0s | RAM free  7.12 GB | Elapsed    5.1 min
Chunk   62 | S1   124000 | Candidates     402874 | Matches     112001 | Chunk    4.1s | RAM free  7.10 GB | Elapsed    5.2 min
Chunk   63 | S1   126000 | Candidates     409059 | Matches     113713 | Chunk    4.9s | RAM free  7.10 GB | Elapsed    5.2 min
Chunk   64 | S1   128000 | Candidates     415445 | Matches     115338 | Chunk    3.9s | RAM free  7.10 GB | Elapsed    5.3 min
Chunk   65 | S1   130000 | Candidates     421396 | Matches     117043 | Chunk    3.9s | RAM free  7.10 GB | Elapsed    5.4 min
Chunk   66 | S1   132000 | Candidates     428372 | Matches     118809 | Chunk    5.4s | RAM free  7.13 GB | Elapsed    5.5 min
Chunk   67 | S1   134000 | Candidates     434601 | Matches     120652 | Chunk    4.1s | RAM free  7.13 GB | Elapsed    5.5 min
Chunk   68 | S1   136000 | Candidates     441440 | Matches     122460 | Chunk    4.1s | RAM free  7.12 GB | Elapsed    5.6 min
Chunk   69 | S1   138000 | Candidates     448050 | Matches     124232 | Chunk    4.5s | RAM free  7.11 GB | Elapsed    5.7 min
Chunk   70 | S1   140000 | Candidates     453894 | Matches     126032 | Chunk    4.7s | RAM free  7.10 GB | Elapsed    5.7 min
Chunk   71 | S1   142000 | Candidates     460424 | Matches     127842 | Chunk    4.0s | RAM free  7.10 GB | Elapsed    5.8 min
Chunk   72 | S1   144000 | Candidates     467616 | Matches     129633 | Chunk    4.2s | RAM free  7.10 GB | Elapsed    5.9 min
Chunk   73 | S1   146000 | Candidates     473220 | Matches     131374 | Chunk    5.0s | RAM free  7.10 GB | Elapsed    6.0 min
Chunk   74 | S1   148000 | Candidates     480673 | Matches     133244 | Chunk    4.3s | RAM free  7.10 GB | Elapsed    6.0 min
Chunk   75 | S1   150000 | Candidates     487147 | Matches     135082 | Chunk    4.0s | RAM free  7.10 GB | Elapsed    6.1 min
Chunk   76 | S1   152000 | Candidates     493528 | Matches     136917 | Chunk    4.7s | RAM free  7.10 GB | Elapsed    6.2 min
Chunk   77 | S1   154000 | Candidates     500356 | Matches     138753 | Chunk    4.5s | RAM free  7.12 GB | Elapsed    6.3 min
Chunk   78 | S1   156000 | Candidates     506675 | Matches     140549 | Chunk    4.0s | RAM free  7.11 GB | Elapsed    6.3 min
Chunk   79 | S1   158000 | Candidates     514229 | Matches     142470 | Chunk    4.4s | RAM free  7.10 GB | Elapsed    6.4 min
Chunk   80 | S1   160000 | Candidates     520169 | Matches     144191 | Chunk    4.9s | RAM free  7.10 GB | Elapsed    6.5 min
Chunk   81 | S1   162000 | Candidates     526913 | Matches     146015 | Chunk    4.1s | RAM free  7.10 GB | Elapsed    6.5 min
Chunk   82 | S1   164000 | Candidates     533100 | Matches     147835 | Chunk    4.1s | RAM free  7.10 GB | Elapsed    6.6 min
Chunk   83 | S1   166000 | Candidates     539489 | Matches     149634 | Chunk    5.0s | RAM free  7.11 GB | Elapsed    6.7 min
Chunk   84 | S1   168000 | Candidates     545596 | Matches     151512 | Chunk    4.1s | RAM free  7.11 GB | Elapsed    6.8 min
Chunk   85 | S1   170000 | Candidates     551737 | Matches     153412 | Chunk    3.9s | RAM free  7.11 GB | Elapsed    6.8 min
Chunk   86 | S1   172000 | Candidates     558117 | Matches     155302 | Chunk    4.4s | RAM free  7.10 GB | Elapsed    6.9 min
Chunk   87 | S1   174000 | Candidates     565259 | Matches     157117 | Chunk    4.9s | RAM free  7.11 GB | Elapsed    7.0 min
Chunk   88 | S1   176000 | Candidates     571712 | Matches     159034 | Chunk    4.0s | RAM free  7.11 GB | Elapsed    7.1 min
Chunk   89 | S1   178000 | Candidates     577959 | Matches     160905 | Chunk    3.9s | RAM free  7.11 GB | Elapsed    7.1 min
Chunk   90 | S1   180000 | Candidates     584980 | Matches     162771 | Chunk    5.5s | RAM free  7.09 GB | Elapsed    7.2 min
Chunk   91 | S1   182000 | Candidates     591246 | Matches     164561 | Chunk    4.0s | RAM free  7.09 GB | Elapsed    7.3 min
Chunk   92 | S1   184000 | Candidates     597756 | Matches     166421 | Chunk    4.0s | RAM free  7.12 GB | Elapsed    7.3 min
Chunk   93 | S1   186000 | Candidates     604023 | Matches     168171 | Chunk    4.5s | RAM free  7.10 GB | Elapsed    7.4 min
Chunk   94 | S1   188000 | Candidates     610613 | Matches     170023 | Chunk    4.6s | RAM free  7.10 GB | Elapsed    7.5 min
Chunk   95 | S1   190000 | Candidates     617106 | Matches     171795 | Chunk    3.9s | RAM free  7.10 GB | Elapsed    7.6 min
Chunk   96 | S1   192000 | Candidates     623640 | Matches     173636 | Chunk    4.0s | RAM free  7.09 GB | Elapsed    7.6 min
Chunk   97 | S1   194000 | Candidates     630791 | Matches     175438 | Chunk    5.5s | RAM free  7.10 GB | Elapsed    7.7 min
Chunk   98 | S1   196000 | Candidates     637159 | Matches     177282 | Chunk    4.1s | RAM free  7.10 GB | Elapsed    7.8 min
Chunk   99 | S1   198000 | Candidates     644215 | Matches     179141 | Chunk    4.2s | RAM free  7.10 GB | Elapsed    7.9 min
Chunk  100 | S1   200000 | Candidates     651086 | Matches     180943 | Chunk    5.0s | RAM free  7.09 GB | Elapsed    7.9 min
Chunk  101 | S1   202000 | Candidates     658439 | Matches     182750 | Chunk    4.4s | RAM free  7.09 GB | Elapsed    8.0 min
Chunk  102 | S1   204000 | Candidates     664589 | Matches     184539 | Chunk    4.0s | RAM free  7.09 GB | Elapsed    8.1 min
Chunk  103 | S1   206000 | Candidates     671259 | Matches     186322 | Chunk    4.4s | RAM free  7.12 GB | Elapsed    8.2 min
Chunk  104 | S1   208000 | Candidates     677417 | Matches     188047 | Chunk    4.7s | RAM free  7.10 GB | Elapsed    8.2 min
Chunk  105 | S1   210000 | Candidates     683638 | Matches     189884 | Chunk    4.0s | RAM free  7.10 GB | Elapsed    8.3 min
Chunk  106 | S1   212000 | Candidates     690494 | Matches     191671 | Chunk    4.0s | RAM free  7.10 GB | Elapsed    8.4 min
Chunk  107 | S1   214000 | Candidates     696870 | Matches     193430 | Chunk    5.1s | RAM free  7.09 GB | Elapsed    8.5 min
Chunk  108 | S1   216000 | Candidates     703525 | Matches     195376 | Chunk    4.0s | RAM free  7.09 GB | Elapsed    8.5 min
Chunk  109 | S1   218000 | Candidates     710786 | Matches     197210 | Chunk    4.1s | RAM free  7.09 GB | Elapsed    8.6 min
Chunk  110 | S1   220000 | Candidates     717444 | Matches     198935 | Chunk    4.6s | RAM free  7.09 GB | Elapsed    8.7 min
Chunk  111 | S1   222000 | Candidates     723350 | Matches     200750 | Chunk    4.3s | RAM free  7.11 GB | Elapsed    8.7 min
Chunk  112 | S1   224000 | Candidates     730080 | Matches     202587 | Chunk    4.1s | RAM free  7.11 GB | Elapsed    8.8 min
Chunk  113 | S1   226000 | Candidates     736566 | Matches     204298 | Chunk    4.1s | RAM free  7.10 GB | Elapsed    8.9 min
Chunk  114 | S1   228000 | Candidates     743452 | Matches     206136 | Chunk    5.2s | RAM free  7.11 GB | Elapsed    9.0 min
Chunk  115 | S1   230000 | Candidates     749794 | Matches     207902 | Chunk    3.8s | RAM free  7.11 GB | Elapsed    9.0 min
Chunk  116 | S1   232000 | Candidates     756521 | Matches     209716 | Chunk    4.1s | RAM free  7.11 GB | Elapsed    9.1 min
Chunk  117 | S1   234000 | Candidates     762518 | Matches     211440 | Chunk    4.5s | RAM free  7.09 GB | Elapsed    9.2 min
Chunk  118 | S1   236000 | Candidates     768858 | Matches     213379 | Chunk    4.5s | RAM free  7.11 GB | Elapsed    9.2 min
Chunk  119 | S1   238000 | Candidates     775272 | Matches     215171 | Chunk    4.0s | RAM free  7.10 GB | Elapsed    9.3 min
Chunk  120 | S1   240000 | Candidates     781402 | Matches     216970 | Chunk    4.1s | RAM free  7.11 GB | Elapsed    9.4 min
Chunk  121 | S1   242000 | Candidates     787663 | Matches     218710 | Chunk    5.0s | RAM free  7.12 GB | Elapsed    9.5 min
Chunk  122 | S1   244000 | Candidates     794568 | Matches     220515 | Chunk    4.0s | RAM free  7.11 GB | Elapsed    9.5 min
Chunk  123 | S1   246000 | Candidates     800525 | Matches     222302 | Chunk    3.8s | RAM free  7.11 GB | Elapsed    9.6 min
Chunk  124 | S1   248000 | Candidates     807758 | Matches     224113 | Chunk    5.1s | RAM free  7.09 GB | Elapsed    9.7 min
Chunk  125 | S1   250000 | Candidates     814270 | Matches     225845 | Chunk    4.4s | RAM free  7.11 GB | Elapsed    9.8 min
Chunk  126 | S1   252000 | Candidates     820669 | Matches     227679 | Chunk    4.0s | RAM free  7.11 GB | Elapsed    9.8 min
Chunk  127 | S1   254000 | Candidates     826730 | Matches     229465 | Chunk    4.2s | RAM free  7.09 GB | Elapsed    9.9 min
Chunk  128 | S1   256000 | Candidates     832945 | Matches     231252 | Chunk    4.9s | RAM free  7.10 GB | Elapsed   10.0 min
Chunk  129 | S1   258000 | Candidates     839067 | Matches     233074 | Chunk    3.8s | RAM free  7.10 GB | Elapsed   10.0 min
Chunk  130 | S1   260000 | Candidates     845048 | Matches     234826 | Chunk    3.9s | RAM free  7.10 GB | Elapsed   10.1 min
Chunk  131 | S1   262000 | Candidates     851221 | Matches     236615 | Chunk    4.9s | RAM free  7.09 GB | Elapsed   10.2 min
Chunk  132 | S1   264000 | Candidates     858381 | Matches     238371 | Chunk    4.4s | RAM free  7.09 GB | Elapsed   10.3 min
Chunk  133 | S1   266000 | Candidates     864143 | Matches     240204 | Chunk    3.8s | RAM free  7.09 GB | Elapsed   10.3 min
Chunk  134 | S1   268000 | Candidates     869416 | Matches     241943 | Chunk    3.9s | RAM free  7.09 GB | Elapsed   10.4 min
Chunk  135 | S1   270000 | Candidates     876989 | Matches     243759 | Chunk    5.3s | RAM free  7.10 GB | Elapsed   10.5 min
Chunk  136 | S1   272000 | Candidates     883301 | Matches     245571 | Chunk    4.0s | RAM free  7.10 GB | Elapsed   10.5 min
Chunk  137 | S1   274000 | Candidates     889686 | Matches     247449 | Chunk    4.0s | RAM free  7.09 GB | Elapsed   10.6 min
Chunk  138 | S1   276000 | Candidates     896300 | Matches     249221 | Chunk    5.0s | RAM free  7.11 GB | Elapsed   10.7 min
Chunk  139 | S1   278000 | Candidates     902428 | Matches     251122 | Chunk    4.2s | RAM free  7.11 GB | Elapsed   10.8 min
Chunk  140 | S1   280000 | Candidates     909304 | Matches     252870 | Chunk    4.2s | RAM free  7.10 GB | Elapsed   10.8 min
Chunk  141 | S1   282000 | Candidates     915694 | Matches     254667 | Chunk    4.5s | RAM free  7.11 GB | Elapsed   10.9 min
Chunk  142 | S1   284000 | Candidates     921516 | Matches     256503 | Chunk    4.6s | RAM free  7.11 GB | Elapsed   11.0 min
Chunk  143 | S1   286000 | Candidates     928227 | Matches     258336 | Chunk    4.2s | RAM free  7.11 GB | Elapsed   11.0 min
Chunk  144 | S1   288000 | Candidates     934798 | Matches     260046 | Chunk    3.9s | RAM free  7.10 GB | Elapsed   11.1 min
Chunk  145 | S1   290000 | Candidates     941033 | Matches     261836 | Chunk    5.1s | RAM free  7.10 GB | Elapsed   11.2 min
Chunk  146 | S1   292000 | Candidates     947047 | Matches     263620 | Chunk    3.9s | RAM free  7.10 GB | Elapsed   11.3 min
Chunk  147 | S1   294000 | Candidates     953767 | Matches     265469 | Chunk    4.0s | RAM free  7.09 GB | Elapsed   11.3 min
Chunk  148 | S1   296000 | Candidates     961250 | Matches     267300 | Chunk    4.9s | RAM free  7.10 GB | Elapsed   11.4 min
Chunk  149 | S1   298000 | Candidates     968110 | Matches     269145 | Chunk    4.6s | RAM free  7.09 GB | Elapsed   11.5 min
Chunk  150 | S1   300000 | Candidates     974957 | Matches     271105 | Chunk    4.0s | RAM free  7.09 GB | Elapsed   11.6 min
Chunk  151 | S1   302000 | Candidates     981557 | Matches     272911 | Chunk    4.2s | RAM free  7.09 GB | Elapsed   11.6 min
Chunk  152 | S1   304000 | Candidates     988221 | Matches     274802 | Chunk    5.1s | RAM free  7.12 GB | Elapsed   11.7 min
Chunk  153 | S1   306000 | Candidates     993939 | Matches     276658 | Chunk    3.9s | RAM free  7.12 GB | Elapsed   11.8 min
Chunk  154 | S1   308000 | Candidates    1000923 | Matches     278471 | Chunk    4.1s | RAM free  7.11 GB | Elapsed   11.8 min
Chunk  155 | S1   310000 | Candidates    1006942 | Matches     280184 | Chunk    4.7s | RAM free  7.09 GB | Elapsed   11.9 min
Chunk  156 | S1   312000 | Candidates    1014856 | Matches     282088 | Chunk    4.8s | RAM free  7.12 GB | Elapsed   12.0 min

In [ ]:
# ============================================================
# STEP 5 — CLEAN S2 + LOAD S3
# ============================================================

import gc
import pickle
import psutil
import pandas as pd

# Free S2 memory
del s2
del s2_name_index
del s2_addr_index
del s2_name_freq
del s2_addr_freq

gc.collect()

vm = psutil.virtual_memory()
print(f"After S2 cleanup: {vm.available/1024**3:.2f} GB RAM free")

# ------------------------------------------------------------
# Load S3
# ------------------------------------------------------------
S3_PATH = f"{TEST_DIR}/test_source3.tsv"

s3 = pd.read_csv(
    S3_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("✅ S3 loaded")
print("S3 shape:", s3.shape)

# ------------------------------------------------------------
# Load ONLY S3 indexes
# ------------------------------------------------------------
with open(f"{INDEX_DIR}/s3_name_index.pkl", "rb") as f:
    s3_name_index = pickle.load(f)

with open(f"{INDEX_DIR}/s3_addr_index.pkl", "rb") as f:
    s3_addr_index = pickle.load(f)

with open(f"{INDEX_DIR}/s3_name_freq.pkl", "rb") as f:
    s3_name_freq = pickle.load(f)

with open(f"{INDEX_DIR}/s3_addr_freq.pkl", "rb") as f:
    s3_addr_freq = pickle.load(f)

print("✅ S3 indexes loaded")

gc.collect()

vm = psutil.virtual_memory()
print(f"After S3 indexes: {vm.available/1024**3:.2f} GB RAM free")

print("S3 rows:", len(s3))
print("S3 name index entries:", len(s3_name_index))
print("S3 address index entries:", len(s3_addr_index))

After S2 cleanup: 9.01 GB RAM free
✅ S3 loaded
S3 shape: (5082316, 4)
✅ S3 indexes loaded
After S3 indexes: 6.08 GB RAM free
S3 rows: 5082316
S3 name index entries: 918689
S3 address index entries: 1296266

In [ ]:
# ============================================================
# STEP 6 — RAM-SAFE S3 PRODUCTION
# V5 MODEL | THRESHOLD 0.60
# ============================================================

import os
import re
import csv
import gc
import time
import psutil
import numpy as np
import pandas as pd
import unicodedata

from rapidfuzz.fuzz import ratio

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
S3_PATH = f"{TEST_DIR}/test_source3.tsv"
S3_WORK = f"{WORK_DIR}/s3_results.tsv"

S1_PATH = f"{TEST_DIR}/test_source1.tsv"

THRESHOLD = 0.60
CHUNK_SIZE = 2000

# ------------------------------------------------------------
# Safety check
# ------------------------------------------------------------
if os.path.exists(S3_WORK):
    raise RuntimeError(
        f"""
Existing S3 output found:

{S3_WORK}

This code will NOT overwrite it.
If this is an old/incomplete run, delete it first.
"""
    )

# ------------------------------------------------------------
# RAM helper
# ------------------------------------------------------------
def show_ram(label=""):
    gc.collect()
    vm = psutil.virtual_memory()
    print(
        f"💾 {label} RAM available: "
        f"{vm.available/1024**3:.2f} GB / "
        f"{vm.total/1024**3:.2f} GB"
    )

# ------------------------------------------------------------
# NORMALIZATION
# Same normalization used by V5 pipeline
# ------------------------------------------------------------
def normalize_advanced(text):

    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(
        r"[^\w\s]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


def tokens(text):

    if not text:
        return set()

    return set(text.split())


# ============================================================
# V5 FEATURE BUILDER — 20 FEATURES
# ============================================================

def make_features(
    s1_name,
    s1_addr,
    s1_country,
    s3_name,
    s3_addr,
    s3_country
):

    n1 = normalize_advanced(s1_name)
    a1 = normalize_advanced(s1_addr)

    n3 = normalize_advanced(s3_name)
    a3 = normalize_advanced(s3_addr)

    # Tokens
    nt1 = tokens(n1)
    nt3 = tokens(n3)

    at1 = tokens(a1)
    at3 = tokens(a3)

    # Shared tokens
    name_shared = len(nt1 & nt3)
    addr_shared = len(at1 & at3)

    # Shared address numbers
    nums1 = set(
        re.findall(
            r"\b\d+\b",
            a1
        )
    )

    nums3 = set(
        re.findall(
            r"\b\d+\b",
            a3
        )
    )

    shared_addr_numbers = len(
        nums1 & nums3
    )

    # Similarity
    name_sim = ratio(
        n1,
        n3
    ) / 100.0

    addr_sim = ratio(
        a1,
        a3
    ) / 100.0

    # Lengths
    name_len_1 = len(n1)
    name_len_3 = len(n3)

    addr_len_1 = len(a1)
    addr_len_3 = len(a3)

    name_len_diff = abs(
        name_len_1 - name_len_3
    )

    addr_len_diff = abs(
        addr_len_1 - addr_len_3
    )

    name_len_ratio = (
        min(name_len_1, name_len_3)
        /
        max(name_len_1, name_len_3)
        if max(name_len_1, name_len_3) > 0
        else 1.0
    )

    addr_len_ratio = (
        min(addr_len_1, addr_len_3)
        /
        max(addr_len_1, addr_len_3)
        if max(addr_len_1, addr_len_3) > 0
        else 1.0
    )

    # V5 engineered features
    similarity_gap = abs(
        name_sim - addr_sim
    )

    max_similarity = max(
        name_sim,
        addr_sim
    )

    similarity_product = (
        name_sim * addr_sim
    )

    token_overlap_gap = abs(
        name_shared - addr_shared
    )

    # EXACT 20-FEATURE ORDER
    return [
        # 1
        int(n1 == n3),

        # 2
        int(a1 == a3),

        # 3
        int(
            str(s1_country).strip().lower()
            ==
            str(s3_country).strip().lower()
        ),

        # 4
        name_sim,

        # 5
        addr_sim,

        # 6
        name_shared /
        max(len(nt1), len(nt3), 1),

        # 7
        addr_shared /
        max(len(at1), len(at3), 1),

        # 8
        name_shared /
        max(len(nt1 | nt3), 1),

        # 9
        addr_shared /
        max(len(at1 | at3), 1),

        # 10
        name_shared,

        # 11
        addr_shared,

        # 12
        shared_addr_numbers,

        # 13
        name_len_diff,

        # 14
        addr_len_diff,

        # 15
        name_len_ratio,

        # 16
        addr_len_ratio,

        # 17
        similarity_gap,

        # 18
        max_similarity,

        # 19
        similarity_product,

        # 20
        token_overlap_gap
    ]


# ============================================================
# S3 CANDIDATE GENERATOR
# SAME RULES USED FOR S2
# ============================================================

def generate_candidates_s3(
    s1_name,
    s1_addr,
    s1_country
):

    # Normalize S1
    n1 = normalize_advanced(
        s1_name
    )

    a1 = normalize_advanced(
        s1_addr
    )

    name_tok = tokens(n1)
    addr_tok = tokens(a1)

    # --------------------------------------------------------
    # Candidate counts
    # --------------------------------------------------------
    candidate_counts = {}

    # --------------------------------------------------------
    # NAME RARE TOKEN BLOCK
    # Frequency <= 500
    # --------------------------------------------------------
    for tok in name_tok:

        if s3_name_freq.get(
            tok,
            10**9
        ) <= 500:

            ids = s3_name_index.get(
                tok
            )

            if ids is not None:

                for idx in ids:

                    candidate_counts[idx] = (
                        candidate_counts.get(
                            idx,
                            0
                        ) + 1
                    )

    # --------------------------------------------------------
    # ADDRESS RARE TOKEN BLOCK
    # Frequency <= 500
    # --------------------------------------------------------
    for tok in addr_tok:

        if s3_addr_freq.get(
            tok,
            10**9
        ) <= 500:

            ids = s3_addr_index.get(
                tok
            )

            if ids is not None:

                # FIXED:
                # idx comes from this loop
                for idx in ids:

                    candidate_counts[idx] = (
                        candidate_counts.get(
                            idx,
                            0
                        ) + 1
                    )

    # --------------------------------------------------------
    # Require >= 2 shared rare tokens
    # --------------------------------------------------------
    candidate_indices = [
        idx
        for idx, count
        in candidate_counts.items()
        if count >= 2
    ]

    if not candidate_indices:
        return []

    # --------------------------------------------------------
    # Final hybrid candidate rules
    #
    # 1. exact name + country
    # 2. exact address + country
    # 3. >=2 shared name tokens + name similarity >= 0.60
    # 4. >=3 shared address tokens
    # 5. >=2 shared address tokens + address similarity >= 0.30
    # --------------------------------------------------------

    final_indices = []

    s1_country_norm = (
        str(s1_country)
        .strip()
        .lower()
    )

    for idx in candidate_indices:

        row = s3.iloc[idx]

        s3_name = row[
            "business_name"
        ]

        s3_addr = row[
            "business_address"
        ]

        s3_country = row[
            "country"
        ]

        # Normalize candidate
        n3 = normalize_advanced(
            s3_name
        )

        a3 = normalize_advanced(
            s3_addr
        )

        # Candidate tokens
        nt3 = tokens(n3)
        at3 = tokens(a3)

        # Shared token counts
        name_shared = len(
            name_tok & nt3
        )

        addr_shared = len(
            addr_tok & at3
        )

        # Country
        country_same = (
            s1_country_norm
            ==
            str(s3_country)
            .strip()
            .lower()
        )

        # Exact
        name_exact = (
            n1 == n3
        )

        addr_exact = (
            a1 == a3
        )

        # Similarity
        name_sim = ratio(
            n1,
            n3
        ) / 100.0

        addr_sim = ratio(
            a1,
            a3
        ) / 100.0

        # Final rules
        keep = (
            # Rule 1
            (
                name_exact
                and
                country_same
            )

            or

            # Rule 2
            (
                addr_exact
                and
                country_same
            )

            or

            # Rule 3
            (
                name_shared >= 2
                and
                name_sim >= 0.60
            )

            or

            # Rule 4
            (
                addr_shared >= 3
            )

            or

            # Rule 5
            (
                addr_shared >= 2
                and
                addr_sim >= 0.30
            )
        )

        if keep:
            final_indices.append(
                idx
            )

    return final_indices


# ============================================================
# VERIFY S3 IS LOADED
# ============================================================

print("============================================================")
print("S3 PRODUCTION CHECK")
print("============================================================")

print(
    "S3 rows:",
    len(s3)
)

print(
    "S3 name index:",
    len(s3_name_index)
)

print(
    "S3 address index:",
    len(s3_addr_index)
)

print(
    "S3 name frequency:",
    len(s3_name_freq)
)

print(
    "S3 address frequency:",
    len(s3_addr_freq)
)

print(
    "Threshold:",
    THRESHOLD
)

print(
    "Chunk size:",
    CHUNK_SIZE
)

show_ram("Before smoke test")


# ============================================================
# SMALL S3 SMOKE TEST
# ============================================================

print("\n🔎 Running S3 smoke test on first 100 S1 rows...")

smoke_candidates = 0
smoke_matches = 0

smoke_s1 = pd.read_csv(
    S1_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=100
)

for _, row in smoke_s1.iterrows():

    candidate_indices = (
        generate_candidates_s3(
            row["business_name"],
            row["business_address"],
            row["country"]
        )
    )

    smoke_candidates += len(
        candidate_indices
    )

    if candidate_indices:

        feature_rows = []
        candidate_ids = []

        for idx in candidate_indices:

            s3_row = s3.iloc[idx]

            feature_rows.append(
                make_features(
                    row["business_name"],
                    row["business_address"],
                    row["country"],
                    s3_row["business_name"],
                    s3_row["business_address"],
                    s3_row["country"]
                )
            )

            candidate_ids.append(
                str(
                    s3_row["entity_id"]
                )
            )

        X_smoke = np.asarray(
            feature_rows,
            dtype=np.float32
        )

        probs_smoke = (
            model.predict_proba(
                X_smoke
            )[:, 1]
        )

        smoke_matches += int(
            np.sum(
                probs_smoke >= THRESHOLD
            )
        )

        del X_smoke
        del probs_smoke
        del feature_rows
        del candidate_ids


del smoke_s1
gc.collect()

print(
    "✅ Smoke test complete"
)

print(
    "First 100 S1 candidates:",
    smoke_candidates
)

print(
    "First 100 S1 predicted matches:",
    smoke_matches
)

show_ram("After smoke test")


# ============================================================
# CREATE S3 OUTPUT
# ============================================================

with open(
    S3_WORK,
    "w",
    newline="",
    encoding="utf-8"
) as f:

    writer = csv.writer(
        f,
        delimiter="\t"
    )

    writer.writerow([
        "source1_entity_id",
        "candidate_entity_ids",
        "matched_entity_ids"
    ])


# ============================================================
# FULL S3 PRODUCTION
# ============================================================

total_s1 = 0
total_candidates = 0
total_matches = 0

start_time = time.time()

print("\n============================================================")
print("🚀 STARTING FULL S3 PRODUCTION")
print("============================================================")

for chunk_no, s1_chunk in enumerate(
    pd.read_csv(
        S1_PATH,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    chunk_start = time.time()

    output_rows = []

    # --------------------------------------------------------
    # Process each S1 entity
    # --------------------------------------------------------
    for _, row in s1_chunk.iterrows():

        s1_id = row[
            "entity_id"
        ]

        s1_name = row[
            "business_name"
        ]

        s1_addr = row[
            "business_address"
        ]

        s1_country = row[
            "country"
        ]

        # ----------------------------------------------------
        # Candidate generation
        # ----------------------------------------------------
        candidate_indices = (
            generate_candidates_s3(
                s1_name,
                s1_addr,
                s1_country
            )
        )

        candidate_ids = []
        matched_ids = []

        # ----------------------------------------------------
        # V5 prediction
        # ----------------------------------------------------
        if candidate_indices:

            feature_rows = []

            for idx in candidate_indices:

                s3_row = s3.iloc[idx]

                feature_rows.append(
                    make_features(
                        s1_name,
                        s1_addr,
                        s1_country,
                        s3_row[
                            "business_name"
                        ],
                        s3_row[
                            "business_address"
                        ],
                        s3_row[
                            "country"
                        ]
                    )
                )

                candidate_ids.append(
                    str(
                        s3_row[
                            "entity_id"
                        ]
                    )
                )

            # Convert only current S1 candidates
            # into float32 matrix
            X = np.asarray(
                feature_rows,
                dtype=np.float32
            )

            # CatBoost prediction
            probs = model.predict_proba(
                X
            )[:, 1]

            # Threshold = 0.60
            for cid, p in zip(
                candidate_ids,
                probs
            ):

                if p >= THRESHOLD:
                    matched_ids.append(
                        cid
                    )

            # Free temporary prediction memory
            del X
            del probs
            del feature_rows

        # ----------------------------------------------------
        # Deduplicate
        # ----------------------------------------------------
        candidate_ids = list(
            dict.fromkeys(
                candidate_ids
            )
        )

        matched_ids = list(
            dict.fromkeys(
                matched_ids
            )
        )

        # ----------------------------------------------------
        # Store one S1 row
        # ----------------------------------------------------
        output_rows.append([
            s1_id,
            ",".join(
                candidate_ids
            ),
            ",".join(
                matched_ids
            )
        ])

        total_s1 += 1
        total_candidates += len(
            candidate_ids
        )
        total_matches += len(
            matched_ids
        )

    # --------------------------------------------------------
    # Write chunk immediately
    # --------------------------------------------------------
    with open(
        S3_WORK,
        "a",
        newline="",
        encoding="utf-8"
    ) as f:

        writer = csv.writer(
            f,
            delimiter="\t"
        )

        writer.writerows(
            output_rows
        )

    # --------------------------------------------------------
    # Free chunk memory
    # --------------------------------------------------------
    del output_rows
    del s1_chunk

    gc.collect()

    # --------------------------------------------------------
    # Progress
    # --------------------------------------------------------
    elapsed = (
        time.time()
        -
        start_time
    )

    chunk_time = (
        time.time()
        -
        chunk_start
    )

    vm = psutil.virtual_memory()

    print(
        f"Chunk {chunk_no:4d} | "
        f"S1 {total_s1:8d} | "
        f"Candidates {total_candidates:10d} | "
        f"Matches {total_matches:10d} | "
        f"Chunk {chunk_time:6.1f}s | "
        f"RAM free {vm.available/1024**3:5.2f} GB | "
        f"Elapsed {elapsed/60:6.1f} min"
    )


# ============================================================
# FINAL S3 SUMMARY
# ============================================================

print("\n============================================================")
print("✅ S3 PRODUCTION COMPLETE")
print("============================================================")

print(
    "S1 processed:",
    total_s1
)

print(
    "Expected S1:",
    1732544
)

print(
    "Total candidates:",
    total_candidates
)

print(
    "Total matches:",
    total_matches
)

print(
    "Avg candidates/S1:",
    total_candidates /
    max(total_s1, 1)
)

print(
    "Avg matches/S1:",
    total_matches /
    max(total_s1, 1)
)

print(
    "Output:",
    S3_WORK
)

show_ram("After S3 production")

# ============================================================
# FINAL SAFETY CHECK
# ============================================================

if total_s1 != 1732544:

    print(
        "\n⚠️ WARNING: S1 count is not 1,732,544."
    )

else:

    print(
        "\n✅ All 1,732,544 S1 entities processed."
    )

============================================================
S3 PRODUCTION CHECK
============================================================
S3 rows: 5082316
S3 name index: 918689
S3 address index: 1296266
S3 name frequency: 918689
S3 address frequency: 1296266
Threshold: 0.6
Chunk size: 2000
💾 Before smoke test RAM available: 6.07 GB / 12.67 GB

🔎 Running S3 smoke test on first 100 S1 rows...
✅ Smoke test complete
First 100 S1 candidates: 399
First 100 S1 predicted matches: 61
💾 After smoke test RAM available: 6.07 GB / 12.67 GB

============================================================
🚀 STARTING FULL S3 PRODUCTION
============================================================
Chunk    1 | S1     2000 | Candidates       6428 | Matches       1598 | Chunk    4.2s | RAM free  6.06 GB | Elapsed    0.1 min
Chunk    2 | S1     4000 | Candidates      12398 | Matches       3289 | Chunk    3.7s | RAM free  6.06 GB | Elapsed    0.1 min
Chunk    3 | S1     6000 | Candidates      19228 | Matches       4850 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    0.2 min
Chunk    4 | S1     8000 | Candidates      25240 | Matches       6503 | Chunk    4.7s | RAM free  6.06 GB | Elapsed    0.3 min
Chunk    5 | S1    10000 | Candidates      31334 | Matches       8193 | Chunk    3.7s | RAM free  6.07 GB | Elapsed    0.3 min
Chunk    6 | S1    12000 | Candidates      37352 | Matches       9811 | Chunk    3.7s | RAM free  6.06 GB | Elapsed    0.4 min
Chunk    7 | S1    14000 | Candidates      43990 | Matches      11417 | Chunk    4.6s | RAM free  6.06 GB | Elapsed    0.5 min
Chunk    8 | S1    16000 | Candidates      50147 | Matches      13040 | Chunk    4.2s | RAM free  6.06 GB | Elapsed    0.5 min
Chunk    9 | S1    18000 | Candidates      56423 | Matches      14662 | Chunk    3.9s | RAM free  6.06 GB | Elapsed    0.6 min
Chunk   10 | S1    20000 | Candidates      62395 | Matches      16401 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    0.7 min
Chunk   11 | S1    22000 | Candidates      68981 | Matches      18027 | Chunk    4.9s | RAM free  6.07 GB | Elapsed    0.8 min
Chunk   12 | S1    24000 | Candidates      75885 | Matches      19676 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    0.8 min
Chunk   13 | S1    26000 | Candidates      82019 | Matches      21320 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    0.9 min
Chunk   14 | S1    28000 | Candidates      87778 | Matches      23008 | Chunk    5.6s | RAM free  6.07 GB | Elapsed    1.0 min
Chunk   15 | S1    30000 | Candidates      93906 | Matches      24704 | Chunk    4.4s | RAM free  6.06 GB | Elapsed    1.1 min
Chunk   16 | S1    32000 | Candidates     100539 | Matches      26422 | Chunk    4.5s | RAM free  6.06 GB | Elapsed    1.1 min
Chunk   17 | S1    34000 | Candidates     106567 | Matches      28175 | Chunk    5.5s | RAM free  6.07 GB | Elapsed    1.2 min
Chunk   18 | S1    36000 | Candidates     113180 | Matches      29851 | Chunk    4.7s | RAM free  6.06 GB | Elapsed    1.3 min
Chunk   19 | S1    38000 | Candidates     119349 | Matches      31559 | Chunk    4.2s | RAM free  6.07 GB | Elapsed    1.4 min
Chunk   20 | S1    40000 | Candidates     125878 | Matches      33200 | Chunk    5.4s | RAM free  6.07 GB | Elapsed    1.5 min
Chunk   21 | S1    42000 | Candidates     132570 | Matches      34876 | Chunk    5.2s | RAM free  6.06 GB | Elapsed    1.6 min
Chunk   22 | S1    44000 | Candidates     139352 | Matches      36555 | Chunk    6.9s | RAM free  6.06 GB | Elapsed    1.7 min
Chunk   23 | S1    46000 | Candidates     145419 | Matches      38194 | Chunk    5.8s | RAM free  6.07 GB | Elapsed    1.8 min
Chunk   24 | S1    48000 | Candidates     151926 | Matches      39820 | Chunk    4.5s | RAM free  6.07 GB | Elapsed    1.8 min
Chunk   25 | S1    50000 | Candidates     158594 | Matches      41559 | Chunk    4.5s | RAM free  6.07 GB | Elapsed    1.9 min
Chunk   26 | S1    52000 | Candidates     165029 | Matches      43311 | Chunk    5.8s | RAM free  6.07 GB | Elapsed    2.0 min
Chunk   27 | S1    54000 | Candidates     171889 | Matches      45001 | Chunk    4.5s | RAM free  6.06 GB | Elapsed    2.1 min
Chunk   28 | S1    56000 | Candidates     178288 | Matches      46578 | Chunk    4.4s | RAM free  6.06 GB | Elapsed    2.2 min
Chunk   29 | S1    58000 | Candidates     184558 | Matches      48262 | Chunk    5.4s | RAM free  6.06 GB | Elapsed    2.3 min
Chunk   30 | S1    60000 | Candidates     191087 | Matches      50019 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    2.3 min
Chunk   31 | S1    62000 | Candidates     198854 | Matches      51710 | Chunk    4.3s | RAM free  6.06 GB | Elapsed    2.4 min
Chunk   32 | S1    64000 | Candidates     205628 | Matches      53309 | Chunk    5.1s | RAM free  6.07 GB | Elapsed    2.5 min
Chunk   33 | S1    66000 | Candidates     212597 | Matches      54984 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    2.5 min
Chunk   34 | S1    68000 | Candidates     219200 | Matches      56723 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    2.6 min
Chunk   35 | S1    70000 | Candidates     225446 | Matches      58363 | Chunk    4.5s | RAM free  6.07 GB | Elapsed    2.7 min
Chunk   36 | S1    72000 | Candidates     231874 | Matches      60007 | Chunk    4.6s | RAM free  6.06 GB | Elapsed    2.8 min
Chunk   37 | S1    74000 | Candidates     238193 | Matches      61704 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    2.8 min
Chunk   38 | S1    76000 | Candidates     244988 | Matches      63463 | Chunk    4.1s | RAM free  6.07 GB | Elapsed    2.9 min
Chunk   39 | S1    78000 | Candidates     252021 | Matches      65197 | Chunk    5.3s | RAM free  6.06 GB | Elapsed    3.0 min
Chunk   40 | S1    80000 | Candidates     257972 | Matches      66901 | Chunk    3.9s | RAM free  6.06 GB | Elapsed    3.1 min
Chunk   41 | S1    82000 | Candidates     264317 | Matches      68518 | Chunk    3.9s | RAM free  6.06 GB | Elapsed    3.1 min
Chunk   42 | S1    84000 | Candidates     271149 | Matches      70312 | Chunk    5.1s | RAM free  6.07 GB | Elapsed    3.2 min
Chunk   43 | S1    86000 | Candidates     278326 | Matches      72005 | Chunk    4.3s | RAM free  6.06 GB | Elapsed    3.3 min
Chunk   44 | S1    88000 | Candidates     284883 | Matches      73771 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    3.3 min
Chunk   45 | S1    90000 | Candidates     290656 | Matches      75470 | Chunk    4.4s | RAM free  6.06 GB | Elapsed    3.4 min
Chunk   46 | S1    92000 | Candidates     296925 | Matches      77050 | Chunk    4.5s | RAM free  6.06 GB | Elapsed    3.5 min
Chunk   47 | S1    94000 | Candidates     302865 | Matches      78696 | Chunk    3.8s | RAM free  6.06 GB | Elapsed    3.6 min
Chunk   48 | S1    96000 | Candidates     308992 | Matches      80416 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    3.6 min
Chunk   49 | S1    98000 | Candidates     315610 | Matches      82132 | Chunk    5.2s | RAM free  6.06 GB | Elapsed    3.7 min
Chunk   50 | S1   100000 | Candidates     321949 | Matches      83861 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    3.8 min
Chunk   51 | S1   102000 | Candidates     328754 | Matches      85518 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    3.8 min
Chunk   52 | S1   104000 | Candidates     334626 | Matches      87101 | Chunk    4.5s | RAM free  6.05 GB | Elapsed    3.9 min
Chunk   53 | S1   106000 | Candidates     341024 | Matches      88754 | Chunk    4.3s | RAM free  6.06 GB | Elapsed    4.0 min
Chunk   54 | S1   108000 | Candidates     346429 | Matches      90481 | Chunk    3.7s | RAM free  6.06 GB | Elapsed    4.1 min
Chunk   55 | S1   110000 | Candidates     352882 | Matches      92131 | Chunk    4.0s | RAM free  6.05 GB | Elapsed    4.1 min
Chunk   56 | S1   112000 | Candidates     359223 | Matches      93831 | Chunk    4.9s | RAM free  6.06 GB | Elapsed    4.2 min
Chunk   57 | S1   114000 | Candidates     365779 | Matches      95509 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    4.3 min
Chunk   58 | S1   116000 | Candidates     371950 | Matches      97220 | Chunk    3.9s | RAM free  6.06 GB | Elapsed    4.3 min
Chunk   59 | S1   118000 | Candidates     378624 | Matches      98855 | Chunk    4.9s | RAM free  6.06 GB | Elapsed    4.4 min
Chunk   60 | S1   120000 | Candidates     386298 | Matches     100571 | Chunk    4.4s | RAM free  6.06 GB | Elapsed    4.5 min
Chunk   61 | S1   122000 | Candidates     392206 | Matches     102245 | Chunk    3.8s | RAM free  6.06 GB | Elapsed    4.6 min
Chunk   62 | S1   124000 | Candidates     397986 | Matches     103874 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    4.6 min
Chunk   63 | S1   126000 | Candidates     404394 | Matches     105505 | Chunk    4.7s | RAM free  6.06 GB | Elapsed    4.7 min
Chunk   64 | S1   128000 | Candidates     410481 | Matches     107139 | Chunk    3.9s | RAM free  6.06 GB | Elapsed    4.8 min
Chunk   65 | S1   130000 | Candidates     416198 | Matches     108692 | Chunk    3.8s | RAM free  6.06 GB | Elapsed    4.8 min
Chunk   66 | S1   132000 | Candidates     422730 | Matches     110370 | Chunk    5.1s | RAM free  6.06 GB | Elapsed    4.9 min
Chunk   67 | S1   134000 | Candidates     428776 | Matches     112007 | Chunk    4.0s | RAM free  6.05 GB | Elapsed    5.0 min
Chunk   68 | S1   136000 | Candidates     435813 | Matches     113699 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    5.0 min
Chunk   69 | S1   138000 | Candidates     442614 | Matches     115310 | Chunk    4.7s | RAM free  6.05 GB | Elapsed    5.1 min
Chunk   70 | S1   140000 | Candidates     448302 | Matches     117012 | Chunk    4.3s | RAM free  6.06 GB | Elapsed    5.2 min
Chunk   71 | S1   142000 | Candidates     454808 | Matches     118665 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    5.3 min
Chunk   72 | S1   144000 | Candidates     461888 | Matches     120398 | Chunk    4.4s | RAM free  6.05 GB | Elapsed    5.3 min
Chunk   73 | S1   146000 | Candidates     467273 | Matches     121985 | Chunk    4.6s | RAM free  6.05 GB | Elapsed    5.4 min
Chunk   74 | S1   148000 | Candidates     474357 | Matches     123684 | Chunk    4.2s | RAM free  6.05 GB | Elapsed    5.5 min
Chunk   75 | S1   150000 | Candidates     480520 | Matches     125339 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    5.6 min
Chunk   76 | S1   152000 | Candidates     486696 | Matches     127041 | Chunk    5.0s | RAM free  6.05 GB | Elapsed    5.6 min
Chunk   77 | S1   154000 | Candidates     493562 | Matches     128697 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    5.7 min
Chunk   78 | S1   156000 | Candidates     499505 | Matches     130342 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    5.8 min
Chunk   79 | S1   158000 | Candidates     506971 | Matches     132071 | Chunk    5.1s | RAM free  6.05 GB | Elapsed    5.9 min
Chunk   80 | S1   160000 | Candidates     512917 | Matches     133759 | Chunk    4.3s | RAM free  6.05 GB | Elapsed    5.9 min
Chunk   81 | S1   162000 | Candidates     519807 | Matches     135455 | Chunk    4.2s | RAM free  6.06 GB | Elapsed    6.0 min
Chunk   82 | S1   164000 | Candidates     525987 | Matches     137162 | Chunk    4.1s | RAM free  6.05 GB | Elapsed    6.1 min
Chunk   83 | S1   166000 | Candidates     532055 | Matches     138811 | Chunk    4.8s | RAM free  6.06 GB | Elapsed    6.1 min
Chunk   84 | S1   168000 | Candidates     537696 | Matches     140489 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    6.2 min
Chunk   85 | S1   170000 | Candidates     543787 | Matches     142137 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    6.3 min
Chunk   86 | S1   172000 | Candidates     550385 | Matches     143867 | Chunk    5.1s | RAM free  6.06 GB | Elapsed    6.4 min
Chunk   87 | S1   174000 | Candidates     557322 | Matches     145567 | Chunk    4.2s | RAM free  6.06 GB | Elapsed    6.4 min
Chunk   88 | S1   176000 | Candidates     563625 | Matches     147280 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    6.5 min
Chunk   89 | S1   178000 | Candidates     570023 | Matches     148918 | Chunk    4.6s | RAM free  6.05 GB | Elapsed    6.6 min
Chunk   90 | S1   180000 | Candidates     576968 | Matches     150646 | Chunk    4.9s | RAM free  6.06 GB | Elapsed    6.7 min
Chunk   91 | S1   182000 | Candidates     583029 | Matches     152345 | Chunk    3.9s | RAM free  6.06 GB | Elapsed    6.7 min
Chunk   92 | S1   184000 | Candidates     589297 | Matches     153980 | Chunk    4.1s | RAM free  6.05 GB | Elapsed    6.8 min
Chunk   93 | S1   186000 | Candidates     595574 | Matches     155604 | Chunk    5.1s | RAM free  6.06 GB | Elapsed    6.9 min
Chunk   94 | S1   188000 | Candidates     601927 | Matches     157278 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    6.9 min
Chunk   95 | S1   190000 | Candidates     608241 | Matches     159006 | Chunk    4.1s | RAM free  6.05 GB | Elapsed    7.0 min
Chunk   96 | S1   192000 | Candidates     614592 | Matches     160653 | Chunk    5.1s | RAM free  6.06 GB | Elapsed    7.1 min
Chunk   97 | S1   194000 | Candidates     621714 | Matches     162273 | Chunk    4.4s | RAM free  6.05 GB | Elapsed    7.2 min
Chunk   98 | S1   196000 | Candidates     627806 | Matches     163987 | Chunk    4.1s | RAM free  6.05 GB | Elapsed    7.2 min
Chunk   99 | S1   198000 | Candidates     634279 | Matches     165606 | Chunk    4.7s | RAM free  6.05 GB | Elapsed    7.3 min
Chunk  100 | S1   200000 | Candidates     640672 | Matches     167330 | Chunk    4.4s | RAM free  6.05 GB | Elapsed    7.4 min
Chunk  101 | S1   202000 | Candidates     647812 | Matches     169107 | Chunk    4.2s | RAM free  6.06 GB | Elapsed    7.5 min
Chunk  102 | S1   204000 | Candidates     653961 | Matches     170811 | Chunk    4.3s | RAM free  6.05 GB | Elapsed    7.5 min
Chunk  103 | S1   206000 | Candidates     660675 | Matches     172499 | Chunk    5.0s | RAM free  6.06 GB | Elapsed    7.6 min
Chunk  104 | S1   208000 | Candidates     666889 | Matches     174165 | Chunk    4.0s | RAM free  6.05 GB | Elapsed    7.7 min
Chunk  105 | S1   210000 | Candidates     672909 | Matches     175898 | Chunk    4.0s | RAM free  6.05 GB | Elapsed    7.7 min
Chunk  106 | S1   212000 | Candidates     679707 | Matches     177601 | Chunk    5.3s | RAM free  6.06 GB | Elapsed    7.8 min
Chunk  107 | S1   214000 | Candidates     685902 | Matches     179205 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    7.9 min
Chunk  108 | S1   216000 | Candidates     692485 | Matches     180957 | Chunk    4.1s | RAM free  6.05 GB | Elapsed    8.0 min
Chunk  109 | S1   218000 | Candidates     699555 | Matches     182646 | Chunk    5.1s | RAM free  6.05 GB | Elapsed    8.1 min
Chunk  110 | S1   220000 | Candidates     706349 | Matches     184293 | Chunk    4.3s | RAM free  6.05 GB | Elapsed    8.1 min
Chunk  111 | S1   222000 | Candidates     712074 | Matches     185972 | Chunk    3.8s | RAM free  6.05 GB | Elapsed    8.2 min
Chunk  112 | S1   224000 | Candidates     718633 | Matches     187678 | Chunk    4.5s | RAM free  6.05 GB | Elapsed    8.3 min
Chunk  113 | S1   226000 | Candidates     724983 | Matches     189290 | Chunk    4.7s | RAM free  6.05 GB | Elapsed    8.3 min
Chunk  114 | S1   228000 | Candidates     731626 | Matches     190922 | Chunk    4.0s | RAM free  6.05 GB | Elapsed    8.4 min
Chunk  115 | S1   230000 | Candidates     737757 | Matches     192608 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    8.5 min
Chunk  116 | S1   232000 | Candidates     744962 | Matches     194300 | Chunk    5.4s | RAM free  6.06 GB | Elapsed    8.6 min
Chunk  117 | S1   234000 | Candidates     750857 | Matches     195952 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    8.6 min
Chunk  118 | S1   236000 | Candidates     757185 | Matches     197756 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    8.7 min
Chunk  119 | S1   238000 | Candidates     763367 | Matches     199388 | Chunk    4.7s | RAM free  6.05 GB | Elapsed    8.8 min
Chunk  120 | S1   240000 | Candidates     769389 | Matches     201003 | Chunk    4.4s | RAM free  6.06 GB | Elapsed    8.8 min
Chunk  121 | S1   242000 | Candidates     775679 | Matches     202662 | Chunk    4.0s | RAM free  6.06 GB | Elapsed    8.9 min
Chunk  122 | S1   244000 | Candidates     782369 | Matches     204376 | Chunk    4.5s | RAM free  6.06 GB | Elapsed    9.0 min
Chunk  123 | S1   246000 | Candidates     787854 | Matches     205956 | Chunk    4.6s | RAM free  6.06 GB | Elapsed    9.1 min
Chunk  124 | S1   248000 | Candidates     795048 | Matches     207603 | Chunk    4.1s | RAM free  6.06 GB | Elapsed    9.1 min
Chunk  125 | S1   250000 | Candidates     801220 | Matches     209196 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    9.2 min
Chunk  126 | S1   252000 | Candidates     807945 | Matches     210912 | Chunk    5.3s | RAM free  6.05 GB | Elapsed    9.3 min
Chunk  127 | S1   254000 | Candidates     813853 | Matches     212592 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    9.4 min
Chunk  128 | S1   256000 | Candidates     820520 | Matches     214287 | Chunk    4.0s | RAM free  6.05 GB | Elapsed    9.4 min
Chunk  129 | S1   258000 | Candidates     827065 | Matches     216005 | Chunk    4.6s | RAM free  6.05 GB | Elapsed    9.5 min
Chunk  130 | S1   260000 | Candidates     833240 | Matches     217659 | Chunk    4.4s | RAM free  6.06 GB | Elapsed    9.6 min
Chunk  131 | S1   262000 | Candidates     839114 | Matches     219299 | Chunk    3.9s | RAM free  6.05 GB | Elapsed    9.6 min
Chunk  132 | S1   264000 | Candidates     845895 | Matches     220898 | Chunk    5.1s | RAM free  6.05 GB | Elapsed    9.7 min
Chunk  133 | S1   266000 | Candidates     851910 | Matches     222695 | Chunk    4.8s | RAM free  6.05 GB | Elapsed    9.8 min
Chunk  134 | S1   268000 | Candidates     857481 | Matches     224449 | Chunk    3.9s | RAM free  6.06 GB | Elapsed    9.9 min
Chunk  135 | S1   270000 | Candidates     864687 | Matches     226192 | Chunk    4.2s | RAM free  6.05 GB | Elapsed    9.9 min
Chunk  136 | S1   272000 | Candidates     870918 | Matches     227941 | Chunk    5.3s | RAM free  6.06 GB | Elapsed   10.0 min
Chunk  137 | S1   274000 | Candidates     876841 | Matches     229627 | Chunk    3.9s | RAM free  6.05 GB | Elapsed   10.1 min
Chunk  138 | S1   276000 | Candidates     883480 | Matches     231320 | Chunk    4.1s | RAM free  6.06 GB | Elapsed   10.2 min
Chunk  139 | S1   278000 | Candidates     889567 | Matches     233053 | Chunk    4.8s | RAM free  6.06 GB | Elapsed   10.2 min
Chunk  140 | S1   280000 | Candidates     896386 | Matches     234653 | Chunk    4.5s | RAM free  6.05 GB | Elapsed   10.3 min
Chunk  141 | S1   282000 | Candidates     902457 | Matches     236352 | Chunk    3.9s | RAM free  6.05 GB | Elapsed   10.4 min
Chunk  142 | S1   284000 | Candidates     908170 | Matches     238068 | Chunk    4.1s | RAM free  6.06 GB | Elapsed   10.4 min
Chunk  143 | S1   286000 | Candidates     914646 | Matches     239821 | Chunk    4.9s | RAM free  6.06 GB | Elapsed   10.5 min
Chunk  144 | S1   288000 | Candidates     920821 | Matches     241431 | Chunk    3.9s | RAM free  6.06 GB | Elapsed   10.6 min
Chunk  145 | S1   290000 | Candidates     926809 | Matches     243074 | Chunk    3.9s | RAM free  6.05 GB | Elapsed   10.7 min
Chunk  146 | S1   292000 | Candidates     932385 | Matches     244677 | Chunk    4.8s | RAM free  6.05 GB | Elapsed   10.7 min
Chunk  147 | S1   294000 | Candidates     939271 | Matches     246428 | Chunk    4.3s | RAM free  6.06 GB | Elapsed   10.8 min
Chunk  148 | S1   296000 | Candidates     946422 | Matches     248167 | Chunk    4.4s | RAM free  6.05 GB | Elapsed   10.9 min
Chunk  149 | S1   298000 | Candidates     953240 | Matches     249844 | Chunk    4.9s | RAM free  6.05 GB | Elapsed   11.0 min
Chunk  150 | S1   300000 | Candidates     959737 | Matches     251691 | Chunk    4.5s | RAM free  6.06 GB | Elapsed   11.0 min
Chunk  151 | S1   302000 | Candidates     965821 | Matches     253364 | Chunk    3.9s | RAM free  6.05 GB | Elapsed   11.1 min
Chunk  152 | S1   304000 | Candidates     972014 | Matches     255199 | Chunk    4.2s | RAM free  6.04 GB | Elapsed   11.2 min

In [ ]:
# ============================================================
# FINAL V5 — RAM-SAFE S2 + S3 COMBINATION + VALIDATION
# ============================================================

import os
import csv
import time
import gc

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

BASE = "/content/amazon_ml_challenge/student_resource"

WORK = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE"

S2_FILE = os.path.join(WORK, "s2_results.tsv")
S3_FILE = os.path.join(WORK, "s3_results.tsv")

OUTPUT_DIR = os.path.join(BASE, "output")

MATCHING_FILE = os.path.join(OUTPUT_DIR, "matching_results.tsv")
CANDIDATE_FILE = os.path.join(OUTPUT_DIR, "candidate_pairs.tsv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("=" * 70)
print("V5 FINAL COMBINATION")
print("=" * 70)

for f in [S2_FILE, S3_FILE]:
    print(f"{f}")
    print(f"  exists: {os.path.exists(f)}")
    if os.path.exists(f):
        print(f"  size: {os.path.getsize(f) / (1024**3):.2f} GB")

# ------------------------------------------------------------
# SAFETY CHECK
# ------------------------------------------------------------

assert os.path.exists(S2_FILE), f"Missing S2 file: {S2_FILE}"
assert os.path.exists(S3_FILE), f"Missing S3 file: {S3_FILE}"

# Remove old final outputs so we don't accidentally append
for f in [MATCHING_FILE, CANDIDATE_FILE]:
    if os.path.exists(f):
        os.remove(f)
        print("Removed old:", f)

gc.collect()

# ------------------------------------------------------------
# HELPERS
# ------------------------------------------------------------

def split_ids(x):
    """
    Convert comma-separated IDs to a set.
    Empty string -> empty set.
    """
    if not x:
        return set()
    return set(v for v in x.split(",") if v)


def join_ids(values):
    """
    Stable deterministic ordering.
    """
    if not values:
        return ""
    return ",".join(sorted(values))


# ------------------------------------------------------------
# STREAMING COMBINATION
# ------------------------------------------------------------

start = time.time()

processed = 0
total_candidates = 0
total_matches = 0

with open(S2_FILE, "r", encoding="utf-8", newline="") as f2, \
     open(S3_FILE, "r", encoding="utf-8", newline="") as f3, \
     open(MATCHING_FILE, "w", encoding="utf-8", newline="") as fm, \
     open(CANDIDATE_FILE, "w", encoding="utf-8", newline="") as fc:

    r2 = csv.DictReader(f2, delimiter="\t")
    r3 = csv.DictReader(f3, delimiter="\t")

    expected2 = [
        "source1_entity_id",
        "candidate_entity_ids",
        "matched_entity_ids"
    ]

    expected3 = [
        "source1_entity_id",
        "candidate_entity_ids",
        "matched_entity_ids"
    ]

    assert r2.fieldnames == expected2, (
        f"Unexpected S2 columns: {r2.fieldnames}"
    )

    assert r3.fieldnames == expected3, (
        f"Unexpected S3 columns: {r3.fieldnames}"
    )

    matching_writer = csv.writer(
        fm,
        delimiter="\t",
        lineterminator="\n"
    )

    candidate_writer = csv.writer(
        fc,
        delimiter="\t",
        lineterminator="\n"
    )

    # Headers
    matching_writer.writerow([
        "source1_entity_id",
        "matched_entity_ids"
    ])

    candidate_writer.writerow([
        "source1_entity_id",
        "candidate_entity_ids"
    ])

    while True:

        row2 = next(r2, None)
        row3 = next(r3, None)

        if row2 is None and row3 is None:
            break

        # Both files must contain exactly the same S1 sequence
        assert row2 is not None and row3 is not None, (
            "S2 and S3 result files have different numbers of rows."
        )

        s1_2 = row2["source1_entity_id"]
        s1_3 = row3["source1_entity_id"]

        assert s1_2 == s1_3, (
            f"S1 order mismatch at row {processed + 1}: "
            f"S2={s1_2}, S3={s1_3}"
        )

        s1_id = s1_2

        # Read S2/S3 candidate and match sets
        c2 = split_ids(row2["candidate_entity_ids"])
        c3 = split_ids(row3["candidate_entity_ids"])

        m2 = split_ids(row2["matched_entity_ids"])
        m3 = split_ids(row3["matched_entity_ids"])

        # Final candidate set = exact union of S2 + S3
        candidates = c2 | c3

        # Final predicted matches = exact union of S2 + S3
        matches = m2 | m3

        # Critical safety rule:
        # every final match MUST be inside final candidate set
        assert matches.issubset(candidates), (
            f"Invalid final match outside candidate set for {s1_id}"
        )

        matching_writer.writerow([
            s1_id,
            join_ids(matches)
        ])

        candidate_writer.writerow([
            s1_id,
            join_ids(candidates)
        ])

        processed += 1
        total_candidates += len(candidates)
        total_matches += len(matches)

        if processed % 100000 == 0:
            elapsed = time.time() - start
            print(
                f"{processed:,} S1 | "
                f"Candidates {total_candidates:,} | "
                f"Matches {total_matches:,} | "
                f"Elapsed {elapsed/60:.1f} min"
            )

# ------------------------------------------------------------
# FINAL SUMMARY
# ------------------------------------------------------------

elapsed = time.time() - start

print("\n" + "=" * 70)
print("✅ FINAL COMBINATION COMPLETE")
print("=" * 70)

print("S1 processed:", f"{processed:,}")
print("Total final candidates:", f"{total_candidates:,}")
print("Total final matches:", f"{total_matches:,}")

print(
    "Avg candidates/S1:",
    total_candidates / processed
)

print(
    "Avg matches/S1:",
    total_matches / processed
)

print("Time:", f"{elapsed/60:.2f} minutes")

print("\nMatching file:")
print(MATCHING_FILE)
print(
    "Size:",
    f"{os.path.getsize(MATCHING_FILE)/(1024**3):.2f} GB"
)

print("\nCandidate file:")
print(CANDIDATE_FILE)
print(
    "Size:",
    f"{os.path.getsize(CANDIDATE_FILE)/(1024**3):.2f} GB"
)

gc.collect()

======================================================================
V5 FINAL COMBINATION
======================================================================
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE/s2_results.tsv
  exists: True
  size: 0.11 GB
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE/s3_results.tsv
  exists: True
  size: 0.11 GB
100,000 S1 | Candidates 649,083 | Matches 174,539 | Elapsed 0.0 min
200,000 S1 | Candidates 1,291,758 | Matches 348,273 | Elapsed 0.1 min
300,000 S1 | Candidates 1,934,694 | Matches 522,796 | Elapsed 0.1 min
400,000 S1 | Candidates 2,579,171 | Matches 696,909 | Elapsed 0.1 min
500,000 S1 | Candidates 3,210,096 | Matches 870,874 | Elapsed 0.2 min
600,000 S1 | Candidates 3,847,905 | Matches 1,045,214 | Elapsed 0.2 min
700,000 S1 | Candidates 4,494,333 | Matches 1,220,449 | Elapsed 0.3 min
800,000 S1 | Candidates 5,145,354 | Matches 1,396,470 | Elapsed 0.3 min
900,000 S1 | Candidates 5,785,697 | Matches 1,570,882 | Elapsed 0.3 min
1,000,000 S1 | Candidates 6,435,582 | Matches 1,746,454 | Elapsed 0.4 min
1,100,000 S1 | Candidates 7,095,640 | Matches 1,920,543 | Elapsed 0.4 min
1,200,000 S1 | Candidates 7,745,593 | Matches 2,094,957 | Elapsed 0.5 min
1,300,000 S1 | Candidates 8,381,877 | Matches 2,269,093 | Elapsed 0.5 min
1,400,000 S1 | Candidates 9,019,149 | Matches 2,444,571 | Elapsed 0.5 min
1,500,000 S1 | Candidates 9,668,109 | Matches 2,618,506 | Elapsed 0.6 min
1,600,000 S1 | Candidates 10,317,340 | Matches 2,792,388 | Elapsed 0.6 min
1,700,000 S1 | Candidates 10,958,439 | Matches 2,965,088 | Elapsed 0.6 min

======================================================================
✅ FINAL COMBINATION COMPLETE
======================================================================
S1 processed: 1,732,544
Total final candidates: 11,165,620
Total final matches: 3,022,283
Avg candidates/S1: 6.444638635440139
Avg matches/S1: 1.7444191893539212
Time: 0.66 minutes

Matching file:
/content/amazon_ml_challenge/student_resource/output/matching_results.tsv
Size: 0.06 GB

Candidate file:
/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv
Size: 0.16 GB

0

In [ ]:
# ============================================================
# OFFICIAL CHALLENGE VALIDATOR
# ============================================================

import subprocess
import sys

validator = os.path.join(
    BASE,
    "utils",
    "validate_submission.py"
)

cmd = [
    sys.executable,
    validator,
    "--matching",
    MATCHING_FILE,
    "--candidate",
    CANDIDATE_FILE,
    "--test-dir",
    os.path.join(BASE, "dataset", "test")
]

print("=" * 70)
print("RUNNING OFFICIAL VALIDATOR")
print("=" * 70)

result = subprocess.run(
    cmd,
    capture_output=True,
    text=True
)

print(result.stdout)

if result.stderr:
    print("STDERR:")
    print(result.stderr)

print("=" * 70)

if result.returncode == 0:
    print("✅ VALIDATOR PASSED")
else:
    print("❌ VALIDATOR FAILED")
    print("Return code:", result.returncode)

======================================================================
RUNNING OFFICIAL VALIDATOR
======================================================================
ML Challenge 2026 — submission validator
  test dir: /content/amazon_ml_challenge/student_resource/dataset/test
  required S1 entities: 1732544
  matching_results.tsv: 1732544 rows (837705 empty, 894839 non-empty).
  candidate_pairs.tsv: 1732544 rows (668458 empty, 1064086 non-empty).

WARNING: ID-existence check is OFF (the default) — not checking that matched/candidate IDs exist in the test set. Every other rule is still checked. Re-run with --check-ids to enable it (needs test_source2/3.tsv; uses more memory). A nonexistent ID only lowers your score, never rejects your submission.
PASS — no blocking issues found. Safe to submit.

======================================================================
✅ VALIDATOR PASSED

In [ ]:
from google.colab import files

files.download(
    "/content/amazon_ml_challenge/student_resource/output/matching_results.tsv"
)

In [ ]:
from google.colab import files

files.download(
    "/content/amazon_ml_challenge/student_resource/output/candidate_pairs.tsv"
)

In [ ]:
# ============================================================
# REPRODUCE THE KNOWN V1.1 PIPELINE
# EXACT ADDRESS + UNIQUE EXACT NAME + COUNTRY
# ============================================================

import os
import re
import gc
import csv
import pickle
import unicodedata
import pandas as pd
from collections import defaultdict

BASE = "/content/amazon_ml_challenge/student_resource"
TEST_DIR = f"{BASE}/dataset/test"

DRIVE_BASE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"
INDEX_DIR = f"{DRIVE_BASE}/V5_full_indexes"

V11_DIR = f"{DRIVE_BASE}/V1_1_REPRODUCTION"
os.makedirs(V11_DIR, exist_ok=True)

MATCH_OUT = f"{V11_DIR}/matching_results.tsv"
CAND_OUT = f"{V11_DIR}/candidate_pairs.tsv"

S1_PATH = f"{TEST_DIR}/test_source1.tsv"
S2_PATH = f"{TEST_DIR}/test_source2.tsv"
S3_PATH = f"{TEST_DIR}/test_source3.tsv"

# ------------------------------------------------------------
# NORMALIZATION
# ------------------------------------------------------------

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def normalize_country(text):
    if pd.isna(text):
        return ""
    return str(text).lower().strip()


# ------------------------------------------------------------
# LOAD TEST S1
# ------------------------------------------------------------

print("Loading Test S1...")

test_s1 = pd.read_csv(
    S1_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("S1:", test_s1.shape)

# ------------------------------------------------------------
# BUILD EXACT LOOKUPS FROM S1
#
# For each S1:
#   exact normalized address + country
#   exact UNIQUE normalized name + country
# ------------------------------------------------------------

name_counts = defaultdict(int)
name_to_s1 = defaultdict(list)

address_to_s1 = defaultdict(list)

print("\nBuilding S1 exact maps...")

for row in test_s1.itertuples(index=False):

    sid = row.entity_id
    country = normalize_country(row.country)

    name = normalize_advanced(
        row.business_name
    )

    address = normalize_advanced(
        row.business_address
    )

    if name:
        key = (country, name)
        name_counts[key] += 1
        name_to_s1[key].append(sid)

    if address:
        key = (country, address)
        address_to_s1[key].append(sid)

print("Name keys:", len(name_to_s1))
print("Address keys:", len(address_to_s1))

# Keep ONLY unique names
unique_name_map = {}

for key, ids in name_to_s1.items():
    if name_counts[key] == 1:
        unique_name_map[key] = ids[0]

del name_to_s1
del name_counts

gc.collect()

print("Unique name keys:", len(unique_name_map))

# ------------------------------------------------------------
# PREDICTION STORAGE
# ------------------------------------------------------------

predictions = {
    sid: []
    for sid in test_s1["entity_id"]
}

candidates = {
    sid: []
    for sid in test_s1["entity_id"]
}

# ------------------------------------------------------------
# PROCESS S2 + S3
# ------------------------------------------------------------

total_candidate_pairs = 0

for source_name, path in [
    ("S2", S2_PATH),
    ("S3", S3_PATH)
]:

    print("\n========================================")
    print("Processing", source_name)
    print("========================================")

    processed = 0
    source_candidates = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=100000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id

            country = normalize_country(
                row.country
            )

            name = normalize_advanced(
                row.business_name
            )

            address = normalize_advanced(
                row.business_address
            )

            found_s1 = set()

            # ------------------------------------------------
            # BLOCK 1: EXACT ADDRESS + COUNTRY
            # ------------------------------------------------

            if address:

                found_s1.update(
                    address_to_s1.get(
                        (country, address),
                        []
                    )
                )

            # ------------------------------------------------
            # BLOCK 2: UNIQUE EXACT NAME + COUNTRY
            # ------------------------------------------------

            if name:

                sid = unique_name_map.get(
                    (country, name)
                )

                if sid is not None:
                    found_s1.add(sid)

            # ------------------------------------------------
            # SAVE CANDIDATES
            # ------------------------------------------------

            for sid in found_s1:

                candidates[sid].append(
                    eid
                )

                predictions[sid].append(
                    eid
                )

                source_candidates += 1

            processed += 1

        print(
            source_name,
            "| processed:",
            f"{processed:,}",
            "| candidate pairs:",
            f"{source_candidates:,}"
        )

    total_candidate_pairs += source_candidates

    print(
        source_name,
        "COMPLETE | candidate pairs:",
        f"{source_candidates:,}"
    )

# ------------------------------------------------------------
# DEDUPLICATE
# ------------------------------------------------------------

print("\nDeduplicating...")

for sid in predictions:

    predictions[sid] = list(
        dict.fromkeys(
            predictions[sid]
        )
    )

    candidates[sid] = list(
        dict.fromkeys(
            candidates[sid]
        )
    )

# ------------------------------------------------------------
# WRITE FILES
# ------------------------------------------------------------

print("\nWriting V1.1 files...")

with open(
    MATCH_OUT,
    "w",
    encoding="utf-8",
    newline=""
) as f_match, open(
    CAND_OUT,
    "w",
    encoding="utf-8",
    newline=""
) as f_cand:

    mw = csv.writer(
        f_match,
        delimiter="\t",
        lineterminator="\n"
    )

    cw = csv.writer(
        f_cand,
        delimiter="\t",
        lineterminator="\n"
    )

    mw.writerow([
        "source1_entity_id",
        "matched_entity_ids"
    ])

    cw.writerow([
        "source1_entity_id",
        "candidate_entity_ids"
    ])

    for sid in test_s1["entity_id"]:

        mids = predictions[sid]
        cids = candidates[sid]

        mw.writerow([
            sid,
            ",".join(mids)
        ])

        cw.writerow([
            sid,
            ",".join(cids)
        ])

# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

nonempty = sum(
    bool(predictions[sid])
    for sid in predictions
)

total_matches = sum(
    len(predictions[sid])
    for sid in predictions
)

total_candidates = sum(
    len(candidates[sid])
    for sid in candidates
)

print("\n" + "=" * 70)
print("✅ V1.1 REPRODUCTION COMPLETE")
print("=" * 70)

print(
    "S1 entities:",
    len(test_s1)
)

print(
    "Non-empty S1:",
    nonempty
)

print(
    "Empty S1:",
    len(test_s1) - nonempty
)

print(
    "Total candidate pairs:",
    total_candidates
)

print(
    "Total predicted matches:",
    total_matches
)

print(
    "Avg candidates/S1:",
    total_candidates / len(test_s1)
)

print(
    "Avg matches/S1:",
    total_matches / len(test_s1)
)

print("\nMatching:")
print(MATCH_OUT)

print("\nCandidates:")
print(CAND_OUT)

Loading Test S1...
S1: (1732544, 4)

Building S1 exact maps...
Name keys: 1229995
Address keys: 1673690
Unique name keys: 1098328

========================================
Processing S2
========================================
S2 | processed: 100,000 | candidate pairs: 20,316
S2 | processed: 200,000 | candidate pairs: 40,054
S2 | processed: 300,000 | candidate pairs: 60,010
S2 | processed: 400,000 | candidate pairs: 79,931
S2 | processed: 500,000 | candidate pairs: 100,044
S2 | processed: 600,000 | candidate pairs: 119,892
S2 | processed: 700,000 | candidate pairs: 139,923
S2 | processed: 800,000 | candidate pairs: 160,016
S2 | processed: 900,000 | candidate pairs: 179,651
S2 | processed: 1,000,000 | candidate pairs: 199,553
S2 | processed: 1,100,000 | candidate pairs: 219,630
S2 | processed: 1,200,000 | candidate pairs: 239,536
S2 | processed: 1,300,000 | candidate pairs: 259,679
S2 | processed: 1,400,000 | candidate pairs: 279,853
S2 | processed: 1,500,000 | candidate pairs: 299,550
S2 | processed: 1,600,000 | candidate pairs: 319,534
S2 | processed: 1,700,000 | candidate pairs: 339,574
S2 | processed: 1,800,000 | candidate pairs: 359,503
S2 | processed: 1,900,000 | candidate pairs: 379,381
S2 | processed: 2,000,000 | candidate pairs: 398,970
S2 | processed: 2,100,000 | candidate pairs: 419,056
S2 | processed: 2,200,000 | candidate pairs: 438,789
S2 | processed: 2,300,000 | candidate pairs: 458,725
S2 | processed: 2,400,000 | candidate pairs: 478,780
S2 | processed: 2,500,000 | candidate pairs: 498,747
S2 | processed: 2,600,000 | candidate pairs: 518,596
S2 | processed: 2,700,000 | candidate pairs: 538,365
S2 | processed: 2,800,000 | candidate pairs: 558,379
S2 | processed: 2,900,000 | candidate pairs: 578,461
S2 | processed: 3,000,000 | candidate pairs: 598,222
S2 | processed: 3,100,000 | candidate pairs: 617,952
S2 | processed: 3,200,000 | candidate pairs: 638,086
S2 | processed: 3,300,000 | candidate pairs: 657,812
S2 | processed: 3,400,000 | candidate pairs: 677,714
S2 | processed: 3,500,000 | candidate pairs: 697,871
S2 | processed: 3,600,000 | candidate pairs: 717,742
S2 | processed: 3,700,000 | candidate pairs: 737,844
S2 | processed: 3,800,000 | candidate pairs: 757,905
S2 | processed: 3,900,000 | candidate pairs: 777,702
S2 | processed: 4,000,000 | candidate pairs: 797,773
S2 | processed: 4,100,000 | candidate pairs: 817,430
S2 | processed: 4,200,000 | candidate pairs: 837,178
S2 | processed: 4,300,000 | candidate pairs: 857,126
S2 | processed: 4,400,000 | candidate pairs: 876,876
S2 | processed: 4,500,000 | candidate pairs: 896,828
S2 | processed: 4,600,000 | candidate pairs: 916,817
S2 | processed: 4,700,000 | candidate pairs: 936,522
S2 | processed: 4,800,000 | candidate pairs: 956,472
S2 | processed: 4,887,273 | candidate pairs: 973,830
S2 COMPLETE | candidate pairs: 973,830

========================================
Processing S3
========================================
S3 | processed: 100,000 | candidate pairs: 14,473
S3 | processed: 200,000 | candidate pairs: 29,225
S3 | processed: 300,000 | candidate pairs: 44,416
S3 | processed: 400,000 | candidate pairs: 59,596
S3 | processed: 500,000 | candidate pairs: 73,877
S3 | processed: 600,000 | candidate pairs: 88,523
S3 | processed: 700,000 | candidate pairs: 103,273
S3 | processed: 800,000 | candidate pairs: 118,131
S3 | processed: 900,000 | candidate pairs: 132,966
S3 | processed: 1,000,000 | candidate pairs: 148,256
S3 | processed: 1,100,000 | candidate pairs: 163,108
S3 | processed: 1,200,000 | candidate pairs: 177,794
S3 | processed: 1,300,000 | candidate pairs: 192,126
S3 | processed: 1,400,000 | candidate pairs: 206,676
S3 | processed: 1,500,000 | candidate pairs: 221,713
S3 | processed: 1,600,000 | candidate pairs: 236,406
S3 | processed: 1,700,000 | candidate pairs: 251,300
S3 | processed: 1,800,000 | candidate pairs: 266,223
S3 | processed: 1,900,000 | candidate pairs: 281,284
S3 | processed: 2,000,000 | candidate pairs: 295,963
S3 | processed: 2,100,000 | candidate pairs: 310,593
S3 | processed: 2,200,000 | candidate pairs: 325,557
S3 | processed: 2,300,000 | candidate pairs: 340,596
S3 | processed: 2,400,000 | candidate pairs: 355,285
S3 | processed: 2,500,000 | candidate pairs: 370,461
S3 | processed: 2,600,000 | candidate pairs: 385,088
S3 | processed: 2,700,000 | candidate pairs: 399,458
S3 | processed: 2,800,000 | candidate pairs: 414,198
S3 | processed: 2,900,000 | candidate pairs: 428,972
S3 | processed: 3,000,000 | candidate pairs: 443,938
S3 | processed: 3,100,000 | candidate pairs: 458,940
S3 | processed: 3,200,000 | candidate pairs: 473,590
S3 | processed: 3,300,000 | candidate pairs: 488,303
S3 | processed: 3,400,000 | candidate pairs: 502,837
S3 | processed: 3,500,000 | candidate pairs: 517,639
S3 | processed: 3,600,000 | candidate pairs: 532,442
S3 | processed: 3,700,000 | candidate pairs: 546,926
S3 | processed: 3,800,000 | candidate pairs: 561,580
S3 | processed: 3,900,000 | candidate pairs: 576,490
S3 | processed: 4,000,000 | candidate pairs: 591,842
S3 | processed: 4,100,000 | candidate pairs: 606,228
S3 | processed: 4,200,000 | candidate pairs: 621,251
S3 | processed: 4,300,000 | candidate pairs: 635,611
S3 | processed: 4,400,000 | candidate pairs: 650,115
S3 | processed: 4,500,000 | candidate pairs: 664,620
S3 | processed: 4,600,000 | candidate pairs: 679,302
S3 | processed: 4,700,000 | candidate pairs: 693,906
S3 | processed: 4,800,000 | candidate pairs: 708,686
S3 | processed: 4,900,000 | candidate pairs: 723,433
S3 | processed: 5,000,000 | candidate pairs: 738,121
S3 | processed: 5,082,316 | candidate pairs: 750,189
S3 COMPLETE | candidate pairs: 750,189

Deduplicating...

Writing V1.1 files...

======================================================================
✅ V1.1 REPRODUCTION COMPLETE
======================================================================
S1 entities: 1732544
Non-empty S1: 912910
Empty S1: 819634
Total candidate pairs: 1724019
Total predicted matches: 1724019
Avg candidates/S1: 0.9950794900446973
Avg matches/S1: 0.9950794900446973

Matching:
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv

Candidates:
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/candidate_pairs.tsv

In [ ]:
print("We will test the V1.1 rule on training validation before using the final submission.")
print("Do NOT upload V1_1_REPRODUCTION yet.")

We will test the V1.1 rule on training validation before using the final submission.
Do NOT upload V1_1_REPRODUCTION yet.

In [ ]:
# ============================================================
# V1.1 PRECISION DIAGNOSTIC
# DO NOT GENERATE OR SUBMIT TEST FILES YET
# ============================================================

import os
import re
import gc
import numpy as np
import pandas as pd
from collections import defaultdict
from rapidfuzz.fuzz import ratio

print("=" * 70)
print("V1.1 PRECISION DIAGNOSTIC")
print("=" * 70)

# Check that the validation objects from our notebook exist
needed = [
    "s1_val",
    "val_ids",
    "gt_lookup",
    "normalize_advanced",
    "normalize_country"
]

missing = [x for x in needed if x not in globals()]

if missing:
    print("MISSING OBJECTS:", missing)
    print("\nDo NOT continue.")
    print("Send me this output and I will give you the recovery cell.")
else:
    print("Validation objects: READY")

    TRAIN_S2 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source2.tsv"
    TRAIN_S3 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source3.tsv"

    # --------------------------------------------------------
    # Build validation S1 exact indexes
    # --------------------------------------------------------

    val_name_map = defaultdict(list)
    val_addr_map = defaultdict(list)

    for row in s1_val.itertuples(index=False):

        sid = str(row.entity_id)
        country = normalize_country(row.country)

        name = normalize_advanced(row.business_name)
        address = normalize_advanced(row.business_address)

        if name:
            val_name_map[(country, name)].append(sid)

        if address:
            val_addr_map[(country, address)].append(sid)

    print("Validation S1:", len(s1_val))
    print("Unique-name keys:", len(val_name_map))
    print("Address keys:", len(val_addr_map))

    # --------------------------------------------------------
    # Statistics
    # --------------------------------------------------------

    stats = {
        "address_only": 0,
        "name_only": 0,
        "both": 0,

        "address_tp": 0,
        "address_fp": 0,

        "name_tp": 0,
        "name_fp": 0,

        "both_tp": 0,
        "both_fp": 0,

        "total_candidates": 0,
        "total_tp": 0,
    }

    # Store name-only pairs so we can test filters
    name_only_pairs = []

    # --------------------------------------------------------
    # Scan training S2/S3
    # --------------------------------------------------------

    for source_name, path in [
        ("S2", TRAIN_S2),
        ("S3", TRAIN_S3)
    ]:

        print("\nProcessing", source_name)

        processed = 0

        for chunk in pd.read_csv(
            path,
            sep="\t",
            usecols=[
                "entity_id",
                "business_name",
                "business_address",
                "country"
            ],
            dtype=str,
            keep_default_na=False,
            chunksize=200000
        ):

            for row in chunk.itertuples(index=False):

                eid = str(row.entity_id)
                country = normalize_country(row.country)

                name = normalize_advanced(row.business_name)
                address = normalize_advanced(row.business_address)

                addr_sids = set()
                name_sids = set()

                if address:
                    addr_sids.update(
                        val_addr_map.get(
                            (country, address),
                            []
                        )
                    )

                if name:
                    # Only UNIQUE exact name
                    sids = val_name_map.get(
                        (country, name),
                        []
                    )

                    if len(sids) == 1:
                        name_sids.add(sids[0])

                candidates = addr_sids | name_sids

                for sid in candidates:

                    true_ids = gt_lookup.get(
                        sid,
                        set()
                    )

                    is_true = eid in true_ids

                    stats["total_candidates"] += 1

                    if is_true:
                        stats["total_tp"] += 1

                    in_addr = sid in addr_sids
                    in_name = sid in name_sids

                    if in_addr and in_name:

                        stats["both"] += 1

                        if is_true:
                            stats["both_tp"] += 1
                        else:
                            stats["both_fp"] += 1

                    elif in_addr:

                        stats["address_only"] += 1

                        if is_true:
                            stats["address_tp"] += 1
                        else:
                            stats["address_fp"] += 1

                    elif in_name:

                        stats["name_only"] += 1

                        if is_true:
                            stats["name_tp"] += 1
                        else:
                            stats["name_fp"] += 1

                        # Keep only name-only candidates for
                        # the detailed filter analysis.
                        s1row = s1_val[
                            s1_val["entity_id"] == sid
                        ]

                        if len(s1row):

                            s1r = s1row.iloc[0]

                            s1_name = normalize_advanced(
                                s1r.business_name
                            )

                            s1_addr = normalize_advanced(
                                s1r.business_address
                            )

                            name_sim = (
                                ratio(name, s1_name) / 100
                            )

                            addr_sim = (
                                ratio(address, s1_addr) / 100
                                if address and s1_addr
                                else 0.0
                            )

                            nums1 = set(
                                re.findall(
                                    r"\d+",
                                    address
                                )
                            )

                            nums2 = set(
                                re.findall(
                                    r"\d+",
                                    s1_addr
                                )
                            )

                            shared_numbers = len(
                                nums1 & nums2
                            )

                            name_only_pairs.append({
                                "sid": sid,
                                "eid": eid,
                                "true": is_true,
                                "name_sim": name_sim,
                                "addr_sim": addr_sim,
                                "shared_numbers": shared_numbers,
                                "s1_addr_empty": not bool(s1_addr),
                                "src_addr_empty": not bool(address)
                            })

                processed += len(chunk)

            if processed % 1000000 == 0:
                print(
                    source_name,
                    "| processed:",
                    f"{processed:,}"
                )

        print(
            source_name,
            "complete"
        )

    # --------------------------------------------------------
    # Baseline precision statistics
    # --------------------------------------------------------

    def precision(tp, fp):
        return (
            tp / (tp + fp)
            if tp + fp
            else 1.0
        )

    print("\n" + "=" * 70)
    print("V1.1 CANDIDATE BREAKDOWN")
    print("=" * 70)

    print(
        "Total candidates:",
        f"{stats['total_candidates']:,}"
    )

    print(
        "True candidates:",
        f"{stats['total_tp']:,}"
    )

    print(
        "Address only:",
        f"{stats['address_only']:,}",
        "| TP:",
        f"{stats['address_tp']:,}",
        "| FP:",
        f"{stats['address_fp']:,}",
        "| Precision:",
        round(
            precision(
                stats["address_tp"],
                stats["address_fp"]
            ),
            4
        )
    )

    print(
        "Name only:",
        f"{stats['name_only']:,}",
        "| TP:",
        f"{stats['name_tp']:,}",
        "| FP:",
        f"{stats['name_fp']:,}",
        "| Precision:",
        round(
            precision(
                stats["name_tp"],
                stats["name_fp"]
            ),
            4
        )
    )

    print(
        "Both:",
        f"{stats['both']:,}",
        "| TP:",
        f"{stats['both_tp']:,}",
        "| FP:",
        f"{stats['both_fp']:,}",
        "| Precision:",
        round(
            precision(
                stats["both_tp"],
                stats["both_fp"]
            ),
            4
        )
    )

    # --------------------------------------------------------
    # Analyze name-only candidates
    # --------------------------------------------------------

    df = pd.DataFrame(name_only_pairs)

    print("\nName-only detailed rows:", len(df))

    if len(df):

        print("\nName-only TRUE/FALSE by address similarity:")

        for threshold in [
            0.00,
            0.20,
            0.30,
            0.40,
            0.50,
            0.60,
            0.70,
            0.80
        ]:

            selected = df[
                (df["addr_sim"] >= threshold)
                |
                df["s1_addr_empty"]
                |
                df["src_addr_empty"]
            ]

            tp = int(selected["true"].sum())
            total = len(selected)
            fp = total - tp

            print(
                f"addr_sim >= {threshold:.2f} | "
                f"kept={total:,} | "
                f"TP={tp:,} | "
                f"FP={fp:,} | "
                f"precision={precision(tp, fp):.4f}"
            )

        print("\nName-only with shared address number:")

        for minimum in [1]:

            selected = df[
                (df["shared_numbers"] >= minimum)
                |
                df["s1_addr_empty"]
                |
                df["src_addr_empty"]
            ]

            tp = int(selected["true"].sum())
            total = len(selected)
            fp = total - tp

            print(
                f"shared_numbers >= {minimum} | "
                f"kept={total:,} | "
                f"TP={tp:,} | "
                f"FP={fp:,} | "
                f"precision={precision(tp, fp):.4f}"
            )

    print("\n" + "=" * 70)
    print("DIAGNOSTIC COMPLETE")
    print("=" * 70)

    del name_only_pairs
    del df
    gc.collect()

======================================================================
V1.1 PRECISION DIAGNOSTIC
======================================================================
MISSING OBJECTS: ['s1_val', 'val_ids', 'gt_lookup']

Do NOT continue.
Send me this output and I will give you the recovery cell.

In [ ]:
# ============================================================
# RECOVER VALIDATION OBJECTS AFTER COLAB RESTART
# ============================================================

import os
import gc
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

BASE = "/content/amazon_ml_challenge/student_resource"
TRAIN_DIR = f"{BASE}/dataset/train"

S1_TRAIN = f"{TRAIN_DIR}/train_source1.tsv"
GT_FILE  = f"{TRAIN_DIR}/train_ground_truth.tsv"

print("=" * 70)
print("RECOVERING VALIDATION DATA")
print("=" * 70)

# ------------------------------------------------------------
# Load Source 1
# ------------------------------------------------------------

print("Loading training Source 1...")

s1_all = pd.read_csv(
    S1_TRAIN,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("Source 1 rows:", len(s1_all))

# ------------------------------------------------------------
# Load ground truth
# ------------------------------------------------------------

print("Loading ground truth...")

gt_df = pd.read_csv(
    GT_FILE,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("Ground-truth rows:", len(gt_df))

# ------------------------------------------------------------
# Ground-truth lookup
# ------------------------------------------------------------

gt_lookup = {}

for row in gt_df.itertuples(index=False):

    sid = str(row.source1_entity_id)

    value = str(
        row.matched_entity_ids
    ).strip()

    if value:
        gt_lookup[sid] = set(
            x.strip()
            for x in value.split(",")
            if x.strip()
        )
    else:
        gt_lookup[sid] = set()

# ------------------------------------------------------------
# IMPORTANT:
# Recreate the same 2,000-S1 validation design
# using deterministic random_state=42.
#
# We use train_test_split so the validation IDs are
# deterministic and do not depend on dataframe order
# after the restart.
# ------------------------------------------------------------

_, s1_val = train_test_split(
    s1_all,
    test_size=2000,
    random_state=42
)

s1_val = s1_val.reset_index(
    drop=True
)

val_ids = s1_val[
    "entity_id"
].astype(str).tolist()

# ------------------------------------------------------------
# Training IDs
# ------------------------------------------------------------

train_ids = s1_all[
    ~s1_all["entity_id"].isin(val_ids)
]["entity_id"].astype(str).tolist()

# ------------------------------------------------------------
# Validation lookup
# ------------------------------------------------------------

s1_val_lookup = (
    s1_val
    .set_index("entity_id")
    .to_dict("index")
)

# ------------------------------------------------------------
# Check
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("✅ VALIDATION OBJECTS RECOVERED")
print("=" * 70)

print(
    "All Source 1:",
    len(s1_all)
)

print(
    "Validation S1:",
    len(s1_val)
)

print(
    "Training S1:",
    len(train_ids)
)

print(
    "Validation IDs:",
    len(val_ids)
)

print(
    "Ground-truth entries:",
    len(gt_lookup)
)

# Ground truth coverage
covered = sum(
    sid in gt_lookup
    for sid in val_ids
)

print(
    "Validation IDs with GT:",
    covered
)

print(
    "Validation IDs with at least one true match:",
    sum(
        bool(gt_lookup.get(sid, set()))
        for sid in val_ids
    )
)

print("\nSample validation IDs:")
print(val_ids[:10])

# ------------------------------------------------------------
# Make sure normalization functions exist
# ------------------------------------------------------------

if "normalize_advanced" not in globals():

    import re
    import unicodedata

    def normalize_advanced(text):

        if pd.isna(text):
            return ""

        text = str(text).lower().strip()

        text = unicodedata.normalize(
            "NFKC",
            text
        )

        replacements = {
            "&": " and ",
            "street": " st ",
            "road": " rd ",
            "avenue": " ave ",
            "drive": " dr ",
            "boulevard": " blvd ",
            "highway": " hwy ",
            "lane": " ln ",
            "parkway": " pkwy ",
            "place": " pl ",
            "suite": " ste "
        }

        for old, new in replacements.items():
            text = text.replace(old, new)

        text = re.sub(
            r"[^\w\s]",
            " ",
            text
        )

        text = re.sub(
            r"\s+",
            " ",
            text
        )

        return text.strip()


if "normalize_country" not in globals():

    def normalize_country(text):

        if pd.isna(text):
            return ""

        return str(text).lower().strip()


print("\nNormalization functions: READY")

gc.collect()

======================================================================
RECOVERING VALIDATION DATA
======================================================================
Loading training Source 1...
Source 1 rows: 2206821
Loading ground truth...
Ground-truth rows: 2206821

======================================================================
✅ VALIDATION OBJECTS RECOVERED
======================================================================
All Source 1: 2206821
Validation S1: 2000
Training S1: 2204821
Validation IDs: 2000
Ground-truth entries: 2206821
Validation IDs with GT: 2000
Validation IDs with at least one true match: 1880

Sample validation IDs:
['S1-53356671', 'S1-320151505', 'S1-938947364', 'S1-195839862', 'S1-655046555', 'S1-758070915', 'S1-169338169', 'S1-796421498', 'S1-802535179', 'S1-97176033']

Normalization functions: READY

0

In [ ]:
# ============================================================
# V1.1 PRECISION + F0.5 DIAGNOSTIC — RECOVERED VALIDATION
# ============================================================

import pandas as pd
import numpy as np
import re
from collections import defaultdict
from rapidfuzz.fuzz import ratio

TRAIN_S2 = f"{TRAIN_DIR}/train_source2.tsv"
TRAIN_S3 = f"{TRAIN_DIR}/train_source3.tsv"

print("=" * 70)
print("V1.1 PRECISION + F0.5 DIAGNOSTIC")
print("=" * 70)

# ------------------------------------------------------------
# FAST LOOKUP — IMPORTANT
# ------------------------------------------------------------

s1_lookup_val = (
    s1_val
    .set_index("entity_id")
    .to_dict("index")
)

print("Validation S1 lookup:", len(s1_lookup_val))

# ------------------------------------------------------------
# EXACT NORMALIZED INDEXES
# ------------------------------------------------------------

name_map = defaultdict(list)
address_map = defaultdict(list)

for sid, r in s1_lookup_val.items():

    country = normalize_country(
        r["country"]
    )

    name = normalize_advanced(
        r["business_name"]
    )

    address = normalize_advanced(
        r["business_address"]
    )

    if name:
        name_map[
            (country, name)
        ].append(sid)

    if address:
        address_map[
            (country, address)
        ].append(sid)

print("Exact name keys:", len(name_map))
print("Exact address keys:", len(address_map))

# ------------------------------------------------------------
# PREDICTION SETS
#
# Baseline:
#   exact normalized address + country
#   OR unique exact normalized name + country
#
# Variants:
#   A = baseline
#   B = name-only requires address similarity >= 0.30
#   C = name-only requires address similarity >= 0.40
#   D = name-only requires address similarity >= 0.50
#   E = name-only requires shared address number
# ------------------------------------------------------------

pred_A = defaultdict(set)
pred_B = defaultdict(set)
pred_C = defaultdict(set)
pred_D = defaultdict(set)
pred_E = defaultdict(set)

# Detailed counters
stats = {
    "address_exact": 0,
    "name_only": 0,
    "both": 0,

    "name_only_tp": 0,
    "name_only_fp": 0,

    "name_sim_030": 0,
    "name_sim_040": 0,
    "name_sim_050": 0,

    "name_num_shared": 0,
}

# ------------------------------------------------------------
# NUMBER EXTRACTION
# ------------------------------------------------------------

def extract_numbers(text):

    if not text:
        return set()

    return set(
        re.findall(
            r"\d+",
            text
        )
    )

# ------------------------------------------------------------
# F0.5
# ------------------------------------------------------------

def calculate_entity_f05(predictions):

    scores = []

    for sid in val_ids:

        true_ids = gt_lookup.get(
            sid,
            set()
        )

        predicted_ids = predictions.get(
            sid,
            set()
        )

        tp = len(
            true_ids & predicted_ids
        )

        fp = len(
            predicted_ids - true_ids
        )

        fn = len(
            true_ids - predicted_ids
        )

        # Exact challenge definition
        if tp == 0:

            score = (
                1.0
                if fp == 0 and fn == 0
                else 0.0
            )

        else:

            precision = tp / (
                tp + fp
            )

            recall = tp / (
                tp + fn
            )

            beta2 = 0.25

            score = (
                1.25
                * precision
                * recall
                /
                (
                    beta2 * precision
                    + recall
                )
            )

        scores.append(score)

    return float(
        np.mean(scores)
    )

# ------------------------------------------------------------
# PROCESS TRAINING SOURCE
# ------------------------------------------------------------

def process_source(path, source_name):

    rows = 0
    candidates = 0

    print(
        f"\nScanning {source_name}..."
    )

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=100000
    ):

        for row in chunk.itertuples(
            index=False
        ):

            eid = row.entity_id

            country = normalize_country(
                row.country
            )

            name = normalize_advanced(
                row.business_name
            )

            address = normalize_advanced(
                row.business_address
            )

            # --------------------------------------------
            # Exact address candidates
            # --------------------------------------------

            address_candidates = set(
                address_map.get(
                    (country, address),
                    []
                )
            ) if address else set()

            # --------------------------------------------
            # Exact UNIQUE name candidates
            # --------------------------------------------

            name_candidates = set()

            if name:

                name_ids = name_map.get(
                    (country, name),
                    []
                )

                if len(name_ids) == 1:
                    name_candidates.add(
                        name_ids[0]
                    )

            # --------------------------------------------
            # Categorize
            # --------------------------------------------

            both = (
                address_candidates
                &
                name_candidates
            )

            address_only = (
                address_candidates
                -
                name_candidates
            )

            name_only = (
                name_candidates
                -
                address_candidates
            )

            stats["both"] += len(both)
            stats["address_exact"] += len(
                address_only
            )
            stats["name_only"] += len(
                name_only
            )

            # --------------------------------------------
            # BASELINE A
            # --------------------------------------------

            baseline_candidates = (
                address_candidates
                |
                name_candidates
            )

            for sid in baseline_candidates:

                pred_A[sid].add(eid)

            candidates += len(
                baseline_candidates
            )

            # --------------------------------------------
            # Address-exact candidates are ALWAYS kept
            # in all variants.
            # --------------------------------------------

            for sid in address_candidates:

                pred_B[sid].add(eid)
                pred_C[sid].add(eid)
                pred_D[sid].add(eid)
                pred_E[sid].add(eid)

            # --------------------------------------------
            # Name-only filtering
            # --------------------------------------------

            if name_only:

                for sid in name_only:

                    s1row = s1_lookup_val.get(
                        sid
                    )

                    if s1row is None:
                        continue

                    s1_address = normalize_advanced(
                        s1row["business_address"]
                    )

                    s1_numbers = extract_numbers(
                        s1_address
                    )

                    source_numbers = extract_numbers(
                        address
                    )

                    shared_numbers = (
                        s1_numbers
                        &
                        source_numbers
                    )

                    address_sim = (
                        ratio(
                            s1_address,
                            address
                        ) / 100.0
                        if s1_address and address
                        else 0.0
                    )

                    # B: >= 0.30
                    if address_sim >= 0.30:

                        pred_B[sid].add(eid)
                        stats["name_sim_030"] += 1

                    # C: >= 0.40
                    if address_sim >= 0.40:

                        pred_C[sid].add(eid)
                        stats["name_sim_040"] += 1

                    # D: >= 0.50
                    if address_sim >= 0.50:

                        pred_D[sid].add(eid)
                        stats["name_sim_050"] += 1

                    # E: shared address number
                    if shared_numbers:

                        pred_E[sid].add(eid)
                        stats["name_num_shared"] += 1

                    # ------------------------------------------------
                    # Name-only TP / FP for diagnostic precision
                    # ------------------------------------------------

                    true_ids = gt_lookup.get(
                        sid,
                        set()
                    )

                    if eid in true_ids:
                        stats["name_only_tp"] += 1
                    else:
                        stats["name_only_fp"] += 1

            rows += 1

        if rows % 1_000_000 == 0:

            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"baseline candidate links: "
                f"{candidates:,}"
            )

    print(
        f"{source_name} COMPLETE | "
        f"rows: {rows:,} | "
        f"baseline candidates: {candidates:,}"
    )

# ------------------------------------------------------------
# RUN BOTH SOURCES
# ------------------------------------------------------------

process_source(
    TRAIN_S2,
    "Source 2"
)

process_source(
    TRAIN_S3,
    "Source 3"
)

# ------------------------------------------------------------
# CALCULATE F0.5
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("F0.5 RESULTS")
print("=" * 70)

f05_A = calculate_entity_f05(pred_A)
f05_B = calculate_entity_f05(pred_B)
f05_C = calculate_entity_f05(pred_C)
f05_D = calculate_entity_f05(pred_D)
f05_E = calculate_entity_f05(pred_E)

print(
    f"V1.1 baseline                 : {f05_A:.6f}"
)

print(
    f"Name-only address sim >= 0.30 : {f05_B:.6f}"
)

print(
    f"Name-only address sim >= 0.40 : {f05_C:.6f}"
)

print(
    f"Name-only address sim >= 0.50 : {f05_D:.6f}"
)

print(
    f"Name-only shared number        : {f05_E:.6f}"
)

print("\n" + "=" * 70)
print("NAME-ONLY PRECISION")
print("=" * 70)

tp = stats["name_only_tp"]
fp = stats["name_only_fp"]

precision = (
    tp / (tp + fp)
    if tp + fp
    else 0
)

print(
    "Name-only pairs:",
    tp + fp
)

print(
    "Name-only TP:",
    tp
)

print(
    "Name-only FP:",
    fp
)

print(
    f"Name-only precision: {precision:.4f}"
)

print("\n" + "=" * 70)
print("FILTER COUNTS")
print("=" * 70)

print(
    "Name-only address sim >= 0.30:",
    stats["name_sim_030"]
)

print(
    "Name-only address sim >= 0.40:",
    stats["name_sim_040"]
)

print(
    "Name-only address sim >= 0.50:",
    stats["name_sim_050"]
)

print(
    "Name-only shared address number:",
    stats["name_num_shared"]
)

print("\n" + "=" * 70)
print("CANDIDATE CATEGORY COUNTS")
print("=" * 70)

print(
    "Address-only:",
    stats["address_exact"]
)

print(
    "Name-only:",
    stats["name_only"]
)

print(
    "Both name + address:",
    stats["both"]
)

print("\nDONE.")

======================================================================
V1.1 PRECISION + F0.5 DIAGNOSTIC
======================================================================
Validation S1 lookup: 2000
Exact name keys: 1995
Exact address keys: 2000

Scanning Source 2...
Source 2: 1,000,000 rows | baseline candidate links: 2,201
Source 2: 2,000,000 rows | baseline candidate links: 4,451
Source 2: 3,000,000 rows | baseline candidate links: 6,661
Source 2: 4,000,000 rows | baseline candidate links: 8,916
Source 2: 5,000,000 rows | baseline candidate links: 11,146
Source 2 COMPLETE | rows: 5,034,616 | baseline candidates: 11,222

Scanning Source 3...
Source 3: 1,000,000 rows | baseline candidate links: 2,154
Source 3: 2,000,000 rows | baseline candidate links: 4,409
Source 3: 3,000,000 rows | baseline candidate links: 6,550
Source 3: 4,000,000 rows | baseline candidate links: 8,716
Source 3: 5,000,000 rows | baseline candidate links: 10,968
Source 3 COMPLETE | rows: 5,285,603 | baseline candidates: 11,580

======================================================================
F0.5 RESULTS
======================================================================
V1.1 baseline                 : 0.386293
Name-only address sim >= 0.30 : 0.384608
Name-only address sim >= 0.40 : 0.437803
Name-only address sim >= 0.50 : 0.484277
Name-only shared number        : 0.465703

======================================================================
NAME-ONLY PRECISION
======================================================================
Name-only pairs: 21856
Name-only TP: 1364
Name-only FP: 20492
Name-only precision: 0.0624

======================================================================
FILTER COUNTS
======================================================================
Name-only address sim >= 0.30: 17145
Name-only address sim >= 0.40: 4624
Name-only address sim >= 0.50: 1433
Name-only shared address number: 1256

======================================================================
CANDIDATE CATEGORY COUNTS
======================================================================
Address-only: 821
Name-only: 21856
Both name + address: 125

DONE.

In [ ]:
# ============================================================
# AMAZON ML CHALLENGE — RAM-SAFE V5 RECOVERY
# Step 1: Recover validation S1 + ground truth + V5 model
# ============================================================

import os
import gc
import pandas as pd
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier

ROOT = "/content/amazon_ml_challenge/student_resource"

TRAIN_S1 = f"{ROOT}/dataset/train/train_source1.tsv"
TRAIN_GT = f"{ROOT}/dataset/train/train_ground_truth.tsv"

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "Amazon-ML-Challenge-2026/ml/"
    "V5_ML_Final/V5_ML_Final/v5_model.cbm"
)

# ------------------------------------------------------------
# 1. Load ONLY Source 1
# ------------------------------------------------------------

print("Loading train Source 1 only...")

s1_all = pd.read_csv(
    TRAIN_S1,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("S1 shape:", s1_all.shape)

# ------------------------------------------------------------
# 2. Load ground truth
# ------------------------------------------------------------

print("Loading ground truth...")

gt = pd.read_csv(
    TRAIN_GT,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("GT shape:", gt.shape)

# ------------------------------------------------------------
# 3. Recreate EXACT validation split
# ------------------------------------------------------------

train_s1, s1_val = train_test_split(
    s1_all,
    test_size=2000,
    random_state=42
)

s1_val = s1_val.reset_index(drop=True)

val_ids = set(s1_val["entity_id"])

# Ground truth lookup ONLY for validation
gt_lookup = {}

for row in gt.itertuples(index=False):

    sid = row.source1_entity_id

    if sid in val_ids:

        value = row.matched_entity_ids

        if value:
            ids = set(
                x.strip()
                for x in value.split(",")
                if x.strip()
            )
        else:
            ids = set()

        gt_lookup[sid] = ids

# ------------------------------------------------------------
# 4. Validation lookup
# ------------------------------------------------------------

s1_val_lookup = (
    s1_val
    .set_index("entity_id")
    .to_dict("index")
)

# ------------------------------------------------------------
# 5. Basic validation statistics
# ------------------------------------------------------------

singleton_count = sum(
    1
    for sid in val_ids
    if len(gt_lookup.get(sid, set())) == 0
)

matched_count = len(val_ids) - singleton_count

print("\n" + "=" * 60)
print("V5 VALIDATION RECOVERY")
print("=" * 60)

print("Validation S1:", len(val_ids))
print("Validation GT:", len(gt_lookup))
print("With >=1 true match:", matched_count)
print("True singletons:", singleton_count)
print(
    "Singleton %:",
    round(100 * singleton_count / len(val_ids), 2)
)

# ------------------------------------------------------------
# 6. Load V5 model ONLY
# ------------------------------------------------------------

print("\nLoading V5 CatBoost model...")

v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

print("V5 model loaded.")
print("Model trees:", v5_model.tree_count_)
print("Model features:", v5_model.feature_count_)

# ------------------------------------------------------------
# 7. Clean unnecessary object
# ------------------------------------------------------------

del train_s1
del gt
gc.collect()

print("\nRAM-safe recovery COMPLETE.")
print("Do NOT load S2/S3 yet.")

Loading train Source 1 only...
S1 shape: (2206821, 4)
Loading ground truth...
GT shape: (2206821, 2)

============================================================
V5 VALIDATION RECOVERY
============================================================
Validation S1: 2000
Validation GT: 2000
With >=1 true match: 1880
True singletons: 120
Singleton %: 6.0

Loading V5 CatBoost model...
V5 model loaded.
Model trees: 670

AttributeError: 'CatBoostClassifier' object has no attribute 'feature_count_'

In [ ]:
print("V5 model loaded successfully.")
print("Model trees:", v5_model.tree_count_)
print("Model feature names:", len(v5_model.feature_names_))
print("Feature names:", v5_model.feature_names_)

print("\nValidation S1:", len(val_ids))
print("Validation GT:", len(gt_lookup))
print("Singletons:", singleton_count)
print("Recovery successful.")

V5 model loaded successfully.
Model trees: 670
Model feature names: 20
Feature names: ['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard', 'address_jaccard', 'shared_name_token_count', 'shared_address_token_count', 'shared_address_number_count', 'name_length_diff', 'address_length_diff', 'name_length_ratio', 'address_length_ratio', 'similarity_gap', 'max_similarity', 'similarity_product', 'token_overlap_gap']

Validation S1: 2000
Validation GT: 2000
Singletons: 120
Recovery successful.

In [ ]:
# ============================================================
# RAM CLEANUP BEFORE VALIDATION INDEX BUILD
# ============================================================

import gc

# We no longer need the full 2.2M-row S1 dataframe
if "s1_all" in globals():
    del s1_all

# These were already deleted in the recovery cell, but safe to check
if "train_s1" in globals():
    del train_s1

if "gt" in globals():
    del gt

gc.collect()

print("RAM cleanup complete.")
print("Validation S1:", len(s1_val))
print("Validation IDs:", len(val_ids))
print("GT lookup:", len(gt_lookup))
print("V5 model:", v5_model.tree_count_, "trees /", len(v5_model.feature_names_), "features")

RAM cleanup complete.
Validation S1: 2000
Validation IDs: 2000
GT lookup: 2000
V5 model: 670 trees / 20 features

In [ ]:
# ============================================================
# STEP 2A — RESTORE NORMALIZATION FUNCTION
# ============================================================

import re
import unicodedata

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# Quick verification — only 2,000 validation rows
val_name_tokens = set()
val_address_tokens = set()

for row in s1_val.itertuples(index=False):
    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    val_name_tokens.update(name.split())
    val_address_tokens.update(address.split())

print("Normalization function restored.")
print("Validation name tokens:", len(val_name_tokens))
print("Validation address tokens:", len(val_address_tokens))

Normalization function restored.
Validation name tokens: 2388
Validation address tokens: 5554

In [ ]:
# ============================================================
# STEP 2B — RAM-SAFE S2/S3 TOKEN FREQUENCY SCAN
# ============================================================

from collections import Counter
import pandas as pd
import gc

name_freq_val = Counter()
address_freq_val = Counter()

for path, source_name in [
    (TRAIN_S2, "TRAIN S2"),
    (TRAIN_S3, "TRAIN S3")
]:
    print("\n" + "=" * 60)
    print("Scanning:", source_name)
    print("=" * 60)

    rows_processed = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_name", "business_address"],
        dtype=str,
        keep_default_na=False,
        chunksize=100000
    ):

        for value in chunk["business_name"]:
            text = normalize_advanced(value)
            for token in set(text.split()):
                if token in val_name_tokens:
                    name_freq_val[token] += 1

        for value in chunk["business_address"]:
            text = normalize_advanced(value)
            for token in set(text.split()):
                if token in val_address_tokens:
                    address_freq_val[token] += 1

        rows_processed += len(chunk)

        if rows_processed % 1_000_000 == 0:
            print(f"{source_name}: {rows_processed:,} rows processed")

        del chunk

    gc.collect()

print("\n" + "=" * 60)
print("TOKEN FREQUENCY SCAN COMPLETE")
print("=" * 60)

print("Name tokens counted:", len(name_freq_val))
print("Address tokens counted:", len(address_freq_val))

print("\nName tokens <=500:",
      sum(1 for x in name_freq_val.values() if x <= 500))

print("Address tokens <=500:",
      sum(1 for x in address_freq_val.values() if x <= 500))

print("\nRAM-safe scan completed.")

============================================================
Scanning: TRAIN S2
============================================================
TRAIN S2: 1,000,000 rows processed
TRAIN S2: 2,000,000 rows processed
TRAIN S2: 3,000,000 rows processed
TRAIN S2: 4,000,000 rows processed
TRAIN S2: 5,000,000 rows processed

============================================================
Scanning: TRAIN S3
============================================================
TRAIN S3: 1,000,000 rows processed
TRAIN S3: 2,000,000 rows processed
TRAIN S3: 3,000,000 rows processed
TRAIN S3: 4,000,000 rows processed
TRAIN S3: 5,000,000 rows processed

============================================================
TOKEN FREQUENCY SCAN COMPLETE
============================================================
Name tokens counted: 2388
Address tokens counted: 5544

Name tokens <=500: 1001
Address tokens <=500: 2040

RAM-safe scan completed.

In [ ]:
# ============================================================
# STEP 3 — RAM-SAFE VALIDATION BLOCKER INDEX
# ============================================================

from collections import defaultdict
import pandas as pd
import gc
import time

RARE_LIMIT = 500

# ------------------------------------------------------------
# Build validation S1 lookup structures
# ------------------------------------------------------------

s1_lookup = {}
val_name_map = defaultdict(set)
val_addr_map = defaultdict(set)

for row in s1_val.itertuples(index=False):

    sid = row.entity_id
    country = normalize_advanced(row.country)
    name = normalize_advanced(row.business_name)
    address = normalize_advanced(row.business_address)

    s1_lookup[sid] = {
        "name": name,
        "address": address,
        "country": country
    }

    if name:
        val_name_map[(country, name)].add(sid)

    if address:
        val_addr_map[(country, address)].add(sid)


# ------------------------------------------------------------
# Rare-token → validation S1 maps
# ------------------------------------------------------------

rare_name_to_s1 = defaultdict(set)
rare_addr_to_s1 = defaultdict(set)

for sid, row in s1_lookup.items():

    country = row["country"]

    for token in set(row["name"].split()):
        if name_freq_val.get(token, 10**9) <= RARE_LIMIT:
            rare_name_to_s1[(country, token)].add(sid)

    for token in set(row["address"].split()):
        if address_freq_val.get(token, 10**9) <= RARE_LIMIT:
            rare_addr_to_s1[(country, token)].add(sid)


print("=" * 65)
print("VALIDATION BLOCKER INDEX READY")
print("=" * 65)
print("Validation S1:", len(s1_lookup))
print("Exact name keys:", len(val_name_map))
print("Exact address keys:", len(val_addr_map))
print("Rare name keys:", len(rare_name_to_s1))
print("Rare address keys:", len(rare_addr_to_s1))

=================================================================
VALIDATION BLOCKER INDEX READY
=================================================================
Validation S1: 2000
Exact name keys: 1995
Exact address keys: 2000
Rare name keys: 1002
Rare address keys: 2045

In [ ]:
# ============================================================
# STEP 4 — RAM-SAFE VALIDATION CANDIDATE SCAN — TRAIN S2
# ============================================================

import pandas as pd
import gc
import time
from collections import defaultdict

candidate_lookup_s2 = defaultdict(set)

rows_processed = 0
links_added = 0
start_time = time.time()

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    for row in chunk.itertuples(index=False):

        eid = row.entity_id
        country = normalize_advanced(row.country)
        name = normalize_advanced(row.business_name)
        address = normalize_advanced(row.business_address)

        found_s1 = set()

        # ----------------------------------------------------
        # BLOCK 1 — exact name + country
        # ----------------------------------------------------
        if name:
            found_s1.update(
                val_name_map.get((country, name), ())
            )

        # ----------------------------------------------------
        # BLOCK 2 — exact address + country
        # ----------------------------------------------------
        if address:
            found_s1.update(
                val_addr_map.get((country, address), ())
            )

        # ----------------------------------------------------
        # BLOCK 3 — rare name tokens
        # ----------------------------------------------------
        for token in set(name.split()):

            if name_freq_val.get(token, 10**9) <= RARE_LIMIT:

                found_s1.update(
                    rare_name_to_s1.get(
                        (country, token),
                        ()
                    )
                )

        # ----------------------------------------------------
        # BLOCK 4 — rare address tokens
        # ----------------------------------------------------
        for token in set(address.split()):

            if address_freq_val.get(token, 10**9) <= RARE_LIMIT:

                found_s1.update(
                    rare_addr_to_s1.get(
                        (country, token),
                        ()
                    )
                )

        # ----------------------------------------------------
        # Store only validation S1 -> S2 candidates
        # ----------------------------------------------------
        for sid in found_s1:
            candidate_lookup_s2[sid].add(eid)
            links_added += 1

    rows_processed += len(chunk)

    if rows_processed % 1_000_000 == 0:
        current_pairs = sum(
            len(x) for x in candidate_lookup_s2.values()
        )

        print(
            f"S2: {rows_processed:,} rows | "
            f"candidate links: {current_pairs:,}"
        )

    del chunk
    gc.collect()


elapsed = time.time() - start_time

print("\n" + "=" * 65)
print("S2 VALIDATION CANDIDATE SCAN COMPLETE")
print("=" * 65)

print("Rows scanned:", f"{rows_processed:,}")
print("S1 entities with candidates:", len(candidate_lookup_s2))
print("Candidate links:", f"{links_added:,}")
print("Elapsed:", round(elapsed / 60, 2), "minutes")

# ------------------------------------------------------------
# Candidate recall against ground truth
# ------------------------------------------------------------

total_true_s2 = 0
found_true_s2 = 0

for sid in val_ids:

    true_ids = {
        x for x in gt_lookup.get(sid, set())
        if x.startswith("S2-")
    }

    candidates = candidate_lookup_s2.get(sid, set())

    total_true_s2 += len(true_ids)
    found_true_s2 += len(true_ids & candidates)

missed_true_s2 = total_true_s2 - found_true_s2

print("\n" + "=" * 65)
print("S2 CANDIDATE RECALL")
print("=" * 65)

print("True S2 matches:", total_true_s2)
print("True S2 matches found:", found_true_s2)
print("True S2 matches missed:", missed_true_s2)

if total_true_s2:
    print(
        "Candidate recall:",
        f"{100 * found_true_s2 / total_true_s2:.2f}%"
    )

print(
    "Zero-candidate validation S1:",
    sum(
        1 for sid in val_ids
        if len(candidate_lookup_s2.get(sid, set())) == 0
    )
)

gc.collect()

S2: 1,000,000 rows | candidate links: 45,808
S2: 2,000,000 rows | candidate links: 91,625
S2: 3,000,000 rows | candidate links: 137,571
S2: 4,000,000 rows | candidate links: 183,282
S2: 5,000,000 rows | candidate links: 228,896

=================================================================
S2 VALIDATION CANDIDATE SCAN COMPLETE
=================================================================
Rows scanned: 5,034,616
S1 entities with candidates: 1884
Candidate links: 230,494
Elapsed: 4.01 minutes

=================================================================
S2 CANDIDATE RECALL
=================================================================
True S2 matches: 3279
True S2 matches found: 2661
True S2 matches missed: 618
Candidate recall: 81.15%
Zero-candidate validation S1: 116

0

In [ ]:
# ============================================================
# STEP 5 — DIAGNOSTIC BROADER BLOCKER — TRAIN S2
# Frequency limit: 2500
# NO FULL CANDIDATE TABLE STORED
# ============================================================

from collections import defaultdict
import pandas as pd
import gc
import time

TEST_LIMIT = 2500

# ------------------------------------------------------------
# Build broader validation S1 token maps
# ------------------------------------------------------------

broad_name_map = defaultdict(set)
broad_addr_map = defaultdict(set)

for sid, row in s1_lookup.items():

    country = row["country"]

    for token in set(row["name"].split()):
        if name_freq_val.get(token, 10**9) <= TEST_LIMIT:
            broad_name_map[(country, token)].add(sid)

    for token in set(row["address"].split()):
        if address_freq_val.get(token, 10**9) <= TEST_LIMIT:
            broad_addr_map[(country, token)].add(sid)


# ------------------------------------------------------------
# Reverse ground-truth lookup
# Only ~3k true S2 IDs, so this is tiny.
# ------------------------------------------------------------

true_s2_reverse = defaultdict(set)

for sid in val_ids:
    for eid in gt_lookup.get(sid, set()):
        if eid.startswith("S2-"):
            true_s2_reverse[eid].add(sid)


# ------------------------------------------------------------
# Scan S2
# ------------------------------------------------------------

rows_processed = 0
candidate_links = 0
found_true = set()

start_time = time.time()

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    for row in chunk.itertuples(index=False):

        eid = row.entity_id
        country = normalize_advanced(row.country)
        name = normalize_advanced(row.business_name)
        address = normalize_advanced(row.business_address)

        candidate_sids = set()

        # ----------------------------------------------------
        # Exact name / address
        # ----------------------------------------------------

        if name:
            candidate_sids.update(
                val_name_map.get((country, name), ())
            )

        if address:
            candidate_sids.update(
                val_addr_map.get((country, address), ())
            )

        # ----------------------------------------------------
        # Name: >=2 shared tokens
        # ----------------------------------------------------

        name_hits = defaultdict(int)

        for token in set(name.split()):

            if name_freq_val.get(token, 10**9) <= TEST_LIMIT:

                for sid in broad_name_map.get(
                    (country, token), ()
                ):
                    name_hits[sid] += 1

        for sid, count in name_hits.items():
            if count >= 2:
                candidate_sids.add(sid)

        # ----------------------------------------------------
        # Address: >=2 shared tokens
        # ----------------------------------------------------

        addr_hits = defaultdict(int)

        for token in set(address.split()):

            if address_freq_val.get(token, 10**9) <= TEST_LIMIT:

                for sid in broad_addr_map.get(
                    (country, token), ()
                ):
                    addr_hits[sid] += 1

        for sid, count in addr_hits.items():
            if count >= 2:
                candidate_sids.add(sid)

        # ----------------------------------------------------
        # Statistics only — don't store candidates
        # ----------------------------------------------------

        candidate_links += len(candidate_sids)

        # True-pair recall
        true_sids = true_s2_reverse.get(eid)

        if true_sids:
            found_true.update(
                true_sids & candidate_sids
            )

    rows_processed += len(chunk)

    if rows_processed % 1_000_000 == 0:
        print(
            f"S2: {rows_processed:,} rows | "
            f"candidate links: {candidate_links:,} | "
            f"true S1 recovered: {len(found_true):,}"
        )

    del chunk
    gc.collect()


elapsed = time.time() - start_time

total_true_s2 = sum(
    len(
        {
            x for x in gt_lookup.get(sid, set())
            if x.startswith("S2-")
        }
    )
    for sid in val_ids
)

# Count actual true pairs recovered.
# We need the pair-level count, not just S1 count.
found_true_pairs = 0

for sid in val_ids:
    true_ids = {
        x for x in gt_lookup.get(sid, set())
        if x.startswith("S2-")
    }

    # We didn't store candidate pairs, so reconstruct recovery
    # from the reverse set gathered above.
    found_true_pairs += sum(
        1
        for eid in true_ids
        if sid in true_s2_reverse.get(eid, set())
        and eid in set()  # placeholder prevented below
    )

# ------------------------------------------------------------
# The pair-level recovery needs a separate tiny pass over
# the TRUE S2 IDs. We will do that next if needed.
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("BROADER S2 BLOCKER DIAGNOSTIC")
print("=" * 65)
print("Frequency limit:", TEST_LIMIT)
print("Rows scanned:", f"{rows_processed:,}")
print("Candidate links:", f"{candidate_links:,}")
print("Elapsed:", round(elapsed / 60, 2), "minutes")
print("Validation S1 recovered:", len(found_true))
print("Total validation S1:", len(val_ids))

print("\nNOTE:")
print("The S1 recovery count above is only an intermediate diagnostic.")
print("We will calculate exact pair-level recall next.")

S2: 1,000,000 rows | candidate links: 6,719 | true S1 recovered: 422
S2: 2,000,000 rows | candidate links: 13,539 | true S1 recovered: 748
S2: 3,000,000 rows | candidate links: 20,223 | true S1 recovered: 1,006
S2: 4,000,000 rows | candidate links: 27,072 | true S1 recovered: 1,216
S2: 5,000,000 rows | candidate links: 33,768 | true S1 recovered: 1,371

=================================================================
BROADER S2 BLOCKER DIAGNOSTIC
=================================================================
Frequency limit: 2500
Rows scanned: 5,034,616
Candidate links: 33,994
Elapsed: 4.29 minutes
Validation S1 recovered: 1374
Total validation S1: 2000

NOTE:
The S1 recovery count above is only an intermediate diagnostic.
We will calculate exact pair-level recall next.

In [ ]:
# ============================================================
# STEP 6 — TRUE S2 PAIR BLOCKING AUDIT
# ============================================================

from collections import defaultdict, Counter
import pandas as pd
import gc
import re
from rapidfuzz.fuzz import ratio

# ------------------------------------------------------------
# Build true S2 -> S1 mapping
# ------------------------------------------------------------

true_s2_to_s1 = {}

for sid in val_ids:
    for eid in gt_lookup.get(sid, set()):
        if eid.startswith("S2-"):
            true_s2_to_s1[eid] = sid

print("Known true S2 pairs:", len(true_s2_to_s1))

# ------------------------------------------------------------
# Statistics
# ------------------------------------------------------------

stats = Counter()

examples = {
    "missed": [],
    "exact_name": [],
    "exact_address": [],
    "name_2_rare": [],
    "addr_2_rare": [],
    "addr_3": [],
    "addr_2_sim30": []
}

# ------------------------------------------------------------
# Scan S2
# ------------------------------------------------------------

rows_processed = 0

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    for row in chunk.itertuples(index=False):

        eid = row.entity_id

        # Ignore the ~5M rows that aren't known true pairs
        if eid not in true_s2_to_s1:
            continue

        sid = true_s2_to_s1[eid]
        s1row = s1_lookup[sid]

        name1 = s1row["name"]
        addr1 = s1row["address"]
        country1 = s1row["country"]

        name2 = normalize_advanced(row.business_name)
        addr2 = normalize_advanced(row.business_address)
        country2 = normalize_advanced(row.country)

        same_country = country1 == country2

        name_tokens1 = set(name1.split())
        name_tokens2 = set(name2.split())

        addr_tokens1 = set(addr1.split())
        addr_tokens2 = set(addr2.split())

        shared_name = name_tokens1 & name_tokens2
        shared_addr = addr_tokens1 & addr_tokens2

        shared_numbers = (
            set(re.findall(r"\d+", addr1)) &
            set(re.findall(r"\d+", addr2))
        )

        name_sim = (
            ratio(name1, name2) / 100
            if name1 and name2 else 0
        )

        addr_sim = (
            ratio(addr1, addr2) / 100
            if addr1 and addr2 else 0
        )

        # ----------------------------------------------------
        # Individual signals
        # ----------------------------------------------------

        exact_name = (
            same_country
            and bool(name1)
            and name1 == name2
        )

        exact_addr = (
            same_country
            and bool(addr1)
            and addr1 == addr2
        )

        # V5-style blocker
        name_2_rare = (
            same_country
            and len(shared_name) >= 2
            and any(
                name_freq_val.get(t, 10**9) <= 500
                for t in shared_name
            )
            and name_sim >= 0.60
        )

        addr_2_rare = (
            same_country
            and len(shared_addr) >= 2
            and any(
                address_freq_val.get(t, 10**9) <= 500
                for t in shared_addr
            )
            and addr_sim >= 0.60
        )

        addr_3 = (
            same_country
            and len(shared_addr) >= 3
        )

        addr_2_sim30 = (
            same_country
            and len(shared_addr) >= 2
            and addr_sim >= 0.30
        )

        # ----------------------------------------------------
        # Record statistics
        # ----------------------------------------------------

        stats["total"] += 1

        if same_country:
            stats["same_country"] += 1

        if exact_name:
            stats["exact_name"] += 1

        if exact_addr:
            stats["exact_address"] += 1

        if name_2_rare:
            stats["name_2_rare"] += 1

        if addr_2_rare:
            stats["addr_2_rare"] += 1

        if addr_3:
            stats["addr_3"] += 1

        if addr_2_sim30:
            stats["addr_2_sim30"] += 1

        # Actual current V5 blocker
        current_v5 = (
            exact_name
            or exact_addr
            or name_2_rare
            or addr_2_rare
        )

        if current_v5:
            stats["current_v5"] += 1
        else:
            stats["current_v5_missed"] += 1

            if len(examples["missed"]) < 15:
                examples["missed"].append({
                    "s1": sid,
                    "s2": eid,
                    "name1": name1,
                    "name2": name2,
                    "addr1": addr1,
                    "addr2": addr2,
                    "country1": country1,
                    "country2": country2,
                    "shared_name": len(shared_name),
                    "shared_addr": len(shared_addr),
                    "shared_numbers": len(shared_numbers),
                    "name_sim": round(name_sim, 3),
                    "addr_sim": round(addr_sim, 3)
                })

    rows_processed += len(chunk)

    if rows_processed % 1_000_000 == 0:
        print(
            f"Scanned {rows_processed:,} rows | "
            f"true pairs found: {stats['total']:,}"
        )

    del chunk
    gc.collect()

# ------------------------------------------------------------
# Print results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TRUE S2 BLOCKING AUDIT")
print("=" * 70)

total = stats["total"]

print("True S2 pairs:", total)

for key, label in [
    ("same_country", "Same country"),
    ("exact_name", "Exact name + country"),
    ("exact_address", "Exact address + country"),
    ("name_2_rare", ">=2 rare name + sim >=0.60"),
    ("addr_2_rare", ">=2 rare address + sim >=0.60"),
    ("addr_3", ">=3 shared address tokens"),
    ("addr_2_sim30", ">=2 address tokens + sim >=0.30"),
    ("current_v5", "CURRENT V5 BLOCKER"),
]:
    count = stats[key]
    pct = 100 * count / total if total else 0
    print(f"{label:40s}: {count:5d}  ({pct:6.2f}%)")

print("\nCurrent V5 missed:",
      stats["current_v5_missed"])

print("\n" + "=" * 70)
print("EXAMPLES OF TRUE PAIRS MISSED BY CURRENT V5")
print("=" * 70)

for i, x in enumerate(examples["missed"], 1):
    print(f"\n--- MISS {i} ---")
    print("S1:", x["s1"])
    print("S2:", x["s2"])
    print("Name:", x["name1"], " <-> ", x["name2"])
    print("Address:", x["addr1"], " <-> ", x["addr2"])
    print("Country:", x["country1"], " <-> ", x["country2"])
    print(
        "Shared name:", x["shared_name"],
        "| Shared address:", x["shared_addr"],
        "| Shared numbers:", x["shared_numbers"]
    )
    print(
        "Name sim:", x["name_sim"],
        "| Address sim:", x["addr_sim"]
    )

gc.collect()

Known true S2 pairs: 3279
Scanned 1,000,000 rows | true pairs found: 661
Scanned 2,000,000 rows | true pairs found: 1,304
Scanned 3,000,000 rows | true pairs found: 1,940
Scanned 4,000,000 rows | true pairs found: 2,631
Scanned 5,000,000 rows | true pairs found: 3,262

======================================================================
TRUE S2 BLOCKING AUDIT
======================================================================
True S2 pairs: 3279
Same country                            :  3279  (100.00%)
Exact name + country                    :   684  ( 20.86%)
Exact address + country                 :   615  ( 18.76%)
>=2 rare name + sim >=0.60              :  1131  ( 34.49%)
>=2 rare address + sim >=0.60           :  1669  ( 50.90%)
>=3 shared address tokens               :  3116  ( 95.03%)
>=2 address tokens + sim >=0.30         :  3124  ( 95.27%)
CURRENT V5 BLOCKER                      :  2524  ( 76.97%)

Current V5 missed: 755

======================================================================
EXAMPLES OF TRUE PAIRS MISSED BY CURRENT V5
======================================================================

--- MISS 1 ---
S1: S1-757078074
S2: S2-308074507
Name: sa enbridge inc  <->  sa errgide errgide inc
Address: 17119 carriage dale court spring tx  <->
Country: us  <->  us
Shared name: 2 | Shared address: 0 | Shared numbers: 0
Name sim: 0.703 | Address sim: 0

--- MISS 2 ---
S1: S1-643898887
S2: S2-984226971
Name: taylor harbor senior  <->  taylor harbor partners
Address: 9219 falls creek trail albuquerque nm  <->
Country: us  <->  us
Shared name: 2 | Shared address: 0 | Shared numbers: 0
Name sim: 0.762 | Address sim: 0

--- MISS 3 ---
S1: S1-198841366
S2: S2-264172545
Name: the dent yoga  <->  the dent yoga center
Address: 294 lincoln st abington ma  <->  303 lincoln st abington ma
Country: us  <->  us
Shared name: 3 | Shared address: 4 | Shared numbers: 0
Name sim: 0.788 | Address sim: 0.885

--- MISS 4 ---
S1: S1-443154384
S2: S2-781289854
Name: span media limited  <->  limited span media
Address: d 298 basement defence colony new delhi delhi  <->  d 298 c 4 janak puri new delhi delhi
Country: india  <->  india
Shared name: 3 | Shared address: 4 | Shared numbers: 1
Name sim: 0.556 | Address sim: 0.617

--- MISS 5 ---
S1: S1-75762876
S2: S2-59326140
Name: a trusted canada llc  <->  a trusred canada llc
Address: 195 rodeo rd unit 220 casa grande az  <->  null 195 rodeo rd az casa grande
Country: us  <->  us
Shared name: 3 | Shared address: 6 | Shared numbers: 1
Name sim: 0.95 | Address sim: 0.735

--- MISS 6 ---
S1: S1-512287160
S2: S2-105895280
Name: boyle encore inc  <->  the boyle encore inc
Address: 691 main st unit 1 2 marion oh  <->  main st marion oh
Country: us  <->  us
Shared name: 3 | Shared address: 4 | Shared numbers: 0
Name sim: 0.889 | Address sim: 0.723

--- MISS 7 ---
S1: S1-153594731
S2: S2-209658522
Name: wilkinson meshflow llc  <->  wilkinson meshflow l l c
Address: 401 carpenter rd snohomish wa  <->
Country: us  <->  us
Shared name: 2 | Shared address: 0 | Shared numbers: 0
Name sim: 0.957 | Address sim: 0

--- MISS 8 ---
S1: S1-960182443
S2: S2-850046906
Name: gujarat energy  <->  gujarat energy ltd
Address: 83 sp mukherjee rd 4th floor kolkata kolkata kolkata howrah west bengal  <->  83 sp mukherjee rd 4th floor kolkata kolkata kolkata west bengal
Country: india  <->  india
Shared name: 2 | Shared address: 9 | Shared numbers: 2
Name sim: 0.875 | Address sim: 0.948

--- MISS 9 ---
S1: S1-805319803
S2: S2-134516401
Name: seven global pvt ltd  <->  seven pvt global ltd
Address: s no 40 digambar nagar maharashtra pune city pune  <->
Country: india  <->  india
Shared name: 4 | Shared address: 0 | Shared numbers: 0
Name sim: 0.8 | Address sim: 0

--- MISS 10 ---
S1: S1-976150307
S2: S2-837655809
Name: baba shree developers limited  <->  ப ப ஸ ர ட வலப பர ஸ ல ம ட ட
Address: new no 278 102 4th floor peters rd royapettah chennai tamil nadu  <->  a 278 102 chennai tamil nadu
Country: india  <->  india
Shared name: 0 | Shared address: 5 | Shared numbers: 2
Name sim: 0.109 | Address sim: 0.587

--- MISS 11 ---
S1: S1-631845594
S2: S2-847167076
Name: ear nose and throat health inc  <->  ear nose and throat
Address: 7 cherry circle rockland ma  <->  cherry circle rockland ma
Country: us  <->  us
Shared name: 4 | Shared address: 4 | Shared numbers: 0
Name sim: 0.776 | Address sim: 0.962

--- MISS 12 ---
S1: S1-577633788
S2: S2-367211974
Name: meor llc  <->  meor
Address: 3107 walnut creek dr unit a city of wilson nc  <->  walnut creek dr wilson nc
Country: us  <->  us
Shared name: 1 | Shared address: 5 | Shared numbers: 0
Name sim: 0.667 | Address sim: 0.714

--- MISS 13 ---
S1: S1-84668021
S2: S2-706975881
Name: raj consulting private limited  <->  र ज क सल ट ग प र इव ट ल म ट ड
Address: 712 plaza panchshil gamdevi mumbai maharashtra  <->  712 mumbai maharashtra
Country: india  <->  india
Shared name: 0 | Shared address: 3 | Shared numbers: 1
Name sim: 0.102 | Address sim: 0.647

--- MISS 14 ---
S1: S1-315679803
S2: S2-583454017
Name: 4 laboratories  <->  4 laboratories inc
Address: 3455 meadowlark dr edgewood ky  <->
Country: us  <->  us
Shared name: 2 | Shared address: 0 | Shared numbers: 0
Name sim: 0.875 | Address sim: 0

--- MISS 15 ---
S1: S1-407760885
S2: S2-879747468
Name: shivam consultants private limited  <->  ਸ ਵਮ ਕ ਸਲਟ ਟਸ ਪ ਰ ਈਵ ਟ ਲ ਮਟ ਡ
Address: sco 124 third floor new pizzare building amritsar punjab  <->  sco 124 amritsar punjab
Country: india  <->  india
Shared name: 0 | Shared address: 4 | Shared numbers: 1
Name sim: 0.095 | Address sim: 0.582

0

In [ ]:
# ============================================================
# STEP 7 — TRUE-PAIR ANCHOR COVERAGE AUDIT
# ============================================================

from collections import Counter
import pandas as pd
import re
import gc

# ------------------------------------------------------------
# Known true S2 pairs already created
# ------------------------------------------------------------

print("Known true S2 pairs:", len(true_s2_to_s1))

anchor_stats = Counter()

total = 0

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    for row in chunk.itertuples(index=False):

        eid = row.entity_id

        if eid not in true_s2_to_s1:
            continue

        sid = true_s2_to_s1[eid]
        s1row = s1_lookup[sid]

        name1 = s1row["name"]
        addr1 = s1row["address"]

        name2 = normalize_advanced(row.business_name)
        addr2 = normalize_advanced(row.business_address)

        name_tokens = set(name1.split()) & set(name2.split())
        addr_tokens = set(addr1.split()) & set(addr2.split())

        nums1 = set(re.findall(r"\d+", addr1))
        nums2 = set(re.findall(r"\d+", addr2))
        shared_nums = nums1 & nums2

        # Rare tokens according to validation-derived vocabulary
        rare_name_tokens = {
            t for t in name_tokens
            if name_freq_val.get(t, 10**9) <= 500
        }

        rare_addr_tokens = {
            t for t in addr_tokens
            if address_freq_val.get(t, 10**9) <= 500
        }

        total += 1

        # Individual anchors
        if len(name_tokens) >= 2:
            anchor_stats["name_2"] += 1

        if len(addr_tokens) >= 2:
            anchor_stats["addr_2"] += 1

        if len(addr_tokens) >= 3:
            anchor_stats["addr_3"] += 1

        if rare_name_tokens:
            anchor_stats["rare_name_any"] += 1

        if len(rare_name_tokens) >= 2:
            anchor_stats["rare_name_2"] += 1

        if rare_addr_tokens:
            anchor_stats["rare_addr_any"] += 1

        if len(rare_addr_tokens) >= 2:
            anchor_stats["rare_addr_2"] += 1

        if shared_nums:
            anchor_stats["shared_number"] += 1

        # Useful combinations
        if len(addr_tokens) >= 2 and shared_nums:
            anchor_stats["addr2_plus_number"] += 1

        if len(addr_tokens) >= 2 and rare_addr_tokens:
            anchor_stats["addr2_plus_rare"] += 1

        if len(name_tokens) >= 2 and rare_name_tokens:
            anchor_stats["name2_plus_rare"] += 1

        # Broad potential blocker
        if (
            len(addr_tokens) >= 2
            or len(name_tokens) >= 2
            or shared_nums
        ):
            anchor_stats["broad_union"] += 1

    del chunk
    gc.collect()

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TRUE-PAIR ANCHOR COVERAGE")
print("=" * 70)

print("Total true S2 pairs:", total)

checks = [
    ("name_2", ">=2 shared name tokens"),
    ("addr_2", ">=2 shared address tokens"),
    ("addr_3", ">=3 shared address tokens"),
    ("rare_name_any", ">=1 rare name token"),
    ("rare_name_2", ">=2 rare name tokens"),
    ("rare_addr_any", ">=1 rare address token"),
    ("rare_addr_2", ">=2 rare address tokens"),
    ("shared_number", ">=1 shared address number"),
    ("addr2_plus_number", ">=2 address tokens + number"),
    ("addr2_plus_rare", ">=2 address tokens + rare address token"),
    ("name2_plus_rare", ">=2 name tokens + rare name token"),
    ("broad_union", "name2 OR addr2 OR shared number"),
]

for key, label in checks:
    n = anchor_stats[key]
    pct = 100 * n / total if total else 0
    print(f"{label:42s}: {n:5d} ({pct:6.2f}%)")

gc.collect()

Known true S2 pairs: 3279

======================================================================
TRUE-PAIR ANCHOR COVERAGE
======================================================================
Total true S2 pairs: 3279
>=2 shared name tokens                    :  2561 ( 78.10%)
>=2 shared address tokens                 :  3126 ( 95.33%)
>=3 shared address tokens                 :  3116 ( 95.03%)
>=1 rare name token                       :  1227 ( 37.42%)
>=2 rare name tokens                      :   183 (  5.58%)
>=1 rare address token                    :  1854 ( 56.54%)
>=2 rare address tokens                   :   708 ( 21.59%)
>=1 shared address number                 :  2574 ( 78.50%)
>=2 address tokens + number               :  2574 ( 78.50%)
>=2 address tokens + rare address token   :  1854 ( 56.54%)
>=2 name tokens + rare name token         :  1174 ( 35.80%)
name2 OR addr2 OR shared number           :  3270 ( 99.73%)

0

In [ ]:
# ============================================================
# STEP 8 — MEASURE BROAD BLOCKER CANDIDATE VOLUME
# ============================================================

from collections import defaultdict
import pandas as pd
import re
import gc
import time

print("Building validation token indexes...")

# ------------------------------------------------------------
# Build tiny inverted indexes for the 2,000 validation S1s
# ------------------------------------------------------------

name_index_all = defaultdict(set)
addr_index_all = defaultdict(set)
number_index_all = defaultdict(set)

for sid in val_ids:

    row = s1_lookup[sid]

    name_tokens = set(row["name"].split())
    addr_tokens = set(row["address"].split())
    numbers = set(re.findall(r"\d+", row["address"]))

    for token in name_tokens:
        name_index_all[token].add(sid)

    for token in addr_tokens:
        addr_index_all[token].add(sid)

    for num in numbers:
        number_index_all[num].add(sid)

print("Name index keys:", len(name_index_all))
print("Address index keys:", len(addr_index_all))
print("Number index keys:", len(number_index_all))

# ------------------------------------------------------------
# Scan S2 and count candidate links
# ------------------------------------------------------------

candidate_links = 0
candidate_rows = 0
rows_processed = 0

# Track how many validation S1s get at least one candidate
covered_s1 = set()

start = time.time()

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    for row in chunk.itertuples(index=False):

        name2 = normalize_advanced(row.business_name)
        addr2 = normalize_advanced(row.business_address)

        name_tokens = set(name2.split())
        addr_tokens = set(addr2.split())
        numbers = set(re.findall(r"\d+", addr2))

        # ----------------------------------------------------
        # Find validation S1s sharing name/address tokens
        # ----------------------------------------------------

        name_counts = Counter()

        for token in name_tokens:
            for sid in name_index_all.get(token, ()):
                name_counts[sid] += 1

        addr_counts = Counter()

        for token in addr_tokens:
            for sid in addr_index_all.get(token, ()):
                addr_counts[sid] += 1

        candidates = set()

        # >=2 shared name tokens
        for sid, count in name_counts.items():
            if count >= 2:
                candidates.add(sid)

        # >=2 shared address tokens
        for sid, count in addr_counts.items():
            if count >= 2:
                candidates.add(sid)

        # >=1 shared address number
        for num in numbers:
            candidates.update(number_index_all.get(num, ()))

        if candidates:
            candidate_rows += 1
            candidate_links += len(candidates)
            covered_s1.update(candidates)

    rows_processed += len(chunk)

    if rows_processed % 1_000_000 == 0:
        elapsed = time.time() - start

        print(
            f"Scanned {rows_processed:,} rows | "
            f"candidate links: {candidate_links:,} | "
            f"S1 covered: {len(covered_s1):,} | "
            f"time: {elapsed/60:.1f} min"
        )

    del chunk
    gc.collect()

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

elapsed = time.time() - start

print("\n" + "=" * 70)
print("BROAD BLOCKER CANDIDATE VOLUME")
print("=" * 70)

print("S2 rows scanned:", f"{rows_processed:,}")
print("S2 rows producing candidates:", f"{candidate_rows:,}")
print("Candidate links:", f"{candidate_links:,}")
print("Validation S1 covered:", f"{len(covered_s1):,}", "/ 2000")
print("Average candidates per covered S1:",
      round(candidate_links / max(len(covered_s1), 1), 2))

print("Elapsed:", round(elapsed / 60, 2), "minutes")

gc.collect()

Building validation token indexes...
Name index keys: 2388
Address index keys: 5554
Number index keys: 1279
Scanned 1,000,000 rows | candidate links: 97,402,175 | S1 covered: 2,000 | time: 8.3 min
Scanned 2,000,000 rows | candidate links: 194,818,612 | S1 covered: 2,000 | time: 16.2 min
Scanned 3,000,000 rows | candidate links: 292,315,643 | S1 covered: 2,000 | time: 24.2 min
Scanned 4,000,000 rows | candidate links: 389,834,136 | S1 covered: 2,000 | time: 31.9 min

KeyboardInterrupt:

In [ ]:
# STEP 9 — QUICK RARITY THRESHOLD SWEEP

from collections import Counter
import pandas as pd
import gc

THRESHOLDS = [500, 1000, 2500, 5000, 10000]

counts = {
    t: {"name": 0, "addr": 0, "union": 0}
    for t in THRESHOLDS
}

total = 0

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=["entity_id", "business_name", "business_address"],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):
    for row in chunk.itertuples(index=False):

        eid = row.entity_id

        if eid not in true_s2_to_s1:
            continue

        sid = true_s2_to_s1[eid]
        s1row = s1_lookup[sid]

        n1 = set(s1row["name"].split())
        a1 = set(s1row["address"].split())

        n2 = set(normalize_advanced(row.business_name).split())
        a2 = set(normalize_advanced(row.business_address).split())

        shared_n = n1 & n2
        shared_a = a1 & a2

        total += 1

        for t in THRESHOLDS:

            rare_n = {
                x for x in shared_n
                if name_freq_val.get(x, 10**9) <= t
            }

            rare_a = {
                x for x in shared_a
                if address_freq_val.get(x, 10**9) <= t
            }

            name_ok = len(rare_n) >= 1
            addr_ok = len(rare_a) >= 1

            if name_ok:
                counts[t]["name"] += 1

            if addr_ok:
                counts[t]["addr"] += 1

            if name_ok or addr_ok:
                counts[t]["union"] += 1

    del chunk
    gc.collect()

print("\nTRUE-PAIR RARITY SWEEP")
print("=" * 65)
print(f"Total true pairs: {total}\n")

print(f"{'Threshold':>10} | {'Name':>8} | {'Address':>8} | {'Union':>8}")
print("-" * 45)

for t in THRESHOLDS:
    print(
        f"{t:>10} | "
        f"{counts[t]['name']:>4} "
        f"({100*counts[t]['name']/total:5.1f}%) | "
        f"{counts[t]['addr']:>4} "
        f"({100*counts[t]['addr']/total:5.1f}%) | "
        f"{counts[t]['union']:>4} "
        f"({100*counts[t]['union']/total:5.1f}%)"
    )

gc.collect()

TRUE-PAIR RARITY SWEEP
=================================================================
Total true pairs: 3279

 Threshold |     Name |  Address |    Union
---------------------------------------------
       500 | 1227 ( 37.4%) | 1854 ( 56.5%) | 2364 ( 72.1%)
      1000 | 1373 ( 41.9%) | 2257 ( 68.8%) | 2668 ( 81.4%)
      2500 | 1656 ( 50.5%) | 2696 ( 82.2%) | 2968 ( 90.5%)
      5000 | 1802 ( 55.0%) | 2916 ( 88.9%) | 3112 ( 94.9%)
     10000 | 2106 ( 64.2%) | 3003 ( 91.6%) | 3185 ( 97.1%)

0

In [ ]:
# STEP 10 — SELECTIVE 2-TOKEN BLOCKER RECALL
# Only audits the 3,279 known true pairs. No candidate generation.

import pandas as pd
import gc

THRESHOLDS = [500, 1000, 2500, 5000, 10000]

counts = {
    t: {"addr2": 0, "name2": 0, "union": 0}
    for t in THRESHOLDS
}

total = 0

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=["entity_id", "business_name", "business_address"],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):
    for row in chunk.itertuples(index=False):

        eid = row.entity_id

        if eid not in true_s2_to_s1:
            continue

        sid = true_s2_to_s1[eid]
        s1row = s1_lookup[sid]

        name1 = set(s1row["name"].split())
        addr1 = set(s1row["address"].split())

        name2 = set(normalize_advanced(row.business_name).split())
        addr2 = set(normalize_advanced(row.business_address).split())

        shared_name = name1 & name2
        shared_addr = addr1 & addr2

        total += 1

        for t in THRESHOLDS:

            rare_name = {
                x for x in shared_name
                if name_freq_val.get(x, 10**9) <= t
            }

            rare_addr = {
                x for x in shared_addr
                if address_freq_val.get(x, 10**9) <= t
            }

            # Selective anchors
            name_ok = (
                len(shared_name) >= 2
                and len(rare_name) >= 1
            )

            addr_ok = (
                len(shared_addr) >= 2
                and len(rare_addr) >= 1
            )

            if name_ok:
                counts[t]["name2"] += 1

            if addr_ok:
                counts[t]["addr2"] += 1

            if name_ok or addr_ok:
                counts[t]["union"] += 1

    del chunk
    gc.collect()

print("\nSELECTIVE 2-TOKEN BLOCKER RECALL")
print("=" * 70)
print("Total true pairs:", total)

print(
    f"{'Threshold':>10} | "
    f"{'Name 2+rare':>13} | "
    f"{'Addr 2+rare':>13} | "
    f"{'Union':>10}"
)
print("-" * 60)

for t in THRESHOLDS:
    print(
        f"{t:>10} | "
        f"{counts[t]['name2']:>5} "
        f"({100*counts[t]['name2']/total:5.1f}%) | "
        f"{counts[t]['addr2']:>5} "
        f"({100*counts[t]['addr2']/total:5.1f}%) | "
        f"{counts[t]['union']:>5} "
        f"({100*counts[t]['union']/total:5.1f}%)"
    )

gc.collect()

SELECTIVE 2-TOKEN BLOCKER RECALL
======================================================================
Total true pairs: 3279
 Threshold |   Name 2+rare |   Addr 2+rare |      Union
------------------------------------------------------------
       500 |  1174 ( 35.8%) |  1854 ( 56.5%) |  2344 ( 71.5%)
      1000 |  1315 ( 40.1%) |  2257 ( 68.8%) |  2650 ( 80.8%)
      2500 |  1583 ( 48.3%) |  2696 ( 82.2%) |  2956 ( 90.1%)
      5000 |  1719 ( 52.4%) |  2916 ( 88.9%) |  3102 ( 94.6%)
     10000 |  2008 ( 61.2%) |  3003 ( 91.6%) |  3176 ( 96.9%)

0

In [ ]:
# ============================================================
# STEP 11 — QUICK CANDIDATE VOLUME ESTIMATE
# Test 500k S2 rows only
# ============================================================

from collections import defaultdict, Counter
import pandas as pd
import re
import gc
import time

THRESHOLD = 5000
SAMPLE_ROWS = 500_000

print("Building selective token indexes...")

# ------------------------------------------------------------
# S1 token indexes
# Only keep tokens whose S2 frequency <= 5000
# ------------------------------------------------------------

name_idx = defaultdict(set)
addr_idx = defaultdict(set)

s1_country = {}

for sid in val_ids:

    row = s1_lookup[sid]

    country = row["country"]
    s1_country[sid] = country

    for token in set(row["name"].split()):
        if name_freq_val.get(token, 10**9) <= THRESHOLD:
            name_idx[token].add(sid)

    for token in set(row["address"].split()):
        if address_freq_val.get(token, 10**9) <= THRESHOLD:
            addr_idx[token].add(sid)

print("Selective name keys:", len(name_idx))
print("Selective address keys:", len(addr_idx))

# ------------------------------------------------------------
# Scan only first 500k S2 rows
# ------------------------------------------------------------

candidate_links = 0
rows_with_candidates = 0
covered_s1 = set()

start = time.time()

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    for row in chunk.itertuples(index=False):

        country2 = normalize_advanced(row.country)

        # Candidate occurrence counters
        counts = Counter()

        # -------------------------
        # Name: >=2 shared rare tokens
        # -------------------------
        for token in set(normalize_advanced(row.business_name).split()):

            if token in name_idx:
                for sid in name_idx[token]:
                    if s1_country[sid] == country2:
                        counts[sid] += 1

        # -------------------------
        # Address: >=2 shared rare tokens
        # -------------------------
        for token in set(normalize_advanced(row.business_address).split()):

            if token in addr_idx:
                for sid in addr_idx[token]:
                    if s1_country[sid] == country2:
                        counts[sid] += 1

        # ----------------------------------------------------
        # IMPORTANT:
        # Need >=2 hits from the same field.
        # ----------------------------------------------------

        name_counts = Counter()
        addr_counts = Counter()

        # Recompute separately so name/address aren't mixed
        for token in set(normalize_advanced(row.business_name).split()):
            if token in name_idx:
                for sid in name_idx[token]:
                    if s1_country[sid] == country2:
                        name_counts[sid] += 1

        for token in set(normalize_advanced(row.business_address).split()):
            if token in addr_idx:
                for sid in addr_idx[token]:
                    if s1_country[sid] == country2:
                        addr_counts[sid] += 1

        candidates = set()

        for sid, n in name_counts.items():
            if n >= 2:
                candidates.add(sid)

        for sid, n in addr_counts.items():
            if n >= 2:
                candidates.add(sid)

        if candidates:
            rows_with_candidates += 1
            candidate_links += len(candidates)
            covered_s1.update(candidates)

    del chunk
    gc.collect()

elapsed = time.time() - start

print("\n" + "=" * 70)
print("500K-ROW CANDIDATE ESTIMATE")
print("=" * 70)

print("S2 rows tested:", f"{SAMPLE_ROWS:,}")
print("Rows producing candidates:", f"{rows_with_candidates:,}")
print("Candidate links:", f"{candidate_links:,}")
print("Validation S1 covered:", f"{len(covered_s1):,}")
print(
    "Average candidates per candidate-producing row:",
    round(candidate_links / max(rows_with_candidates, 1), 2)
)

# Rough full-S2 extrapolation
scale = 5_034_616 / SAMPLE_ROWS

print("\nROUGH FULL-S2 ESTIMATE")
print("Estimated candidate links:",
      f"{int(candidate_links * scale):,}")

print("Estimated candidate-producing rows:",
      f"{int(rows_with_candidates * scale):,}")

print("Elapsed:", round(elapsed / 60, 2), "minutes")

gc.collect()

Building selective token indexes...
Selective name keys: 1791
Selective address keys: 4338

======================================================================
500K-ROW CANDIDATE ESTIMATE
======================================================================
S2 rows tested: 500,000
Rows producing candidates: 49,171
Candidate links: 55,375
Validation S1 covered: 1,555
Average candidates per candidate-producing row: 1.13

ROUGH FULL-S2 ESTIMATE
Estimated candidate links: 557,583
Estimated candidate-producing rows: 495,114
Elapsed: 6.37 minutes

0

In [ ]:
# ============================================================
# STEP 12A — FAST 100K S2 BLOCKER TEST
# ============================================================

from collections import defaultdict, Counter
import pandas as pd
import time
import gc

THRESHOLD = 5000
TEST_ROWS = 100000

print("Building fast indexes...")

# ------------------------------------------------------------
# O(1) exact indexes
# ------------------------------------------------------------

exact_name_idx = defaultdict(set)
exact_addr_idx = defaultdict(set)

name_idx = defaultdict(set)
addr_idx = defaultdict(set)

s1_country = {}

for sid in val_ids:

    row = s1_lookup[sid]

    name = row["name"]
    addr = row["address"]
    country = row["country"]

    s1_country[sid] = country

    if name:
        exact_name_idx[(country, name)].add(sid)

    if addr:
        exact_addr_idx[(country, addr)].add(sid)

    for token in set(name.split()):
        if name_freq_val.get(token, 10**9) <= THRESHOLD:
            name_idx[token].add(sid)

    for token in set(addr.split()):
        if address_freq_val.get(token, 10**9) <= THRESHOLD:
            addr_idx[token].add(sid)

print("Exact name keys:", len(exact_name_idx))
print("Exact address keys:", len(exact_addr_idx))
print("Selective name keys:", len(name_idx))
print("Selective address keys:", len(addr_idx))

# ------------------------------------------------------------
# Test only first 100K S2 rows
# ------------------------------------------------------------

candidate_pairs = 0
candidate_rows = 0
covered_s1 = set()

start = time.time()

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    for row in chunk.itertuples(index=False):

        country = normalize_advanced(row.country)

        name = normalize_advanced(row.business_name)
        addr = normalize_advanced(row.business_address)

        candidates = set()

        # ----------------------------------------------------
        # Exact name/address — O(1)
        # ----------------------------------------------------

        if name:
            candidates.update(
                exact_name_idx.get((country, name), ())
            )

        if addr:
            candidates.update(
                exact_addr_idx.get((country, addr), ())
            )

        # ----------------------------------------------------
        # Selective name tokens
        # ----------------------------------------------------

        name_counts = Counter()

        for token in set(name.split()):

            for sid in name_idx.get(token, ()):

                if s1_country[sid] == country:
                    name_counts[sid] += 1

        for sid, count in name_counts.items():

            if count >= 2:
                candidates.add(sid)

        # ----------------------------------------------------
        # Selective address tokens
        # ----------------------------------------------------

        addr_counts = Counter()

        for token in set(addr.split()):

            for sid in addr_idx.get(token, ()):

                if s1_country[sid] == country:
                    addr_counts[sid] += 1

        for sid, count in addr_counts.items():

            if count >= 2:
                candidates.add(sid)

        if candidates:

            candidate_rows += 1
            candidate_pairs += len(candidates)
            covered_s1.update(candidates)

    del chunk
    gc.collect()

elapsed = time.time() - start

print("\n" + "=" * 60)
print("100K FAST BLOCKER TEST")
print("=" * 60)

print("Rows scanned:", TEST_ROWS)
print("Rows producing candidates:", f"{candidate_rows:,}")
print("Candidate links:", f"{candidate_pairs:,}")
print("S1 covered:", f"{len(covered_s1):,}/2000")
print("Time:", round(elapsed, 2), "seconds")
print("Time:", round(elapsed / 60, 2), "minutes")

gc.collect()

Building fast indexes...
Exact name keys: 1995
Exact address keys: 2000
Selective name keys: 1791
Selective address keys: 4338

============================================================
100K FAST BLOCKER TEST
============================================================
Rows scanned: 100000
Rows producing candidates: 59,281
Candidate links: 65,871
S1 covered: 1,816/2000
Time: 256.05 seconds
Time: 4.27 minutes

0

In [ ]:
# ============================================================
# STEP 13 — FAST VECTORISED BLOCKER TEST
# 100K S2 rows only
# ============================================================

import pandas as pd
import numpy as np
import time
import gc

THRESHOLD = 5000
TEST_ROWS = 100000
CHUNK_SIZE = 50000

print("Building vectorized indexes...")

# ------------------------------------------------------------
# S1 -> selective token tables
# ------------------------------------------------------------

name_records = []
addr_records = []
exact_name_map = {}
exact_addr_map = {}

for sid in val_ids:

    row = s1_lookup[sid]

    country = row["country"]
    name = row["name"]
    addr = row["address"]

    if name:
        exact_name_map[(country, name)] = sid

    if addr:
        exact_addr_map[(country, addr)] = sid

    for token in set(name.split()):
        if name_freq_val.get(token, 10**9) <= THRESHOLD:
            name_records.append((token, country, sid))

    for token in set(addr.split()):
        if address_freq_val.get(token, 10**9) <= THRESHOLD:
            addr_records.append((token, country, sid))

name_lookup = pd.DataFrame(
    name_records,
    columns=["token", "country", "s1_id"]
)

addr_lookup = pd.DataFrame(
    addr_records,
    columns=["token", "country", "s1_id"]
)

del name_records, addr_records
gc.collect()

print("Name index rows:", len(name_lookup))
print("Address index rows:", len(addr_lookup))

# ------------------------------------------------------------
# Read only 100K rows
# ------------------------------------------------------------

start = time.time()

candidate_pairs = set()

for chunk in pd.read_csv(
    TRAIN_S2,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str,
    keep_default_na=False,
    chunksize=CHUNK_SIZE
):

    # Normalize once
    chunk["name_n"] = chunk["business_name"].map(normalize_advanced)
    chunk["addr_n"] = chunk["business_address"].map(normalize_advanced)
    chunk["country_n"] = chunk["country"].map(normalize_advanced)

    # --------------------------------------------------------
    # NAME BLOCK
    # --------------------------------------------------------

    name_tokens = chunk[
        ["entity_id", "country_n", "name_n"]
    ].copy()

    name_tokens["token"] = name_tokens["name_n"].str.split()

    name_tokens = name_tokens[
        ["entity_id", "country_n", "token"]
    ].explode("token")

    name_tokens = name_tokens[
        name_tokens["token"].notna()
    ].drop_duplicates(
        ["entity_id", "token"]
    )

    name_matches = name_tokens.merge(
        name_lookup,
        left_on=["token", "country_n"],
        right_on=["token", "country"],
        how="inner"
    )

    name_counts = (
        name_matches
        .groupby(["entity_id", "s1_id"])
        .size()
        .reset_index(name="n")
    )

    name_candidates = name_counts[
        name_counts["n"] >= 2
    ][["entity_id", "s1_id"]]

    # --------------------------------------------------------
    # ADDRESS BLOCK
    # --------------------------------------------------------

    addr_tokens = chunk[
        ["entity_id", "country_n", "addr_n"]
    ].copy()

    addr_tokens["token"] = addr_tokens["addr_n"].str.split()

    addr_tokens = addr_tokens[
        ["entity_id", "country_n", "token"]
    ].explode("token")

    addr_tokens = addr_tokens[
        addr_tokens["token"].notna()
    ].drop_duplicates(
        ["entity_id", "token"]
    )

    addr_matches = addr_tokens.merge(
        addr_lookup,
        left_on=["token", "country_n"],
        right_on=["token", "country"],
        how="inner"
    )

    addr_counts = (
        addr_matches
        .groupby(["entity_id", "s1_id"])
        .size()
        .reset_index(name="n")
    )

    addr_candidates = addr_counts[
        addr_counts["n"] >= 2
    ][["entity_id", "s1_id"]]

    # --------------------------------------------------------
    # EXACT NAME / ADDRESS
    # --------------------------------------------------------

    for r in chunk.itertuples(index=False):

        key_name = (r.country_n, r.name_n)
        key_addr = (r.country_n, r.addr_n)

        sid = exact_name_map.get(key_name)

        if sid is not None:
            candidate_pairs.add((r.entity_id, sid))

        sid = exact_addr_map.get(key_addr)

        if sid is not None:
            candidate_pairs.add((r.entity_id, sid))

    # --------------------------------------------------------
    # Add token candidates
    # --------------------------------------------------------

    for r in name_candidates.itertuples(index=False):
        candidate_pairs.add((r.entity_id, r.s1_id))

    for r in addr_candidates.itertuples(index=False):
        candidate_pairs.add((r.entity_id, r.s1_id))

    del chunk
    del name_tokens, addr_tokens
    del name_matches, addr_matches
    del name_counts, addr_counts
    del name_candidates, addr_candidates

    gc.collect()

elapsed = time.time() - start

print("\n" + "=" * 65)
print("VECTORISED 100K TEST")
print("=" * 65)

print("Candidate pairs:", f"{len(candidate_pairs):,}")
print("Time:", round(elapsed, 2), "seconds")
print("Time:", round(elapsed / 60, 2), "minutes")

gc.collect()

Building vectorized indexes...
Name index rows: 1988
Address index rows: 4946

=================================================================
VECTORISED 100K TEST
=================================================================
Candidate pairs: 65,517
Time: 325.11 seconds
Time: 5.42 minutes

0

In [ ]:
# ============================================================
# V5.1 — CHANGE BLOCKER RARITY LIMIT
# ============================================================

RARITY_LIMIT = 5000

def generate_candidates(
    s1_name,
    s1_addr,
    s1_country,
    name_idx,
    addr_idx,
    name_freq,
    addr_freq
):
    name_hits = defaultdict(int)
    addr_hits = defaultdict(int)

    # -------------------------
    # NAME BLOCK
    # -------------------------
    for token in tokens_fast(s1_name):

        if name_freq.get(token, 999999999) <= RARITY_LIMIT:

            for eid in name_idx.get(token, []):
                name_hits[eid] += 1

    # -------------------------
    # ADDRESS BLOCK
    # -------------------------
    for token in tokens_fast(s1_addr):

        if addr_freq.get(token, 999999999) <= RARITY_LIMIT:

            for eid in addr_idx.get(token, []):
                addr_hits[eid] += 1

    # -------------------------
    # Require >=2 shared tokens
    # -------------------------
    candidate_ids = set()

    for eid, count in name_hits.items():
        if count >= 2:
            candidate_ids.add(eid)

    for eid, count in addr_hits.items():
        if count >= 2:
            candidate_ids.add(eid)

    return candidate_ids


print("=" * 60)
print("V5.1 BLOCKER READY")
print("=" * 60)
print("Rarity limit:", RARITY_LIMIT)
print("Name requirement: >=2 shared selective tokens")
print("Address requirement: >=2 shared selective tokens")
print("Model threshold: 0.60")
print("No dataset scan performed.")

============================================================
V5.1 BLOCKER READY
============================================================
Rarity limit: 5000
Name requirement: >=2 shared selective tokens
Address requirement: >=2 shared selective tokens
Model threshold: 0.60
No dataset scan performed.

In [ ]:
# Fix validation lookup column names
s1_val_lookup = (
    s1_val
    .set_index("entity_id")
    .to_dict("index")
)

print("Sample validation row keys:")
print(list(next(iter(s1_val_lookup.values())).keys()))

Sample validation row keys:
['business_name', 'business_address', 'country']

In [ ]:
# ============================================================
# RESTORE MISSING HELPERS
# ============================================================

import re
import pandas as pd

def normalize_country(text):
    if pd.isna(text):
        return ""
    return str(text).lower().strip()

def get_token_set(text):
    if pd.isna(text) or not text:
        return set()
    return set(str(text).split())

print("Helpers restored:")
print("✓ normalize_country")
print("✓ get_token_set")

Helpers restored:
✓ normalize_country
✓ get_token_set

In [ ]:
# ============================================================
# STEP 2A — PREPARE V5.1 VALIDATION INDEX
# ============================================================

from collections import defaultdict
import gc

V51_LIMIT = 5000

# Make sure lookup uses the actual source column names
s1_val_lookup = (
    s1_val
    .set_index("entity_id")
    .to_dict("index")
)

# ------------------------------------------------------------
# Country-aware rare-token indexes
# ------------------------------------------------------------

v51_name_index = defaultdict(set)
v51_addr_index = defaultdict(set)

val_name_tokens = {}
val_address_tokens = {}
val_country = {}

for sid in val_ids:

    r = s1_val_lookup[sid]

    name = normalize_advanced(r["business_name"])
    addr = normalize_advanced(r["business_address"])
    country = normalize_country(r["country"])

    val_name_tokens[sid] = get_token_set(name)
    val_address_tokens[sid] = get_token_set(addr)
    val_country[sid] = country

    for token in val_name_tokens[sid]:
        if name_freq_val.get(token, 10**9) <= V51_LIMIT:
            v51_name_index[(country, token)].add(sid)

    for token in val_address_tokens[sid]:
        if address_freq_val.get(token, 10**9) <= V51_LIMIT:
            v51_addr_index[(country, token)].add(sid)

print("=" * 65)
print("V5.1 VALIDATION INDEX READY")
print("=" * 65)
print("Rarity limit:", V51_LIMIT)
print("Name index keys:", len(v51_name_index))
print("Address index keys:", len(v51_addr_index))
print("Validation S1:", len(val_ids))

gc.collect()

=================================================================
V5.1 VALIDATION INDEX READY
=================================================================
Rarity limit: 5000
Name index keys: 1807
Address index keys: 4399
Validation S1: 2000

37

In [ ]:
V5_FEATURES = [
    "name_exact",
    "address_exact",
    "country_exact",
    "name_similarity",
    "address_similarity",
    "name_token_overlap",
    "address_token_overlap",
    "name_jaccard",
    "address_jaccard",
    "shared_name_token_count",
    "shared_address_token_count",
    "shared_address_number_count",
    "name_length_diff",
    "address_length_diff",
    "name_length_ratio",
    "address_length_ratio",
    "similarity_gap",
    "max_similarity",
    "similarity_product",
    "token_overlap_gap"
]

print("✅ V5_FEATURES restored")
print("Feature count:", len(V5_FEATURES))
print("pair_features available:", callable(pair_features))

✅ V5_FEATURES restored
Feature count: 20
pair_features available: True

In [ ]:
# ============================================================
# RESTORE V5 pair_features()
# Exact 20 features used by V5 model
# ============================================================

from rapidfuzz.fuzz import ratio

def pair_features(s1, candidate):

    name1 = normalize_advanced(
        s1["business_name"]
    )
    name2 = normalize_advanced(
        candidate["business_name"]
    )

    addr1 = normalize_advanced(
        s1["business_address"]
    )
    addr2 = normalize_advanced(
        candidate["business_address"]
    )

    country1 = normalize_country(
        s1["country"]
    )
    country2 = normalize_country(
        candidate["country"]
    )

    t1_name = get_token_set(name1)
    t2_name = get_token_set(name2)

    t1_addr = get_token_set(addr1)
    t2_addr = get_token_set(addr2)

    shared_name = t1_name & t2_name
    shared_addr = t1_addr & t2_addr

    nums1 = set(re.findall(r"\d+", addr1))
    nums2 = set(re.findall(r"\d+", addr2))

    name_sim = (
        ratio(name1, name2) / 100
        if name1 and name2 else 0.0
    )

    addr_sim = (
        ratio(addr1, addr2) / 100
        if addr1 and addr2 else 0.0
    )

    name_overlap = (
        len(shared_name)
        / max(1, min(len(t1_name), len(t2_name)))
    )

    addr_overlap = (
        len(shared_addr)
        / max(1, min(len(t1_addr), len(t2_addr)))
    )

    name_union = t1_name | t2_name
    addr_union = t1_addr | t2_addr

    name_jaccard = (
        len(shared_name)
        / max(1, len(name_union))
    )

    addr_jaccard = (
        len(shared_addr)
        / max(1, len(addr_union))
    )

    return {
        "name_exact": int(
            bool(name1) and name1 == name2
        ),

        "address_exact": int(
            bool(addr1) and addr1 == addr2
        ),

        "country_exact": int(
            country1 == country2
        ),

        "name_similarity": name_sim,
        "address_similarity": addr_sim,

        "name_token_overlap": name_overlap,
        "address_token_overlap": addr_overlap,

        "name_jaccard": name_jaccard,
        "address_jaccard": addr_jaccard,

        "shared_name_token_count": len(shared_name),
        "shared_address_token_count": len(shared_addr),

        "shared_address_number_count": len(
            nums1 & nums2
        ),

        "name_length_diff": abs(
            len(name1) - len(name2)
        ),

        "address_length_diff": abs(
            len(addr1) - len(addr2)
        ),

        "name_length_ratio": (
            min(len(name1), len(name2))
            / max(1, max(len(name1), len(name2)))
        ),

        "address_length_ratio": (
            min(len(addr1), len(addr2))
            / max(1, max(len(addr1), len(addr2)))
        ),

        "similarity_gap": abs(
            name_sim - addr_sim
        ),

        "max_similarity": max(
            name_sim,
            addr_sim
        ),

        "similarity_product": (
            name_sim * addr_sim
        ),

        "token_overlap_gap": abs(
            name_overlap - addr_overlap
        )
    }


print("✅ V5 pair_features restored")
print("Features:", len(V5_FEATURES))
print(V5_FEATURES)

✅ V5 pair_features restored
Features: 20
['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard', 'address_jaccard', 'shared_name_token_count', 'shared_address_token_count', 'shared_address_number_count', 'name_length_diff', 'address_length_diff', 'name_length_ratio', 'address_length_ratio', 'similarity_gap', 'max_similarity', 'similarity_product', 'token_overlap_gap']

In [ ]:
# ============================================================
# STEP 2B — V5.1 VALIDATION SCORING
# ============================================================

import pandas as pd
import numpy as np
import gc
import time

V51_LIMIT = 5000
V51_THRESHOLD = 0.60
BATCH_SIZE = 10000

required = [
    "val_ids",
    "gt_lookup",
    "s1_val_lookup",
    "v5_model",
    "pair_features",
    "V5_FEATURES",
    "v51_name_index",
    "v51_addr_index",
    "val_name_tokens",
    "val_address_tokens",
    "val_country"
]

missing = [x for x in required if x not in globals()]

if missing:
    raise RuntimeError("Missing: " + ", ".join(missing))

print("=" * 70)
print("V5.1 VALIDATION SCORING")
print("=" * 70)
print("Rarity limit:", V51_LIMIT)
print("Threshold:", V51_THRESHOLD)
print("Validation S1:", len(val_ids))

# ------------------------------------------------------------
# Exact indexes
# ------------------------------------------------------------

exact_name = {}
exact_addr = {}

for sid in val_ids:

    r = s1_val_lookup[sid]

    name = normalize_advanced(r["business_name"])
    addr = normalize_advanced(r["business_address"])
    country = normalize_country(r["country"])

    if name:
        exact_name[(country, name)] = sid

    if addr:
        exact_addr[(country, addr)] = sid

print("Exact indexes ready.")

# ------------------------------------------------------------
# Prediction storage
# ------------------------------------------------------------

predicted_by_s1_v51 = {
    sid: set()
    for sid in val_ids
}

feature_batch = []
pair_batch = []

total_candidates = 0
total_predictions = 0


def score_v51_batch():

    global total_predictions

    if not feature_batch:
        return

    X = pd.DataFrame(
        feature_batch,
        columns=V5_FEATURES
    )

    probs = v5_model.predict_proba(X)[:, 1]

    keep = probs >= V51_THRESHOLD

    for i in np.where(keep)[0]:

        sid, eid = pair_batch[i]

        predicted_by_s1_v51[sid].add(eid)

    total_predictions += int(keep.sum())

    feature_batch.clear()
    pair_batch.clear()

    del X, probs, keep
    gc.collect()


# ------------------------------------------------------------
# Process source
# ------------------------------------------------------------

def process_v51_source(path, source_name):

    global total_candidates

    start = time.time()
    rows = 0
    source_candidates = 0

    print("\n" + "=" * 70)
    print("Scanning", source_name)
    print("=" * 70)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        dtype=str,
        keep_default_na=False,
        chunksize=200000
    ):

        for row in chunk.itertuples(index=False):

            eid = row.entity_id

            country = normalize_country(row.country)

            name = normalize_advanced(row.business_name)
            address = normalize_advanced(row.business_address)

            name_tokens = get_token_set(name)
            address_tokens = get_token_set(address)

            found_s1 = set()

            # ------------------------------------------------
            # Exact name
            # ------------------------------------------------

            if name:
                sid = exact_name.get((country, name))
                if sid is not None:
                    found_s1.add(sid)

            # ------------------------------------------------
            # Exact address
            # ------------------------------------------------

            if address:
                sid = exact_addr.get((country, address))
                if sid is not None:
                    found_s1.add(sid)

            # ------------------------------------------------
            # Selective NAME blocker
            # >=2 shared tokens + >=1 rare shared token
            # ------------------------------------------------

            possible_s1 = set()

            for token in name_tokens:

                possible_s1.update(
                    v51_name_index.get(
                        (country, token),
                        ()
                    )
                )

            for sid in possible_s1:

                shared = (
                    name_tokens &
                    val_name_tokens[sid]
                )

                if len(shared) < 2:
                    continue

                if any(
                    name_freq_val.get(t, 10**9)
                    <= V51_LIMIT
                    for t in shared
                ):
                    found_s1.add(sid)

            # ------------------------------------------------
            # Selective ADDRESS blocker
            # >=2 shared tokens + >=1 rare shared token
            # ------------------------------------------------

            possible_s1 = set()

            for token in address_tokens:

                possible_s1.update(
                    v51_addr_index.get(
                        (country, token),
                        ()
                    )
                )

            for sid in possible_s1:

                shared = (
                    address_tokens &
                    val_address_tokens[sid]
                )

                if len(shared) < 2:
                    continue

                if any(
                    address_freq_val.get(t, 10**9)
                    <= V51_LIMIT
                    for t in shared
                ):
                    found_s1.add(sid)

            # ------------------------------------------------
            # Build V5 features
            # ------------------------------------------------

            for sid in found_s1:

                s1_row = s1_val_lookup[sid]

                source_row = {
                    "entity_id": eid,
                    "business_name": row.business_name,
                    "business_address": row.business_address,
                    "country": row.country
                }

                features = pair_features(
                    s1_row,
                    source_row
                )

                feature_batch.append(features)
                pair_batch.append((sid, eid))

                source_candidates += 1
                total_candidates += 1

                if len(feature_batch) >= BATCH_SIZE:
                    score_v51_batch()

            rows += 1

        del chunk
        gc.collect()

        if rows % 1_000_000 == 0:

            print(
                f"{source_name}: "
                f"{rows:,} rows | "
                f"candidates: {source_candidates:,} | "
                f"predictions: {total_predictions:,} | "
                f"time: {(time.time()-start)/60:.1f} min"
            )

    score_v51_batch()

    print(
        f"{source_name} COMPLETE | "
        f"candidates: {source_candidates:,} | "
        f"time: {(time.time()-start)/60:.2f} min"
    )


# ------------------------------------------------------------
# RUN S2 + S3
# ------------------------------------------------------------

process_v51_source(
    TRAIN_S2,
    "S2"
)

process_v51_source(
    TRAIN_S3,
    "S3"
)

# ------------------------------------------------------------
# Entity-level Macro F0.5
# ------------------------------------------------------------

entity_scores = []

singleton_total = 0
singleton_correct = 0

for sid in val_ids:

    true_ids = gt_lookup.get(sid, set())
    pred_ids = predicted_by_s1_v51[sid]

    tp = len(true_ids & pred_ids)
    fp = len(pred_ids - true_ids)
    fn = len(true_ids - pred_ids)

    if not true_ids:

        singleton_total += 1

        if not pred_ids:
            singleton_correct += 1

        score = (
            1.0
            if not pred_ids
            else 0.0
        )

    elif tp == 0:

        score = (
            1.0
            if fp == 0 and fn == 0
            else 0.0
        )

    else:

        precision = tp / (tp + fp)
        recall = tp / (tp + fn)

        score = (
            1.25 * precision * recall
            /
            (0.25 * precision + recall)
        )

    entity_scores.append(score)


final_f05_v51 = float(
    np.mean(entity_scores)
)

print("\n" + "=" * 70)
print("V5.1 VALIDATION RESULT")
print("=" * 70)

print("Total candidates scored:", f"{total_candidates:,}")
print("Positive predictions:", f"{total_predictions:,}")

print(
    "S1 with predictions:",
    sum(bool(x) for x in predicted_by_s1_v51.values()),
    "/",
    len(val_ids)
)

print(
    "Singleton accuracy:",
    f"{singleton_correct}/{singleton_total}"
)

print(
    "ENTITY MACRO F0.5:",
    final_f05_v51
)

print(
    "Previous V5:",
    0.902677
)

print(
    "Difference:",
    final_f05_v51 - 0.902677
)

gc.collect()

======================================================================
V5.1 VALIDATION SCORING
======================================================================
Rarity limit: 5000
Threshold: 0.6
Validation S1: 2000
Exact indexes ready.

======================================================================
Scanning S2
======================================================================
S2: 1,000,000 rows | candidates: 350,863 | predictions: 1,343 | time: 1.6 min
S2: 2,000,000 rows | candidates: 702,600 | predictions: 2,720 | time: 2.9 min
S2: 3,000,000 rows | candidates: 1,052,842 | predictions: 4,000 | time: 4.4 min
S2: 4,000,000 rows | candidates: 1,404,603 | predictions: 5,384 | time: 5.7 min
S2: 5,000,000 rows | candidates: 1,754,971 | predictions: 6,698 | time: 7.1 min
S2 COMPLETE | candidates: 1,767,213 | time: 7.20 min

======================================================================
Scanning S3
======================================================================
S3: 1,000,000 rows | candidates: 258,738 | predictions: 7,804 | time: 1.2 min
S3: 2,000,000 rows | candidates: 517,376 | predictions: 8,880 | time: 2.5 min
S3: 3,000,000 rows | candidates: 776,952 | predictions: 9,951 | time: 3.7 min
S3: 4,000,000 rows | candidates: 1,034,699 | predictions: 11,026 | time: 4.9 min
S3: 5,000,000 rows | candidates: 1,292,366 | predictions: 12,191 | time: 6.2 min
S3 COMPLETE | candidates: 1,366,165 | time: 6.50 min

======================================================================
V5.1 VALIDATION RESULT
======================================================================
Total candidates scored: 3,133,378
Positive predictions: 12,512
S1 with predictions: 1980 / 2000
Singleton accuracy: 11/120
ENTITY MACRO F0.5: 0.6498650665054595
Previous V5: 0.902677
Difference: -0.25281193349454045

31

In [ ]:
# STEP 1A — LOAD TEST S1 ONLY

import pandas as pd
import gc

S1_PATH = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/dataset/test/test_source1.tsv"

test_s1 = pd.read_csv(
    S1_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("✅ Test S1 loaded")
print("Rows:", len(test_s1))
print("Columns:", list(test_s1.columns))

gc.collect()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/dataset/test/test_source1.tsv'

In [ ]:
import glob

matches = glob.glob(
    "/content/drive/MyDrive/**/test_source1.tsv",
    recursive=True
)

print("Found:")
for p in matches:
    print(p)

Found:

In [ ]:
import glob

matches = glob.glob(
    "/content/amazon_ml_challenge/student_resource/**/test_source1.tsv",
    recursive=True
)

print("Found:")
for p in matches:
    print(p)

Found:
/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv

In [ ]:
TEST_S1_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"

test_s1 = pd.read_csv(
    TEST_S1_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("✅ Test S1 loaded")
print("Rows:", len(test_s1))
print("Columns:", list(test_s1.columns))

gc.collect()

✅ Test S1 loaded
Rows: 1732544
Columns: ['entity_id', 'business_name', 'business_address', 'country']

17

In [ ]:
# STEP 3 — VERIFY V5 PRODUCTION ASSETS

required = [
    "s2_names_a",
    "s2_addrs_a",
    "s2_countries_a",
    "s2_ids",
    "s3_names_a",
    "s3_addrs_a",
    "s3_countries_a",
    "s3_ids",
    "s2_name_index",
    "s2_addr_index",
    "s2_name_freq",
    "s2_addr_freq",
    "s3_name_index",
    "s3_addr_index",
    "s3_name_freq",
    "s3_addr_freq",
    "v5_model"
]

missing = [x for x in required if x not in globals()]

if missing:
    print("❌ MISSING:")
    for x in missing:
        print(" -", x)
else:
    print("✅ ALL V5 PRODUCTION ASSETS READY")
    print("S2 rows:", len(s2_ids))
    print("S3 rows:", len(s3_ids))
    print("Model trees:", v5_model.tree_count_)
    print("Model features:", len(v5_model.feature_names_))

❌ MISSING:
 - s2_names_a
 - s2_addrs_a
 - s2_countries_a
 - s2_ids
 - s3_names_a
 - s3_addrs_a
 - s3_countries_a
 - s3_ids
 - s2_name_index
 - s2_addr_index
 - s2_name_freq
 - s2_addr_freq
 - s3_name_index
 - s3_addr_index
 - s3_name_freq
 - s3_addr_freq

In [ ]:
import os

WORK_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production"

print("=" * 60)
print("CHECKING EXISTING V5 PRODUCTION FILES")
print("=" * 60)

for name in [
    "s2_results.tsv",
    "s3_results.tsv",
    "s2_checkpoint.txt",
    "s3_checkpoint.txt"
]:
    path = os.path.join(WORK_DIR, name)

    if os.path.exists(path):
        size_mb = os.path.getsize(path) / (1024**2)
        print(f"✅ {name} — {size_mb:.1f} MB")
    else:
        print(f"❌ {name} — NOT FOUND")

============================================================
CHECKING EXISTING V5 PRODUCTION FILES
============================================================
❌ s2_results.tsv — NOT FOUND
❌ s3_results.tsv — NOT FOUND
❌ s2_checkpoint.txt — NOT FOUND
❌ s3_checkpoint.txt — NOT FOUND

In [ ]:
import os

INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

print("=" * 60)
print("CHECKING SAVED V5 INDEXES")
print("=" * 60)

files = [
    "s2_name_index.pkl",
    "s2_addr_index.pkl",
    "s2_name_freq.pkl",
    "s2_addr_freq.pkl",
    "s3_name_index.pkl",
    "s3_addr_index.pkl",
    "s3_name_freq.pkl",
    "s3_addr_freq.pkl",
]

for f in files:
    p = os.path.join(INDEX_DIR, f)
    if os.path.exists(p):
        print(f"✅ {f} — {os.path.getsize(p)/(1024**2):.1f} MB")
    else:
        print(f"❌ {f} — NOT FOUND")

============================================================
CHECKING SAVED V5 INDEXES
============================================================
✅ s2_name_index.pkl — 96.4 MB
✅ s2_addr_index.pkl — 196.7 MB
✅ s2_name_freq.pkl — 12.7 MB
✅ s2_addr_freq.pkl — 16.5 MB
✅ s3_name_index.pkl — 100.9 MB
✅ s3_addr_index.pkl — 196.1 MB
✅ s3_name_freq.pkl — 13.6 MB
✅ s3_addr_freq.pkl — 16.0 MB

In [ ]:
import glob
import os

patterns = [
    "**/s2_names_a*",
    "**/s2_addrs_a*",
    "**/s2_countries_a*",
    "**/s2_ids*",
    "**/s3_names_a*",
    "**/s3_addrs_a*",
    "**/s3_countries_a*",
    "**/s3_ids*"
]

print("=" * 60)
print("SEARCHING FOR SAVED S2/S3 ARRAYS")
print("=" * 60)

found = []

for pattern in patterns:
    matches = glob.glob(
        "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/" + pattern,
        recursive=True
    )

    for p in matches:
        print("✅", p)
        found.append(p)

print("\nTotal files found:", len(found))

============================================================
SEARCHING FOR SAVED S2/S3 ARRAYS
============================================================

Total files found: 0

In [ ]:
import os

roots = [
    "/content/amazon_ml_challenge/student_resource",
    "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"
]

terms = [
    "s2_names",
    "s2_addrs",
    "s2_countries",
    "s2_ids",
    "s3_names",
    "s3_addrs",
    "s3_countries",
    "s3_ids"
]

print("=" * 70)
print("SEARCHING V5 ARRAY FILES")
print("=" * 70)

found = []

for root in roots:
    if not os.path.exists(root):
        continue

    for dirpath, dirs, files in os.walk(root):
        for f in files:
            low = f.lower()

            if any(term in low for term in terms):
                path = os.path.join(dirpath, f)
                print(path)
                found.append(path)

print("\nTOTAL FOUND:", len(found))

======================================================================
SEARCHING V5 ARRAY FILES
======================================================================

TOTAL FOUND: 0

In [ ]:
# STEP 8 — LOAD S2 ONLY

import pandas as pd
import gc

S2_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"

print("Loading S2...")
s2 = pd.read_csv(
    S2_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("✅ S2 loaded")
print("Rows:", len(s2))
print("Columns:", list(s2.columns))

gc.collect()

Loading S2...
✅ S2 loaded
Rows: 4887273
Columns: ['entity_id', 'business_name', 'business_address', 'country']

0

In [ ]:
# STEP 9A — LOAD S2 SAVED INDEXES

import os
import pickle
import gc

INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

def load_idx(name):
    path = os.path.join(INDEX_DIR, name)
    with open(path, "rb") as f:
        obj = pickle.load(f)
    print("✅", name)
    return obj

s2_name_index = load_idx("s2_name_index.pkl")
s2_addr_index = load_idx("s2_addr_index.pkl")
s2_name_freq  = load_idx("s2_name_freq.pkl")
s2_addr_freq  = load_idx("s2_addr_freq.pkl")

print("\n✅ S2 indexes loaded")
print("Name keys:", len(s2_name_index))
print("Address keys:", len(s2_addr_index))
print("Name frequencies:", len(s2_name_freq))
print("Address frequencies:", len(s2_addr_freq))

gc.collect()

✅ s2_name_index.pkl
✅ s2_addr_index.pkl
✅ s2_name_freq.pkl
✅ s2_addr_freq.pkl

✅ S2 indexes loaded
Name keys: 861199
Address keys: 1330963
Name frequencies: 861199
Address frequencies: 1330963

30

In [ ]:
# STEP 10 — LOAD V5 MODEL

from catboost import CatBoostClassifier
import gc

MODEL_PATH = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm"

v5_model = CatBoostClassifier()
v5_model.load_model(MODEL_PATH)

print("✅ V5 MODEL LOADED")
print("Trees:", v5_model.tree_count_)
print("Features:", len(v5_model.feature_names_))
print("Feature names:")
print(v5_model.feature_names_)

gc.collect()

✅ V5 MODEL LOADED
Trees: 670
Features: 20
Feature names:
['name_exact', 'address_exact', 'country_exact', 'name_similarity', 'address_similarity', 'name_token_overlap', 'address_token_overlap', 'name_jaccard', 'address_jaccard', 'shared_name_token_count', 'shared_address_token_count', 'shared_address_number_count', 'name_length_diff', 'address_length_diff', 'name_length_ratio', 'address_length_ratio', 'similarity_gap', 'max_similarity', 'similarity_product', 'token_overlap_gap']

0

In [ ]:
# STEP 11 — RESTORE V5 CANDIDATE GENERATOR

from collections import defaultdict

RARITY_LIMIT = 500

def generate_candidates(
    name1,
    addr1,
    country1,
    name_index,
    addr_index,
    name_freq,
    addr_freq
):
    name_hits = defaultdict(int)
    addr_hits = defaultdict(int)

    # Name blocking
    for token in name1.split():

        if name_freq.get(token, 999999999) <= RARITY_LIMIT:

            for eid in name_index.get(token, ()):

                name_hits[eid] += 1

    # Address blocking
    for token in addr1.split():

        if addr_freq.get(token, 999999999) <= RARITY_LIMIT:

            for eid in addr_index.get(token, ()):

                addr_hits[eid] += 1

    candidate_ids = set()

    for eid, count in name_hits.items():
        if count >= 2:
            candidate_ids.add(eid)

    for eid, count in addr_hits.items():
        if count >= 2:
            candidate_ids.add(eid)

    return candidate_ids

print("✅ V5 candidate generator restored")
print("Rarity limit:", RARITY_LIMIT)

✅ V5 candidate generator restored
Rarity limit: 500

In [ ]:
# STEP 12 — V5 SMOKE TEST
# Only 10 S1 rows. No large scan.

import time

print("Running 10-row smoke test...")

for i in range(10):

    row = test_s1.iloc[i]

    name1 = normalize_advanced(row["business_name"])
    addr1 = normalize_advanced(row["business_address"])
    country1 = normalize_country(row["country"])

    candidates = generate_candidates(
        name1,
        addr1,
        country1,
        s2_name_index,
        s2_addr_index,
        s2_name_freq,
        s2_addr_freq
    )

    print(
        f"{i+1}/10 | "
        f"S1={row['entity_id']} | "
        f"candidates={len(candidates)}"
    )

print("✅ SMOKE TEST COMPLETE")

Running 10-row smoke test...
1/10 | S1=S1-714132312 | candidates=0
2/10 | S1=S1-106407869 | candidates=0
3/10 | S1=S1-156285671 | candidates=1
4/10 | S1=S1-689823050 | candidates=2
5/10 | S1=S1-921369899 | candidates=1
6/10 | S1=S1-481669221 | candidates=2
7/10 | S1=S1-909865979 | candidates=0
8/10 | S1=S1-280204013 | candidates=125
9/10 | S1=S1-742053041 | candidates=6
10/10 | S1=S1-913506265 | candidates=0
✅ SMOKE TEST COMPLETE

In [ ]:
# STEP 13A — FAST V5 FEATURE BUILDER

import re
import numpy as np
import pandas as pd
from rapidfuzz.fuzz import ratio

def tokens_fast(text):
    if not text:
        return set()
    return set(text.split())

def extract_numbers_fast(text):
    return set(re.findall(r"\d+", text))

def build_fast_features(
    s1_name,
    s1_addr,
    s1_country,
    names,
    addrs,
    countries
):
    t1n = tokens_fast(s1_name)
    t1a = tokens_fast(s1_addr)
    nums1 = extract_numbers_fast(s1_addr)

    rows = []

    for n2, a2, c2 in zip(names, addrs, countries):

        t2n = tokens_fast(n2)
        t2a = tokens_fast(a2)

        shared_n = t1n & t2n
        shared_a = t1a & t2a

        union_n = t1n | t2n
        union_a = t1a | t2a

        ns = ratio(s1_name, n2) / 100 if s1_name and n2 else 0.0
        ass = ratio(s1_addr, a2) / 100 if s1_addr and a2 else 0.0

        nt = len(shared_n) / max(1, min(len(t1n), len(t2n)))
        at = len(shared_a) / max(1, min(len(t1a), len(t2a)))

        nj = len(shared_n) / len(union_n) if union_n else 0.0
        aj = len(shared_a) / len(union_a) if union_a else 0.0

        nums2 = extract_numbers_fast(a2)

        rows.append([
            int(bool(s1_name) and s1_name == n2),
            int(bool(s1_addr) and s1_addr == a2),
            int(s1_country == c2),
            ns,
            ass,
            nt,
            at,
            nj,
            aj,
            len(shared_n),
            len(shared_a),
            len(nums1 & nums2),
            abs(len(s1_name) - len(n2)),
            abs(len(s1_addr) - len(a2)),
            min(len(s1_name), len(n2)) /
                max(1, max(len(s1_name), len(n2))),
            min(len(s1_addr), len(a2)) /
                max(1, max(len(s1_addr), len(a2))),
            abs(ns - ass),
            max(ns, ass),
            ns * ass,
            abs(nt - at)
        ])

    return pd.DataFrame(rows, columns=V5_FEATURES)

print("✅ Fast V5 feature builder ready")

✅ Fast V5 feature builder ready

In [ ]:
# ============================================================
# STEP 13B — FAST S2 V5 INFERENCE
# ============================================================

import os
import gc
import time
import pandas as pd

OUT_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production"
os.makedirs(OUT_DIR, exist_ok=True)

S2_MATCH = f"{OUT_DIR}/s2_results.tsv"
S2_CAND = f"{OUT_DIR}/s2_candidates.tsv"

# Raw arrays = lightweight references into the existing S2 dataframe
s2_names_raw = s2["business_name"].to_numpy()
s2_addrs_raw = s2["business_address"].to_numpy()

# Fresh output files
open(S2_MATCH, "w").close()
open(S2_CAND, "w").close()

start = time.time()
total_rows = 0
total_candidates = 0
total_matches = 0

print("=" * 70)
print("FAST V5 S2 INFERENCE STARTED")
print("=" * 70)

for chunk_start in range(0, len(test_s1), 2000):

    chunk = test_s1.iloc[
        chunk_start:chunk_start + 2000
    ]

    match_lines = []
    cand_lines = []

    for row in chunk.itertuples(index=False):

        sid = row.entity_id

        name1 = normalize_advanced(row.business_name)
        addr1 = normalize_advanced(row.business_address)
        country1 = normalize_country(row.country)

        # V5 raw candidates
        raw_candidates = generate_candidates(
            name1,
            addr1,
            country1,
            s2_name_index,
            s2_addr_index,
            s2_name_freq,
            s2_addr_freq
        )

        # Country filter
        candidates = [
            idx for idx in raw_candidates
            if s2_countries_a[idx] == country1
        ]

        # Original V5 similarity selection
        selected = []

        t_name = tokens_fast(name1)
        t_addr = tokens_fast(addr1)

        for idx in candidates:

            name2 = normalize_advanced(
                s2_names_raw[idx]
            )

            addr2 = normalize_advanced(
                s2_addrs_raw[idx]
            )

            shared_name = len(
                t_name & tokens_fast(name2)
            )

            shared_addr = len(
                t_addr & tokens_fast(addr2)
            )

            name_sim = (
                ratio(name1, name2) / 100
                if name1 and name2 else 0
            )

            addr_sim = (
                ratio(addr1, addr2) / 100
                if addr1 and addr2 else 0
            )

            keep = (
                name1 == name2
                or
                addr1 == addr2
                or
                (
                    shared_name >= 2
                    and name_sim >= 0.60
                )
                or
                (
                    shared_addr >= 3
                )
                or
                (
                    shared_addr >= 2
                    and addr_sim >= 0.30
                )
            )

            if keep:
                selected.append(idx)

        candidate_ids = [
            str(s2_ids[idx])
            for idx in selected
        ]

        matched_ids = []

        if selected:

            cand_names = [
                normalize_advanced(
                    s2_names_raw[idx]
                )
                for idx in selected
            ]

            cand_addrs = [
                normalize_advanced(
                    s2_addrs_raw[idx]
                )
                for idx in selected
            ]

            cand_countries = [
                s2_countries_a[idx]
                for idx in selected
            ]

            X = build_fast_features(
                name1,
                addr1,
                country1,
                cand_names,
                cand_addrs,
                cand_countries
            )

            probs = v5_model.predict_proba(
                X
            )[:, 1]

            matched_ids = [
                candidate_ids[j]
                for j, p in enumerate(probs)
                if p >= THRESHOLD
            ]

            del X, probs

        match_lines.append(
            sid + "\t" + ",".join(matched_ids) + "\n"
        )

        cand_lines.append(
            sid + "\t" + ",".join(candidate_ids) + "\n"
        )

        total_candidates += len(candidate_ids)
        total_matches += len(matched_ids)

    with open(S2_MATCH, "a", encoding="utf-8") as f:
        f.writelines(match_lines)

    with open(S2_CAND, "a", encoding="utf-8") as f:
        f.writelines(cand_lines)

    total_rows += len(chunk)

    if total_rows % 20000 == 0:

        elapsed = time.time() - start

        print(
            f"{total_rows:,}/{len(test_s1):,} | "
            f"candidates={total_candidates:,} | "
            f"matches={total_matches:,} | "
            f"time={elapsed/60:.1f} min"
        )

    del chunk, match_lines, cand_lines
    gc.collect()

print("\n" + "=" * 70)
print("✅ S2 COMPLETE")
print("=" * 70)
print("Rows:", total_rows)
print("Candidates:", total_candidates)
print("Matches:", total_matches)
print("Time:", round((time.time() - start) / 60, 2), "min")

======================================================================
FAST V5 S2 INFERENCE STARTED
======================================================================
20,000/1,732,544 | candidates=141,424 | matches=14,109 | time=1.0 min
40,000/1,732,544 | candidates=284,656 | matches=28,587 | time=2.0 min
60,000/1,732,544 | candidates=424,498 | matches=43,128 | time=2.9 min
80,000/1,732,544 | candidates=575,771 | matches=57,825 | time=3.8 min
100,000/1,732,544 | candidates=713,739 | matches=72,187 | time=4.8 min
120,000/1,732,544 | candidates=860,164 | matches=86,314 | time=5.7 min
140,000/1,732,544 | candidates=999,388 | matches=100,139 | time=6.6 min
160,000/1,732,544 | candidates=1,138,281 | matches=114,295 | time=7.5 min
180,000/1,732,544 | candidates=1,277,257 | matches=128,951 | time=8.5 min
200,000/1,732,544 | candidates=1,421,075 | matches=143,598 | time=9.4 min
220,000/1,732,544 | candidates=1,563,392 | matches=157,993 | time=10.4 min
240,000/1,732,544 | candidates=1,696,962 | matches=172,221 | time=11.3 min
260,000/1,732,544 | candidates=1,836,018 | matches=186,310 | time=12.3 min
280,000/1,732,544 | candidates=1,978,224 | matches=200,495 | time=13.3 min
300,000/1,732,544 | candidates=2,124,862 | matches=214,783 | time=14.3 min
320,000/1,732,544 | candidates=2,266,568 | matches=229,525 | time=15.3 min
340,000/1,732,544 | candidates=2,405,053 | matches=243,735 | time=16.2 min
360,000/1,732,544 | candidates=2,542,782 | matches=257,809 | time=17.2 min
380,000/1,732,544 | candidates=2,679,417 | matches=271,815 | time=18.1 min
400,000/1,732,544 | candidates=2,821,088 | matches=285,995 | time=19.1 min
420,000/1,732,544 | candidates=2,954,982 | matches=300,196 | time=20.1 min
440,000/1,732,544 | candidates=3,086,151 | matches=314,212 | time=21.1 min
460,000/1,732,544 | candidates=3,234,357 | matches=328,671 | time=22.1 min
480,000/1,732,544 | candidates=3,381,950 | matches=343,174 | time=23.0 min
500,000/1,732,544 | candidates=3,520,694 | matches=357,481 | time=24.0 min
520,000/1,732,544 | candidates=3,664,424 | matches=371,816 | time=24.9 min
540,000/1,732,544 | candidates=3,806,500 | matches=386,094 | time=25.9 min
560,000/1,732,544 | candidates=3,944,318 | matches=400,614 | time=26.9 min
580,000/1,732,544 | candidates=4,084,529 | matches=414,871 | time=27.8 min
600,000/1,732,544 | candidates=4,226,569 | matches=429,099 | time=28.8 min
620,000/1,732,544 | candidates=4,366,840 | matches=443,344 | time=29.7 min
640,000/1,732,544 | candidates=4,507,196 | matches=457,755 | time=30.7 min
660,000/1,732,544 | candidates=4,643,605 | matches=472,154 | time=31.7 min
680,000/1,732,544 | candidates=4,789,371 | matches=486,466 | time=32.7 min
700,000/1,732,544 | candidates=4,925,037 | matches=500,937 | time=33.7 min
720,000/1,732,544 | candidates=5,064,895 | matches=515,191 | time=34.8 min
740,000/1,732,544 | candidates=5,205,045 | matches=529,671 | time=35.9 min
760,000/1,732,544 | candidates=5,353,616 | matches=544,081 | time=36.9 min
780,000/1,732,544 | candidates=5,510,100 | matches=558,406 | time=37.9 min
800,000/1,732,544 | candidates=5,663,913 | matches=572,946 | time=39.0 min
820,000/1,732,544 | candidates=5,799,342 | matches=587,213 | time=40.0 min
840,000/1,732,544 | candidates=5,948,041 | matches=601,387 | time=41.0 min
860,000/1,732,544 | candidates=6,084,039 | matches=615,599 | time=42.0 min
880,000/1,732,544 | candidates=6,228,546 | matches=630,029 | time=43.0 min
900,000/1,732,544 | candidates=6,365,981 | matches=644,405 | time=44.0 min
920,000/1,732,544 | candidates=6,506,472 | matches=658,594 | time=44.9 min
940,000/1,732,544 | candidates=6,653,404 | matches=672,957 | time=46.0 min
960,000/1,732,544 | candidates=6,789,269 | matches=687,458 | time=46.9 min
980,000/1,732,544 | candidates=6,940,571 | matches=701,821 | time=47.9 min
1,000,000/1,732,544 | candidates=7,085,632 | matches=716,514 | time=48.9 min
1,020,000/1,732,544 | candidates=7,225,579 | matches=730,754 | time=49.8 min
1,040,000/1,732,544 | candidates=7,365,027 | matches=745,045 | time=50.8 min
1,060,000/1,732,544 | candidates=7,504,696 | matches=759,489 | time=51.7 min
1,080,000/1,732,544 | candidates=7,645,464 | matches=773,528 | time=52.7 min
1,100,000/1,732,544 | candidates=7,790,604 | matches=787,857 | time=53.6 min
1,120,000/1,732,544 | candidates=7,930,589 | matches=802,233 | time=54.6 min
1,140,000/1,732,544 | candidates=8,073,494 | matches=816,638 | time=55.5 min
1,160,000/1,732,544 | candidates=8,216,532 | matches=830,937 | time=56.6 min
1,180,000/1,732,544 | candidates=8,374,045 | matches=845,440 | time=57.6 min
1,200,000/1,732,544 | candidates=8,504,184 | matches=859,793 | time=58.5 min
1,220,000/1,732,544 | candidates=8,640,697 | matches=874,143 | time=59.5 min
1,240,000/1,732,544 | candidates=8,777,033 | matches=888,016 | time=60.6 min
1,260,000/1,732,544 | candidates=8,922,830 | matches=902,208 | time=61.7 min
1,280,000/1,732,544 | candidates=9,055,666 | matches=916,585 | time=62.7 min
1,300,000/1,732,544 | candidates=9,193,212 | matches=930,881 | time=63.6 min
1,320,000/1,732,544 | candidates=9,333,799 | matches=945,047 | time=64.6 min
1,340,000/1,732,544 | candidates=9,471,431 | matches=959,602 | time=65.6 min
1,360,000/1,732,544 | candidates=9,604,665 | matches=973,969 | time=66.5 min
1,380,000/1,732,544 | candidates=9,738,077 | matches=987,920 | time=67.4 min
1,400,000/1,732,544 | candidates=9,877,969 | matches=1,002,612 | time=68.5 min
1,420,000/1,732,544 | candidates=10,019,389 | matches=1,016,857 | time=69.6 min
1,440,000/1,732,544 | candidates=10,155,052 | matches=1,031,213 | time=70.7 min
1,460,000/1,732,544 | candidates=10,297,622 | matches=1,045,857 | time=71.7 min
1,480,000/1,732,544 | candidates=10,443,154 | matches=1,060,041 | time=72.7 min
1,500,000/1,732,544 | candidates=10,588,445 | matches=1,074,214 | time=73.6 min
1,520,000/1,732,544 | candidates=10,734,500 | matches=1,088,450 | time=74.6 min
1,540,000/1,732,544 | candidates=10,871,868 | matches=1,102,389 | time=75.9 min
1,560,000/1,732,544 | candidates=11,014,501 | matches=1,116,886 | time=77.3 min
1,580,000/1,732,544 | candidates=11,154,489 | matches=1,131,193 | time=78.3 min
1,600,000/1,732,544 | candidates=11,301,252 | matches=1,145,362 | time=79.5 min
1,620,000/1,732,544 | candidates=11,441,940 | matches=1,159,295 | time=80.8 min
1,640,000/1,732,544 | candidates=11,576,054 | matches=1,173,824 | time=81.8 min
1,660,000/1,732,544 | candidates=11,719,837 | matches=1,188,015 | time=82.8 min
1,680,000/1,732,544 | candidates=11,861,677 | matches=1,202,529 | time=83.8 min
1,700,000/1,732,544 | candidates=11,999,773 | matches=1,216,704 | time=84.8 min
1,720,000/1,732,544 | candidates=12,145,391 | matches=1,231,031 | time=85.8 min

======================================================================
✅ S2 COMPLETE
======================================================================
Rows: 1732544
Candidates: 12240592
Matches: 1240219
Time: 86.51 min

In [ ]:
import os

OUT_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production"

for f in ["s2_results.tsv", "s2_candidates.tsv"]:
    p = os.path.join(OUT_DIR, f)
    print(
        f,
        "✅" if os.path.exists(p) else "❌",
        f"{os.path.getsize(p)/(1024**2):.1f} MB"
        if os.path.exists(p) else ""
    )

s2_results.tsv ✅ 37.7 MB
s2_candidates.tsv ✅ 172.5 MB

In [ ]:
# STEP 15 — CLEAN S2 RAM

import gc

del s2
del s2_names_raw
del s2_addrs_raw
del s2_ids
del s2_countries_a
del s2_name_index
del s2_addr_index
del s2_name_freq
del s2_addr_freq

gc.collect()

print("✅ S2 RAM cleared")

✅ S2 RAM cleared

In [ ]:
# STEP 16 — LOAD S3 ONLY

import pandas as pd
import gc

S3_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

print("Loading S3...")

s3 = pd.read_csv(
    S3_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("✅ S3 loaded")
print("Rows:", len(s3))
print("Columns:", list(s3.columns))

gc.collect()

Loading S3...
✅ S3 loaded
Rows: 5082316
Columns: ['entity_id', 'business_name', 'business_address', 'country']

0

In [ ]:
# STEP 17 — LOAD S3 SAVED INDEXES

import os
import pickle
import gc

INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"

def load_idx_s3(name):
    path = os.path.join(INDEX_DIR, name)
    with open(path, "rb") as f:
        obj = pickle.load(f)
    print("✅", name)
    return obj

s3_name_index = load_idx_s3("s3_name_index.pkl")
s3_addr_index = load_idx_s3("s3_addr_index.pkl")
s3_name_freq  = load_idx_s3("s3_name_freq.pkl")
s3_addr_freq  = load_idx_s3("s3_addr_freq.pkl")

print("\n✅ S3 indexes loaded")
print("Name keys:", len(s3_name_index))
print("Address keys:", len(s3_addr_index))
print("Name frequencies:", len(s3_name_freq))
print("Address frequencies:", len(s3_addr_freq))

gc.collect()

✅ s3_name_index.pkl
✅ s3_addr_index.pkl
✅ s3_name_freq.pkl
✅ s3_addr_freq.pkl

✅ S3 indexes loaded
Name keys: 918689
Address keys: 1296266
Name frequencies: 918689
Address frequencies: 1296266

0

In [ ]:
# STEP 18 — LIGHTWEIGHT S3 ARRAYS

import gc

s3_names_raw = s3["business_name"].to_numpy()
s3_addrs_raw = s3["business_address"].to_numpy()

s3_ids = s3["entity_id"].to_numpy()
s3_countries_a = (
    s3["country"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
    .to_numpy()
)

print("✅ S3 arrays ready")
print("S3 IDs:", len(s3_ids))
print("S3 countries:", len(s3_countries_a))

gc.collect()

✅ S3 arrays ready
S3 IDs: 5082316
S3 countries: 5082316

28

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s3_results.tsv'

In [ ]:
import os

OUT_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production"

os.makedirs(OUT_DIR, exist_ok=True)

print("✅ Output folder ready")
print(OUT_DIR)

✅ Output folder ready
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production

In [ ]:
import glob

matches = glob.glob(
    "/content/**/test_source1.tsv",
    recursive=True
)

print("Found:")
for p in matches:
    print(p)

Found:

In [ ]:
import os

matches = []

for root, dirs, files in os.walk(
    "/content/drive/MyDrive"
):
    if "test_source1.tsv" in files:
        matches.append(
            os.path.join(root, "test_source1.tsv")
        )

print("Found:")
for p in matches:
    print(p)

print("Total:", len(matches))

Found:
Total: 0

In [ ]:
import os

for p in [
    "/content/amazon_ml_challenge",
    "/content/amazon_ml_challenge/student_resource",
    "/content/amazon_ml_challenge/student_resource/dataset"
]:
    print(p, "→", os.path.exists(p))

/content/amazon_ml_challenge → False
/content/amazon_ml_challenge/student_resource → False
/content/amazon_ml_challenge/student_resource/dataset → False

In [ ]:
import os

print("Files in /content:")
for item in os.listdir("/content"):
    print(item)

Files in /content:
.config
6ab10eb3b23ba_student_resource.zip
drive
sample_data

In [ ]:
import zipfile

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    files = z.namelist()

print("Total files:", len(files))

for f in files:
    if "test_source" in f:
        print(f)

Total files: 34
student_resource/dataset/test/test_source2.tsv
__MACOSX/student_resource/dataset/test/._test_source2.tsv
student_resource/dataset/test/test_source3.tsv
__MACOSX/student_resource/dataset/test/._test_source3.tsv
student_resource/dataset/test/test_source1.tsv
__MACOSX/student_resource/dataset/test/._test_source1.tsv

In [ ]:
import zipfile
import os

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"
EXTRACT_DIR = "/content/amazon_ml_challenge"

os.makedirs(EXTRACT_DIR, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extract("student_resource/dataset/test/test_source1.tsv", EXTRACT_DIR)

TEST_S1_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"

print("Extracted:", os.path.exists(TEST_S1_PATH))
print(TEST_S1_PATH)

Extracted: True
/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv

In [ ]:
import pandas as pd
import gc

TEST_S1_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"

test_s1 = pd.read_csv(TEST_S1_PATH, sep="\t")

print("Test S1 rows:", len(test_s1))
print("Columns:", test_s1.columns.tolist())
print(test_s1.head(2))

gc.collect()

Test S1 rows: 1732544
Columns: ['entity_id', 'business_name', 'business_address', 'country']
      entity_id         business_name                        business_address  \
0  S1-714132312       Zephay Labs Inc             2621 Cotten Road, Tyler, TX
1  S1-106407869  Vision Partners Corp  IA, Iowa City, 1064 Newton Rd, Unit 11

  country
0      US
1      US

90

In [ ]:
print("S3 dataframe:", "s3" in globals())
print("S3 names:", "s3_names_raw" in globals())
print("S3 addresses:", "s3_addrs_raw" in globals())
print("S3 IDs:", "s3_ids" in globals())
print("S3 countries:", "s3_countries_a" in globals())

print("Name index:", "s3_name_index" in globals())
print("Address index:", "s3_addr_index" in globals())
print("Name freq:", "s3_name_freq" in globals())
print("Address freq:", "s3_addr_freq" in globals())

print("V5 model:", "v5_model" in globals())
print("generate_candidates:", "generate_candidates" in globals())
print("build_fast_features:", "build_fast_features" in globals())

S3 dataframe: False
S3 names: False
S3 addresses: False
S3 IDs: False
S3 countries: False
Name index: False
Address index: False
Name freq: False
Address freq: False
V5 model: False
generate_candidates: False
build_fast_features: False

In [ ]:
import zipfile
import os

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"
EXTRACT_DIR = "/content/amazon_ml_challenge"

S3_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extract("student_resource/dataset/test/test_source3.tsv", EXTRACT_DIR)

print("S3 extracted:", os.path.exists(S3_PATH))
print(S3_PATH)

S3 extracted: True
/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv

In [ ]:
import pandas as pd
import gc

S3_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

s3 = pd.read_csv(S3_PATH, sep="\t")

print("S3 rows:", len(s3))
print("Columns:", s3.columns.tolist())
print(s3.head(2))

gc.collect()

S3 rows: 5082316
Columns: ['entity_id', 'business_name', 'business_address', 'country']
      entity_id          business_name  \
0  S3-462677478         मॉडर्न फाइनेंस
1  S3-374810425  Shri Sai Infratech Co

                                    business_address country
0  No 10 Enkay Square, 448A, Udyog Vihar Phase V,...   India
1                              3/115, East Delhi, DL   India

118

In [ ]:
import re
import unicodedata
import numpy as np
import gc

def normalize_advanced(text):
    if pd.isna(text):
        return ""
    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

s3_names_raw = s3["business_name"].fillna("").to_numpy()
s3_addrs_raw = s3["business_address"].fillna("").to_numpy()
s3_ids = s3["entity_id"].to_numpy()
s3_countries_a = s3["country"].fillna("").str.lower().str.strip().to_numpy()

s3_names_a = np.array(
    [normalize_advanced(x) for x in s3_names_raw],
    dtype=object
)

s3_addrs_a = np.array(
    [normalize_advanced(x) for x in s3_addrs_raw],
    dtype=object
)

print("S3 arrays created:")
print("Names:", len(s3_names_a))
print("Addresses:", len(s3_addrs_a))
print("IDs:", len(s3_ids))
print("Countries:", len(s3_countries_a))

gc.collect()

S3 arrays created:
Names: 5082316
Addresses: 5082316
IDs: 5082316
Countries: 5082316

28

In [ ]:
import os

BASE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print("Base exists:", os.path.exists(BASE))

if os.path.exists(BASE):
    print("\nInside Amazon-ML-Challenge-2026:")
    for x in os.listdir(BASE):
        print(" -", x)

ML = os.path.join(BASE, "ml")
print("\nML exists:", os.path.exists(ML))

if os.path.exists(ML):
    print("\nInside ml:")
    for x in os.listdir(ML):
        print(" -", x)

Base exists: True

Inside Amazon-ML-Challenge-2026:
 - ml

ML exists: True

Inside ml:
 - V5_Final_Production

In [ ]:
import os

PROD_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production"

print("Files in V5_Final_Production:")
for f in os.listdir(PROD_DIR):
    print(" -", f)

Files in V5_Final_Production:
 - s3_candidates.tsv
 - s3_results.tsv

In [ ]:
import os

PROD_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production"

for f in ["s3_results.tsv", "s3_candidates.tsv"]:
    path = os.path.join(PROD_DIR, f)
    size_mb = os.path.getsize(path) / (1024 * 1024)

    print(f"\n{f}")
    print("Size:", round(size_mb, 2), "MB")

    with open(path, "r", encoding="utf-8") as file:
        for i in range(3):
            print(repr(file.readline().rstrip("\n")))

s3_results.tsv
Size: 0.0 MB
''
''
''

s3_candidates.tsv
Size: 0.0 MB
''
''
''

In [ ]:
import os

DRIVE_BASE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

targets = [
    "v5_model.cbm",
    "s3_name_index.pkl",
    "s3_addr_index.pkl",
    "s3_name_freq.pkl",
    "s3_addr_freq.pkl",
    "s2_name_index.pkl",
    "s2_addr_index.pkl"
]

found = []

for root, dirs, files in os.walk(DRIVE_BASE):
    for f in files:
        if f in targets:
            found.append(os.path.join(root, f))

print("Found:", len(found))

for p in found:
    print(p)

Found: 0

In [ ]:
import os

matches = []

for root, dirs, files in os.walk("/content"):
    # Skip Drive to keep this fast
    if root.startswith("/content/drive"):
        continue

    if "v5_model.cbm" in files:
        matches.append(os.path.join(root, "v5_model.cbm"))

print("V5 model files found:", len(matches))

for p in matches:
    print(p)

V5 model files found: 0

In [ ]:
# No code needed here.
# Use the Colab cell only to confirm the dataset is available.
print("Dataset ZIP:", "/content/6ab10eb3b23ba_student_resource.zip")

Dataset ZIP: /content/6ab10eb3b23ba_student_resource.zip

In [ ]:
import os

BASE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

for root, dirs, files in os.walk(BASE):
    for f in files:
        if f in [
            "s2_results.tsv",
            "s2_candidates.tsv",
            "s3_results.tsv",
            "s3_candidates.tsv",
            "matching_results.tsv",
            "candidate_pairs.tsv"
        ]:
            path = os.path.join(root, f)
            size = os.path.getsize(path) / (1024 * 1024)
            print(round(size, 2), "MB  ->", path)

0.0 MB  -> /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s3_candidates.tsv
0.0 MB  -> /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s3_results.tsv

In [ ]:
import zipfile

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    names = z.namelist()

for name in names:
    if "train_source" in name or "train_ground_truth" in name:
        print(name)

student_resource/dataset/train/train_ground_truth.tsv
__MACOSX/student_resource/dataset/train/._train_ground_truth.tsv
student_resource/dataset/train/train_source2.tsv
__MACOSX/student_resource/dataset/train/._train_source2.tsv
student_resource/dataset/train/train_source3.tsv
__MACOSX/student_resource/dataset/train/._train_source3.tsv
student_resource/dataset/train/train_source1.tsv
__MACOSX/student_resource/dataset/train/._train_source1.tsv

In [ ]:
import zipfile
import os

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"
EXTRACT_DIR = "/content/amazon_ml_challenge"

train_files = [
    "student_resource/dataset/train/train_source1.tsv",
    "student_resource/dataset/train/train_source2.tsv",
    "student_resource/dataset/train/train_source3.tsv",
    "student_resource/dataset/train/train_ground_truth.tsv",
]

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    for f in train_files:
        z.extract(f, EXTRACT_DIR)
        print("Extracted:", f)

print("\nDone.")

Extracted: student_resource/dataset/train/train_source1.tsv
Extracted: student_resource/dataset/train/train_source2.tsv
Extracted: student_resource/dataset/train/train_source3.tsv
Extracted: student_resource/dataset/train/train_ground_truth.tsv

Done.

In [ ]:
import zipfile
import os

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"
EXTRACT_DIR = "/content/amazon_ml_challenge"

S2_PATH = "student_resource/dataset/test/test_source2.tsv"

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extract(S2_PATH, EXTRACT_DIR)

FULL_S2_PATH = "/content/amazon_ml_challenge/" + S2_PATH

print("S2 extracted:", os.path.exists(FULL_S2_PATH))
print(FULL_S2_PATH)

S2 extracted: True
/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv

In [ ]:
import pandas as pd
import numpy as np
import re
import unicodedata
import gc

S2_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"

s2 = pd.read_csv(
    S2_PATH,
    sep="\t",
    dtype=str,
    usecols=["entity_id", "business_name", "business_address", "country"]
)

print("S2 rows:", len(s2))

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

s2_ids = s2["entity_id"].to_numpy()

s2_names_a = np.array(
    [normalize_advanced(x) for x in s2["business_name"].fillna("")],
    dtype=object
)

s2_addrs_a = np.array(
    [normalize_advanced(x) for x in s2["business_address"].fillna("")],
    dtype=object
)

s2_countries_a = (
    s2["country"].fillna("").str.lower().str.strip().to_numpy()
)

print("S2 arrays ready:", len(s2_ids))
print("Names:", len(s2_names_a))
print("Addresses:", len(s2_addrs_a))
print("Countries:", len(s2_countries_a))

gc.collect()

S2 rows: 4887273
S2 arrays ready: 4887273
Names: 4887273
Addresses: 4887273
Countries: 4887273

95

In [ ]:
from collections import defaultdict, Counter
import pickle
import os
import gc

INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"
os.makedirs(INDEX_DIR, exist_ok=True)

RARITY_LIMIT = 500

print("Building S2 name index...")

s2_name_index = defaultdict(list)
s2_name_freq = Counter()

for eid, text in enumerate(s2_names_a):
    tokens = set(text.split())
    for tok in tokens:
        s2_name_index[tok].append(eid)
        s2_name_freq[tok] += 1

print("Name index keys:", len(s2_name_index))

print("Building S2 address index...")

s2_addr_index = defaultdict(list)
s2_addr_freq = Counter()

for eid, text in enumerate(s2_addrs_a):
    tokens = set(text.split())
    for tok in tokens:
        s2_addr_index[tok].append(eid)
        s2_addr_freq[tok] += 1

print("Address index keys:", len(s2_addr_index))

gc.collect()

print("Saving S2 indexes...")

with open(f"{INDEX_DIR}/s2_name_index.pkl", "wb") as f:
    pickle.dump(dict(s2_name_index), f, protocol=pickle.HIGHEST_PROTOCOL)

with open(f"{INDEX_DIR}/s2_addr_index.pkl", "wb") as f:
    pickle.dump(dict(s2_addr_index), f, protocol=pickle.HIGHEST_PROTOCOL)

with open(f"{INDEX_DIR}/s2_name_freq.pkl", "wb") as f:
    pickle.dump(dict(s2_name_freq), f, protocol=pickle.HIGHEST_PROTOCOL)

with open(f"{INDEX_DIR}/s2_addr_freq.pkl", "wb") as f:
    pickle.dump(dict(s2_addr_freq), f, protocol=pickle.HIGHEST_PROTOCOL)

print("✅ S2 indexes saved to Drive")
print(INDEX_DIR)

Building S2 name index...
Name index keys: 690486
Building S2 address index...
Address index keys: 603004
Saving S2 indexes...
✅ S2 indexes saved to Drive
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes

In [ ]:
import os

TRAIN_DIR = "/content/amazon_ml_challenge/student_resource/dataset/train"

for f in [
    "train_source1.tsv",
    "train_source2.tsv",
    "train_source3.tsv",
    "train_ground_truth.tsv"
]:
    path = os.path.join(TRAIN_DIR, f)
    print(f, round(os.path.getsize(path) / (1024 * 1024), 2), "MB")

train_source1.tsv 200.34 MB
train_source2.tsv 466.63 MB
train_source3.tsv 480.37 MB
train_ground_truth.tsv 121.13 MB

In [ ]:
import psutil

ram = psutil.virtual_memory()

print("Total RAM:", round(ram.total / 1024**3, 2), "GB")
print("Available RAM:", round(ram.available / 1024**3, 2), "GB")
print("Used RAM:", round(ram.used / 1024**3, 2), "GB")

Total RAM: 12.67 GB
Available RAM: 4.45 GB
Used RAM: 7.9 GB

In [ ]:
import gc

# S2 indexes are already saved to Drive.
# We no longer need the large S2 dataframe/arrays in RAM.

for name in [
    "s2",
    "s2_ids",
    "s2_names_a",
    "s2_addrs_a",
    "s2_countries_a"
]:
    if name in globals():
        del globals()[name]

gc.collect()

import psutil
ram = psutil.virtual_memory()

print("Available RAM:", round(ram.available / 1024**3, 2), "GB")
print("Used RAM:", round(ram.used / 1024**3, 2), "GB")

Available RAM: 6.48 GB
Used RAM: 5.88 GB

In [ ]:
import gc

if "test_s1" in globals():
    del test_s1

gc.collect()

import psutil
ram = psutil.virtual_memory()

print("Available RAM:", round(ram.available / 1024**3, 2), "GB")
print("Used RAM:", round(ram.used / 1024**3, 2), "GB")

Available RAM: 6.87 GB
Used RAM: 5.49 GB

In [ ]:
import pandas as pd
import gc

S3_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

s3 = pd.read_csv(
    S3_PATH,
    sep="\t",
    dtype=str,
    usecols=["entity_id", "business_name", "business_address", "country"]
)

print("S3 rows:", len(s3))
print("Available RAM after load:",
      round(__import__("psutil").virtual_memory().available / 1024**3, 2),
      "GB")

S3 rows: 5082316
Available RAM after load: 5.96 GB

In [ ]:
import numpy as np
import re
import unicodedata
import gc

def normalize_advanced(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

s3_ids = s3["entity_id"].to_numpy()

s3_names_a = np.array(
    [normalize_advanced(x) for x in s3["business_name"].fillna("")],
    dtype=object
)

s3_addrs_a = np.array(
    [normalize_advanced(x) for x in s3["business_address"].fillna("")],
    dtype=object
)

s3_countries_a = (
    s3["country"].fillna("").str.lower().str.strip().to_numpy()
)

print("S3 arrays:", len(s3_ids))
print("Available RAM:",
      round(__import__("psutil").virtual_memory().available / 1024**3, 2),
      "GB")

gc.collect()

S3 arrays: 5082316
Available RAM: 6.43 GB

28

In [ ]:
import gc
import psutil

del s3
gc.collect()

print("S3 dataframe freed.")
print("Available RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")
print("S3 arrays still available:", len(s3_ids))

S3 dataframe freed.
Available RAM: 6.53 GB
S3 arrays still available: 5082316

In [ ]:
import pickle
from collections import defaultdict, Counter
import gc
import psutil
import os

INDEX_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes"
os.makedirs(INDEX_DIR, exist_ok=True)

# Build name index + frequency
s3_name_idx = defaultdict(list)
s3_name_freq = Counter()

for i, name in enumerate(s3_names_a):
    for token in name.split():
        s3_name_idx[token].append(s3_ids[i])
        s3_name_freq[token] += 1

print("Name index built:", len(s3_name_idx))
print("RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")

# Build address index + frequency
s3_addr_idx = defaultdict(list)
s3_addr_freq = Counter()

for i, addr in enumerate(s3_addrs_a):
    for token in addr.split():
        s3_addr_idx[token].append(s3_ids[i])
        s3_addr_freq[token] += 1

print("Address index built:", len(s3_addr_idx))
print("RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")

# Save immediately
with open(f"{INDEX_DIR}/s3_name_index.pkl", "wb") as f:
    pickle.dump(dict(s3_name_idx), f, protocol=pickle.HIGHEST_PROTOCOL)

with open(f"{INDEX_DIR}/s3_addr_index.pkl", "wb") as f:
    pickle.dump(dict(s3_addr_idx), f, protocol=pickle.HIGHEST_PROTOCOL)

with open(f"{INDEX_DIR}/s3_name_freq.pkl", "wb") as f:
    pickle.dump(dict(s3_name_freq), f, protocol=pickle.HIGHEST_PROTOCOL)

with open(f"{INDEX_DIR}/s3_addr_freq.pkl", "wb") as f:
    pickle.dump(dict(s3_addr_freq), f, protocol=pickle.HIGHEST_PROTOCOL)

print("✅ All 4 S3 indexes saved.")

Name index built: 734717
RAM: 6.2 GB
Address index built: 574797
RAM: 5.77 GB
✅ All 4 S3 indexes saved.

In [ ]:
import os

TRAIN_DIR = "/content/amazon_ml_challenge/student_resource/dataset/train"

for f in [
    "train_source1.tsv",
    "train_source2.tsv",
    "train_source3.tsv",
    "train_ground_truth.tsv"
]:
    p = os.path.join(TRAIN_DIR, f)
    print(f"{f:25} {os.path.exists(p)}   {os.path.getsize(p)/1024**2:.1f} MB")

train_source1.tsv         True   200.3 MB
train_source2.tsv         True   466.6 MB
train_source3.tsv         True   480.4 MB
train_ground_truth.tsv    True   121.1 MB

In [ ]:
import gc
import psutil

for name in [
    "s3_name_idx", "s3_addr_idx", "s3_name_freq", "s3_addr_freq",
    "s3_names_a", "s3_addrs_a", "s3_countries_a", "s3_ids"
]:
    if name in globals():
        del globals()[name]

gc.collect()

print("Unnecessary S3 objects freed.")
print("Available RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")

Unnecessary S3 objects freed.
Available RAM: 8.24 GB

In [ ]:
import pandas as pd
import gc
import psutil

TRAIN_DIR = "/content/amazon_ml_challenge/student_resource/dataset/train"

s1_train = pd.read_csv(
    f"{TRAIN_DIR}/train_source1.tsv",
    sep="\t",
    dtype=str
)

gt = pd.read_csv(
    f"{TRAIN_DIR}/train_ground_truth.tsv",
    sep="\t",
    dtype=str
)

print("S1:", s1_train.shape)
print("GT:", gt.shape)
print("Available RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")

S1: (2206821, 4)
GT: (2206821, 2)
Available RAM: 8.1 GB

In [ ]:
import gc
import psutil

gt_lookup = {}

for sid, matches in zip(
    gt["source1_entity_id"],
    gt["matched_entity_ids"].fillna("")
):
    gt_lookup[sid] = set(
        x.strip() for x in str(matches).split(",")
        if x.strip()
    )

del gt
gc.collect()

print("GT lookup:", len(gt_lookup))
print("Available RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")

GT lookup: 2206821
Available RAM: 6.8 GB

In [ ]:
import re
import unicodedata
import gc
import psutil

def normalize_advanced(text):
    if pd.isna(text):
        return ""
    text = str(text).lower().strip()
    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

def normalize_country(text):
    if pd.isna(text):
        return ""
    return str(text).lower().strip()

train_ids = s1_train["entity_id"].to_numpy()

train_names = np.array(
    [normalize_advanced(x) for x in s1_train["business_name"].fillna("")],
    dtype=object
)

train_addrs = np.array(
    [normalize_advanced(x) for x in s1_train["business_address"].fillna("")],
    dtype=object
)

train_countries = s1_train["country"].fillna("").str.lower().str.strip().to_numpy()

print("S1 arrays:", len(train_ids))
print("Available RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")

S1 arrays: 2206821
Available RAM: 6.61 GB

In [ ]:
from collections import defaultdict

train_name_map = defaultdict(list)
train_address_map = defaultdict(list)

for i in range(len(train_ids)):
    sid = train_ids[i]
    country = train_countries[i]

    if train_names[i]:
        train_name_map[(country, train_names[i])].append(sid)

    if train_addrs[i]:
        train_address_map[(country, train_addrs[i])].append(sid)

print("Name keys:", len(train_name_map))
print("Address keys:", len(train_address_map))

Name keys: 1522823
Address keys: 2129981

In [ ]:
from collections import Counter
import pandas as pd
import gc
import psutil

name_freq = Counter()
addr_freq = Counter()

TRAIN_S2 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source2.tsv"
TRAIN_S3 = "/content/amazon_ml_challenge/student_resource/dataset/train/train_source3.tsv"

def add_freq(path):
    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_name", "business_address"],
        chunksize=100_000
    ):
        names = chunk["business_name"].fillna("").map(normalize_advanced)
        addrs = chunk["business_address"].fillna("").map(normalize_advanced)

        for x in names:
            name_freq.update(set(x.split()))

        for x in addrs:
            addr_freq.update(set(x.split()))

        del chunk, names, addrs
        gc.collect()

add_freq(TRAIN_S2)
add_freq(TRAIN_S3)

print("Name tokens:", len(name_freq))
print("Address tokens:", len(addr_freq))
print("Available RAM:", round(psutil.virtual_memory().available / 1024**3, 2), "GB")

Name tokens: 1455872
Address tokens: 732777
Available RAM: 5.55 GB

In [ ]:
# Rebuild training vocabularies
# Uses the train_names/train_addrs arrays already created earlier.

train_name_vocab = set()
train_address_vocab = set()

for x in train_names:
    if x:
        train_name_vocab.update(x.split())

for x in train_addrs:
    if x:
        train_address_vocab.update(x.split())

print("Name tokens:", len(train_name_vocab))
print("Address tokens:", len(train_address_vocab))
print(
    "Available RAM:",
    round(psutil.virtual_memory().available / 1024**3, 2),
    "GB"
)

Name tokens: 108675
Address tokens: 441675
Available RAM: 5.54 GB

In [ ]:
import os
import pickle
import gc

CHECKPOINT_DIR = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_training_checkpoint"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# Save S1 normalized arrays
with open(f"{CHECKPOINT_DIR}/train_s1_arrays.pkl", "wb") as f:
    pickle.dump(
        {
            "train_ids": train_ids,
            "train_names": train_names,
            "train_addrs": train_addrs,
            "train_countries": train_countries,
        },
        f,
        protocol=pickle.HIGHEST_PROTOCOL
    )

# Save exact lookup maps
with open(f"{CHECKPOINT_DIR}/train_exact_maps.pkl", "wb") as f:
    pickle.dump(
        {
            "train_name_map": dict(train_name_map),
            "train_address_map": dict(train_address_map),
        },
        f,
        protocol=pickle.HIGHEST_PROTOCOL
    )

# Save ground-truth lookup
with open(f"{CHECKPOINT_DIR}/gt_lookup.pkl", "wb") as f:
    pickle.dump(gt_lookup, f, protocol=pickle.HIGHEST_PROTOCOL)

# Save vocabularies if they currently exist
if "train_name_vocab" in globals() and "train_address_vocab" in globals():
    with open(f"{CHECKPOINT_DIR}/train_vocabs.pkl", "wb") as f:
        pickle.dump(
            {
                "train_name_vocab": train_name_vocab,
                "train_address_vocab": train_address_vocab,
            },
            f,
            protocol=pickle.HIGHEST_PROTOCOL
        )
    print("✓ Vocabularies saved")
else:
    print("⚠ Vocabularies not currently in memory — will rebuild later")

print("\n========== CHECKPOINT SAVED ==========")
print("Location:", CHECKPOINT_DIR)

for filename in sorted(os.listdir(CHECKPOINT_DIR)):
    size_mb = os.path.getsize(
        os.path.join(CHECKPOINT_DIR, filename)
    ) / (1024**2)
    print(f"{filename:30s} {size_mb:,.1f} MB")

gc.collect()

✓ Vocabularies saved

========== CHECKPOINT SAVED ==========
Location: /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_training_checkpoint
gt_lookup.pkl                  148.0 MB
train_exact_maps.pkl           220.6 MB
train_s1_arrays.pkl            206.0 MB
train_vocabs.pkl               5.5 MB

30

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

BASE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"

print("BASE exists:", os.path.exists(BASE))

for root, dirs, files in os.walk(BASE):
    for f in files:
        if any(x in f.lower() for x in [
            "index", "freq", "model", "candidate", "result"
        ]):
            path = os.path.join(root, f)
            size_mb = os.path.getsize(path) / (1024**2)
            print(f"{size_mb:8.1f} MB | {path}")

Mounted at /content/drive
BASE exists: True
     1.4 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm
    96.4 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s2_name_index.pkl
   196.7 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s2_addr_index.pkl
    12.7 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s2_name_freq.pkl
    16.5 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s2_addr_freq.pkl
   100.9 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s3_name_index.pkl
   196.1 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s3_addr_index.pkl
    13.6 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s3_name_freq.pkl
    16.0 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_full_indexes/s3_addr_freq.pkl
    18.8 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Inference/matching_results_v5.tsv
    53.4 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Inference/candidate_pairs_v5.tsv
   172.5 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s2_candidates.tsv
    37.7 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s2_results.tsv
    17.0 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s3_results.tsv
    69.6 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s3_candidates.tsv
   113.1 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE/s2_results.tsv
   110.6 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE/s3_results.tsv
    43.3 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv
    43.3 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/candidate_pairs.tsv
     0.2 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Validation/v51_validation_s2_candidates.tsv

In [ ]:
import os

PROD = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE"

files = [
    "s2_results.tsv",
    "s3_results.tsv",
    "s2_candidates.tsv",
    "s3_candidates.tsv",
]

print("========== FILE CHECK ==========")

for f in files:
    path = os.path.join(PROD, f)

    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fp:
            header = fp.readline().strip()
            rows = sum(1 for _ in fp)

        size_mb = os.path.getsize(path) / (1024**2)

        print(f"\n{f}")
        print("  Size :", round(size_mb, 1), "MB")
        print("  Rows :", f"{rows:,}")
        print("  Header:", header)
    else:
        print("\nMISSING:", f)

========== FILE CHECK ==========

s2_results.tsv
  Size : 113.1 MB
  Rows : 1,732,544
  Header: source1_entity_id	candidate_entity_ids	matched_entity_ids

s3_results.tsv
  Size : 110.6 MB
  Rows : 1,732,544
  Header: source1_entity_id	candidate_entity_ids	matched_entity_ids

MISSING: s2_candidates.tsv

MISSING: s3_candidates.tsv

In [ ]:
import os

PROD = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE"
OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION"

os.makedirs(OUT, exist_ok=True)

def split_result_file(source_file, matching_file, candidate_file):
    with open(source_file, "r", encoding="utf-8") as fin, \
         open(matching_file, "w", encoding="utf-8") as fout_match, \
         open(candidate_file, "w", encoding="utf-8") as fout_cand:

        header = fin.readline().strip()

        # Required submission headers
        fout_match.write("source1_entity_id\tmatched_entity_ids\n")
        fout_cand.write("source1_entity_id\tcandidate_entity_ids\n")

        rows = 0

        for line in fin:
            parts = line.rstrip("\n").split("\t")

            if len(parts) != 3:
                raise ValueError(
                    f"Bad line at row {rows + 2}: {parts}"
                )

            s1_id, candidates, matches = parts

            fout_match.write(
                f"{s1_id}\t{matches}\n"
            )

            fout_cand.write(
                f"{s1_id}\t{candidates}\n"
            )

            rows += 1

            if rows % 500_000 == 0:
                print(f"Processed {rows:,} rows")

    return rows


print("=== BUILDING S2 FILES ===")

n2 = split_result_file(
    f"{PROD}/s2_results.tsv",
    f"{OUT}/matching_results_s2.tsv",
    f"{OUT}/candidate_pairs_s2.tsv"
)

print("\n=== BUILDING S3 FILES ===")

n3 = split_result_file(
    f"{PROD}/s3_results.tsv",
    f"{OUT}/matching_results_s3.tsv",
    f"{OUT}/candidate_pairs_s3.tsv"
)

print("\n========== DONE ==========")
print("S2 rows:", f"{n2:,}")
print("S3 rows:", f"{n3:,}")
print("Output folder:", OUT)

for f in sorted(os.listdir(OUT)):
    size_mb = os.path.getsize(os.path.join(OUT, f)) / (1024**2)
    print(f"{f:30s} {size_mb:,.1f} MB")

=== BUILDING S2 FILES ===
Processed 500,000 rows
Processed 1,000,000 rows
Processed 1,500,000 rows

=== BUILDING S3 FILES ===
Processed 500,000 rows
Processed 1,000,000 rows
Processed 1,500,000 rows

========== DONE ==========
S2 rows: 1,732,544
S3 rows: 1,732,544
Output folder: /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION
candidate_pairs_s2.tsv         91.3 MB
candidate_pairs_s3.tsv         90.1 MB
matching_results_s2.tsv        41.5 MB
matching_results_s3.tsv        40.1 MB

In [ ]:
# Inspect the first 5 rows of our generated files

OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION"

for f in [
    "matching_results_s2.tsv",
    "matching_results_s3.tsv",
    "candidate_pairs_s2.tsv",
    "candidate_pairs_s3.tsv"
]:
    print("\n==========", f, "==========")
    with open(f"{OUT}/{f}", "r", encoding="utf-8") as fp:
        for _ in range(3):
            print(fp.readline().rstrip())

========== matching_results_s2.tsv ==========
source1_entity_id	matched_entity_ids
S1-714132312	S2-786029403,S2-435263846
S1-106407869

========== matching_results_s3.tsv ==========
source1_entity_id	matched_entity_ids
S1-714132312	S3-625880872,S3-867809779
S1-106407869

========== candidate_pairs_s2.tsv ==========
source1_entity_id	candidate_entity_ids
S1-714132312	S2-786029403,S2-187020300,S2-637340732,S2-435263846
S1-106407869

========== candidate_pairs_s3.tsv ==========
source1_entity_id	candidate_entity_ids
S1-714132312	S3-625880872,S3-867809779
S1-106407869

In [ ]:
import os

OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION"

S2_MATCH = f"{OUT}/matching_results_s2.tsv"
S3_MATCH = f"{OUT}/matching_results_s3.tsv"

S2_CAND = f"{OUT}/candidate_pairs_s2.tsv"
S3_CAND = f"{OUT}/candidate_pairs_s3.tsv"

FINAL_MATCH = f"{OUT}/matching_results.tsv"
FINAL_CAND = f"{OUT}/candidate_pairs.tsv"


def combine_files(file1, file2, output, column_name):

    with open(file1, "r", encoding="utf-8") as f1, \
         open(file2, "r", encoding="utf-8") as f2, \
         open(output, "w", encoding="utf-8") as fout:

        # Skip headers
        f1.readline()
        f2.readline()

        fout.write(f"source1_entity_id\t{column_name}\n")

        rows = 0

        while True:
            line1 = f1.readline()
            line2 = f2.readline()

            if not line1 and not line2:
                break

            if not line1 or not line2:
                raise ValueError("S2/S3 row counts do not match!")

            p1 = line1.rstrip("\n").split("\t", 1)
            p2 = line2.rstrip("\n").split("\t", 1)

            s1_2, ids2 = p1
            s1_3, ids3 = p2

            if s1_2 != s1_3:
                raise ValueError(
                    f"S1 mismatch: {s1_2} != {s1_3}"
                )

            combined = []

            if ids2.strip():
                combined.extend(ids2.split(","))

            if ids3.strip():
                combined.extend(ids3.split(","))

            fout.write(
                f"{s1_2}\t{','.join(combined)}\n"
            )

            rows += 1

            if rows % 500_000 == 0:
                print(f"Combined {rows:,} rows")

    return rows


print("=== COMBINING MATCHING RESULTS ===")

match_rows = combine_files(
    S2_MATCH,
    S3_MATCH,
    FINAL_MATCH,
    "matched_entity_ids"
)

print("\n=== COMBINING CANDIDATES ===")

candidate_rows = combine_files(
    S2_CAND,
    S3_CAND,
    FINAL_CAND,
    "candidate_entity_ids"
)

print("\n========== FINAL FILES ==========")
print("Matching rows :", f"{match_rows:,}")
print("Candidate rows:", f"{candidate_rows:,}")

print("\nFiles:")
print(FINAL_MATCH)
print(FINAL_CAND)

=== COMBINING MATCHING RESULTS ===
Combined 500,000 rows
Combined 1,000,000 rows
Combined 1,500,000 rows

=== COMBINING CANDIDATES ===
Combined 500,000 rows
Combined 1,000,000 rows
Combined 1,500,000 rows

========== FINAL FILES ==========
Matching rows : 1,732,544
Candidate rows: 1,732,544

Files:
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv
/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/candidate_pairs.tsv

In [ ]:
import os
import subprocess
import sys

BASE_DATA = "/content/amazon_ml_challenge/student_resource/dataset/test"
OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION"

VALIDATOR = "/content/amazon_ml_challenge/student_resource/utils/validate_submission.py"

print("Validator exists:", os.path.exists(VALIDATOR))
print("Test directory exists:", os.path.exists(BASE_DATA))

cmd = [
    sys.executable,
    VALIDATOR,
    "--matching",
    f"{OUT}/matching_results.tsv",
    "--candidate",
    f"{OUT}/candidate_pairs.tsv",
    "--test-dir",
    BASE_DATA
]

print("\nRunning official validator...\n")

result = subprocess.run(
    cmd,
    capture_output=True,
    text=True
)

print(result.stdout)

if result.stderr:
    print("STDERR:")
    print(result.stderr)

print("\nReturn code:", result.returncode)

Validator exists: False
Test directory exists: False

Running official validator...


STDERR:
/usr/bin/python3: can't open file '/content/amazon_ml_challenge/student_resource/utils/validate_submission.py': [Errno 2] No such file or directory


Return code: 2

In [ ]:
import os

print("Files in /content:")
for x in os.listdir("/content"):
    print(" -", x)

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"

print("\nZIP exists:", os.path.exists(ZIP_PATH))

Files in /content:
 - .config
 - drive
 - sample_data

ZIP exists: False

In [ ]:
import os
import csv

OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION"

MATCH = f"{OUT}/matching_results.tsv"
CAND = f"{OUT}/candidate_pairs.tsv"

match_rows = 0
cand_rows = 0
match_ids = set()
cand_ids = set()

bad_matches = 0
duplicate_match_s1 = 0
duplicate_cand_s1 = 0
empty_matches = 0
nonempty_matches = 0

# --------------------------------------------------
# Check matching file
# --------------------------------------------------

print("Checking matching_results.tsv ...")

with open(MATCH, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    header = next(reader)

    print("Header:", header)

    for row in reader:
        if len(row) != 2:
            bad_matches += 1
            continue

        s1, matches = row
        match_rows += 1

        if s1 in match_ids:
            duplicate_match_s1 += 1
        match_ids.add(s1)

        if matches.strip():
            nonempty_matches += 1
        else:
            empty_matches += 1


# --------------------------------------------------
# Check candidate file
# --------------------------------------------------

print("\nChecking candidate_pairs.tsv ...")

with open(CAND, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    header = next(reader)

    print("Header:", header)

    for row in reader:
        if len(row) != 2:
            continue

        s1, candidates = row
        cand_rows += 1

        if s1 in cand_ids:
            duplicate_cand_s1 += 1
        cand_ids.add(s1)


# --------------------------------------------------
# Compare S1 coverage
# --------------------------------------------------

missing_candidates = match_ids - cand_ids
extra_candidates = cand_ids - match_ids


# --------------------------------------------------
# Check every match is inside candidates
# --------------------------------------------------

print("\nChecking match ⊆ candidate ...")

# Build candidate lookup one S1 at a time
candidate_map = {}

with open(CAND, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    for s1, candidates in reader:
        candidate_map[s1] = set(
            x for x in candidates.split(",") if x
        )

with open(MATCH, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    checked = 0

    for s1, matches in reader:
        if matches.strip():
            candidates = candidate_map.get(s1, set())

            for mid in matches.split(","):
                if mid not in candidates:
                    bad_matches += 1

            checked += 1


print("\n==============================")
print("      SELF-VALIDATION")
print("==============================")

print("Matching rows       :", f"{match_rows:,}")
print("Candidate rows      :", f"{cand_rows:,}")
print("Unique matching S1  :", f"{len(match_ids):,}")
print("Unique candidate S1 :", f"{len(cand_ids):,}")

print("Duplicate match S1  :", duplicate_match_s1)
print("Duplicate cand S1   :", duplicate_cand_s1)

print("Empty matches       :", f"{empty_matches:,}")
print("Non-empty matches   :", f"{nonempty_matches:,}")

print("Missing candidate S1:", len(missing_candidates))
print("Extra candidate S1  :", len(extra_candidates))

print("Invalid matches     :", bad_matches)

print("\nEXPECTED:")
print("Rows should be      : 1,732,544")
print("Unique S1 should be : 1,732,544")
print("Invalid matches     : 0")

Checking matching_results.tsv ...
Header: ['source1_entity_id', 'matched_entity_ids']

Checking candidate_pairs.tsv ...
Header: ['source1_entity_id', 'candidate_entity_ids']

Checking match ⊆ candidate ...

==============================
      SELF-VALIDATION
==============================
Matching rows       : 1,732,544
Candidate rows      : 1,732,544
Unique matching S1  : 1,732,544
Unique candidate S1 : 1,732,544
Duplicate match S1  : 0
Duplicate cand S1   : 0
Empty matches       : 837,705
Non-empty matches   : 894,839
Missing candidate S1: 0
Extra candidate S1  : 0
Invalid matches     : 0

EXPECTED:
Rows should be      : 1,732,544
Unique S1 should be : 1,732,544
Invalid matches     : 0

In [ ]:
import os

OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION"

print("FINAL SUBMISSION FILES")

for f in [
    "matching_results.tsv",
    "candidate_pairs.tsv"
]:
    path = os.path.join(OUT, f)
    print(
        f"{f:25s}",
        round(os.path.getsize(path) / (1024**2), 2),
        "MB"
    )

FINAL SUBMISSION FILES
matching_results.tsv      59.25 MB
candidate_pairs.tsv       159.15 MB

In [ ]:
import os
import zipfile
from google.colab import files

OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION"
ZIP_PATH = "/content/V5_SUBMISSION.zip"

with zipfile.ZipFile(
    ZIP_PATH,
    "w",
    compression=zipfile.ZIP_DEFLATED
) as z:
    z.write(
        f"{OUT}/matching_results.tsv",
        arcname="matching_results.tsv"
    )
    z.write(
        f"{OUT}/candidate_pairs.tsv",
        arcname="candidate_pairs.tsv"
    )

print("ZIP created:")
print(ZIP_PATH)
print("Size:", round(os.path.getsize(ZIP_PATH) / (1024**2), 2), "MB")

files.download(ZIP_PATH)

ZIP created:
/content/V5_SUBMISSION.zip
Size: 91.68 MB

In [ ]:
from google.colab import files

MATCHING_FILE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"

files.download(MATCHING_FILE)

In [ ]:
import os

path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Inference/matching_results_v5.tsv"

print("Exists:", os.path.exists(path))

if os.path.exists(path):
    print("Size:", round(os.path.getsize(path) / (1024**2), 2), "MB")

    with open(path, "r", encoding="utf-8") as f:
        header = f.readline().strip()
        rows = 0
        nonempty = 0

        for line in f:
            rows += 1
            parts = line.rstrip("\n").split("\t", 1)

            if len(parts) == 2 and parts[1].strip():
                nonempty += 1

    print("Header:", header)
    print("Rows:", f"{rows:,}")
    print("Non-empty:", f"{nonempty:,}")
    print(
        "Match rate:",
        round(nonempty / rows * 100, 2),
        "%"
    )

Exists: True
Size: 18.79 MB
Header: source1_entity_id	matched_entity_ids
Rows: 632,000
Non-empty: 242,920
Match rate: 38.44 %

In [ ]:
import os

BASE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"

print("Searching for V5 scoring/probability files...\n")

keywords = [
    "prob",
    "score",
    "feature",
    "inference",
    "result"
]

for root, dirs, files in os.walk(BASE):
    for f in files:
        name = f.lower()

        if any(k in name for k in keywords):
            path = os.path.join(root, f)
            size_mb = os.path.getsize(path) / (1024**2)

            print(f"{size_mb:8.1f} MB | {path}")

Searching for V5 scoring/probability files...

    31.1 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/ml_features_v3_1000.pkl
     0.0 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_inference.py
     0.0 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_feature_list.txt
    31.1 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/ml_features_v3_1000.pkl
    18.8 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Inference/matching_results_v5.tsv
    37.7 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s2_results.tsv
    17.0 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production/s3_results.tsv
   113.1 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE/s2_results.tsv
   110.6 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_Final_Production_RAMSAFE/s3_results.tsv
    43.3 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv
    41.5 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_s2.tsv
    40.1 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_s3.tsv
    59.2 MB | /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv

In [ ]:
import csv
from collections import Counter

MATCH = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"

match_count_dist = Counter()

with open(MATCH, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    for s1, matches in reader:
        if not matches.strip():
            match_count_dist[0] += 1
        else:
            match_count_dist[len(matches.split(","))] += 1

print("========== MATCH DISTRIBUTION ==========")

total = sum(match_count_dist.values())

for k in sorted(match_count_dist):
    print(
        f"{k:3d} matches : "
        f"{match_count_dist[k]:,} S1 "
        f"({match_count_dist[k]/total*100:.2f}%)"
    )

print("\nTotal S1:", f"{total:,}")

========== MATCH DISTRIBUTION ==========
  0 matches : 837,705 S1 (48.35%)
  1 matches : 173,477 S1 (10.01%)
  2 matches : 165,737 S1 (9.57%)
  3 matches : 175,541 S1 (10.13%)
  4 matches : 153,549 S1 (8.86%)
  5 matches : 108,371 S1 (6.26%)
  6 matches : 62,360 S1 (3.60%)
  7 matches : 30,488 S1 (1.76%)
  8 matches : 12,795 S1 (0.74%)
  9 matches : 5,159 S1 (0.30%)
 10 matches : 2,250 S1 (0.13%)
 11 matches : 1,305 S1 (0.08%)
 12 matches : 906 S1 (0.05%)
 13 matches : 652 S1 (0.04%)
 14 matches : 508 S1 (0.03%)
 15 matches : 361 S1 (0.02%)
 16 matches : 292 S1 (0.02%)
 17 matches : 220 S1 (0.01%)
 18 matches : 157 S1 (0.01%)
 19 matches : 119 S1 (0.01%)
 20 matches : 79 S1 (0.00%)
 21 matches : 72 S1 (0.00%)
 22 matches : 71 S1 (0.00%)
 23 matches : 43 S1 (0.00%)
 24 matches : 47 S1 (0.00%)
 25 matches : 32 S1 (0.00%)
 26 matches : 29 S1 (0.00%)
 27 matches : 22 S1 (0.00%)
 28 matches : 31 S1 (0.00%)
 29 matches : 16 S1 (0.00%)
 30 matches : 21 S1 (0.00%)
 31 matches : 11 S1 (0.00%)
 32 matches : 21 S1 (0.00%)
 33 matches : 10 S1 (0.00%)
 34 matches : 8 S1 (0.00%)
 35 matches : 10 S1 (0.00%)
 36 matches : 10 S1 (0.00%)
 37 matches : 3 S1 (0.00%)
 38 matches : 4 S1 (0.00%)
 39 matches : 5 S1 (0.00%)
 40 matches : 3 S1 (0.00%)
 41 matches : 5 S1 (0.00%)
 42 matches : 3 S1 (0.00%)
 43 matches : 4 S1 (0.00%)
 44 matches : 1 S1 (0.00%)
 45 matches : 2 S1 (0.00%)
 46 matches : 3 S1 (0.00%)
 48 matches : 2 S1 (0.00%)
 49 matches : 3 S1 (0.00%)
 50 matches : 2 S1 (0.00%)
 52 matches : 3 S1 (0.00%)
 54 matches : 4 S1 (0.00%)
 55 matches : 2 S1 (0.00%)
 58 matches : 2 S1 (0.00%)
 59 matches : 1 S1 (0.00%)
 60 matches : 1 S1 (0.00%)
 61 matches : 1 S1 (0.00%)
 63 matches : 1 S1 (0.00%)
 65 matches : 1 S1 (0.00%)
 66 matches : 1 S1 (0.00%)
 72 matches : 1 S1 (0.00%)
116 matches : 1 S1 (0.00%)

Total S1: 1,732,544

In [ ]:
import csv
from collections import Counter

MATCH = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"

dist = Counter()

with open(MATCH, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    for s1, matches in reader:
        n = 0 if not matches.strip() else len(matches.split(","))
        dist[n] += 1

total = sum(dist.values())

print("========== CRITICAL MATCH SUMMARY ==========")

for n in range(0, 6):
    count = dist[n]
    print(
        f"{n} matches : {count:,} "
        f"({count/total*100:.2f}%)"
    )

five_plus = sum(v for k, v in dist.items() if k >= 5)
one_plus = total - dist[0]

print("\n1+ matches :", f"{one_plus:,}")
print("2+ matches :", f"{sum(v for k,v in dist.items() if k >= 2):,}")
print("3+ matches :", f"{sum(v for k,v in dist.items() if k >= 3):,}")
print("5+ matches :", f"{five_plus:,}")
print("Total S1   :", f"{total:,}")

========== CRITICAL MATCH SUMMARY ==========
0 matches : 837,705 (48.35%)
1 matches : 173,477 (10.01%)
2 matches : 165,737 (9.57%)
3 matches : 175,541 (10.13%)
4 matches : 153,549 (8.86%)
5 matches : 108,371 (6.26%)

1+ matches : 894,839
2+ matches : 721,362
3+ matches : 555,625
5+ matches : 226,535
Total S1   : 1,732,544

In [ ]:
import csv
import os

SRC = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"
OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_conservative1.tsv"

kept = 0
emptied = 0

with open(SRC, "r", encoding="utf-8") as fin, \
     open(OUT, "w", encoding="utf-8") as fout:

    reader = csv.reader(fin, delimiter="\t")
    writer = csv.writer(fout, delimiter="\t", lineterminator="\n")

    header = next(reader)
    writer.writerow(header)

    for s1, matches in reader:

        ids = [x for x in matches.split(",") if x]

        if len(ids) == 1:
            writer.writerow([s1, ids[0]])
            kept += 1
        else:
            writer.writerow([s1, ""])
            emptied += 1

print("Created:", OUT)
print("Kept single-match S1:", f"{kept:,}")
print("Emptied multi/zero S1 :", f"{emptied:,}")
print("Total:", f"{kept + emptied:,}")

Created: /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_conservative1.tsv
Kept single-match S1: 173,477
Emptied multi/zero S1 : 1,559,067
Total: 1,732,544

In [ ]:
import csv

SRC = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"
OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_conservative2.tsv"

kept = 0
emptied = 0

with open(SRC, "r", encoding="utf-8") as fin, \
     open(OUT, "w", encoding="utf-8") as fout:

    reader = csv.reader(fin, delimiter="\t")
    writer = csv.writer(fout, delimiter="\t", lineterminator="\n")

    writer.writerow(next(reader))

    for s1, matches in reader:
        ids = [x for x in matches.split(",") if x]

        if 1 <= len(ids) <= 2:
            writer.writerow([s1, ",".join(ids)])
            kept += 1
        else:
            writer.writerow([s1, ""])
            emptied += 1

print("Created:", OUT)
print("Kept S1:", f"{kept:,}")
print("Emptied S1:", f"{emptied:,}")
print("Total:", f"{kept + emptied:,}")

Created: /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_conservative2.tsv
Kept S1: 339,214
Emptied S1: 1,393,330
Total: 1,732,544

In [ ]:
import csv
from collections import Counter

V1 = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv"
V5 = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"

v1 = {}
v1_dist = Counter()

print("Reading V1.1...")

with open(V1, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    for s1, matches in reader:
        ids = set(x for x in matches.split(",") if x)
        v1[s1] = ids
        v1_dist[len(ids)] += 1

print("V1.1 rows:", f"{len(v1):,}")
print("V1.1 non-empty:", f"{sum(v for k,v in v1_dist.items() if k > 0):,}")

overlap_entities = 0
overlap_matches = 0
v5_nonempty = 0

print("\nComparing V5...")

with open(V5, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    for s1, matches in reader:
        v5_ids = set(x for x in matches.split(",") if x)

        if v5_ids:
            v5_nonempty += 1

        common = v1.get(s1, set()) & v5_ids

        if common:
            overlap_entities += 1
            overlap_matches += len(common)

print("\n========== OVERLAP ==========")
print("V1.1 non-empty S1 :", f"{sum(v for k,v in v1_dist.items() if k > 0):,}")
print("V5 non-empty S1   :", f"{v5_nonempty:,}")
print("Common S1 entities:", f"{overlap_entities:,}")
print("Common match IDs  :", f"{overlap_matches:,}")

print("\nV1.1 distribution:")
for k in sorted(v1_dist):
    if k <= 5:
        print(f"{k} matches:", f"{v1_dist[k]:,}")

Reading V1.1...
V1.1 rows: 1,732,544
V1.1 non-empty: 912,910

Comparing V5...

========== OVERLAP ==========
V1.1 non-empty S1 : 912,910
V5 non-empty S1   : 894,839
Common S1 entities: 430,736
Common match IDs  : 670,487

V1.1 distribution:
0 matches: 819,634
1 matches: 471,711
2 matches: 257,239
3 matches: 110,833
4 matches: 41,093
5 matches: 15,237

In [ ]:
import csv

V1 = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv"
V5 = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"

OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_intersection.tsv"

# Load V1.1 IDs
v1 = {}

with open(V1, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    for s1, matches in reader:
        v1[s1] = set(x for x in matches.split(",") if x)

common_s1 = 0
common_ids = 0
total = 0

with open(V5, "r", encoding="utf-8") as fin, \
     open(OUT, "w", encoding="utf-8") as fout:

    reader = csv.reader(fin, delimiter="\t")
    writer = csv.writer(fout, delimiter="\t", lineterminator="\n")

    next(reader)
    writer.writerow(["source1_entity_id", "matched_entity_ids"])

    for s1, matches in reader:
        v5_ids = set(x for x in matches.split(",") if x)

        common = v1.get(s1, set()) & v5_ids

        if common:
            common_s1 += 1
            common_ids += len(common)
            writer.writerow([s1, ",".join(sorted(common))])
        else:
            writer.writerow([s1, ""])

        total += 1

print("========== INTERSECTION ==========")
print("Total S1       :", f"{total:,}")
print("Non-empty S1   :", f"{common_s1:,}")
print("Common match IDs:", f"{common_ids:,}")
print("Match rate     :", round(common_s1 / total * 100, 2), "%")
print("Output         :", OUT)

========== INTERSECTION ==========
Total S1       : 1,732,544
Non-empty S1   : 430,736
Common match IDs: 670,487
Match rate     : 24.86 %
Output         : /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_intersection.tsv

In [ ]:
import csv
import os

FILE = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_intersection.tsv"

rows = 0
nonempty = 0

with open(FILE, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    header = next(reader)

    for s1, matches in reader:
        rows += 1
        if matches.strip():
            nonempty += 1

print("Header:", header)
print("Rows:", f"{rows:,}")
print("Non-empty:", f"{nonempty:,}")
print("Size:", round(os.path.getsize(FILE) / (1024**2), 2), "MB")

Header: ['source1_entity_id', 'matched_entity_ids']
Rows: 1,732,544
Non-empty: 430,736
Size: 30.78 MB

In [ ]:
from google.colab import files
import shutil

SRC = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_intersection.tsv"
FINAL = "/content/matching_results.tsv"

shutil.copy2(SRC, FINAL)

print("Ready:", FINAL)

files.download(FINAL)

Ready: /content/matching_results.tsv

In [ ]:
import csv

V1 = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv"
V5 = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results.tsv"

OUT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_v1plus_v5single.tsv"

v1 = {}

with open(V1, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    next(reader)

    for s1, matches in reader:
        v1[s1] = matches.strip()

added = 0
kept_v1 = 0
empty = 0
total = 0

with open(V5, "r", encoding="utf-8") as fin, \
     open(OUT, "w", encoding="utf-8") as fout:

    reader = csv.reader(fin, delimiter="\t")
    writer = csv.writer(fout, delimiter="\t", lineterminator="\n")

    next(reader)
    writer.writerow(["source1_entity_id", "matched_entity_ids"])

    for s1, v5_matches in reader:

        v1_matches = v1.get(s1, "")

        # Proven V1.1 prediction wins
        if v1_matches:
            final_matches = v1_matches
            kept_v1 += 1

        else:
            v5_ids = [x for x in v5_matches.split(",") if x]

            # Add ONLY V5 singleton predictions
            if len(v5_ids) == 1:
                final_matches = v5_ids[0]
                added += 1
            else:
                final_matches = ""
                empty += 1

        writer.writerow([s1, final_matches])
        total += 1

print("========== HYBRID ==========")
print("Total S1          :", f"{total:,}")
print("V1.1 retained     :", f"{kept_v1:,}")
print("V5 singleton added:", f"{added:,}")
print("Empty             :", f"{empty:,}")
print("Output            :", OUT)

========== HYBRID ==========
Total S1          : 1,732,544
V1.1 retained     : 912,910
V5 singleton added: 91,330
Empty             : 728,304
Output            : /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_v1plus_v5single.tsv

In [ ]:
import pandas as pd
import re
import unicodedata
import gc

TEST_DIR = "/content/amazon_ml_challenge/student_resource/dataset/test"

HYBRID = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_v1plus_v5single.tsv"
V1 = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv"

def norm(x):
    if pd.isna(x):
        return ""
    x = unicodedata.normalize("NFKC", str(x).lower().strip())
    reps = {
        "&":" and ", "street":" st ", "road":" rd ",
        "avenue":" ave ", "drive":" dr ", "boulevard":" blvd ",
        "highway":" hwy ", "lane":" ln ", "parkway":" pkwy ",
        "place":" pl ", "suite":" ste "
    }
    for a,b in reps.items():
        x = x.replace(a,b)
    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

# --------------------------------------------------
# 1. Find ONLY the 91,330 V5-added S1 -> target pairs
# --------------------------------------------------

v1_matches = {}

with open(V1, "r", encoding="utf-8") as f:
    next(f)
    for line in f:
        sid, matches = line.rstrip("\n").split("\t", 1)
        if matches:
            v1_matches[sid] = matches

added = {}

with open(HYBRID, "r", encoding="utf-8") as f:
    next(f)
    for line in f:
        sid, matches = line.rstrip("\n").split("\t", 1)

        # Hybrid added a V5 singleton only when V1 was empty
        if not v1_matches.get(sid) and matches:
            added[sid] = matches

print("V5-only additions:", f"{len(added):,}")

# --------------------------------------------------
# 2. Load ONLY the relevant S1 rows
# --------------------------------------------------

s1_info = {}

for chunk in pd.read_csv(
    f"{TEST_DIR}/test_source1.tsv",
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100_000
):
    for row in chunk.itertuples(index=False):
        sid = row.entity_id

        if sid in added:
            s1_info[sid] = (
                norm(row.business_name),
                norm(row.business_address),
                norm(row.country)
            )

    if len(s1_info) == len(added):
        break

print("Relevant S1 loaded:", f"{len(s1_info):,}")

# --------------------------------------------------
# 3. Stream S2 + S3 and verify target rows
# --------------------------------------------------

exact_name = 0
exact_address = 0
exact_both = 0
exact_country = 0
strong_exact = 0
checked = 0

for source_name in ["test_source2.tsv", "test_source3.tsv"]:

    path = f"{TEST_DIR}/{source_name}"

    print("\nScanning", source_name)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=200_000
    ):
        for row in chunk.itertuples(index=False):

            target_id = row.entity_id

            # Find whether this target is one of our 91k additions
            matched_sid = None

            # Reverse lookup is expensive, so use a temporary target map
            # built below on first pass.
            if target_id in target_to_s1:
                matched_sid = target_to_s1[target_id]

            if matched_sid is None:
                continue

            n1, a1, c1 = s1_info[matched_sid]

            n2 = norm(row.business_name)
            a2 = norm(row.business_address)
            c2 = norm(row.country)

            checked += 1

            ne = bool(n1 and n1 == n2)
            ae = bool(a1 and a1 == a2)
            ce = bool(c1 and c1 == c2)

            if ne:
                exact_name += 1
            if ae:
                exact_address += 1
            if ne and ae:
                exact_both += 1
            if ce:
                exact_country += 1
            if ce and (ne or ae):
                strong_exact += 1

        del chunk
        gc.collect()

print("\n==============================")
print("V5 SINGLETON EVIDENCE CHECK")
print("==============================")
print("Additions:", f"{len(added):,}")
print("Target rows checked:", f"{checked:,}")
print("Exact name:", f"{exact_name:,}")
print("Exact address:", f"{exact_address:,}")
print("Exact both:", f"{exact_both:,}")
print("Exact country:", f"{exact_country:,}")
print("Exact name/address + country:", f"{strong_exact:,}")

V5-only additions: 91,330

FileNotFoundError: [Errno 2] No such file or directory: '/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv'

In [ ]:
from google.colab import files
import shutil
import os

SRC = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_SUBMISSION/matching_results_v1plus_v5single.tsv"
FINAL = "/content/matching_results.tsv"

shutil.copy2(SRC, FINAL)

print("File:", FINAL)
print("Size:", round(os.path.getsize(FINAL) / (1024**2), 2), "MB")

files.download(FINAL)

File: /content/matching_results.tsv
Size: 44.31 MB

In [ ]:
# ============================================================
# AMAZON ML CHALLENGE 2026
# ============================================================
# ONE-HOUR RAM-SAFE TRAINING AUDIT
#
# PURPOSE:
#   1. Verify cross-country behavior in actual TRAIN GT
#   2. Measure country-aware exact blocking recall
#   3. Measure country-aware address-number rescue
#   4. Measure exact-name / exact-address coverage
#   5. Measure true match cardinality
#   6. Produce evidence for the NEXT single submission
#
# IMPORTANT:
#   - NO leaderboard submission
#   - NO test prediction generation
#   - NO full S2/S3 loading
#   - Streaming/chunked only
#   - Sampled S1 validation to control runtime/RAM
# ============================================================

import os
import gc
import re
import csv
import time
import json
import math
import random
import unicodedata
from collections import defaultdict, Counter

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

DRIVE_ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

# We intentionally use a sample for the expensive S2/S3 scans.
# 50k is large enough to give useful evidence while staying RAM-safe.
SAMPLE_S1 = 50_000

# Chunk size for all large TSV files.
CHUNK_SIZE = 100_000

# Random seed for reproducibility.
SEED = 42

# Address-number frequency limit.
# We don't want extremely common numbers such as "1", "10", etc.
NUMBER_LIMIT = 1000

# Save results here.
AUDIT_DIR = os.path.join(
    DRIVE_ROOT,
    "ML_AUDIT",
    "Submission_A_Planning"
)

os.makedirs(AUDIT_DIR, exist_ok=True)

REPORT_FILE = os.path.join(
    AUDIT_DIR,
    "training_country_number_audit.txt"
)

JSON_FILE = os.path.join(
    AUDIT_DIR,
    "training_country_number_audit.json"
)

START_TIME = time.time()

print("=" * 80)
print("AMAZON ML CHALLENGE 2026")
print("RAM-SAFE TRAINING AUDIT")
print("=" * 80)
print("Drive root:", DRIVE_ROOT)
print("Sample S1:", f"{SAMPLE_S1:,}")
print("Chunk size:", f"{CHUNK_SIZE:,}")
print("Output:", AUDIT_DIR)
print()


# ============================================================
# 1. FIND TRAINING FILES
# ============================================================

print("=" * 80)
print("STEP 1 — LOCATING TRAINING DATA")
print("=" * 80)

target_names = {
    "train_source1.tsv",
    "train_source2.tsv",
    "train_source3.tsv",
    "train_ground_truth.tsv"
}

found = {}

# We search recursively but DO NOT read any files yet.
for root, dirs, files in os.walk(DRIVE_ROOT):

    # Ignore some potentially huge irrelevant directories.
    dirs[:] = [
        d for d in dirs
        if d not in {
            ".git",
            "__pycache__",
            "node_modules"
        }
    ]

    for fname in files:
        if fname in target_names:
            path = os.path.join(root, fname)

            # Keep first valid occurrence.
            if fname not in found:
                found[fname] = path

for name in sorted(target_names):
    if name in found:
        print("FOUND:", found[name])
    else:
        print("MISSING:", name)

print()

required = [
    "train_source1.tsv",
    "train_source2.tsv",
    "train_source3.tsv",
    "train_ground_truth.tsv"
]

missing = [x for x in required if x not in found]

if missing:
    print("=" * 80)
    print("TRAINING DATA NOT AVAILABLE ON DRIVE")
    print("=" * 80)
    print("Missing:")
    for x in missing:
        print(" -", x)

    print()
    print(
        "STOPPING SAFELY. No large data was loaded and no submission was changed."
    )

    with open(REPORT_FILE, "w", encoding="utf-8") as f:
        f.write("TRAINING AUDIT COULD NOT START\n\n")
        f.write("Missing files:\n")
        for x in missing:
            f.write(f"{x}\n")

    raise SystemExit


S1_PATH = found["train_source1.tsv"]
S2_PATH = found["train_source2.tsv"]
S3_PATH = found["train_source3.tsv"]
GT_PATH = found["train_ground_truth.tsv"]

print("All training files found.")
print()


# ============================================================
# 2. NORMALIZATION FUNCTIONS
# ============================================================

print("=" * 80)
print("STEP 2 — INITIALIZING NORMALIZATION")
print("=" * 80)

def normalize_country(x):
    if x is None:
        return ""
    return str(x).strip().lower()


def normalize_text(x):
    if x is None:
        return ""

    if pd.isna(x):
        return ""

    text = str(x).lower().strip()

    text = unicodedata.normalize("NFKC", text)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


_num_pattern = re.compile(r"\d+")


def extract_numbers(text):
    if not text:
        return set()

    return set(_num_pattern.findall(text))


def token_set(text):
    if not text:
        return set()

    return set(text.split())


# ============================================================
# 3. READ ONLY S1 + GT
# ============================================================

print("=" * 80)
print("STEP 3 — READING S1 + GROUND TRUTH")
print("=" * 80)

print("Loading S1 only...")

s1 = pd.read_csv(
    S1_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("S1 shape:", s1.shape)

# We only keep the columns we need.
s1 = s1[
    [
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
].copy()

# ------------------------------------------------------------
# Random sample
# ------------------------------------------------------------

random.seed(SEED)

if len(s1) > SAMPLE_S1:
    sample_indices = sorted(
        random.sample(
            range(len(s1)),
            SAMPLE_S1
        )
    )

    s1_sample = s1.iloc[sample_indices].copy()
else:
    s1_sample = s1.copy()

print(
    "Validation sample:",
    f"{len(s1_sample):,}"
)

# ------------------------------------------------------------
# Normalize sampled S1
# ------------------------------------------------------------

s1_sample["country_n"] = (
    s1_sample["country"]
    .map(normalize_country)
)

s1_sample["name_n"] = (
    s1_sample["business_name"]
    .map(normalize_text)
)

s1_sample["address_n"] = (
    s1_sample["business_address"]
    .map(normalize_text)
)

s1_sample["address_numbers"] = (
    s1_sample["address_n"]
    .map(extract_numbers)
)

s1_sample["address_tokens"] = (
    s1_sample["address_n"]
    .map(token_set)
)

# ------------------------------------------------------------
# Create compact lookup
# ------------------------------------------------------------

s1_rows = {}

for row in s1_sample.itertuples(index=False):

    s1_rows[row.entity_id] = {
        "country": row.country_n,
        "name": row.name_n,
        "address": row.address_n,
        "numbers": row.address_numbers,
        "tokens": row.address_tokens
    }

print("S1 sample prepared.")
print()

# Free the full S1 DataFrame.
del s1
gc.collect()


# ============================================================
# 4. READ GROUND TRUTH
# ============================================================

print("=" * 80)
print("STEP 4 — READING GROUND TRUTH FOR SAMPLE")
print("=" * 80)

# We ONLY retain GT rows for sampled S1 entities.
sample_ids = set(s1_rows.keys())

gt_sample = {}

gt_rows_read = 0
gt_rows_kept = 0

for chunk in pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=CHUNK_SIZE
):

    gt_rows_read += len(chunk)

    for row in chunk.itertuples(index=False):

        sid = row.source1_entity_id

        if sid not in sample_ids:
            continue

        value = row.matched_entity_ids.strip()

        if value:
            matches = [
                x.strip()
                for x in value.split(",")
                if x.strip()
            ]
        else:
            matches = []

        gt_sample[sid] = matches
        gt_rows_kept += 1

    if gt_rows_read % 1_000_000 == 0:
        print(
            "GT rows scanned:",
            f"{gt_rows_read:,}",
            "| sample GT rows:",
            f"{gt_rows_kept:,}"
        )

print()
print("GT rows scanned:", f"{gt_rows_read:,}")
print("GT sample rows:", f"{gt_rows_kept:,}")

# Ensure every sampled S1 has a GT entry.
for sid in sample_ids:
    if sid not in gt_sample:
        gt_sample[sid] = []

print()


# ============================================================
# 5. TRUE MATCH CARDINALITY
# ============================================================

print("=" * 80)
print("STEP 5 — TRUE MATCH CARDINALITY")
print("=" * 80)

gt_cardinality = Counter()

for sid, matches in gt_sample.items():
    gt_cardinality[len(matches)] += 1

total_gt_entities = len(gt_sample)

for k in sorted(gt_cardinality):
    count = gt_cardinality[k]
    pct = (
        100.0 * count / total_gt_entities
        if total_gt_entities
        else 0
    )

    print(
        f"{k:>3} matches : "
        f"{count:>8,} "
        f"({pct:6.2f}%)"
    )

print()

# Useful categories.
gt_nonempty = sum(
    count
    for k, count in gt_cardinality.items()
    if k > 0
)

gt_empty = gt_cardinality.get(0, 0)

gt_singleton = gt_cardinality.get(1, 0)

gt_multi = sum(
    count
    for k, count in gt_cardinality.items()
    if k >= 2
)

print("GT empty:", gt_empty)
print("GT non-empty:", gt_nonempty)
print("GT singleton:", gt_singleton)
print("GT multi-match:", gt_multi)
print()


# ============================================================
# 6. PREPARE GROUND-TRUTH ID SET
# ============================================================

print("=" * 80)
print("STEP 6 — PREPARING SAMPLE MATCH IDs")
print("=" * 80)

# This set is deliberately restricted to the 50k sample.
# It should remain manageable.
gt_match_ids = set()

for matches in gt_sample.values():
    for eid in matches:
        gt_match_ids.add(eid)

print(
    "Unique matched S2/S3 IDs in sample:",
    f"{len(gt_match_ids):,}"
)

print()


# ============================================================
# 7. STREAM S2 + S3
# ============================================================

print("=" * 80)
print("STEP 7 — STREAMING SOURCE 2 + SOURCE 3")
print("=" * 80)

print(
    "This is the expensive part.",
    "It will scan S2 and S3 without loading either file."
)
print()


# ------------------------------------------------------------
# Candidate statistics
# ------------------------------------------------------------

stats = {
    "rows_s2": 0,
    "rows_s3": 0,

    "gt_match_rows_seen": 0,

    "country_consistent_gt": 0,
    "country_inconsistent_gt": 0,

    "exact_name_hits": 0,
    "exact_address_hits": 0,

    "country_exact_name_hits": 0,
    "country_exact_address_hits": 0,

    "number_token_hits": 0,

    "gt_recovered_by_exact_name": 0,
    "gt_recovered_by_exact_address": 0,
    "gt_recovered_by_country_exact_name": 0,
    "gt_recovered_by_country_exact_address": 0,

    "gt_recovered_by_number_and_token": 0,

    "gt_total_links": 0
}


# ------------------------------------------------------------
# Build compact indexes from SAMPLE S1
# ------------------------------------------------------------

print("Building sample S1 indexes...")

name_index = defaultdict(set)
address_index = defaultdict(set)
country_name_index = defaultdict(set)
country_address_index = defaultdict(set)

country_number_index = defaultdict(set)

for sid, data in s1_rows.items():

    country = data["country"]
    name = data["name"]
    address = data["address"]

    if name:
        name_index[name].add(sid)

        if country:
            country_name_index[
                (country, name)
            ].add(sid)

    if address:
        address_index[address].add(sid)

        if country:
            country_address_index[
                (country, address)
            ].add(sid)

    for num in data["numbers"]:

        # We use country + number.
        if country and num:
            country_number_index[
                (country, num)
            ].add(sid)

print(
    "Name keys:",
    f"{len(name_index):,}"
)

print(
    "Address keys:",
    f"{len(address_index):,}"
)

print(
    "Country-name keys:",
    f"{len(country_name_index):,}"
)

print(
    "Country-address keys:",
    f"{len(country_address_index):,}"
)

print(
    "Country-number keys:",
    f"{len(country_number_index):,}"
)

print()


# ============================================================
# 8. STREAMING FUNCTION
# ============================================================

def process_source(path, source_name):

    print("-" * 80)
    print("PROCESSING", source_name)
    print("-" * 80)

    processed = 0
    last_report = 0

    # --------------------------------------------------------
    # We don't store all candidates.
    # We only accumulate whether TRUE GT links were recoverable.
    # --------------------------------------------------------

    local = {
        "gt_links": 0,
        "country_consistent": 0,
        "country_inconsistent": 0,

        "exact_name": 0,
        "exact_address": 0,

        "country_exact_name": 0,
        "country_exact_address": 0,

        "number_token": 0,

        "gt_exact_name": 0,
        "gt_exact_address": 0,

        "gt_country_exact_name": 0,
        "gt_country_exact_address": 0,

        "gt_number_token": 0
    }

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=CHUNK_SIZE
    ):

        for row in chunk.itertuples(index=False):

            processed += 1

            eid = row.entity_id

            # ------------------------------------------------
            # We only need detailed work for IDs that are
            # actually GT matches of our S1 sample.
            # ------------------------------------------------

            is_gt = eid in gt_match_ids

            # Fast path for non-GT rows:
            # We don't need to calculate all expensive features.
            if not is_gt:
                continue

            local["gt_links"] += 1

            name = normalize_text(row.business_name)
            address = normalize_text(row.business_address)
            country = normalize_country(row.country)

            # ------------------------------------------------
            # Find the S1 entities whose GT contains this ID.
            #
            # We build this reverse mapping only for the
            # sampled GT, not the entire dataset.
            # ------------------------------------------------

            possible_s1 = gt_reverse.get(eid, [])

            # ------------------------------------------------
            # Country consistency
            # ------------------------------------------------

            for sid in possible_s1:

                s1data = s1_rows[sid]

                if (
                    s1data["country"]
                    and country
                    and s1data["country"] == country
                ):
                    local["country_consistent"] += 1
                else:
                    local["country_inconsistent"] += 1

            # ------------------------------------------------
            # Exact name
            # ------------------------------------------------

            name_candidates = (
                name_index.get(name, set())
                if name
                else set()
            )

            if name_candidates:
                local["exact_name"] += 1

            if any(
                eid in gt_sample.get(sid, [])
                for sid in name_candidates
            ):
                local["gt_exact_name"] += 1

            # ------------------------------------------------
            # Exact address
            # ------------------------------------------------

            address_candidates = (
                address_index.get(address, set())
                if address
                else set()
            )

            if address_candidates:
                local["exact_address"] += 1

            if any(
                eid in gt_sample.get(sid, [])
                for sid in address_candidates
            ):
                local["gt_exact_address"] += 1

            # ------------------------------------------------
            # Country + exact name
            # ------------------------------------------------

            country_name_candidates = (
                country_name_index.get(
                    (country, name),
                    set()
                )
                if country and name
                else set()
            )

            if country_name_candidates:
                local["country_exact_name"] += 1

            if any(
                eid in gt_sample.get(sid, [])
                for sid in country_name_candidates
            ):
                local["gt_country_exact_name"] += 1

            # ------------------------------------------------
            # Country + exact address
            # ------------------------------------------------

            country_address_candidates = (
                country_address_index.get(
                    (country, address),
                    set()
                )
                if country and address
                else set()
            )

            if country_address_candidates:
                local["country_exact_address"] += 1

            if any(
                eid in gt_sample.get(sid, [])
                for sid in country_address_candidates
            ):
                local["gt_country_exact_address"] += 1

            # ------------------------------------------------
            # Address number + token rescue
            # ------------------------------------------------

            source_numbers = extract_numbers(address)
            source_tokens = token_set(address)

            number_candidates = set()

            for num in source_numbers:

                if num not in country_number_index:
                    continue

                possible = country_number_index[
                    (country, num)
                ]

                number_candidates.update(possible)

            if number_candidates:
                local["number_token"] += 1

            # Require:
            # 1. same country
            # 2. shared address number
            # 3. shared address token

            for sid in number_candidates:

                s1data = s1_rows[sid]

                if not (
                    source_numbers
                    & s1data["numbers"]
                ):
                    continue

                if not (
                    source_tokens
                    & s1data["tokens"]
                ):
                    continue

                if eid in gt_sample.get(sid, []):
                    local["gt_number_token"] += 1
                    break

        # ----------------------------------------------------
        # Progress report
        # ----------------------------------------------------

        if processed - last_report >= 1_000_000:

            elapsed = time.time() - START_TIME

            print(
                source_name,
                "| processed:",
                f"{processed:,}",
                "| GT rows:",
                f"{local['gt_links']:,}",
                "| elapsed:",
                f"{elapsed / 60:.1f} min"
            )

            last_report = processed

        # Explicit cleanup after each chunk.
        del chunk
        gc.collect()

    print()
    print(
        source_name,
        "COMPLETE:",
        f"{processed:,}",
        "rows"
    )

    return processed, local


# ============================================================
# 9. BUILD GT REVERSE INDEX
# ============================================================

print("=" * 80)
print("BUILDING SAMPLE GT REVERSE INDEX")
print("=" * 80)

gt_reverse = defaultdict(list)

for sid, matches in gt_sample.items():
    for eid in matches:
        gt_reverse[eid].append(sid)

print(
    "GT IDs with reverse links:",
    f"{len(gt_reverse):,}"
)

print()


# ============================================================
# 10. PROCESS S2
# ============================================================

rows2, result2 = process_source(
    S2_PATH,
    "SOURCE 2"
)

gc.collect()


# ============================================================
# 11. PROCESS S3
# ============================================================

rows3, result3 = process_source(
    S3_PATH,
    "SOURCE 3"
)

gc.collect()


# ============================================================
# 12. COMBINE RESULTS
# ============================================================

print()
print("=" * 80)
print("STEP 12 — COMBINING RESULTS")
print("=" * 80)

combined = {}

for key in result2:

    combined[key] = (
        result2.get(key, 0)
        +
        result3.get(key, 0)
    )

combined["rows_s2"] = rows2
combined["rows_s3"] = rows3
combined["sample_s1"] = len(s1_rows)
combined["sample_gt_entities"] = len(gt_sample)
combined["gt_unique_match_ids"] = len(gt_match_ids)


# ============================================================
# 13. CALCULATE RECALL METRICS
# ============================================================

print()
print("=" * 80)
print("STEP 13 — CALCULATING BLOCKING RECALL")
print("=" * 80)

total_links = combined["gt_links"]

print("Total GT links in sample:", f"{total_links:,}")
print()

if total_links > 0:

    metrics = {

        "exact_name_recall":
            combined["gt_exact_name"] / total_links,

        "exact_address_recall":
            combined["gt_exact_address"] / total_links,

        "country_exact_name_recall":
            combined["gt_country_exact_name"] / total_links,

        "country_exact_address_recall":
            combined["gt_country_exact_address"] / total_links,

        "address_number_token_recall":
            combined["gt_number_token"] / total_links,
    }

else:
    metrics = {}

for name, value in metrics.items():

    print(
        f"{name:35s}: "
        f"{value * 100:7.3f}%"
    )

print()


# ============================================================
# 14. COUNTRY CONSISTENCY
# ============================================================

print("=" * 80)
print("STEP 14 — COUNTRY CONSISTENCY OF ACTUAL GT")
print("=" * 80)

country_total = (
    combined["country_consistent"]
    +
    combined["country_inconsistent"]
)

if country_total:

    consistency = (
        combined["country_consistent"]
        / country_total
    )

    inconsistency = (
        combined["country_inconsistent"]
        / country_total
    )

    print(
        "Country-consistent GT links:",
        f"{combined['country_consistent']:,}",
        f"({consistency * 100:.4f}%)"
    )

    print(
        "Cross-country GT links:",
        f"{combined['country_inconsistent']:,}",
        f"({inconsistency * 100:.4f}%)"
    )

else:

    consistency = None
    inconsistency = None

print()


# ============================================================
# 15. ESTIMATE BENEFIT OF COUNTRY BLOCKING
# ============================================================

print("=" * 80)
print("STEP 15 — COUNTRY BLOCKING INTERPRETATION")
print("=" * 80)

if consistency is not None:

    if consistency >= 0.999:

        country_conclusion = (
            "VERY STRONG EVIDENCE: sampled GT matches are "
            "country-consistent. Country-aware blocking is "
            "strongly justified for the next experiment."
        )

    elif consistency >= 0.99:

        country_conclusion = (
            "STRONG EVIDENCE: country-aware blocking should "
            "be investigated seriously."
        )

    elif consistency >= 0.95:

        country_conclusion = (
            "COUNTRY IS USEFUL but not perfectly strict. "
            "Use country as a strong feature/block, not an "
            "absolute exclusion without further analysis."
        )

    else:

        country_conclusion = (
            "CAUTION: some GT matches cross countries. "
            "Do NOT make country a hard blocker yet."
        )

else:

    country_conclusion = "Insufficient GT links."

print(country_conclusion)
print()


# ============================================================
# 16. ADDRESS-NUMBER INTERPRETATION
# ============================================================

print("=" * 80)
print("STEP 16 — ADDRESS NUMBER RESCUE")
print("=" * 80)

number_recall = metrics.get(
    "address_number_token_recall",
    0
)

address_recall = metrics.get(
    "country_exact_address_recall",
    0
)

print(
    "Country + exact address recall:",
    f"{address_recall * 100:.3f}%"
)

print(
    "Country + number + token recall:",
    f"{number_recall * 100:.3f}%"
)

if number_recall > address_recall:

    number_conclusion = (
        "Address-number + token blocking recovers additional "
        "GT links beyond exact country+address."
    )

else:

    number_conclusion = (
        "Address-number + token blocking does not show a "
        "recall advantage over exact country+address in this sample."
    )

print(number_conclusion)
print()


# ============================================================
# 17. SAVE REPORT
# ============================================================

print("=" * 80)
print("STEP 17 — SAVING AUDIT RESULTS")
print("=" * 80)

report_lines = []

report_lines.append(
    "AMAZON ML CHALLENGE 2026 — TRAINING AUDIT"
)

report_lines.append("=" * 70)

report_lines.append(
    f"Sample S1: {len(s1_rows):,}"
)

report_lines.append(
    f"GT entities: {len(gt_sample):,}"
)

report_lines.append(
    f"S2 rows scanned: {rows2:,}"
)

report_lines.append(
    f"S3 rows scanned: {rows3:,}"
)

report_lines.append("")

report_lines.append(
    "TRUE MATCH CARDINALITY"
)

for k in sorted(gt_cardinality):

    count = gt_cardinality[k]

    pct = (
        100 * count / total_gt_entities
        if total_gt_entities
        else 0
    )

    report_lines.append(
        f"{k} matches: {count:,} ({pct:.3f}%)"
    )

report_lines.append("")

report_lines.append(
    "BLOCKING RECALL"
)

for name, value in metrics.items():

    report_lines.append(
        f"{name}: {value * 100:.4f}%"
    )

report_lines.append("")

report_lines.append(
    "COUNTRY CONSISTENCY"
)

if consistency is not None:

    report_lines.append(
        f"Country-consistent: {consistency * 100:.4f}%"
    )

    report_lines.append(
        f"Cross-country: {inconsistency * 100:.4f}%"
    )

report_lines.append("")

report_lines.append(
    "COUNTRY CONCLUSION"
)

report_lines.append(
    country_conclusion
)

report_lines.append("")

report_lines.append(
    "ADDRESS NUMBER CONCLUSION"
)

report_lines.append(
    number_conclusion
)

report_lines.append("")

elapsed = time.time() - START_TIME

report_lines.append(
    f"Runtime: {elapsed / 60:.2f} minutes"
)

with open(
    REPORT_FILE,
    "w",
    encoding="utf-8"
) as f:

    f.write(
        "\n".join(report_lines)
    )


# ------------------------------------------------------------
# JSON
# ------------------------------------------------------------

json_data = {

    "sample_s1": len(s1_rows),

    "sample_gt_entities":
        len(gt_sample),

    "rows_s2":
        rows2,

    "rows_s3":
        rows3,

    "gt_cardinality":
        {
            str(k): int(v)
            for k, v in gt_cardinality.items()
        },

    "metrics":
        {
            k: float(v)
            for k, v in metrics.items()
        },

    "country_consistent":
        int(combined["country_consistent"]),

    "country_inconsistent":
        int(combined["country_inconsistent"]),

    "country_consistency":
        None
        if consistency is None
        else float(consistency),

    "country_conclusion":
        country_conclusion,

    "number_conclusion":
        number_conclusion,

    "runtime_minutes":
        float((time.time() - START_TIME) / 60)
}

with open(
    JSON_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        json_data,
        f,
        indent=2
    )


# ============================================================
# 18. FINAL SUMMARY
# ============================================================

print()
print("=" * 80)
print("✅ TRAINING AUDIT COMPLETE")
print("=" * 80)

print(
    "Sample S1:",
    f"{len(s1_rows):,}"
)

print(
    "S2 scanned:",
    f"{rows2:,}"
)

print(
    "S3 scanned:",
    f"{rows3:,}"
)

print()

print("GT CARDINALITY:")

for k in sorted(gt_cardinality):

    print(
        f"  {k} matches:",
        f"{gt_cardinality[k]:,}"
    )

print()

print("RECALL:")

for name, value in metrics.items():

    print(
        f"  {name}:",
        f"{value * 100:.3f}%"
    )

print()

print(
    "COUNTRY CONSISTENCY:",
    f"{consistency * 100:.3f}%"
    if consistency is not None
    else "N/A"
)

print()

print("COUNTRY CONCLUSION:")
print(country_conclusion)

print()

print("ADDRESS NUMBER:")
print(number_conclusion)

print()

print("REPORT SAVED:")
print(REPORT_FILE)

print()
print("JSON SAVED:")
print(JSON_FILE)

print()

print(
    "Total runtime:",
    f"{(time.time() - START_TIME) / 60:.2f} minutes"
)

print()
print("=" * 80)
print("DO NOT SUBMIT ANYTHING FROM THIS CELL.")
print("This cell is analysis only.")
print("=" * 80)

# Final cleanup.
gc.collect()

================================================================================
AMAZON ML CHALLENGE 2026
RAM-SAFE TRAINING AUDIT
================================================================================
Drive root: /content/drive/MyDrive/Amazon-ML-Challenge-2026
Sample S1: 50,000
Chunk size: 100,000
Output: /content/drive/MyDrive/Amazon-ML-Challenge-2026/ML_AUDIT/Submission_A_Planning

================================================================================
STEP 1 — LOCATING TRAINING DATA
================================================================================
MISSING: train_ground_truth.tsv
MISSING: train_source1.tsv
MISSING: train_source2.tsv
MISSING: train_source3.tsv

================================================================================
TRAINING DATA NOT AVAILABLE ON DRIVE
================================================================================
Missing:
 - train_source1.tsv
 - train_source2.tsv
 - train_source3.tsv
 - train_ground_truth.tsv

STOPPING SAFELY. No large data was loaded and no submission was changed.

SystemExit:

/usr/local/lib/python3.13/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
import os

zip_path = "/content/6ab10eb3b23ba_student_resource.zip"

print("ZIP exists:", os.path.exists(zip_path))

if os.path.exists(zip_path):
    size_gb = os.path.getsize(zip_path) / (1024**3)
    print(f"ZIP size: {size_gb:.2f} GB")
else:
    print("❌ ZIP not found. Check the uploaded filename.")

ZIP exists: True
ZIP size: 0.76 GB

In [ ]:
import os
import zipfile
import time

ZIP_PATH = "/content/6ab10eb3b23ba_student_resource.zip"
EXTRACT_PATH = "/content/amazon_ml_challenge"

os.makedirs(EXTRACT_PATH, exist_ok=True)

print("Extracting dataset...")
start = time.time()

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extractall(EXTRACT_PATH)

print(f"\n✅ Extraction complete in {(time.time()-start)/60:.2f} minutes")

print("\nTop-level contents:")
for x in os.listdir(EXTRACT_PATH):
    print(" -", x)

Extracting dataset...

✅ Extraction complete in 0.67 minutes

Top-level contents:
 - __MACOSX
 - student_resource

In [ ]:
import os

DATASET = "/content/amazon_ml_challenge/student_resource/dataset"

print("DATASET EXISTS:", os.path.exists(DATASET))
print()

for split in ["train", "test"]:
    folder = os.path.join(DATASET, split)

    print(f"========== {split.upper()} ==========")

    if not os.path.exists(folder):
        print("❌ Folder missing:", folder)
        continue

    for fname in sorted(os.listdir(folder)):
        path = os.path.join(folder, fname)

        if os.path.isfile(path):
            size_mb = os.path.getsize(path) / (1024**2)
            print(f"{fname:30s} {size_mb:10.1f} MB")

    print()

DATASET EXISTS: True

========== TRAIN ==========
train_ground_truth.tsv              121.1 MB
train_source1.tsv                   200.3 MB
train_source2.tsv                   466.6 MB
train_source3.tsv                   480.4 MB

========== TEST ==========
test_source1.tsv                    166.9 MB
test_source2.tsv                    485.9 MB
test_source3.tsv                    482.6 MB

In [ ]:
import os
import pandas as pd
from collections import Counter

DATASET = "/content/amazon_ml_challenge/student_resource/dataset"

TRAIN_S1 = os.path.join(DATASET, "train", "train_source1.tsv")
TEST_S1  = os.path.join(DATASET, "test", "test_source1.tsv")
GT_PATH  = os.path.join(DATASET, "train", "train_ground_truth.tsv")

print("=" * 80)
print("STEP 5 — COUNTRY / FRANCE CHECK")
print("=" * 80)

# ------------------------------------------------------------
# 1. CHECK SCHEMA WITHOUT LOADING WHOLE FILE
# ------------------------------------------------------------

print("\nTRAIN S1 columns:")
train_head = pd.read_csv(
    TRAIN_S1,
    sep="\t",
    dtype=str,
    nrows=3,
    keep_default_na=False
)
print(train_head.columns.tolist())

print("\nTEST S1 columns:")
test_head = pd.read_csv(
    TEST_S1,
    sep="\t",
    dtype=str,
    nrows=3,
    keep_default_na=False
)
print(test_head.columns.tolist())

print("\nGROUND TRUTH columns:")
gt_head = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str,
    nrows=5,
    keep_default_na=False
)
print(gt_head.columns.tolist())

print("\nGround truth sample:")
print(gt_head.to_string(index=False))

del train_head, test_head, gt_head
import gc
gc.collect()


# ------------------------------------------------------------
# 2. TRAIN S1 COUNTRY DISTRIBUTION
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("TRAIN S1 COUNTRY DISTRIBUTION")
print("=" * 80)

train_country = Counter()
train_rows = 0

for chunk in pd.read_csv(
    TRAIN_S1,
    sep="\t",
    dtype={"country": "string"},
    usecols=["country"],
    chunksize=200_000,
    keep_default_na=False
):
    train_rows += len(chunk)

    for c in chunk["country"]:
        c = str(c).strip().lower()
        train_country[c] += 1

    del chunk

print("Training S1 rows:", f"{train_rows:,}")

for country, count in train_country.most_common():
    print(
        f"{country!r:20s} "
        f"{count:>10,} "
        f"({100*count/train_rows:6.2f}%)"
    )


# ------------------------------------------------------------
# 3. TEST S1 COUNTRY DISTRIBUTION
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("TEST S1 COUNTRY DISTRIBUTION")
print("=" * 80)

test_country = Counter()
test_rows = 0

for chunk in pd.read_csv(
    TEST_S1,
    sep="\t",
    dtype={"country": "string"},
    usecols=["country"],
    chunksize=200_000,
    keep_default_na=False
):
    test_rows += len(chunk)

    for c in chunk["country"]:
        c = str(c).strip().lower()
        test_country[c] += 1

    del chunk

print("Test S1 rows:", f"{test_rows:,}")

for country, count in test_country.most_common():
    print(
        f"{country!r:20s} "
        f"{count:>10,} "
        f"({100*count/test_rows:6.2f}%)"
    )


# ------------------------------------------------------------
# 4. FRANCE CHECK
# ------------------------------------------------------------

train_france = train_country.get("france", 0)
test_france = test_country.get("france", 0)

print("\n" + "=" * 80)
print("🇫🇷 FRANCE RESULT")
print("=" * 80)

print("France in TRAIN S1:", f"{train_france:,}")
print("France in TEST S1 :", f"{test_france:,}")

if train_france == 0 and test_france > 0:
    print("\n✅ CONFIRMED: France is unseen in TRAIN and present in TEST.")

elif train_france > 0:
    print("\n⚠️ France exists in training — this differs from the challenge description.")

else:
    print("\n⚠️ France was not found in test S1.")


# ------------------------------------------------------------
# 5. MEMORY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("RAM-SAFE CHECK COMPLETE")
print("=" * 80)

gc.collect()

================================================================================
STEP 5 — COUNTRY / FRANCE CHECK
================================================================================

TRAIN S1 columns:
['entity_id', 'business_name', 'business_address', 'country']

TEST S1 columns:
['entity_id', 'business_name', 'business_address', 'country']

GROUND TRUTH columns:
['source1_entity_id', 'matched_entity_ids']

Ground truth sample:
source1_entity_id                                                            matched_entity_ids
        S1-965667               S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
      S1-55344266                           S2-249013014,S2-197070651,S3-478195123,S3-384364074
     S1-343815751                                        S2-790675320,S2-479876582,S3-878454467
     S1-656753428                                         S2-153058913,S2-24659151,S3-679606215
     S1-102811957 S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785

================================================================================
TRAIN S1 COUNTRY DISTRIBUTION
================================================================================
Training S1 rows: 2,206,821
'us'                  1,323,633 ( 59.98%)
'india'                 883,188 ( 40.02%)

================================================================================
TEST S1 COUNTRY DISTRIBUTION
================================================================================
Test S1 rows: 1,732,544
'india'                 809,986 ( 46.75%)
'us'                    663,106 ( 38.27%)
'france'                259,452 ( 14.98%)

================================================================================
🇫🇷 FRANCE RESULT
================================================================================
France in TRAIN S1: 0
France in TEST S1 : 259,452

✅ CONFIRMED: France is unseen in TRAIN and present in TEST.

================================================================================
RAM-SAFE CHECK COMPLETE
================================================================================

0

In [ ]:
# ============================================================
# STEP 6 — TRAINING GT COUNTRY CONSISTENCY
# RAM-SAFE SAMPLED VALIDATION
# ============================================================

import os
import gc
import random
import pandas as pd
from collections import defaultdict

DATASET = "/content/amazon_ml_challenge/student_resource/dataset"

S1_PATH = os.path.join(DATASET, "train", "train_source1.tsv")
S2_PATH = os.path.join(DATASET, "train", "train_source2.tsv")
S3_PATH = os.path.join(DATASET, "train", "train_source3.tsv")
GT_PATH = os.path.join(DATASET, "train", "train_ground_truth.tsv")

SAMPLE_S1 = 50_000
CHUNK_SIZE = 200_000
SEED = 42

print("=" * 80)
print("STEP 6 — TRAINING GT COUNTRY CONSISTENCY")
print("=" * 80)

# ------------------------------------------------------------
# 1. SAMPLE S1 IDs + COUNTRY
# ------------------------------------------------------------

print("\n[1/4] Reading S1 countries...")

s1_sample = pd.read_csv(
    S1_PATH,
    sep="\t",
    dtype=str,
    usecols=["entity_id", "country"],
    keep_default_na=False
)

random.seed(SEED)

if len(s1_sample) > SAMPLE_S1:
    s1_sample = s1_sample.sample(
        n=SAMPLE_S1,
        random_state=SEED
    ).reset_index(drop=True)

s1_country = {}

for row in s1_sample.itertuples(index=False):
    s1_country[row.entity_id] = str(row.country).strip().lower()

sample_ids = set(s1_country.keys())

print("Sampled S1:", f"{len(sample_ids):,}")

del s1_sample
gc.collect()


# ------------------------------------------------------------
# 2. GET GT MATCHES FOR SAMPLED S1
# ------------------------------------------------------------

print("\n[2/4] Reading GT for sampled S1...")

# matched_id -> expected S1 country
expected_country = {}

# Keep some entity-level information too.
gt_by_s1 = defaultdict(list)

rows_scanned = 0

for chunk in pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=CHUNK_SIZE
):

    rows_scanned += len(chunk)

    for row in chunk.itertuples(index=False):

        sid = row.source1_entity_id

        if sid not in sample_ids:
            continue

        value = row.matched_entity_ids.strip()

        if not value:
            continue

        country = s1_country[sid]

        for mid in value.split(","):

            mid = mid.strip()

            if not mid:
                continue

            gt_by_s1[sid].append(mid)

            # Same source entity should normally have
            # one expected country. If duplicate GT IDs
            # appear, we retain the first observed country.
            if mid not in expected_country:
                expected_country[mid] = country

print(
    "GT rows scanned:",
    f"{rows_scanned:,}"
)

print(
    "Unique matched S2/S3 IDs in sample:",
    f"{len(expected_country):,}"
)

total_gt_links = sum(
    len(v) for v in gt_by_s1.values()
)

print(
    "Total GT links in sample:",
    f"{total_gt_links:,}"
)

del chunk
gc.collect()


# ------------------------------------------------------------
# 3. LOOK UP COUNTRIES IN S2/S3
# ------------------------------------------------------------

print("\n[3/4] Scanning S2 + S3 for those matched IDs...")
print("Only GT-relevant IDs are inspected.")

same_country = 0
different_country = 0
not_found = 0

# Keep examples of any cross-country links.
cross_country_examples = []

def inspect_source(path, source_name):

    global same_country
    global different_country
    global not_found
    global cross_country_examples

    found_ids = set()

    processed = 0
    relevant = 0

    print("\n---", source_name, "---")

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        usecols=["entity_id", "country"],
        keep_default_na=False,
        chunksize=CHUNK_SIZE
    ):

        processed += len(chunk)

        # IMPORTANT:
        # Filter before doing any Python-level work.
        mask = chunk["entity_id"].isin(expected_country)

        relevant_chunk = chunk.loc[
            mask,
            ["entity_id", "country"]
        ]

        relevant += len(relevant_chunk)

        for row in relevant_chunk.itertuples(index=False):

            mid = row.entity_id
            actual_country = str(row.country).strip().lower()
            expected = expected_country[mid]

            found_ids.add(mid)

            if actual_country == expected:
                same_country += 1
            else:
                different_country += 1

                if len(cross_country_examples) < 20:
                    cross_country_examples.append({
                        "source": source_name,
                        "matched_id": mid,
                        "expected_country": expected,
                        "actual_country": actual_country
                    })

        if processed % 1_000_000 == 0:
            print(
                "Processed:",
                f"{processed:,}",
                "| relevant:",
                f"{relevant:,}"
            )

        del relevant_chunk
        del chunk
        gc.collect()

    print(
        source_name,
        "complete:",
        f"{processed:,}",
        "rows | relevant:",
        f"{relevant:,}"
    )

    return found_ids


found_s2 = inspect_source(
    S2_PATH,
    "S2"
)

gc.collect()

found_s3 = inspect_source(
    S3_PATH,
    "S3"
)

gc.collect()


# ------------------------------------------------------------
# 4. FINAL REPORT
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STEP 6 RESULT")
print("=" * 80)

found_total = len(found_s2) + len(found_s3)

print(
    "Expected matched IDs:",
    f"{len(expected_country):,}"
)

print(
    "S2 matched IDs found:",
    f"{len(found_s2):,}"
)

print(
    "S3 matched IDs found:",
    f"{len(found_s3):,}"
)

print()

print(
    "Same-country GT links:",
    f"{same_country:,}"
)

print(
    "Cross-country GT links:",
    f"{different_country:,}"
)

print(
    "Country mismatches not observed:",
    "N/A"
)

checked = same_country + different_country

if checked:
    print(
        "\nSame-country percentage:",
        f"{100 * same_country / checked:.4f}%"
    )

    print(
        "Cross-country percentage:",
        f"{100 * different_country / checked:.4f}%"
    )

print("\nCross-country examples:")

if cross_country_examples:
    for x in cross_country_examples:
        print(x)
else:
    print("NONE FOUND IN SAMPLE")

print("\n" + "=" * 80)
print("RAM-SAFE COUNTRY VALIDATION COMPLETE")
print("=" * 80)

gc.collect()

================================================================================
STEP 6 — TRAINING GT COUNTRY CONSISTENCY
================================================================================

[1/4] Reading S1 countries...
Sampled S1: 50,000

[2/4] Reading GT for sampled S1...
GT rows scanned: 2,206,821
Unique matched S2/S3 IDs in sample: 172,636
Total GT links in sample: 172,636

[3/4] Scanning S2 + S3 for those matched IDs...
Only GT-relevant IDs are inspected.

--- S2 ---
Processed: 1,000,000 | relevant: 16,603
Processed: 2,000,000 | relevant: 33,201
Processed: 3,000,000 | relevant: 49,844
Processed: 4,000,000 | relevant: 66,302
Processed: 5,000,000 | relevant: 82,768
S2 complete: 5,034,616 rows | relevant: 83,407

--- S3 ---
Processed: 1,000,000 | relevant: 16,830
Processed: 2,000,000 | relevant: 33,844
Processed: 3,000,000 | relevant: 50,626
Processed: 4,000,000 | relevant: 67,610
Processed: 5,000,000 | relevant: 84,434
S3 complete: 5,285,603 rows | relevant: 89,229

================================================================================
STEP 6 RESULT
================================================================================
Expected matched IDs: 172,636
S2 matched IDs found: 83,407
S3 matched IDs found: 89,229

Same-country GT links: 172,636
Cross-country GT links: 0
Country mismatches not observed: N/A

Same-country percentage: 100.0000%
Cross-country percentage: 0.0000%

Cross-country examples:
NONE FOUND IN SAMPLE

================================================================================
RAM-SAFE COUNTRY VALIDATION COMPLETE
================================================================================

0

In [ ]:
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print("=" * 80)
print("SEARCHING SAVED RESULT FILES")
print("=" * 80)

targets = [
    "matching_results.tsv",
    "matching_results_v1plus_v5single.tsv",
    "matching_results_v5.tsv",
    "matching_results_s3.tsv",
    "matching_results_s2.tsv",
]

for root, dirs, files in os.walk(ROOT):
    for f in files:
        if f in targets:
            path = os.path.join(root, f)
            size_mb = os.path.getsize(path) / (1024**2)
            print(f"{size_mb:8.1f} MB  |  {path}")

print("\nSearch complete.")

================================================================================
SEARCHING SAVED RESULT FILES
================================================================================

Search complete.

In [ ]:
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print("ROOT EXISTS:", os.path.exists(ROOT))
print()

if os.path.exists(ROOT):
    print("Contents of Amazon-ML-Challenge-2026:")
    for name in os.listdir(ROOT):
        path = os.path.join(ROOT, name)

        if os.path.isdir(path):
            print(f"[DIR]  {name}")
        else:
            size_mb = os.path.getsize(path) / (1024**2)
            print(f"[FILE] {name}  ({size_mb:.1f} MB)")

ROOT EXISTS: False

In [ ]:
from google.colab import drive
import os

drive.mount("/content/drive")

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print("\nDrive mounted:", os.path.exists("/content/drive/MyDrive"))
print("Challenge folder exists:", os.path.exists(ROOT))

Mounted at /content/drive

Drive mounted: True
Challenge folder exists: True

In [ ]:
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print("=" * 80)
print("SAVED AMAZON ML ASSETS")
print("=" * 80)

for name in sorted(os.listdir(ROOT)):
    path = os.path.join(ROOT, name)

    if os.path.isdir(path):
        print(f"[DIR]  {name}")
    else:
        size_mb = os.path.getsize(path) / (1024**2)
        print(f"[FILE] {name}  ({size_mb:.1f} MB)")

================================================================================
SAVED AMAZON ML ASSETS
================================================================================
[DIR]  ML_AUDIT
[DIR]  data
[DIR]  ml
[DIR]  notebooks

In [ ]:
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

for folder in ["ml", "data", "notebooks", "ML_AUDIT"]:
    base = os.path.join(ROOT, folder)

    print("\n" + "=" * 80)
    print(folder.upper())
    print("=" * 80)

    for root, dirs, files in os.walk(base):
        level = root.replace(base, "").count(os.sep)

        # Don't print excessively deep directory trees
        if level > 3:
            dirs[:] = []

        for f in sorted(files):
            path = os.path.join(root, f)
            size_mb = os.path.getsize(path) / (1024**2)

            print(
                f"{size_mb:8.1f} MB | "
                f"{os.path.relpath(path, ROOT)}"
            )

================================================================================
ML
================================================================================
     5.2 MB | ml/V5_ML_Final-20260925T182640Z-1-001.zip
     0.8 MB | ml/catboost_v1_v3_1000.cbm
    31.1 MB | ml/ml_features_v3_1000.pkl
     0.0 MB | ml/V5_ML_Final/V5_ML_Final/V5_final_report.txt
    31.1 MB | ml/V5_ML_Final/V5_ML_Final/ml_features_v3_1000.pkl
     0.0 MB | ml/V5_ML_Final/V5_ML_Final/v5_feature_list.txt
     0.0 MB | ml/V5_ML_Final/V5_ML_Final/v5_inference.py
     1.4 MB | ml/V5_ML_Final/V5_ML_Final/v5_model.cbm
     0.0 MB | ml/V5_ML_Final/V5_ML_Final/v5_threshold_predictions.csv
    16.5 MB | ml/V5_full_indexes/s2_addr_freq.pkl
   196.7 MB | ml/V5_full_indexes/s2_addr_index.pkl
    12.7 MB | ml/V5_full_indexes/s2_name_freq.pkl
    96.4 MB | ml/V5_full_indexes/s2_name_index.pkl
    16.0 MB | ml/V5_full_indexes/s3_addr_freq.pkl
   196.1 MB | ml/V5_full_indexes/s3_addr_index.pkl
    13.6 MB | ml/V5_full_indexes/s3_name_freq.pkl
   100.9 MB | ml/V5_full_indexes/s3_name_index.pkl
    53.4 MB | ml/V5_Final_Inference/candidate_pairs_v5.tsv
     0.0 MB | ml/V5_Final_Inference/checkpoint.txt
    18.8 MB | ml/V5_Final_Inference/matching_results_v5.tsv
   172.5 MB | ml/V5_Final_Production/s2_candidates.tsv
    37.7 MB | ml/V5_Final_Production/s2_results.tsv
    69.6 MB | ml/V5_Final_Production/s3_candidates.tsv
    17.0 MB | ml/V5_Final_Production/s3_results.tsv
   113.1 MB | ml/V5_Final_Production_RAMSAFE/s2_results.tsv
   110.6 MB | ml/V5_Final_Production_RAMSAFE/s3_results.tsv
    43.3 MB | ml/V1_1_REPRODUCTION/candidate_pairs.tsv
    43.3 MB | ml/V1_1_REPRODUCTION/matching_results.tsv
     0.2 MB | ml/V5_Final_Validation/v51_validation_s2_candidates.tsv
    91.3 MB | ml/V5_SUBMISSION/candidate_pairs_s2.tsv
    41.5 MB | ml/V5_SUBMISSION/matching_results_s2.tsv

================================================================================
DATA
================================================================================
  1044.1 MB | data/6ab10eb3b23ba_student_resource.zip

================================================================================
NOTEBOOKS
================================================================================
     2.5 MB | notebooks/Amazon_ML_Challenge_2026.ipynb

================================================================================
ML_AUDIT
================================================================================
     0.0 MB | ML_AUDIT/Submission_A_Planning/training_country_number_audit.txt

In [ ]:
import os
import subprocess

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

files = [
    "ml/V1_1_REPRODUCTION/matching_results.tsv",
    "ml/V5_SUBMISSION/matching_results.tsv",
    "ml/V5_SUBMISSION/matching_results_s2.tsv",
    "ml/V5_SUBMISSION/matching_results_s3.tsv",
    "ml/V5_Final_Inference/matching_results_v5.tsv",
]

print("=" * 100)
print("IDENTIFYING SAVED PREDICTION FILES")
print("=" * 100)

for rel in files:

    path = os.path.join(ROOT, rel)

    print("\n" + "-" * 100)
    print(rel)

    if not os.path.exists(path):
        print("MISSING")
        continue

    size_mb = os.path.getsize(path) / (1024**2)
    print(f"Size: {size_mb:.2f} MB")

    # Count lines without loading the file.
    result = subprocess.run(
        ["wc", "-l", path],
        capture_output=True,
        text=True
    )

    print("Lines:", result.stdout.strip().split()[0])

    print("First 3 lines:")
    with open(path, "r", encoding="utf-8") as f:
        for _ in range(3):
            line = f.readline()
            if not line:
                break
            print(line.rstrip()[:500])

====================================================================================================
IDENTIFYING SAVED PREDICTION FILES
====================================================================================================

----------------------------------------------------------------------------------------------------
ml/V1_1_REPRODUCTION/matching_results.tsv
Size: 43.27 MB
Lines: 1732545
First 3 lines:
source1_entity_id	matched_entity_ids
S1-714132312
S1-106407869

----------------------------------------------------------------------------------------------------
ml/V5_SUBMISSION/matching_results.tsv
MISSING

----------------------------------------------------------------------------------------------------
ml/V5_SUBMISSION/matching_results_s2.tsv
Size: 41.52 MB
Lines: 1732545
First 3 lines:
source1_entity_id	matched_entity_ids
S1-714132312	S2-786029403,S2-435263846
S1-106407869

----------------------------------------------------------------------------------------------------
ml/V5_SUBMISSION/matching_results_s3.tsv
MISSING

----------------------------------------------------------------------------------------------------
ml/V5_Final_Inference/matching_results_v5.tsv
Size: 18.79 MB
Lines: 632001
First 3 lines:
source1_entity_id	matched_entity_ids
S1-714132312	S3-867809779,S3-625880872
S1-106407869

In [ ]:
import csv
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

V1_PATH = os.path.join(ROOT, "ml/V1_1_REPRODUCTION/matching_results.tsv")
V5S2_PATH = os.path.join(ROOT, "ml/V5_SUBMISSION/matching_results_s2.tsv")

v1_nonempty = 0
v5_nonempty = 0
v5_singletons = 0
v1_empty_v5_singleton = 0
v1_nonempty_v5_singleton = 0
both_empty = 0
both_nonempty = 0
v5_multi = 0

with open(V1_PATH, "r", encoding="utf-8", newline="") as f1, \
     open(V5S2_PATH, "r", encoding="utf-8", newline="") as f2:

    r1 = csv.DictReader(f1, delimiter="\t")
    r2 = csv.DictReader(f2, delimiter="\t")

    for row1, row2 in zip(r1, r2):

        m1 = row1["matched_entity_ids"].strip()
        m5 = row2["matched_entity_ids"].strip()

        n1 = len(m1.split(",")) if m1 else 0
        n5 = len(m5.split(",")) if m5 else 0

        if n1 > 0:
            v1_nonempty += 1

        if n5 > 0:
            v5_nonempty += 1

        if n5 == 1:
            v5_singletons += 1

            if n1 == 0:
                v1_empty_v5_singleton += 1
            else:
                v1_nonempty_v5_singleton += 1

        if n5 > 1:
            v5_multi += 1

        if n1 == 0 and n5 == 0:
            both_empty += 1

        if n1 > 0 and n5 > 0:
            both_nonempty += 1

print("=" * 80)
print("V1.1 vs V5-S2")
print("=" * 80)

print(f"V1.1 non-empty                 : {v1_nonempty:,}")
print(f"V5-S2 non-empty                : {v5_nonempty:,}")
print(f"V5-S2 singleton                : {v5_singletons:,}")
print(f"V5-S2 multi-match              : {v5_multi:,}")
print(f"V1 empty + V5 singleton        : {v1_empty_v5_singleton:,}")
print(f"V1 non-empty + V5 singleton    : {v1_nonempty_v5_singleton:,}")
print(f"Both empty                      : {both_empty:,}")
print(f"Both non-empty                  : {both_nonempty:,}")

================================================================================
V1.1 vs V5-S2
================================================================================
V1.1 non-empty                 : 912,910
V5-S2 non-empty                : 739,405
V5-S2 singleton                : 283,386
V5-S2 multi-match              : 456,019
V1 empty + V5 singleton        : 130,047
V1 non-empty + V5 singleton    : 153,339
Both empty                      : 525,502
Both non-empty                  : 445,273

In [ ]:
import os
import subprocess

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

files = [
    "ml/V5_Final_Production_RAMSAFE/s2_results.tsv",
    "ml/V5_Final_Production_RAMSAFE/s3_results.tsv",
    "ml/V5_Final_Production/s2_results.tsv",
    "ml/V5_Final_Production/s3_results.tsv",
]

for rel in files:
    path = os.path.join(ROOT, rel)

    print("\n" + "=" * 100)
    print(rel)

    if not os.path.exists(path):
        print("MISSING")
        continue

    print(f"Size: {os.path.getsize(path)/(1024**2):.2f} MB")

    result = subprocess.run(
        ["wc", "-l", path],
        capture_output=True,
        text=True
    )
    print("Lines:", result.stdout.strip().split()[0])

    print("First 5 lines:")
    with open(path, "r", encoding="utf-8") as f:
        for _ in range(5):
            line = f.readline()
            if not line:
                break
            print(line.rstrip()[:1000])

====================================================================================================
ml/V5_Final_Production_RAMSAFE/s2_results.tsv
Size: 113.14 MB
Lines: 1732545
First 5 lines:
source1_entity_id	candidate_entity_ids	matched_entity_ids
S1-714132312	S2-786029403,S2-187020300,S2-637340732,S2-435263846	S2-786029403,S2-435263846
S1-106407869
S1-156285671	S2-285293738
S1-689823050	S2-212601842,S2-152111886	S2-212601842

====================================================================================================
ml/V5_Final_Production_RAMSAFE/s3_results.tsv
Size: 110.55 MB
Lines: 1732545
First 5 lines:
source1_entity_id	candidate_entity_ids	matched_entity_ids
S1-714132312	S3-625880872,S3-867809779	S3-625880872,S3-867809779
S1-106407869
S1-156285671	S3-290424417,S3-51004541,S3-133101125
S1-689823050

====================================================================================================
ml/V5_Final_Production/s2_results.tsv
Size: 37.68 MB
Lines: 1732544
First 5 lines:
S1-714132312
S1-106407869
S1-156285671
S1-689823050	S2-212601842
S1-921369899

====================================================================================================
ml/V5_Final_Production/s3_results.tsv
Size: 16.97 MB
Lines: 808000
First 5 lines:
S1-714132312	S3-867809779,S3-625880872
S1-106407869
S1-156285671
S1-689823050
S1-921369899

In [ ]:
import csv
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

V1_PATH = os.path.join(
    ROOT, "ml/V1_1_REPRODUCTION/matching_results.tsv"
)

S2_PATH = os.path.join(
    ROOT, "ml/V5_Final_Production_RAMSAFE/s2_results.tsv"
)

S3_PATH = os.path.join(
    ROOT, "ml/V5_Final_Production_RAMSAFE/s3_results.tsv"
)

v1_nonempty = 0
v5_combined_nonempty = 0
v5_combined_singleton = 0
v5_combined_multi = 0

v1_empty_v5_singleton = 0
v1_nonempty_v5_singleton = 0

v1_empty_v5_multi = 0

total = 0

with open(V1_PATH, "r", encoding="utf-8", newline="") as f1, \
     open(S2_PATH, "r", encoding="utf-8", newline="") as f2, \
     open(S3_PATH, "r", encoding="utf-8", newline="") as f3:

    r1 = csv.DictReader(f1, delimiter="\t")
    r2 = csv.DictReader(f2, delimiter="\t")
    r3 = csv.DictReader(f3, delimiter="\t")

    for row1, row2, row3 in zip(r1, r2, r3):

        total += 1

        m1 = row1["matched_entity_ids"].strip()
        m2 = row2["matched_entity_ids"].strip()
        m3 = row3["matched_entity_ids"].strip()

        n1 = len(m1.split(",")) if m1 else 0
        n2 = len(m2.split(",")) if m2 else 0
        n3 = len(m3.split(",")) if m3 else 0

        if n1:
            v1_nonempty += 1

        combined = n2 + n3

        if combined:
            v5_combined_nonempty += 1

        if combined == 1:
            v5_combined_singleton += 1

            if n1 == 0:
                v1_empty_v5_singleton += 1
            else:
                v1_nonempty_v5_singleton += 1

        elif combined > 1:
            v5_combined_multi += 1

            if n1 == 0:
                v1_empty_v5_multi += 1

print("=" * 90)
print("V1.1 vs COMBINED V5 (S2 + S3)")
print("=" * 90)

print(f"Total S1 rows                  : {total:,}")
print(f"V1.1 non-empty                 : {v1_nonempty:,}")
print(f"V5 combined non-empty         : {v5_combined_nonempty:,}")
print(f"V5 combined singleton         : {v5_combined_singleton:,}")
print(f"V5 combined multi-match       : {v5_combined_multi:,}")
print(f"V1 empty + V5 singleton       : {v1_empty_v5_singleton:,}")
print(f"V1 non-empty + V5 singleton   : {v1_nonempty_v5_singleton:,}")
print(f"V1 empty + V5 multi-match     : {v1_empty_v5_multi:,}")

==========================================================================================
V1.1 vs COMBINED V5 (S2 + S3)
==========================================================================================
Total S1 rows                  : 1,732,544
V1.1 non-empty                 : 912,910
V5 combined non-empty         : 894,839
V5 combined singleton         : 173,477
V5 combined multi-match       : 721,362
V1 empty + V5 singleton       : 91,330
V1 non-empty + V5 singleton   : 82,147
V1 empty + V5 multi-match     : 282,949

In [ ]:
import csv

paths = [
    "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv",
    "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv",
    "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv",
]

for path in paths:
    print("\n" + "=" * 90)
    print(path)

    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader)

    print(header)

==========================================================================================
/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv
['entity_id', 'business_name', 'business_address', 'country']

==========================================================================================
/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv
['entity_id', 'business_name', 'business_address', 'country']

==========================================================================================
/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv
['entity_id', 'business_name', 'business_address', 'country']

In [ ]:
import csv
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

V1_PATH = os.path.join(ROOT, "ml/V1_1_REPRODUCTION/matching_results.tsv")
S2_PATH = os.path.join(ROOT, "ml/V5_Final_Production_RAMSAFE/s2_results.tsv")
S3_PATH = os.path.join(ROOT, "ml/V5_Final_Production_RAMSAFE/s3_results.tsv")

S1_TEST_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source1.tsv"
S2_TEST_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source2.tsv"
S3_TEST_PATH = "/content/amazon_ml_challenge/student_resource/dataset/test/test_source3.tsv"

# ------------------------------------------------------------
# 1. Recover exactly the 91,330 baseline additions
# ------------------------------------------------------------

additions = {}

with open(V1_PATH, "r", encoding="utf-8", newline="") as f1, \
     open(S2_PATH, "r", encoding="utf-8", newline="") as f2, \
     open(S3_PATH, "r", encoding="utf-8", newline="") as f3:

    r1 = csv.DictReader(f1, delimiter="\t")
    r2 = csv.DictReader(f2, delimiter="\t")
    r3 = csv.DictReader(f3, delimiter="\t")

    for row1, row2, row3 in zip(r1, r2, r3):

        m1 = row1["matched_entity_ids"].strip()
        m2 = row2["matched_entity_ids"].strip()
        m3 = row3["matched_entity_ids"].strip()

        # Only V1-empty entities
        if m1:
            continue

        n2 = len(m2.split(",")) if m2 else 0
        n3 = len(m3.split(",")) if m3 else 0

        # Exactly one V5 match across S2 + S3
        if n2 + n3 != 1:
            continue

        s1_id = row1["source1_entity_id"]

        if n2 == 1:
            additions[s1_id] = ("S2", m2)
        else:
            additions[s1_id] = ("S3", m3)

print("=" * 90)
print("BASELINE ADDITIONS")
print("=" * 90)
print(f"Collected additions: {len(additions):,}")

# ------------------------------------------------------------
# 2. Read countries only for required S1 IDs
# ------------------------------------------------------------

s1_country = {}

with open(S1_TEST_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:
        sid = row["entity_id"]

        if sid in additions:
            s1_country[sid] = row["country"].strip().lower()

# ------------------------------------------------------------
# 3. Required S2 / S3 target IDs
# ------------------------------------------------------------

s2_targets = {
    matched_id
    for source_type, matched_id in additions.values()
    if source_type == "S2"
}

s3_targets = {
    matched_id
    for source_type, matched_id in additions.values()
    if source_type == "S3"
}

s2_country = {}
s3_country = {}

with open(S2_TEST_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:
        sid = row["entity_id"]

        if sid in s2_targets:
            s2_country[sid] = row["country"].strip().lower()

with open(S3_TEST_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:
        sid = row["entity_id"]

        if sid in s3_targets:
            s3_country[sid] = row["country"].strip().lower()

# ------------------------------------------------------------
# 4. Compare countries
# ------------------------------------------------------------

same_country = 0
cross_country = 0
missing_country = 0

cross_examples = []

for s1_id, (source_type, matched_id) in additions.items():

    c1 = s1_country.get(s1_id, "")

    if source_type == "S2":
        c2 = s2_country.get(matched_id, "")
    else:
        c2 = s3_country.get(matched_id, "")

    if not c1 or not c2:
        missing_country += 1
        continue

    if c1 == c2:
        same_country += 1
    else:
        cross_country += 1

        if len(cross_examples) < 20:
            cross_examples.append(
                (s1_id, source_type, matched_id, c1, c2)
            )

print("\n" + "=" * 90)
print("COUNTRY AUDIT — 91,330 BASELINE ADDITIONS")
print("=" * 90)

print(f"Same-country       : {same_country:,}")
print(f"Cross-country      : {cross_country:,}")
print(f"Missing country    : {missing_country:,}")

checked = same_country + cross_country

if checked:
    print(f"Cross-country rate : {100 * cross_country / checked:.4f}%")

print("\nCross-country examples:")
if cross_examples:
    for x in cross_examples:
        print(x)
else:
    print("NONE")

==========================================================================================
BASELINE ADDITIONS
==========================================================================================
Collected additions: 91,330

==========================================================================================
COUNTRY AUDIT — 91,330 BASELINE ADDITIONS
==========================================================================================
Same-country       : 91,330
Cross-country      : 0
Missing country    : 0
Cross-country rate : 0.0000%

Cross-country examples:
NONE

In [ ]:
import csv
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

V1_PATH = os.path.join(ROOT, "ml/V1_1_REPRODUCTION/matching_results.tsv")
S2_PATH = os.path.join(ROOT, "ml/V5_Final_Production_RAMSAFE/s2_results.tsv")
S3_PATH = os.path.join(ROOT, "ml/V5_Final_Production_RAMSAFE/s3_results.tsv")

s2_additions = 0
s3_additions = 0

with open(V1_PATH, "r", encoding="utf-8", newline="") as f1, \
     open(S2_PATH, "r", encoding="utf-8", newline="") as f2, \
     open(S3_PATH, "r", encoding="utf-8", newline="") as f3:

    r1 = csv.DictReader(f1, delimiter="\t")
    r2 = csv.DictReader(f2, delimiter="\t")
    r3 = csv.DictReader(f3, delimiter="\t")

    for row1, row2, row3 in zip(r1, r2, r3):

        if row1["matched_entity_ids"].strip():
            continue

        m2 = row2["matched_entity_ids"].strip()
        m3 = row3["matched_entity_ids"].strip()

        n2 = len(m2.split(",")) if m2 else 0
        n3 = len(m3.split(",")) if m3 else 0

        if n2 + n3 != 1:
            continue

        if n2 == 1:
            s2_additions += 1
        else:
            s3_additions += 1

print("=" * 70)
print("91,330 BASELINE ADDITIONS — SOURCE SPLIT")
print("=" * 70)

print(f"S2 additions : {s2_additions:,}")
print(f"S3 additions : {s3_additions:,}")
print(f"Total        : {s2_additions + s3_additions:,}")

print(f"S2 share     : {100*s2_additions/(s2_additions+s3_additions):.2f}%")
print(f"S3 share     : {100*s3_additions/(s2_additions+s3_additions):.2f}%")

======================================================================
91,330 BASELINE ADDITIONS — SOURCE SPLIT
======================================================================
S2 additions : 45,091
S3 additions : 46,239
Total        : 91,330
S2 share     : 49.37%
S3 share     : 50.63%

In [ ]:
import csv
import os
from collections import Counter

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

V1_PATH = os.path.join(ROOT, "ml/V1_1_REPRODUCTION/matching_results.tsv")
S2_PATH = os.path.join(ROOT, "ml/V5_Final_Production_RAMSAFE/s2_results.tsv")
S3_PATH = os.path.join(ROOT, "ml/V5_Final_Production_RAMSAFE/s3_results.tsv")

# candidate-count buckets
s2_buckets = Counter()
s3_buckets = Counter()

total_additions = 0

with open(V1_PATH, "r", encoding="utf-8", newline="") as f1, \
     open(S2_PATH, "r", encoding="utf-8", newline="") as f2, \
     open(S3_PATH, "r", encoding="utf-8", newline="") as f3:

    r1 = csv.DictReader(f1, delimiter="\t")
    r2 = csv.DictReader(f2, delimiter="\t")
    r3 = csv.DictReader(f3, delimiter="\t")

    for row1, row2, row3 in zip(r1, r2, r3):

        # Only V1-empty entities
        if row1["matched_entity_ids"].strip():
            continue

        m2 = row2["matched_entity_ids"].strip()
        m3 = row3["matched_entity_ids"].strip()

        n2 = len(m2.split(",")) if m2 else 0
        n3 = len(m3.split(",")) if m3 else 0

        # Exact 91,330 baseline additions
        if n2 + n3 != 1:
            continue

        total_additions += 1

        if n2 == 1:
            candidates = row2["candidate_entity_ids"].strip()
            count = len(candidates.split(",")) if candidates else 0
            s2_buckets[count] += 1

        else:
            candidates = row3["candidate_entity_ids"].strip()
            count = len(candidates.split(",")) if candidates else 0
            s3_buckets[count] += 1

print("=" * 90)
print("CANDIDATE AMBIGUITY — 91,330 BASELINE ADDITIONS")
print("=" * 90)

print(f"Total additions: {total_additions:,}")

def print_buckets(name, buckets):
    print("\n" + name)

    ranges = [
        ("1 candidate", lambda x: x == 1),
        ("2 candidates", lambda x: x == 2),
        ("3 candidates", lambda x: x == 3),
        ("4-5 candidates", lambda x: 4 <= x <= 5),
        ("6-10 candidates", lambda x: 6 <= x <= 10),
        ("11-20 candidates", lambda x: 11 <= x <= 20),
        ("21+ candidates", lambda x: x >= 21),
    ]

    total = sum(buckets.values())

    for label, fn in ranges:
        n = sum(v for k, v in buckets.items() if fn(k))
        print(f"{label:20s}: {n:8,} ({100*n/total:.2f}%)")

print_buckets("S2", s2_buckets)
print_buckets("S3", s3_buckets)

==========================================================================================
CANDIDATE AMBIGUITY — 91,330 BASELINE ADDITIONS
==========================================================================================
Total additions: 91,330

S2
1 candidate         :   23,964 (53.15%)
2 candidates        :    8,400 (18.63%)
3 candidates        :    3,179 (7.05%)
4-5 candidates      :    3,055 (6.78%)
6-10 candidates     :    3,093 (6.86%)
11-20 candidates    :    1,804 (4.00%)
21+ candidates      :    1,596 (3.54%)

S3
1 candidate         :   26,767 (57.89%)
2 candidates        :    6,938 (15.00%)
3 candidates        :    2,975 (6.43%)
4-5 candidates      :    3,819 (8.26%)
6-10 candidates     :    2,785 (6.02%)
11-20 candidates    :    1,573 (3.40%)
21+ candidates      :    1,382 (2.99%)

In [ ]:
import os

path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_threshold_predictions.csv"

print("Exists:", os.path.exists(path))
print("Size:", os.path.getsize(path) / (1024**2), "MB")

with open(path, "r", encoding="utf-8") as f:
    for i in range(10):
        line = f.readline()
        if not line:
            break
        print(line.rstrip()[:1000])

Exists: True
Size: 6.29425048828125e-05 MB
threshold,predicted_matches
0.55,4601
0.6,4581
0.65,4552
0.7,4527

In [ ]:
import csv
import os

GT_PATH = "/content/amazon_ml_challenge/student_resource/dataset/train/train_ground_truth.tsv"

print("=" * 80)
print("GROUND TRUTH HEADER")
print("=" * 80)

with open(GT_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.reader(f, delimiter="\t")
    header = next(reader)

print(header)

print("\nFirst 3 rows:")
with open(GT_PATH, "r", encoding="utf-8", newline="") as f:
    for i, line in enumerate(f):
        print(line.rstrip()[:1000])
        if i >= 2:
            break

================================================================================
GROUND TRUTH HEADER
================================================================================
['source1_entity_id', 'matched_entity_ids']

First 3 rows:
source1_entity_id	matched_entity_ids
S1-965667	S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
S1-55344266	S2-249013014,S2-197070651,S3-478195123,S3-384364074

In [ ]:
import csv
import random
import re
import unicodedata

TRAIN = "/content/amazon_ml_challenge/student_resource/dataset/train"

S1_PATH = f"{TRAIN}/train_source1.tsv"
S2_PATH = f"{TRAIN}/train_source2.tsv"
S3_PATH = f"{TRAIN}/train_source3.tsv"
GT_PATH = f"{TRAIN}/train_ground_truth.tsv"

SAMPLE_GT_LINKS = 20000
random.seed(42)

# ------------------------------------------------------------
# Same normalization family we used for V5.
# IMPORTANT: this is a PROXY because friend's normalize.py
# was not included.
# ------------------------------------------------------------

def normalize_proxy(x):
    if x is None:
        return ""

    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def make_keys(name, address, country):
    name = normalize_proxy(name)
    address = normalize_proxy(address)
    country = str(country).lower().strip()

    # Friend's 11 key structure
    name_first = name.split()[0] if name else ""
    address_tokens = address.split()
    address_first = address_tokens[0] if address_tokens else ""
    address_last = address_tokens[-1] if address_tokens else ""

    m = re.search(r"(\d+)", address)
    house_number = m.group(1) if m else ""

    remaining = re.sub(r"^\s*\d+\s*", "", address)
    street_prefix = remaining[:7]

    return {
        country + "|" + name[:5],
        country + "|" + name[:4],
        country + "|" + name[-5:],
        country + "|" + name_first,

        country + "|" + address[:15],
        country + "|" + address[:10],
        country + "|" + address[:5],
        country + "|" + address_first,
        country + "|" + address_last,

        country + "|" + house_number,
        country + "|" + house_number + "|" + street_prefix,
    }


# ------------------------------------------------------------
# 1. Sample genuine GT links
# ------------------------------------------------------------

gt_links = []

with open(GT_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:
        s1 = row["source1_entity_id"]
        matches = row["matched_entity_ids"].strip()

        if not matches:
            continue

        for mid in matches.split(","):
            gt_links.append((s1, mid))

random.shuffle(gt_links)
gt_links = gt_links[:SAMPLE_GT_LINKS]

print("=" * 90)
print("FRIEND BLOCKING RECALL TEST")
print("=" * 90)
print(f"Sample genuine links: {len(gt_links):,}")

# ------------------------------------------------------------
# 2. Determine which source each GT target belongs to
# ------------------------------------------------------------

target_ids = {mid for _, mid in gt_links}
s1_ids = {sid for sid, _ in gt_links}

s2_ids_needed = {x for x in target_ids if x.startswith("S2-")}
s3_ids_needed = {x for x in target_ids if x.startswith("S3-")}

# ------------------------------------------------------------
# 3. Retrieve only required records
# ------------------------------------------------------------

s1_rows = {}
s2_rows = {}
s3_rows = {}

with open(S1_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:
        if row["entity_id"] in s1_ids:
            s1_rows[row["entity_id"]] = row

with open(S2_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:
        if row["entity_id"] in s2_ids_needed:
            s2_rows[row["entity_id"]] = row

with open(S3_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:
        if row["entity_id"] in s3_ids_needed:
            s3_rows[row["entity_id"]] = row

print(f"S1 records retrieved: {len(s1_rows):,}")
print(f"S2 records retrieved: {len(s2_rows):,}")
print(f"S3 records retrieved: {len(s3_rows):,}")

# ------------------------------------------------------------
# 4. Test whether at least ONE friend blocking key matches
# ------------------------------------------------------------

recovered = 0
missed = 0

missed_examples = []

for s1_id, target_id in gt_links:

    s1 = s1_rows.get(s1_id)

    if target_id.startswith("S2-"):
        target = s2_rows.get(target_id)
    else:
        target = s3_rows.get(target_id)

    if not s1 or not target:
        continue

    k1 = make_keys(
        s1["business_name"],
        s1["business_address"],
        s1["country"]
    )

    k2 = make_keys(
        target["business_name"],
        target["business_address"],
        target["country"]
    )

    if k1.intersection(k2):
        recovered += 1
    else:
        missed += 1

        if len(missed_examples) < 10:
            missed_examples.append(
                (
                    s1_id,
                    target_id,
                    s1["business_name"],
                    target["business_name"],
                    s1["business_address"],
                    target["business_address"]
                )
            )

checked = recovered + missed

print("\n" + "=" * 90)
print("RESULT")
print("=" * 90)

print(f"Checked genuine links : {checked:,}")
print(f"Recovered by keys     : {recovered:,}")
print(f"Missed by keys        : {missed:,}")

if checked:
    print(f"Blocking recall       : {100 * recovered / checked:.2f}%")

print("\nFirst missed examples:")
for x in missed_examples:
    print(x)

==========================================================================================
FRIEND BLOCKING RECALL TEST
==========================================================================================
Sample genuine links: 20,000
S1 records retrieved: 19,913
S2 records retrieved: 9,736
S3 records retrieved: 10,264

==========================================================================================
RESULT
==========================================================================================
Checked genuine links : 20,000
Recovered by keys     : 19,546
Missed by keys        : 454
Blocking recall       : 97.73%

First missed examples:
('S1-136382020', 'S3-186577100', 'Sun Consulting Private Limited', 'ਸਨ ਕੰਸਲਟਿੰਗ ਪ੍ਰਾਈਵੇਟ ਲਿਮਟਿਡ', 'Bxviii/3726, Model Town Road, Ludhiana, Punjab', 'Plto 360 Bxviii/3726, Ludhiana, ਪੰਜਾਬ')
('S1-297757420', 'S3-960041409', 'Flexi India Public Limited', 'fipublic.com', 'G Floor, No 36, 6Th Block, Madhuvana Layout, Mysore, Karnataka', 'Plot 9-3 G Floor, Mysore, ಕರ್ನಾಟಕ')
('S1-625649085', 'S2-456745937', 'Mountain Dental Associates', 'Dental Mountain Ascsaocintes', 'Terre Haute, IN, 825 15th Street', '00825 15ND STREET, TERRE HAUTE, IN')
('S1-25915543', 'S2-45054347', 'Ishita International School Private Limited', 'Limited Ishita International Private Services', 'H.N. 38 Pooth Kalan Village, Sector- 20, Rohini, Delhi', '855 H.N. 38 POOTH KLAAN VILLAGE, ROHINI, DELHI, दिल्ली')
('S1-553166169', 'S3-494264090', 'Kalinga Traders Pvt Ltd', 'Shri Kalinga Traders Pvt', 'Property.No.55, 3Rd Floor, Saidtjlajab, Westend Marg, New Delhi, South West Delhi, Delhi', 'Hn 146/1 Property.no.55, South West Delhi, DL')
('S1-301741692', 'S3-417567329', 'Royal Developers Pvt Ltd', 'రాయల్ డెవలపర్స్ ప్రైవేట్ లిమిటెడ్', 'Dwarapudi, East Godavari, Vemulapalli, 5-2/1 Tula Sri Rangarao Colony, Andhra Pradesh', 'Tula Sri Rangarao Colony, Visakhapatnam Region, AP')
('S1-610452879', 'S3-404562038', 'Aditya Best Construction Private Limited', 'આદિત્ય બેસ્ટ કન્સ્ટ્રક્શન પ્રાઇવેટ લિમિટેડ', '204, L.G Complex, Opp. Sauras Hotel Near Sayaji Library, Navsari, Gujarat', 'No. 0054 204, Navsari, GJ')
('S1-993431338', 'S2-688583831', 'Indian Services Pvt Ltd', 'इंडियन सर्विसेज प्रा. लि.', 'Plot-54, L/G.F, Shop Patparganj Road Pandav Nagar Near Mother Dairy, Delhi, East Delhi, Delhi', 'BLOCK E-794 PLOT-54, L/G.F, SHOP PATPARGANJ ROAD PANDAV NAGAR NEAR MOTHER DAIRY, EAST DELHI, DELHI, दिल्ली')
('S1-701895362', 'S3-895815847', 'Johnson Cardiology LP', '([LLC]) Johnson Cardiology', '298 Benedict Avenue, Oak Ridge, TN', '296 Benedict Avenue, Oak Ridge, Tennessee')
('S1-288101456', 'S3-501261579', 'Freight Trading', 'Mr Freight Tráding', 'Block A, Office 1607 To 1612, 16Th Floor, Navratna Corporate Park, Ambli Bopal Road, Opp. Jayantilal Park, Ahmadabad City, Ahmedabad, Gujarat', '')

In [ ]:
import csv
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

S2_PATH = os.path.join(
    ROOT, "ml/V5_Final_Production_RAMSAFE/s2_results.tsv"
)

S3_PATH = os.path.join(
    ROOT, "ml/V5_Final_Production_RAMSAFE/s3_results.tsv"
)

# ------------------------------------------------------------
# Use the SAME 20,000 GT links from the previous cell
# ------------------------------------------------------------

target_map = {}

for s1_id, target_id in gt_links:
    target_map.setdefault(s1_id, set()).add(target_id)

found = set()

# ------------------------------------------------------------
# Scan V5 S2 candidates
# ------------------------------------------------------------

with open(S2_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:

        s1_id = row["source1_entity_id"]

        if s1_id not in target_map:
            continue

        candidates = row["candidate_entity_ids"].strip()

        if not candidates:
            continue

        candidate_set = set(candidates.split(","))

        for target_id in target_map[s1_id]:
            if target_id in candidate_set:
                found.add((s1_id, target_id))

# ------------------------------------------------------------
# Scan V5 S3 candidates
# ------------------------------------------------------------

with open(S3_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")

    for row in reader:

        s1_id = row["source1_entity_id"]

        if s1_id not in target_map:
            continue

        candidates = row["candidate_entity_ids"].strip()

        if not candidates:
            continue

        candidate_set = set(candidates.split(","))

        for target_id in target_map[s1_id]:
            if target_id in candidate_set:
                found.add((s1_id, target_id))

# ------------------------------------------------------------
# RESULT
# ------------------------------------------------------------

checked = len(gt_links)
recovered = len(found)
missed = checked - recovered

print("=" * 90)
print("V5 CANDIDATE RECALL — SAME 20,000 GENUINE LINKS")
print("=" * 90)

print(f"Checked genuine links : {checked:,}")
print(f"Recovered by V5      : {recovered:,}")
print(f"Missed by V5         : {missed:,}")

print(f"\nV5 candidate recall  : {100 * recovered / checked:.2f}%")
print(f"Friend proxy recall  : 97.73%")
print(f"Difference           : {100 * recovered / checked - 97.73:.2f} percentage points")

==========================================================================================
V5 CANDIDATE RECALL — SAME 20,000 GENUINE LINKS
==========================================================================================
Checked genuine links : 20,000
Recovered by V5      : 0
Missed by V5         : 20,000

V5 candidate recall  : 0.00%
Friend proxy recall  : 97.73%
Difference           : -97.73 percentage points

In [ ]:
import csv
import os

ROOT = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

S2_PATH = os.path.join(
    ROOT, "ml/V5_Final_Production_RAMSAFE/s2_results.tsv"
)

S3_PATH = os.path.join(
    ROOT, "ml/V5_Final_Production_RAMSAFE/s3_results.tsv"
)

print("=" * 100)
print("V5 CANDIDATE FORMAT DIAGNOSTIC")
print("=" * 100)

# Show first 5 sampled GT links
print("\nSample GT links:")
for x in gt_links[:5]:
    print(x)

# Pick the first S1 and inspect its V5 rows
test_s1 = gt_links[0][0]
test_targets = {
    target for s1, target in gt_links
    if s1 == test_s1
}

print("\nTesting S1:", test_s1)
print("Genuine targets:", test_targets)

for path, source in [(S2_PATH, "S2"), (S3_PATH, "S3")]:

    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")

        for row in reader:

            if row["source1_entity_id"] != test_s1:
                continue

            candidates = row["candidate_entity_ids"].strip()
            matches = row["matched_entity_ids"].strip()

            print("\nSOURCE:", source)
            print("S1:", row["source1_entity_id"])
            print("Candidates:", candidates[:2000])
            print("Matched:", matches)

            candidate_list = candidates.split(",") if candidates else []

            print("\nTarget membership:")
            for target in test_targets:
                print(
                    target,
                    "FOUND" if target in candidate_list else "NOT FOUND"
                )

            break

====================================================================================================
V5 CANDIDATE FORMAT DIAGNOSTIC
====================================================================================================

Sample GT links:
('S1-954682379', 'S3-986958728')
('S1-388440835', 'S2-999242929')
('S1-582018742', 'S2-901838218')
('S1-661359922', 'S2-378727203')
('S1-668828510', 'S3-159115451')

Testing S1: S1-954682379
Genuine targets: {'S3-986958728'}

In [ ]:
import csv
import re
import unicodedata
from collections import Counter

TRAIN = "/content/amazon_ml_challenge/student_resource/dataset/train"

S1_PATH = f"{TRAIN}/train_source1.tsv"
S2_PATH = f"{TRAIN}/train_source2.tsv"
S3_PATH = f"{TRAIN}/train_source3.tsv"

# ------------------------------------------------------------
# Helpers — V5 normalization / blocker logic
# ------------------------------------------------------------

def norm(x):
    if x is None:
        return ""

    x = str(x).lower().strip()
    x = unicodedata.normalize("NFKC", x)

    replacements = {
        "&": " and ",
        "street": " st ",
        "road": " rd ",
        "avenue": " ave ",
        "drive": " dr ",
        "boulevard": " blvd ",
        "highway": " hwy ",
        "lane": " ln ",
        "parkway": " pkwy ",
        "place": " pl ",
        "suite": " ste "
    }

    for a, b in replacements.items():
        x = x.replace(a, b)

    x = re.sub(r"[^\w\s]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def tokens(x):
    return set(x.split()) if x else set()


def numbers(x):
    return set(re.findall(r"\d+", x)) if x else set()


def sim(a, b):
    # Standard SequenceMatcher proxy for the V5 similarity feature.
    from difflib import SequenceMatcher
    return SequenceMatcher(None, a, b).ratio()


# ------------------------------------------------------------
# SAME 20,000 GT LINKS FROM PREVIOUS CELL
# ------------------------------------------------------------

sample_links = gt_links[:20000]

target_s1 = {s1 for s1, _ in sample_links}
target_s2 = {t for _, t in sample_links if t.startswith("S2-")}
target_s3 = {t for _, t in sample_links if t.startswith("S3-")}

# ------------------------------------------------------------
# Retrieve only the required training records
# ------------------------------------------------------------

s1_rows = {}
s2_rows = {}
s3_rows = {}

with open(S1_PATH, "r", encoding="utf-8", newline="") as f:
    r = csv.DictReader(f, delimiter="\t")
    for row in r:
        if row["entity_id"] in target_s1:
            s1_rows[row["entity_id"]] = row

with open(S2_PATH, "r", encoding="utf-8", newline="") as f:
    r = csv.DictReader(f, delimiter="\t")
    for row in r:
        if row["entity_id"] in target_s2:
            s2_rows[row["entity_id"]] = row

with open(S3_PATH, "r", encoding="utf-8", newline="") as f:
    r = csv.DictReader(f, delimiter="\t")
    for row in r:
        if row["entity_id"] in target_s3:
            s3_rows[row["entity_id"]] = row

print("=" * 90)
print("V5 BLOCKER RECALL — SAME TRAINING LINKS")
print("=" * 90)

print(f"S1 records: {len(s1_rows):,}")
print(f"S2 targets: {len(s2_rows):,}")
print(f"S3 targets: {len(s3_rows):,}")

# ------------------------------------------------------------
# Normalize sampled records
# ------------------------------------------------------------

def prepare(row):
    name = norm(row["business_name"])
    address = norm(row["business_address"])

    return {
        "name": name,
        "address": address,
        "country": row["country"].lower().strip(),
        "name_tokens": tokens(name),
        "address_tokens": tokens(address),
        "numbers": numbers(address),
    }


s1_p = {k: prepare(v) for k, v in s1_rows.items()}
s2_p = {k: prepare(v) for k, v in s2_rows.items()}
s3_p = {k: prepare(v) for k, v in s3_rows.items()}

# ------------------------------------------------------------
# Collect only tokens that occur in the sampled TARGET records.
# Then scan S2/S3 to obtain their global frequencies.
# This avoids building a giant 10M-row token dictionary.
# ------------------------------------------------------------

interesting_name_tokens = set()
interesting_addr_tokens = set()

for row in list(s2_p.values()) + list(s3_p.values()):
    interesting_name_tokens.update(row["name_tokens"])
    interesting_addr_tokens.update(row["address_tokens"])

name_freq = Counter()
addr_freq = Counter()

print("\nScanning training S2/S3 for frequencies of sampled target tokens...")

for path in [S2_PATH, S3_PATH]:

    with open(path, "r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f, delimiter="\t")

        for row in r:

            n = norm(row["business_name"])
            a = norm(row["business_address"])

            for t in tokens(n):
                if t in interesting_name_tokens:
                    name_freq[t] += 1

            for t in tokens(a):
                if t in interesting_addr_tokens:
                    addr_freq[t] += 1

print("Frequency scan complete.")

# ------------------------------------------------------------
# V5 pair eligibility
# ------------------------------------------------------------

def v5_candidate(s1, target):

    # V5 high-recall conditions
    exact_name = (
        s1["name"] != "" and
        s1["name"] == target["name"]
    )

    exact_address = (
        s1["address"] != "" and
        s1["address"] == target["address"]
    )

    shared_name = s1["name_tokens"] & target["name_tokens"]
    shared_addr = s1["address_tokens"] & target["address_tokens"]

    shared_name_count = len(shared_name)
    shared_addr_count = len(shared_addr)

    rare_name_shared = sum(
        1 for t in shared_name
        if name_freq[t] <= 500
    )

    rare_addr_shared = sum(
        1 for t in shared_addr
        if addr_freq[t] <= 500
    )

    # Candidate generation / blocking
    blocked = (
        exact_name
        or exact_address
        or (
            rare_name_shared >= 2
        )
        or (
            rare_addr_shared >= 2
        )
    )

    if not blocked:
        return False

    # V5 similarity filtering
    name_sim = sim(s1["name"], target["name"])
    addr_sim = sim(s1["address"], target["address"])

    passes_similarity = (
        exact_name
        or exact_address
        or (
            shared_name_count >= 2
            and name_sim >= 0.60
        )
        or (
            shared_addr_count >= 3
        )
        or (
            shared_addr_count >= 2
            and addr_sim >= 0.30
        )
    )

    return passes_similarity


# ------------------------------------------------------------
# Evaluate same 20,000 genuine links
# ------------------------------------------------------------

recovered = 0
missed = 0
missed_examples = []

for s1_id, target_id in sample_links:

    s1 = s1_p.get(s1_id)

    if target_id.startswith("S2-"):
        target = s2_p.get(target_id)
    else:
        target = s3_p.get(target_id)

    if s1 is None or target is None:
        continue

    if v5_candidate(s1, target):
        recovered += 1
    else:
        missed += 1

        if len(missed_examples) < 10:
            missed_examples.append(
                (
                    s1_id,
                    target_id,
                    s1["name"],
                    target["name"],
                    s1["address"],
                    target["address"]
                )
            )

checked = recovered + missed

print("\n" + "=" * 90)
print("V5 RESULT")
print("=" * 90)

print(f"Checked genuine links : {checked:,}")
print(f"Recovered by V5      : {recovered:,}")
print(f"Missed by V5         : {missed:,}")

if checked:
    print(f"V5 blocker recall    : {100 * recovered / checked:.2f}%")

print("\nFriend raw key recall : 97.73%")

print("\nFirst V5 misses:")
for x in missed_examples:
    print(x)

==========================================================================================
V5 BLOCKER RECALL — SAME TRAINING LINKS
==========================================================================================
S1 records: 19,913
S2 targets: 9,736
S3 targets: 10,264

Scanning training S2/S3 for frequencies of sampled target tokens...

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

matches = []

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.zip') and 'Trojans' in file:
            matches.append(os.path.join(root, file))

print("Found files:")
for x in matches:
    print(x)

Found files:

In [4]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print("Folder exists:", os.path.exists(base))

if os.path.exists(base):
    print("\nContents:")
    for item in os.listdir(base):
        print(item)

Folder exists: True

Contents:
notebooks
data
ml
ML_AUDIT
SUBMISSION_BASELINE_0444
SUBMISSION_A_HYBRID
SUBMISSION_B_FRIEND

In [5]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/SUBMISSION_B_FRIEND"

print("Folder exists:", os.path.exists(base))

for root, dirs, files in os.walk(base):
    level = root.replace(base, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        path = os.path.join(root, file)
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"{indent}    {file}  ({size_mb:.2f} MB)")

Folder exists: True
SUBMISSION_B_FRIEND/
    block_indexes/

In [6]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/SUBMISSION_B_FRIEND"

print("DIRECT FILES:")
for item in os.listdir(base):
    path = os.path.join(base, item)
    if os.path.isfile(path):
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"  {item}  -->  {size_mb:.2f} MB")

print("\nDIRECT FOLDERS:")
for item in os.listdir(base):
    path = os.path.join(base, item)
    if os.path.isdir(path):
        print(f"  {item}/")

DIRECT FILES:

DIRECT FOLDERS:
  block_indexes/

In [7]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

targets = {
    "matching_results.tsv",
    "matching_results_B.tsv",
    "candidate_pairs.tsv",
    "candidate_pairs_B.tsv",
    "Tech Trojans_submission.zip",
    "v5_model.cbm",
    "pipeline.py",
    "Documentation_template.md"
}

print("Searching entire Amazon-ML-Challenge-2026 folder...\n")

found = []

for root, dirs, files in os.walk(base):
    # Skip block indexes because it contains many files
    dirs[:] = [d for d in dirs if d != "block_indexes"]

    for file in files:
        if file in targets:
            path = os.path.join(root, file)
            size_mb = os.path.getsize(path) / (1024 * 1024)
            found.append((file, path, size_mb))

if found:
    for file, path, size in found:
        print(f"{file}")
        print(f"  {size:.2f} MB")
        print(f"  {path}\n")
else:
    print("NO TARGET FILES FOUND")

Searching entire Amazon-ML-Challenge-2026 folder...

v5_model.cbm
  1.41 MB
  /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm

matching_results.tsv
  43.27 MB
  /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/matching_results.tsv

candidate_pairs.tsv
  43.27 MB
  /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V1_1_REPRODUCTION/candidate_pairs.tsv

In [8]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

print("Searching for B / rescue / final submission files...\n")

for root, dirs, files in os.walk(base):
    # Skip huge block index folders
    dirs[:] = [d for d in dirs if d != "block_indexes"]

    for file in files:
        name = file.lower()

        if (
            "rescue" in name
            or "submission_b" in name
            or "final_submission" in name
            or "matching_results_b" in name
            or "candidate_pairs_b" in name
        ):
            path = os.path.join(root, file)
            size_mb = os.path.getsize(path) / (1024 * 1024)

            print(f"{file}")
            print(f"  Size: {size_mb:.2f} MB")
            print(f"  Path: {path}\n")

Searching for B / rescue / final submission files...

In [9]:
import os

print("Checking current Colab runtime...\n")

for name in [
    "matching_results.tsv",
    "matching_results_B.tsv",
    "candidate_pairs.tsv",
    "candidate_pairs_B.tsv",
    "Tech Trojans_submission.zip"
]:
    path = "/content/" + name

    if os.path.exists(path):
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"FOUND: {path}")
        print(f"Size: {size_mb:.2f} MB\n")
    else:
        print(f"Not found: {path}")

Checking current Colab runtime...

Not found: /content/matching_results.tsv
Not found: /content/matching_results_B.tsv
Not found: /content/candidate_pairs.tsv
Not found: /content/candidate_pairs_B.tsv
Not found: /content/Tech Trojans_submission.zip

In [10]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

targets = [
    "pipeline.py",
    "README.md",
    "requirements.txt",
    "Documentation_template.md"
]

print("Searching for code/documentation...\n")

for root, dirs, files in os.walk(base):
    dirs[:] = [d for d in dirs if d != "block_indexes"]

    for file in files:
        if file in targets:
            path = os.path.join(root, file)
            size_kb = os.path.getsize(path) / 1024
            print(f"{file}")
            print(f"  {size_kb:.1f} KB")
            print(f"  {path}\n")

Searching for code/documentation...

In [11]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026"

for folder in [
    "ml",
    "notebooks",
    "ML_AUDIT",
    "SUBMISSION_A_HYBRID"
]:
    path = os.path.join(base, folder)

    print("\n" + "="*60)
    print(folder)
    print("="*60)

    if not os.path.exists(path):
        print("NOT FOUND")
        continue

    for item in os.listdir(path):
        p = os.path.join(path, item)

        if os.path.isfile(p):
            size = os.path.getsize(p)/(1024*1024)
            print(f"FILE   {item}   ({size:.2f} MB)")
        else:
            print(f"FOLDER {item}/")

============================================================
ml
============================================================
FILE   ml_features_v3_1000.pkl   (31.09 MB)
FILE   catboost_v1_v3_1000.cbm   (0.83 MB)
FILE   V5_ML_Final-20260925T182640Z-1-001.zip   (5.23 MB)
FOLDER V5_ML_Final/
FOLDER V5_full_indexes/
FOLDER V5_Final_Inference/
FOLDER V5_Final_Production/
FOLDER V5_Final_Production_RAMSAFE/
FOLDER V1_1_REPRODUCTION/
FOLDER V5_Final_Validation/
FOLDER V5_SUBMISSION/

============================================================
notebooks
============================================================
FILE   Amazon_ML_Challenge_2026.ipynb   (2.59 MB)

============================================================
ML_AUDIT
============================================================
FOLDER Submission_A_Planning/

============================================================
SUBMISSION_A_HYBRID
============================================================
FOLDER block_indexes/
FILE   singleton_candidates_combined500.tsv   (6.35 MB)

In [12]:
import os

base = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml"

targets = [
    "pipeline.py",
    "README.md",
    "requirements.txt",
    "v5_model.cbm",
    "matching_results.tsv",
    "candidate_pairs.tsv",
    "matching_results_B.tsv",
    "candidate_pairs_B.tsv",
    "Documentation_template.md"
]

print("Searching V5 folders...\n")

for root, dirs, files in os.walk(base):

    # Don't search huge index folders
    dirs[:] = [
        d for d in dirs
        if d not in ["V5_full_indexes", "block_indexes"]
    ]

    # Only inspect V5-related folders
    if not any(x in root for x in [
        "V5_ML_Final",
        "V5_Final_Inference",
        "V5_Final_Production",
        "V5_Final_Production_RAMSAFE",
        "V5_Final_Validation",
        "V5_SUBMISSION"
    ]):
        continue

    for file in files:
        if file in targets:
            path = os.path.join(root, file)
            size_mb = os.path.getsize(path) / (1024 * 1024)

            print(f"FOUND: {file}")
            print(f"Size: {size_mb:.2f} MB")
            print(f"Path: {path}\n")

Searching V5 folders...

FOUND: v5_model.cbm
Size: 1.41 MB
Path: /content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final/V5_ML_Final/v5_model.cbm

In [13]:
import zipfile
import os

zip_path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final-20260925T182640Z-1-001.zip"

print("ZIP exists:", os.path.exists(zip_path))

with zipfile.ZipFile(zip_path, "r") as z:
    print("\nFILES INSIDE ZIP:\n")
    for name in z.namelist():
        print(name)

ZIP exists: True

FILES INSIDE ZIP:

V5_ML_Final/v5_threshold_predictions.csv
V5_ML_Final/v5_inference.py
V5_ML_Final/v5_feature_list.txt
V5_ML_Final/V5_final_report.txt
V5_ML_Final/v5_model.cbm
V5_ML_Final/ml_features_v3_1000.pkl

In [14]:
import zipfile
import os

zip_path = "/content/drive/MyDrive/Amazon-ML-Challenge-2026/ml/V5_ML_Final-20260925T182640Z-1-001.zip"

extract_path = "/content/V5_GITHUB_FILES"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_path)

print("Extracted successfully.")

for root, dirs, files in os.walk(extract_path):
    for file in files:
        path = os.path.join(root, file)
        size_mb = os.path.getsize(path) / (1024*1024)
        print(f"{path}  ({size_mb:.2f} MB)")

Extracted successfully.
/content/V5_GITHUB_FILES/V5_ML_Final/v5_threshold_predictions.csv  (0.00 MB)
/content/V5_GITHUB_FILES/V5_ML_Final/v5_feature_list.txt  (0.00 MB)
/content/V5_GITHUB_FILES/V5_ML_Final/ml_features_v3_1000.pkl  (31.09 MB)
/content/V5_GITHUB_FILES/V5_ML_Final/V5_final_report.txt  (0.00 MB)
/content/V5_GITHUB_FILES/V5_ML_Final/v5_inference.py  (0.00 MB)
/content/V5_GITHUB_FILES/V5_ML_Final/v5_model.cbm  (1.41 MB)

In [15]:
%cd /content

!git clone https://github.com/YOUR_GITHUB_USERNAME/Amazon_ML_Challenge_2026.git

/content
Cloning into 'Amazon_ML_Challenge_2026'...
fatal: could not read Username for 'https://github.com': No such device or address

In [16]:
import getpass

token = getpass.getpass("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 ")

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 ··········

In [17]:
username = "mhakashvarma"

In [18]:
%cd /content

!git clone https://{username}:{token}@github.com/{username}/Amazon_ML_Challenge_2026.git

/content
Cloning into 'Amazon_ML_Challenge_2026'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), done.
Resolving deltas: 100% (1/1), done.

In [19]:
%cd /content/Amazon_ML_Challenge_2026
!git status

/content/Amazon_ML_Challenge_2026
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [20]:
import os
import shutil

repo = "/content/Amazon_ML_Challenge_2026"
src = "/content/V5_GITHUB_FILES/V5_ML_Final"

# Create project folder
dest = os.path.join(repo, "V5_ML_Final")
os.makedirs(dest, exist_ok=True)

# Files we want in GitHub
files_to_copy = [
    "v5_inference.py",
    "v5_feature_list.txt",
    "v5_model.cbm",
    "V5_final_report.txt"
]

for file in files_to_copy:
    source = os.path.join(src, file)
    target = os.path.join(dest, file)

    shutil.copy2(source, target)
    print("Copied:", file)

print("\nDone.")

Copied: v5_inference.py
Copied: v5_feature_list.txt
Copied: v5_model.cbm
Copied: V5_final_report.txt

Done.